### ISSUE TITLE
build-marist-s390x-rhel-7.3 unable to resolve host

### ISSUE THREAD

**Issue by gdams** [AdoptOpenJDK/openjdk-infrastructure#1]
I am having issues using `wget` or `curl` on this machine. This is also preventing me from being able to connect it to jenkins

```bash
➜  ~ ssh linux1@148.100.5.162
[linux1@adoptopenjdk ~]$ wget https://google.com
--2017-06-26 04:02:53--  https://google.com/
Resolving google.com (google.com)... failed: Connection refused.
wget: unable to resolve host address ‘google.com’
[linux1@adoptopenjdk ~]$ 
```
CC @bblondin @AdoptOpenJDK/getopenjdk

**Comment by bblondin** [comment]
wget is fine... there was a permission issue on /etc/resolv.conf where by non-root users were unable to read the file. Thus DNS would not resolve.

I have added read permission for 'other' group on  /etc/resolv.conf

**Comment by tellison** [comment]
I don't see a `rhel_7_s390x.yml` playbook, so I'm curious - where was this fixed?

**Comment by bblondin** [comment]
@tellison 
This was fixed on the localhost. 
# chmod o+r /etc/resolv.conf

**Comment by tellison** [comment]
This needs to be added to an Ansible script, because these images may be discarded and recreated.  Without a simple way to reconfigure the machine we'll end up hitting the same problem again.

**Comment by bblondin** [comment]
Yes we do need a playbook for this OS/arch
however it is very odd that the /etc/resolv.conf is not readable by all users. The *nix default is to allow this.
