### ISSUE TITLE
Install JDK8 on build/test machines to support latest Jenkins version

### ISSUE THREAD

**Issue by tellison** [AdoptOpenJDK/openjdk-infrastructure#10]
The new version of Jenkins requires JDK8.  Our nodes currently have JDK7, so need to be upgraded (via Ansible?) to install the later JDK before upgrading Jenkins.

Consider running AdoptOpenJDK builds of JDK8 on each node?

**Comment by karianna** [comment]
Need to make sure that this JDK is separate from the Java 7 boot JDK we'd be using for the builds.  Should be possible though..

**Comment by gdams** [comment]
Assigning to @bblondin. Can you check which machines do and don't already have java 8?

**Comment by bblondin** [comment]
Most systems already had Java 8 on them. Installed Java 8 on those there were missing.


Hostname: | IP Address: | Default Java on Path | Java 8 if not Default:
-- | -- | -- | --
build-1and1-win2008r2-1 | 109.228.48.187 | java version 1.7.0_80 | /cygdrive/c/Program Files/Java/jre1.8.0_60/bin/java.exe
build-joyent-x64-freebsd-11-1 | 165.225.138.105 | openjdk 1.8.0_131 |  
build-joyent-x64-smartOS-14-1 | 165.225.138.202 | openjdk version 1.8.0_102-internal |  
build-linaro-armv8-centos7-1 | 64.28.99.122 | openjdk 1.8.0_131 |  
build-linaro-armv8-centos7-2 | 192.168.1.14 | openjdk 1.8.0_131 |  
build-macstadium-macos1010-1 | 207.254.50.138 | java version 1.8.0_131 |  
build-macstadium-macos1010-2 | 208.83.1.242 | java version 1.8.0_131 |  
build-marist-s390x-rhel-6 | 148.100.110.55 | java version 1.5.0 | /opt/java8/bin/java
build-marist-s390x-rhel-7.3 | 148.100.5.162 | openjdk version 1.8.0_111 |  
build-marist-s390x-sles-12 | 148.100.110.56 | java version 1.7.0_131 | /opt/java8/bin/java
build-marist-s390x-ubuntu-16.04 | 148.100.33.147 | openjdk 1.8.0_131 |  
build-osuosl-ppc64-aix-71-1 | 140.211.9.10 | java version 1.8.0 |  
build-osuosl-ppc64-aix-71-2 | 140.211.9.12 | java version 1.8.0 |  
build-osuosl-ppc64le-centos-7.2 | 140.211.168.138 | openjdk 1.8.0_131 |  
build-osuosl-ppc64le-fedora-24-1 | 140.211.168.134 | openjdk 1.8.0_131 |  
build-osuosl-ppc64le-fedora-24-2 | 140.211.168.52 | openjdk 1.8.0_131 |  
build-osuosl-ppc64le-ubuntu-16.10 | 140.211.168.135 | openjdk 1.8.0_131 |  
build-packet-armv8-ubuntu-16.04 | 147.75.111.14 | openjdk 1.8.0_131 |  
build-packet-x64-ubuntu-16 | 147.75.205.223 | openjdk 1.8.0_131 |  
build-scaleway-armv7-ubuntu16.04-1 | 212.47.233.28 | openjdk 1.8.0_131 |  
build-scaleway-armv7-ubuntu16.04-2 | 212.47.246.7 | openjdk 1.8.0_131 |  
build-scaleway-x64-ubuntu-16.04-1 | 163.172.174.45 | openjdk 1.8.0_131 |  
build-scaleway-x64-ubuntu-16.04-2 | 51.15.46.107 | openjdk 1.8.0_131 |  
ci.adoptopenjdk.net | 78.47.239.97 | openjdk 1.8.0_131 |  
test-macincloud-macos1010-1 | 74.80.250.151 | java version 1.8.0_131 |  
test-macincloud-macos1010-2 | 74.80.250.173 | java version 1.8.0_131 |  
test-packet-x64-ubuntu-16.04-1 | 147.75.204.239 | openjdk 1.8.0_131 |  
test-packet-x64-windows-2012r2-1 | 147.75.101.30 | java version 1.8.0_131 |  
test-scaleway-x64-ubuntu-16.04-1 | 51.15.76.107 | openjdk 1.8.0_131 |  
Nagios Server | 78.47.239.96 | openjdk 1.8.0_131 |  
ansible.adoptopenjdk.net | 35.177.240.157 | openjdk 1.8.0_131 |  
openjdk-api-server | 147.75.204.225 | openjdk 1.8.0_131 |  
keybox.adoptopenjdk.net | 147.75.205.63 | openjdk 1.8.0_131 |

**Comment by gdams** [comment]
@bblondin do you reckon we are good to update jenkins to the new version then?

**Comment by gdams** [comment]
upgraded jenkins, let's see how it goes this time
