### ISSUE TITLE
Ensure JDK13 is on  all build machines for bootstrapping JDK14

### ISSUE THREAD

**Issue by sxa** [AdoptOpenJDK/openjdk-infrastructure#1001]
Updates made in the playbooks but JDK13 is not yet deployed on many of the machines (which is preventing many of the builds in https://ci.adoptopenjdk.net/view/Tooling/job/JavaFutures/ from working (fixing that will just require execution on the two machines that are being used by that job but it needs to be done everywhere.

**Comment by sxa555** [comment]
Added to both machines used for building the [JavaFutures](https://ci.adoptopenjdk.net/view/Tooling/job/JavaFutures/) codebases for now, which should resolve the immediate problem.

**Comment by sxa** [comment]
Now that we are building JDK head which is JDK15 we should also install a JDK14 boot JDK on each build machine

**Comment by Willsparker** [comment]
From the machines I have access to:

| Build Machine                     | JDK13 | JDK14 |
|-----------------------------------|-------|-------|
| build-azure-win2012r2-x64-1       | Y     | N     |
| build-azure-win2012r2-x64-2       | Y     | N     |
| build-digitalocean-centos69-x64-1 | Y     | N     |
| build-digitalocean-centos69-x64-2 | N     | N     |
| build-osuosl-centos74-ppc64le-1   | N     | N     |
| build-osuosl-centos74-ppc64le-2   | Y     | N     |
| build-packet-centos74-armv8-1     | N     | N     |
| build-softlayer-centos6-x64-1     | Y     | N     |
| build-softlayer-win2012r2-x64-1   | N     | N     |
| build-softlayer-win2012r2-x64-2 *  | N     | N     |

* also doesn't have JDK10 on it.
I'll get to work putting them on these machines 👍

**Comment by sxa** [comment]
> @sxa What machines are left, and can I get access to them? :-)

You tell me - you've been updating the inventories recently!

Also bear in mind that the appropriate `JDK*_BOOT_DIR` definitions in jenkins for each machine will need updated to point to the install location

**Comment by Willsparker** [comment]
I've updated the `JDK*_BOOT_DIR` variables for each machine I've done :-) 
Here's a list of machines at `ci.adoptopenjdk.net` that I haven't been able to access to check if they have JDK13/14 on them.
```
build-godaddy-rhel7-x64-1 
build-inspira-solaris10u11-sparcv9-1 (D)(Not sure how to ping)
build-inspira-solaris10u11-sparcv9-2		
build-linaro-centos74-armv8-1 (D)		
build-linaro-centos74-armv8-2 (D)		
build-linaro-centos76-armv8-2 (D) (P)	
build-macstadium-macos1010-x64-1	
build-macstadium-macos1012-x64-1
build-macstadium-macos1014-x64-1
build-macstadium-macos1014-x64-2
build-marist-rhel77-s390x-1			
build-marist-rhel77-s390x-2
build-marist-ubuntu1604-s390x-1		
build-marist-ubuntu1604-s390x-2 (D)(P)		
build-marist-ubuntu1604-s390x-3 (D)(P)	
build-marist-zOS-s390x-1 (D)			
build-marist-zOS-s390x-2 (D)			
build-osuosl-aix71-ppc64-1
build-osuosl-aix71-ppc64-2
build-packet-ubuntu1804-armv8l-1		
build-scaleway-ubuntu1604-armv7-1		
build-scaleway-ubuntu1604-x64-1			
build-siteox-solaris10u9-x64-1	
build-spearhead-freebsd12-x64-1	
```
In the list above, `(D)` means disconnected from Jenkins, `(P)` means I'm unable to ping them with the IP address listed in `inventory.yml`. In the cases (of which I've noted down) that the machine isn't listed in `inventory.yml`, I took the IP address from the Configure tab at `ci.adoptopenjdk.net`.

**Comment by sxa** [comment]
Running the following pipelines to verify whether there are any problems:
- https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk15-pipeline/120/
- https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk14-pipeline/173/

**Comment by sxa** [comment]
Marked several in the table above as `[OK]` which should now let you in Will!

**Comment by sxa** [comment]
NOTE: We've just start building JDK16 so perhaps we should add JDK15 onto this list of installs too now :-D

**Comment by Willsparker** [comment]
Will do :-) I'll go back and put it on the machines I've already done. How do I get JDK15 on there..?

**Comment by sxa** [comment]
Hmmm actually let's leave JDK15 for now until it's GA

**Comment by Willsparker** [comment]
AH well.... I've put jdk-15+27 on a handful of machines before I saw that comment:
```
build-azure-win2012r2-x64-1
build-azure-win2012r2-x64-2
build-osuosl-centos74-ppc64le-1
build-osuosl-centos74-ppc64le-2
build-packet-centos74-armv8-1
build-softlayer-win2012r2-x64-1
build-softlayer-win2012r2-x64-2
build-godaddy-rhel7-x64-1
build-scaleway-ubuntu1604-x64-1
```

**Comment by Willsparker** [comment]
Unfortunately, I'm still getting issues on the machines you've said I've got access to when I `ssh root@<IP>`
```
build-linaro-centos76-armv8-2. - Network is unreachable
build-marist-rhel77-s390x-1.  - Permission denied (publickey)
build-marist-rhel77-s390x-2.  - Permission denied (publickey)
build-marist-ubuntu1604-s390x-1 - Permission denied (publickey)
build-osuosl-aix71-ppc64-1 - Asks for password to root
build-osuosl-aix71-ppc64-2 - Asks for password to root
build-packet-ubuntu1804-armv8l-1 - Permission denied (publickey)
```

**Comment by Haroon-Khel** [comment]
Any progress on this?

**Comment by sxa** [comment]
Fair question ... For some reason @Willsparker's key does not appear to be on some of those systems. Will try and remember to fix tomorrow

**Comment by Willsparker** [comment]
I've got access to the superuser, so I'll re-look at it once I've got a bit of spare time. (@sxa Keep in mind I've had a laptop change since I last looked at this :-) )

**Comment by sxa** [comment]
All done other than the Packet and Linaro machines (neither of which should need the update). Please re-opn if there are any further issues.
