### ISSUE TITLE
s390x Machine Out Of Space

### ISSUE THREAD

**Issue by M-Davies** [AdoptOpenJDK/openjdk-infrastructure#1019]
`build-marist-rhel74-s390x-1` seems to have hit its storage capacity on ci.adoptopenjdk

https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-linux-s390x-hotspot/335/console

Console Output (in case the link above doesn't work): [s390x_outofspace.txt](https://github.com/AdoptOpenJDK/openjdk-build/files/3904890/s390x_outofspace.txt)

**Comment by sxa555** [comment]
`/var/tmp` was full of a temporary `yum-nagios` directory. Cleared that, ran `yum update`, failed, manually updated the three large java packages on the machine, then cleaned up the packages and did a `yum update` again as perr the crontab and it's now happy again.

**Comment by M-Davies** [comment]
@sxa555 it looks like `build-marist-rhel74-s390x-2` has also run out of space 
- https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-linux-s390x-hotspot/351/console
- [output.txt](https://github.com/AdoptOpenJDK/openjdk-infrastructure/files/3938957/output.txt)

**Comment by sxa555** [comment]
`/var/tmp/yum-nagious` had blown up again. Removed. It's also locking the RPM database which isn't helpful.

Fortunately these machines will soon be replaced so I'm not going to spend time looking for a full fux.

**Comment by M-Davies** [comment]
@sxa555 `build-marist-rhel74-s390x-2` ran out of space again https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk13u/job/jdk13u-linux-s390x-hotspot/115/console 

Out of curiosity, would it be possible to get me and Adam limited access to these machines so we can clean them out when they run out space? It would save us having to badger you everytime this happens on other machines too
