### ISSUE TITLE
UB16 x86 - "adoptopenjdk_install" Role Error

### ISSUE THREAD

**Issue by rajdeepsingh1** [AdoptOpenJDK/openjdk-infrastructure#1027]
Receiving the following error when the role `adoptopenjdk_install` is being applied:

TASK [../AdoptOpenJDK_Unix_Playbook/roles/adoptopenjdk_install : Chown /usr/lib/jvm/jdk-11*] ***
fatal: [ub16x64rt1]: FAILED! => {"msg": "template error while templating string: expected token 'end of print statement', got '{'. String: {{ adoptopenjdk{{ jdk_version }}_dir.stdout }}"}

**Comment by Willsparker** [comment]
Do you have an up-to-date version of the playbooks? That issue should have been fixed with #1005

**Comment by sxa555** [comment]
Closing this on the basis of the previous comment - if it's still an issue please re-open
