### ISSUE TITLE
Replace Marist zLinux boxes with new z15 ones

### ISSUE THREAD

**Issue by sxa555** [AdoptOpenJDK/openjdk-infrastructure#1031]
Marist are replacing their virtual machines with new ones on a z15 s390x system. They have supplied me with replacements, but they need to be in place by the end of the year when the old ones will be taken back. This means we have to get the machines set up (5 Ubuntu, 2 RHEL7 and one SLES12) before the end of this month ... which means most of it needs to be complete by the end of next week.

New z15 systems:
- [x] build-marist-rhel77-s390x-1
- [x] build-marist-rhel77-s390x-2
- [x] build-marist-ubuntu1604-s390x-1
- [x] test-marist-sles12-s390x-1
- [x] test-marist-ubuntu1604-s390x-1
- [x] test-marist-ubuntu1604-s390x-2
- [x] test-marist-ubuntu1604-s390x-3
- [x] test-marist-ubuntu1604-s390x-4

Old systems to decommission
- [x] build-marist-rhel74-s390x-1
- [x] build-marist-rhel74-s390x-2
- [x] build-marist-ubuntu1604-s390x-2
- [x] build-marist-ubuntu1604-s390x-3
- [x] test-marist-ubuntu1604-s390x-1(-z13)
- [x] test-marist-ubuntu1604-s390x-2-XJ

**Comment by Haroon-Khel** [comment]
Running the ansible playbook locally on the machine. Ansible was installed on the machine with pip. 
Pip was installed via:
```
curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
python get-pip.py --user
```

The installation of Ansible required the following 2 prerequisites:
```
python-devel.s390x
openssl-devel.s390x
```
which were installed using `yum install`

Then Ansible was installed using 
`pip install ansible`

**Comment by Haroon-Khel** [comment]
Had to manually uninstall nss-softokn-freebl.s390 as it was conflicting with the installation of nss-softokn-freebl.s390x (one of the yum tasks)

**Comment by Haroon-Khel** [comment]
As per #1043, the task Install additional build tools for RHEL on s390x in Common/tasks/RedHat.yml needs to be commented out in order for the playbook to run

**Comment by Haroon-Khel** [comment]
Issue with the task `SSH into the Nagios Master and excute the Nagios_Ansible_Config_tool.sh script` in roles/Nagios_Master_Config. The machine hangs while requesting the user to input the root password for the Nagios Master machine. Skipping Nagios tasks until this is resolved

**Comment by Haroon-Khel** [comment]
Issue with the task `Security - Disable Password Authentication for root user` in roles/Security. The log output is given by:
```
TASK [Security : Security - Disable Password Authentication for root user] ************************************************************************************************************************************************************************************************************
task path: /root/openjdk-infrastructure/ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Security/tasks/main.yml:39
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: OSError: [Errno 1] Operation not permitted
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Unable to make /tmp/tmp9nm0tr into to /etc/ssh/sshd_config, failed final rename from /etc/ssh/.ansible_tmpkp5pclsshd_config: [Errno 1] Operation not permitted"}
```

**Comment by Haroon-Khel** [comment]
Playbook has completed running. However the following ansible tasks are being skipped, and their errors need to be resolved:

- [ ] Security - Disable Password Authentication for root user in roles/Security

- [ ] SSH into the Nagios Master and excute the Nagios_Ansible_Config_tool.sh script in roles/Nagios_Master_Config

**Comment by sxa555** [comment]
Interesting ... Will need investigating but I'll get the machine into jenkins and see if it works. That ought to be enough to make it usable - thanks :-)

**Comment by sxa555** [comment]
Other than an issue with the hostname definitions (side effect of the firewall issue which made us run the playbooks locally on the machine) we seem to be looking ok so I'm going to start disconnecting the old systems now ...

**Comment by Haroon-Khel** [comment]
The following packages are failing to install on the SLES 12 machine:

- [ ]  bison

- [ ] flex

- [ ] systemtap-sdt-devel

- [ ] xorg-x11-server

- [ ] xorg-x11-server-extra

- [ ] java-1_8_0-openjdk

- [ ] git

- [ ] perl-CPAN-Meta

**Comment by Haroon-Khel** [comment]
The playbook ran successfully on the second RHEL 7 machine (148.100.86.218). Like the first RHEL 7 machine (148.100.86.102), the Nagios tasks were ignored, as was the `Security - Disable Password Authentication` security task. 
This machine did install, and did not have a problem doing so, the s390 versions of the `glibc`, `glibc-devel` and `libstdc++` packages stated in https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1043, therefore I am inclined to close that issue

**Comment by Haroon-Khel** [comment]
The playbook has finished running on the SLES machine (148.100.86.12), with the Nagios tasks ignored for now. Besides the above build tools which failed to install, the only other problem I encountered was the absence of a jenkins and zeus group. I added these accordingly, based on their config in one of the other machines (148.100.86.218)

**Comment by sxa555** [comment]
For now I've set `JAVA_HOME` to point to `/usr/lib/jvm/jdk-13.0.1+9` instead of the more normal java 8, which has allowed https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1532/ to run through ok on that machine, so it seems more or less set up enough to at least run some testing. I'll leave it in place and able to run tests overnight and see if anything else may be missing :-)

**Comment by sxa555** [comment]
Going to provide some links to stuff that has been running on the SLES12 box just so we can keep a close eye on them:
- https://ci.adoptopenjdk.net/job/Test_openjdk11_j9_sanity.system_s390x_linux_xl/10

**Comment by adam-thorpe** [comment]
The SLES12 box is showing similar failures to the other ubuntu boxes, I think it just needs a reboot like the other ones: https://ci.adoptopenjdk.net/user/adam-thorpe/my-views/view/Nightly%20test%20openjdk%20openJ9/job/Test_openjdk8_j9_sanity.openjdk_s390x_linux_xl/8/

**Comment by sxa555** [comment]
Looks like it's been rebooted now - if you manager to run a grinder on it running the same test let us know if it works.

Example error for historic reference:

```
06:42:50  java.net.UnknownHostException: openjdk01.adoptopenjdk.net: openjdk01.adoptopenjdk.net: Name or service not known
06:42:50  	at java.net.InetAddress.getLocalHost(InetAddress.java:1506)
06:42:50  	at CookieManagerTest.makeHttpCall(CookieManagerTest.java:95)
06:42:50  	at CookieManagerTest.main(CookieManagerTest.java:43)
06:42:50  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
06:42:50  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
06:42:50  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
06:42:50  	at java.lang.reflect.Method.invoke(Method.java:498)
06:42:50  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
06:42:50  	at java.lang.Thread.run(Thread.java:821)
06:42:50  Caused by: java.net.UnknownHostException: openjdk01.adoptopenjdk.net: Name or service not known
06:42:50  	at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
06:42:50  	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:929)
06:42:50  	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1324)
06:42:50  	at java.net.InetAddress.getLocalHost(InetAddress.java:1501)
06:42:50  	... 8 more
06:42:50  
```
With a summary of 
```
08:06:16  
08:06:16  TEST TARGETS SUMMARY
08:06:16  ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
08:06:16  PASSED test targets:
08:06:16  	jdk_io_0
08:06:16  	jdk_lang_0
08:06:16  	jdk_math_0
08:06:16  	jdk_security1_0
08:06:16  	jdk_util_0
08:06:16  
08:06:16  FAILED test targets:
08:06:16  	jdk_net_0
08:06:16  	jdk_nio_0
08:06:16  	jdk_rmi_0
08:06:16  
08:06:16  TOTAL: 8   EXECUTED: 8   PASSED: 5   FAILED: 3   DISABLED: 0   SKIPPED: 0
08:06:16  ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
08:06:16  To rebuild the failed test in a jenkins job, copy the following link and fill out the <Jenkins URL> and <FAILED test target>:
```

**Comment by sxa555** [comment]
Rerunning the job Adam mentioned at https://ci.adoptopenjdk.net/user/adam-thorpe/my-views/view/Nightly%20test%20openjdk%20openJ9/job/Test_openjdk8_j9_sanity.openjdk_s390x_linux_xl/9

**Comment by sxa555** [comment]
@smlambert Can you confirm whether you're happy with the new test machines? I'd like your final approval before formally handing back the old ones. We've been running exclusively with the new ones for a couple of weeks now.

**Comment by smlambert** [comment]
Things are looking good, there are a couple of failures that have arisen over the past couple of days (therefore likely NOT related to the addition of the new machines).

**Comment by smlambert** [comment]
test-marist-ubuntu1604-s390x-1-z13 has a failure due to pre-existing /tmp folder, but I see its in the list to be decommissioned

https://ci.adoptopenjdk.net/view/Test_openjdk/job/Test_openjdk8_hs_sanity.openjdk_s390x_linux/100/testReport/java_lang_ClassLoader_forNameLeak_ClassForNameLeak/java/ClassForNameLeak/

Standard Error
java.nio.file.FileAlreadyExistsException: /tmp
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:88)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:384)
	at java.nio.file.Files.createDirectory(Files.java:674)
	at java.nio.file.Files.createAndCheckIsDirectory(Files.java:781)
	at java.nio.file.Files.createDirectories(Files.java:727)
	at jdk.testlibrary.JarUtils.createJarFile(JarUtils.java:66)
	at jdk.testlibrary.JarUtils.createJarFile(JarUtils.java:106)
	at ClassForNameLeak.main(ClassForNameLeak.java:88)

**Comment by sxa555** [comment]
Thanks ... Yep I renamed some original systems to have a z13 suffix to avoid confusion so that one shouldn't be as problem (though curious ...)

**Comment by Haroon-Khel** [comment]
Regarding the multicast network config of the machines, the Ubuntu machines do not seem to have an issue sending or receiving packets. I've configured the RHEL machines to be able to receive packets from ipv4 addresses, but still can't figure how to do the same for ipv6 (progress is documented in #699). The SLES machine has the opposite problem; accepts multicast packets from ipv6 addresses, but not from ipv4. Looking into this.

**Comment by sxa555** [comment]
Done, other than the PR to update the inventory which is pending a review by Martijn at the moment https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/1041

**Comment by sxa555** [comment]
Have removed the `build` tag from https://ci.adoptopenjdk.net/computer/build-marist-ubuntu1604-s390x-1/  since it's not a proper build machine (as it's not RHEL!) and things were being scheduled on it (!)
