### ISSUE TITLE
Request to install Chinese GB18030 locale to AIX

### ISSUE THREAD

**Issue by toshiona** [AdoptOpenJDK/openjdk-infrastructure#1032]
This is a following up request of #704. Thank you for handling that request.
We'd like to ask one more locale to install AIX (7.1 and 7.2) for internationalization testing.

- Zh_CN (Zh_CN.GB18030)

**Comment by sej-jackson** [comment]
Done.

**Comment by toshiona** [comment]
Thank you for quick action, sej.
