### ISSUE TITLE
Failing SLES 12 tasks in Unix playbook

### ISSUE THREAD

**Issue by Haroon-Khel** [AdoptOpenJDK/openjdk-infrastructure#1033]
Currently the unix playbook fails while running on an x86_64 SLES 12 machine on our intranet. The failing tasks are:

- The `zypper_repository` task in `roles/Common/tasks/SLES.yml`. The repo at `https://download.opensuse.org/repositories/devel:/tools:/scm/SLE_12_SP3/` is no longer available.

- A temporary solution is to change the repo to `https://download.opensuse.org/repositories/devel:/tools:/scm/SLE_12_SP5/`, but this results in failures when trying to install `systemtap-sdt-devel` and `git`, in `roles/Common/vars/SLES.yml`

- The task `Install XML::Parser` in `roles/CPAN`

- The tasks `Enable NVidia CUDA toolkit Repo for SLES12 on x86_64` and `Install NVidia CUDA toolkit for SLES12 on x86_64` in `roles/NVidia_Cuda_Toolkit`

- `Mount swap file` in `roles/Swap_File`

**Comment by Willsparker** [comment]
Looking into it :)

**Comment by Willsparker** [comment]
The above link to the SP5 repo doesn't contain `systemtap-std-dev` and to install git, `git-core` need to be used. However, https://download.opensuse.org/repositories/devel:/tools/SLE_12_SP4/ has both :-)

**Comment by Willsparker** [comment]
Regarding the `XML::Parser` issue, the machine requires `expat-devel` or `libexpat1-dev` installed, of which I can't find a way of downloading, either through `wget` or adding a repository and using `zypper`. The alternative is installing `perl-XML-parser` in the `Common` role, according to https://github.com/chorny/XML-Parser/README.md, though I'm not sure how to verify this.

**Comment by Willsparker** [comment]
The `NVidia_Cuda_Toolkit` task was failing as it was trying to `rpm -i ` all words after the actual package. Not entirely sure why, but separating the `rpm` and `sed` command fixes the issue.

**Comment by Willsparker** [comment]
https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/1062#issuecomment-570226824
