### ISSUE TITLE
Add more Linux aarch64 test machines

### ISSUE THREAD

**Issue by jerboaa** [AdoptOpenJDK/openjdk-infrastructure#1037]
Currently there is only one Linux aarch64 test machine online (the big packet box). This seems to become a bottleneck for JDK11+ testing. It would be nice to get more test-labelled machines online. There used to be 4 or so of them.

**Comment by jerboaa** [comment]
#680 seems related.

**Comment by smlambert** [comment]
Seems like we lost all the openlab ones
<img width="606" alt="Screen Shot 2019-12-11 at 8 51 34 PM" src="https://user-images.githubusercontent.com/2836948/70675744-0a13f000-1c58-11ea-8120-4bfea0cecb86.png">
: https://ci.adoptopenjdk.net/label/hw.arch.aarch64/

**Comment by sxa555** [comment]
@gdams Any outlook on recoering the openlab ones? I don't believe I have access to anything there ...

**Comment by gdams** [comment]
I'm spinning up some aws machines now.

**Comment by sxa555** [comment]
Have tagged https://ci.adoptopenjdk.net/computer/build-packet-ubuntu1604-armv8-2/ with the test tags too to alleviate the load a bit

**Comment by gdams** [comment]
@sxa555 I've now removed the tag as 6 aws machines are online
