### ISSUE TITLE
Failing to install s390 build tools on RHEL 7 s390x

### ISSUE THREAD

**Issue by Haroon-Khel** [AdoptOpenJDK/openjdk-infrastructure#1043]
When running the Unix playbook, the following build tools fail to install on an RHEL 7 s390x machine:

```
Additional_Build_Tools_RHEL_s390x:
  - glibc.s390                    # a dependency required for executing a 32-bit C binary
  - glibc-devel.s390              # a dependency required for executing a 32-bit C binary
  - libstdc++.s390                # a dependency required for executing a 32-bit C binary
```
This subtasks is called by the task `Install additional build tools for RHEL on s390x` in Common/tasks/RedHat.yml.

The error provides the following log (for all 3 packages):
```
Error:  Multilib version problems found. This often means that the root
       cause is something else and multilib version checking is just
       pointing out that there is a problem. Eg.:
       
         1. You have an upgrade for nss-softokn-freebl which is missing some
            dependency that another package requires. Yum is trying to
            solve this by installing an older version of nss-softokn-freebl of the
            different architecture. If you exclude the bad architecture
            yum will tell you what the root cause is (which package
            requires what). You can try redoing the upgrade with
            --exclude nss-softokn-freebl.otherarch ... this should give you an error
            message showing the root cause of the problem.
       
         2. You have multiple architectures of nss-softokn-freebl installed, but
            yum can only see an upgrade for one of those architectures.
            If you don't want/need both architectures anymore then you
            can remove the one with the missing update and everything
            will work.
       
         3. You have duplicate versions of nss-softokn-freebl installed already.
            You can use "yum check" to get yum show these errors.
       
       ...you can also use --setopt=protected_multilib=false to remove
       this checking, however this is almost never the correct thing to
       do as something else is very likely to go wrong (often causing
       much more problems).
       
       Protected multilib versions: nss-softokn-freebl-3.44.0-8.el7_7.s390 != nss-softokn-freebl-3.44.0-5.el7.s390x
```

These packages were added to the playbook via this past commit: https://github.com/AdoptOpenJDK/openjdk-infrastructure/commit/c61c9fac0a32610bbeb3e17170f00be0a5f77709

The machine itself has the **s390x** version of those packages, so I suspect the reason for the error lies here.

**Comment by sxa555** [comment]
@JennyChenyj I believe it was your change in https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/1018 that introduced this issue

**Comment by JennyChenyj** [comment]
Hey! Thanks for explaining to me the issue! Sorry about that errors. 
Here is a potential solution. We can switch the state in the task that installs the additional build tools from ```latest``` to ```present```. If the machine has the packages, it will skip installing or updating them. If the machine does not have the packages, they will be installed. I met a similar issue before, and we solved it using this method.

**Comment by JennyChenyj** [comment]
Here is a link to the pull request: https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/1045/files

**Comment by Haroon-Khel** [comment]
Closing this issue as the error could not be reproduced.
