### ISSUE TITLE
Temp access to test-packet-armv8-ubuntu-16-04 for hardware specs?

### ISSUE THREAD

**Issue by jerboaa** [AdoptOpenJDK/openjdk-infrastructure#1048]
I'd need to know the exact hardware this machine runs:
https://ci.adoptopenjdk.net/computer/test-packet-armv8-ubuntu-16-04/

This would help diagnose some random JDK 11 test failures on we see occasionally on that machine.

My public SSH key is here:
https://jerboaa.fedorapeople.org/key_ssh_jerboaa.pub

**Comment by sxa555** [comment]
Sure ...

**Comment by sxa555** [comment]
`jerboaa` account created and ssh key above added

**Comment by jerboaa** [comment]
@sxa555 I'm done with it and access can get revoked again. Thank you!
