### ISSUE TITLE
git clone fails using https on rasp pi

### ISSUE THREAD

**Issue by jdekonin** [AdoptOpenJDK/openjdk-infrastructure#107]
Using the current ansible script on a rasp pi I get this error :  
```
lnxarmpirt-i1:/tmp $ git clone https://github.com/eclipse/openj9.git
Cloning into 'openj9'...
fatal: Unable to find remote helper for 'https'
```
Fix is to add the libcurl4-openssl-dev package and (re)compile/install git.  I'll submit a change for this shortly.  

Edit:  the alternative fix is to apt-get the git and git-core packages, but that would only work if git version is > 2.0 (openj9 requirement).

**Comment by gdams** [comment]
should just be a case of adding an extra var section for armv7 such as the v8 one [here](https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/master/ansible/playbooks/AdoptOpenJDK_Linux_Playbook/roles/Common/vars/Ubuntu.yml#L50-L51).
