### ISSUE TITLE
Add windows systemtests to vagrant playbook testing

### ISSUE THREAD

**Issue by sxa555** [AdoptOpenJDK/openjdk-infrastructure#1072]
Ref #1071 the "extended" systemtests (despite their name) are the quickest ones that show up this problem. We should add this to the Vagrant windows test script to trap this additional requirement which the existing basic test isn't catching

**Comment by Willsparker** [comment]
Can do - I've spoken to @morgan-davies and he's pointed me in the direction on how to do it. Did you want this to replace the `MachineInfo` test or just run afterwards?

**Comment by Willsparker** [comment]
So... running this on a windows VM :
```
export TEST_JDK_HOME='path_to_downloaded_jdk'
cd $HOME
if [ ! -d "testLocation" ];
then
	echo "Creating testLocation directory"
	mkdir testLocation
fi
cd testLocation
if [ ! -d "openjdk-tests" ];
then
	echo "Git cloning openjdk-tests"
	git clone https://github.com/adoptopenjdk/openjdk-tests
fi
cd openjdk-tests
./get.sh -t $HOME/testLocation/openjdk-tests -p x64_windows
cd TKG
make -f run_configure.mk AUTO_DETECT=true
export BUILD_LIST=system
make compile
make _extended.system
```
Which output this:
```
TEST TARGETS SUMMARY
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
DISABLED test targets:
	JdiTest_0
PASSED test targets:
	MachineInfo_0
	MachineInfo_0
	MachineInfo_0
	MachineInfo_0
	MathLoadTest_all_0
	MachineInfo_0
	MachineInfo_0
	MachineInfo_0
	ConcurrentLoadTest_0
	DirectByteBufferLoadTest_0
	LangLoadTest_0
	LockingLoadTest_0
	UtilLoadTest_0
	MachineInfo_0
TOTAL: 16   EXECUTED: 14   PASSED: 14   FAILED: 0   DISABLED: 1   SKIPPED: 1
ALL TESTS PASSED
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
_extended.system done
```
Seems to be an awful lot of `Machineinfo` tests ... However, apart from this, it appears to correctly run them - If this output seems correct, I'll put the PR in :-)

**Comment by sxa555** [comment]
Yep I'm happy with that
Would be good to actively try and break it as well ... Once the PR is in, run against a branch (not one that will ever be merged!) that removes Strawberry perl from the playbook and verify that one or more of them break :-)

**Comment by Willsparker** [comment]
Disabling the Strawberry-Perl task makes the install `OpenSSL` task fail. 
https://ci.adoptopenjdk.net/job/VagrantPlaybookCheck/OS=Win2012,label=vagrant/274/

as OpenSSL is required for J9, I'm going to make the VM build Hotspot instead, disable the OpenSSL role and test that JDK :-)

**Comment by Willsparker** [comment]
https://ci.adoptopenjdk.net/job/VagrantPlaybookCheck/OS=Win2012,label=vagrant/275/console

The tests fail ( well... they don't even run) if Strawberry Perl isn't installed :-) I'll put in the PR
