### ISSUE TITLE
Revisit github teams in the project and what they control

### ISSUE THREAD

**Issue by sxa** [AdoptOpenJDK/openjdk-infrastructure#1084]
I've been looking at some of the teams that we have and what they get access to and a few things have stood out:

1. We don't have too much consistency in the naming of the teams
2. We don't have a group that lets people triage builds that gives them access to the [signing job](https://ci.adoptopenjdk.net/job/build-scripts/job/release/job/sign_build/) logs
3. We have a number of jobs where the permissions seem to have unnecessarily listed individuals listed against things instead of teams

I've copied some of this from the [infrastructure](https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/1066) and [build](https://github.com/AdoptOpenJDK/openjdk-build/pull/1457) FAQs but I'll add more as I put them together:

### Infrastructure

- [adoptopenjdk-infrastructure](https://github.com/orgs/AdoptOpenJDK/teams/adoptopenjdk-infrastructure) - write access to the repository which lets you be an official approver of PRs (triage doesn't)
- [infrastructure](https://github.com/orgs/AdoptOpenJDK/teams/infrastructure) - higher level of access for system administrators only
- [admin_infrastructure](https://github.com/orgs/AdoptOpenJDK/teams/admin_infrastructure) - The Admin team - can force through changes without   approval etc.

### Build

- [GetOpenJDK](https://github.com/orgs/AdoptOpenJDK/teams/getopenjdk) - `Triage` level of access which lets you assign issues to people
- [build](https://github.com/orgs/AdoptOpenJDK/teams/build) - `Write` access which lets you approve and merge PRs and run and configure most jenkins jobs
- [release](https://github.com/orgs/AdoptOpenJDK/teams/build) - Allows you to run the release jobs in jenkins

### Test
- [testing](https://github.com/orgs/AdoptOpenJDK/teams/testing) - `Write` access which lets you approve and merge PRs and run and configure most jenkins jobs (to 5 test repos, bumblebench, openjdk-systemtest, openjdk-tests, stf, openjdk-test-tools)
- [coretest](https://github.com/orgs/AdoptOpenJDK/teams/coretest) - `write` access to TKG repo 

### Other groups:
- [icedtea-web](https://github.com/orgs/AdoptOpenJDK/teams/icedtea-web)
- [installer](https://github.com/orgs/AdoptOpenJDK/teams/installer)
- [jenkins-admins](https://github.com/orgs/AdoptOpenJDK/teams/jenkins-admins)
- [Jitwatch](https://github.com/orgs/AdoptOpenJDK/teams/Jitwatch)
- [jsplitpkgscan](https://github.com/orgs/AdoptOpenJDK/teams/jspliypkgscan)
- [openjdk-upstream-binaries](https://github.com/orgs/AdoptOpenJDK/teams/openjdk-upstream-binaries)
- [openjdk-upstream-binary-rel-eng](https://github.com/orgs/AdoptOpenJDK/teams/openjdk-upstream-binary-rel-eng)

**Comment by jerboaa** [comment]
openjdk-upstream-binaries (admin group)
openjdk-upstream-binary-rel-eng (write group)

These two are for the OpenJDK Project Builds work we do in openjdk8-upstream-binaries and openjdk11-upstream-binaries.

**Comment by sxa** [comment]
For the main repos I'm going to propose the following updates for now. Putting `build` `infrastructure` and `test` means they'll be easier to collate in a sorted list. I'm somewhat in two minds about `build-core`

| Old name | New name | Access level | Other change? |
|---|---|---|---|
| GetOpenJDK | build-triage | | |
| build | build | Can run jobs | |
| <none> | build-core | Visibility of install jobs | Will remove lots of special cases |
| <none> | infrastructure-triage | Only triage access | For new people to the team |
| adoptopenjdk-infrastructure | infrastructure | Can approve PRs | |
| admin_infrastructure | infrastructure-core | Jenkins agent control | |
| infrastructure | infrastructure-secret | Access to secrets repo | |
| <none> | test-triage | own issues, run Grinders | (Grinders currently unrestricted) |
| testing | test | | |
| coretest | test-core | | |

**Comment by sxa** [comment]
@AdoptOpenJDK/tsc previous comment for review. Renaming will "lose" any at-mentions to the old team but I don't think we really use those for the affected ones. My plan would be to rename, and update any jenkins jobs which are acces-controlled by the old name, as well as implementing the new `build-core` group.

**Comment by aahlenst** [comment]
I'm happy with the proposed changes.

**Comment by smlambert** [comment]
I would like to reduce the number of members in the testing group, they were originally added to enable a larger set of people to be able to run Grinders, as that seemed to be the mechanism used to control access.  I can go in and cull many of the names in the testing group, as there are many names that are not active there.

**Comment by sxa** [comment]
Agreed @smlambert - I need to do the same with the others but I felt that rationalising them so I could figure out what the groups were for first was a prereqs (Luckily you only have two so less of a problem!) :-)

**Comment by gdams** [comment]
+1

**Comment by karianna** [comment]
The list looks good, was thinking about `build-triage` --> `support` but I'm not too fussed

**Comment by tellison** [comment]
Top level repo names look good, and as for the suffixes...
```
-triage suffixed ones for anyone who turns up and thinks they can help with something. Little real access
unsuffixed version for team members who are committers and have the ability to approve/merge PRs
-core suffixed ones for higher level access of some sort
```
how about, rather than 'unsuffixed', you use `-team`, so we end up with, for example, `build-triage`, `build-team`, `build-core` which would be explicit.

**Comment by sxa** [comment]
@karianna Yeah I can see why we'd call it "support", although this is primarily for access to the build repository and I wanted to make the names be related to the main repo they're for, at least for now.

@tellison I suppose my only thought would be "Would triagers not think they're part of a team" and they're all teams (So you'd have "the build-team team" but I can see how some sort of suffix might be useful too. Definitely one I'm not personally concerned with either way though. Perhaps a suffix of `-committers` might be more descriptive (other than the fact that's not necessarily descriptive with respect to running extra jenkins jobs that level may have access to over triage)

**Comment by sxa** [comment]
All build and infrastructure ones now renamed. We need to revisit what is now `openjdk-triage` as it had write access to quite a few other repositories so that will need a separate sanitisation. I suspect we'll create a replacement for getOpenJDK which has a cleaner set of permissions and users in it and restrict `openjdk-triage` down to just the build repos.

Installer/sigfning jobs have been updated with the new permissions so permissions on those jobs are using the team instead of multiple individual users beign explicitly specified

**Comment by sxa** [comment]
Test teams renamed as described above too - new `test-triag` group created with triage (not write) access to the test repos. We should look at the ACLs on the Grinder jobs too.

For now I'm going to consider this closed, although future adjustments to this can be iterative (and potentially documented in here)
