### ISSUE TITLE
JDK11 : Test failures on test-godaddy-win2016-x64-2 due to processes locking and not able to start.  

### ISSUE THREAD

**Issue by archanaNogriya** [AdoptOpenJDK/openjdk-infrastructure#1088]
Job running : https://ci.adoptopenjdk.net/job/Test_openjdk11_j9_sanity.openjdk_x86-64_windows_xl/119/console

Failing with error -

WARNING: not all children have been started. Can't complete test.
17:34:49           You can try to increase the timeout or
17:34:49           you can try to use a faster VM (i.e. not a debug version).
17:34:49  whenComplete: pid: 65840, exception: null, thread: Thread[ForkJoinPool.commonPool-worker-3,10,system], elapsed: PT0.0106094S
17:34:49  whenComplete: pid: 68484, exception: null, thread: Thread[ForkJoinPool.commonPool-worker-3,10,system], elapsed: PT0.0116973S
17:34:49  whenComplete: pid: 47144, exception: null, thread: Thread[ForkJoinPool.commonPool-worker-3,10,system], elapsed: PT0.0125725S
17:34:49  whenComplete: pid: 36956, exception: null, thread: Thread[ForkJoinPool.commonPool-worker-7,10,system], elapsed: PT0.0125725S
17:34:49  whenComplete: pid: 16812, exception: null, thread: Thread[ForkJoinPool.commonPool-worker-3,10,system], elapsed: PT0.02916S
17:34:49  whenComplete: pid: 65468, exception: null, thread: Thread[ForkJoinPool.commonPool-worker-1,10,system], elapsed: PT0.02916S
17:34:49  destroyProcessTree destroyForcibly
17:34:49  pid 14596, alive: true; parent: Optional[49528], [user: Optional[S160-153-234-5\jenkins], cmd: C:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows_xl\openjdkbinary\j2sdk-image\bin\java.exe, startTime: Optional[2020-01-09T17:33:16.202Z], totalTime: Optional[PT0.859375S]]
17:34:49  destroyProcessTree destroyForcibly
17:34:49  pid 19840, alive: true; parent: Optional[49528], [user: Optional[S160-153-234-5\jenkins], cmd: C:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows_xl\openjdkbinary\j2sdk-image\bin\java.exe, startTime: Optional[2020-01-09T17:33:16.208Z], totalTime: Optional[PT0.984375S]]
17:34:49  test OnExitTest.test2(): failure
17:34:49  java.lang.AssertionError: spawned process should have been in children expected [true] but found [false]
17:34:49  	at org.testng.Assert.fail(Assert.java:94)
17:34:49  	at org.testng.Assert.failNotEquals(Assert.java:496)
17:34:49  	at org.testng.Assert.assertTrue(Assert.java:42)
17:34:49  	at OnExitTest.lambda$test2$4(OnExitTest.java:154)
17:34:49  	at OnExitTest$$Lambda$74/0000000000000000.accept(Unknown Source)
17:34:49  	at java.base/java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1603)
17:34:49  	at OnExitTest.test2(OnExitTest.java:153)
17:34:49  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
17:34:49  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
17:34:49  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
17:34:49  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
17:34:49  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
17:34:49  	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
17:34:49  	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
17:34:49  	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
17:34:49  	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
17:34:49  	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
17:34:49  	at org.testng.TestRunner.privateRun(TestRunner.java:773)
17:34:49  	at org.testng.TestRunner.run(TestRunner.java:623)
17:34:49  	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
17:34:49  	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
17:34:49  	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
17:34:49  	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
17:34:49  	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
17:34:49  	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
17:34:49  	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
17:34:49  	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
17:34:49  	at org.testng.TestNG.run(TestNG.java:1018)
17:34:49  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
17:34:49  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:54)
17:34:49  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
17:34:49  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
17:34:49  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
17:34:49  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
17:34:49  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
17:34:49  	at java.base/java.lang.Thread.run(Thread.java:834)
17:34:49  
17:34:49  ===============================================
17:34:49  java/lang/ProcessHandle/OnExitTest.java
17:34:49  Total tests run: 3, Failures: 1, Skips: 0
17:34:49  ===============================================
17:34:49  
17:34:49  whenComplete: pid: 14596, exception: null, thread: Thread[ForkJoinPool.commonPool-worker-7,10,system], elapsed: PT0.1503435S
17:34:49  whenComplete: pid: 19840, exception: null, thread: Thread[ForkJoinPool.commonPool-worker-7,10,system], elapsed: PT0.2293896S
17:34:49  STDERR:
17:34:49  java.io.IOException: Cannot run program "C:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows_xl\openjdkbinary\j2sdk-image\bin\java": CreateProcess error=1455, The paging file is too small for this operation to complete
17:34:49  	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
17:34:49  	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
17:34:49  	at JavaChild.<init>(JavaChild.java:74)
17:34:49  	at JavaChild.spawnJavaChild(JavaChild.java:196)
17:34:49  	at JavaChild.interpretCommands(JavaChild.java:388)
17:34:49  	at JavaChild.interpretCommands(JavaChild.java:322)
17:34:49  	at JavaChild.main(JavaChild.java:268)
17:34:49  Caused by: java.io.IOException: CreateProcess error=1455, The paging file is too small for this operation to complete
17:34:49  	at java.base/java.lang.ProcessImpl.create(Native Method)
17:34:49  	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:478)
17:34:49  	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:154)
17:34:49  	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
17:34:49  	... 6 more
17:34:49  JVMDUMP039I Processing dump event "systhrow", detail "java/lang/OutOfMemoryError" at 2020/01/09 10:33:17 - please wait.
17:34:49  JVMDUMP032I JVM requested System dump using 'C:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows_xl\openjdk-tests\TKG\test_output_15785903507579\jdk_lang_0\work\java\lang\ProcessHandle\OnExitTest\core.20200109.103317.36956.0001.dmp' in response to an event
17:34:49  Unhandled exception
17:34:49  Type=Segmentation error vmState=0xffffffff
17:34:49  Windows_ExceptionCode=c0000005 J9Generic_Signal=00000004 ExceptionAddress=00007FFBB0FE9A1D ContextFlags=0010005f
17:34:49  Handler1=00007FFBB13FAD30 Handler2=00007FFBB28DF180 InaccessibleReadAddress=00000000000057AB
17:34:49  RDI=0000005EEB3FBAE0 RSI=0000023F388AD150 RAX=0000023F38182430 RBX=0000023F388B8DB0
17:34:49  RCX=0000000000000000 RDX=0000005EEB3FBAE0 R8=0000023F38251500 R9=0000000000008000
17:34:49  R10=0000023F388B9350 R11=0000005EEB3FB7F0 R12=000000007FFD0000 R13=0000000000000000
17:34:49  R14=0000023F388A0168 R15=0000023F388A9F00

**Comment by archanaNogriya** [comment]
looks like very similar problem as https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1086.

**Comment by sxa555** [comment]
Machine was rebooted to resolve 1086 which will have resolved this too as it's on the same machine
