### ISSUE TITLE
"ansible_processor_vcpus" reported as '***Undefined***' on s390x RHEL7

### ISSUE THREAD

**Issue by sej-jackson** [AdoptOpenJDK/openjdk-infrastructure#1090]
Running playbooks on new Rhel7.7 system (s390x) which fell over in gmake task because they are reporting `ansible_processor_vcpus` as undefined.

>TASK [gmake : Compile and install make 4.1 from source] ************************
>fatal: [jsvt302.hursley.ibm.com]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'ansible_processor_vcpus' is undefined\n\nThe error appears to be in '/home/sej42282/gitibm/runtimes/infra-can/ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/gmake/tasks/main.yml': line 40, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Compile and install make 4.1 from source\n  ^ here\n"}

`/proc/cpuinfo` contains:
```
# cat /proc/cpuinfo
vendor_id       : IBM/S390
# processors    : 2
bogomips per cpu: 21881.00
max thread id   : 0
features        : esan3 zarch stfle msa ldisp eimm dfp edat etf3eh highgprs te vx vxd vxe gs sie 
facilities      : 0 1 2 3 4 6 7 8 9 10 12 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 30 31 32 33 34 35 36 37 38 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 57 58 59 60 73 74 75 76 77 80 81 82 128 129 130 131 133 134 135 146 147 156 168
cache0          : level=1 type=Data scope=Private size=128K line_size=256 associativity=8
cache1          : level=1 type=Instruction scope=Private size=128K line_size=256 associativity=8
cache2          : level=2 type=Data scope=Private size=4096K line_size=256 associativity=8
cache3          : level=2 type=Instruction scope=Private size=2048K line_size=256 associativity=8
cache4          : level=3 type=Unified scope=Shared size=131072K line_size=256 associativity=32
cache5          : level=4 type=Unified scope=Shared size=688128K line_size=256 associativity=42
processor 0: version = FF,  identification = 313F07,  machine = 3906
processor 1: version = FF,  identification = 313F07,  machine = 3906
```

Comparing with a working system - also RHEL 7.7, but x86, `/proc/cpuinfo` contains:
```
processor       : 0
vendor_id       : AuthenticAMD
cpu family      : 23
model           : 1
model name      : AMD EPYC Processor (with IBPB)
stepping        : 2
microcode       : 0x1000065
cpu MHz         : 2199.998
cache size      : 512 KB
physical id     : 0
siblings        : 1
core id         : 0
cpu cores       : 1
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm art rep_good nopl extd_apicid eagerfpu pni pclmulqdq ssse3 fma cx16 sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm cmp_legacy svm cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw retpoline_amd ssbd ibpb vmmcall fsgsbase tsc_adjust bmi1 avx2 smep bmi2 rdseed adx smap clflushopt sha_ni xsaveopt xsavec xgetbv1 virt_ssbd arat
bogomips        : 4399.99
TLB size        : 1024 4K pages
clflush size    : 64
cache_alignment : 64
address sizes   : 40 bits physical, 48 bits virtual
power management:
```
(and similar repeated for each cpu).

There are a lot of instances of this variable being used, so for now I'm setting an override of `ansible_processor_vcpus=1` for this system in my hosts file to get around the problem.

**Comment by Willsparker** [comment]
I saw a similar problem looking at the playbook for FreeBSD, where it had `ansible_processor_cores` undefined, and it required the `ansible_processor_vcpus` variable instead. Solutions that come to mind would be to change the role to have a task specific to Rhel7 on S390x, or to make a task in the `../Common/tasks/Redhat.yml` file that sets `vcpus` to the same value as `cores`.

**Comment by Haroon-Khel** [comment]
@Willsparker If you havent already implemented a solution, I think the following way might be the quickest way to do it
`"{{ ansible_processor_vcpus | default(whatever you want as the default) }}"`

**Comment by Haroon-Khel** [comment]
If tested it roughly, with a simple `debug msg` command and it works; it outputs the default value if the variable is undefined. I haven't tested it in the gmake task

**Comment by Haroon-Khel** [comment]
Theres also a task in the `cmake` role that i've just spotted which does something similar to what you have mentioned in your comment:

```
- name: Set ansible_processor_vcpus
  set_fact:
    ansible_processor_vcpus: "{{ ansible_processor_cores }}"
  when:
    - ansible_architecture == "s390x"
  tags: cmake
```

**Comment by Willsparker** [comment]
I'll have a look - if we go for the default value solution (i.e, 1), it would build an awful lot slower if it actually has potential for a lot more processors

**Comment by Haroon-Khel** [comment]
You could try setting the default value to be the same value as `cores`, as suggested in your comment above, if that too isn't undefined

**Comment by sej-jackson** [comment]
There were 14x files using `ansible_processor_vcpus` - I don't know if the problem is just associated with the `s390x` architecture though - it's the first one I've done.
```
find . -name "*.yml" -exec grep -l ansible_processor_vcpus {} \;
./roles/Common/tasks/CentOS.yml
./roles/Common/tasks/FreeBSD.yml
./roles/Common/tasks/SLES.yml
./roles/Debug/tasks/main.yml
./roles/GIT_Source/tasks/main.yml
./roles/Nagios_Plugins/tasks/nagios_FreeBSD.yml
./roles/Nagios_Plugins/tasks/nagios_RedHat.yml
./roles/Nagios_Plugins/tasks/nagios_SLES.yml
./roles/OpenSSL/tasks/main.yml
./roles/ccache/tasks/main.yml
./roles/cmake/tasks/main.yml
./roles/gcc_48/tasks/main.yml
./roles/gmake/tasks/main.yml
./roles/local_srcinstall/tasks/main.yml
```

**Comment by Haroon-Khel** [comment]
I do remember having this issue with the new z15 RHEL marist machines, but it must have slipped my mind to open an issue

**Comment by Willsparker** [comment]
Okay, I'll put (what I think will be) a fix in. For the other architectures, I think we should handle those cases individually, as they come up.

**Comment by Willsparker** [comment]
Just FYI, the above PR will needed to be tested as I've not got access to an `s390x` machine, if someone wouldn't mind doing that...?

**Comment by sxa555** [comment]
@Haroon-Khel If your machiens showed up the problem then we could use one of the `s390x` Marist machines to test this. If we remove `/usr/local/bin/make` from the machine and run the playbook that should trigger it to rebuild the role. If you want to do that give me a shout and I'll mark it offline in jenkins for a while

**Comment by Haroon-Khel** [comment]
@sxa555 I dont think I need to use the marist machine. I've recreated the error on a s390x RHEL fyre box and am testing the pr on it

**Comment by sej-jackson** [comment]
I too created an s390x Rhel Fyre ember, and it's completed successfully against @Willsparker 's changes.

**Comment by Haroon-Khel** [comment]
I think https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/1092#pullrequestreview-342539797 serves as a more succinct solution, but I think we should look to creating a separate role for situations like this; resolving variables that appear undefined
