### ISSUE TITLE
JTReg failure on test-packet-x64-windows-2012r2-1

### ISSUE THREAD

**Issue by adam-thorpe** [AdoptOpenJDK/openjdk-infrastructure#1091]
Failing test: java/lang/SecurityManager/modules/CustomSecurityManager.sh
JDK11+ (test isn't ran on 8)
OpenJ9 and Hotspot
Any windows build

```
10:05:36  STDOUT:
10:05:36  STDERR:
10:05:36  File not found - *.java
10:05:36  error: no source files
```
Looks like the test is failing here: https://github.com/ibmruntimes/openj9-openjdk-jdk11/blob/57727e567282a160037923fc8f64d9c322b68d92/test/jdk/java/lang/SecurityManager/modules/CustomSecurityManager.sh#L54

Hard to tell when this first cropped up as it seems that tests haven't been ran on this machine in a while

**Comment by sxa555** [comment]
Can you get a Grinder set showing the same test being run on this machine and another one - otherwise the above doesn't show this as being a machine-specific issue.

**Comment by adam-thorpe** [comment]
Failing machine (packet 2012r2-1):
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1746/
Passing machine: (godaddy 2016-2): https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1747/

**Comment by sxa555** [comment]
Had a look on the machine, cleared up some old processes, [re-ran](https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1753/console) but same error occurred

**Comment by sxa555** [comment]
@smlambert I'm going to disable this machine in jenkins for now so this does not recur during the releases. If you want the machine back feel free to re-enable it

**Comment by smlambert** [comment]
thanks @sxa555 I think its better to disable as you have done, as it will be less confusing for people triaging the releases.

**Comment by sxa** [comment]
This was caused by the `PATH` being different on the machine so had the windows `find` first in the path instead of the cygwin one. Now resolved
