### ISSUE TITLE
Create openjdk14-binaries and openjdk15-binaries repos

### ISSUE THREAD

**Issue by jerboaa** [AdoptOpenJDK/openjdk-infrastructure#1093]
In order to facilitate [openjdk HEAD](https://github.com/AdoptOpenJDK/openjdk-jdk) builds (see https://github.com/AdoptOpenJDK/openjdk-build/issues/1467) it would be good if we had a place to upload nightly releases. Right now there are neither `openjdk14-binaries` repos nor `openjdk15-binaries` repos on github. It would be great if somebody could create them.

**Comment by smlambert** [comment]
Thank you for raising this, it was a request that was also echoed by participants at the August OpenJDK committers workshop to the question, "what can we do at the project from a test perspective that would be helpful to OpenJDK developers?".  The answer was build tip, test lots, raise issues early.

**Comment by tellison** [comment]
Created new repositories called [openjdk14-binaries](https://github.com/AdoptOpenJDK/openjdk14-binaries) and [openjdk15-binaries](https://github.com/AdoptOpenJDK/openjdk15-binaries).

Please check they are as you expected.

**Comment by jerboaa** [comment]
Thanks! Looks good. I'll find out once pipelines for 14 and tip are up and running (and they try to publish results there). :)
