### ISSUE TITLE
Create openjdk-jdk14 mirror repository.

### ISSUE THREAD

**Issue by jerboaa** [AdoptOpenJDK/openjdk-infrastructure#1096]
I believe it should be possible to use the skara mirror as base:
https://github.com/openjdk/jdk14

JDK 14 is slated to get released in March, but I'd need to get this added now as a stepping stone for JDK head builds. See: https://github.com/AdoptOpenJDK/openjdk-build/issues/1467

**Comment by jerboaa** [comment]
In April building will need to switch from openjdk-jdk14 to openjdk-jdk14u.

**Comment by karianna** [comment]
> I believe it should be possible to use the Skara mirror as a base:
> https://github.com/openjdk/jdk14
> 
> JDK 14 is slated to get released in March, but I'd need to get this added now as a stepping stone for JDK head builds. See: [AdoptOpenJDK/openjdk-build#1467](https://github.com/AdoptOpenJDK/openjdk-build/issues/1467)

Can we confirm from Skara that the jdk14 repo is stable and won't be rebooted?

**Comment by gdams** [comment]
I'll create a skara mirror script so that we can test things out.

**Comment by gdams** [comment]
https://github.com/AdoptOpenJDK/openjdk-jdk14

**Comment by gdams** [comment]
Script PR is here: https://github.com/AdoptOpenJDK/openjdk-build/pull/1483

**Comment by jerboaa** [comment]
Thanks!
