### ISSUE TITLE
Investigate running Jenkins master as a service

### ISSUE THREAD

**Issue by tellison** [AdoptOpenJDK/openjdk-infrastructure#11]
Launching Jenkins currently requires remembering a long command-line.  To keep things simple it would be preferable to embody this as a system service or some such thing, so that it will start on normal machine boot level, and be easier to stop/restart etc.

_Original suggestion by @karianna_

**Comment by bblondin** [comment]
Would you be able to explain this further please?
Does the following not work?  ```service jenkins start``` (stop/status/restart)
did this stop working after the 'upgrade' last Friday?

I assume the command you are taking about is:
```
/usr/bin/daemon --name=jenkins --inherit --env=JENKINS_HOME=/home/jenkins/.jenkins --output=/var/log/jenkins/jenkins.log --pidfile=/var/run/jenkins/jenkins.pid -- /usr/bin/java -Djava.awt.headless=true -jar /usr/share/jenkins/jenkins.war --webroot=/var/cache/jenkins/war --httpPort=8080
```

 Short term this command could be added to the MOTD for quick reference

**Comment by tellison** [comment]
The `service jenkins start` wasn't tried.  Discussion at the time concluded that we should run the daemon command above to start jenkins, and were left wondering why calling service wouldn't work... it may.

**Comment by karianna** [comment]
A few months ago when I went in to try and restart jenkins that service call failed.  @gdams at the time told me why but I now sadly forget.  @bblondin MOTD would be a great idea as a temp measure.

**Comment by bblondin** [comment]
added motd

```
Welcome to Ubuntu 16.04.2 LTS (GNU/Linux 4.8.0-52-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
##############################################################
How to start Jenkins:
Full command: /usr/bin/daemon --name=jenkins --inherit --env=JENKINS_HOME=/home/jenkins/.jenkins --output=/var/log/jenkins/jenkins.log --pidfile=/var/run/jenkins/jenkins.pid -- /usr/bin/java -Djava.awt.headless=true -jar /usr/share/jenkins/jenkins.war --webroot=/var/cache/jenkins/war --httpPort=8080
Service: service jenkins start (stop/status/restart)
##############################################################
Last login: Mon Jul 10 16:21:55 2017 from 32.97.110.54
```

**Comment by gdams** [comment]
@bblondin can this be closed now?
