### ISSUE TITLE
Ensure make 4.1 is the default on Linux/ppc64le build machines

### ISSUE THREAD

**Issue by sxa** [AdoptOpenJDK/openjdk-infrastructure#1106]
I've just replaced `/usr/bin/make` with a symlink to `/usr/local/bin/make` after hitting the issue described in #499 again. Ideally we'd modify the playbooks to remove the system installed make (as we do for the `GIT_Source` role unless the `dont_remove_system` tag is skipped on the playbooks (Hmmm that should possibly have been called `remove_system`

Since it affected the builds today (Maybe as a result of whatever's causing https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1097) I've adjusted it again so hopefully that will have resolved the immediate problem.

**Comment by Willsparker** [comment]
I'll look into this whilst I wait for `qemu` stuff :-)

**Comment by Willsparker** [comment]
I've had a look - putting in the conditional to run the `gmake` stuff when the `make` version is too low wasn't difficult, however when adding a task to remove system `make`, an error message came up : 
```
TASK [gmake : Remove system git if needed (yum)] **************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Error: Trying to remove \"yum\", which is protected\n
```
It seems `yum` is dependent on `make`, therefore on CentOS/RHEL (at least) we can't remove it. I can add a task to symlink it from `/usr/bin/make` to `/usr/local/bin/make`, as this will make the system `make` inaccessible?

**Comment by sxa555** [comment]
This leaves us with three options:
1. Force remove `make`, breaking the `yum` dependency
2. Find/produce a make 4.1 RPM package and use that instead
3. As you say, replace `/usr/bin/make` with a symlink, but that will be overridden if yum decides to update `make` ... TO avoid that we can add an exclude for `make` into `/etc/yum.conf`
4. Modify our scripts to ensure that `/usr/local/bin/make` is used if it exists instead of just `make`

4 may be the best option, although of the others 3 is likely best

**Comment by sxa555** [comment]
In fact option 4 might be quite trivial ... https://github.com/AdoptOpenJDK/openjdk-build/blob/master/configureBuild.sh#L262

**Comment by Willsparker** [comment]
Just for updating-sake, @sxa555 and I have come to the conclusion that there is something in the build scripts that are causing the builds to use the wrong version of `make` as https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/602 and https://github.com/AdoptOpenJDK/openjdk-build/pull/759
should cause `/usr/local/bin` to be in the path before /usr/bin, and `/usr/local/bin/make` is symlinked to `/usr/local/bin/gmake` . Therefore, it when `make` is used, it should use `gmake` by default unless overwritten

**Comment by Willsparker** [comment]
Having symlinked `/bin/false` to /usr/bin/make` on an x86_64 CentOS6 VM and running a build, it didn't crash and built successfully, so there doesn't appear to be any use of the default `make` from the build scripts (at least in this instance).

**Comment by Willsparker** [comment]
@sxa555 I did the same as above on a PPC64le Redhat 7.7 machine and the build was successfull for jdk8-j9. So I'm not sure now ...

**Comment by sxa555** [comment]
Looks like I might have to "break" one of the real bulid machines in order to verify this ... I'll wait til I'm back in the office though :-)

**Comment by Willsparker** [comment]
This issue doesn't appear to be specific to PPC - recently the `gmake` role has been changed in such a way that it won't execute on any playbooks (ref : #1129 ), and so when running on a SUSE12 Vagrant VM (x86) in the VagrantPlaybookCheck Jenkins job, version 3.82 was being used, which caused the same issues that were on the ppc machines. A PR will be put in to fix the issue with the playbooks.

**Comment by sxa555** [comment]
Let's try and break one of the build machines tomorrow @Willsparker :-)

**Comment by sxa555** [comment]
I've "broken" [build-osuosl-centos74-ppc64le-2](https://ci.adoptopenjdk.net/computer/build-osuosl-centos74-ppc64le-2) so we can see if this recurs. /usr/bin/make is now 3.82 again

**Comment by Willsparker** [comment]
Assuming that this issue should still be prevalent when running the `JavaFutures` Jenkins Job, the issue seems resolved -  build-osuosl-centos74-ppc64le-2 was able to build Loom, Valhalla and Amber in ~1 hr. @sxa555 Did you remove a tag from the machine to stop other jobs from running on it?

**Comment by sxa555** [comment]
https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk14u/job/jdk14u-linux-ppc64le-openj9-linuxXL/4/ ran on that machine so it looks like it's still running things

**Comment by sxa555** [comment]
Looks like `/usr/bin/make` was  still set as a symlink to 4.1 - I've switched it back to being 3.82 - let's see what happens overnight

**Comment by sxa555** [comment]
Going to close this again as /usr/bin/make being 3.82 is not slowing down build-osuosl-centos74-ppc64le-2. Can re-open (again) if it recurs. It's worth noting that we did see a slowdown on one of the Linux/s390x boxes last week but wasn't clear if it was exactly the same problem

**Comment by sxa** [comment]
Causing problems again on the openj9 builds - taking 5 hours at present. This screenshot is from the current situation on https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-linux-ppc64le-openj9/ - I've switched `/usr/bin/make` back to point at 4.1 to prevent slowing down the release cycle any further
![image](https://user-images.githubusercontent.com/6487691/79451433-76c04200-7fde-11ea-8e53-e5ebd5e4672f.png)

**Comment by Willsparker** [comment]
It seems that job (as linked above) is back to a fairly consistent time of sub-45 minutes for the build section.

<img width="531" alt="Screenshot 2020-05-12 at 09 05 23" src="https://user-images.githubusercontent.com/52783864/81657413-c3f1d100-942f-11ea-8d55-bf659e81ed15.png">

This would fairly point to the issue being the make version, however the playbooks should install gmake fine ( https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/d3f1eca8397c9e5115fef848af84ae28d98b614d/ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/gmake/tasks/main.yml#L21 ) , and then subsequently symlink it. I suppose maybe yum broke the symlink by updating `make` , causing the original issue. 
I've also seen no issue with building (or it taking awhile) on CentOS6/7/8 (admittedly they'll be x64) in the `VagrantPlaybookCheck` Jenkins job, so in the current state, the playbooks should be okay.

**Comment by sxa** [comment]
The `/usr/bin/make` symlink is pointing back to our 4.1 make. The underlying issue needs a resolution - at the moment I believe that when the OS updates make it removes the symlink and puts it back to 3.82

**Comment by Willsparker** [comment]
So we're back to the intial list of suggestions - presumably option 3 next?
> As you say, replace /usr/bin/make with a symlink, but that will be overridden if yum decides to update make ... TO avoid that we can add an exclude for make into /etc/yum.conf

That wouldn't be too difficult to put in - `echo "exclude= make" > /etc/yum.conf` , except 'Ansiblised'

**Comment by Willsparker** [comment]
Update from @sxa on Slack, in response to my above suggestion:

> The problem with that is that it could block other things (such as yum) from receiving patches, plus you have to be fairly selective about which systems to apply it to.
