### ISSUE TITLE
Remove zulu-9 from the Linux/x86 playbooks

### ISSUE THREAD

**Issue by sxa555** [AdoptOpenJDK/openjdk-infrastructure#1108]
This is causing confusion on the Ubuntu systems (and possible CentOS/RHEL) as it seems to be setting it as a default. Since java 9 is out of support this is not ideal. Also we should not require zulu 9 on the machines as we have a valid adoptopenjdk9 available if required now.

Since I can't see any trace of zulu 7 being installed either it may also be possible to remove the zulu repositories entirely from t he playbooks.

**Comment by sej-jackson** [comment]
`zulu` is mentioned in 5x files:
```
find . -type f -exec grep -l zulu {} \;
./AdoptOpenJDK_Unix_Playbook/roles/Common/vars/CentOS.yml
./AdoptOpenJDK_Unix_Playbook/roles/Common/vars/Ubuntu.yml
./AdoptOpenJDK_Unix_Playbook/roles/Common/vars/Debian.yml
./AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/CentOS.yml
./AdoptOpenJDK_ITW_Playbook/roles/Common/tasks/CentOS.yml
```
@Haroon-Khel - is it ok to go ahead and removed the tasks for adding `zulu.repo` from the IcedTea-Web playbook also?
