### ISSUE TITLE
Access to test-marist-ubuntu1604-s390x-1 for docker setup

### ISSUE THREAD

**Issue by dinogun** [AdoptOpenJDK/openjdk-infrastructure#1120]
Need to investigate docker push failures on this box and update setup on jenkins userid

**Comment by dinogun** [comment]
@sxa555 @gdams can one of you help me get access ... docker builds are failing on this box.

**Comment by sxa555** [comment]
Key added to `jenkins@148.100.113.20`

**Comment by dinogun** [comment]
Thanks @sxa555 ! Just wanted to make sure that the access is not temp though, as I need to have access to all the docker build machines (I already do to the rest of them)

**Comment by sxa555** [comment]
@dunogun What is the "setup on the jenkins user ID" that you had to perform. I can't have things hacked on production boxes in a way that isn't documented and repeatable

**Comment by sxa555** [comment]
@dinogun Can you reply to the above comment please?

**Comment by dinogun** [comment]
Looks like I missed the comment. The thing that was missed out was logging into dockerhub repo, because of which the docker images were not getting pushed to dockerhub. Not sure if this has been automated for the other boxes. The encrypted auth info and other docker config options are stored in `.docker/config.json` which can be copied over.

**Comment by sxa555** [comment]
Thanks - we need to have a process in place for putting that on a restricted subset of machines which will be used for this as we don't want to leak keys so these will need to have slightly tighter access control than the others
