### ISSUE TITLE
Migrate trss.adoptopenjdk.net to alternate server (was systemdown)

### ISSUE THREAD

**Issue by smlambert** [AdoptOpenJDK/openjdk-infrastructure#1121]
https://trss.adoptopenjdk.net seems to have disappeared (Error 522 Connection timed out.) Machine seems to have vanished, can not ping it.  Slack msg mentions issue with renewal of go daddy machines.

Slack thread: 
https://adoptopenjdk.slack.com/archives/C5219G28G/p1580748982037500

**Comment by sxa555** [comment]
Godaddy machines are currently all unavailable. I cannot easily bring them back at this time.

**Comment by sxa555** [comment]
We have lost the machine. I have reprovisioned another server on AWS and hopefully we can get it provisioned using the draft playbook that seems to only be in https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/489#issuecomment-472385609

**Comment by Haroon-Khel** [comment]
Aside from the mongodb installation, the playbook mentioned in @sxa555 's comment ran fine on 34.243.30.50. 
I then installed mongodb 4.2.3 manually and started it's service

**Comment by karianna** [comment]
@smlambert - Seems to be back up - can we close this now?

**Comment by smlambert** [comment]
I will let @sxa555 answer definitively, but I think that the intention was to shift trss over to AWS at 34.243.30.50, which is partially set up now.  In the meantime the godaddy instance has come back online, but we will still wish to move it off godaddy due to the way the machines expire (and that it will recur regularly).  So there is still work to be done to move the instance to its new full-time host machine.

**Comment by sxa555** [comment]
Correct - going to use this to track the full recreation and playbook updates moving it to the new server. DNS update and associated SSL certificate are still outstanding.

**Comment by Haroon-Khel** [comment]
@sxa555 Im currently looking into the outstanding items mentioned

**Comment by karianna** [comment]
DNS has propagated to 34.243.30.50

**Comment by Haroon-Khel** [comment]
The new server now accepts https requests, but the browser does not trust the certificate. From the old machine, I have copied over (to the new machine) the files:
```
/etc/ssl/trss_adoptopenjdk_net.crt
/etc/ssl/trss_adoptopenjdk_net.key
```
and configured nginx to point to them. Are there any other cert files, from the old machine that I should know about? @gdams @karianna

**Comment by Haroon-Khel** [comment]
@gdams fixed the last few issues with the https config. I have added redirecting rules to the nginx config to allow for the otherwise inaccessible routes to be accessed (ill be adding these rules to the playbook shortly)

**Comment by sxa555** [comment]
Sounds good - the server is up and running so I'll close this, and we can progress the PR to add the playbook for it separately.
