### ISSUE TITLE
Update playbooks to handle RHEL 8

### ISSUE THREAD

**Issue by sej-jackson** [AdoptOpenJDK/openjdk-infrastructure#1125]
Now that RHEL 8 is available, let's get the playbooks updated to handle it.

Known issues so far:
- `ntp` package is no longer available (use `chrony` instead - should be installed by default)
- `java-1.7.0-openjdk-devel` 
- Asian locales need prereq packages: `glibc-locale-source` `glibc-langpack-XX`
- various problems setting up CPAN, but apparently no longer required (so skip it?)
- gmake build fails - but can use native version 4.2.1 instead

**Comment by Willsparker** [comment]
Due to CentOS and RHEL being very similar, we can look into doing them both at the same time.
