### ISSUE TITLE
git-hg mirroring server needs reprovisioned

### ISSUE THREAD

**Issue by sxa555** [AdoptOpenJDK/openjdk-infrastructure#1128]
Since we lost all of the godaddy servers this week we lost [this machine](https://ci.adoptopenjdk.net/computer/infra-godaddy-ubuntu1604-x64-1/) which we were using to perform the git-hg mirroring, which means https://ci.adoptopenjdk.net has a lot of mirroring jobs backed up. We need this resolved as a matter of urgency. We have playbooks for setting this up, and I have provisioned a new machine at 34.244.17.191 which we can use for this

**Comment by Haroon-Khel** [comment]
@sxa555, my git-hg playbook ran successfully on the machine

**Comment by sxa555** [comment]
Most of the jobs in https://ci.adoptopenjdk.net/job/git-hg/ are now running successfully (I had to sort out the filesystems - added a 200Gb disk as `/home/jenkins/workspace` and also added a suitable private key to be able t push back to git. The system is in jenkins as [infra-aws-ubuntu1804-x64-1/](https://ci.adoptopenjdk.net/computer/infra-aws-ubuntu1804-x64-1/) with five executors to mat7ch what the previous machine had.

The only problems are the two arm mirroring jobs which seem like they might have problems operating on a clean workspace:
```

 * [new tag]               jdk8u92-b34                 -> jdk8u92-b34
Fetching root
fatal: '/home/jenkins/workspace/git-hg/git-hg-aarch32-jdk8u/git-hg/jdk8u/workspace/openjdk-clean-mirror/root/' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```
- https://ci.adoptopenjdk.net/job/git-hg/job/git-hg-aarch64-jdk8u
- https://ci.adoptopenjdk.net/job/git-hg/job/git-hg-aarch32-jdk8u

I've asked @andrew-m-leonard as our resident git-hg expert ;-)

**Comment by sxa555** [comment]
Above error resolved by https://github.com/AdoptOpenJDK/openjdk-build/pull/1529

**Comment by sxa555** [comment]
Note: https://ci.adoptopenjdk.net/computer/infra-godaddy-ubuntu1604-x64-1/ is now back so we have cross-provider backup capacity for these operations now
