### ISSUE TITLE
Access to test machines

### ISSUE THREAD

**Issue by akolarkunnu** [AdoptOpenJDK/openjdk-infrastructure#113]
I work on openjdk regression test failures. I wanted to rerun some failed test cases. So, please provide access to test machines for me.

**Comment by gdams** [comment]
can we have a sponsor from @AdoptOpenJDK/testing to approve this please?

**Comment by smlambert** [comment]
@gdams - please give @akolarkunnu temp access to the test machines (or let me know how I can do it), thanks!

**Comment by gdams** [comment]
@akolarkunnu would you be able to ping me your public ssh key on slack? If you're not currently on our slack channel you can join here: https://adoptopenjdk.net/slack

**Comment by gdams** [comment]
Removing the Temp Infra Access label as @akolarkunnu is a member of the organisation. Permanent jenkins user access will be apropriate

**Comment by gdams** [comment]
key is deployed
