### ISSUE TITLE
Update playbooks to handle SLES 15

### ISSUE THREAD

**Issue by sej-jackson** [AdoptOpenJDK/openjdk-infrastructure#1141]
Now that SLES 15 is available, let's get the playbooks updated to handle it.

Will add list of known issues once I've started testing properly, but @Willsparker has already started work on this, so let's have somewhere to track and discuss what we know so far...

**Comment by Willsparker** [comment]
I feel I should explain the above PR in more depth in here to explain whats already been done: 

The `libelf0` package that couldn't be installed was removed from `Build_Tool_Packages`, and added to the SLES11 and SLES12 specific package lists. 
I added a section for SLES15 specific build packages- I built this list based off SLES12's list and any error messages I got compiling JDK8-J9. Where possible I'd use `-devel`. I replaced `libelf0` with `libelf-devel` and this seems to suffice.
The only package unavailable was `libdwarf-devel` however, so I added the repository containing that, into the `../Common/tasks/SLES.yml` file. 
I also added the same conditionals on `Running ./configure & make for expat on Linux x86-64` as there were for the rest of the tasks involving `expat`.

**Comment by Willsparker** [comment]
Latest commit on the PR is to add SLES15 to the conditions to start the `chronyd` service instead of using `ntp`, and to move `ntp` to SLES11 and SLES12 specific package lists, as `ntp` is available on SLES15-SP0, not SLES15-SP1.

**Comment by Willsparker** [comment]
With the above PR merged, we can include support for SLES15 SP1 too. @sej-jackson was saying that most of the above changes work for SP1, except the package `pulseaudio` doesn't exist in the default repos. There's also an issue with `GIT_Source` not build correctly via ansible, however works manually.

**Comment by Willsparker** [comment]
The above issue with `Git_Source` was due to the machine not having `sudo` installed by default. However, I don't think `sudo` needs to be put into the `./configure and make` steps, as the `become` parameter is set. If this is required, I can add `sudo` to the package list and make a task that inserts the user into the sudoers file.
