### ISSUE TITLE
 test-ibm-ppc64-aix-71-1 configuration issue

### ISSUE THREAD

**Issue by lumpfish** [AdoptOpenJDK/openjdk-infrastructure#1146]
jdk14 test execution jobs fail on test-ibm-ppc64-aix-71-1 when they try to execute java -version for the jdk under test with the messages:
```
11:27:11  Run /home/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image/bin/java -version
11:27:11  libjvm.so preloadLibrary(/home/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image/lib/compressedrefs/libj9vm29.so): 	0509-022 Cannot load module /home/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image/lib/compressedrefs/libj9vm29.so.
11:27:11  	0509-150   Dependent module libc++.a(cxxabi_64.o) could not be loaded.
11:27:11  	0509-022 Cannot load module libc++.a(cxxabi_64.o).
11:27:11  	0509-026 System error: A file or directory in the path name does not exist.
11:27:11  	0509-022 Cannot load module /home/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image/lib/compressedrefs/libj9vm29.so.
11:27:11  	0509-150   Dependent module /home/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image/lib/compressedrefs/libj9vm29.so could not be loaded.
11:27:11  libjvm.so failed to load: j9vm29
```
Is something missing from the machine configuration?

FWIW, tests are running OK on  test-ibm-ppc64-aix-71-2.

**Comment by sxa555** [comment]
Have installed the XLC runtime on the machine for now as per https://www.ibm.com/support/pages/xl-cc-runtime-aix-v16101-fix-pack-december-2018 although I suspect we'll need to put the full xlc16 compiler on that machine in order to build native test code.

**Comment by lumpfish** [comment]
Also occurring on  build-osuosl-ppc64-aix-71-1: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/2239/console

**Comment by lumpfish** [comment]
Test now starts OK on test-ibm-ppc64-aix-71-1

**Comment by sxa555** [comment]
Installed full xlc16 compiler on build-osuosl-ppc64-aix-71-1 - as a build machine it ought to be capable of building all JDK versions
