### ISSUE TITLE
Build a version of OpenSSL 1.1.1d for Windows with VS2017

### ISSUE THREAD

**Issue by sxa555** [AdoptOpenJDK/openjdk-infrastructure#1159]
Ref: https://github.com/AdoptOpenJDK/openjdk-build/issues/1556
We should build a new version and store it in the usual place (https://ci.adoptopenjdk.net/userContent/OpenSSL111win/) for use by the playbooks.

**Comment by sxa555** [comment]
Now available at https://ci.adoptopenjdk.net/userContent/OpenSSL111win/OpenSSL111d-64bitVS2017.tgz - the playbooks and build scripts will need to be updated to install and use this when required

**Comment by Willsparker** [comment]
Just FYI, currently the playbooks will get the source and build OpenSSL 1.1.1d 64 bit, with VS2013. They don't just retrieve it from the `ci.adoptopenjdk.net`.
