### ISSUE TITLE
Additional Linux/x64 build  box

### ISSUE THREAD

**Issue by sxa555** [AdoptOpenJDK/openjdk-infrastructure#1171]
With Linux/x64 being one of our most important platforms, we are running at a slight risk by only having build machines for this platform on a single provider (DigitalOcean). While we haven't had any issues with DO, we should ensure we have at least one extra Linux/x64 build which is hosted on another provider.

Several of our x64 providers cannot supply CentOS6 systems, but SoftLayer can, so I'm assigning this to Tim to provision us a backup Linux/x64 CentOS6 build  machine at SoftLayer (8 core, 16GB, RAM, >=100GB disk as a preferred configuration)

Hostname will be: `build-softlayer-centos6-x64-1`

**Comment by tellison** [comment]
New machine provisioned as requested.

Login details set privately.
