### ISSUE TITLE
build-softlayer-centos6-x64-1 failing to build openj9

### ISSUE THREAD

**Issue by sxa555** [AdoptOpenJDK/openjdk-infrastructure#1176]
HotSpot builds seem ok but the openj9 ones are having issues with this failure on the new machine:
```
/home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-linux-x64-openj9/workspace/build/src/build/linux-x86_64-normal-server-release/vm/compiler/../compiler/net/StreamExceptions.hpp:25:10: fatal error: net/gen/compile.pb.h: No such file or directory
 #include "net/gen/compile.pb.h"
          ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```
Not immediately obvious why but I'll remove the `gcc75` label from [the machine](https://ci.adoptopenjdk.net/computer/build-softlayer-centos6-x64-1) until we can identify a solution.

Ref: https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-linux-x64-openj9/544/console

**Comment by Willsparker** [comment]
A quick search points to it being a Protobuf issue. If I'm reading this right, the file in question is meant to be output here: https://github.com/eclipse/openj9/blob/5f64d16f35681782bcda4c81f236eadc354e2d68/runtime/compiler/CMakeLists.txt#L111

**Comment by Willsparker** [comment]
I've rebuilt Protobuf v3.7.1 on the machine to see if that solves the issue

**Comment by sxa555** [comment]
Doesn't appear to have resolved it based on re-enabling the machine:
https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-linux-x64-openj9-linuxXL/506/console

**Comment by sxa555** [comment]
Removed `gcc75` tag and re-enabled one of the other centos machines until we've fixed this problem.

**Comment by Willsparker** [comment]
Running https://github.com/eclipse/openj9/blob/5f64d16f35681782bcda4c81f236eadc354e2d68/runtime/compiler/CMakeLists.txt#L114 manually causes the required files to be generated, where they're expected to be. So it's not the way it's built thats the issue.

**Comment by Willsparker** [comment]
https://github.com/eclipse/openj9/issues/8681

Closing as this is not an infrastructure issue.

**Comment by sxa555** [comment]
On that basis I have added the `gcc75` label back onto that machine
