### ISSUE TITLE
test-azure-win2012r2-x64-2 not responding

### ISSUE THREAD

**Issue by sxa555** [AdoptOpenJDK/openjdk-infrastructure#1182]
Follow on from #627 
This machine seems to he having problems despite being recovered a few weeks ago.
@adam-thorpe has been trying to get onto it to verify if the setup is good for running tests and therefore re-enabling

**Comment by d3r3kk** [comment]
Will handle it as soon as I can get past 2FA on the Azure portal!

I have a suggestion for managing the Azure access that we need in a slightly different manner - will take it up with @karianna and @gdams.

**Comment by sxa555** [comment]
Any luck?

**Comment by sxa555** [comment]
Also would be useful to know if Azure access can be granted to non-MSFT employees ;-)

**Comment by d3r3kk** [comment]
Anyone with a Microsoft Account (outlook.com/hotmail.com/etc... even non-MS addresses are available to use, although I've not gone that route and cannot speak to it well). 

Simply adding the account to the IAM for the subscription or for the resource itself is enough to grant access. I _should_ be able to get some traction on it this week - our team is doing a 'team week' remote get together and we've been going full tilt unfortunately (and @karianna has been rather intensely under pressure for it, so I'm trying to not be too pushy _yet_!).

**Comment by sxa555** [comment]
@d3r3kk @karianna Any outlook on recovering this system?

**Comment by d3r3kk** [comment]
Can I bring this machine to a full Stop and lose it's public IP address, or will this cause problems with how Jenkins talks to the node?

**Comment by sxa555** [comment]
No that's ok - for most of the UNIX machines it would be a problem, but for windows the machines call in to the jenkins server so the IP address doesn't matter (although we should update `inventory.yml` to store the new IP address.

**Comment by sxa555** [comment]
@adam-thorpe Machine is up and running again now :-)

**Comment by karianna** [comment]
So we can close this now?
