### ISSUE TITLE
Enable fullcore dumping on test-ibm-ppc64-aix-71-1/2

### ISSUE THREAD

**Issue by M-Davies** [AdoptOpenJDK/openjdk-infrastructure#1189]
https://github.com/eclipse/openj9/issues/8652#issuecomment-595377476

Two of our test machines currently don't have [fullcore dumping](https://www.ibm.com/support/knowledgecenter/en/ssw_aix_71/l_commands/lsattr.html) enabled on them which reduces the detail and quantity of the coredumps generated by crashing java applications. 

We should enable fullcore dumping for these two machines to make our javacore dumps more helpful to the VM triage teams. 
- Verify the aix machines have fullcore set to true: `lsattr -D -l sys0 | grep fullcore` 
- Set them to true if not: `chdev -l sys0 -a fullcore=true`[1]

[1] https://www.ibm.com/support/knowledgecenter/ssw_aix_71/c_commands/chdev.html

**Comment by sxa555** [comment]
Assigning to Sej to add to the playbooks in a suitable manner, but I've run this on both of the requested AIX machines, although I haven't rebooted yet - does the following suggest that a reboot is required for this to take effect?
```
p159a01:/ # chdev -l sys0 -a fullcore=true
sys0 changed
p159a01:/ # lsattr -D -l sys0 | grep fullcore
fullcore        false   Enable full CORE dump                               True
p159a01:/ # 
```

**Comment by M-Davies** [comment]
It looks like it’s already set to true in that case.

Reading the documentation, from my understanding, the 2nd value is the default one and the 4th value is what it's currently set to. If you do `chdev -l sys0 -a fullcore=false`, it should set the 4th value to `false`

**Comment by sej-jackson** [comment]
Correct @M-Davies :)

**Comment by M-Davies** [comment]
In that case, once it has been added to the playbooks, this can be closed

**Comment by jdekonin** [comment]
Its already in the playbook, although you could remove the second occurrence if you want.

https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/04d9b5c2d7ab90bf9e1c38287bc185a404324412/ansible/playbooks/aix.yml#L707
and again here 
https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/04d9b5c2d7ab90bf9e1c38287bc185a404324412/ansible/playbooks/aix.yml#L945
