### ISSUE TITLE
build-siteox-solaris10u9-x64-1  has disappeared from jenkins

### ISSUE THREAD

**Issue by sxa555** [AdoptOpenJDK/openjdk-infrastructure#1191]
Was blocking JDK8 pipelines. Have disabled the solaris/x64 build job for now until this is resolved.
It appears that the underlying directory for the machine on the jenkins server file system is there, but it's [no longer showing on  the jenkins UI](https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-solaris-x64-hotspot/) and cannot have jobs scheduled on it

**Comment by gdams** [comment]
reloading the jenkins config fixed this
