### ISSUE TITLE
Upgrade CI box underlying network and add automount script

### ISSUE THREAD

**Issue by karianna** [AdoptOpenJDK/openjdk-infrastructure#1196]
See guidance in Hetzer Cloud UI

**Comment by sxa555** [comment]
New 1TB filesystem mounted on the jenkins jobs directory - existing data copied across, leaving the `workspace` directory where it was. Original directory is in `jobs-ORIGINALFS.200312.sxabak` alongside jobs.

**Comment by karianna** [comment]
And we installed the scripts and networking upgrade.
