### ISSUE TITLE
Clean up Jenkins master SDA disk after Java 14 release

### ISSUE THREAD

**Issue by karianna** [AdoptOpenJDK/openjdk-infrastructure#1198]
We're keeping the jobs directory there as a copy Just in Case, but it's now mounted at sdb going forward.

**Comment by sxa555** [comment]
I removed the openjdk9*build* and openjdk10*build* entries from `jobs` today

**Comment by sxa555** [comment]
Have also removed the build-scripts/jobs/jobs directory from the old location which means there is now over 100GB available for the jenkins master workspace directory which should allow the concurrent playbook work which was implemented recently to work ok

**Comment by sxa555** [comment]
@karianna Do you want me to wipe out all of the backup jobs directory now, or are you happy leaving it with 100GB for now?

**Comment by karianna** [comment]
> @karianna Do you want me to wipe out all of the backup jobs directory now, or are you happy leaving it with 100GB for now?

I think you can wipe :-)

**Comment by sxa555** [comment]
Done. Backup of everything but the `archive` directories is in `jobs-ORIGINALFS.200312.sxabak.tar.xz` (1.4Gb)
