### ISSUE TITLE
nagios.adoptopenjdk.net certificate about to expire

### ISSUE THREAD

**Issue by bblondin** [AdoptOpenJDK/openjdk-infrastructure#12]
Hello,

Your certificate (or certificates) for the names listed below will expire in
19 days (on 26 Jul 17 00:42 +0000). Please make sure to renew
your certificate before then, or visitors to your website will encounter errors.

nagios.adoptopenjdk.net

For any questions or support, please visit https://community.letsencrypt.org/.
Unfortunately, we can't provide support by email.

For details about when we send these emails, please visit
https://letsencrypt.org/docs/expiration-emails/. In particular, note
that this reminder email is still sent if you've obtained a slightly
different certificate by adding or removing names. If you've replaced
this certificate with a newer one that covers more or fewer names than
the list above, you may be able to ignore this message.

If you want to stop receiving all email from this address, click
http://mandrillapp.com/track/unsub.php?u=30850198&id=8fb004715c47471b98c23130d1ca600a.OYLci%2Fk79LBUOvvM5JFmpLp8Mdw%3D&r=https%3A%2F%2Fmandrillapp.com%2Funsub%3Fmd_email%3Dbrad_blondin%2540ca.ibm.com
(Warning: this is a one-click action that cannot be undone)

Regards,
The Let's Encrypt Team

**Comment by bblondin** [comment]
Renewed certificate.

Expires: Wednesday, October 4, 2017 at 7:37:00 AM Eastern Daylight Time

Renew process:
1) log in as root to Nagios server
2) run: letsencrypt renew
3) service apache2 restart
4) service nagios restart

**Comment by gdams** [comment]
@bblondin I can give you a long term certificate from cloudflare if you want to swap it out?

**Comment by bblondin** [comment]
I just scripted it to automatically do it for me

``` bash
# Auto renew letsencrypt certificate every 3 months on the 1st of the month at 3:30am
30 03 01 Jan,Apr,Jul,Oct * /usr/bin/letsencrypt renew
40 03 01 Jan,Apr,Jul,Oct * /usr/sbin/service apache2 restart && /usr/sbin/service nagios restart
```
