### ISSUE TITLE
build-softlayer-centos6-x64-1 - No space left on disk

### ISSUE THREAD

**Issue by smlambert** [AdoptOpenJDK/openjdk-infrastructure#1202]
I have marked it offline, builds failing with this message:

Creating nashorn/dist/nashorn.jar
java.io.IOException: No spwrapper script does not seem to be touching the log file in /home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-linux-x64-openj9@tmp/durable-609226cb
(JENKINS-48300: if on an extremely laggy filesystem, consider -Dorg.jenkinsci.plugins.durabletask.BourneShellScript.HEARTBEAT_CHECK_INTERVAL=86400)
Cannot contact build-softlayer-centos6-x64-1: java.io.IOException: No space left on device
wrapper script does not seem to be touching the log file in /home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-linux-x64-openj9@tmp/durable-609226cb

**Comment by Willsparker** [comment]
Cleared up 13GBs from deleting the JDK13u workspace
