### ISSUE TITLE
Make openssl 1.1.1e available on Windows build machines

### ISSUE THREAD

**Issue by lumpfish** [AdoptOpenJDK/openjdk-infrastructure#1205]
openj9-openjdk releases bundle openssl on Windows and Mac.

On Mac openssl is fetched and built at jdk build time; on Windows it is preloaded onto the build machines under /cygdrive/c/openjdk - e.g. /cygdrive/c/openjdk/OpenSSL-1.1.1d-x86_32

A new version of openssl, 1.1.1e is available which needs adding to the Windows build machines so that it can be bundled in the jdk builds.

**Comment by Willsparker** [comment]
I'll work on adding this to the playbooks too :-)

**Comment by sxa555** [comment]
Hmmm my earlier comment got lost ... We will need a VS2013 version for JDK8, and VS2017 for later versions as per the comments on https://github.com/AdoptOpenJDK/openjdk-build/issues/1556

**Comment by Willsparker** [comment]
Alright - shouldn't be an issue :-)

**Comment by sxa555** [comment]
Only JDK8 is 32-bit for OpenJ9, so 32-bit with VS2017 is not required at present

**Comment by andrew-m-leonard** [comment]
@Willsparker @sxa555 are the current windows build machines updated?

**Comment by Willsparker** [comment]
Not yet - but I was able to confirm yesterday that updating it won't break the builds. Which machines did you want them on-I may have access to a few of them :-)

**Comment by andrew-m-leonard** [comment]
So for the various version, nodes that have these labels:
jdk8 builds: win2012&&mingw-cygwin&&buildj9&&windows&&x64
jdk11 builds: win2012&&vs2017&&buildj9&&windows&&x64
jdk14 builds: buildj9&&windows&&x64

**Comment by Willsparker** [comment]
Okay, the only machines I have access to are: 
`build-azure-win2008r2-x64-1` &
`build-azure-win2008r2-x64-2`. 
ci.adoptopenjdk.net is currently down so I'm unable to check which nodes have those tags

**Comment by Willsparker** [comment]
As an FYI, for the `build-softlayer-win2012r2-x64` machines, I've had to edit the PATH environment variable to remove the `" M/` at the end, as it was causing VS2017 Developer Command prompt to fail : http://www.blinnov.com/en/2010/06/04/microsoft-was-unexpected-at-this-time/

**Comment by Willsparker** [comment]
The machines (I believe) we're putting OpenSSL-1.1.1e on:
- [ ] build-azure-win2008r2-x64-1
- [ ] build-azure-win2008r2-x64-2
- [ ] build-softlayer-win2012r2-x64-1
- [ ] build-softlayer-win2012r2-x64-2

**Comment by Willsparker** [comment]
ref: #1239 
I think, given that the machines are going to be replaced, as well as the win2008r2 machines not building OpenJ9, I see no reason for them to need OpenSSL-1.1.1e on them. Once the playbook update PR is in, this issue can be closed :-)
