### ISSUE TITLE
s390x machine git tags fetch failure

### ISSUE THREAD

**Issue by M-Davies** [AdoptOpenJDK/openjdk-infrastructure#1233]
- https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-linux-s390x-openj9-linuxXL/132/
- build-marist-rhel77-s390x-2 fails to fetch jdk11 tags from https://github.com/ibmruntimes/openj9-openjdk-jdk11. This is being reported as a machine issue due to the other jdk11 builds fetching references without issue.
```
Pulling latest changes from git openjdk source repository
Fetching origin
error: cannot lock ref 'refs/tags/jdk-11.0.7+4': unable to resolve reference 'refs/tags/jdk-11.0.7+4': reference broken
From https://github.com/ibmruntimes/openj9-openjdk-jdk11
 ! [new tag]               jdk-11.0.7+4 -> jdk-11.0.7+4  (unable to update local ref)
 * [new tag]               jdk-11.0.7+7 -> jdk-11.0.7+7
 * [new tag]               jdk-11.0.7+8 -> jdk-11.0.7+8
error: Could not fetch origin
```

**Comment by Willsparker** [comment]
I believe this is due to a corrupted Git repo on the machine. We can take the steps to try and recover it : https://stackoverflow.com/a/50346081 . Or we could just reclone the repository :-)

**Comment by M-Davies** [comment]
Its also possible a cache clean might resolve this

**Comment by sxa555** [comment]
Deleted that workspace earlier and it appears to have resolved this
