### ISSUE TITLE
x64&&centos&&linux&&gcc75 label combo all machines offline

### ISSUE THREAD

**Issue by jerboaa** [AdoptOpenJDK/openjdk-infrastructure#1234]
https://ci.adoptopenjdk.net/label/x64&&centos&&linux&&gcc75/

Shows only one offline node. It whould be great if we had at least 1 such build machine online.

**Comment by sxa555** [comment]
It's back online now - I need to check into that since we should have 7.5 on all the machines now.

**Comment by sxa555** [comment]
Labels added back onto all three build machines
