### ISSUE TITLE
build-digitalocean-centos69-x64-2 Out of Space 

### ISSUE THREAD

**Issue by M-Davies** [AdoptOpenJDK/openjdk-infrastructure#1235]
https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-linux-x64-openj9-linuxXL/537/consoleFull

[build-digitalocean-centos69-x64-2](https://ci.adoptopenjdk.net/computer/build-digitalocean-centos69-x64-2/)

```
Creating images/lib/ct.sym
Compiling tools to generate DDR pointer classes and structure stubs
/bin/cp: writing `/home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-linux-x64-openj9-linuxXL/workspace/build/src/build/linux-x86_64-normal-server-release/images/j2sdk-image/jre/lib/rt.jar': No space left on device
Images.gmk:290: recipe for target '/home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-linux-x64-openj9-linuxXL/workspace/build/src/build/linux-x86_64-normal-server-release/images/j2sdk-image/jre/lib/rt.jar' failed
gmake[2]: *** [/home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-linux-x64-openj9-linuxXL/workspace/build/src/build/linux-x86_64-normal-server-release/images/j2sdk-image/jre/lib/rt.jar] Error 1
```

**Comment by sxa555** [comment]
We're losing 25Gb to https://github.com/AdoptOpenJDK/openjdk-build/issues/1528 but I've cleared that up for now so the machine should be ok for tonight's builds

**Comment by karianna** [comment]
@sxa555 shall we close or more permanent work to do?

**Comment by sxa555** [comment]
As soon as PR tester runs again the problem will recur if 1528 isn't resolved, so yes there is more to do

**Comment by sxa555** [comment]
Cleared - for now ... There was some leakage in the jdk8 hotspot workspace
