### ISSUE TITLE
Replace win2008 machines with win2012

### ISSUE THREAD

**Issue by gdams** [AdoptOpenJDK/openjdk-infrastructure#1239]
Once https://github.com/AdoptOpenJDK/openjdk-build/pull/1638 lands we will no longer need win2008R2 build machines. 

My proposal is that we replace them with two new 2012 machines so that we have a larger pool of 2012.

Steps:

- [x] Merge https://github.com/AdoptOpenJDK/openjdk-build/pull/1638
- [x] Spin up 2 new 2012 machines (leave 2008 running for now)
- [x] Destroy old Softlayer JCK machine
- [x] Run Ansible on them and add to jenkins
- [x] Ensure that builds run on them
- [x] Remove 200R2 machines are a few weeks

**Comment by gdams** [comment]
We do also have a JCK windows machine that we should re-purpose at the same time (https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/master/ansible/inventory.yml#L190)

**Comment by Willsparker** [comment]
I'm happy to run the playbooks on them and confirm builds run on them 👍

**Comment by gdams** [comment]
@tellison has confirmed that the JCK machine still exists so I've requested that he re-provision it as a fresh image

**Comment by tellison** [comment]
Have we checked with the OpenJ9 folks about their build requirements on Windows?

**Comment by gdams** [comment]
@tellison all of the OpenJ9 builds are running on win2012 the only thing that was still using 2008 is JDK8u Hotspot

**Comment by gdams** [comment]
two Azure 2012R2 machines have been handed to @Willsparker

**Comment by gdams** [comment]
https://ci.adoptopenjdk.net/computer/build-azure-win2012r2-x64-1/
https://ci.adoptopenjdk.net/computer/build-azure-win2012r2-x64-2/

both added to jenkins

**Comment by tellison** [comment]
The old Softlayer JCK machine has been decommissioned, and a shiny new test machine provisioned in its place.  Name is `test-win2012-2.adoptopenjdk.net` and details sent privately to @gdams in the first instance to share with infra team.

**Comment by Willsparker** [comment]
The 2 new `build-azure-2012r2-x64` machines have had the playbook ran on them, and are connected to Jenkins

**Comment by gdams** [comment]
Installer jobs failing with:

```bash
Expand-Archive : The term 'Expand-Archive' is not recognized as the name of a 
cmdlet, function, script file, or operable program. Check the spelling of the 
name, or if a path was included, verify that the path is correct and try again.
```

this is because the machines had PowerShell 4.0 rather than 5.

To fix I installed WMF 5.1 on both machines (https://docs.microsoft.com/en-gb/powershell/scripting/wmf/setup/install-configure?view=powershell-7)

**Comment by gdams** [comment]
Shortnames were not enabled on drive C:

fix:
```batch
fsutil 8dot3name set C: 0
fsutil file setshortname "C:\Program Files (x86)\WiX Toolset v3.14" WIXTOO~1.14
```

**Comment by gdams** [comment]
missing the codesign cert. @Willsparker is creating a new role for this

**Comment by gdams** [comment]
builds all passing, there is some work to automate the steps above.

**Comment by gdams** [comment]
All manual steps listed above have now been automated, big thank you to @Willsparker for all the hard work!

**Comment by gdams** [comment]
2008R2 machines have been destroyed, I left a disk image that we can use to bring back up if we need to
