### ISSUE TITLE
Decommission Softlayer machine (158.176.72.88)

### ISSUE THREAD

**Issue by tellison** [AdoptOpenJDK/openjdk-infrastructure#1248]
The machine `jck-softlayer-x64-rhel-7.adoptopenjdk.net (158.176.72.88)` is no longer being used.

This is a tracking issue to decommission it.  As always, machines can be created on demand if required.

Looking for approval from infra team 
//cc @sxa555

**Comment by sxa555** [comment]
Yep fine by me as I cannot find any trace of it being in use - thanks

**Comment by sxa555** [comment]
Yep fine by me as I cannot find any trace of it being in use - thanks

**Comment by tellison** [comment]
Done
