### ISSUE TITLE
Need access to test-packet-armv8-ubuntu-16-04

### ISSUE THREAD

**Issue by knn-k** [AdoptOpenJDK/openjdk-infrastructure#1262]
I need an access to test-packet-armv8-ubuntu-16-04 for investigating failures that don't occur on other machines.

**Comment by knn-k** [comment]
One of the failures to investigate: https://github.com/eclipse/openj9/issues/9048

**Comment by sxa555** [comment]
Created account `konno@147.75.74.50` and given access to it

**Comment by Haroon-Khel** [comment]
@knn-k I assume this request was related to https://github.com/eclipse/openj9/issues/9042. Since that issue has been closed, do you still need access to test-packet-armv8-ubuntu-16-04?

**Comment by knn-k** [comment]
You can disable my account at test-packet-armv8-ubuntu-16-04 for now.
Thanks.

**Comment by karianna** [comment]
@sxa in case he missed it

**Comment by Haroon-Khel** [comment]
Your account has been removed from the machine
