### ISSUE TITLE
Add jhuttana to team openjdk-upstream-binary-rel-eng

### ISSUE THREAD

**Issue by jerboaa** [AdoptOpenJDK/openjdk-infrastructure#1265]
openjdk-upstream-binary-rel-eng team got created for people who should have write access to openjdkXX-upstream-binaries. I'd like to add @jhuttana to this team as she'll be doing some release work there going forward.

@AdoptOpenJDK/tsc OK?

**Comment by gdams** [comment]
+1

**Comment by sxa555** [comment]
+1 from me as I trust Severin's judgement :-)

**Comment by jerboaa** [comment]
@jhuttana please add some basic info to your Github profile. Thanks!

**Comment by jhuttana** [comment]
> @jhuttana please add some basic info to your Github profile. Thanks!

@jerboaa @sxa555 Sure I will update required information to my profile :)
Thank you both!

**Comment by jerboaa** [comment]
@jhuttana Thanks!

**Comment by jerboaa** [comment]
@sxa555 @karianna In order to get @jhuttana added to that team we need to get her added to the org first. Apparently I don't have that power :-(

**Comment by sxa555** [comment]
Thanks - invited @jhuttana to both the project and the `openjdk-upstream-binary-rel-eng` team. Welcome!

**Comment by jhuttana** [comment]
> Thanks - invited @jhuttana to both the project and the `openjdk-upstream-binary-rel-eng` team. Welcome!

Thank you so much!
