### ISSUE TITLE
Need access to test-aws-ubuntu1804-armv8-1

### ISSUE THREAD

**Issue by knn-k** [AdoptOpenJDK/openjdk-infrastructure#1267]
I need an access to test-aws-ubuntu1804-armv8-1 for investigating failures that don't occur on other machines.

**Comment by knn-k** [comment]
Link to the issue to investigate: https://github.com/eclipse/openj9/issues/9042

**Comment by sxa** [comment]
Access granted to `konno@34.243.202.254` account on [test-aws-ubuntu1804-armv8-1](https://ci.adoptopenjdk.net/computer/test-aws-ubuntu1804-armv8-1/)

**Comment by knn-k** [comment]
Thank you.  I can ssh to it now.

**Comment by Haroon-Khel** [comment]
@knn-k I assume this request was related to https://github.com/eclipse/openj9/issues/9042. Since that issue has been closed, do you still need access to test-aws-ubuntu1804-armv8-1?

**Comment by knn-k** [comment]
You can disable my account at test-aws-ubuntu1804-armv8-1 for now.
Thanks.

**Comment by Haroon-Khel** [comment]
Your account on this machine has been disabled
