### ISSUE TITLE
switch ppcle build machine to be Ubuntu 16.04

### ISSUE THREAD

**Issue by gdams** [AdoptOpenJDK/openjdk-infrastructure#127]
we should remove the fedora and ubuntu 16.10 machines and deploy two Ubuntu 16.04 machines as Ubuntu 16.04 is the standard build machine that we have been using everywhere else

**Comment by sxa555** [comment]
@gdams Is there anything blocking this - presumably since we have the hardware the re-image is pretty trivial?

**Comment by gdams** [comment]
no should be a case of deleting the old machine, re provisioning with ubuntu 16.04 and checking that we can build on it

**Comment by gdams** [comment]
machine has been switched. I will close this now and confirm that the openj9 builds pass
