### ISSUE TITLE
AIX machines fall over at cleanws()

### ISSUE THREAD

**Issue by M-Davies** [AdoptOpenJDK/openjdk-infrastructure#1279]
- https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-aix-ppc64-openj9/
- https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-aix-ppc64-hotspot/

Seen on both [build-osuosl-ppc64-aix-71-1](https://ci.adoptopenjdk.net/computer/build-osuosl-ppc64-aix-71-1/) and [build-osuosl-ppc64-aix-71-2](https://ci.adoptopenjdk.net/computer/build-osuosl-ppc64-aix-71-2/), the build completes successfully and archives its artifacts but fails to clean up afterwards. 
```
[Pipeline] cleanWs
build-osuosl-ppc64-aix-71-2 was marked offline: Connection was broken: java.io.IOException: Unexpected EOF
	at hudson.remoting.ChunkedInputStream.readUntilBreak(ChunkedInputStream.java:99)
	at hudson.remoting.ChunkedCommandTransport.readBlock(ChunkedCommandTransport.java:39)
	at hudson.remoting.AbstractSynchronousByteArrayCommandTransport.read(AbstractSynchronousByteArrayCommandTransport.java:34)
	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:63)
```

Could do with a restart to see if that resolves it?

**Comment by sxa** [comment]
They both seem to be online at the moment despite that error message - did someone bring them back?

**Comment by M-Davies** [comment]
They get this error at the same point every time for the last 3 builds.  I don't think someone is turning them off and on again mid build

**Comment by sxa** [comment]
> They get this error at the same point every time for the last 3 builds. I don't think someone is turning them off and on again mid build

I wasn't suggesting so - it just looked like `build-osuosl-ppc64-aix-71-2 was marked offline` was indicating that jenkins had marked it offline during the build due to the connection failure, but that may not be correct. There's nothing obvious wrong with the machines at the moment though so unclear why this would be happening, or why it's just on JDK8. Will take a look at the `/tmp` file system

**Comment by sxa** [comment]
I couldn't find aything obvious wrong on the machine and I rean a couple of JDK8 builds today without incident which makes me wonder if somethign is happening at a particular time on the machines (Which would explain why it only hits the builds running through the regularly scheduled nightly pipeline)

On this basis, I don't think it'll impact the GA builds this week, but I'll leave this open as if there is a recurring issue now appearing we'll need to mitigate it one way or another

**Comment by M-Davies** [comment]
https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-aix-ppc64-openj9/ seems to be fine now. Hotspot failed [last night](https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-aix-ppc64-hotspot/537/consoleFull) on `build-osuosl-ppc64-aix-71-1`.

**Comment by M-Davies** [comment]
Next two builds passed.

**Comment by M-Davies** [comment]
Next builds passed on `build-osuosl-ppc64-aix-71-1` and `build-osuosl-ppc64-aix-71-2`. I'm going to close this but it can always be reopened if this pops up again
