### ISSUE TITLE
Understand why Windows vagrant VMs need --force to reboot

### ISSUE THREAD

**Issue by sxa** [AdoptOpenJDK/openjdk-infrastructure#1281]
Split out from the comments in https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/1273#issuecomment-613877327

**Comment by Willsparker** [comment]
As additional information, The `vagrant reload` ( rebooting the VM via vagrant) is required to remount the shared folder on the VM, as tasks that run `win_reboot` (i.e. https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/8b955671b060eef7770febec312172b270ecc48c/ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/cygwin/tasks/main.yml#L122 ) , are what cause the shared folder to be lost in the first place.

**Comment by Willsparker** [comment]
I'm in the process of trying to recreate this issue with:

https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/606/
Although this failed, It was still running when `ssh`ing into the machine the job runs on. `vagrant halt` worked as expected.

https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/607/

**Comment by Willsparker** [comment]
https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/615/

I was able to get an example of `vagrant halt` working, without force. Also did this locally. I'm going to try and get another example of it working- if it does then I'll close this issue :-)

**Comment by Willsparker** [comment]
https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/617/OS=Win2012,label=infra-softlayer-ubuntu1804-x64-1/consoleFull

Another example of `vagrant halt` working by itself - seems `--force` isn't needed anymore.
