### ISSUE TITLE
Adopt Jenkins Mac machine cannot generate core dump due to /cores permission setting

### ISSUE THREAD

**Issue by LongyuZhang** [AdoptOpenJDK/openjdk-infrastructure#1282]
When generating core dump on Adopt Jenkins Mac machines, it shows error message:
```
15:02:04       [java] JVMDUMP032I JVM requested System dump using '/Users/jenkins/workspace/Grinder_Sandbox/openjdk-tests/functional/cmdLineTests/lockWordAlignment/core.20200408.120204.84960.0001.dmp' in response to an event
15:02:11       [java] JVMDUMP012E Error in System dump: The core file created by child process with pid = 84965 was not found. Expected to find core file with name "/cores/core.84965"
```
in https://ci.adoptopenjdk.net/view/work%20in%20progress/job/Grinder_Sandbox/1249.

A same issue ever happened on Internal Jenkins Mac machine with GCCheck test (https://github.com/eclipse/openj9/issues/3791), but got fixed after @jdekonin changed the permission setting for /cores ```chown -R root:staff /cores```. And previously mentioned code also works successfully on internal mac machine after this change.

Currently, the Internal Mac /cores permission is root:staff, while Adopt Mac /cores is root:admin (https://github.com/AdoptOpenJDK/openjdk-tests/issues/1564). Could you change this permission setting to see if it fixes this problem? Really appreciate!

fyi @sxa @jdekonin @llxia

**Comment by lumpfish** [comment]
A number of openj9 functional tests are still failing due to this issue.  With the Jan 2021 release coming up soon it would be good if this could be fixed to increase the test pass rate.  @gdams - are you able to look into this?

**Comment by sxa** [comment]
@gdams Can you confirm the status of this please? I've heard that it doesn't work properly on recent macos versions?

**Comment by andrew-m-leonard** [comment]
I can confirm box test-macstadium-macos1013-x64-1 which has:
```
drwxrwxr-t   3 root  staff    96 11 Feb 03:22 cores
```
Passes this test.

**Comment by andrew-m-leonard** [comment]
Grinders to find out which ones need fixing:
https://ci.adoptopenjdk.net/job/Grinder/6720/
https://ci.adoptopenjdk.net/job/Grinder/6721/
https://ci.adoptopenjdk.net/job/Grinder/6722/
https://ci.adoptopenjdk.net/job/Grinder/6723/
https://ci.adoptopenjdk.net/job/Grinder/6724/

**Comment by andrew-m-leonard** [comment]
Core issues fixed, ansible update applied to correct permissions: https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/1811
