### ISSUE TITLE
release build failure on Softlayer/JDK11/Windows

### ISSUE THREAD

**Issue by sxa** [AdoptOpenJDK/openjdk-infrastructure#1284]
Failed on the [regular Softlayer build machine](https://ci.adoptopenjdk.net/computer/build-softlayer-win2012r2-x64-2/) (job [516](https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-windows-x64-hotspot/516/), succeeded on [the new one at Azure](https://ci.adoptopenjdk.net/computer/build-azure-win2012r2-x64-2/) (job [517](https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-windows-x64-hotspot/517/)]

Have locked the 516 console log to allow fo investigation. I'd like to have someone look at and understand this one instead of just cleaning up the workspace and retrying if possible.

**Comment by sxa** [comment]
It's now back up and running (I've just connected to it) but still showing a service failure in the admin console. We should see if the machine is now capable of running a build again if all of the windows release builds for this cycle have now been completed.
![image](https://user-images.githubusercontent.com/6487691/79561714-b439d380-80a1-11ea-8851-ce8f5c2383b2.png)

**Comment by gdams** [comment]
rebuild of failed job: https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-windows-x64-hotspot/522/

**Comment by gdams** [comment]
same failure, I'll keep the machine marked offline.

**Comment by Willsparker** [comment]
I've had a look at the particular file and it is _there_, however the path looks a little funny in the console output: 
`c1xx: fatal error C1083: Cannot open source file: '../../../../..c:/cygwin64/tmp/openjdk-build/workspace/build/src/build/windows-x86_64-normal-clientANDserver-release/hotspot/variant-server/libjvm/gtest/objs/BUILD_GTEST_LIBJVM_pch.cpp': No such file or directory`
Specifically the `..c:/` bit.

**Comment by Willsparker** [comment]
I noticed that on the failing build has 
`BUILD_CONFIG[WORKSPACE_DIR]="/tmp/openjdk-build/workspace"`,
Whereas the succeeding builds on JDK11 w/ the azure machines has `BUILD_CONFIG[WORKSPACE_DIR]="/cygdrive/j/jenkins/tmp/workspace"` - The cygdrive path.

In addition to this, a succeeding JDK14 build, that ran on the softlayer machine (https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk14u/job/jdk14u-windows-x64-hotspot/13/) also had that variable set to a cygdrive path: 
`BUILD_CONFIG[WORKSPACE_DIR]="/cygdrive/c/Users/jenkins/workspace/build-scripts/jobs/jdk14u/jdk14u-windows-x64-hotspot/workspace"`

**Comment by Willsparker** [comment]
https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-windows-x64-hotspot/522/ws/
The workspaces for the build list `C:/cygwin64/tmp`, whereas the succeeding build has `J:/jenkins/tmp`. I think the the workspace for the failing build is meant to be `C:/tmp`. That would cause `BUILD_CONFIG[WORKSPACE_DIR]` to be `/cygdrive/c/tmp/workspace`

**Comment by Willsparker** [comment]
ref : https://github.com/AdoptOpenJDK/openjdk-build/pull/1647 https://github.com/AdoptOpenJDK/openjdk-build/pull/1639

@gdams and I had a look and have replicated it, using `build-softlayer-win2012r2-x64-1` so, it's those ones specifically. `https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-windows-x64-hotspot/533/console`

We've narrowed it down to being a change with the two pull requests linked above. Subsequent runs of the same job ( 534-537 ) have been overriding the `CYGWIN_WORKSPACE` variable with various paths to see what works. It seems to be replacing `/cygdrive/c/` with `c:/`, which is what's causing the `..c:/` to appear in paths.

**Comment by sxa** [comment]
Any outlook on a fix for this?

**Comment by Willsparker** [comment]
This is the particular line that's the issue: https://github.com/AdoptOpenJDK/openjdk-build/blob/0cae7e2e783c11631c3a2671ca1612d22c098414/pipelines/build/common/openjdk_build_pipeline.groovy#L518

The file path needs to be changed in such a way that the build scripts 'like' it. We were testing different values by changing the `CYGWIN_WORKSPACE` variable (that we configured the machine, in Jenkins, to have), however the values we tried didn't work for various reasons.

| CYGWIN_WORKSPACE Var                   | Run       |
|----------------------------------------|-----------|
| C:/cygwin64/tmp/openjdk-build          | 533       |
| c:/cygdrive/c/tmp/openjdk-build        | 534       |
| /tmp/openjdk-build                     | 535       |
| /cygdrive/c/tmp/openjdk-build          | 536 / 537 |
| /C:/cygwin64/tmp/openjdk-build/        | 538       |
| /cygdrive/c/cygwin64/tmp/openjdk-build | 544       |

**Comment by Willsparker** [comment]
The paths are required to be in a Windows format, otherwise the builds will fail with the initial git clone (as that is ran in `git-bash`). Therefore, no paths starting with `/cygdrive/c/` will work.
In addition, ommiting the `/tmp` part of the file path stops conflict between the `C:/cygwin64/tmp` and the `C:/tmp` folders. In the above PR, I opted for `workspace` as it's representative of what the folder does.
