### ISSUE TITLE
Rebuild macOS 10.10 build machines as macOS 10.14

### ISSUE THREAD

**Issue by gdams** [AdoptOpenJDK/openjdk-infrastructure#1290]
Now that JDK8 is also using 10.14 we should rebuild our two 10.10 machines as newer 10.14 ones.

**Comment by gdams** [comment]
cancelled build-macstadium-macos1010-2 and created build-macstadium-macos1014-2

**Comment by gdams** [comment]
added first machine https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/1297

**Comment by gdams** [comment]
@sxa any issues with me migrating the second 10.10 mac to 10.14 now?

**Comment by sxa** [comment]
I've jsut marked https://ci.adoptopenjdk.net/computer/build-macstadium-macos1010-x64-1/ offline so let's give it a day or so (or even oeer the weekend) to verify completely that nothing is tied to it before going ahead :-)

**Comment by sxa** [comment]
@gdams Can we progress the build machine migration now?

**Comment by gdams** [comment]
I have provisioned a new 10.14 build machine in macstadium and cancelled the last 10.10 build machine

**Comment by gdams** [comment]
https://ci.adoptopenjdk.net/computer/build-macstadium-macos1014-x64-3/ added to jenkins
