### ISSUE TITLE
build-digitalocean-centos69-x64-1 attempting to build m2 in nightlies

### ISSUE THREAD

**Issue by M-Davies** [AdoptOpenJDK/openjdk-infrastructure#1291]
https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-linux-x64-openj9

This nightly job is attempting to fetch the remote ref `openj9-0.20.0-m2` even though m2 is now over for 0.20.0. Looking at the last three nights, this only seems to have been occuring on `build-digitalocean-centos69-x64-1`
```
Retrieving cacerts file if needed
origin	https://github.com/ibmruntimes/openj9-openjdk-jdk11.git (fetch)
origin	https://github.com/ibmruntimes/openj9-openjdk-jdk11.git (push)
jdk11
origin	https://github.com/ibmruntimes/openj9-openjdk-jdk11.git (fetch)
Resetting the git openjdk source repository at /home/jenkins/workspace/build-scripts/jobs/jdk11u/jdk11u-linux-x64-openj9/workspace/build/src in 10 seconds...
Pulling latest changes from git openjdk source repository
Fetching origin
fatal: Couldn't find remote ref refs/heads/openj9-0.20.0-m2
error: Could not fetch origin
```

**Comment by sxa** [comment]
It's from `git fetch --tags` in https://github.com/AdoptOpenJDK/openjdk-build/blob/master/sbin/prepareWorkspace.sh#L81 - @pshipton @danheidinga do the milestone tags get removed from the extensions repository? I'm not quite sure why else something like this would occur.

For now I'l delete the workspace on the impacted build machine and let it reclone

@johnoliver FYA - is this something we'd be able to cope with? This is a nightly and the job is not trying to build from the mentioned tag.

**Comment by pshipton** [comment]
There are no tags created in the extensions repo. The extensions branch openj9-0.20.0 has moved on from the m2 content to the release content.

At OpenJ9/OMR, there is still a tag i.e.
https://github.com/eclipse/openj9/releases/tag/openj9-0.20.0-m2
https://github.com/eclipse/openj9-omr/releases/tag/openj9-0.20.0-m2

**Comment by sxa** [comment]
Backup created in openj9-infra1291.tgz in jenkins homedir if @johnoliver for @johnoliver to investigate further but I've removed the workspace directory from the machine so it will get repopulated from scratch on the next run on that system, therefore this is resolved.
