### ISSUE TITLE
Setup new RHEL8/x64 system to improve testing coverage

### ISSUE THREAD

**Issue by sxa** [AdoptOpenJDK/openjdk-infrastructure#1293]
`54.246.216.49` is available with a fresh install of RHEL8 - @Haroon-Khel and I have access for now until it is installed. Needs the ansible playbooks run on it then we can add it into the test farm.
FYI @smlambert

**Comment by sxa** [comment]
Online in jenkins at https://ci.adoptopenjdk.net/computer/test-aws-rhel8-x64-1/log - can we try running some grinders on it and see if it's ok, and also add it to the inventory.yml file

**Comment by Haroon-Khel** [comment]
Running a sanity job on the machine
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/2946/

**Comment by Haroon-Khel** [comment]
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/2946/testReport/

**Comment by sxa** [comment]
Thanks @Haroon-Khel - we'll leave that in jenkins to be used along with the other test systems!

References:
- [Issue for adding support for CentOS/RHEL8](https://github.com/AdoptOpenJDK/openjdk-website/issues/672)
- [PR to add support for CentOS8 to the playbooks](https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/1131)
