### ISSUE TITLE
Set Up new Ubuntu 20.04/x64 system to improve testing coverage 

### ISSUE THREAD

**Issue by sxa** [AdoptOpenJDK/openjdk-infrastructure#1299]
34.241.242.10 is available with a fresh install of Ubuntu 20.04LTS - @Haroon-Khel and I have access for now until it is installed. Needs the ansible playbooks run on it then hopefully [jenkins will connect to it](https://ci.adoptopenjdk.net/computer/test-aws-ubuntu2004-x64-1/) and we can add it into the test farm and run a Grinder on it.
FYI @smlambert

**Comment by Haroon-Khel** [comment]
Running a sanity job on the machine
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/2955/

**Comment by Haroon-Khel** [comment]
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/2955/testReport/
Only one failure. A familiar locale test failure `java/util/Locale/LocaleCategory.java.LocaleCategory`

**Comment by Haroon-Khel** [comment]
Like https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1268, I have fixed the test locally, but it continues to fail in Jenkins. @sxa The machine needs to be disconnected and reconnected from Jenkins, for the test to pass

**Comment by sxa** [comment]
I have granted you access to the two new machines in jenkins (this one and the rhel8 one) so you can go to the machine and click "Disconnect" and once it's disconnected click the button to relaunch the agent

**Comment by Haroon-Khel** [comment]
Test passes https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/2959/testReport/

**Comment by sxa** [comment]
Two new distributions this week - I'm taking that as a win! Thanks.

**Comment by Haroon-Khel** [comment]
FYI @sxa the fix I implemented was simoky using the command `update-locale LANG=en_US.UTF-8`, which auto updated the locale
