### ISSUE TITLE
Verify test-aws-win2019-x64-1

### ISSUE THREAD

**Issue by sxa** [AdoptOpenJDK/openjdk-infrastructure#1307]
Doesn't seem to be able to start the jenkins agent as a service - it comes up with an error on the jenkins side when you try to start it. I've launched it manually with the `startjenkins.cmd` script for now to connect it, but since it doesn't currently have the `ci.role.test` label on it we should probably run a couple of Grinders to ensure that it works ok before adding that label onto it.

**Comment by Willsparker** [comment]
Brief initial look:
- The service starts okay and it does connect to Jenkins, but it seems to be unstable- I'm yet to complete a grinder run on it.
- After a reboot cycle, I had trouble connecting to the Jenkins user - at that same point, the service failed to start (without error message it said..). Stopping the service from start automatically on startup and then rebooting seemed to fixed this issue.
- I've set the service to  have an `automatic (delayed)` start, therefore it'll start 2 minutes after the last `automatic` service has started. I've started a [Grinder (](https://ci.adoptopenjdk.net/job/Grinder/3068/console) running sanity.openjdk to see if it works. If this succeeds, I'll do another reboot cycle and see if I can recreate the success.

**Comment by Willsparker** [comment]
Above grinder didn't work, unfortunately. The service stopped halfway through and didn't reboot itself. I started it manually however it error'd on Jenkins' end. I then started it again and it displayed the error message mentioned above:
```
Windows could not start the Jenkins agent (jenkinsslave-C__Users_jenkins) service on Local Computer.
The service did not return an error. This could be an internal Windows error or an internal service error. 
If the problem persists, contact your system administrator
```
Given the agent works when being launched with the `startjenkins.cmd` script, I would assume the installation of the service is broken, so I'll try re-installing it.

**Comment by Willsparker** [comment]
Reinstalling the Jenkins agent seems to have done the trick : https://ci.adoptopenjdk.net/job/Grinder/3071/console
I created a new node `tes-aws-win2019-x64-3` which was a copy of `-1`, and installed that service. I'm going to delete the `test-aws-win2019-x64-1` node and rename the `-3` node to be `-1`. 
Once that's done, I'll run another Grinder just to be cautious and then the tag can be added.

**Comment by Willsparker** [comment]
https://ci.adoptopenjdk.net/job/Grinder/3072/
Seems to be okay. I'm going to add the label now, feel free to reopen if I missed something
