### ISSUE TITLE
test-softlayer-win2012r2-x64-2 fails to instantiate

### ISSUE THREAD

**Issue by M-Davies** [AdoptOpenJDK/openjdk-infrastructure#1310]
`test-softlayer-win2012r2-x64-2` has been failing to run tests for two nights. Looks like it needs a clean down.

First failure was a corrupt repository on https://ci.adoptopenjdk.net/view/Test_openjdk/job/Test_openjdk11_j9_sanity.openjdk_x86-64_windows/197
```
 > git rev-parse --is-inside-work-tree # timeout=10
ERROR: Workspace has a .git repository, but it appears to be corrupt.
hudson.plugins.git.GitException: Command "git rev-parse --is-inside-work-tree" returned status code 128:
stdout: 
stderr: fatal: not a git repository (or any parent up to mount point /cygdrive)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
```
Second failure was a failed cleanup https://ci.adoptopenjdk.net/view/Test_openjdk/job/Test_openjdk11_j9_sanity.openjdk_x86-64_windows/198
```
ERROR: Failed to clean the workspace
jenkins.util.io.CompositeIOException: Unable to delete 'C:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows\openjdk-tests'. Tried 3 times (of a maximum of 3) waiting 0.1 sec between attempts.
```

**Comment by Willsparker** [comment]
Deleted the folder, lets see if it happens again. 
Similar to #1328

**Comment by Willsparker** [comment]
Seems my clear-up has worked. It's got passed where it failed before :-)
https://ci.adoptopenjdk.net/view/Test_openjdk/job/Test_openjdk11_j9_sanity.openjdk_x86-64_windows/205/
Closing..

**Comment by M-Davies** [comment]
Thanks @Willsparker
