### ISSUE TITLE
Cleanup leftover tarballs after playbook runs

### ISSUE THREAD

**Issue by gdams** [AdoptOpenJDK/openjdk-infrastructure#1312]
Several tarballs are still left in /tmp

```
drwxr-xr-x 15 root    root       4096 May  6 10:25 cmake-3.11.4
-r--r-----  1 root    root    7955301 May  6 10:19 cmake-3.11.4.tar.gz
-rw-r--r--  1 root    root     235553 May  6 10:17 cuda_install_32499.log
-rw-r--r--  1 root    root    1370296 May  6 10:17 cuda-installer-32600
-rw-r--r--  1 root    root         88 May  6 10:17 cuda-installer-32767
drwxr-xr-x  2 root    root       4096 May  6 10:22 hsperfdata_root
drwxr-xr-x  9 jenkins jenkins    4096 May  6 10:14 make-4.1
-r--r-----  1 root    root    1878787 May  6 10:14 make-4.1.tar.gz
```

cleanup docker images

/ansible
remove ansible depedency
run yum clean all

**Comment by Haroon-Khel** [comment]
@d3r3kk Has there been any progress on this?

**Comment by d3r3kk** [comment]
Thanks @gdams for taking this over. I'd started it locally and then got stalled as I tried to whittle down the size even further.

The image size is still ~6Gb after your cleanup, so it will require further thought to get this down to a more reasonable size for Azure DevOps agents to make use of (the build-time limit on an Azure DevOps agent is ~10Gb).

**Comment by gdams** [comment]
@d3r3kk can you confirm what the largest files are on the machine still? I thought that removing cuda was going to save a few Gb
