### ISSUE TITLE
Request to install Docker on test machines 

### ISSUE THREAD

**Issue by smlambert** [AdoptOpenJDK/openjdk-infrastructure#132]
We have some Docker-based tests that we would like to run, and so require Docker to be installed on the Linux test machines.

**Comment by karianna** [comment]
@gdams Don't we already have Docker test machines?

**Comment by smlambert** [comment]
That's my bad!  They were not labelled with docker label in Jenkins, so I made the assumption it wasn't installed.  Closing this and will add Jenkins labels.
