### ISSUE TITLE
Access to TRSS server machines

### ISSUE THREAD

**Issue by LongyuZhang** [AdoptOpenJDK/openjdk-infrastructure#1326]
Currently I have only access to TRSS server machine ```trssmon1```, I would also need root access to other TRSS servers to be able to update changes. Thanks.

**Comment by LongyuZhang** [comment]
fyi @llxia @smlambert

**Comment by smlambert** [comment]
@sxa - context for this request, Lan is currently the only QA person who goes and updates the trss server, but we will also have @LongyuZhang help with updating and maintaining this server

**Comment by sxa** [comment]
I approve this. Will get a suitable ssh key added once I can contact @LongyuZhang. We need to look at this access control and how the TRSS server is started/stopped. I'll create another issue to handle that.

**Comment by sxa** [comment]
Key added
