### ISSUE TITLE
AIX machine required for JCK testing

### ISSUE THREAD

**Issue by sxa555** [AdoptOpenJDK/openjdk-infrastructure#133]
Just spotted I hadn't formalised this requirement in an issue ... We need to run the JCK suite on AIX and it's access needs to be locked down so it cannot be shared with other jobs. The build machines are running 7.1TL04 which is the earliest level that's likely to work properly, so if we could have the same as that it would be ideal (although 7.2 should be ok if there's a particular reason to provision something later)

**Comment by gdams** [comment]
Assigning to @tellison as we're going to have to go back to the OSUOSL to request this.

**Comment by smlambert** [comment]
We also need AIX test machine for regular tests, do you want a separate issue for that request?

**Comment by gdams** [comment]
yes please @smlambert

**Comment by gdams** [comment]
FYI @tellison

**Comment by sxa555** [comment]
Closing as we're no longer running the JCK
