### ISSUE TITLE
JMC Build broken: There are no nodes with the label ‘build-scaleway-x64-ubuntu-16-04-2’

### ISSUE THREAD

**Issue by reinhapa** [AdoptOpenJDK/openjdk-infrastructure#1336]
Seems the needed build node is no longer available for https://ci.adoptopenjdk.net/view/JMC/job/jmc-build/

Any suggestion on selecting an alternative one?

**Comment by sxa** [comment]
This is a side effect of the changes from @Willsparker in https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/619#issuecomment-630128207 - I can't see where the machine is defined in the jenkins job but if you can adjust it to point at the new name [build-scaleway-ubuntu1604-x64-1](https://ci.adoptopenjdk.net/computer/build-scaleway-ubuntu1604-x64-1) that will resolve the problem (and let me know where it's set :-) )

**Comment by reinhapa** [comment]
@sxa just changed to the new within the [Jenkinsfile](https://github.com/AdoptOpenJDK/openjdk-jmc-overrides/blob/master/Jenkinsfile)
