### ISSUE TITLE
Workspace corrupt message on test-azure-win2012r2-x64-1

### ISSUE THREAD

**Issue by lumpfish** [AdoptOpenJDK/openjdk-infrastructure#1339]
A test run (https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_sanity.openjdk_x86-32_windows/205/console) has failed with the message:
```
 > git rev-parse --is-inside-work-tree # timeout=10
ERROR: Workspace has a .git repository, but it appears to be corrupt.
```

**Comment by Willsparker** [comment]
Should be fixed now, I just deleted the workspace as further down the log there was an error message
```
jenkins.util.io.CompositeIOException: Unable to delete 'C:\Users\jenkins\workspace\Test_openjdk8_j9_sanity.openjdk_x86-32_windows\openjdk-tests'. Tried 3 times (of a maximum of 3) waiting 0.1 sec between attempts.
```
A rogue `java.exe` process was running in it. Made sure nothing was running on the machine at the time (on Jenkins), stopped it and deleted the file :-)
