### ISSUE TITLE
java.io.IOException: Unexpected EOF  : build-osuosl-centos74-ppc64le-1 & build-osuosl-centos74-ppc64le-2 network issues

### ISSUE THREAD

**Issue by archanaNogriya** [AdoptOpenJDK/openjdk-infrastructure#1347]
It looks like a connectivity issue.

**jdk11u-linux-ppc64le-openj9-linuxXL**
**jdk14u-linux-ppc64le-openj9-linuxXL**

https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-linux-ppc64le-openj9-linuxXL/217/console

I dont see detailed exception but looks like it failed after assigning to the machine build-osuosl-centos74-ppc64le-1 & build-osuosl-centos74-ppc64le-2

`00:32:19  Still waiting to schedule task
00:32:19  Waiting for next available executor on ‘build&&linux&&ppc64le’
01:30:24  Running on build-osuosl-centos74-ppc64le-1 in /home/jenkins/workspace/build-scripts/jobs/jdk11u/jdk11u-linux-ppc64le-openj9-linuxXL
[Pipeline] {
[Pipeline] echo
01:30:24  checking linux
[Pipeline] stage
[Pipeline] { (build)
[Pipeline] checkout
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // node
[Pipeline] }
[Pipeline] // stage
[Pipeline] echo
01:31:08  Execution error: java.io.IOException: Unexpected EOF`

**Comment by archanaNogriya** [comment]
all ppc64le build Failures due to machine build-osuosl-centos74-ppc64le-1 & build-osuosl-centos74-ppc64le-2.
 
jdk-linux-ppc64le-hotspot
jdk14u-linux-ppc64le-openj9
jdk14u-linux-ppc64le-hotspot
jdk11u-linux-ppc64le-openj9-linuxXL
jdk14u-linux-ppc64le-openj9-linuxXL

**Comment by sxa** [comment]
I've kicked off ppc64le piplines on [JDK11](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk11-pipeline/975/) and [JDk14](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk14-pipeline/193/)

I'll close this on the assumption that they will run cleanly since the macines seem live now - will reopen if that proves to be inaccurate
