### ISSUE TITLE
test-macincloud-macos1010-x64-2 is not reachable.

### ISSUE THREAD

**Issue by archanaNogriya** [AdoptOpenJDK/openjdk-infrastructure#1348]
Test_openjdk11_j9_sanity.openjdk_x86-64_mac
https://ci.adoptopenjdk.net/view/Test_openjdk/job/Test_openjdk11_j9_sanity.openjdk_x86-64_mac/244/console

Looks like test machine test-macincloud-macos1010-x64-2 is not reachable.

hudson.remoting.Channel$CallSiteStackTrace: Remote call to test-macincloud-macos1010-x64-2 at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1788) at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:356) at hudson.remoting.Channel.call(Channel.java:998) at hudson.FilePath.act(FilePath.java:1069) at hudson.FilePath.act(FilePath.java:1058) at hudson.tasks.junit.JUnitParser.parseResult(JUnitParser.java:114) at hudson.tasks.junit.JUnitResultArchiver.parse(JUnitResultArchiver.java:137) at hudson.tasks.junit.JUnitResultArchiver.parseAndAttach(JUnitResultArchiver.java:167) at hudson.tasks.junit.pipeline.JUnitResultsStepExecution.run(JUnitResultsStepExecution.java:52) at hudson.tasks.junit.pipeline.JUnitResultsStepExecution.run(JUnitResultsStepExecution.java:25) at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47) at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) at java.util.concurrent.FutureTask.run(FutureTask.java:266) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) java.lang.NoClassDefFoundError: Could not initialize class jenkins.model.Jenkins at hudson.ExtensionList.lookup(ExtensionList.java:433) at hudson.tasks.junit.TestNameTransformer.all(TestNameTransformer.java:40) at

**Comment by archanaNogriya** [comment]
This is also in Test_openjdk14_hs_sanity.openjdk_x86-64_mac
https://ci.adoptopenjdk.net/view/Test_openjdk/job/Test_openjdk14_hs_sanity.openjdk_x86-64_mac/97/console

**Comment by sxa** [comment]
Given that this is not specific to any given test job, can we rename this issue to indicate the machine that has the problem
