### ISSUE TITLE
openj9 AIX build jobs not launching as no agents available

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-infrastructure#1350]
https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-aix-ppc64-openj9/639/console

**Comment by jdekonin** [comment]
If the provider is the same as OpenJ9 & OMR AIX machines (CECC), which I believe it is, then its an outage at the site.  There is no ticketing system or wiki for updates when we've asked, but there is a email list which I will add @sxa and @Willsparker too when there is an update provided.

https://github.com/eclipse/openj9/issues/9759

**Comment by Willsparker** [comment]
I believe the provider is IBM : https://ci.adoptopenjdk.net/computer/test-ibm-aix71-ppc64-3/

**Comment by sxa** [comment]
@jdekonin This isn't an outage - the machine is up and running - it's a jenkins agent issue

**Comment by sxa** [comment]
Machine is now running with an OpenJ9 VM at /usr/jdk-11.0.7+10-jre/bin/java and seems happily running things - closing

**Comment by sxa** [comment]
Restarted with OpenJ9 JDK11 JVM extracted to /usr/jdk-11.0.7+10-jre and it seems to be live at https://ci.adoptopenjdk.net/computer/test-ibm-aix71-ppc64-1/

Will see if it behaves this evening - if so we can remove the duplicate agent definitions https://ci.adoptopenjdk.net/computer/test-ibm-aix71-ppc64-3/ and https://ci.adoptopenjdk.net/computer/test-ibm-aix71-ppc64-4/
