### ISSUE TITLE
test aws win2019-2 appears to have two agents trying to connect

### ISSUE THREAD

**Issue by sxa** [AdoptOpenJDK/openjdk-infrastructure#1352]
From the jenkins log:
`2020-06-02 15:39:31.553+0000 [id=8131709]	INFO	o.j.r.p.i.ConnectionHeadersFilterLayer#onRecv: [JNLP4-connect connection from ec2-34-245-29-235.eu-west-1.compute.amazonaws.com/34.245.29.235:62564] Refusing headers from remote: test-aws-win2019-x64-2 is already connected to this master. Rejecting this connection.
`

**Comment by Willsparker** [comment]
The Jenkins user had a `cmd` window where it was running the Jenkins agent, but it had error'd. Closed that, restarted the service on the Admin user and reenabled the machine in Jenkins, and it seems connected okay. I'd prefer to wait overnight to have something run on it to make sure. I tried running a Grinder but Windows tests are currently blocked by https://github.com/AdoptOpenJDK/openjdk-tests/pull/1804

**Comment by Willsparker** [comment]
Above PR is merged therefore running a Grinder to ensure it's a stable connection: https://ci.adoptopenjdk.net/job/Grinder/3179/console

**Comment by sxa** [comment]
Passed!
