### ISSUE TITLE
Changing VS2017 Adopt Windows playbook to install 15.9.22 from local cache

### ISSUE THREAD

**Issue by KevinBonilla** [AdoptOpenJDK/openjdk-infrastructure#1354]
Related to #1270, using the command line to create a local cache we have a way to manually install `VS2017 15.9.22`. Since we're eventually moving away from VS2010 (my understanding) in October. I believe we need to change the way we install VS2017 in [Adopt_Windows_Playbook ](https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/master/ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/MSVS_2017/tasks/main.yml). I have documentation in our internal wiki that shows how to download the cached `15.9.22` version offline and manually install the program. 

If I can figure out how to create a silent installation of this then we would be able to ensure that all machines would run on the same compiler level. Thoughts on this? 

fyi: @jdekonin @sxa 

Useful links 
https://docs.microsoft.com/en-us/visualstudio/install/create-an-offline-installation-of-visual-studio?view=vs-2017

**Comment by jdekonin** [comment]
I am all for locking all the compile/build machines at the same level of compiler.  I think as long as there is a documented method for how the offline installation was created and its documented what level its been created for then it should be good.  @sxa thoughts??

Notes that just because the offline installation is created a say 15.9.22 there is nothing stopping someone from updating the tools to something newer manually if there was an update.

**Comment by sxa** [comment]
Is this not a dup of #1270? I don't want conversations fragmented
This would need wider approval I think before doing it than just me.
Are we also confident that such a solution is allowed within the terms of the license agreement for the free compiler download?

**Comment by karianna** [comment]
> Is this not a dup of #1270? I don't want conversations fragmented
> This would need wider approval I think before doing it than just me.
> Are we also confident that such a solution is allowed within the terms of the license agreement for the free compiler download?

I think this a dup yeah...

**Comment by sxa** [comment]
We should continue discussion in the original issue
