### ISSUE TITLE
Network Issue : adoptopenjdk.jfrog.io:443 failed to respond

### ISSUE THREAD

**Issue by archanaNogriya** [AdoptOpenJDK/openjdk-infrastructure#1356]
jdk14u-linux-s390x-openj9
https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk14u/job/jdk14u-linux-s390x-openj9/89/console

[Pipeline] echo
01:20:48  Execution error: null
it is a network glitch in the installer

Task :rpm:uploadRedHatRpmPackage
Uploading adoptopenjdk-14-openj9-14.0.1+7-202006022031-1.s390x.rpm to rpm-nightly for centos:6 on s390x
Uploading adoptopenjdk-14-openj9-14.0.1+7-202006022031-1.s390x.rpm to rpm-nightly for centos:7 on s390x
Uploading adoptopenjdk-14-openj9-14.0.1+7-202006022031-1.s390x.rpm to rpm-nightly for centos:8 on s390x
Uploading adoptopenjdk-14-openj9-14.0.1+7-202006022031-1.s390x.rpm to rpm-nightly for rhel:6 on s390x
Uploading adoptopenjdk-14-openj9-14.0.1+7-202006022031-1.s390x.rpm to rpm-nightly for rhel:7 on s390x
Uploading adoptopenjdk-14-openj9-14.0.1+7-202006022031-1.s390x.rpm to rpm-nightly for rhel:8 on s390x
Task :rpm:uploadRedHatRpmPackage FAILED
FAILURE: Build failed with an exception.

What went wrong:
Execution failed for task ':rpm:uploadRedHatRpmPackage'.
org.apache.http.NoHttpResponseException: adoptopenjdk.jfrog.io:443 failed to respond

**Comment by Haroon-Khel** [comment]
Since adoptopenjdk.jfrog.io is not under our control, I am going to close this issue for now
