### ISSUE TITLE
build-scaleway-ubuntu1604-armv7-1 have connection issues which is causing build failure 

### ISSUE THREAD

**Issue by archanaNogriya** [AdoptOpenJDK/openjdk-infrastructure#1357]
jdk14u-linux-arm-hotspot
Hung
https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk14u/job/jdk14u-linux-arm-hotspot/97/console

22:17:34  Cannot contact build-scaleway-ubuntu1604-armv7-1: java.lang.InterruptedException
I've killed the job
Added to intermittent list: #1450

**Comment by sxa** [comment]
Machine is pingable but not responding on the ssh port.

I have logged into scaleway console. The instances page is not bringing up the details properly and I have raised a support ticket as I have no way to conn, However I can trigger a poweroff / poweron cycle so will see if that resolves it

**Comment by sxa** [comment]
Machine has been restarted, jenkins agent connected and running again
