### ISSUE TITLE
build-azure-win2012r2-x64-2 is having a connect issue.

### ISSUE THREAD

**Issue by archanaNogriya** [AdoptOpenJDK/openjdk-infrastructure#1359]
jdk-windows-x64-openj9
https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk/job/jdk-windows-x64-openj9/2/console
Again it seems network issue

 `05:15:58  ERROR: Build failed for targets 'product-images legacy-jre-image test-image debug-image' in configuration 'windows-x86_64-server-release' (exit code 2) 
05:15:58  Stopping sjavac server
05:15:59  
05:15:59  === Output from failing command(s) repeated here ===
05:15:59  * For target jdk_modules_java.compiler__the.java.compiler_batch:
05:15:59  [stderr] java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@72fb5619[Not completed, task = com.sun.tools.sjavac.comp.PooledSjavac$$Lambda$41/0x00000001000be840@76c4dc19] rejected from java.util.concurrent.ThreadPoolExecutor@37f9d622[Shutting down, pool size = 1, active threads = 0, queued tasks = 0, completed tasks = 6]
05:15:59  [stderr] 	at java.base/java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2057)
05:15:59  [stderr] 	at java.base/java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:827)
05:15:59  [stderr] 	at java.base/java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1357)
05:15:59  [stderr] 	at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:140)
05:15:59  [stderr] 	at jdk.compiler.interim/com.sun.tools.sjavac.comp.PooledSjavac.compile(PooledSjavac.java:61)
05:15:59  [stderr] 	at jdk.compiler.interim/com.sun.tools.sjavac.server.IdleResetSjavac.compile(IdleResetSjavac.java:70)
05:15:59  [stderr] 	at jdk.compiler.interim/com.sun.tools.sjavac.server.RequestHandler.run(RequestHandler.java:104)
05:15:59  * For target jdk_modules_java.datatransfer__the.java.datatransfer_batch:
05:15:59  Connection attempt failed: Connection refused: no further information
05:15:59  Connection attempt failed: Connection refused: no further information
05:15:59  Connection attempt failed: Connection refused: no further information
05:15:59  Giving up
05:15:59  IOException caught during compilation: Could not connect to server
05:15:59  * For target jdk_modules_java.xml__the.java.xml_batch:
05:15:59  Connection attempt failed: Connection refused: no further information
05:15:59  Connection attempt failed: Connection refused: no further information
05:15:59  Connection attempt failed: Connection refused: no further information
05:15:59  Giving up
05:15:59  IOException caught during compilation: Could not connect to server`

**Comment by Haroon-Khel** [comment]
@Willsparker Could you take a look at this? It may just be an obvious network issue

**Comment by Willsparker** [comment]
https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk/job/jdk-windows-x64-openj9/3/console
https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-windows-x64-hotspot/609/consoleFull
https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-windows-x86-32-hotspot/607/consoleFull

It appears the machine was okay last night - I think the initial issue was a one-off :-) Closing, happy to reopen if it recurrs
