### ISSUE TITLE
test-macincloud-macos1013-x64-1 connection issue.

### ISSUE THREAD

**Issue by archanaNogriya** [AdoptOpenJDK/openjdk-infrastructure#1361]
**Test_openjdk8_j9_sanity.openjdk_x86-64_mac_xl**
https://ci.adoptopenjdk.net/view/Test_openjdk/job/Test_openjdk8_j9_sanity.openjdk_x86-64_mac_xl/218/console

`18:58:06  XML output with verification to /Users/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_x86-64_mac_xl/openjdk-tests/TKG/test_output_15911206752866/jdk_lang_j9_0/work
19:00:29  Cannot contact test-macincloud-macos1013-x64-1: java.lang.InterruptedException
19:07:54  wrapper script does not seem to be touching the log file in /Users/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_x86-64_mac_xl@tmp/durable-c83a6035`

**Comment by Haroon-Khel** [comment]
@gdams Would you mind taking a look at this?

**Comment by Haroon-Khel** [comment]
Re running the sanity job on `test-macincloud-macos1013-x64-1`, https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/3186/, couldnt recreate the error. I suspect this is an intermittent failure so will be closing this for now while keeping an eye on the job
