### ISSUE TITLE
build-digitalocean-centos69-x64-2: No space left on device

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-infrastructure#1365]
**jdk-linux-x64-openj9**
https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk/job/jdk-linux-x64-openj9/3/consoleFull
```
04:33:10  fatal: cannot create directory at 'test/jdk/java/util/concurrent/CountDownLatch': No space left on device
```

**Comment by Willsparker** [comment]
@sxa A good 6Gb is taken up by the `jdk11-linux-riscv-openj9-build` folder in the `/home/jenkins/workspace` directory. As we have it added to the pipelines now, presumably we can delete the standalone Jenkins Job (and by virtue, the folder taking up this space) ?

**Comment by sxa** [comment]
Yes

**Comment by Willsparker** [comment]
Cool - 6.2GB free on the machine now. I'm unable to delete the project but I've disabled it now.
