### ISSUE TITLE
/var/run/docker.sock: connect: permission denied on test-godaddy-debian8-x64-4

### ISSUE THREAD

**Issue by llxia** [AdoptOpenJDK/openjdk-infrastructure#1368]
It seems that `test-godaddy-debian8-x64-4 ` is not configured properly to run docker. We got the following error:

```
12:24:40  docker run --rm -v /home/jenkins/workspace/Test_openjdk11_j9_extended.external_x86-64_linux_wycheproof/openjdkbinary/j2sdk-image:/opt/java/openjdk --rm adoptopenjdk-wycheproof-test:11-jdk-ubuntu-openj9-full 
12:24:40  docker: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.38/containers/create: dial unix /var/run/docker.sock: connect: permission denied.
12:24:40  See 'docker run --help'.
```

https://ci.adoptopenjdk.net/job/Test_openjdk11_j9_extended.external_x86-64_linux_wycheproof/1/console
https://ci.adoptopenjdk.net/job/Test_openjdk11_j9_extended.external_x86-64_linux_quarkus/21/console

**Comment by Haroon-Khel** [comment]
Seems related to https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/721

**Comment by Haroon-Khel** [comment]
On the machine, Ive added the `jenkins` user to the `docker` group which I thought should fix it. @jdekonin do you think this is another case where the machine needs to be disconnected from jenkins and then reconnected for this usergroup update to take effect?

**Comment by sxa** [comment]
Yes - jenkins agent will need to be restarted as the process will have been started without being in the docker group and it can't magically pick i up unfortunately. I'll disconnect/reconnect debian-4 now

**Comment by sxa** [comment]
jenkins agent now correctly running in the docker group based on checking in the script console:
`Result: uid=1001(jenkins) gid=1001(jenkins) groups=1001(jenkins),998(docker)`

**Comment by Haroon-Khel** [comment]
Ive also made this change to the other 3 `test-godaddy-debian8-x64` machines as I suspect they have been misconfigured the same way

**Comment by sxa** [comment]
Yep - am holding off til we have a verified grinder run for one of the external tests before putting more of them into the pool. Are the godaddy centos ones ok?

**Comment by Haroon-Khel** [comment]
Ive configured docker on the `test-godaddy-centos` machines to the same extent as ive done the debian8 and ubuntu ones, see [here](https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/721#issuecomment-636891372),but I have not run any tests on them yet

**Comment by Haroon-Khel** [comment]
Rerunning both failed tests, [wycheproof](https://ci.adoptopenjdk.net/job/Grinder/3252/consoleFull) and [quarkus](https://ci.adoptopenjdk.net/job/Grinder/3254/console), I am now getting a different error for both:

```
15:26:52  Unable to recognize DOCKER_OS from DOCKERIMAGE_TAG = --version!
15:26:52  docker run  --rm adoptopenjdk-derby-test:11-jdk-ubuntu-openj9-full 
15:26:52  Unable to find image 'adoptopenjdk-derby-test:11-jdk-ubuntu-openj9-full' locally
15:26:53  docker: Error response from daemon: pull access denied for adoptopenjdk-derby-test, repository does not exist or may require 'docker login'.
15:26:53  See 'docker run --help'.
```

After a bit of digging, I found this error to be similar to https://github.com/AdoptOpenJDK/openjdk-tests/issues/1768

**Comment by llxia** [comment]
Re https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1368#issuecomment-639545515, your Grinder is missing `DOCKERIMAGE_TAG `

Running the `wycheproof` on `test-godaddy-debian8-x64-4` 
https://ci.adoptopenjdk.net/job/Test_openjdk11_j9_extended.external_x86-64_linux_wycheproof/4/

**Comment by llxia** [comment]
The above test build did not have `docker permission denied` error on test-godaddy-debian8-x64-4. It looks like `test-godaddy-debian8-x64-4` is fixed. 

The test build later failed at `BouncyCastleTest ` which is unrelated to this issue

**Comment by Haroon-Khel** [comment]
My bad, I assumed using the `Rerun in Grinder` ability would duplicate the failing test. 

Seeing as this `BouncyCastleTest` error is unrelated, I will be closing this issue
