### ISSUE TITLE
Failed to copy artifacts on build-softlayer-win2012r2-x64-1

### ISSUE THREAD

**Issue by archanaNogriya** [AdoptOpenJDK/openjdk-infrastructure#1371]
**jdk14u-windows-x64-hotspot**
Running on build-softlayer-win2012r2-x64-1

https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk14u/job/jdk14u-windows-x64-hotspot/94/console

```
23:40:10  Due to the Copy artifact compatibility mode, set as migration, the build can reach the project build-scripts/release/create_installer_windows.
23:40:10   But in Production mode, this will not be the case anymore.
23:40:10   Please consider adding the CopyArtifactPermission on the project you want to copy.
23:40:10  Copied 0 artifacts from "build-scripts » release » create_installer_windows" build number 4450
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // node
[Pipeline] echo
23:40:10  Execution error: Failed to copy artifacts from build-scripts/release/create_installer_windows with filter: wix/ReleaseDir/OpenJDK*jdk_*_windows_*.msi
```

**Comment by karianna** [comment]
This is probably the copyArtifacts mode needing to swap to Production in Jenkins.  I'll try to take a look with @M-Davies today

**Comment by M-Davies** [comment]
@karianna Would we have to add the permission [discussed here](https://adoptopenjdk.slack.com/archives/C09NW3L2J/p1591198380436300) to both the installer and pipeline jobs? They both archive artifacts after all

**Comment by karianna** [comment]
copyArtifacts Permissions changed - closing for now.

**Comment by gdams** [comment]
For reference, here is the change that I made to the installer job:

![Screenshot 2020-06-08 at 13 06 18](https://user-images.githubusercontent.com/20224954/84028566-da387180-a988-11ea-86df-8ea8a442ac74.png)

**Comment by douph1** [comment]
This error was not due to compatibility mode as the plugin said "the build can reach the project".
As far as I know you have not already passed into production mode.
This is probably a filter error like for the XL job fixed by https://github.com/AdoptOpenJDK/openjdk-build/pull/1830
