### ISSUE TITLE
Connection issue on machine **build-osuosl-aix71-ppc64-2

### ISSUE THREAD

**Issue by archanaNogriya** [AdoptOpenJDK/openjdk-infrastructure#1372]
**jdk8u-aix-ppc64-hotspot**

https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-aix-ppc64-hotspot/599/consoleFull

Very clearly is connection issue here on machine **build-osuosl-aix71-ppc64-2** 
`20:58:31  build-osuosl-aix71-ppc64-2 was marked offline: Connection was broken: java.io.IOException: Unexpected EOF
20:58:31  	at hudson.remoting.ChunkedInputStream.readUntilBreak(ChunkedInputStream.java:99)
20:58:31  	at hudson.remoting.ChunkedCommandTransport.readBlock(ChunkedCommandTransport.java:39)
20:58:31  	at hudson.remoting.AbstractSynchronousByteArrayCommandTransport.read(AbstractSynchronousByteArrayCommandTransport.java:34)
20:58:31  	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:63)`

**Comment by Willsparker** [comment]
(Probably) Related: #1374 

I did the same as in the above issue and started a [grinder](https://ci.adoptopenjdk.net/job/Grinder/3280/) testing the same stuff. The machine appears to be back online okay- it may have just dropped off momentarily which caused the test to fail
