### ISSUE TITLE
CopyArtifactPermission file permission issue

### ISSUE THREAD

**Issue by archanaNogriya** [AdoptOpenJDK/openjdk-infrastructure#1373]
jdk8u-windows-x64-hotspot

Running on build-azure-win2012r2-x64-1

https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-windows-x64-hotspot/627/console

Not able to
CopyArtifactPermission file permission issue, Unable to get file permissions

**Comment by karianna** [comment]
probably related to #1372

**Comment by karianna** [comment]
https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1371
