### ISSUE TITLE
test-softlayer-win2012r2-x64-1 workspace corrupt

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-infrastructure#1376]
Test jobs cannot clean workspace due to errors:
https://ci.adoptopenjdk.net/job/Test_openjdk11_j9_sanity.openjdk_x86-64_windows_xl/242/console

**Comment by Willsparker** [comment]
Deleted it manually after stopping a `java.exe` process, presumably left over from a previous test run.
