### ISSUE TITLE
 build-softlayer-win2012r2-x64-1: Unable to clean workspace

### ISSUE THREAD

**Issue by lumpfish** [AdoptOpenJDK/openjdk-infrastructure#1379]
Builds are failing on  build-softlayer-win2012r2-x64-1 (e.g. https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-windows-x64-openj9-windowsXL/315/console) with:
```
17:05:37  Running in C:/workspace/openjdk-build
[Pipeline] {
[Pipeline] stage
[Pipeline] { (build)
[Pipeline] cleanWs
17:05:38  [WS-CLEANUP] Deleting project workspace...
17:05:38  [WS-CLEANUP] Deferred wipeout is disabled by the job configuration...
17:05:38  Cannot delete workspace: null
17:05:38  Option not to fail the build is turned on, so let's continue
[Pipeline] checkout
17:05:38  No credentials specified
17:05:38  Cloning the remote Git repository
17:05:43  Cloning repository https://github.com/AdoptOpenJDK/openjdk-build.git
17:05:43  ERROR: Failed to clean the workspace
17:05:43  jenkins.util.io.CompositeIOException: Unable to delete 'C:\workspace\openjdk-build'. Tried 3 times (of a maximum of 3) waiting 0.1 sec between attempts.
.....
```

**Comment by Willsparker** [comment]
Manually deleted - there was a leftover file called `_the..` which isn't able to be deleted through the Windows File Explorer as it claims it isn't there. Running `rm -rf C:/workspace/openjdk-build` in Cygwin cleared it out.

**Comment by lumpfish** [comment]
@Willsparker - I'm still seeing this error: https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-windows-x64-openj9-windowsXL/317/console

**Comment by Willsparker** [comment]
Okay, I've cleared the file off again- however I get the impression this is going to happen every run as it's consistently the same `_the..` file at `openjdk-build/workspace/build/src/build/*/jdk/gensrc/java/nio/`

@M-Davies Can the build-scripts be changed to cleanup the old workspace using `cygwin` instead of (presumably) cmd ...?

**Comment by M-Davies** [comment]
@Willsparker We currently clean using the [cleanws](https://www.jenkins.io/doc/pipeline/steps/ws-cleanup/) plugin which I don't believe you can use on the machines themselves, so no cmd line.

We could test switching to a deferred wipeout (like we've done for [Windows/OpenJ9](https://github.com/AdoptOpenJDK/openjdk-build/blob/master/pipelines/build/common/openjdk_build_pipeline.groovy#L509) and see if that resolves the issue

**Comment by lumpfish** [comment]
@M-Davies - what do you mean by "like we've done for Windows / OpenJ9"?  The builds I'm submitting are Windows / OpenJ9.

**Comment by M-Davies** [comment]
https://github.com/AdoptOpenJDK/openjdk-build/issues/453 updated `cleanws` to ensure that we're cleaning up properly (as before, we were leaving stuff all over the place on the nodes). 

https://github.com/AdoptOpenJDK/openjdk-build/blob/master/pipelines/build/common/openjdk_build_pipeline.groovy#L509 is the changed line

**Comment by lumpfish** [comment]
But we're already running that code aren't we, if we're building Windows / OpenJ9?

**Comment by M-Davies** [comment]
> But we're already running that code aren't we, if we're building Windows / OpenJ9?
> 
Ah I misread your links above as hotspot not j9 😬. So yes, we are already using that code

**Comment by lumpfish** [comment]
After @Willsparker 's manual clean up a build has been successful: https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-windows-x64-openj9-windowsXL/318/console. but then the next one failed, as Will suspected: https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-windows-x86-32-openj9/585/console.
Nightly build https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk8-pipeline/1102/ (Jun 8, 2020 7:05:11 PM) did not suffer from this - all builds since then have I think.

@Willsparker - please could you clean up the machine manual;ly again so I can get the last jdk8 openj9-0.21.0-m1 build done pending a solution.

**Comment by Willsparker** [comment]
@lumpfish Cleaned

**Comment by Willsparker** [comment]
I'm going to close this issue and make a new one in `openjdk-build` as I believe it's more relevant there
