### ISSUE TITLE
Failed to copy artifacts from build-scripts/release/create_installer_windows

### ISSUE THREAD

**Issue by archanaNogriya** [AdoptOpenJDK/openjdk-infrastructure#1384]
**jdk11u-windows-x64-openj9-windowsXL**
https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-windows-x64-openj9-windowsXL/371/console

`Execution error: Failed to copy artifacts from build-scripts/release/create_installer_windows with filter: wix/ReleaseDir/OpenJDK*jdk_*_windows*.msi`

**Comment by karianna** [comment]
FYI - @M-Davies

**Comment by M-Davies** [comment]
Dup of https://github.com/AdoptOpenJDK/openjdk-build/issues/1834
