### ISSUE TITLE
Create openjdk-jdk15 and openjdk16-binaries repository

### ISSUE THREAD

**Issue by M-Davies** [AdoptOpenJDK/openjdk-infrastructure#1389]
See https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1096 for how this was done before

https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk15/job/jdk15-linux-x64-hotspot/2/console
```
14:25:47  git clone --depth=1 https://github.com/adoptopenjdk/openjdk-jdk15.git /home/jenkins/workspace/build-scripts/jobs/jdk15/jdk15-linux-x64-hotspot/workspace/./build//src
14:25:47  Cloning into '/home/jenkins/workspace/build-scripts/jobs/jdk15/jdk15-linux-x64-hotspot/workspace/./build//src'...
14:25:48  fatal: could not read Username for 'https://github.com': No such device or address
```

Not sure if this is the place to raise the `openjdk16-binaries` binaries request.

**Comment by karianna** [comment]
https://github.com/AdoptOpenJDK/openjdk16-binaries has been created.

**Comment by karianna** [comment]
There is a plan for Java 16 to go to GitHub instead as part of Project Skara - we'll need to track when that happens.

**Comment by gdams** [comment]
I'll create the openjdk-jdk15 mirror

**Comment by gdams** [comment]
https://github.com/AdoptOpenJDK/openjdk-jdk15 created

**Comment by gdams** [comment]
https://ci.adoptopenjdk.net/view/git-hg/job/git-hg-jdk15u/ created to mirror jdk15 from Skara

**Comment by gdams** [comment]
Source mirror complete, we should be good to re-run the builds

**Comment by M-Davies** [comment]
Thanks @gdams . Im just waiting on https://ci.adoptopenjdk.net/job/build-scripts/job/utils/job/pipeline_jobs_generator_jdk15/4/ to pull in the changes @sxa made then I'll kick off a new set

**Comment by gdams** [comment]
Thanks, let me know if there are any issues!

**Comment by M-Davies** [comment]
https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk15-pipeline/168/console

**Comment by karianna** [comment]
openjdk-jdk15 is done

**Comment by sxa** [comment]
> https://ci.adoptopenjdk.net/view/git-hg/job/git-hg-jdk15u/ created to mirror jdk15 from Skara

To clarify the above for anyone looking at this, the link is now https://ci.adoptopenjdk.net/view/git-hg/job/git-mirrors/job/git-skara-jdk15/
