### ISSUE TITLE
test-aws-win2019-x64-2 corrupt workspace

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-infrastructure#1394]
https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_special.openjdk_x86-32_windows/120/console
```
Running on test-aws-win2019-x64-2 in C:\Users\jenkins.EC2AMAZ-T7I06S9\workspace\Test_openjdk8_j9_special.openjdk_x86-32_windows
[Pipeline] {
[Pipeline] checkout
No credentials specified
 > git rev-parse --is-inside-work-tree # timeout=10
ERROR: Workspace has a .git repository, but it appears to be corrupt.
hudson.plugins.git.GitException: Command "git rev-parse --is-inside-work-tree" returned status code 128:
stdout: 
stderr: fatal: not a git repository (or any parent up to mount point /cygdrive)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
```

**Comment by andrew-m-leonard** [comment]
Machine disabled: https://ci.adoptopenjdk.net/computer/test-aws-win2019-x64-2/

**Comment by Willsparker** [comment]
Machine had to be rebooted before I was able to connect for some reason. Folder has been cleared off 👍

**Comment by Willsparker** [comment]
I've also reenabled the machine in Jenkins, and had to reconnect it as the service has to be started manually. Not sure why it was set to manual, but I've changed it back to `automatic`.
