### ISSUE TITLE
What xcode version is used to build jdk8 on OSX?

### ISSUE THREAD

**Issue by pshipton** [AdoptOpenJDK/openjdk-infrastructure#1400]
The OpenJ9 project wants to update their builds for OSX, to use similar machines and tools as Adopt.
https://github.com/eclipse/openj9/issues/9806

We've determined 10.14 as the build machine, but haven't been able to confirm the xcode version used.

Apparently `xcodebuild -version` can work to find the version, unless xcode is installed via old cmdln tools. Which apparently OpenJ9 and perhaps Adopt use since it requires a smaller footprint to install this way.

**Comment by pshipton** [comment]
@jdekonin @keithc-ca @sxa

**Comment by pshipton** [comment]
`/usr/bin/xcodebuild -version` should work

**Comment by pshipton** [comment]
Perhaps all we can do is confirm the gcc/clang version? Which Stewart already provided.

```
Using clang C compiler version 10.0.1 [Apple LLVM version 10.0.1 (clang-1001.0.46.4) Target: x86_64-apple-darwin18.7.0 Thread model: posix
```

**Comment by pshipton** [comment]
Pls try `xcodebuild -version` on an Adopt jdk8 build machine.

**Comment by Willsparker** [comment]
ping @gdams

**Comment by gdams** [comment]
This is the Xcode version we use to build JDK8u. Note it is full Xcode rather than the command line tools:

```bash
build-macstadium-macos1014-x64-1:~ administrator$ xcodebuild -version
Xcode 10.3
Build version 10G8
```

**Comment by pshipton** [comment]
@gdams what Xcode is used for the other Java versions?

**Comment by sxa** [comment]
I think we're building all on the same level now but will defer to @gdams

**Comment by pshipton** [comment]
@gdams what Xcode is used for the other Java versions?

**Comment by gdams** [comment]
for all other Java versions we use Xcode command-line build tools:

```bash
$ clang --version
Apple LLVM version 10.0.1 (clang-1001.0.46.4)
Target: x86_64-apple-darwin18.7.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

**Comment by jdekonin** [comment]
I am a little confused as to why the newer releases are on a slightly older version?  Whats the reason behind using too different versions?  Is there any plan on unifying for system setup simplicity?

**Comment by gdams** [comment]
jdk8u currently requires the full fat Xcode installation so we are pinned to whatever we can get on the machine at the time of setup. The other versions all use command-line tools which gives us a lot more flexibility.
