### ISSUE TITLE
build-osuosl-aix71-ppc64-2 marked offline

### ISSUE THREAD

**Issue by archanaNogriya** [AdoptOpenJDK/openjdk-infrastructure#1407]
**jdk8u-aix-ppc64-hotspot**
https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-aix-ppc64-hotspot/624/console

`20:15:27  build-osuosl-aix71-ppc64-2 was marked offline: Connection was broken: java.io.IOException: Unexpected EOF
20:15:27  	at hudson.remoting.ChunkedInputStream.readUntilBreak(ChunkedInputStream.java:99)
20:15:27  	at hudson.remoting.ChunkedCommandTransport.readBlock(ChunkedCommandTransport.java:39)
20:15:27  	at hudson.remoting.AbstractSynchronousByteArrayCommandTransport.read(AbstractSynchronousByteArrayCommandTransport.java:34)
20:15:27  	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:63)`

**Comment by sxa** [comment]
Looks fully online and working at the moment - I would suggest ensuring this is logged in the intermittent build failures issue.
