### ISSUE TITLE
test-softlayer-win2012r2-x64-2 corrupt git repo unable to clean...

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-infrastructure#1410]
https://ci.adoptopenjdk.net/job/Test_openjdk14_j9_sanity.openjdk_x86-64_windows/114/console
```
Running on test-softlayer-win2012r2-x64-2 in C:\Users\jenkins\workspace\Test_openjdk14_j9_sanity.openjdk_x86-64_windows
[Pipeline] {
[Pipeline] checkout
No credentials specified
 > git rev-parse --is-inside-work-tree # timeout=10
ERROR: Workspace has a .git repository, but it appears to be corrupt.
hudson.plugins.git.GitException: Command "git rev-parse --is-inside-work-tree" returned status code 128:
stdout: 
stderr: fatal: not a git repository (or any parent up to mount point /cygdrive)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).

	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2430)
...
Cloning the remote Git repository
Cloning repository https://github.com/AdoptOpenJDK/openjdk-tests.git
ERROR: Failed to clean the workspace
jenkins.util.io.CompositeIOException: Unable to delete 'C:\Users\jenkins\workspace\Test_openjdk14_j9_sanity.openjdk_x86-64_windows\openjdk-tests'. Tried 3 times (of a maximum of 3) waiting 0.1 sec between attempts.

```

**Comment by Willsparker** [comment]
ref: #1396

**Comment by Willsparker** [comment]
Again, another instance of a leftover java process using the file, therefore stopping anything from being able to delete it. 
The file in particular a core log file from a test:
`C:\Users\jenkins\workspace\Test_openjdk14_j9_sanity.openjdk_x86-64_windows\openjdk-tests\TKG\test_output_15927131979083\jdk_lang_j9_0\work\scratch_1\javacore.20200620.233449.36172.0001`

I'm not sure whether this is relevant, but the contents of it is attached: 
[test-softlayer-win2012-x64-2-javacore.20200620.txt](https://github.com/AdoptOpenJDK/openjdk-infrastructure/files/4824315/test-softlayer-win2012-x64-2-javacore.20200620.txt)

With the final words: 
```
3LKMONOBJECT       java/lang/ref/ReferenceQueue@0x00000000FFDF6110: <unowned>
3LKNOTIFYQ            Waiting to be notified:
3LKWAITNOTIFY            "Common-Cleaner" (
```
It does indeed look like it's not finished properly.

**Comment by Willsparker** [comment]
I've stopped the process and deleted the file. I'll include a link to the above comment in my `track corrupt workspaces on windows` issue.
