### ISSUE TITLE
Jenkins Upgrade to 2.235.1 from 2.222.4

### ISSUE THREAD

**Issue by karianna** [AdoptOpenJDK/openjdk-infrastructure#1414]
https://www.jenkins.io/changelog-stable/

**Comment by sxa** [comment]
@karianna Do you intend to schedule this over the weekend?

**Comment by karianna** [comment]
> @karianna Do you intend to schedule this over the weekend?

Yes if I see master is quiet

**Comment by Willsparker** [comment]
Jenkins has been upgraded to 2.235.2 👍  Thanks @karianna

**Comment by sxa** [comment]
To be clear - it has been upgraded to 2.235.2
