### ISSUE TITLE
Asynchronous Resource Disposer Report - June 2020

### ISSUE THREAD

**Issue by karianna** [AdoptOpenJDK/openjdk-infrastructure#1415]
Resource | State | Tracked since | &nbsp;
-- | -- | -- | --
Workspace build-azure-win2012r2-x64-1:J:/jenkins/tmp_ws-cleanup_1592304830562 | jenkins.util.io.CompositeIOException: Unable to delete 'J:\jenkins\tmp_ws-cleanup_1592304830562'. Tried 3 times (of a maximum of 3) waiting 0.1 sec between attempts. | 2020-06-16 12:53 |  
Workspace test-ibm-aix71-ppc64-1:/home/jenkins/workspace/build-scripts/jobs/jdk11u/jdk11u-aix-ppc64-openj9_ws-cleanup_1593005797525 | To dispose | 2020-06-24 15:36 |  
Workspace test-godaddy-debian8-x64-2:/home/jenkins/workspace/DockerScannerTool_ws-cleanup_1592508423009 | jenkins.util.io.CompositeIOException: Unable to delete '/home/jenkins/workspace/DockerScannerTool_ws-cleanup_1592508423009'. Tried 3 times (of a maximum of 3) waiting 0.1 sec between attempts. | 2020-06-18 21:27 |

**Comment by Willsparker** [comment]
@karianna Could I get access to https://ci.adoptopenjdk.net/administrativeMonitor/AsyncResourceDisposer/ ?

**Comment by sxa** [comment]
Unfortunately it does not appear to be possible to view that without jenkins admin access ...

**Comment by karianna** [comment]
Yeah sorry, we're still keeping Jenkins Admin locked down for now, So I'll just post the details here.  Happy to screen share/pair on a particular issue though.

**Comment by Willsparker** [comment]
Alright, thank you :-)

**Comment by Willsparker** [comment]
@karianna Do you mind if this issue is closed, as #1396 can be used to put the reports, when they're required :-)
