### ISSUE TITLE
Request for access to installer build jobs

### ISSUE THREAD

**Issue by adamfarley** [AdoptOpenJDK/openjdk-infrastructure#1416]
I request access to the installer build jobs on Adopt jenkins.

E.g. https://ci.adoptopenjdk.net/job/build-scripts/job/release/job/create_installer_windows/

This access is requested because I'm now working on build and test failure triage at Adopt.

**Comment by sxa** [comment]
I approve

**Comment by karianna** [comment]
> I approve

Shall we just add Adam to the installer team?

**Comment by sxa** [comment]
Done (Need to streamline this a bit...)
