### ISSUE TITLE
All arm nodes offline over weekend

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-infrastructure#1417]
build-scaleway-ubuntu1604-armv7-1 & 2 both offline over weekend causing build pipelines to all queue up...

Re-launched build-scaleway-ubuntu1604-armv7-1 sucessfully.
build-scaleway-ubuntu1604-armv7-2 won't come back online.

**Comment by sxa** [comment]
`-2` had to be force restarted. Came back quickly and reconnected
