### ISSUE TITLE
Azure windows machines require cleardown

### ISSUE THREAD

**Issue by M-Davies** [AdoptOpenJDK/openjdk-infrastructure#1419]
While working on testing some code changes for an issue I am working on, I enabled `clean workspace` for some builds by accident which has reproduced https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1396. They will likely need to be cleaned out before the nightly builds start later

`build-azure-1`
https://ci.adoptopenjdk.net/view/work%20in%20progress/job/jdk8u-windows-x64-hotspot/25/console
```
10:32:53  [WS-CLEANUP] Deleting project workspace...
10:32:53  [WS-CLEANUP] Deferred wipeout is disabled by the job configuration...
10:33:29  Cannot delete workspace: null
10:33:29  Option not to fail the build is turned on, so let's continue
[Pipeline] checkout
10:33:30  No credentials specified
10:33:30  Cloning the remote Git repository
10:33:28  Cloning repository https://github.com/M-Davies/openjdk-build.git
10:33:28  ERROR: Failed to clean the workspace
10:33:28  jenkins.util.io.CompositeIOException: Unable to delete 'J:\jenkins\tmp'. Tried 3 times (of a maximum of 3) waiting 0.1 sec between attempts.
```
`build-azure-2`
https://ci.adoptopenjdk.net/view/work%20in%20progress/job/jdk8u-windows-x64-hotspot/15/console
```
10:10:00  [WS-CLEANUP] Deleting project workspace...
10:10:00  [WS-CLEANUP] Deferred wipeout is disabled by the job configuration...
10:10:00  Cannot delete workspace: null
10:10:00  Option not to fail the build is turned on, so let's continue
[Pipeline] checkout
10:10:01  No credentials specified
10:10:01  Cloning the remote Git repository
10:10:01  Cloning repository https://github.com/M-Davies/openjdk-build.git
10:10:01  ERROR: Failed to clean the workspace
10:10:01  jenkins.util.io.CompositeIOException: Unable to delete 'J:\jenkins\tmp'. Tried 3 times (of a maximum of 3) waiting 0.1 sec between attempts.
```

**Comment by sxa** [comment]
For the file on `azure-1` it cannot remove a zero lenght file called `_the..` in the directory that it's having problems with. I'v retried from the command line and also from the GUI - no change. The machine wants to reboot itself for updates anyway so I'll initiate that just now which should clear it out

**Comment by sxa** [comment]
Seems to be the same file on `-2`:

`j:\jenkins\tmp\workspace\build\src\build\windows-x86_64-normal-server-release\jdk\gensrc\java\nio\_the..`

The file was created at exactly 8am today UK time. I'll reboot it too

**Comment by sxa** [comment]
That didn't work ... However removing it with the cygwin `rm` command did ... Closing, but rather confused ...

**Comment by Willsparker** [comment]
So, [this PR](https://github.com/AdoptOpenJDK/openjdk-build/pull/1892) seems to have fixed this problem for specifically the path: `C:/workspace/openjdk-build/workspace/build/src/build/*/jdk/gensrc` (as that was the path that was affecting Softlayer machines). It seems an additional `context.sh` script or more general fix is required to fix it for the `azure` machines. Not sure why it's only now it decided to start being an issue with `azure`.

**Comment by M-Davies** [comment]
@Willsparker Can you raise a build issue for that?

**Comment by Willsparker** [comment]
PR in ;-)
