### ISSUE TITLE
test-godaddy-ubuntu1604-x64-2 cannot reach test-godaddy-ubuntu1604-x64-2

### ISSUE THREAD

**Issue by adamfarley** [AdoptOpenJDK/openjdk-infrastructure#1423]
[This test](https://ci.adoptopenjdk.net/job/Test_openjdk11_corretto_sanity.perf_x86-64_linux/117/consoleText) failed while running on test-godaddy-ubuntu1604-x64-2 because test-godaddy-ubuntu1604-x64-2 was not known.

```
test-godaddy-ubuntu1604-x64-2.adoptopenjdk.net: test-godaddy-ubuntu1604-x64-2.adoptopenjdk.net: Name or service not known
```

I attempted to ping test-godaddy-ubuntu1604-x64-2.adoptopenjdk.net, but got an error on my local machine too.

Is this an infrastructure problem?

[Re-running the test now](https://ci.adoptopenjdk.net/job/Test_openjdk11_corretto_sanity.perf_x86-64_linux/118/console), to see if it was a one-off.

Edit: It wasn't a one-off. This keeps happening.

**Comment by Willsparker** [comment]
From what I can gather with https://stackoverflow.com/questions/33028842/unknownhostexception-name-or-service-not-known , the `/etc/hosts` file needs to be updated with `127.0.0.1  test-godaddy-ubuntu1604-x64-2.adoptopenjdk.net localhost`.
Did that for IPv4 to see if that fixes the issue. If not, I'll try for IPv6.
https://ci.adoptopenjdk.net/job/Grinder/3504/console

**Comment by Willsparker** [comment]
Seems to have fixed it in that linked Grinder :-) closing

**Comment by adamfarley** [comment]
Good job @Willsparker :)

**Comment by sxa** [comment]
I was sure we'd fixed this in past ... but bear in mind that the solution you've implemented is not the same as [the playbooks](https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/master/ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/main.yml#L54).

Also unless this fix gets deployed to other equivalent machines (and it doesn't seem to have been) then the test will continue to fail.

There is also a comment in `/etc/hosts` which suggests that changes in there will get overridden anyway so we should resolve that.

See also https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1145 https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1134 https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1031#issuecomment-567907462

**Comment by Willsparker** [comment]
@sxa From what I can see from the playbook would want the following: 
```
<ansible_default_ipv4_address>   test-godaddy-ubuntu1604-x64-2.adoptopenjdk.net    test-godaddy-ubuntu1604-x64-2
```
The `ansible_default_ipv4_address` appears to be 10.0.2.15 (looking at several `VPC` runs), however I assume this isn't necessarily the case for the `GoDaddy` machines? 
Looking at that comment, I'll just need to change both the `/etc/hosts` and the `/etc/cloud/templates/hosts.debian.tmpl` files on all the machines to make them persist, so that shouldn't be an issue :-)

**Comment by Willsparker** [comment]
Hmm, I ran `ansible all -i host -m setup`, with the host file containing the IP for `test-godaddy-ubuntu1604-x64-2` as listed in `Jenkins` ( 160.153.246.176 ), and the `ansible_default_ipv4_address` came out as the same as the one in the host file. I'll put this into `/etc/hosts` on the machine and rerun the grinder:
```
160.153.246.176  test-godaddy-ubuntu1604-x64-2.adoptopenjdk.net    test-godaddy-ubuntu1604-x64-2
```
If the grinder works, I'll put it into the `/etc/cloud/templates/hosts.debian.tmpl` file so it will persist through restarts.

**Comment by Willsparker** [comment]
https://ci.adoptopenjdk.net/job/Grinder/3509/ 
It appears the above fix works. @sxa are you alright with me manually putting those entries into all of the goDaddy machines in `/etc/hosts` and `/etc/cloud/templates/hosts.debian.tmpl` ?

**Comment by sxa** [comment]
I'm wondering if we need a provider specific ansible role to be able to make changes such as to the template file going forward, otherwise when we get new machines from this provider we'll lose the entries

**Comment by Willsparker** [comment]
Wouldn't be a bad idea, I think. I would imagine there's more provider specific changes that are needed than changing the host file. Off the top of my head, some providers have shortnames already enabled for Windows, some don't, for example.

**Comment by sxa** [comment]
> however I assume this isn't necessarily the case for the GoDaddy machines?

Yep

**Comment by Willsparker** [comment]
Right, for all 4 of the GoDaddy Machines, I've put the following in both `/etc/hosts` AND `/etc/cloud/templates/hosts.debian.tmpl`
```
<IP of Machine according to Jenkins> test-godaddy-ubuntu1604-x64-X.adoptopenjdk.net test-godaddy-ubuntu1604-x64-X
```
I'm going to go back through the various infra / build issues that had this error message / ones relating to hostnames, in the hope that a few can be closed with these fixes. Closing this issue. I'll open another one that looks to make a provider specific role for the playbooks that will automate this.
