### ISSUE TITLE
test-softlayer-ubuntu1604-x64-1 short on disk space possibly?

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-infrastructure#1425]
Test failed with no disk space error: https://ci.adoptopenjdk.net/job/Test_openjdk11_j9_sanity.external_x86-64_linux_example-test/17/console

However looking at machine, it has 20Gb free now...? maybe fixed itself?

**Comment by Willsparker** [comment]
I'll run a grinder and see if the issue recurs. From the log it say it deleted the workspace after running the tests - however I'd be surprised if tests can amount to 20GB...?

**Comment by Willsparker** [comment]
Grinder succeeded and it appears the machine has 21GB free mounted at `/home`, so seems alright now. Closing

**Comment by andrew-m-leonard** [comment]
Re-occurred: https://ci.adoptopenjdk.net/job/Test_openjdk14_j9_sanity.external_x86-64_linux_quarkus_quickstarts/27/console

**Comment by andrew-m-leonard** [comment]
Suspect test issue with docker image: https://github.com/AdoptOpenJDK/openjdk-tests/issues/1887

**Comment by Willsparker** [comment]
There's an awful lot of containers and images left over from various sources on that machine: 
```
**<none>                                  <none>                       89f40895d8a8        13 hours ago        422MB
<none>                                  <none>                       7368b376cf6a        13 hours ago        422MB
adoptopenjdk-tomee-test                 14-jdk-ubuntu-openj9-full    3db92a60f71b        13 hours ago        849MB
<none>                                  <none>                       033a1897fe47        13 hours ago        422MB
adoptopenjdk-lucene-solr-test           14-jdk-ubuntu-openj9-full    f5c719c7e653        13 hours ago        1.38GB
adoptopenjdk-system-test-test           14-jdk-ubuntu-hotspot-full   b12f70ddb3e1        13 hours ago        835MB
adoptopenjdk-camel-test                 14-jdk-ubuntu-hotspot-full   128083d3620e        13 hours ago        754MB
adoptopenjdk-kafka-test                 14-jdk-ubuntu-hotspot-full   203a8e38d57b        13 hours ago        798MB**
```
To give an example.

Whatevers creating these jobs aren't clearing up after themselves properly and are just filling the machine.
```
root@test-softlayer-ubuntu1604-x64-1:~# df -h
Filesystem      Size  Used Avail Use% Mounted on
...
/dev/xvde1       40G   38G     0 100% /var/lib/docker
...
overlay          40G   38G     0 100% /var/lib/docker/overlay2/af83920345799fea2b2eec0b859c04a61587721bd6625a9de904bb4186f6596a/merged
```

**Comment by Willsparker** [comment]
For the sake of not wanting to ruin anything, I've removed all containers and all of the dangling images, using `docker rmi $(docker images -f "dangling=true" -q)`.
This will have just deleted all of the intermediate containers / images that chew up a lot of space.
It's freed up 7.0GB:
```
root@test-softlayer-ubuntu1604-x64-1:~# df -h
...
/dev/xvde1       40G   31G  7.0G  82% /var/lib/docker
```
