### ISSUE TITLE
Create a role to run tasks specific to machine providers

### ISSUE THREAD

**Issue by Willsparker** [AdoptOpenJDK/openjdk-infrastructure#1427]
Ref: https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1423#issuecomment-654186885 

Some providers have differences in the way some of the machines are configured. The main example that prompted this issue is the way `goDaddy` has it's `/etc/hosts` file setup. Currently, our playbooks will alter the `/etc/hosts` file :
https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/fab906de48f8e63262f27a2da044a8512334c5d6/ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/main.yml#L52
However, specifically `goDaddy` machines will reset the `/etc/hosts` file to a template file at `/etc/cloud/templates/hosts.debian.tmpl` whenever restarted, causing the issues found at #1423 and #1145 .

If we had a role which runs tasks specific to machine providers, we could stop issues like this. I suppose this could be setup a lot like how the `Common` role is, with provider specific `.yml` files, however there may not be that many tasks to really merit it.

**Comment by Willsparker** [comment]
With each machine, we set the hostnames of it to what we call the machines in `inventory.yml` / on Jenkins. i.e., the hostname of `test-godaddy-ubuntu1604-x64-1` is `test-godaddy-ubuntu1604-x64-1`.
We can use this as a way of identifying the provider for use in ansible, running something along the lines of `hostname | cut -d- -f2`, and registering the output to a variable. I tried this approach on the following OSs and it appears to work:
```
Debian8
Ubuntu1604
Ubuntu1804
CentOS6
CentOS7
```
The only downside of using this is that in some machines, the hostname hasn't been set properly (i.e. `build-godaddy-rhel7-x64-1` has the hostname `0a`), however these aren't the majority, and would presumably need to be rectified anyway.

For ease, I'm going to create a single role for provider specific functions, as there doesn't appear to be enough (currently) to really merit a structure similar to that of the `Common` role.

**Comment by jdekonin** [comment]
Also something to keep in mind, there are folks that use the playbooks that do not use the inventory.yml or the naming convention that is used here.  It would be nice if that wasn't being forced onto all users.  My team uses a our own `main.yml` and only includes those roles that we know work for our environment(s), so we would definitely appreciate this in its own role if that were at all possible.

**Comment by Willsparker** [comment]
Good point. I can put the `adoptopenjdk` tag onto the role/tasks, which we already suggest people skip when running these playbooks- seems fitting as the only group to benefit from a provider specific role is AdoptOpenJDK :) Does that work for your team?
