### ISSUE TITLE
Date and time check request for build-siteox-solaris10u9-x64-1

### ISSUE THREAD

**Issue by adamfarley** [AdoptOpenJDK/openjdk-infrastructure#1430]
I noticed a solaris build failed with a CertificateNotYetValidException.

```
java.security.cert.CertificateNotYetValidException: NotBefore: Sat Jul 04 19:00:00 CDT 2020
```

This implies that it has the wrong date + time set locally.

Please could someone with access to the machine pop on there and see what date it thinks it is?

If it's wrong, please correct it. Thanks. :)

Machine: build-siteox-solaris10u9-x64-1

**Comment by gdams** [comment]
the date is wrong but it doesn't look really wrong:

```bash
#  date
Sun Jul  5 06:05:10 CDT 2020
```

updating now anyway

**Comment by gdams** [comment]
running a test build: https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-solaris-x64-hotspot/371/console
