### ISSUE TITLE
Replace build-packet-centos74-armv8-1 with new machine with reliable "disk"

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-infrastructure#1431]
Issue https://github.com/AdoptOpenJDK/openjdk-build/issues/1804
highlighted a probable intermittent "disk" I/O issue during "builds"
We need a reliable centos7 arm x64 machine replacement

**Comment by gdams** [comment]
we will switch to aarch64 docker images once we've got the CPU releases out so this will be unnecessary https://github.com/AdoptOpenJDK/openjdk-build/pull/1964
