### ISSUE TITLE
Memory usage review requested for test-godaddy-centos7-x64-1

### ISSUE THREAD

**Issue by adamfarley** [AdoptOpenJDK/openjdk-infrastructure#1439]
[One of the tests](https://trss.adoptopenjdk.net/output/test?id=5f0522367eaab3443c94d44e) is reporting that it can't find 4g of available memory on the machine, while the pre-test check appears to believe the os has more than that much.

Please check this machine and see if something's hogging the memory.

If it is, please get the memory released if possible, or perhaps just turn the machine off + on?

**Comment by sxa** [comment]
There were a couple of docker images on the machine which I've cleared up - both were running java processes using in the order of 1Gb of RAM. One was `camel-quarkus` and the other was `tomee` `microprofile-tck`.

I'm fairly sure this will resolve it.

**Comment by adamfarley** [comment]
Thanks @sxa :)
