### ISSUE TITLE
Fix QEMU VMs for QEMUPlaybookCheck; Investigate adding ARM64 too

### ISSUE THREAD

**Issue by Willsparker** [AdoptOpenJDK/openjdk-infrastructure#1444]
Ref: https://ci.adoptopenjdk.net/job/QEMUPlaybookCheck/ , #1059 

For awhile the s390x machine at the referenced Jenkins job has not been able to complete its playbook due to what looks like missing packages (From https://ci.adoptopenjdk.net/job/QEMUPlaybookCheck/41/ARCHITECTURE=s390x,label=vagrant/ ):

```
install 'gnupg2'' failed: E: Failed to fetch http://gb.ports.ubuntu.com/ubuntu-ports/pool/main/o/openldap/libldap-common_2.4.45+dfsg-1ubuntu1.4_all.deb  404  Not Found [IP: 91.189.88.150 80]\nE: Failed to fetch http://gb.ports.ubuntu.com/ubuntu-ports/pool/main/o/openldap/libldap-2.4-2_2.4.45+dfsg-1ubuntu1.4_s390x.deb  404  Not Found [IP: 91.189.88.150 80]\nE:
```

ppc64le has also been failing but reporting a false positive ( from https://ci.adoptopenjdk.net/job/QEMUPlaybookCheck/41/ARCHITECTURE=ppc64le,label=vagrant/ ). It appears the build is failing due to `FILENAME` not being defined before running `make-adopt-build-farm.sh`
```
01:46:05 BRANCH:  (For release either BRANCH or TAG should be set)
01:46:05 TAG: 
01:46:05 FILENAME must be set in the environment
01:46:05 + [[ true == true ]]
```
As `QEMUPlaybookCheck` uses the same script to build the [JDK](https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/master/ansible/pbTestScripts/buildJDK.sh) as `vagrantPlaybookCheck` , this should be fixed with #1442

When this Jenkins job was initially put in, I was unable to get `ARM64` to work as `ssh`ing to the machine wasn't working, so I'll aim to give this another go too.

**Comment by Willsparker** [comment]
With S390x, I was able to replicate the problem, and fixed it by running `sudo apt-get update` before attempting to install `gnupg2`. I'll add `update_cache: yes` to the task to do this.

**Comment by Willsparker** [comment]
QEMUPlaybookCheck run to determine any other issues with s390x: 
https://ci.adoptopenjdk.net/job/QEMUPlaybookCheck/42/

**Comment by sxa** [comment]
gcc 4.8 install resolved in https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/1454

**Comment by Willsparker** [comment]
https://ci.adoptopenjdk.net/job/QEMUPlaybookCheck/46/
`QPC` run with the changes in @sxa 's above PR

**Comment by Willsparker** [comment]
The above run shows that it fails at the Docker role with: 
```
09:29:09 TASK [Docker : Install Docker for Debian] **************************************
09:29:18 fatal: [localhost]: FAILED! => {"changed": false, "msg": "No package matching 'docker-ce' is available"}
```
It looks like it's called `docker.io` https://packages.debian.org/buster/arm64/docker.io/download for ARM64 Deb10.
