### ISSUE TITLE
Cygwin 3.15 is unable to build OpenJ9

### ISSUE THREAD

**Issue by Willsparker** [AdoptOpenJDK/openjdk-infrastructure#1448]
As the title suggests - Cygwin 3.15 is unable to build OpenJ9 due to the following error:
```
if not exist "C:\Users\Administrator\git\openj9-openjdk-jdk11\build\windows-x86_64-normal-server-release\vm\" mkdir "C:\Users\Administrator\git\openj9-openjdk-jdk11\build\windows-x86_64-normal-server-release\vm\"
The filename, directory name, or volume label syntax is incorrect.^M
make[6]: *** [C:/Users/Administrator/git/openj9-openjdk-jdk11/build/windows-x86_64-normal-server-release/vm/compiler/build/rules/win-msvc/common.mk:90: jit_createdirs] Error 1
make[6]: Leaving directory '/cygdrive/c/Users/Administrator/git/openj9-openjdk-jdk11/build/windows-x86_64-normal-server-release/vm/compiler'
make[5]: *** [makefile:70: default] Error 2
```
I was able to reproduce this on a VM too, where the only difference between a previous working JDK11/J9 build and that one, was updating `cygwin` and `cygwin-devel` packages to `3.15` with `setup_x86-64.exe`.

Currently the playbooks install `3.15`, so won't be usable until `cygwin` is updated.

Ref: https://github.com/eclipse/openj9/issues/10109

**Comment by Willsparker** [comment]
(assigned it to myself so I remember to go back and close this either when the eclipse issue has been closed, or when Cygwin is updated)

**Comment by lumpfish** [comment]
Looks like cygwin 3.1.6 is available: https://cygwin.com/pipermail/cygwin-announce/2020-July/009605.html.  Don't know if it fixes the particular issue breaking the openj9 build though.

**Comment by Willsparker** [comment]
Yep! Spotted that - https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/733/ should hopefully show us if its fixed :-)

**Comment by Willsparker** [comment]
It appears to have worked, for JDK8 / J9 at least.
I'm going to try JDK11 / J9 as well.

**Comment by Willsparker** [comment]
https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/735/
Yep! Cygwin 3.16 has fixed the issue. Closing now
