### ISSUE TITLE
Install Xvfb or equivalent on Mac test machines

### ISSUE THREAD

**Issue by smlambert** [AdoptOpenJDK/openjdk-infrastructure#1450]
Much like the recent work to enable jdk_awt and jdk_swing tests on AIX (via https://github.com/AdoptOpenJDK/openjdk-tests/pull/1835), we should do the same for Mac / osx platform.  Those tests require require DISPLAY variable to be set.  

2 parts required to enable jdk_awt/jdk_swing test targets: 
- xvfb or xquartz or some equivalent needs to be installed on machine
- changes similar to https://github.com/AdoptOpenJDK/openjdk-tests/pull/1835 need to be made to the Jenkinsfile for testing to set the DISPLAY variable at the start of the test run and unset it at the end of the run.

For additional details refer to GHE runtimes/infrastructure/issues/1111 and runtimes/backlog/issues/280

**Comment by karianna** [comment]
Duplicate of https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/211

**Comment by smlambert** [comment]
Ah, thanks I wondered if it already existed as an issue, will close this as dup (but VERY keen on getting #211 resolved).
