### ISSUE TITLE
build-softlayer-win2012r2-x64-1 intermittently fails to call the adopt api when hosting JDK-Next pipelines

### ISSUE THREAD

**Issue by M-Davies** [AdoptOpenJDK/openjdk-infrastructure#1459]
Ok so a little background first.

We have been seeing sporadic api request failures across the windows [jdk next jobs](https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk/) (both hotspot and openj9 are affected). The errors look like net related failures where curl is closed early due to poor internet connections (unconfirmed), see below
```
10:10:31  + ./build-farm/make-adopt-build-farm.sh
10:10:31  This appears to be JDK Head. Querying the Adopt API to get the JDK HEAD Number (https://api.adoptopenjdk.net/v3/info/available_releases)...
10:10:31  RETRYWARNING: Query 1 failed. Retrying in 30 seconds (max retries = 5)...
10:10:36   > git rev-parse "origin/master^{commit}" # timeout=10
10:10:36   > git config core.sparsecheckout # timeout=10
10:10:36   > git checkout -f 6de791416bb7f18af4de8aa4692061427d5e96db # timeout=10
10:11:04  This appears to be JDK Head. Querying the Adopt API to get the JDK HEAD Number (https://api.adoptopenjdk.net/v3/info/available_releases)...
10:11:04  RETRYWARNING: Query 2 failed. Retrying in 30 seconds (max retries = 5)...
10:11:36  This appears to be JDK Head. Querying the Adopt API to get the JDK HEAD Number (https://api.adoptopenjdk.net/v3/info/available_releases)...
10:11:36  RETRYWARNING: Query 3 failed. Retrying in 30 seconds (max retries = 5)...
10:12:03  This appears to be JDK Head. Querying the Adopt API to get the JDK HEAD Number (https://api.adoptopenjdk.net/v3/info/available_releases)...
10:12:03  RETRYWARNING: Query 4 failed. Retrying in 30 seconds (max retries = 5)...
10:12:36  Failed 5 times to query or parse the adopt api. Dumping headers via curl -v https://api.adoptopenjdk.net/v3/info/available_releases and exiting...
```
For the record, no headers are dumped with `curl -v` despite the console log saying it does.

After some investigation with a few test runs:
- https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk/job/jdk-windows-x64-openj9/62/
- https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk/job/jdk-windows-x64-openj9/66/console
- https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk/job/jdk-windows-x64-openj9/68/console

I have concluded that it does not affect other java versions as far as I can tell from some more test runs on other java versions
- https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-windows-x64-openj9/769/console
- https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-windows-x64-openj9/686/console
- https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-windows-x64-hotspot/678/console
- https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk15/job/jdk15-windows-x64-openj9/46/console

It only seems to affect JDK-Next [openj9](https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk/job/jdk-windows-x64-openj9/) and [hotspot](https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk/job/jdk-windows-x64-hotspot/) windows jobs.

Furthermore it only seems to affect [build-softlayer-win2012r2-x64-1](https://ci.adoptopenjdk.net/computer/build-softlayer-win2012r2-x64-1/) as other machines [pass without hitting this problem](https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk/job/jdk-windows-x64-hotspot/204/consoleFull)

Running with clean workspace might resolve the hidden problem but it currently cannot be done due to [an issue affecting windows machines cleaning themselves](https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1396) as seen below https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk/job/jdk-windows-x64-openj9/69/console

Code for the api querying is here:
https://github.com/AdoptOpenJDK/openjdk-build/blob/master/build-farm/make-adopt-build-farm.sh#L29-L58

**Comment by Willsparker** [comment]
>  https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk/job/jdk-windows-x64-openj9/69/console

Ref: #1396 - Thought we fixed this with the two `rm -rf` commands, seems not :/ - I'll update the reference issue.

**Comment by Willsparker** [comment]
Alright, first brief look: 
- I don't think it's necessarily a network related thing. The page its querying for ( https://api.adoptopenjdk.net/v3/info/available_releases ) is so tiny that if it can't get that, I would imagine I wouldn't be able to connect to it with 'Microsoft Remote Desktop'.
- The lines of code you linked are only ever ran on `JDK` jobs ( due to 
https://github.com/AdoptOpenJDK/openjdk-build/blob/6de791416bb7f18af4de8aa4692061427d5e96db/build-farm/make-adopt-build-farm.sh#L27 ), hence why they'll only appear on those jobs.
- Looking at some of the most recent builds, the machine hasn't passed at all. Which is good because intermittent issues particularly suck.

Running `curl` in the `cygwin` terminal on the machine output absolutely nothing, however when you run it in `cmd`, an error box appears saying: 
```
The procedure entry point _memset_chk could not be located in the dynamic link library C:\cygwin64\bin\curl.exe
```
Followed by the standard Windows `curl.exe has stopped working` box.

When running this on `build-softlayer-win2012r2-x64-2`, `curl` runs as expected- so it seems to be an issue with the `curl` installation on `cygwin`.

**Comment by M-Davies** [comment]
> Looking at some of the most recent builds, the machine hasn't passed at all. Which is good because intermittent issues particularly suck.

Bear in mind, some of the most recent builds were likely my test runs. Make sure you check who started the job 😉

**Comment by Willsparker** [comment]
When I run an old version of `cygwin setup` (version 2.889), the list of mirrors is reduced to the following:
```
http://cygwin.mirror.constant.com
http://update.setup.invalid
```
According to the playbooks, we opt for the ` https://mirrors.kernel.org/sourceware/cygwin/` mirror, so something isn't right. Even going for the first one throws a lot of issues, so I'm going to download a new version of `setup.exe`. This should allow me to reinstall `curl` - I'll try first at the same version it currently is, and if that doesn't fix the issue, I'll try an updated version.

**Comment by Willsparker** [comment]
The new setup.exe (v2.905) had the correct mirrors and allowed the reinstallation of `curl` (v7.58.0), and now it works as expected within both the cygwin terminal and `cmd`. 
` curl -v https://api.adoptopenjdk.net/v3/info/available_releases ` outputs correctly too. 
@M-Davies could you re-try the build?

**Comment by M-Davies** [comment]
https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk/job/jdk-windows-x64-openj9/71/console looks good! Thanks @Willsparker
