### ISSUE TITLE
AIX Ramdisk Job Failures (Can't Find Ramdisk)

### ISSUE THREAD

**Issue by adamfarley** [AdoptOpenJDK/openjdk-infrastructure#1461]
This job keeps failing because the subjobs can't seem to find the ramdisk: https://ci.adoptopenjdk.net/job/Monitor_AIX_ramdisks/

```
ls: 0653-341 The file /ramdisk0/build/* does not exist.
```

Due to the comments [here](https://github.com/AdoptOpenJDK/openjdk-build/pull/1984#pullrequestreview-454077034) and [here](https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1443#issuecomment-658897724), I believe this is because the AIX machines no longer use ramdisks.

If this will be the case going forward, I recommend disabling the Monitor_AIX_ramdisks job (or at least the schedule part).

**Comment by Willsparker** [comment]
That job been disabled - I can't see who or when it was disabled, but it is currently, so closing the issue :-)
