### ISSUE TITLE
AWS aarch64 VM appears to have no cmake

### ISSUE THREAD

**Issue by adamfarley** [AdoptOpenJDK/openjdk-infrastructure#1462]
Two [JDK11](https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-linux-aarch64-openj9/428/consoleFull) [builds](https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-linux-aarch64-openj9-linuxXL/303/consoleFull) on this machine failed with this error:

```
00:43:53  checking for cmake... no
00:43:53  configure: error: Could not find required tool for CMAKE
00:43:53  configure exiting with result code 1
```

Specific machines: 
- EC2 (adopt_aws) - Dynamic Linux aarch64 VM provisioned from AWS (i-00023f9bef762963a)
- EC2 (adopt_aws) - Dynamic Linux aarch64 VM provisioned from AWS (i-09906b2cd5c8665e7)

Since these were dynamically provisioned, I presume there's a template or ansible book (etc) that they are generated from.

Can someone please review this template-book-thing to see if cmake is in there?

**Comment by Haroon-Khel** [comment]
Looking though our Unix playbook, it seems `cmake` only gets installed mac, and architectures x86, ppc64le, s390x and armv7l. Couldn't find anything for aarch64 so it seems this may be why this issue is occuring.

I don't exactly know how the setup behind how we dynamically provision AWS VMs, so will have to find this out first.

**Comment by sxa** [comment]
Following the merging of https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/1464 the following jobs are still not running successfully - same cmake failure:
- https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-linux-aarch64-openj9/434
- https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-linux-aarch64-openj9-linuxXL/309

**Comment by Willsparker** [comment]
Thought I'd mention that (from what I can see), the PR did indeed work to install cmake: https://ci.adoptopenjdk.net/job/QEMUPlaybookCheck/62/ARCHITECTURE=aarch64,label=vagrant/console
From the looks of it, the machines are being provisioned using this build image: https://hub.docker.com/r/adoptopenjdk/centos7_build_image/tags
of which, the `arm64` architecture hasn't been updated for 12 days.

**Comment by sxa** [comment]
@gdams is investigating

**Comment by knn-k** [comment]
The latest build is OK.
https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-linux-aarch64-openj9/437/

>[2020-07-29T23:43:36.569Z] checking for cmake... /usr/local/bin/cmake

**Comment by gdams** [comment]
okay all looks good then! closing

**Comment by knn-k** [comment]
The build 437 above was run on the following machine:

```
[2020-07-29T23:33:07.535Z] Running on EC2 (adopt_aws) - Dynamic Linux aarch64 VM provisioned from AWS (i-00724003cc63e26a8) in /home/ubuntu/workspace/build-scripts/jobs/jdk11u/jdk11u-linux-aarch64-openj9
```
