### ISSUE TITLE
Failure in java default task on RHEL7 on ppc64le/s390x

### ISSUE THREAD

**Issue by sxa** [AdoptOpenJDK/openjdk-infrastructure#1467]
May affect other environments e.g. CentOS but this task and the equivalent s390x one in the same section don't appear to work on my RHEL7.8/ppc64le and s390x systems

https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/master/ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/RedHat.yml#L176

```
TASK [Common : Set default java version - RHEL 7 ppc64le] *********************************************************************************************************************************************************
skipping: [aopocz11]
fatal: [aopocp11]: FAILED! => {"changed": false, "msg": "Specified path java-1.8.0-openjdk.ppc64le does not exist"}
```

**Comment by Willsparker** [comment]
I've been able to recreate the problem on RHEL7.6. Judging from the playbook log: 
```
 ______________________________________________________ 
< TASK [Common : Install Java (Not RedHat 6 on ppc64)] >
 ------------------------------------------------------ 
changed: [9.30.212.79] => (item=java-1.7.0-openjdk-devel)
changed: [9.30.212.79] => (item=java-1.8.0-openjdk-devel)
```
Java is definitely installed. It also appears in `/usr/lib/jvm/`:
```
[root@ezel1 ~]# ls /usr/lib/jvm
...
java-1.7.0-openjdk-1.7.0.261-2.6.22.2.el7_8.ppc64le
...
java-1.8.0-openjdk-1.8.0.262.b10-0.el7_8.ppc64le
...
```
For some reason, the path specified in the task that @sxa linked to is _very_ specific: `/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.161-0.b14.el7_4.ppc64/jre/bin/java`
To avoid this, it'd be better to make the path one of the symlinks that is created when installing that tasks (i.e. `java-1.8.0-openjdk` ). This will keep it consistently working, regardless of the JDK8 version.

**Comment by Willsparker** [comment]
Edit- apologies, the task that was the issue was 'Set default java version - RHEL 7 ppc64le' , not 'Set default java version - RHEL 7 ppc64'. Either way, the proposed fix is the same- change the path from `java-1.8.0-openjdk.ppc64le` to `java-1.8.0-openjdk`

**Comment by Willsparker** [comment]
Changing the path to a correct one causes a different issue: 
```
FAILED! => {"changed": false, "msg": "Needed to install the alternative, but unable to do so as we are missing the link"}
```
This appears to be due to the fact that the `alternatives` ansible module requires the `link` parameter for RHEL-based systems: https://docs.ansible.com/ansible/latest/modules/alternatives_module.html#parameter-link

Adding `link: /etc/alternatives/java` reports a different error message: 
```
 FAILED! => {"changed": false, "cmd": "/usr/sbin/update-alternatives --install /etc/alternatives/java java /usr/lib/jvm/java-1.8.0-openjdk/bin/java 50", "msg": "the primary link for java must be /usr/bin/java"
```

**Comment by Willsparker** [comment]
Okay- Updating the task to be: 
```
- name: Set default java version - RHEL 7 ppc64le
  alternatives:
    name: java
    link: /usr/bin/java
    path: /usr/lib/jvm/java-1.8.0-openjdk/jre/bin/java
  when:
    - ansible_distribution_major_version == "7"
    - ansible_architecture == "ppc64le"
  tags: default_java
```
Passes, and the following is the result:
```
[root@ezel1 jvm]# alternatives --display java
...
/usr/lib/jvm/java-1.8.0-openjdk/jre/bin/java - priority 50
...
```
PR incoming

**Comment by Willsparker** [comment]
Double checked on a RHEL7.6 s390x machine, when installing `java-1.8.0-openjdk-devel` as it does on ppc64le, the same `java-1.8.0-openjdk` symlink is still in `/usr/lib/jvm`, therefore we can use the same task for both architectures

**Comment by Willsparker** [comment]
Interestingly, The `link` parameter issue doesn't affect x86_64 CentOS6/7/8. Not entirely sure why- but `VPC` has shown that they work as expected. We also don't have tasks for non `x86_64` CentOS architecture, so this won't be an issue for CentOS.
