### ISSUE TITLE
EPEL 6 repo not installed on RHEL6 so libdwarf-devel is not found

### ISSUE THREAD

**Issue by sxa** [AdoptOpenJDK/openjdk-infrastructure#1470]
(Seen on one of my own servers - installing the epel 6 rpm resolved it)

**Comment by Haroon-Khel** [comment]
Ill add the task to the `Redhat.yml` file in Common

**Comment by sxa** [comment]
@Willsparker Can you see if your vagrant VM for Cent6 already has the EPEL repository in it - would be good to know why it doesn't seem to affect VPC. (I've had a couple of other issues with that playbook too on RHEL but that was the most obvious one)

**Comment by Willsparker** [comment]
Looking at https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/OS=CentOS6,label=vagrant/743/consoleFull
The following task is run : https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/9a8939be81093e4d91784cfe42dc2008204b9fda/ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/CentOS.yml#L9
Which enables it.
From the look of the provisioning log from `vagrant up`, it's already there on the vagrant box as it's able to install `ansible` on it, before the playbook even begins: 
```
20:38:23     adoptopenjdkC6: ================================================================================
20:38:23     adoptopenjdkC6:  Package                 Arch         Version               Repository     Size
20:38:23     adoptopenjdkC6: ================================================================================
20:38:23     adoptopenjdkC6: Installing:
20:38:23     adoptopenjdkC6:  ansible                 noarch       2.6.20-1.el6          epel           10 M
```
Double checked on a fresh CentOS6 VM and yep, that is definitely the expected `epel` repo:
```
[vagrant@adoptopenjdkC6 ~]$ cat /etc/yum.repos.d/epel.repo 
[epel]
name=Extra Packages for Enterprise Linux 6 - $basearch
#baseurl=http://download.fedoraproject.org/pub/epel/6/$basearch
mirrorlist=https://mirrors.fedoraproject.org/metalink?repo=epel-6&arch=$basearch
failovermethod=priority
enabled=1
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-6
```

**Comment by Willsparker** [comment]
Fixed with above PR ! Thanks @Haroon-Khel
