### ISSUE TITLE
Add support for ARM32 in QEMUPlaybookCheck

### ISSUE THREAD

**Issue by Haroon-Khel** [AdoptOpenJDK/openjdk-infrastructure#1471]
As pointed out in https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/1464#issuecomment-664449980, support for arm32 architecture is missing from the QEMU playbook check

**Comment by Willsparker** [comment]
@Haroon-Khel Happy to assist if you need it :)

**Comment by Haroon-Khel** [comment]
Able to create a working ARM32 disk image, and boot it using qemu-system-arm. Last hurdle is to enable ssh on the disk image, which @Willsparker suggests should work by using qemu 5.0

**Comment by Haroon-Khel** [comment]
Using qemu 5.0 didnt solve the problem

**Comment by Willsparker** [comment]
Above PR has been merged and there's a new issue for getting Debian Arm32 working, so I'll close this one :-) Cheers @Haroon-Khel
