### ISSUE TITLE
ccache built from source if it is already in /usr/local/gcc/bin

### ISSUE THREAD

**Issue by sxa** [AdoptOpenJDK/openjdk-infrastructure#1472]
In most linux cases we use a gcc-7 extracted from a prebuilt tarball which includes a copy of ccache.
The ccache role only checks if there is a version in `/usr/local/bin` before deciding whether to build it's own. We should check for that location OR /usr/local/gcc/bin (Or perhaps symlink /usr/local/bin/ccache -> /usr/local/gcc/bin/ccache during the `gcc_7` role instead.

**Comment by Willsparker** [comment]
I'll look into this :) 
I think symlink-ing would be the best option- presumably the build scripts are setup to search for `ccache` at set places so they may not be able to find that version, even if `ansible` does.

**Comment by sxa** [comment]
On the appropriate builds we add `/usr/local/gcc/bin` into the PATH https://github.com/AdoptOpenJDK/openjdk-build/blob/master/build-farm/platform-specific-configurations/linux.sh#L135 so it's not needed but I'm ok with the symlink
