### ISSUE TITLE
Windows installers can't see windows.p12

### ISSUE THREAD

**Issue by M-Davies** [AdoptOpenJDK/openjdk-infrastructure#1484]
While running a JRE installer for a [jdk8u-windows-x64-openj9](https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-windows-x64-openj9/781/console) build, https://ci.adoptopenjdk.net/job/build-scripts/job/release/job/create_installer_windows/6351/console couldn't find a dependancy
```
Package language = 1033,1031,3082,1036,1041,2052,1028, ProductLanguage = 1033, Database codepage = 1252
MSI validation was skipped by option SKIP_MSI_VALIDATION=true
SignTool Error: File not found: C:\Users\jenkins\windows.p12
Failed to sign with SHA1
```
Not sure if this or infrastructure is the correct place to raise this but seeing as it's a installer tool, I would have thought this would have the best initial place

**Comment by M-Davies** [comment]
Also see 
- https://ci.adoptopenjdk.net/job/build-scripts/job/release/job/sign_build/10266/console (for https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-windows-x64-openj9-windowsXL/442/console on `build-softlayer-win2012r2-x64-1`)
- https://ci.adoptopenjdk.net/job/build-scripts/job/release/job/sign_build/10260/console (for https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-windows-x64-openj9-windowsXL/381/console on `build-softlayer-win2012r2-x64-1`)

**Comment by sxa** [comment]
The failures are all on the azure build boxes - the last two links you've given are to the build jobs, not the signing ones where the error messing regarding the certificate is showing up.

Those machines were set up by @gdams with some help from @Willsparker so one of them may have some knowledge of this. I'm not sure what's changed though ...

**Comment by M-Davies** [comment]
> the last two links you've given are to the build jobs, not the signing ones where the error messing regarding the certificate is showing up

This would be better placed in inf or build in that case then as the errors are the same

**Comment by M-Davies** [comment]
> The failures are all on the azure build boxes

I've edited the comment to add some more failures

**Comment by Willsparker** [comment]
possible ref: https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/1247

Annoyingly, I can't see the `sign_build` runs- however, I remember that particular issue : https://adoptopenjdk.slack.com/archives/C09NW3L2J/p1590048825232400

The summary of the above slack conversation is that the file is still there, and renaming them / renaming them back appeared to have fixed it.
I have a look at `build-azure-win2012r2-x64-1` where it is at `C:/users/jenkins/windows.p12` , and `build-softlayer-win2012r2-x64-1` where it is in the same place.
In the hopes that it's the same issue, I've renamed the file to something, and then put it back to `windows.p12` for both machines- let me know if there's any difference.

**Comment by Willsparker** [comment]
https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-windows-x64-openj9/783/
Would someone mind seeing why the installer failed for this build, to confirm if this is the same issue? The run was on `build-softlayer-win2012r2-x64-1`

**Comment by M-Davies** [comment]
@Willsparker https://ci.adoptopenjdk.net/job/build-scripts/job/release/job/create_installer_windows/6398/console
```
SignTool Error: File not found: C:\Users\jenkins\windows.p12

Failed to sign with SHA1
```

**Comment by adamfarley** [comment]
Previously, this issue seemed to happen alongside a StackOverflowError in the compileGroovy build step.

https://github.com/AdoptOpenJDK/openjdk-build/issues/1753

Could they be connected?

I ask because we're seeing that too now.

[jdk15-windows-x86-32-hotspot/7](https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk15/job/jdk15-windows-x86-32-hotspot/7/console)

**Comment by Willsparker** [comment]
The `StackOverflowError` by Gradle previously was linked to not finding a JDK that can run it. I don't believe we've changed the Gradle version recently so I think this may be a coincidence and not linked to this error

**Comment by adamfarley** [comment]
Ok, will raise a separate issue after lunch.

**Comment by Willsparker** [comment]
Every machine with the `Wix` tag has had successful installer runs within the last few hours - it seems this is an intermittent issue as some installer jobs failed in the nightlies but I can't see those logs as the runs are discarded so quickly. I'll keep an eye until I get a run that fails to confirm.

**Comment by Willsparker** [comment]
I can't see this having failed recently. @austin0 @adamfarley Have either of you guys seen this recently? (The last time I could find it after a brief search was the 4th of August)

**Comment by austin0** [comment]
Failing builds have been passing since 12/08/20, whatever you've done seems to be working.

**Comment by Willsparker** [comment]
Alright, I've checked last night's runs and no windows runs failed! (woo) 
It's now been a week we've seen the issue, so I'm going to close this issue- if it recurs, feel free to reopen :-)
