### ISSUE TITLE
Need access build-macstadium-macos1014-x64-2

### ISSUE THREAD

**Issue by Leonardo2718** [AdoptOpenJDK/openjdk-infrastructure#1490]
To debug https://github.com/eclipse/openj9/issues/10313 (which I believe is the same issue as https://github.com/eclipse/openj9/issues/9416) I need to retrieve the build and core files from [build-macstadium-macos1014-x64-2](https://ci.adoptopenjdk.net/computer/build-macstadium-macos1014-x64-2/).

**Comment by Leonardo2718** [comment]
@gdams Could you grant me access with the same key as you used for https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1362#issuecomment-638842862? Thanks!

**Comment by gdams** [comment]
key added: 

`ssh administrator@207.254.28.76`

**Comment by sxa** [comment]
@Leonardo2718 Is this access still required?

**Comment by Leonardo2718** [comment]
@sxa @gdams It looks it won't be possible for me to recover a core file from this machine so I no longer require access. Same for #1362.
