### ISSUE TITLE
test-marist-ubuntu1604-s390x-3 agent process crash

### ISSUE THREAD

**Issue by M-Davies** [AdoptOpenJDK/openjdk-infrastructure#1491]
https://ci.adoptopenjdk.net/view/Test_openjdk/job/Test_openjdk15_hs_sanity.openjdk_s390x_linux/4/console suggested [test-marist-ubuntu1604-s390x-3](https://ci.adoptopenjdk.net/computer/test-marist-ubuntu1604-s390x-3/) is offline and the jenkins UI is complaining that the jenkins agent failed to start on it `This agent is offline because Jenkins failed to launch the agent process on it. See log for more details`

**Comment by Willsparker** [comment]
The log actually says :
```
Evacuated stdout
Agent successfully connected and online
```
However is still apparently loading - I think the agent has hanged so I'm going to disable it, attempt to ssh into it, `kill` the jenkins agent process and restart it. However, `ssh`ing is currently timing out ...

**Comment by Willsparker** [comment]
https://adoptopenjdk.slack.com/archives/C53GHCXL4/p1596639847367300?thread_ts=1596636363.360900&cid=C53GHCXL4

There's a power outage problem where the machines are based. I'll keep the issue open until the problem is resolved :-)

**Comment by Willsparker** [comment]
It's back up now :-)
