### ISSUE TITLE
Request for access to sign_build job

### ISSUE THREAD

**Issue by adamfarley** [AdoptOpenJDK/openjdk-infrastructure#1492]
Summary: Please grant me access to this job: https://ci.adoptopenjdk.net/job/build-scripts/job/release/job/sign_build/

Details:

These jobs appear to have failed several times last night, causing Windows builds to fail as a result, but I can't tell what's wrong (or even if it's an existing issue) because I can't see where sign_build broke.

**Comment by Willsparker** [comment]
ping @karianna 

Don't suppose I could get that too? 😅

**Comment by austin0** [comment]
+1 can I also have access to this.

**Comment by karianna** [comment]
All three folks have been vetted and given access.
