### ISSUE TITLE
build-azure-win2012r2-x64-2 sees StackOverflowError in Task :compileGroovy

### ISSUE THREAD

**Issue by adamfarley** [AdoptOpenJDK/openjdk-infrastructure#1494]
**Summary**

Three builds on this machine failed a compileGroovy task.

**Further Details**

https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk15/job/jdk15-windows-x86-32-hotspot/7/console
https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-windows-x86-32-hotspot/676/console
https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-windows-x64-openj9/703/console

In [this issue](https://github.com/AdoptOpenJDK/openjdk-build/issues/1659) we saw the same symptom, and the issue was resolved by restarting the machine. While not an ideal long-term resolution, it has much to recommend it as a short-term fix.

**Error Message**
```
00:32:44  > Task :compileGroovy
00:39:23  > Task :compileGroovy FAILED
00:39:23  
00:39:23  FAILURE: Build failed with an exception.
00:39:23  
00:39:23  * What went wrong:
00:39:23  Execution failed for task ':compileGroovy'.
00:39:23  > java.lang.StackOverflowError (no error message)
```

**Comment by Willsparker** [comment]
For the sake of trying, I've restarted it - we can see with the nightlies whether this fixes it again

**Comment by Willsparker** [comment]
Looking at the failing builds, I don't see any Windows machines that failed at the `build` stage, and I found a build that worked with `build-azure-win2012r2-x64-2` : https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk15/job/jdk15-windows-x64-openj9/60/consoleFull

Closing, but I'll keep an eye on it. I agree that it's not a very good long term fix, I'd rather have something a bit more concrete as a solution.
