### ISSUE TITLE
Jenkins Access: sign-builds and installer jobs

### ISSUE THREAD

**Issue by Willsparker** [AdoptOpenJDK/openjdk-infrastructure#1498]
ping @karianna 

@austin0 and I are unable to see the sign build logs, i.e.  https://ci.adoptopenjdk.net/job/build-scripts/job/release/job/sign_build/10397/ and the installer jobs, i.e. https://ci.adoptopenjdk.net/job/build-scripts/job/release/job/create_installer_windows/6531/

Unfortunately we still aren't able to see sign_builds despite #1492 , not sure if you can see them @adamfarley  ?

**Comment by adamfarley** [comment]
@Willsparker - I can.

You need to log in on another ci page first, as it doesn't know who you are until you do so.

**Comment by adamfarley** [comment]
If that doesn't work, try leaving all tabs on those pages, clearing browser history, logging in on a general-access ci page, and *then* going to the sign job.

**Comment by Willsparker** [comment]
Just tried it, unfortunately still getting Error 404 with `URI: /job/build-scripts/job/release/job/sign_build/`

**Comment by austin0** [comment]
Also unable to access, @adamfarley can you see anything useful [in this run from today](https://ci.adoptopenjdk.net/job/build-scripts/job/release/job/sign_build/10311/)?

**Comment by adamfarley** [comment]
No, because that job ran on Friday (or earlier) and was purged.

The latest run we still have is #10355, which ran on Friday.

**Comment by sxa** [comment]
You had been granted access to the jobs but not [the containing folder](https://ci.adoptopenjdk.net/job/build-scripts/job/release/) (FYI @karianna for next time!)

I have granted @austin0 and @Willsparker access to the folder now.

**Comment by Willsparker** [comment]
Excellent, thanks @sxa

**Comment by karianna** [comment]
Added.
