### ISSUE TITLE
Locale installation task fails if "locales" package not installed

### ISSUE THREAD

**Issue by sxa** [AdoptOpenJDK/openjdk-infrastructure#1502]
Sample error:
```
TASK [Common : Enable ja_JP locale] *********************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "/etc/locale.gen and /var/lib/locales/supported.d/local are missing. Is the package \"locales\" installed?"}

PLAY RECAP **********************************************************************************************
localhost                  : ok=20   changed=12   unreachable=0    failed=1   
```

**Comment by Willsparker** [comment]
What OS / architecture?

**Comment by sxa** [comment]
I think that was on an arm32/raspbian system but I wouldn't expect it to be specific to that

**Comment by Willsparker** [comment]
The closest I could get to that platform was an aarch64/Debian system, which already had `locales 2.28-10` installed.
Of the 4 Distributions that have the locale stuff in the common file, only CentOS uses `localedef`, which is installed from `glibc-common` (which is already in the build package list). RHEL, Ubuntu and Debian use the `locales_gen` ansible module, which, as the error suggests, uses the `locales` package. 
For ease, I'll add a task that installs the locales package before all the locales tasks- as they're not architecture specific, the install task shouldn't have to be either.

**Comment by Willsparker** [comment]
https://ci.adoptopenjdk.net/job/QEMUPlaybookCheck/77/
https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/834/
If the above runs work, I'll PR 👍
