### ISSUE TITLE
pbTests: Get Win2012r2 running stable in VagrantPlaybookCheck

### ISSUE THREAD

**Issue by Willsparker** [AdoptOpenJDK/openjdk-infrastructure#1504]
Ref: https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/ , #1503 , #1287 , #1072 , #924 

Consistently throughout changing stuff with VagrantPlaybookCheck (`VPC`), Windows has caused issues. With some fairly intermittent issues and obscure problems, I thought I'd open an issue to log the problems we have with it, as well as the fixes I use. 
The reason Windows is an issue when Linux currently isn't, is due to the differences between running Ansible on Windows, as opposed to Linux. Within _pbTestScripts/vagrantPlaybookCheck.sh_ , the code branches depending on if the OS specified is Windows or Linux. In addition, Windows has its own specific `buildJDKWin.sh` and `testJDKWin.sh` scripts, again independent from Linux. The other significant difference is the way of connecting to the VM from the host: Linux uses`localhost:portNo`, windows uses the private IP address that vagrant assigns to it.

Currently, I can see two issues:

- [x] Intermittent issue that stops Ansible initially connecting to the Windows VM (e.g.: https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/807/OS=Win2012,label=vagrant/)
```
TASK [Gathering Facts] *********************************************************
fatal: [172.28.128.3]: UNREACHABLE! => {"changed": false, "msg": "credssp: HTTPSConnectionPool(host='172.28.128.3', port=5986): Max retries exceeded with url: /wsman (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f2bfda80a50>, 'Connection to 172.28.128.3 timed out. (connect timeout=30)'))", "unreachable": true}
```
This occurs when Ansible initially starts the connection to the VM. Attempted fixes include trying to include the timeout from 30s to 60s, using `ansible_winrm_operation_timeout_sec: 60` in the ansible config. This issue could be caused by attempting to use the incorrect IP in the host file - so possibly a more stable way of finding the IP is required.

- [ ] Windows VM losing connection to ansible halfway through the playbook (e.g.: https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/808/OS=Win2012,label=vagrant/)
```
08:07:09 TASK [Windows_Updates : Download and Install Windows Updates] ******************
08:12:20 An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ConnectTimeout: HTTPSConnectionPool(host='172.28.128.3', port=5986): Max retries exceeded with url: /wsman (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f09895bc7d0>, 'Connection to 172.28.128.3 timed out. (connect timeout=30)'))
08:12:20 fatal: [172.28.128.3]: FAILED! => {"msg": "Unexpected failure during module execution.", "stdout": ""}
```
I left the times when these tasks executed as it's fairly important as you can see that the task was executing as expecting for awhile as the timeout is only 30 seconds - so in the above example, Ansible must've lost connection at `08:11:50`. This issue tends to occur in the tasks that take longer to execute, however that may just be due to coincidence (I've seen it in `Windows_Updates` twice and `MSVS_2013` once).
This issue could be due to a machine / Virtualbox problem. For some reason any given user on the machine that runs VPC ( infra-softlayer-ubuntu1804-x64-1 ) has multiple virtual `DHCP` servers running ( seen as the `VBoxNetDHCP` process on the machine). As Windows is the only OS in VPC to still use the IP address assigned to it by Vagrant, it could be that `virtualbox` gets confused and assigns the Windows VM a different IP address halfway through, but this is yet to be confirmed.

**Comment by Willsparker** [comment]
Since creating this issue, I've attempted to recreate the 1st issue 5 times, locally on my mac, each time Ansible was able to connect to the VM as expected- which would point to a machine issue. I'll attempt to do the same locally on the machine in question.

**Comment by Willsparker** [comment]
Upon running `vagrantPlaybookCheck.sh` locally on the machine, the error did occur. The processes afterwards are single instances `VBoxSVC`, `VBoxXPCOMIPCD`, `VBoxHeadless` and `VBoxNetDHCP`, as to be expected.
Rerunning `vagrant provision` after changing the Vagrantfile to output the IP address for the machine showed that the IP address in the host file was correct. Rerunning the `.\ConfigureRemotingForAnsible.ps1` scripts didn't help either.

In addition to this, the 2nd issue occurred again: https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/810/OS=Win2012,label=vagrant/console .
Checking out the machine locally, I found that `vagrant status` was showing the machine as being in the `poweroff` state. Restarting it and running `ansible all -i playbooks/AdoptOpenJDK_Windows_Playbook/hosts.win -u Administrator -m win_ping` worked as expected however, so the IP Address didn't change due to several `VBoxNetDHCP` processes running, the machine just turned off. I don't believe this is due to Jenkins as this was the only OS running in that particular VPC run (however, I'll attempt to confirm that by running it on the machine).

In this, I've found `vagrant` has ` vagrant winrm --command` command, that works similarly to `vagrant powershell -c` or `vagrant ssh -c` which will allow me to interact with the machine outside of Ansible- this also works with the machine that Ansible couldn't connect to, which may be a good alternative to use the vagrant IP address in the host-file (similar to what I did with the linux OSs in #1442 )

**Comment by Willsparker** [comment]
Regarding Issue one, I've had success in using `127.0.0.1:55986`, instead of the IP address to connect with Ansible. The port `55896` refers to the winrm-ssl port that's forwarded to the guest VM's port `5986`. I found this with `--debug` output when running `vagrant winrm --command "echo hi"`.
```
DEBUG virtualbox_6_0:   - [1, "rdp", 3389, 3389, ""]
DEBUG virtualbox_6_0:   - [1, "ssh", 2202, 22, "127.0.0.1"]
DEBUG virtualbox_6_0:   - [1, "winrm", 55985, 5985, "127.0.0.1"]
DEBUG virtualbox_6_0:   - [1, "winrm-ssl", 55986, 5986, "127.0.0.1"]
```
The above refers to the different ports forwarded to the machine. These can also be referred to as individual commands - `vagrant rdp` would use port 3389, however as I don't have a GUI for the machine that runs `VPC`, I can't use that. 
`vagrant ssh` would use port 2202 (on the host) to connect to the guest's port 22. However, the windows vagrant box I'm using doesn't have an ssh server setup by default.
`vagrant winrm` was the command I was having success with, which uses either port 55985 or 55986. As I didn't know which one was being used, I changed the host file to use `127.0.0.1:$portNo` for both. For 55985, I got an `SSLError`:
```
SSLError(\"bad handshake: Error([('SSL routines', 'ssl3_get_record', 'wrong version number')],)\",)
```
However, for 55986, I got the expected output!
```
$ cat play*/A*W*/hosts.tmp
127.0.0.1:55986
$ ansible all -i play*/A*W*/hosts.tmp -u vagrant -m win_ping
127.0.0.1 | SUCCESS => {
    "changed": false, 
    "ping": "pong"
}
```
Therefore, we can move all of the OSs running on `VPC` away from using the IP addresses given to them from vagrant.

**Comment by Willsparker** [comment]
An example of `vagrant port` output for a Windows machine is as follows: 
```
  3389 (guest) => 3389 (host)
    22 (guest) => 2202 (host)
  5985 (guest) => 55985 (host)
  5986 (guest) => 55986 (host)
```
Which refer to the ports I was talking about in the previous comment. The port we want to connect via ansible, in this case is `55986`. This will always be at the bottom of list, and the 4th string in the line. As that port can change, for example if there was another Windows VM taking up port `55986`, we can't just hardcode it- but we can hardcode the `grep` search for `5986`. Therefore, to get the port number we need, we could do the following: 
```
vagrantPort=$(vagrant port |  awk '/5986/ { print $4 }')
```

**Comment by Willsparker** [comment]
Interestingly, I've found that the winrm module in `startScriptWin.py` requires the port relating to `winrm`, not `winrm-ssl` - i.e. port `55985`, not `55986`. I did a quick test to determine what vagrant does in case of port collisions and the 5985 and 5986 ports on the guest, seem to be consistently one apart on the host machine:
```
==> adoptopenjdkW2012: Fixed port collision for 5985 => 55985. Now on port 2201.
==> adoptopenjdkW2012: Fixed port collision for 5986 => 55986. Now on port 2202.
```
Therefore I can just do an arithmetic expression to pass the port to number to `startScriptWin.py`.

**Comment by karianna** [comment]
@Willsparker - Can this be closed now?

**Comment by Willsparker** [comment]
I'm hesitant to close it right now as I haven't put in a fix for the second issue ( See the issue description ). For the minute I haven't seen that issue pop up again, however I am seeing other ones. I'll give it a couple more days of testing, and if it doesn't crop up, I'll close it :-)

**Comment by Willsparker** [comment]
Okay, it's been a fairly long time since I've seen the second issue of Windows VMs shutting down randomly. If it crops up again, I'll open another issue and link this one.
