### ISSUE TITLE
build-marist-rhel77-s390x-1 & 2 low on disk space

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-infrastructure#1511]
build-marist-rhel77-s390x-1 & 2 low on disk space

Failing builds: https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-linux-s390x-openj9/714/consoleFull

**Comment by Willsparker** [comment]
Both machines have 16GB free now, after deleting the `jdk15` folders (as we're building `jdk15u` now). Both machines are re-enabled. Closing now
