### ISSUE TITLE
Request for Deletion of Jenkins Jobs

### ISSUE THREAD

**Issue by adamfarley** [AdoptOpenJDK/openjdk-infrastructure#1518]
The following Jenkins Jobs were created by accident when a script failed to strip out the spaces before concatenating strings.

A PR to fix the "trimming" issue is currently awaiting review, but for now can the jobs with the spaces in their names be deleted, please? 

- Test_openjdk15_j9_special.functional_ s390x_linux_xl
- Test_openjdk15_j9_special.functional_ ppc64le_linux_xl
- Test_openjdk15_j9_sanity.openjdk_ s390x_linux_xl
- Test_openjdk15_j9_sanity.system_ ppc64le_linux_xl
- Test_openjdk15_j9_extended.system_ ppc64le_linux_xl
- Test_openjdk15_j9_sanity.openjdk_ ppc64le_linux_xl
- Test_openjdk15_j9_sanity.perf_ ppc64le_linux_xl
- Test_openjdk15_j9_sanity.system_ s390x_linux_xl
- Test_openjdk15_j9_extended.system_ s390x_linux_xl
- Test_openjdk15_j9_extended.perf_ ppc64le_linux_xl
- Test_openjdk15_j9_extended.perf_ s390x_linux_xl
- Test_openjdk15_j9_extended.openjdk_ ppc64le_linux_xl
- Test_openjdk15_j9_sanity.perf_ s390x_linux_xl
- Test_openjdk15_j9_extended.openjdk_ s390x_linux_xl

P.S. I've already created the jobs with the correct names (no spaces).

P.P.S. Please do not accidentally delete the jobs that have no spaces in their names.

**Comment by Willsparker** [comment]
I've gone through and disabled all the jobs with spaces in them. I don't have permissions to delete them unfortunately.

**Comment by adamfarley** [comment]
Thanks @Willsparker 
Will leave this open until someone with the right access can delete them.

**Comment by sxa** [comment]
Done (removed the directories from the jenkins server filesystem as that was easier than trying to find them all!)
