### ISSUE TITLE
Debian playbook requires updating

### ISSUE THREAD

**Issue by Haroon-Khel** [AdoptOpenJDK/openjdk-infrastructure#1528]
Per https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/1523 it was found that the Debian playbook kept crashing on Debian 8. 

Currently all I know is that the `gcc-7` and `g++-7` packages wont install. Will investigate further

**Comment by Willsparker** [comment]
This is specific to `arm32` - https://ci.adoptopenjdk.net/job/VagrantPlaybookCheck/OS=Debian8,label=vagrant/834/console 
x64 is able to install it okay :-) 
If we can't find any `apt` repos that have it, we could use the `gcc-7` role already in the Unix playbook, as there is an `armv7l` gcc750+ccache tarball at https://ci.adoptopenjdk.net/userContent/gcc/

**Comment by Haroon-Khel** [comment]
In https://ci.adoptopenjdk.net/job/QEMUPlaybookCheck/ARCHITECTURE=arm32,label=vagrant/88/console, `gcc7` and `g++7` are not installed via the repo, but through the `gcc_7` role. However the job failed at the build jdk stage

**Comment by Willsparker** [comment]
As a further to @Haroon-Khel 's above comment, based off ci.adoptopenjdk.net, I don't think we build a OpenJ9 JDK11 for ARM32/armv7l . With #1533 , We'll be able to test building a Hotspot JDK.
The gcc_7 role appeared to work in https://ci.adoptopenjdk.net/job/QEMUPlaybookCheck/ARCHITECTURE=arm32,label=vagrant/88/console , as it was able to build `Freetype`.

**Comment by sxa** [comment]
Correct - OpenJ9 does not have support for arm32/armv7l

**Comment by Willsparker** [comment]
As per https://ci.adoptopenjdk.net/job/QEMUPlaybookCheck/ARCHITECTURE=arm32,label=vagrant/92/
It's just Haroon's PR that will be needed to close this issue- However, I'm going to update #1533 so it will make sure that the build-variant isn't openj9 if building arm32.

**Comment by Haroon-Khel** [comment]
pr is in at https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/1535

**Comment by Willsparker** [comment]
With #1535 and #1533 , running one more ARM32 QPC run to make sure we're good. If it passes, we can close this.

https://ci.adoptopenjdk.net/job/QEMUPlaybookCheck/94/

**Comment by Willsparker** [comment]
https://ci.adoptopenjdk.net/job/QEMUPlaybookCheck/95/ 
Alright, the playbook passed which was the main point of this issue, and it's been able to compile freetype and is halfway through compiling the JDK, so as far as I'm concerned, this issue can be closed :-)
