### ISSUE TITLE
OpenJ9 boot JDKs should be updated

### ISSUE THREAD

**Issue by pshipton** [AdoptOpenJDK/openjdk-infrastructure#1531]
fyi https://github.com/eclipse/openj9/issues/2519

Now that eclipse/omr#2796 has been merged into OMR, we can gain some extra build performance by updating OpenJ9 boot JDKs to include that fix. It's most significant on Linux 390, but it wouldn't hurt to update all build platforms.

Suggest updating zlinux immediately to take advantage of the faster jvm, and then updating everything once the 0.9.0 release builds are available.

**Comment by karianna** [comment]
@sxa Can you confirm this was done?

**Comment by sxa** [comment]
It was not done - we're bootstrapping with a Hotspot VM
