### ISSUE TITLE
 build-marist-rhel77-s390x-1 is low on Disk Space

### ISSUE THREAD

**Issue by adamfarley** [AdoptOpenJDK/openjdk-infrastructure#1537]
Builds on this machine run out of disk space and fail.

Examples:

https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-linux-s390x-openj9-linuxXL/333/consoleFull
https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-linux-s390x-openj9/738/consoleFull

Please take a look and see what's taking up space.

**Comment by Willsparker** [comment]
Right, I've gone through and remove some unnecessary test folders, it has 4.7GB available now. Not sure if this is enough though - I'll check after the nightly builds have run.

**Comment by Willsparker** [comment]
https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-linux-s390x-hotspot/666/consoleFull
Seems to have worked! Machine still has 4.9GB free, so closing now.

**Comment by adamfarley** [comment]
Thanks @Willsparker 👍
