### ISSUE TITLE
Add Ubuntu18 support to aarch64 in qemuPlaybookCheck.sh

### ISSUE THREAD

**Issue by Haroon-Khel** [AdoptOpenJDK/openjdk-infrastructure#1538]
Using this issue to document my progress in adding ubuntu 18 on aarch64 support to the `qemuPlaybookCheck.sh` script

- [x] Create a ubuntu 18 aarch64 qemu disk image

- [x] Test ssh connectivity of disk image

- [x] Test the infra playbook on the disk image (In progress)

- [x] Add support for different OSs in `qemuPlaybookCheck.sh` (In progress)

- [x] Place disk image and associated volume files onto `infra-softlayer-ubuntu1804-x64-1`

- [x] Rename existing disk images to support `OS.ARCHITECTURE.dsk` format

- [x] Update QPC job in jenkins (In progress)

**Comment by sxa** [comment]
Do we also need any more info added to https://github.com/AdoptOpenJDK/openjdk-infrastructure/tree/master/docs on the setup of this VM?

**Comment by Haroon-Khel** [comment]
Yes. Once all of this is done, Ill add instructions to https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/master/docs/Setup-QEMU-Images.md (as well as instructions for setting up an arm32 qemu image which I was supposed to do last week)

**Comment by Haroon-Khel** [comment]
The pr to update the qpc is in, at https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/1541. Ive placed the images onto `infra-softlayer-ubuntu1804-x64-1`. Will run a test qpc job shortly

**Comment by Haroon-Khel** [comment]
Testing the existing disk images individually on `infra-softlayer-ubuntu1804-x64-1`

- [ ] UBUNTU18.AARCH64.dsk.xz

- [ ] DEBIAN10.AARCH64.dsk.xz

- [ ] UBUNTU18.S390X.dsk.xz

- [ ] UBUNTU18.PPC64LE.dsk.xz

- [ ] DEBIAN8.ARM32.dsk.xz

- [ ] DEBIAN11.RISCV.dsk.xz

**Comment by Haroon-Khel** [comment]
Qemu docs have been updated to include setup for debian8.arm32 and ubuntu18.arm64 images

**Comment by Haroon-Khel** [comment]
Closed as https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/1541 is merged
