### ISSUE TITLE
sign_build job cannot find temp jenkins .sh file on windows azure boxes

### ISSUE THREAD

**Issue by adamfarley** [AdoptOpenJDK/openjdk-infrastructure#1543]
This only seems to happen on Windows Azure boxes. Setup issue? 

Requesting attention from @gdams 

Error message:

```
[sign_build] $ sh -xe C:\Users\adoptopenjdk\AppData\Local\Temp\jenkins1497845439152064696.sh
The system cannot find the file specified
```

https://ci.adoptopenjdk.net/job/build-scripts/job/release/job/sign_build/11247/console

**Comment by gdams** [comment]
ahh yeah that makes sense, it tried to use the azure dynamic machine, I'll remove the labels for now to avoid this again

**Comment by adamfarley** [comment]
Thanks @gdams :)
