### ISSUE TITLE
winPB: Find a better way to manage MSVS checksums

### ISSUE THREAD

**Issue by Willsparker** [AdoptOpenJDK/openjdk-infrastructure#1546]
Ref: #1517  , #1545 

With both MSVS_2017 & 2019, we've removed the checksums as the installers are often updated, requiring a lot of 'checksum update' PRs, that can block `VPC` runs until the PRs are merged.
We really should have checksum checks whenever downloading anything from the internet, so a better solution needs to be found. 
At https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/1517#pullrequestreview-475402407 , @sxa suggested caching the installers somewhere so they aren't updated and the checksum stays the same.

**Comment by Willsparker** [comment]
https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/1572#issuecomment-704430037 

@sxa Would something such as
```
if credentials are present
  Retrieve MSVS_201* from the secrets repo / non public place
else
  Retrieve installer from regular place w/o checksum
```
That way other (non-adoptopenjdk) people can still use the playbooks, but when setting up machines, we can ensure the installations okay?

**Comment by sxa** [comment]
I'd say it's not ideal but better than not having a fallback.
