### ISSUE TITLE
build-scaleway-ubuntu1604-armv7-1 offline ?

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-infrastructure#1555]
build-scaleway-ubuntu1604-armv7-1 Jenkins agent fails to start...?
not sure why

**Comment by andrew-m-leonard** [comment]
build-scaleway-ubuntu1604-armv7-2 offline as well

**Comment by aahlenst** [comment]
We've been informed some time ago that Scaleway is going to discontinue their ARM offerings. Maybe they've pulled the plug.

**Comment by Willsparker** [comment]
Ref: https://adoptopenjdk.slack.com/archives/C09NW3L2J/p1600679833003200

**Comment by Willsparker** [comment]
I sort of assume there's nothing that can be done about this yet, until we find a different provider for armv7 machines?

**Comment by karianna** [comment]
This host is online according to the Scaleway console but we're getting ssh connection errors when Jenkins tries to connect

**Comment by karianna** [comment]
Manual SSH hangs as well.  REstarting host one from the console

**Comment by karianna** [comment]
Agent is back up.

**Comment by aahlenst** [comment]
FYI: I've removed the build label from my test machines because they've never been properly vetted for usage as build machines.
