### ISSUE TITLE
Windows installer failing: SignTool Error: File not found: C:\Users\jenkins\windows.p12

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-infrastructure#1556]
https://ci.adoptopenjdk.net/job/build-scripts/job/release/job/sign_build/11503/console
```
find: 'basename' terminated by signal 13
.... lots of these...
find: 'basename' terminated by signal 13
Signing Windows release
Signing ./bin/fixpath.exe
SignTool Error: File not found: C:\Users\jenkins\windows.p12

RETRYWARNING: Failed to sign ./bin/fixpath.exe at 00:05:34: Possible timestamp server error - RC 0 ... Retrying in 10 seconds
SignTool Error: File not found: C:\Users\jenkins\windows.p12
```

**Comment by andrew-m-leonard** [comment]
Seems an issue on build-azure-win2012r2-x64-1 marked offline

**Comment by Willsparker** [comment]
As suggested by @gdams [on slack](https://adoptopenjdk.slack.com/archives/C598A7EMQ/p1600768585004200?thread_ts=1600662156.001200&cid=C598A7EMQ) , we're going to move the `windows.p12` cert over to `C:\openjdk`, as often there are differences between machines in that sometimes the Jenkins user is at `C:/users/jenkins.<Something_random>`. Hopefully this will stop these errors

**Comment by Willsparker** [comment]
With the above build PR being merged, this should hopefully be fixed. [This](https://ci.adoptopenjdk.net/job/build-scripts/job/release/job/create_installer_windows/7968/console) installer run started about 10 minutes after the PR was merged and it looks okay. I'll wait until the nightlies run before I close this issue though

**Comment by Willsparker** [comment]
Looks okay from last night, closing
