### ISSUE TITLE
winPB: Update location of windows.p12 in CodesignCert role

### ISSUE THREAD

**Issue by Willsparker** [AdoptOpenJDK/openjdk-infrastructure#1558]
Ref: https://github.com/AdoptOpenJDK/openjdk-build/pull/2092 , #1556 

Currently looking into placing the windows.p12 cert into `C:/openjdk/` as opposed to `C:/users/jenkins/`, however the link to get windows.p12 in the CodesignCert (ccert) role needs to be updated as it is no longer in the adoptopenjdk/openjdk-installer repo, regardless of where we intend to put it.

The windows.p12 file is currently stored in the `secrets` repo. We could either look to store it elsewhere, possibly with the `Vendor_Files`, or use `dotgpg` to access the `secrets` repo, either way the ccert role needs to be updated to have those changes.

**Comment by Willsparker** [comment]
I think the best thing would be to store it with the Vendor Files, as they'd be required to properly setup a Windows machine anyway. We could put the Vendor Files as a `.tar.gz` archive in the private secrets repo, therefore Its available to the people that are going to be setting up Windows Machines for the machine farm, but not open open. @gdams thoughts?

**Comment by aahlenst** [comment]
Does it have to be a compressed tarball? Why not the individual files?

**Comment by gdams** [comment]
yeah @Willsparker I've got a plan, let me try some hacking around

**Comment by Willsparker** [comment]
> Does it have to be a compressed tarball? Why not the individual files?

I just thought it'd save on space :-)

**Comment by aahlenst** [comment]
> I just thought it'd save on space :-)

If the private secrets repo is in git, the tarball is rather going to waste space. Except git got better at managing those.

**Comment by Willsparker** [comment]
Oh okay! Maybe not a tarball then :sweat_smile:  Either way, individual files or not, IMO they should be stored in the secrets repo

**Comment by Willsparker** [comment]
Ref: #1560
