### ISSUE TITLE
Please add me to this organisation/team so that I can start contributing

### ISSUE THREAD

**Issue by geraintwjones** [AdoptOpenJDK/openjdk-infrastructure#156]
I'm a member of the IBM Runtimes Infrastructure team in Hursley, and would like to contribute to AdoptOpenJDK.

**Comment by gdams** [comment]
LGTM, could I have one other approval from @AdoptOpenJDK/infrastructure

**Comment by bblondin** [comment]
I approve

**Comment by sxa555** [comment]
I'll approve too since he sits behind me and I'm happy to keep an eye on him ;-)

**Comment by geraintwjones** [comment]
Thanks @sxa555 :-)

**Comment by gdams** [comment]
Onboarding complete! Welcome to the team @geraintwjones
