### ISSUE TITLE
mac: Update JDK versions running Jenkins

### ISSUE THREAD

**Issue by Willsparker** [AdoptOpenJDK/openjdk-infrastructure#1567]
Ref: https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1565#issuecomment-698900558

Old JDK8 versions running the Jenkins agent can cause issues with Jenkins (see the issue above).

The following machines need updating (the current JDK8 versions that are running the agent can be seen in the linked comment)

- [ ] test-macincloud-macos1010-x64-1
- [ ] test-macincloud-macos1010-x64-2
- [x] test-macincloud-macos1012-x64-1
- [x] test-macincloud-macos1013-x64-1
- [x] test-macincloud-macos1013-x64-2
- [x] test-macincloud-macos1014-x64-1
- [x] test-macincloud-macos1014-x64-2
- [ ] test-macstadium-macos11-arm64-1 
- [ ] test-macstadium-macos11-arm64-2

**Comment by Willsparker** [comment]
Just a thought- this could be added into the `adoptopenjdk_install` playbook; a task to find the latest version of JDK X, compare to the one thats on it, if the version is lower (or the old version can't be found), install the latest version, remove the old JDK X (if applicable).

**Comment by aahlenst** [comment]
What about using our [Homebrew tap](https://github.com/adoptopenjdk/homebrew-openjdk)? Would make updating easier, too.

**Comment by Willsparker** [comment]
I think my only concern with that would be that the role would have to be mac specific, whereas updating the `adoptopenjdk_install` role would encompass the linux distros too

**Comment by Willsparker** [comment]
@gdams (or @Haroon-Khel or anyone with access to the macOS machines) , could you run the 'Superuser' role on the following machines, please?:
```
test-macincloud-macos1012-x64-1   92.63.141.139
test-macincloud-macos1013-x64-1   46.20.235.28
test-macincloud-macos1013-x64-2   92.63.134.23
test-macincloud-macos1014-x64-1   87.237.62.57
test-macincloud-macos1014-x64-2   92.63.134.40
test-macincloud-macos1014-x64-3   74.80.249.207
```

**Comment by gdams** [comment]
@Willsparker done

**Comment by Willsparker** [comment]
Thanks :-)

**Comment by Willsparker** [comment]
Alright, all the x86_64 ones are updated (except macos10 ones, that cant be updated due to the following error message)
```
test-macincloud-macos1010-x64-1:~ admin$ brew upgrade adoptopenjdk8
Error: /usr/local/Cellar is not writable. You should change the
ownership and permissions of /usr/local/Cellar back to your
user account:
  sudo chown -R $(whoami) /usr/local/Cellar
Error: Cannot write to /usr/local/Cellar
```

**Comment by Willsparker** [comment]
The 2 macos10 machines weren't able to update Java using Homebrew, so I had to do it manually and put it into `/Library/Java/JavaVirtualMachines/jdk8u265-b01`. Restarted the nodes and they're running the Jenkins agent on the later version.

The '2' arm machines (that are actually one but somehow have 2 agents running from it), are already running jdk`1.8.0_265-b01`.

That should be all of them :+1:
