### ISSUE TITLE
Automate SSL certificate renewal on ci.adoptopenjdk.net

### ISSUE THREAD

**Issue by aahlenst** [AdoptOpenJDK/openjdk-infrastructure#1569]

**Comment by Willsparker** [comment]
Presumably, this would be a case of using Nagios to monitor if the cert has expired (#1568 ), and if so, run a script containing the instructions that are given on login to the `ci.adoptopenjdk.net` machine :
```
cd /opt/letsencrypt/
./letsencrypt-auto --config /etc/letsencrypt/configs/ci.adoptopenjdk.net.conf certonly
service nginx restart
```

**Comment by aahlenst** [comment]
I know nothing about the Jenkins config. If indeed nginx is in front of Jenkins, I'd use certbot and let it handle everything. You can call certbot regularly with cron and it will automatically update the certificates if required. I can send you my Ansible role I use at work.

**Comment by Willsparker** [comment]
I've managed to get a working example of a service handler working on the 2 VMs that I have to simulate a Nagios instance. To do this I setup a dummy task in the server config (`/usr/local/nagios/etc/servers/XXX.cfg`)
```
define service {
      host_name			      ubuntu_host
      service_description             failing_check
      check_command                   check_by_ssh! exit 1
      ...
      event_handler                   test_handler
}
```
Fairly self explanatory, but it runs `exit 1` on the host via `ssh`. The `event_handler` field handles what happens as a state-change. To simulate these, I would just use the Nagios interface to set the "state" manually. 

The `event_handler` field calls the `test_handler` command, which is defined in `/usr/local/nagios/etc/objects/commands.cfg`.
```
define command {
  command_name     test_handler
  command_line     $USER1$/check_by_ssh -t 360 -H $HOSTADDRESS$ -C '/usr/lib/nagios/plugins/test_script.sh $SERVICESTATE$'
}
```
This is defined like any other command, but it uses the `check_by_ssh` command to start the `test_script.sh` on the host machine. `$USER1$` is the path to the `check_by_ssh` executable on the Nagios server. 
In this example, all `test_script.sh` does is print the `$SERVICESTATE$` (i.e. 'OK', 'WARNING', 'UNKNOWN', 'CRITICAL') to a file located at: `/home/nagios/debug.log`, which is located on the host. 
When implemented, the actual script will run the commands listed above:
```
cd /opt/letsencrypt/
./letsencrypt-auto --config /etc/letsencrypt/configs/ci.adoptopenjdk.net.conf certonly
service nginx restart
```
Note: To get the `check_by_ssh` command working at all, the Nagios user on the Host machine needs to have the ssh-key for the Nagios user on the server-machine, in the `authorized_keys` file. @karianna I'm slightly concern this would be a security issue (as it's effectively a single-point of failure). All of the `Nagios` users on the host machines will have limited permissions, but even so.

**Comment by aahlenst** [comment]
Why don't you install a cron job on the respective machines that invoke certbot or whatever letsencrypt-auto does? Seems significantly simpler and does not require ssh'ing into the machine.

**Comment by Willsparker** [comment]
I'm certainly not opposed to that - I just haven't used Cron before :grin: It also made sense to me to link how #1568 was implemented, to this. However, If we do it with a Cron Job (and based on the list of things you suggested we monitor in #1229), we wouldn't have to use the `check_by_ssh` plugin at all, which stops my single-point-of-failure concern too :-) 

I'll do some testing and put my findings here

**Comment by Willsparker** [comment]
Okay, yep, looking at it, cronjobs seem easy to implement. The `letsencrypt-auto` command renews it for 90 days, I was thinking we run those commands every 80 days(ish).
Cronjobs don't really allow for `every X amount of days`, so we could just setup the cron job to run everyday, and check it's been 80 days since the last cert renewal in the script ( probably using the `check_ssl_cert` command to find the expiration date)

**Comment by aahlenst** [comment]
> The letsencrypt-auto command renews it for 90 days, I was thinking we run those commands every 80 days(ish).

Run it every week by putting it in `/etc/cron.weekly`. If there's no cert to renew, it will skip it.

**Comment by Willsparker** [comment]
If that's the case, isn't there a chance of there being (up to) 6 days with no certificate renewal, if we checked weekly?

**Comment by aahlenst** [comment]
Certbot usually renews the certificates well in advance. So the certificate should be renewed before Nagios complains. I haven't seen a single warning since we deployed certbot at work.

**Comment by Willsparker** [comment]
Hmm, okay- I'll look at `certbot` in that case, I was just going to put 
```
cd /opt/letsencrypt/
./letsencrypt-auto --config /etc/letsencrypt/configs/ci.adoptopenjdk.net.conf certonly
service nginx restart
```
in a script and run it w/ a cronjob

**Comment by aahlenst** [comment]
It looks like `letsencrypt-auto` should do more or less the same that certbot does. Do you know where `letsencrypt-auto` comes from?

**Comment by Willsparker** [comment]
Not specifically, it's part of the login message when you ssh to the `ci.adoptopenjdk.net` server:
```
TO RENEW THE HTTPS CERT:

cd /opt/letsencrypt/
./letsencrypt-auto --config /etc/letsencrypt/configs/ci.adoptopenjdk.net.conf certonly
service nginx restart

```

**Comment by aahlenst** [comment]
It could be https://github.com/certbot/certbot/blob/master/letsencrypt-auto? So you could leave it in place and maybe we switch to an OS package after upgrading Ubuntu.

**Comment by Willsparker** [comment]
For now, @aahlenst suggested we just put `letsencrypt-auto renew --renew-hook "systemctl reload nginx"` into a file in `/etc/cron.weekly/`. From what I can gather, that will renew all of the certificates on the system automatically, when they expire in <30 days. The `--renew-hook` argument is where the user can specify what's run after a renewal happens. If I'm not missing anything, is everyone happy with that solution?

**Comment by aahlenst** [comment]
No objections from my side.

**Comment by Willsparker** [comment]
Cron job has been put in, I'll keep an eye to make sure the SSL cert is actually renewed when it gets close, via Nagios. Closing issue
