### ISSUE TITLE
zLinux builds stalled due to build-marist-rhel77-s390x-1 offline

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-infrastructure#1576]
![image](https://user-images.githubusercontent.com/31470007/94538588-18a9b300-023c-11eb-9782-66d33ec5d9b8.png)

**Comment by andrew-m-leonard** [comment]
@Haroon-Khel could you take a look at this machine please?

**Comment by Willsparker** [comment]
ref: #1554

**Comment by Haroon-Khel** [comment]
@andrew-m-leonard If this was caused by low disk space, theres now 51G free on the machine. Could you relaunch the agent please? I dont seem to have the required permissions

**Comment by karianna** [comment]
I tried via Jenkins and it didn't like it.

**Comment by Haroon-Khel** [comment]
@karianna Could you grant my user the required perms to be able to view https://ci.adoptopenjdk.net/computer/build-marist-rhel77-s390x-1/log. I currently see the following message at that link

```
Access Denied
Haroon-Khel is missing a permission, one of Agent/ExtendedRead, Agent/Connect is required
```

**Comment by karianna** [comment]
You were missing from the Infra team - try again now (you may need to log out/in to jenkins)

**Comment by karianna** [comment]
PS: That log is only showing the latest from Jan 2020, so nothing useful there :-(

**Comment by sxa** [comment]
Node is back up with an `X` suffix. Occasionally jenkins agent definitions get "confused" and the logs get stuck and don't update. This seems to have happened in this case.

The underlying issue preventing it from starting was that the `authorized_keys` file had been blanked as a result of an update (probably from Bastillion) happening while the disk was full. I have copied the correct keys across which now allows jenkins to connect and start under the new agent definition.
