### ISSUE TITLE
Need a 2nd create_installer_linux node for redundency

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-infrastructure#1577]
build-scaleway-ubuntu1604-x64-1 is the only node for create_installer_linux
if that has an issue, eg.Agent goes offline, disk issue, or whatever, then the builds hang...

Please can we have a 2nd one for redundency?

**Comment by sxa** [comment]
@Haroon-Khel As requested, a new Ubuntu16.04 is now available if you want to progress this: Your key can access `root@160.153.254.64`

**Comment by Haroon-Khel** [comment]
I have run the playbook on the machine. Ive given it the name build-godaddy-ubuntu1604-x64-1, as its original hostname was just its ipadress. Am running a build and test on the machine now.

**Comment by sxa** [comment]
That's a bit odd - it shouldn't have just been the IP address unless you'd run the playbook with the IP in the hosts file previously

**Comment by Haroon-Khel** [comment]
[build-godaddy-ubuntu1604-x64-1](https://ci.adoptopenjdk.net/computer/build-godaddy-ubuntu1604-x64-1/) is now in jenkins. For the sake of testing the create_installer_linux job, I created a temporary gpg key on the machine. The existing installer machine, build-scaleway-ubuntu1604-x64-1, has an adopt key on the machine. Is this a unique key that needs to be on all installer machines to sign rpm and deb packages? Or should I just create a new key for build-godaddy-ubuntu1604-x64-1?

Standalone create installer linux job which has passed on build-godaddy-ubuntu1604-x64-1
https://ci.adoptopenjdk.net/job/build-scripts/job/release/job/standalone_create_installer_linux/121/console

**Comment by aahlenst** [comment]
It needs to be the same key everywhere. And it should not change.

**Comment by Haroon-Khel** [comment]
The new key is now on the machine. Ive added the fpm and ubuntu labels, so the machine should get used by the create_installer_linux job. Lets see if it survives the nightlies

**Comment by sxa** [comment]
Doesn't look like that's the right set of tags as the job is still only trying to run on https://ci.adoptopenjdk.net/computer/build-scaleway-ubuntu1604-x64-1/:

![image](https://user-images.githubusercontent.com/6487691/103462819-c3d87580-4d1f-11eb-8eb9-366acf59a7a4.png)

**Comment by sxa** [comment]
Closing this since it's part of https://github.com/AdoptOpenJDK/openjdk-build/issues/1044
