### ISSUE TITLE
CI checks are failing - period.

### ISSUE THREAD

**Issue by aixtools** [AdoptOpenJDK/openjdk-infrastructure#1584]
It seems, regardless of what is submitted, the CI checks are going to fail.

May I make, what I hope is a simple request - rollback the CI check additions until the mainstream will pass the new tests.

**Comment by karianna** [comment]
Is there a specific issue you're encountering?

**Comment by aixtools** [comment]
I added a new framework for a new version of playbook for AIX and I get 'unrelated' CI check errors (that are probably valid). Makes it hard to trust the CI checks for what you are (that is I am) working on.

**Comment by aixtools** [comment]
Sent a request for an invite to Slack.

**Comment by aahlenst** [comment]
In https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/1583, ansible_lint complains about duplicated YAML keys. And there are duplicated YAML keys:

```
- hosts: all
  roles:
  - role: verify
    role: users
    role: fs
    role: oss
```

You probably wanted to write:

```
- hosts: all
  roles:
    - verify
    - users
    - fs
    - oss
```

**Comment by gdams** [comment]
closing, the CI checks now have 0 warnings/errors
