### ISSUE TITLE
build-osuosl-aix71-ppc64-2 low on disk space 1.94Gb free

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-infrastructure#1589]
Build failures likely due to low disk space: https://ci.adoptopenjdk.net/view/Failed%20Builds/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-aix-ppc64-hotspot/714/console

**Comment by sxa** [comment]
There was a fair bit of crud left from some tests I was doing which I've now cleared up. Hopefully this will be OK going forward (although I still have some optimisations I'd like to put in place on these machines)
