### ISSUE TITLE
low disk space on test-macincloud-macos1014-x64-1

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-infrastructure#1595]
Node test-macincloud-macos1014-x64-1 agent has failed, and cannot be re-launched
https://ci.adoptopenjdk.net/computer/test-macincloud-macos1014-x64-1/

**Comment by Haroon-Khel** [comment]
Im unable to ping the machine, and I get this when trying to ssh into it
```
Haroons-MacBook-Pro:~ haroonkhel$ ssh admin@87.237.62.57
ssh: connect to host 87.237.62.57 port 22: Network is unreachable
```

**Comment by Willsparker** [comment]
Looks like the machine is pingable and `ssh`able again. It seems to be connected to Jenkins too, just low on disk-space

**Comment by gdams** [comment]
I've migrated all machines to macstadium + given them more disk space
