### ISSUE TITLE
Get a Tier 1 x86 sponsor

### ISSUE THREAD

**Issue by gdams** [AdoptOpenJDK/openjdk-infrastructure#16]
Currently we are hosting a lot of our x86 hardware with packet.net

I want to move away from this as I want to free up our usage limit so that we can provision more arm machines for testing

FYI @vielmetti

**Comment by gdams** [comment]
CloudCone call went well this morning, will update with more progress as it comes in

**Comment by vielmetti** [comment]
Good to hear it @gdams looking forward to what you sort out.

**Comment by sxa555** [comment]
@gdams Can this be closed now - are CloudCone fulfilling this requirement?

**Comment by karianna** [comment]
I'm closing this for now as we have OK coverage and MSFT is providing a bunch more.

Challenge is that the LJC is paying for several hosts, which is something we'd like to minimise going forwards.  I'll raise a separate TSC issue for that.
