### ISSUE TITLE
test-aws-win2019-x64-2 OutOfMemory

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-infrastructure#1602]
This machine seems to fail with OOM errors: 
https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_extended.system_x86-32_windows/10/console

NOTE: I have marked it offline

**Comment by sxa** [comment]
[test-aws-win2019-x64-2](https://ci.adoptopenjdk.net/computer/test-aws-win2019-x64-2/) is an AWS `t3a.xlarge` with 16Gb of RAM and 25Gb including virtual memory and is currently showing 6Gb free physical RAM so it is a higher spec than most of our other systems. There is, however, a lot (I'm guessing about 40 or so) `OpenJDK Platform binary` processes on the machine using about 100MB each which I'm clearing up as they're chewing resources unnecessarily and then I'll ring it back online.

Please reopen if this recurs

FYI @smlambert in case there's a cleanup issue

**Comment by smlambert** [comment]
Did you happen to keep the list of running processes?  (were they test processes, jdi tests?)

related: https://github.com/AdoptOpenJDK/TKG/issues/45
