### ISSUE TITLE
cmake not working for JDK11 on AIX

### ISSUE THREAD

**Issue by sxa** [AdoptOpenJDK/openjdk-infrastructure#1603]
Looks like our cmake isn't working properly on the AIX build machines used for OpenJ9 - presumably a libstdc++ mismatch. We should validate whether the cmake binary and stdc++ came from the same up-to-date source.

Ref: https://ci.adoptopenjdk.net/view/Failed%20Builds/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-aix-ppc64-openj9/782/console

```0:43:14  gmake[3]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
00:43:15  Could not load program cmake:
00:43:15  Symbol resolution failed for cmake because:
00:43:15  	Symbol _ZTINSt6thread6_StateE (number 358) is not exported from dependent
00:43:15  	  module /opt/freeware/lib/libstdc++.a[libstdc++.so.6].
00:43:15  	Symbol _ZTVNSt6thread6_StateE (number 359) is not exported from dependent
00:43:15  	  module /opt/freeware/lib/libstdc++.a[libstdc++.so.6].
00:43:15  	Symbol _ZNSt6thread4joinEv (number 370) is not exported from dependent
00:43:15  	  module /opt/freeware/lib/libstdc++.a[libstdc++.so.6].
00:43:15  	Symbol _ZNSt18condition_variableD1Ev (number 387) is not exported from dependent
00:43:15  	  module /opt/freeware/lib/libstdc++.a[libstdc++.so.6].
00:43:15  	Symbol _ZNSt18condition_variableC1Ev (number 388) is not exported from dependent
00:43:15  	  module /opt/freeware/lib/libstdc++.a[libstdc++.so.6].
00:43:15  	Symbol _ZNSt18condition_variable4waitERSt11unique_lockISt5mutexE (number 434) is not exported from dependent
```
FYI @Haroon-Khel @aixtools (This isn't a job which is running on the OSUOSL AIX machines though)

**Comment by Haroon-Khel** [comment]
You were correct in the slack thread. 

`/opt/freeware/lib/libstdc++.a` points to `/opt/freeware/lib/gcc/powerpc-ibm-aix7.1.0.0/8.3.0/libstdc++.a`, while the `libstdc++.a` that `cmake` depends on is at `/opt/freeware/lib/gcc/powerpc-ibm-aix7.1.0.0/8.3.0/pthread/libstdc++.a`

Ive temporarily made `/opt/freeware/lib/libstdc++.a` point to the correct dependancy to see if this fixes the issue (and at the same time to see what else breaks due to this link change)

The job is rerunning at https://ci.adoptopenjdk.net/view/Failed%20Builds/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-aix-ppc64-openj9/786/console

**Comment by sxa** [comment]
Looks primising :-)

**Comment by Haroon-Khel** [comment]
The weekend's jobs ran without error, all on test-ibm-aix71-ppc64-1 (the problem machine). And it seems that the link change hasnt caused anything to break

**Comment by aixtools** [comment]
FYI: I'll add cmake to the list of OSS I need to have 'around' in the new environment I am building and @Haroon-Khel is testing - as we move forward.

**Comment by Haroon-Khel** [comment]
@sxa Can we close this? Or are we going to investigate further into why the wrong `libstdc++.a` dependancy was loaded?

**Comment by aixtools** [comment]
FYI: I am currently working a new package of cmake - 3.18.4.

**Comment by aixtools** [comment]
Note: with regard to libc++.a (not libstdc++.a) the xlC-v16 package includes a new runtime fileset: `libc++.rte`

On the AIX 7.2 systems: the RPM libstdc++ package is: `libstdc++-8.3.0-1.ppc`

On `build`-AIX71: the packages installed are:
```
libstdc++-4.8.5-1.ppc
libstdc++-devel-4.8.5-1.ppc
```

On test-AIX71 (ojdk05):
`libstdc++-8.3.0-2.ppc`

In other words: different everywhere!

**Comment by aixtools** [comment]
re: cmake:

On build-AIX71: cmake is not installed
On test-AIX71: cmake-3.7.2-1.ppc
On test-AIX72: cmake-3.7.2-1.ppc

So, on ojdk01 and ojdk02: not even installed, on the later systems (ojdk03, ojdk04 and ojdk05) it is installed and at the same level.

**NOTE:** This issue refers to something not running on OSUOSL systems - so, purely for information. This will need to be resolved by someone who can actually access those systems - I hope the info helps resolve the issue **there**

**Comment by andrew-m-leonard** [comment]
@sxa @Haroon-Khel do we know how to fix this now?

**Comment by Haroon-Khel** [comment]
@andrew-m-leonard to reiterate my comments made on https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1952

```
p159a01:/ # ldd `which cmake`
/opt/freeware/bin/cmake needs:
         /usr/lib/libc.a(shr_64.o)
         /usr/lib/libpthreads.a(shr_xpg5_64.o)
         /opt/freeware/lib/pthread/ppc64/libstdc++.a(libstdc++.so.6)
```
Ive temporarily made `/opt/freeware/lib/libstdc++.a` to point to `/opt/freeware/lib/pthread/ppc64/libstdc++.a` to see if this fixes the problem (and to see what else breaks!)
Rerunning at https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-aix-ppc64-openj9/922/console

**Comment by Haroon-Khel** [comment]
Failed with 
```
12:30:25  [ 23%] Built target jvmti_test_src
12:30:25  [ 23%] Built target j9util
12:30:25  gmake[4]: *** [Makefile:130: all] Error 2
12:30:25  gmake[3]: *** [/home/jenkins/workspace/build-scripts/jobs/jdk11u/jdk11u-aix-ppc64-openj9/workspace/build/src/closed/OpenJ9.gmk:484: build-j9] Error 2
12:30:25  gmake[2]: *** [/home/jenkins/workspace/build-scripts/jobs/jdk11u/jdk11u-aix-ppc64-openj9/workspace/build/src/closed/custom/Main.gmk:50: j9vm-build] Error 2
12:30:25  
12:30:25  ERROR: Build failed for targets 'product-images legacy-jre-image test-image debug-image' in configuration 'aix-ppc64-normal-server-release' (exit code 2) 
12:30:25  Stopping sjavac server
```
It made it further than before, but still failed
@andrew-m-leonard Is this a familiar failure? Or do you think its related to the symlink change ive just made?

**Comment by andrew-m-leonard** [comment]
@Haroon-Khel the error a bit further up:
```
12:30:13  ar: 0707-108 File libjvm.so is not an archive file.
12:30:13  gmake[6]: *** [runtime/redirector/CMakeFiles/jvm_redirect.dir/build.make:114: runtime/redirector/libjvm.so] Error 1
12:30:13  gmake[6]: *** Deleting file 'runtime/redirector/libjvm.so'
```
wondering if the workspace wasn't clean, just trying it again: https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-aix-ppc64-openj9/923/

**Comment by Haroon-Khel** [comment]
Same error. Ill clean the workspace manually and try one more time

**Comment by sxa** [comment]
Resolved by https://github.com/AdoptOpenJDK/openjdk-build/pull/2489 although https://github.com/AdoptOpenJDK/openjdk-build/issues/2492 is still outstanding.
