### ISSUE TITLE
SXA-processCheck job isn't hitting all machines

### ISSUE THREAD

**Issue by sxa** [AdoptOpenJDK/openjdk-infrastructure#1609]
At one point the [SXA-processCheck job](https://ci.adoptopenjdk.net/view/Tooling/job/SXA-processCheck/) was configured to run on every machine with the [ci.role.test label](https://ci.adoptopenjdk.net/label/ci.role.test/). Despite that, it didn't seem to be taking effect on [test-marist-ubuntu1604-s390x-3](https://ci.adoptopenjdk.net/computer/test-marist-ubuntu1604-s390x-3) as I've just killed off a job from August 11th after the machine was hitting a claimed memory issue (which seems unrelated to the issue I was debugging) but we need to understand why it's not pucking up the machine. It may be a simple matter of it being unavailable at the time the job last ran

**Comment by sxa** [comment]
Something odd going on here since it looks like it [had ran on it](https://ci.adoptopenjdk.net/view/Tooling/job/SXA-processCheck/label=test-marist-ubuntu1604-s390x-3/) but didn't pick up the process I just killed. Will look tomorrow when brain is engaged again :_)
```
jenkins@adoptopenjdk01:~$ ps -ef | grep 24636
jenkins  24636     1 85 Aug11 ?        49-10:26:44 /home/jenkins/workspace/Test_openjdk15_j9_sanity.openjdk_s390x_linux/openjdkbinary/j2sdk-image/bin/keytool -J-Duser.language=en -J-Duser.country=US -genkey -keyalg rsa -alias JavaTest -keystore keystore.jks -keypass changeit -dname cn=sample -storepass changeit
jenkins  31053 30868  0 19:11 pts/0    00:00:00 grep --color=auto 24636
jenkins@adoptopenjdk01:~$ kill 24636
jenkins@adoptopenjdk01:~$ ps -ef | grep 24636
jenkins  31132 30868  0 19:12 pts/0    00:00:00 grep --color=auto 24636
jenkins@adoptopenjdk01:~$ ifconfig eth0
eth0      Link encap:Ethernet  HWaddr fa:16:3e:51:99:da  
          inet addr:148.100.113.30  Bcast:148.100.113.255  Mask:255.255.255.0
          inet6 addr: 2620:91:0:656:f816:3eff:fe51:99da/64 Scope:Global
          inet6 addr: fe80::f816:3eff:fe51:99da/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:424923185 errors:0 dropped:0 overruns:0 frame:0
          TX packets:182299531 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:607905494727 (607.9 GB)  TX bytes:129433496435 (129.4 GB)

jenkins@adoptopenjdk01:~$ 
```

**Comment by karianna** [comment]
Should this check be integrated into Nagios?

**Comment by sxa** [comment]
Going forward possibly

**Comment by sxa** [comment]
Actually probably not as we don't want any such kiiller to run while a job is executing on jenkins which is why I implemented this way as opposed to a cron job or something else - it uses the executor to do the cleanup so nothing else will be running at the tine. We could kill "old" processes with something like nagios but this seems simpler and safer.

**Comment by sxa** [comment]
All systems seem to be getting picked up now so I'm closing this. Suspect it was a glitch caused by a machine being off at the time it last ran
