### ISSUE TITLE
Standardise hostnames on our machines

### ISSUE THREAD

**Issue by sxa555** [AdoptOpenJDK/openjdk-infrastructure#162]
Follow-on to https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/131 - we should define a standard machine naming convention. Currently most are of this format:

`<usage>-<provider>-<arch>-<os>-<sequence>`

Although some are missing the architecture - mostly windows/macos boxes where they're all x64. We do also have an issue where some of our tests don't work properly when there is a `.` in the machine name (for example those with names includeding `ubuntu-16.04`) and in those cases we have replaced the `.` with a `-` on the machine itself.

This work item will discuss that convention and it is what's used in jenkins, nagios etc and listed on https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/master/infrastructure.md, and whether the hostnames on the machines we get from the providers should be changed to match these (possibly with the `.` to `-` translation ... Or whether we should just avoid having `.` in the names at all. At the moment some of the hostnames on the machines don't match what we call them, which is inconvenient when you're logged into multiple machines

**Comment by bblondin** [comment]
yes I agree the ```.``` periods do not translate. using ```-``` dashes is better
Issue #165 (Set system hostname to match jenkins) is related to this

**Comment by judovana** [comment]
I would wote for . replaced by _ instead  by -.
reason is - ubuntu-16.04 would change to ubuntu-16-04 where the . had different meaning then have new dash.

Generality strict delimiter of various parts is currently dash. So it should not be used in sub parts.

Also, what is <usage>  and <prvoder> .. well and <sequence> ... for?Well For us newbies, can you elaborate more on individual parts of <usage>-<provider>-<arch>-<os>-<sequence>? 
Shouldn't be some of those handled elsewhere?  Ideally all except <arch>-<os> ?

**Comment by sxa555** [comment]
@judovana I'm not sure what you mean by the "what is and ... well and ... for?" question. Or "individual parts of ----?"

**Comment by judovana** [comment]
Ha. Markdown had eaten  the tags. Sorry
Also, what is `<usage>`  and `<prvoder>` .. well and `<sequence>` ... for?Well For us newbies, can you elaborate more on individual parts of ` <usage>-<provider>-<arch>-<os>-<sequence>`? 
Shouldn't be some of those handled elsewhere? From those probably only  `<arch>-<os>`  are celar?

**Comment by sxa555** [comment]
Ah :-D `<usage>` is mostly one of `build` `test` `jck`, provider is whichever cloud provider the machine comes from so `softlayer` `marist` `joyent` etc. `<sequence` is just a number to distinguish them if we have more than one of the same machine so `-1` `-2` etc. The link in the initial post has all the machines so has various examples.

**Comment by judovana** [comment]
Thank you. My nit would be that usage should be handled differently. Machine *should* (== one wish) transparent. Provider is interesting, and sequence made sense. TY!

**Comment by gdams** [comment]
closing this as we have now got our inventory.yml sorting this out. I will create new issues to bring any old machines up to date with the new hostname schema
