### ISSUE TITLE
build-marist-ubuntu1604-s390x-2 offline : connection problem

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-infrastructure#1621]
https://ci.adoptopenjdk.net/computer/build-marist-ubuntu1604-s390x-2/log

**Comment by Haroon-Khel** [comment]
Cleared out some directories. Theres 47g free on the machine now

**Comment by sxa** [comment]
Machine no longer exists - we do not build on Ubuntu. The jenkins definitions appear to be lagging behind reality which I have resolved via the above PR
