### ISSUE TITLE
GLIBC_2.14 not found running bootjdk-15 on Azure build agents

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-infrastructure#1635]
https://ci.adoptopenjdk.net/view/Failed%20Builds/job/build-scripts/job/jobs/job/jdk/job/jdk-linux-x64-hotspot/295/console
```
04:39:42  Required boot JDK version: 15
04:39:42  Downloading GA release of boot JDK version 15...
04:39:51  /home/adoptopenjdk/workspace/build-scripts/jobs/jdk/jdk-linux-x64-hotspot/jdk-15/bin/java: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /home/adoptopenjdk/workspace/build-scripts/jobs/jdk/jdk-linux-x64-hotspot/jdk-15/bin/../lib/libjli.so)
```

**Comment by aahlenst** [comment]
Should be fixed with 15.0.1, but nevertheless, the containers need a JDK update then: https://github.com/AdoptOpenJDK/openjdk-build/issues/2097

**Comment by sxa** [comment]
Hmmm do we not run the PR testing on Windows? I would have through this would get picked up

**Comment by sxa** [comment]
This was introduced by https://github.com/AdoptOpenJDK/openjdk-build/pull/2154 and will resolve itself once the next GA JDK15 goes out this week.

**Comment by sxa** [comment]
https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk/job/jdk-linux-x64-hotspot/ is now passing
