### ISSUE TITLE
docker-packet-ubuntu1604-armv8-1 needs bootjdk14 & 15

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-infrastructure#1636]
docker-packet-ubuntu1604-armv8-1 needs bootjdk 14 & 15 to be able to build jdk-15 and jdk-16

**Comment by Willsparker** [comment]
Wouldn't the docker containers just need them?

**Comment by andrew-m-leonard** [comment]
Looks like it tried to download jdk14, but the download actually failed:
```
09:02:12  Downloading GA release of boot JDK version 14...
09:02:12  
09:02:12  gzip: stdin: unexpected end of file
09:02:12  tar: Child returned status 1
09:02:12  tar: Error is not recoverable: exiting now
09:02:12  Downloading GA release of boot JDK version 14 failed.
09:02:12  Attempting to download EA release of boot JDK version 14 ...
09:02:12  
09:02:12  gzip: stdin: unexpected end of file
09:02:12  tar: Child returned status 1
09:02:12  tar: Error is not recoverable: exiting now
```
Closing as a probably glitch

**Comment by andrew-m-leonard** [comment]
Ah no, it is an issue, as the auto download code is trying to download a GA release for aarch64 for jdk14 openj9, of which there isn't one!!

**Comment by sxa** [comment]
Surprised that machine has been selected for builds and its not a build- prefixed one

**Comment by Willsparker** [comment]
@sxa I'm happy to do it, but I'll need my ssh-key put on the machine

**Comment by sxa** [comment]
We don't build on Ubuntu 16.04 for aarch64. I have removed the `build` tag from the machine
