### ISSUE TITLE
(temp) Infra-Access: Need root access to Jenkins server

### ISSUE THREAD

**Issue by Willsparker** [AdoptOpenJDK/openjdk-infrastructure#1637]
Ref: #1569 

I need `root` access to setup a cron job for the `root` user to monitor and auto-renew the SSL certificate - Or any user that has access to the `/opt/letsencrypt` directory. Currently only have access to the `will` user, which doesn't have the perms to renew the cert.
I'll document in the above referenced issue what I'll do specifically.

It will also (probably) help with #1229 , but I can cross that bridge when I get to it :-)

**Comment by karianna** [comment]
post-release day I can screen share and you can walk me through the steps

**Comment by Willsparker** [comment]
Sure :-)

**Comment by sxa** [comment]
@Willsparker when are you around this week? We could try and schedule something with @karianna tomorrow if he's around too since we've got the main releases out. Do you know the required steps or shall we make it up on the fly (Shoulkd be pretty straightforward!)

**Comment by Willsparker** [comment]
To be honest, I don't need to do it myself! Should just need to run
`echo "letsencrypt-auto renew --renew-hook \"systemctl reload nginx\"" >> /etc/cron.weekly/cert_renewal`
Otherwise, I'm around generally in the mornings on weekdays (9-12ish) :-)

**Comment by Willsparker** [comment]
@karianna has put the cronjob in for me. Closing issue
