### ISSUE TITLE
Apt error since 24.10.2020

### ISSUE THREAD

**Issue by assachs** [AdoptOpenJDK/openjdk-infrastructure#1647]
Hello,
since 24.10.2020 i get the following error on several servers (with "apt update"):

E: Encountered a section with no Package: header
E: Problem with MergeList /var/lib/apt/lists/adoptopenjdk.jfrog.io_adoptopenjdk_deb_dists_buster_main_binary-amd64_Packages
E: The package lists or status file could not be parsed or opened.

Since the problem is on multiple servers, i think it's a problem with the file from the repository.

Maybe it's because there is a section with only 4 lines:

Filename: pool/main/a/adoptopenjdk-8-openj9-jre/adoptopenjdk-8-openj9-jre_8u272-b10.openj9-0.23.0-3_amd64.deb
SHA1: 0d99f2588c310a2cb9c89302e25c4d9209c18e6e
SHA256: 6a639904c2b9b2b39a2404fc93bc5c0a9f7a25e29897b0fbbdf1823f858b2e6c
Size: 48905302

**Comment by sxa** [comment]
One for @aahlenst ?

**Comment by aahlenst** [comment]
Have some patience. Jenkins is running since 11:10 UTC and doing package builds/uploads and will do so for at least another 2.5 hours. Apt is inherently racy and, on top of it, Artifactory sucks at doing Apt, so maybe that one is going to heal itself.

**Comment by withanhdammit** [comment]
+1
Will try again later.
```
Hit:8 https://adoptopenjdk.jfrog.io/adoptopenjdk/deb buster InRelease
Reading package lists... Error!
E: Encountered a section with no Package: header
E: Problem with MergeList /var/lib/apt/lists/adoptopenjdk.jfrog.io_adoptopenjdk_deb_dists_buster_main_binary-amd64_Packages
E: The package lists or status file could not be parsed or opened.
```

**Comment by aahlenst** [comment]
Jenkins is done, indexes have been rebuilt, problem is gone. See you next time around for the January CPU. 🥳

**Comment by aahlenst** [comment]
Ah, dang. We have to rebuild 11 for Shenandoah. So yeah, we'll have that problem again maybe on Monday or so, but because it's only 11 Hotspot it will probably be shorter.

**Comment by sxa** [comment]
> because it's only 11 Hotspot it will probably be shorter.

Yep will only impact Linux/x64 and Linux/aarch64 in terms of the apt repos

**Comment by aahlenst** [comment]
FYI: Packages for 11 have been updated. This should have been the last interruption until January 2021. :crossed_fingers:

**Comment by tariqk** [comment]
Hi, welcome from January 2021. As expected, getting the same error on my Raspberry Pi 4:

```
Hit:5 https://adoptopenjdk.jfrog.io/adoptopenjdk/deb buster InRelease
Reading package lists... Error!
E: Encountered a section with no Package: header
E: Problem with MergeList /var/lib/apt/lists/adoptopenjdk.jfrog.io_adoptopenjdk_deb_dists_buster_main_binary-arm64_Packages
E: The package lists or status file could not be parsed or opened.
```

**Comment by aahlenst** [comment]
I pressed the magic button and it should be working again.

**Comment by tariqk** [comment]
Yes it did. Thank you!
