### ISSUE TITLE
Ansible using older access method to GitHub

### ISSUE THREAD

**Issue by karianna** [AdoptOpenJDK/openjdk-infrastructure#1648]
Hello there!

On October 24th, 2020 at 12:42 (UTC) your application (Ansible - Admins) used an access token (with the User-Agent python-requests/2.14.2) as part of a query parameter to access an endpoint through the GitHub API.

https://api.github.com/user

Please use the Authorization HTTP header instead as using the `access_token` query parameter is deprecated.

Depending on your API usage, we'll be sending you this email reminder on a monthly basis.

Visit https://developer.github.com/changes/2020-02-10-deprecating-auth-through-query-param for more information about suggested workarounds and removal dates.

Thanks,
The GitHub Team

**Comment by sxa** [comment]
This doesn't cause a problem as we are in dire need of replacing our ansible server which is not currently being used as it's old (See #756) ... I don't want to completely remove it until we've got a replacement running, but I'm going to close this on the basis that no specific action will be taken on the old server to mitigate it other than shutting it down at some point.

(Side note: I finally have a bit more time and getting this replaced is near the top of my priority stack)
