### ISSUE TITLE
build-osuosl-* AIX systems - planned downtime

### ISSUE THREAD

**Issue by aixtools** [AdoptOpenJDK/openjdk-infrastructure#1651]
Downtime planned for **09-November-2020**, starting at approximately 07.00 GMT - for Systems maintenance.

Please advise re: show-stoppers, if any.

**Comment by sxa** [comment]
Does this really only affect the `build-osuosl` AIX systems and not the `test-osuosl` ones?

**Comment by aixtools** [comment]
System affected include:

p8-aix2-ojdk01 | 140.211.9.10
-- | --
p8-aix2-ojdk02 | 140.211.9.12
p8-aix2-odjk03 | 140.211.9.28
p8-aix2-ojdk04 | 140.211.9.36

**Comment by aixtools** [comment]
The systems were down, but up again. An unexpected blocker prevents the planned maintenance.

I'll come up with a new plan - that will include a short downtime for the individual nodes.

**Comment by sxa** [comment]
@aixtools Any update on the plan for this?

**Comment by aixtools** [comment]
Working on it now.

Are there build-cycles that I may not interrupt?

Step 1 is moving the partitions away from the frame they are on now. I have flexibility in which ones I do first. Currently I am looking at the largest ones (>500G active data to move). But I could do the smaller ones first.

For ojdk: smaller ones are:

p8-aix2-ojdk01 | 140.211.9.10
p8-aix2-ojdk02 | 140.211.9.12
p8-aix2-odjk03 | 140.211.9.28
p8-aix2-ojdk04 | 140.211.9.36

**Comment by sxa** [comment]
Unless any unexpected releases show up I can work around any time you want in the next few weeks - a couple of days notice would be appreciated though :-)

**Comment by aixtools** [comment]
If nothing comes up - real life wise - next Monday morning then - from approximately 0600 GMT until 1200-1300.

If something comes up, I'll post here with a new time.

Next Monday is OK?

**Comment by sxa** [comment]
Yes that sound be ok - thanks :-)

**Comment by aixtools** [comment]
going much slower than expected. Might only have one system completed today.

In any case: not going to start with ojdk03 or ojdk04

**Comment by aixtools** [comment]
No success today. Issues with system configuration prevent normal backup/restore operations.

**Comment by Haroon-Khel** [comment]
@aixtools Any update on this?

**Comment by aixtools** [comment]
No. Systems are not cooperating with creating a SPOT - the classic way to backup and move systems. I am still experimenting. And not happy when systems boot with messages such as" grep_64: .... - as this shows the defaults AIX needs are not functioning.

**Comment by aixtools** [comment]
when is the next release cycle, or was it last month? Not going to attempt this near a release cycle.

**Comment by sxa** [comment]
Next week, so yeah let's hold off til that one's complete :-)

**Comment by aixtools** [comment]
ok, so after 25 January.

**Comment by sxa** [comment]
@aixtools Is there still some downtime required?

**Comment by aixtools** [comment]
Yes. Still need to do VIOS updates - but moving the systems is complex - normal NIM backup/restore is not working with the current configurations.

**Comment by Haroon-Khel** [comment]
@aixtools Any update on this?

**Comment by aixtools** [comment]
Moving build-osuosl-aix71-ppc64-1 this morning. Expect to move build-osuosl-aix71-ppc64-2 tomorrow. Others are moved already.

**Comment by aixtools** [comment]
Systems moved. Will open a new issue if/when movement is needed again.
