### ISSUE TITLE
Machines low on disk space: zLinux build machines

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-infrastructure#1652]
The following nodes are short or near on short of disk space, ideally we need 15Gb free please:

- **offline:** https://ci.adoptopenjdk.net/computer/build-marist-rhel77-s390x-2/
- **close to limit:** https://ci.adoptopenjdk.net/computer/build-marist-rhel77-s390x-1X/
- **offline:** https://ci.adoptopenjdk.net/computer/test-macincloud-macos1014-x64-1/

**Comment by sxa** [comment]
I have a request in to Marist to get upgrades/replacements in place for the build machines as we've now got to the state where the working set of builds is greater than the amount we originally had (which has served us fine up til now)

The macincloud space issue isbeing tracked under https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1659

**Comment by sxa** [comment]
https://ci.adoptopenjdk.net/computer/build-marist-rhel77-s390x-1 is temporarily offline while it's disk is upgraded. I've removed the ability for https://ci.adoptopenjdk.net/computer/build-marist-rhel77-s390x-2 to run tests just now as I want to keep it free for builds while the other machine is down. This will slow things down overnight as we have one fewer machine than usual.

**Comment by sxa** [comment]
This is still on Marist's queue but it keeps getting delayed

**Comment by sxa** [comment]
I thnk [the enabling of JDK16/J9/XL](https://github.com/AdoptOpenJDK/openjdk-build/pull/2251/files) has pushed us over the limit of these machines so I will look at removing that for now until we have more space available.

Saying that, it is interesting that the JDK11 J9 buids seem larger than expected when compared with other versions - we should investigate in case that is indicative of a wider problem (FYI @andrew-m-leonard)

**Comment by sxa** [comment]
[build-scripts-testing](https://ci.adoptopenjdk.net/view/work-in-progress/job/build-scripts-testing) has been chewing up extra disk space on these machiens so I've requested that we avoid running it on zLinux for now. Memo to self: let Morgan know when we have this resolved so they can be used for testing again.

**Comment by sxa** [comment]
Following up again today ...

**Comment by sxa** [comment]
Expecting to get at least one of these machines done in the next day :-)

**Comment by sxa** [comment]
Probably fully mitigated by https://github.com/AdoptOpenJDK/openjdk-build/pull/2416 - the machines are now using about a third of the disk space after removing move of the built artefacts, with no obvious side effects, so if we continue like that, even with the debug builds we should be ok.
