### ISSUE TITLE
Access request for knn-k

### ISSUE THREAD

**Issue by knn-k** [AdoptOpenJDK/openjdk-infrastructure#1656]
Access level:
- [x] Non-privileged
- [ ] jenkins user
- [ ] root/Administrative
- [ ] other (Please specify):

System for which access is needed: test-aws-rhel76-armv8-3

Please explain why you need this access including whether it is a temporary or permanent request:

I need a temporary access to the machine to investigate an issue that seems to occur only on it.
https://github.com/eclipse/openj9/issues/10847

My ssh key:
```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDTr4lPUz3Tbqb4+XssAziu8U86/9T3DZueDRIw9P85PPjtDbGPAAjdZGwG0V5/l8KP5PGdiQoaNnGI8Cw1zczZLN6WSvQmkgcLgUJyPwk4XMBZEL9NuFkcdOX+kX+EtJqrFS6TKlED91Mu++G0E86PTJRT0xMoFZkGz4jouU01GRyprOaqs2GMMgE4Q+cM4Kva18J9225U7Ci1HdlByk91A8RpbQGgAW2bClgDOys/pqr83Q4/jrc7RXF1Z+F63RtC4Izv10xCoxnl0vLb31SpnauwnzXuL0LbB2zpNXkAySxeXUkORQSMMKPRyNle+zvZjDY2snTYF2qYOVpkGZBf konno
```

**Comment by sxa** [comment]
Slightly worryingly that machine appears to have crashed and I can't get into it at the moment ...

**Comment by sxa** [comment]
OK I've got the system recovered but it required a restart. Your key is on the machine - connect to `konno@34.246.191.41`

I've initiated another test run on that machine here: https://ci.adoptopenjdk.net/job/Test_openjdk15_j9_sanity.openjdk_aarch64_linux/85/console

Bear in mind that since I had to restart the machine it's possible that will affect whether your issue can be reproduced.

Once that jenkins job has completed the machine will be offline to other jenkins jobs, so you will have exclusive use of it.

**Comment by knn-k** [comment]
@sxa I get the following error:

```
$ ssh konno@34.246.191.41
konno@34.246.191.41: Permission denied (publickey,gssapi-keyex,gssapi-with-mic).
```

Adding the `-vvv` option to the ssh command shows the following debug output:

```
debug1: Authentications that can continue: publickey,gssapi-keyex,gssapi-with-mic
debug1: Trying private key: /home/konno/.ssh/id_dsa
debug3: no such identity: /home/konno/.ssh/id_dsa: No such file or directory
debug1: Trying private key: /home/konno/.ssh/id_ecdsa
debug3: no such identity: /home/konno/.ssh/id_ecdsa: No such file or directory
debug1: Trying private key: /home/konno/.ssh/id_ed25519
debug3: no such identity: /home/konno/.ssh/id_ed25519: No such file or directory
debug2: we did not send a packet, disable method
debug1: No more authentication methods to try.
konno@34.246.191.41: Permission denied (publickey,gssapi-keyex,gssapi-with-mic).
```

**Comment by sxa** [comment]
Apologies - cut & paste error on my part and it was missing the first `s` of `ssh` at the start - should be ok now

**Comment by sxa** [comment]
Note that the sanity.openjdk job linked above worked on there so it may not reproduce the error any more ...

**Comment by knn-k** [comment]
Thank you.  I can ssh to the machine now.

**Comment by knn-k** [comment]
I think I don't need the access any more.

**Comment by sxa** [comment]
Thanks - if you find you need it again for something specific to the machine please raise another issue
