### ISSUE TITLE
System unavailable: mac&&macos10.14&&xcode10 out of disk space

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-infrastructure#1659]
All the Mac 10.14 nodes are offline, low on disk space:
https://ci.adoptopenjdk.net/label/mac&&macos10.14&&xcode10/

**Comment by sxa** [comment]
NOTE: This is problematic as it is the node label set required for [create_installer_mac](https://ci.adoptopenjdk.net/job/build-scripts/job/release/job/create_installer_mac/)

**Comment by sxa** [comment]
Removed `xcode10.zip` from test-macincloud-macos1014-x64-1's /Users/admin directory which lets us re-enable the machine. There is also a 2.5Gb openj9 source tree as well as two untarred JDK11 directories and one tarred up one.

47Gb is rather low though, so @gdams is going to reprovision some of these systems with larger disks.

**Comment by karianna** [comment]
@gdams - This is done now correct?

**Comment by sxa** [comment]
PING @gdams

**Comment by gdams** [comment]
This is done
