### ISSUE TITLE
Rebuilt AWX

### ISSUE THREAD

**Issue by bblondin** [AdoptOpenJDK/openjdk-infrastructure#166]
AWX is having issues...

We already know of the job status output screen not displaying output and project updates not refreshing.

Today I created a new inventory with 15 systems, upon running a template, it only attempted to run on 12 of the 15 and 1 of the systems somehow used the wrong ip address that wasn't in the inventory.

Since we don't have much setup in AWX it won't be a big lose to rebuild it. 

@gdams What do think?

**Comment by gdams** [comment]
I'm happy for this to be rebuilt if it's not a massive task and we don't have loads of downtime?

**Comment by geraintwjones** [comment]
Going forward, is it worth having as much of the AWX setup/config files as makes sense (or is possible) in GitHub?

**Comment by gdams** [comment]
This ties into the conversation we had about having an inventory in github I suppose

**Comment by geraintwjones** [comment]
Yes it does, and I know (because I've done it) that you can point some AWX artifacts (inventories, the playbooks referenced from templates) at something in GitHub. I was wondering if there's even more we can put into GitHub, so that if we ever need to "start again" with AWX it would be less painful once we've got a lot invested in it.

**Comment by gdams** [comment]
I agree, I'd also like to get github oauth working so we don't have to worry about user accounts

**Comment by bblondin** [comment]
I should be able to work on this Friday

**Comment by bblondin** [comment]
AWX has been rebuild.

- This has fixed the issues with job status output screen not displaying output and project updates not refreshing.

I am currently working on enabling github auth

**Comment by bblondin** [comment]
Looking very good. I added an inventory for all Ubuntu build/test machines and ran the playbook
3 failed with ssh key issues (fixed in keybox)
and 2 more which are waiting on this pull request https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/168

**Comment by bblondin** [comment]
github auth appears to require https on awx, having some issues getting that working. will try again on monday... everything else looks good

**Comment by bblondin** [comment]
AWX is up and running under HTTPS with a self-sign cert.

I was unable to get the job status output to refresh. It appear that there is a bug with some of the support applications.

**Comment by bblondin** [comment]
We are now using cloudflare
