### ISSUE TITLE
/tmp directory being filled by builds

### ISSUE THREAD

**Issue by karianna** [AdoptOpenJDK/openjdk-infrastructure#1661]
/tmp directory is bring filled by builds/installers with files like:

* `/tmp/.gradle-test-kit-jenkins/caches/6.1/scripts`
* `validConnection(org.openjdk.jmc.browser.uitest.CustomConnectionsTest)10802483471178210696dump.png`

We'll need to either get those jobs to tidy up after themselves or write cleaner/sweeper scripts

**Comment by sxa** [comment]
Duplicate of https://github.com/AdoptOpenJDK/openjdk-installer/issues/255
