### ISSUE TITLE
build-ibmcloud-win2012r2-x64-2 fails builds because it cannot delete jenkins/tmp folder

### ISSUE THREAD

**Issue by adamfarley** [AdoptOpenJDK/openjdk-infrastructure#1662]
Action requested:
Please can someone with access to build-ibmcloud-win2012r2-x64-2 take a look at E:\jenkins\tmp and see if they can tell why we can't delete it?

Note:
Please avoid deleting the folder yourself, or restarting the machine. We'd like to figure why this issue has occurred so we can prevent it happening in the future.

Error message:
```
20:27:33  ERROR: Failed to clean the workspace
20:27:33  jenkins.util.io.CompositeIOException: Unable to delete 'E:\jenkins\tmp'. Tried 3 times (of a maximum of 3) waiting 0.1 sec between attempts.
20:27:33  	at jenkins.util.io.PathRemover.forceRemoveDirectoryContents(PathRemover.java:90)
20:27:33  	at hudson.Util.deleteContentsRecursive(Util.java:261)
20:27:33  	at hudson.Util.deleteContentsRecursive(Util.java:250)
etc
```

Examples:

https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-windows-x86-32-openj9/746/console
https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-windows-x64-hotspot/801/console

**Comment by Willsparker** [comment]
ref: #1396 

Sorry, I removed the file manually before I saw this issue (@sxa asked me to check the machine, via Slack)
We have a fix for this in other Windows machines : https://github.com/AdoptOpenJDK/openjdk-build/pull/1956/ 
So, I'm adding `E:/jenkins/tmp etc` to that list here: https://github.com/AdoptOpenJDK/openjdk-build/pull/2204

Closing issue, but I'm going to raise another one in `openjdk-build` to aim to get a less hacky solution: https://github.com/AdoptOpenJDK/openjdk-build/issues/2205
