### ISSUE TITLE
Verify that all Windows machines have useful permissions on them

### ISSUE THREAD

**Issue by sxa** [AdoptOpenJDK/openjdk-infrastructure#1666]
I was looking at the event log on build-azure-1 today and it was full of errors from the jenkins agent trying to write to `C:\Users\jenkins` which it didn't have permission to write to.

We should do an audit of all of the build machines and ensure they have permission to write to wherever they need to. If the home directory for the user is not `C:\users\jenkins` then we could find out how to set that location being used by jenkins to another location

**Comment by sxa** [comment]
@Willsparker Are you able to look at this? It would be good to do a sweep since we've brough a few online earlier this week and ensure there is no risk to the nightly build pipelines

**Comment by Willsparker** [comment]
Yep! I'll have a look today

**Comment by Willsparker** [comment]
The process I'm going through is making sure the Jenkins user has full access to the `C:/user/jenkins` folder, as that's where the Jenkins-Agent stuff is stored, and the Workspace folder that the Jenkins user uses.

- [x] build-azure-win2012r2-x64-1      
- [x] build-azure-win2012r2-x64-2
- [x] build-ibmcloud-win2012r2 -x64-1
- [ ] build-ibmcloud-win2012r2 -x64-2
- [ ] test-azure-win2012r2-x64-1
- [ ] test-azure-win2012r2-x64-2
- [ ] test-azure-win2012r2-x64-3
- [ ] test-aws-win2019-x64-1
- [ ] test-aws-win2019-x64-2
- [ ] test-godaddy-win2016-x64-1
- [ ] test-godaddy-win2016-x64-2
- [ ] test-godaddy-win2016-x64-3
- [ ] test-godaddy-win2016-x64-4
- [ ] test-packet-win2012r2-x64-1
- [ ] test-ibmcloud-win2012r2-x64-1
- [ ] test-ibmcloud-win2012r2-x64-2

**Comment by Willsparker** [comment]
`test-ibmcloud-win2012r2-x64-2` is having some issues with taking RDP connections for now, but it will probably need it's permissions updated too, considering `-1` needed it.

**Comment by sxa** [comment]
Fixing the last machine is blocked on #1690 but I'm happy to close this for now, particularly since we're looking into why we're getting the duplicate home directory for the jenkins user as part of https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1674

**Comment by sxa** [comment]
OK It's come back properly now so I'll reopen to let you finish it :-)

**Comment by Willsparker** [comment]
After all that, I didn't even need to change the permissions! :sweat: 
Closing issue
