### ISSUE TITLE
Replace Travis CI, come up with CI strategy

### ISSUE THREAD

**Issue by aahlenst** [AdoptOpenJDK/openjdk-infrastructure#1668]
Earlier this week, [Travis CI announced a new pricing scheme that also limited the available minutes to OSS projects to 1000](https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing). Those 1000 minutes are a one-time thing. After using them up, we'd have request a new allotment every time the old one runs out. 

Unsurprisingly, we consumed those minutes in 2 days or so and at least since Thursday morning (UTC), no builds were run on Travis CI.  According to the Travis CI dashboard, we've consumed over 6000 minutes in the last 30 days.

Affected repositories according to the Travis CI dashboard:

* openjdk-infrastructure
* blog ✔️ 
* IcedTea-Web ✔️
* jlink.online ✔️
* homebrew-openjdk ✔️
* openjdk-website-next (orphaned)
* openjdk-website ✔️

As a contingency measure, we've purchased the smallest Travis CI plan, but that one has a concurrency of 1. But that's not going to work out long-term and continuosly having to ask Travis CI to expand our allowance isn't attractive, either. The actual OSS offering [travis-ci.org will be put into read-only mode on 2020-12-31](https://docs.travis-ci.com/user/migrate/open-source-repository-migration/#frequently-asked-questions).

Looking through the archives, I could not find a formal decision to use Travis CI. There was only a discussion that dried up in 2019: https://github.com/AdoptOpenJDK/TSC/issues/38.

On yesterday's TSC call, we had a brief discussion how to proceed in the short-term. Decisions:

* If possible, migrate repositories over to GitHub Actions.
* Purchase the smallest Travis CI plan for repositories cannot be moved.
* Investigate alternatives.

Just moving everything over to GitHub Actions is only a short-term measure for multiple reasons:

* Travis CI supports Linux on p (ppc64le) and z (s390x), GitHub Actions does not. This is a problem for openjdk-infrastructure, openjdk-build and the Linux packages currently being in development.
* Even before moving the remaining repositories to GitHub Actions, GitHub Actions was already overloaded which prompted us to [disable the macOS PR tester](https://github.com/AdoptOpenJDK/openjdk-build/pull/2213).

**Comment by aahlenst** [comment]
@smlambert and me started discussions with IBM. IBM is working with another vendor to add support for Linux on p and z.

@gdams @dinogun I've seen a `.travis.yml` in openjdk-docker but the repository does not show up in the Travis CI dashboard. Can you confirm that we're not using Travis CI for Docker?

**Comment by gdams** [comment]
> I've seen a .travis.yml in openjdk-docker but the repository does not show up in the Travis CI dashboard. Can you confirm that we're not using Travis CI for Docker?

@aahlenst the docker repo only uses GH Actions and Appveyor now

**Comment by gdams** [comment]
https://github.com/AdoptOpenJDK/openjdk-docker/pull/460

**Comment by aahlenst** [comment]
homebrew-openjdk isn't using Travis CI since https://github.com/AdoptOpenJDK/homebrew-openjdk/commit/5040d9bed721540b4b76c0e646a92360547b69a8.

**Comment by aahlenst** [comment]
According to reports, Travis CI stopped giving out free minutes for OSS: https://news.ycombinator.com/item?id=25338983

**Comment by aahlenst** [comment]
What needed to migrated away has been migrated away. `openjdk-infrastructure` has a `.travis.yml`, but that is only used to create container images for various platforms.

The aspect "Come up with CI strategy" could not be resolved. Discussions with IBM/CircleCI have shown that it wouldn't be a good choice for us (no immutable build workers). Apart from that, interest to have a good strategy seems to be low, therefore closing.
