### ISSUE TITLE
Ansible request for Windows jenkins user creation

### ISSUE THREAD

**Issue by sxa** [AdoptOpenJDK/openjdk-infrastructure#1674]
Please put the name of the software product (and affectred platforms if relevant) in the title of this issue

- [x] Bug in ansible playbook

Details:

We seem to be having issues whereby on Windows machines we are ending up with a `C:\Users\jenkins` directory which is:
- Not writable by the jenkins user
- Not the home directory of the jenkins user
- Set as the `Remote root directory` in the jenkins machine definition (because that's where we expect it to be)

_It would be useful to find out why the Windows playbooks seem to be giving us two home directories for jenkins - it almost feels like one is being created with `C:\Users\jenkins` as it's home dir and then another user is being create so it gets a funny name as the home dir, and that new user can't write to c:\Users\jenkins (because it's not the same user)_

We have manually tweaked the permissions on the `C:\Users\jenkins` directory on a number of machines but this is not the correct solution to this problem. We could, of course, modify the `Remote root directory` to point to the real home directory of the jenkins users but again, that doesn't seem to be the right solution. Let's try and fix this once and for all for reliability/stability.

![image](https://user-images.githubusercontent.com/6487691/98806142-a28a9580-2410-11eb-82c0-ea3fdf6fcae7.png)

**Comment by Willsparker** [comment]
Unfortunately, I'm unable to recreate the problem with the Windows Vagrant box - the only home user directory being created is `C:\Users\jenkins`. However, I did notice that the `win_user` module has an option `home_directory`. Looking at the `test-ibmcloud-win2012r2-x64-1` machine, the _actual_ home directory for the Jenkins user is the `C:\users\jenkins.<whatever>` folder (judging from the default directories), so it may just be as easy as putting 
`home_directory: C:\Users\jenkins` 
in the task- however, I'm unable to test that this will fix it properly, as I can't recreate the issue on the Vagrant box.

**Comment by sxa** [comment]
I think it's worth doing that change, if only because if it goes wrong it might help us identify when it's occurring.
Looks like it's happened on the AWS boxes, but not the GoDaddy ones. Perhaps I'll create a new AWS one and we can see if it's reproducible if we fire the playbooks on there.
Another thought - did you try running the playbook more than once on the same machine?

**Comment by sxa** [comment]
@Willsparker I'll give you a nice shiny new AWS machine to experiment with - `54.155.17.14`. Will send password elsewhere

**Comment by Willsparker** [comment]
ooooooo _shiny_

I don't think I did, actually. I'll try that with the AWS machine, checking in between. I'll put the fix in before I try :-)

**Comment by Willsparker** [comment]
Running the playbook twice ((without the proposed fix) on a Vagrant VM didn't recreate the issue

**Comment by sxa** [comment]
@Willsparker Another random thought - I wonder if it shows up when you have jenkins set up as a Windows service

**Comment by Willsparker** [comment]
You're right! Both of the folders `C:\users\jenkins` and `C:\jenkins\<something>` are created when the Jenkins service is started (on the Jenkins user). I'm going to try logging in as the Jenkins user before setting up the Jenkins agent, to see if it changes anything :-)

**Comment by Willsparker** [comment]
I've tried creating the `C:\users\jenkins` folder manually, and the one with the weird output was made when the Jenkins service started again.
So, I tried a third time, and if I logged in as the Jenkins user before setting the agent up as a service, the folder isn't created. Therefore, if there's some way we can automate logging on as the Jenkins user in the playbook, we won't run into this situation again (hopefully)..

**Comment by sxa** [comment]
I didn't think the service was set-up during the playbook - am I mistaken?
So you need to log in manually to be able to configure the service. In which case this shouldn't occur.

(I feel I'm missing something here)

Or is it that it happens each time the service is stopped/started, which would be more of a problem.

**Comment by Willsparker** [comment]
No, the service isn't setup as part of the playbook - however, you don't need to login as the Jenkins user to setup the service. To stop the weird folder from being created, the Jenkins user has to have been logged in, so Windows could finish setting up the user (in which, it creates the `C:\Users\jenkins` folder). If you then setup the service, the weird folder isn't created, and the home directory is `C:\Users\jenkins` as we want it to be.
I'm trying to come up with a way of the playbook automatically doing this sign-in thing, so it isn't required to be done manually by the person setting the machine up, before the starting the Jenkins Agent service

**Comment by sxa** [comment]
So given that you'd normally set it up as the jenkins user, what process is it that makes it create the extra one? Is it if you set it up as Administrator (Not something I've done before as you generally don't want it running at all as anything other than the jenkins user)

**Comment by Willsparker** [comment]
You have to be the administrator to install it as a service, IIRC. The process of installing it as a service (and starting it), as the Administrator (before the Jenkins user has been logged on), but then changing the service settings to make it run under the Jenkins user appears to be what creates the folder. 
Presumably if you can install the Jenkins agent as a service, as the Jenkins user, the folder wouldn't be made.

Also ... why don't we setup the Jenkins agent via the playbooks? https://docs.ansible.com/ansible/latest/collections/ansible/windows/win_service_module.html It looks fairly doable ...?

**Comment by sxa** [comment]
I thought you run the service as jenkins and use the menu option in there to install it which prompts you for the admin credentials? Although it's been a while since I did it...

**Comment by sxa** [comment]
> Also ... why don't we setup the Jenkins agent via the playbooks? https://docs.ansible.com/ansible/latest/collections/ansible/windows/win_service_module.html It looks fairly doable ...?

Haven't looked at it - depends if you can get the secret in there I guess.

**Comment by Willsparker** [comment]
Hmm- some documentation for setting up the Jenkins agent on windows machines are needed then, as I do it by the way I described above. With the way you described, the weird folder doesn't occur.
