### ISSUE TITLE
Inventory file is missing mac entries

### ISSUE THREAD

**Issue by Haroon-Khel** [AdoptOpenJDK/openjdk-infrastructure#1675]
Will use this issue to list the mac machines that appear to be in https://ci.adoptopenjdk.net/computer/ but not in the inventory file

**Comment by Haroon-Khel** [comment]
| Machine        | Inventory           | Jenkins  |
| ------------- |-------------| -----|
| test-macincloud-macos1010-x64-1 74.80.250.151    | - [ ] | - [ ] |

**Comment by Haroon-Khel** [comment]
@gdams Is the omission of some of these machines, either from the inventory file or jenkins, deliberate? I thought I should check with you before adding the missing machines to jenkins/inventory file

**Comment by sxa** [comment]
PING @gdams

**Comment by gdams** [comment]
@Haroon-Khel this PR updated the inventory file: https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/1665

It's been ready to go for some time if somebody can review it

**Comment by gdams** [comment]
Should be updated now
