### ISSUE TITLE
Access request for dinogun (jenkins id)

### ISSUE THREAD

**Issue by dinogun** [AdoptOpenJDK/openjdk-infrastructure#1678]
Access level:
- [x] Non-privileged
- [ ] jenkins user
- [ ] root/Administrative
- [ ] other (Please specify):

System for which access is needed: 
docker
- marist:
          ubuntu1603-s390x-1: {ip: 148.100.113.58, user: ubuntu}

Please explain why you need this access including whether it is a temporary or permanent request:
Temp request to test hotspot v8 s390x docker issues

**Comment by sxa** [comment]
Done and added you to the docker group - `dinogun@148.100.113.58`

**Comment by dinogun** [comment]
This issue is now [resolved](https://github.com/docker-library/official-images/pull/9128/files). Dont need access anymore
