### ISSUE TITLE
System unavailable: test-osuosl-aix71-ppc64-1 is hung

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-infrastructure#1682]
https://ci.adoptopenjdk.net/computer/test-osuosl-aix71-ppc64-1/
https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_extended.functional_ppc64_aix/21/consoleFull

Machine is hung

**Comment by Willsparker** [comment]
Jenkins job stopped, I sort of assume the process will need to be stopped manually on the machine? Not sure. Also, `test-osuosl-aix71-ppc64-1` isn't in `inventory.yml`

**Comment by Willsparker** [comment]
Seems to be okay running on a different job , therefore closing ...
