### ISSUE TITLE
Various QPC job failures

### ISSUE THREAD

**Issue by Haroon-Khel** [AdoptOpenJDK/openjdk-infrastructure#1685]
The Ubuntu s390x job has been failing for sometime now at the build stage with the following error
```
18:37:24 Running gradle with /usr/lib/jvm/jdk8 at /home/linux/openjdk-build/workspace/.gradle
18:37:28 Downloading https://services.gradle.org/distributions/gradle-6.5-bin.zip
18:37:55 
18:37:55 Exception in thread "main" javax.net.ssl.SSLHandshakeException: Remote host terminated the handshake
18:37:55 	at sun.security.ssl.SSLSocketImpl.handleEOF(SSLSocketImpl.java:1310)
18:37:55 	at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1151)
18:37:55 	at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1054)
```

The Ubuntu ppc64le job has failed in its recent runs during the playbooks stage when trying to install various packages:

```
16:24:41 failed: [localhost] (item=libgtk2.0-dev) => {"ansible_loop_var": "item", "cache_update_time": 1605535327, "cache_updated": false, "changed": false, "item": "libgtk2.0-dev", "msg": "'/usr/bin/apt-get -y -o \"Dpkg::Options::=--force-confdef\" -o \"Dpkg::Options::=--force-confold\"      install 'libgtk2.0-dev'' failed: E: Sub-process /usr/bin/dpkg returned an error code (1)\n"
```
```
16:27:12 failed: [localhost] (item=ruby) => {"ansible_loop_var": "item", "cache_update_time": 1605535327, "cache_updated": false, "changed": false, "item": "ruby", "msg": "'/usr/bin/apt-get -y -o \"Dpkg::Options::=--force-confdef\" -o \"Dpkg::Options::=--force-confold\"      install 'ruby'' failed: E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).\n", "rc": 100, "stderr": "E: Unmet dependencies.
```

**Comment by Haroon-Khel** [comment]
Recent s390x failure at https://ci.adoptopenjdk.net/job/QEMUPlaybookCheck/ARCHITECTURE=s390x,OS=ubuntu18,label=vagrant/159/console

**Comment by Haroon-Khel** [comment]
The s390x failure occurs at the gradlew stage in the build step. The job has trouble downloading https://services.gradle.org/distributions/gradle-6.5-bin.zip. 

When running the s390x qpc job directly on the machine, the build script has no problem downloading gradle

**Comment by Haroon-Khel** [comment]
The arm32 job fails during the build step aswell
```
08:42:05 javac: no source files
08:42:05 Usage: javac <options> <source files>
08:42:05 use -help for a list of possible options
08:42:06 CompileDemos.gmk:62: recipe for target '/home/linux/openjdk-build/workspace/build/src/build/linux-aarch32-normal-client-release/jdk/demo/applets/Blink/_the.BUILD_DEMO_APPLET_Blink_batch' failed
08:42:06 gmake[2]: *** [/home/linux/openjdk-build/workspace/build/src/build/linux-aarch32-normal-client-release/jdk/demo/applets/Blink/_the.BUILD_DEMO_APPLET_Blink_batch] Error 2
08:42:06 BuildJdk.gmk:93: recipe for target 'demos' failed
08:42:06 gmake[1]: *** [demos] Error 2
08:42:06 /home/linux/openjdk-build/workspace/build/src//make/Main.gmk:128: recipe for target 'demos-only' failed
08:42:06 make: *** [demos-only] Error 2
08:42:06 + grep -q '] Error' /home/vagrant5/workspace/QEMUPlaybookCheck/ARCHITECTURE/arm32/OS/debian8/label/vagrant/ansible/pbTestScripts/qemu_pbCheck/logFiles/DEBIAN8.ARM32.build_log
08:42:06 + echo BUILD FAILED
08:42:06 BUILD FAILED
```

**Comment by Haroon-Khel** [comment]
The ppc64le failure may have been intermittent. The recent job has passed without error
https://ci.adoptopenjdk.net/job/QEMUPlaybookCheck/ARCHITECTURE=ppc64le,OS=ubuntu18,label=vagrant/159/console

**Comment by sxa** [comment]
I've queued up https://ci.adoptopenjdk.net/view/Tooling/job/QEMUPlaybookCheck/160/ without the gradle step

> The arm32 job fails during the build step aswell
> 
> ```
> 08:42:05 javac: no source files
> 08:42:05 Usage: javac <options> <source files>
> 08:42:05 use -help for a list of possible options
> From https://ci.adoptopenjdk.net/job/QEMUPlaybookCheck/ARCHITECTURE=arm32,OS=debian8,label=vagrant/159/console

I think you've missed the critical part from that log - there is a segmentation failed a couple of lines above::

> 08:41:16 ## Starting demos
> 08:41:31 Compiling 1 files for BUILD_DEMO_APPLET_ArcTest
> 08:41:48 Compiling 1 files for BUILD_DEMO_APPLET_BarChart
> 08:42:04 Segmentation fault
> 08:42:04 Compiling 0 files for BUILD_DEMO_APPLET_Blink
> 08:42:05 javac: no source files
> 08:42:05 Usage: javac <options> <source files>
> 08:42:05 use -help for a list of possible options

**Comment by sxa** [comment]
I've queued up https://ci.adoptopenjdk.net/view/Tooling/job/QEMUPlaybookCheck/160/ without the gradle step (Based on my PR at https://github.com/AdoptOpenJDK/openjdk-build/pull/2228 which mean cause an issue with the metadata creation but it's not clear yet)

**Comment by Haroon-Khel** [comment]
Closing since these errors are no longer affecting the QPC job
