### ISSUE TITLE
System unavailable: https://ci.adoptopenjdk.net/label/build&&linux&&arm/ all offline : <10Gb disk space

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-infrastructure#1687]
https://ci.adoptopenjdk.net/label/build&&linux&&arm/

These machines have too little free disk space, i've had a look and cannot see anything obvious to delete

**Comment by timerush6669** [comment]
Stop

**Comment by sxa** [comment]
Removed `build-scripts-testing` directories from the workspace and re-enabled
