### ISSUE TITLE
System unavailable: pLinux & xLinux dockerBuild nodes not available

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-infrastructure#1688]
The Jenkins dockerBuild nodes seem unavailable, docker plugin offline maybe?
https://ci.adoptopenjdk.net/label/build&&linux&&x64&&dockerBuild/
https://ci.adoptopenjdk.net/label/build&&linux&&ppc64le&&dockerBuild/

**Comment by adamfarley** [comment]
That error message is only inside "waitForANodeToBecomeActive()", which shouldn't be used for docker builds.

If you've got a fork/branch of the openjdk-build repo that was created during one of the times we wrongly used  "waitForANodeToBecomeActive()" during the docker build path, then that might be the problem.

**Comment by adamfarley** [comment]
Link to failing job: https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk/job/jdk-linux-ppc64le-hotspot/305/console

**Comment by adamfarley** [comment]
Ok, that's using the main fork. Odd. Investigating.

**Comment by adamfarley** [comment]
Ok, that's the problem. That test ran after Morgan's timeout change broke everything, but *before* he added his change in to fix this very problem: https://github.com/AdoptOpenJDK/openjdk-build/pull/2221

**Comment by adamfarley** [comment]
Rule of thumb: If a docker build failed between 7:35pm on the 9th of November, and 10am on the 10th of November, it's this issue and it has been resolved.

Or it's using a branch that needs refreshing.

**Comment by sxa** [comment]
Hmmm ... Given that this was last night (i.e. after the merge went in) and it should have been from the main branches why do you think it affected this build?

**Comment by sxa** [comment]
Hmmm ok you're right ... But it looks like the JDK16 pipelines are broken which is why the latest one is from a week ago https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk16-pipeline/186/console
