### ISSUE TITLE
Setup weekly infrastructure call

### ISSUE THREAD

**Issue by gdams** [AdoptOpenJDK/openjdk-infrastructure#169]
I think that we have reached a point where we should perhaps split out the infrastructure call into a separate call and then just 1 person needs to report back to the Thursday call. Thoughts @AdoptOpenJDK/infrastructure

**Comment by bblondin** [comment]
I'd second that

**Comment by gdams** [comment]
Does anyone have any preference as to time? Wednesdays would work well for me and would mean that we could remember what to report back for the call on Thursday?? What times work best for everyone in @AdoptOpenJDK/infrastructure ??

**Comment by geraintwjones** [comment]
Wednesdays are my busiest days for meetings, though Tuesdays and Thursdays get quite busy simetimes too. Not sure if people like Mondays or Fridays because they tend to get swept into long weekends and they're when public holidays tend to occur. I was going to suggest Thursdays, but f that's when the "main" meeting is, maybe that's not such a good idea. Tuesday afternoons (UK time)?

**Comment by bletherhead** [comment]
Tuesday afternoons are best for me as well

**Comment by gdams** [comment]
@bblondin how do Tuesday afternoons work for you?

**Comment by bblondin** [comment]
@gdams I will assume you mean morning for me :)
I only have one meeting on Tuesday form 12:00-2pm EST

**Comment by gdams** [comment]
I have created https://calendar.google.com/event?action=TEMPLATE&tmeid=NDh0ZGxsdm9saXE0dmtuNnBjMTA4bTVkZXJfMjAxODAxMzBUMTUwMDAwWiBhZG9wdG9wZW5qZGtAbQ&tmsrc=adoptopenjdk%40gmail.com&scp=ALL. Please let me know if this works for everyone

**Comment by bblondin** [comment]
That works for me

**Comment by geraintwjones** [comment]
It works for me too.

**Comment by bletherhead** [comment]
Good for me too

**Comment by gdams** [comment]
Closing, We will see if everyone is able to attend the call tomorrow
