### ISSUE TITLE
Access request for leonarda

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-infrastructure#1701]
Access level:
- [ ] Non-privileged
- [x] jenkins user
- [ ] root/Administrative
- [ ] other (Please specify):

System for which access is needed: build-scaleway-ubuntu1604-armv7-2

Please explain why you need this access including whether it is a temporary or permanent request:
To debug issue: https://github.com/AdoptOpenJDK/openjdk-build/issues/2247

**Comment by sxa** [comment]
Access granted to user `leonarda` using the provided ssh key. I've given read acces to the jenkins dir. If that's inadequate let me know :-) Good luck with the issue

**Comment by andrew-m-leonard** [comment]
I don't need access any more, thanks
