### ISSUE TITLE
System unavailable: https://ci.adoptopenjdk.net/label/macos10.14&&build&&mac&&x64/ both down invalid SSH key

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-infrastructure#1714]
- Please put the system name in the title of this issue.
https://ci.adoptopenjdk.net/label/macos10.14&&build&&mac&&x64/

Looks like the Jenkins SSH key is invalid?

**Comment by gdams** [comment]
Duplicate. Closing
