### ISSUE TITLE
Solaris playbook cannot locate CSWpkgutil.pkg

### ISSUE THREAD

**Issue by sxa** [AdoptOpenJDK/openjdk-infrastructure#1722]
Please put the name of the software product (and affectred platforms if relevant) in the title of this issue

- [ ] Missing install
- [x] Bug in ansible playbook
- [ ] Request for new playbook addition

Details:
```
TASK [Common : Fetch CSWpkgutil.pkg] *******************************************

fatal: [127.0.0.1]: FAILED! => {"changed": false, "checksum": "f3ec18e5de2da7f4dc19e9464ad42a5f9b43ead6", "msg": "Source /export/home/vagrant/.ansible/tmp/ansible-tmp-1606569858.04-21931-70421185104931/source not found"}
```
Not immeidately clear why. Modifying the source path to be `../files/CSWpkgutil.pkg` (relative the the playbook that invokes it) doesn't appear to resolve it. Debug output (with the chane to use `src: ../files/CSWpkgutil.pkg` is below:

`TASK [Common : Fetch CSWpkgutil.pkg] ******************************************************************************************************************************************************************************
task path: /home/sxa/ws/adoptopenjdkPBTests/openjdk-infrastructure-master/ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/Solaris.yml:18
<127.0.0.1> ESTABLISH SSH CONNECTION FOR USER: vagrant
<127.0.0.1> SSH: EXEC ssh -vvv -F /dev/null -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=2204 -o 'IdentityFile="/home/sxa/ws/adoptopenjdkPBTests/openjdk-infrastructure-master/ansible/id_rsa"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="vagrant"' -o ConnectTimeout=30 -o ControlPath=/home/sxa/.ansible/cp/79ad8e6b4d 127.0.0.1 '/bin/sh -c '"'"'echo ~vagrant && sleep 0'"'"''
<127.0.0.1> (0, '~vagrant\n', 'OpenSSH_7.6p1 Ubuntu-4ubuntu0.3, OpenSSL 1.0.2n  7 Dec 2017\r\ndebug1: Reading configuration data /dev/null\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 17630\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 0\r\n')
<127.0.0.1> ESTABLISH SSH CONNECTION FOR USER: vagrant
<127.0.0.1> SSH: EXEC ssh -vvv -F /dev/null -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=2204 -o 'IdentityFile="/home/sxa/ws/adoptopenjdkPBTests/openjdk-infrastructure-master/ansible/id_rsa"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="vagrant"' -o ConnectTimeout=30 -o ControlPath=/home/sxa/.ansible/cp/79ad8e6b4d 127.0.0.1 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo ~vagrant/.ansible/tmp `"&& mkdir "` echo ~vagrant/.ansible/tmp/ansible-tmp-1606575086.15-17692-135169920606237 `" && echo ansible-tmp-1606575086.15-17692-135169920606237="` echo ~vagrant/.ansible/tmp/ansible-tmp-1606575086.15-17692-135169920606237 `" ) && sleep 0'"'"''
<127.0.0.1> (0, 'ansible-tmp-1606575086.15-17692-135169920606237=~vagrant/.ansible/tmp/ansible-tmp-1606575086.15-17692-135169920606237\n', 'OpenSSH_7.6p1 Ubuntu-4ubuntu0.3, OpenSSL 1.0.2n  7 Dec 2017\r\ndebug1: Reading configuration data /dev/null\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 17630\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 0\r\n')
Using module file /usr/lib/python2.7/dist-packages/ansible/modules/files/stat.py
<127.0.0.1> PUT /home/sxa/.ansible/tmp/ansible-local-17618R06MNy/tmpzy2fPg TO ~vagrant/.ansible/tmp/ansible-tmp-1606575086.15-17692-135169920606237/AnsiballZ_stat.py
<127.0.0.1> SSH: EXEC scp -vvv -F /dev/null -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=2204 -o 'IdentityFile="/home/sxa/ws/adoptopenjdkPBTests/openjdk-infrastructure-master/ansible/id_rsa"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="vagrant"' -o ConnectTimeout=30 -o ControlPath=/home/sxa/.ansible/cp/79ad8e6b4d /home/sxa/.ansible/tmp/ansible-local-17618R06MNy/tmpzy2fPg '[127.0.0.1]:'"'"'~vagrant/.ansible/tmp/ansible-tmp-1606575086.15-17692-135169920606237/AnsiballZ_stat.py'"'"''
<127.0.0.1> (0, '', "Executing: program /usr/bin/ssh host 127.0.0.1, user (unspecified), command scp -v -t '~vagrant/.ansible/tmp/ansible-tmp-1606575086.15-17692-135169920606237/AnsiballZ_stat.py'\nOpenSSH_7.6p1 Ubuntu-4ubuntu0.3, OpenSSL 1.0.2n  7 Dec 2017\r\ndebug1: Reading configuration data /dev/null\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 17630\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\nSending file modes: C0600 118911 tmpzy2fPg\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 0\r\n")
<127.0.0.1> ESTABLISH SSH CONNECTION FOR USER: vagrant
<127.0.0.1> SSH: EXEC ssh -vvv -F /dev/null -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=2204 -o 'IdentityFile="/home/sxa/ws/adoptopenjdkPBTests/openjdk-infrastructure-master/ansible/id_rsa"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="vagrant"' -o ConnectTimeout=30 -o ControlPath=/home/sxa/.ansible/cp/79ad8e6b4d 127.0.0.1 '/bin/sh -c '"'"'chmod u+x '"'"'"'"'"'"'"'"'~vagrant/.ansible/tmp/ansible-tmp-1606575086.15-17692-135169920606237/'"'"'"'"'"'"'"'"' '"'"'"'"'"'"'"'"'~vagrant/.ansible/tmp/ansible-tmp-1606575086.15-17692-135169920606237/AnsiballZ_stat.py'"'"'"'"'"'"'"'"' && sleep 0'"'"''
<127.0.0.1> (0, '', 'OpenSSH_7.6p1 Ubuntu-4ubuntu0.3, OpenSSL 1.0.2n  7 Dec 2017\r\ndebug1: Reading configuration data /dev/null\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 17630\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 0\r\n')
<127.0.0.1> ESTABLISH SSH CONNECTION FOR USER: vagrant
<127.0.0.1> SSH: EXEC ssh -vvv -F /dev/null -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=2204 -o 'IdentityFile="/home/sxa/ws/adoptopenjdkPBTests/openjdk-infrastructure-master/ansible/id_rsa"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="vagrant"' -o ConnectTimeout=30 -o ControlPath=/home/sxa/.ansible/cp/79ad8e6b4d -tt 127.0.0.1 '/bin/sh -c '"'"'sudo -H -S -n  -u root /bin/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-fccxrwgekskdkeihvvkejvijzhgucnfx ; PATH=/opt/csw/bin/:/usr/local/bin:/opt/csw/bin:/usr/xpg4/bin:/usr/sbin:/usr/bin:/usr/ucb /opt/csw/bin/python2.6 '"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'~vagrant/.ansible/tmp/ansible-tmp-1606575086.15-17692-135169920606237/AnsiballZ_stat.py'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"''"'"'"'"'"'"'"'"' && sleep 0'"'"''
Escalation succeeded
<127.0.0.1> (0, 'sudo: unable to resolve host adoptopenjdkSol10\r\n\r\n{"invocation": {"module_args": {"checksum_algorithm": "sha1", "get_checksum": true, "follow": false, "path": "/tmp/CSWpkgutil.pkg", "get_md5": false, "get_mime": true, "get_attributes": true}}, "stat": {"exists": false}, "changed": false}\r\n', 'OpenSSH_7.6p1 Ubuntu-4ubuntu0.3, OpenSSL 1.0.2n  7 Dec 2017\r\ndebug1: Reading configuration data /dev/null\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 17630\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 0\r\nShared connection to 127.0.0.1 closed.\r\n')
<127.0.0.1> PUT /home/sxa/ws/adoptopenjdkPBTests/openjdk-infrastructure-master/ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/files/CSWpkgutil.pkg TO ~vagrant/.ansible/tmp/ansible-tmp-1606575086.15-17692-135169920606237/source
<127.0.0.1> SSH: EXEC scp -vvv -F /dev/null -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=2204 -o 'IdentityFile="/home/sxa/ws/adoptopenjdkPBTests/openjdk-infrastructure-master/ansible/id_rsa"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="vagrant"' -o ConnectTimeout=30 -o ControlPath=/home/sxa/.ansible/cp/79ad8e6b4d /home/sxa/ws/adoptopenjdkPBTests/openjdk-infrastructure-master/ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/files/CSWpkgutil.pkg '[127.0.0.1]:'"'"'~vagrant/.ansible/tmp/ansible-tmp-1606575086.15-17692-135169920606237/source'"'"''
<127.0.0.1> (0, '', "Executing: program /usr/bin/ssh host 127.0.0.1, user (unspecified), command scp -v -t '~vagrant/.ansible/tmp/ansible-tmp-1606575086.15-17692-135169920606237/source'\nOpenSSH_7.6p1 Ubuntu-4ubuntu0.3, OpenSSL 1.0.2n  7 Dec 2017\r\ndebug1: Reading configuration data /dev/null\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 17630\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\nSending file modes: C0664 574464 CSWpkgutil.pkg\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 0\r\n")
<127.0.0.1> ESTABLISH SSH CONNECTION FOR USER: vagrant
<127.0.0.1> SSH: EXEC ssh -vvv -F /dev/null -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=2204 -o 'IdentityFile="/home/sxa/ws/adoptopenjdkPBTests/openjdk-infrastructure-master/ansible/id_rsa"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="vagrant"' -o ConnectTimeout=30 -o ControlPath=/home/sxa/.ansible/cp/79ad8e6b4d 127.0.0.1 '/bin/sh -c '"'"'chmod u+x '"'"'"'"'"'"'"'"'~vagrant/.ansible/tmp/ansible-tmp-1606575086.15-17692-135169920606237/'"'"'"'"'"'"'"'"' '"'"'"'"'"'"'"'"'~vagrant/.ansible/tmp/ansible-tmp-1606575086.15-17692-135169920606237/source'"'"'"'"'"'"'"'"' && sleep 0'"'"''
<127.0.0.1> (0, '', 'OpenSSH_7.6p1 Ubuntu-4ubuntu0.3, OpenSSL 1.0.2n  7 Dec 2017\r\ndebug1: Reading configuration data /dev/null\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 17630\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 0\r\n')
Using module file /usr/lib/python2.7/dist-packages/ansible/modules/files/copy.py
<127.0.0.1> PUT /home/sxa/.ansible/tmp/ansible-local-17618R06MNy/tmppajmQr TO ~vagrant/.ansible/tmp/ansible-tmp-1606575086.15-17692-135169920606237/AnsiballZ_copy.py
<127.0.0.1> SSH: EXEC scp -vvv -F /dev/null -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=2204 -o 'IdentityFile="/home/sxa/ws/adoptopenjdkPBTests/openjdk-infrastructure-master/ansible/id_rsa"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="vagrant"' -o ConnectTimeout=30 -o ControlPath=/home/sxa/.ansible/cp/79ad8e6b4d /home/sxa/.ansible/tmp/ansible-local-17618R06MNy/tmppajmQr '[127.0.0.1]:'"'"'~vagrant/.ansible/tmp/ansible-tmp-1606575086.15-17692-135169920606237/AnsiballZ_copy.py'"'"''
<127.0.0.1> (0, '', "Executing: program /usr/bin/ssh host 127.0.0.1, user (unspecified), command scp -v -t '~vagrant/.ansible/tmp/ansible-tmp-1606575086.15-17692-135169920606237/AnsiballZ_copy.py'\nOpenSSH_7.6p1 Ubuntu-4ubuntu0.3, OpenSSL 1.0.2n  7 Dec 2017\r\ndebug1: Reading configuration data /dev/null\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 17630\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\nSending file modes: C0600 123397 tmppajmQr\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 0\r\n")
<127.0.0.1> ESTABLISH SSH CONNECTION FOR USER: vagrant
<127.0.0.1> SSH: EXEC ssh -vvv -F /dev/null -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=2204 -o 'IdentityFile="/home/sxa/ws/adoptopenjdkPBTests/openjdk-infrastructure-master/ansible/id_rsa"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="vagrant"' -o ConnectTimeout=30 -o ControlPath=/home/sxa/.ansible/cp/79ad8e6b4d 127.0.0.1 '/bin/sh -c '"'"'chmod u+x '"'"'"'"'"'"'"'"'~vagrant/.ansible/tmp/ansible-tmp-1606575086.15-17692-135169920606237/'"'"'"'"'"'"'"'"' '"'"'"'"'"'"'"'"'~vagrant/.ansible/tmp/ansible-tmp-1606575086.15-17692-135169920606237/AnsiballZ_copy.py'"'"'"'"'"'"'"'"' && sleep 0'"'"''
<127.0.0.1> (0, '', 'OpenSSH_7.6p1 Ubuntu-4ubuntu0.3, OpenSSL 1.0.2n  7 Dec 2017\r\ndebug1: Reading configuration data /dev/null\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 17630\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 0\r\n')
<127.0.0.1> ESTABLISH SSH CONNECTION FOR USER: vagrant
<127.0.0.1> SSH: EXEC ssh -vvv -F /dev/null -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=2204 -o 'IdentityFile="/home/sxa/ws/adoptopenjdkPBTests/openjdk-infrastructure-master/ansible/id_rsa"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="vagrant"' -o ConnectTimeout=30 -o ControlPath=/home/sxa/.ansible/cp/79ad8e6b4d -tt 127.0.0.1 '/bin/sh -c '"'"'sudo -H -S -n  -u root /bin/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-oxcafligsaahwfhyxjgcsiyymfwhfftw ; PATH=/opt/csw/bin/:/usr/local/bin:/opt/csw/bin:/usr/xpg4/bin:/usr/sbin:/usr/bin:/usr/ucb /opt/csw/bin/python2.6 '"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'~vagrant/.ansible/tmp/ansible-tmp-1606575086.15-17692-135169920606237/AnsiballZ_copy.py'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"''"'"'"'"'"'"'"'"' && sleep 0'"'"''
Escalation succeeded
<127.0.0.1> (1, 'sudo: unable to resolve host adoptopenjdkSol10\r\n\r\n{"msg": "Source /export/home/vagrant/.ansible/tmp/ansible-tmp-1606575086.15-17692-135169920606237/source not found", "failed": true, "invocation": {"module_args": {"directory_mode": null, "force": true, "remote_src": null, "_original_basename": "CSWpkgutil.pkg", "owner": null, "follow": false, "local_follow": null, "group": null, "unsafe_writes": null, "setype": null, "content": null, "serole": null, "dest": "/tmp/CSWpkgutil.pkg", "selevel": null, "regexp": null, "validate": null, "src": "/export/home/vagrant/.ansible/tmp/ansible-tmp-1606575086.15-17692-135169920606237/source", "checksum": "f3ec18e5de2da7f4dc19e9464ad42a5f9b43ead6", "seuser": null, "delimiter": null, "mode": null, "attributes": null, "backup": false}}}\r\n', 'OpenSSH_7.6p1 Ubuntu-4ubuntu0.3, OpenSSL 1.0.2n  7 Dec 2017\r\ndebug1: Reading configuration data /dev/null\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 17630\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 1\r\nShared connection to 127.0.0.1 closed.\r\n')
<127.0.0.1> Failed to connect to the host via ssh: OpenSSH_7.6p1 Ubuntu-4ubuntu0.3, OpenSSL 1.0.2n  7 Dec 2017
debug1: Reading configuration data /dev/null
debug1: auto-mux: Trying existing master
`

**Comment by gdams** [comment]
Strange that it's working on the vagrant checked in github actions?

**Comment by sxa** [comment]
Question: What was the reason for `remote_tmp = $HOME/.ansible/tmp`?

@Willsparker Any idea why this is seemingly showing differences inside and outside VPC (the action code is in https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/master/.github/workflows/build_vagrant.yml

**Comment by Willsparker** [comment]
Didn't even know we were testing Solaris on VPC :sweat_smile: 
Really, they should be the same, because the Vagrantfile should remain consistent. 

I think this may be the method of communication between the VM and the host. The GitHub_action job runs on a macos host, whereas VPC runs on an Ubuntu1804 host. On my Linux Mint 20 laptop, I can't even start the playbook - 
```
Failed to connect to the host via ssh: Unable to negotiate with 127.0.0.1 port 2200: no matching key exchange method found. Their offer: gss-group1-sha1-toWM5Slw5Ew8Mqkay+al2g==,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1
```
The error message implies that it can't get the ansible temporary script onto the machine, so I doubt it's a playbook issue.

**Comment by Willsparker** [comment]
Yeah - https://ci.adoptopenjdk.net/job/VagrantPlaybookCheck/OS=Solaris10,label=vagrant/952/
The `remote_tmp = $HOME/.ansible/tmp` change fixes it. 
[This line](https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/14272c35b38fe04a54759ba3425d181b5d975390/ansible/ansible.cfg#L31) doesn't do anything in VPC, as VPC doesn't use the inventory.yml file.
