### ISSUE TITLE
System unavailable: docker-packet-ubuntu1604-armv8-1 docker daemon down

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-infrastructure#1726]
https://ci.adoptopenjdk.net/computer/docker-packet-ubuntu1604-armv8-1/
```
09:10:12  + docker pull adoptopenjdk/centos7_build_image
09:10:12  Using default tag: latest
09:10:12  Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```
https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-linux-aarch64-openj9/589/console

**Comment by sxa** [comment]
Odd:
`Active: inactive (dead) since Tue 2020-12-01 06:28:06 UTC; 4h 24min ago`
Restarted
