### ISSUE TITLE
Ansible request for Windows: Short Names for Folders enabled by default

### ISSUE THREAD

**Issue by adamfarley** [AdoptOpenJDK/openjdk-infrastructure#1729]
- [ ] Missing install
- [ ] Bug in ansible playbook
- [x] Request for new playbook addition

Details:
When passing a path into a Makefile on Windows, we need to use the shortened version of each folder name if it contains a space. Since several Windows machines (including) lack these short names for some folders, that is causing problems.

One specific case is the [CUDA issue](https://github.com/AdoptOpenJDK/openjdk-build/issues/2272), where we (currently) can't pass configure variables into the scripts if they contain spaces, because the speech marks get excised and each continuous chunk of text is treated as a separate argument (it seems).

So if all folders on all Windows machines could have these short names automatically added by default, that'd be ideal.

If that's too big, the specific CUDA case only requires two folders (below) to have shortened names. If these could have their short names generated by default, that would solve this specific case.

- C:/Program Files
- C:/Program Files/NVIDIA GPU Computing Toolkit

**Comment by sxa** [comment]
I believe https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/1250/files already implements this on the `C:` drive, therefore this shold not be a problem for future machines installs.

**Comment by Willsparker** [comment]
Unfortunately, the referenced issue is only for `Program Files (x86)`, not `Program Files`. While the task to enable shortnames on the C: drive will create shortnames when there's a new directory, it won't assign shortnames to directories from before it was enabled. 
The other issue, is that if a Windows Machine given to us from a provider doesn't already have Shortnames enabled, the `C:/Program Files` can't have one assigned unless booting it into safe-mode, as something will always be using the `C:/Program Files` folder (or having someone manually go on the machine, stop all the processes that are running on the machine, and doing it manually). In other words, I don't think this can necessarily be done through the playbooks.

**Comment by adamfarley** [comment]
@Willsparker - Sounds like a conversation for https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1731

You're right, changing the playbooks won't fix things retroactively. Manual intervention would be required.

I didn't know you had to stop all processes accessing a folder before you could set a short name though. It may be necessary though, if we're going to enable cuda support for openj9 builds again.
