### ISSUE TITLE
Windows nodes online, but cannot be scheduled...?

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-infrastructure#1738]
Plenty of nodes online: https://ci.adoptopenjdk.net/label/ci.role.test&&hw.arch.x86&&sw.os.windows/
but Jenkins job is waiting:
```
[Pipeline] nodesByLabel
Found a total of 5 nodes with the 'ci.role.test&&hw.arch.x86&&sw.os.windows' label
[Pipeline] node
Still waiting to schedule task
Waiting for next available executor on ‘ci.role.test&&hw.arch.x86&&sw.os.windows’
```

**Comment by sxa** [comment]
Hard to debug this since all the jobs have been aborted, but https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_sanity.openjdk_x86-64_windows/366/console seems to be running ok on one of them
