### ISSUE TITLE
Centos6 docker build failing with Mirrorlist issues

### ISSUE THREAD

**Issue by gdams** [AdoptOpenJDK/openjdk-infrastructure#1745]
Currently, this is broken upstream and waiting on a fix

https://github.com/CentOS/sig-cloud-instance-images/issues/176

**Comment by gdams** [comment]
```bash
Setting up Update Process
Error: Cannot retrieve repository metadata (repomd.xml) for repository: base. Please verify its path and try again
YumRepo Error: All mirror URLs are not using ftp, http[s] or file.
 Eg. Invalid release/repo/arch combination/
removing mirrorlist with no valid mirrors: /var/cache/yum/x86_64/6/base/mirrorlist.txt
Loaded plugins: fastestmirror, ovl
Cleaning repos: base extras updates
Cleaning up Everything
Loaded plugins: fastestmirror, ovl
Setting up Install Process
Determining fastest mirrors
Error: Cannot find a valid baseurl for repo: base
```

**Comment by Willsparker** [comment]
This has also become an issue with the CentOS6 Vagrantfile (see: https://ci.adoptopenjdk.net/job/VagrantPlaybookCheck/OS=CentOS6,label=vagrant/957/console) 
In the provisioning stage, it's not able to install `libselinux-python` , causing the `Update /etc/hosts file - IP FQDN hostname` task to fail.

**Comment by Willsparker** [comment]
( ref: #1756 )

**Comment by Willsparker** [comment]
Well, This may or may not have been known but CentOS6 is at the end of it's life (https://wiki.crowncloud.net/index.php?fixing_update_issues_in_centos6), so, naturally, all the yum stuff becomes broken.

As Stewart attempted in the above referenced PR, we can switch to using `vault.centos` , and I've managed to get this working with the CentOS6 Vagrant VM.

**Comment by Willsparker** [comment]
This is still an issue, unfortunately - the CentOS SCL repo (installed [here](https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/6b233b3f963c6a22cbde3be1b51ff34c1465799a/ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/CentOS.yml#L100) , also has an out of date `baseurl`, so I'm looking to create a task that will change the repo to using `CentOS Vault` like the changes made to the Vagrantfile and Dockerfile in #1765 .
