### ISSUE TITLE
System unavailable: test-ibmcloud-ubuntu1604-x64-1 Docker daemon not running

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-infrastructure#1751]
Node: https://ci.adoptopenjdk.net/computer/test-ibmcloud-ubuntu1604-x64-1/

https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/5265/console
```
09:12:31       [exec] Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

**Comment by Willsparker** [comment]
@sxa `ssh`ing to it times out, are you able to connect to it?

**Comment by sxa** [comment]
No issues connecting at all. Restarted with `service docker stop; service docker start` an all looks good
