### ISSUE TITLE
build-godaddy-win2016-x64-1 missing /cygdrive/c/openjdk/OpenSSL-1.1.1i-x86_64-VS2017

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-infrastructure#1763]
Node https://ci.adoptopenjdk.net/computer/build-godaddy-win2016-x64-1
does not have the latest required openssl:
/cygdrive/c/openjdk/OpenSSL-1.1.1i-x86_64-VS2017

**Comment by Willsparker** [comment]
Putting it on now :-) Shouldn't take too long

**Comment by Willsparker** [comment]
Alright, they should all be installed now. Closing
