### ISSUE TITLE
System unavailable: Jenkins agent failed on build-scaleway-ubuntu1604-armv7-2

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-infrastructure#1764]
Agent won't start on https://ci.adoptopenjdk.net/computer/build-scaleway-ubuntu1604-armv7-2/log
machine not contactable

**Comment by sxa** [comment]
Rebooted and back online https://ci.adoptopenjdk.net/computer/build-scaleway-ubuntu1604-armv7-2/
