### ISSUE TITLE
Nagios: Create user logins for whoever needs access to view Nagios

### ISSUE THREAD

**Issue by Willsparker** [AdoptOpenJDK/openjdk-infrastructure#1768]
I thought it better to just create an issue to determine who wants access to Nagios. If not for anything else, it promotes the active use of Nagios :-)

Unfortunately I made a mistake when creating a user for @adamfarley, in which I used the `-c` option with `htpasswd`, so a new file was created, and the old one lost, so anyone that did have access now does not. I've remade the `nagiosadmin` user with the password it used to have, and it appears to function as it did before, so I think the only lost things were the other user logins. Currently the only logins are Adam's & nagiosAdmin.

I'll create any new logins with the process listed here: https://www.ibm.com/support/knowledgecenter/en/POWER8/p8ef9/p8ef9_ppim_nagios_userid.htm ( and NOT use the `-c` option )

I'll use LastPass to create the passwords, and I'll probably just use the GitHub usernames as usernames, for ease :-)

**Comment by andrew-m-leonard** [comment]
Hi @Willsparker , please can you create me an account, thanks

**Comment by smlambert** [comment]
Please add me as well, thanks!

**Comment by karianna** [comment]
Yes please (any chance Nagios has a GitHub auth plugin?)

**Comment by Willsparker** [comment]
> (any chance Nagios has a GitHub auth plugin?)

As far as I can google in a short time span, there doesn't appear to be, no :/

**Comment by aahlenst** [comment]
@karianna Nagios is very barebones in that regard. Icinga2, a Nagios fork, offers significantly more in that area (and not only there), but no OAuth2 support either. The usual workaround is to delegate to the webserver. https://www.nginx.com/blog/validating-oauth-2-0-access-tokens-nginx/ explains how to do it with nginx. However, I would *not delegate to GitHub*, but to something that allows us to centrally manage (and revoke) group membership, for example Azure AD. Azure AD is compatible with Icinga2 and would allow us to enforce 2FA across all services, including Jenkins.

**Comment by Willsparker** [comment]
All users have been created, and messaged on Slack. I've also written a small overview in the Wiki: https://github.com/AdoptOpenJDK/openjdk-infrastructure/wiki/Overview-of-Nagios 

Closing Issue! If anyone else wants one, Create a new issue, much like a request for access to a machine! :-)
