### ISSUE TITLE
Decomission GoDaddy servers

### ISSUE THREAD

**Issue by sxa** [AdoptOpenJDK/openjdk-infrastructure#1781]
We expect to be shortly losing our machines hosted with godaddy. I am doing some initial experimentation by marking the test machines offline hosted with them with a `-3` or `-4` suffix to see what the impact on pipeline execution time is overnight. Windows and Linux/x64 are generally good for capacity so I do not expect these to become a limiting factor. If this is ok then I'll look at dropping the `-2` machines too.

Full list of systems that will be affected (checks in the boxes mean they are now offline)

- [x] infra-ubuntu1604-x64-1 (git-hg mirroring system)
- [x] [build-rhel7-x64-1](https://ci.adoptopenjdk.net/computer/build-godaddy-rhel7-x64-1/) Was GAO - now used for javafutures - testing with [build-scaleway-ubuntu1604-x64-1](https://ci.adoptopenjdk.net/computer/build-scaleway-ubuntu1604-x64-1/configure)
- [x] [build-ubuntu1604-x64-1](https://ci.adoptopenjdk.net/computer/build-godaddy-rhel7-x64-1/) `fpm&&ubuntu` for packaging ([dup of scaleway](https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1577#issuecomment-740114174) so marking offline)
- [x] [docker-godaddy-ubuntu1604-x64-1](https://ci.adoptopenjdk.net/computer/docker-godaddy-ubuntu1604-x64-1/) No tags so likely unused - marking offline
- [x] test-centos7-x64-1 up to 4
- [x] test-debian8-x64-1 up to 4
- [x] test-ubuntu1604-1 up to 4
- [x] win2016-x64-1 up to 4 (Decomissioning 3&4 generates 4hr queues)
- [x] infra-godaddy-ubuntu1604-x64-2 / bastillion (now migrated) and jumpbox
- [ ] build-godaddy-win2016-x64- (244.75 - Win/aarch64 build)

And these ones which may I believe are not in use:

- [ ] trss.adoptopenjdk.net (OLD, unused? 246.241)
- [x] infra-godaddy-ubuntu1604-x64-3 (ERROR)
- [x] infra-godaddy-awx (Not used - 250.8)
- [x] test-godaddy-ubuntu2004-x64- (246.136)
- [x] test-godaddy-ubuntu2004-x64- (yes same name as above - 198.12.226.105)
- [x] test-godaddy-ubuntu2004-x64-3 (148.66.132.244)
- [x] [build-godaddy-ubuntu1604-x64-1](https://ci.adoptopenjdk.net/computer/build-godaddy-ubuntu1604-x64-1) (254.64) (Marked offline until I know if it is still required for anything)
- [x] infra-will-centos-x64- (253.143)
- [x] infra-will-ubuntu-x64- (253.133)
- [ ] test-msi-install (246.82)
- [ ] gdams-test-docker (252.27)
- [x] sxacross-godaddy-debian8-x86- (160.153.249.78)

**Comment by sxa** [comment]
Have marked all windows test machines offline to test the impact of losing them

**Comment by aahlenst** [comment]
Before moving bastillion, we have to be sure that all firewall rules are updated so that we don't shut us out. Apart from that it would be great if we could move everything to the final destination for Adoptium.

**Comment by sxa** [comment]
**infra-godaddy-ubuntu1604-x64-2 (bastillion)** has been migrated to a digitalocean host (but as per Andreas' comments we need to do an update before shutting down the old server
**
**infra-ubuntu1604-x64-1** (git mirror) has been brought up on an AWS system which we already had but it was never activated in production. Testing with [8](https://ci.adoptopenjdk.net/view/git-mirrors/job/git-mirrors/job/git-hg-jdk8u/982/console), [11](https://ci.adoptopenjdk.net/view/git-mirrors/job/git-mirrors/job/git-hg-jdk11u/873/console), and a [skara](https://ci.adoptopenjdk.net/view/git-mirrors/job/git-mirrors/job/git-skara-jdk/3555/console) job

**Comment by sxa** [comment]
In order to test a way of increasing capacity, I have provisioned a new 24-core Linux/x64 system and am trialling running it with multiple docker containers (each limited to 4 CPU/6Gb to stop the system test suites taking over) that can be used for building or running tests. These are defined with various suffices on https://ci.adoptopenjdk.net/computer/docker-packet-ubuntu2004-x64-1 (suffix indicates the OS, the host/kernel is Ubuntu 20.04). I've left it running for tonight's pipelines after disabling most of the godaddy xLinux test systems, so that should show us how well it copes. At the time of writing (during the JDK8 pipelines) it's running with a load of about 30 (3 of the images are actively using 4 full CPUs) and using about 10Gb of RAM.

**Comment by aahlenst** [comment]
You can go ahead from my side and remove the old bastillion machine.
