### ISSUE TITLE
System unavailable: Multiple windows test systems

### ISSUE THREAD

**Issue by sxa** [AdoptOpenJDK/openjdk-infrastructure#1783]
- All softlayer and azure test machines in https://ci.adoptopenjdk.net/label/ci.role.test&&hw.arch.x86&&sw.os.windows/ should be live but some are not currently connected to jenkins, which is impacting throughput

**Comment by Willsparker** [comment]
For now, the only ones disconnected are the ones that you have marked as disconnected to verify testing capacity. Also, I assume you mean `ibmcloud`, not `softlayer` ?

**Comment by Willsparker** [comment]
The only ones disconnected from that tag are the go-daddy ones that are being decommissioned (#1781), so I'm going to close this issue
