### ISSUE TITLE
build-scaleway-ubuntu1604-armv7-2 does not have enough space for all cached repos

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-infrastructure#1795]
https://ci.adoptopenjdk.net/computer/build-scaleway-ubuntu1604-armv7-2/
runs out of space once all openjdk repos are cached on it
I have cleared the builds-scripts workspace to free it up for the moment...

Also same on machine https://ci.adoptopenjdk.net/computer/build-scaleway-ubuntu1604-armv7-1/

**Comment by sxa** [comment]
They cannot be increased. This will be resolved once we move the build boxes to our new ARM systems.
