### ISSUE TITLE
Ansible request for Dragonwell JDK8 boot JDK on Windows

### ISSUE THREAD

**Issue by sxa** [AdoptOpenJDK/openjdk-infrastructure#1813]
https://github.com/AdoptOpenJDK/openjdk-build/pull/2354 was put in to mitigate the fact that only the alibaba machiens can currently run the Dragonwell builds. This should not be the case - all machines should be able to run any builds, so we need to resolve the underlying problem that was resolved by that PR, and then revert it

**Comment by Willsparker** [comment]
with #1727 , this shouldn't be too difficult :-)

**Comment by Willsparker** [comment]
- [ ] build-azure-win2012r2-x64-1
- [ ] build-azure-win2012r2-x64-2
- [ ] build-ibmcloud-win2012r2-x64-1
- [ ] build-ibmcloud-win2012r2-x64-2

**Comment by Willsparker** [comment]
I think that's all the build machines (except the Alibaba ones, which already have it). Closing issue :-)
