### ISSUE TITLE
System unavailable: infra-vagrant-1 - VPC unable to run `ansible-playbook`

### ISSUE THREAD

**Issue by sxa** [AdoptOpenJDK/openjdk-infrastructure#1814]
- Please put the system name in the title of this issue.

- Link to any log file showing the problem: [Windows](https://ci.adoptopenjdk.net/job/VagrantPlaybookCheck/OS=Win2012,label=vagrant/), [CentOS6](https://ci.adoptopenjdk.net/job/VagrantPlaybookCheck/OS=CentOS6,label=vagrant/983/console), [Ubuntu18.04 ](https://ci.adoptopenjdk.net/job/VagrantPlaybookCheck/OS=Ubuntu1804,label=vagrant/984/console)

- Please describe the issue:
Host system was rebooted recently so that may have impacted things. I also did some apt updates yesterday. All runs have this line:

```
       ./vagrantPlaybookCheck.sh: line 243: ansible-playbook: command not found
```

**Comment by Willsparker** [comment]
This is presumably to do with the restart I had to do yesterday (see: #1804 ). On my machine, `ansible` is at `/usr/local/bin/ansible` , but it isn't on this machine. I thought that the restart would have just reset the $PATH variable, but I can't find the installation of it anywhere.. 
I can however, find the `requests-credssp` pip module that's required for running ansible on windows machines, in `/usr/local/lib/python2.7/dist-packages/` - despite `pip` not being installed. It's almost as if the restart just uninstalled pip and ansible...

When I try running `apt install ansible`, It wants to remove `virtualbox-6.0` for some reason. It also lists `python2.7` in the install list, where, it's already installed...

**Comment by Willsparker** [comment]
Upon inspection, the `ansible` that is being attempted to be installed is from the `http://ftp.uk.debian.org/debian sid/main amd64 Packages` repository, at version `2.9.16+dfsg-1`. However, we can force `apt` to install the one from `http://ppa.launchpad.net/ansible/ansible/ubuntu bionic/main amd64 Packages` , which is broadly the same version : `2.9.16-1ppa~bionic`. This, for some reason, doesn't insist on removing `virtualbox-6.0`, so I've installed that, and the `ansible` and `ansible-playbook` commands are there.
Just running through VPC to make sure there's no additional setup required (Here: https://ci.adoptopenjdk.net/job/VagrantPlaybookCheck/985/ )

**Comment by Willsparker** [comment]
Ah, it's repeating the same issue as : #1804 
Great ...

**Comment by Willsparker** [comment]
Well, what this particular issue was looking at is fixed, so I'm going to close this one, and reopen #1804
