### ISSUE TITLE
build-osuosl-aix71-ppc64-1: execrset: 1480-318 The requested operation is not permitted

### ISSUE THREAD

**Issue by lumpfish** [AdoptOpenJDK/openjdk-infrastructure#1816]
sanity.functional test test cmdLineTester_pltest_numcpus_bound_aix_0 fails on `build-osuosl-aix71-ppc64-1` because the execrset command appears not to complete successfully owing to a permissions issue.

The test runs successfully on `test-osuosl-aix72-ppc64-2` (https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_sanity.functional_ppc64_aix/102/consoleFull).

Output from failing test (in https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_sanity.functional_ppc64_aix/104/consoleFull):
```
20:42:59  ===============================================
20:42:59  Running test cmdLineTester_pltest_numcpus_bound_aix_0 ...
20:42:59  ===============================================
20:42:59  cmdLineTester_pltest_numcpus_bound_aix_0 Start Time: Wed Jan  6 12:42:47 2021 Epoch Time (ms): 1609965767824
20:42:59  "/home/jenkins/workspace/Test_openjdk8_j9_sanity.functional_ppc64_aix/openjdkbinary/j2sdk-image/bin/java" -Xshareclasses:destroyAll; "/home/jenkins/workspace/Test_openjdk8_j9_sanity.functional_ppc64_aix/openjdkbinary/j2sdk-image/bin/java" -Xshareclasses:groupAccess,destroyAll; echo "cache cleanup done";
20:42:59  JVMSHRC005I No shared class caches available
20:43:00  JVMSHRC005I No shared class caches available
20:43:00  cache cleanup done
20:43:00  variation: NoOptions
20:43:00  JVM_OPTIONS:  
20:43:00  { itercnt=1; \
20:43:00  mkdir -p "/home/jenkins/workspace/Test_openjdk8_j9_sanity.functional_ppc64_aix/openjdk-tests/TKG/../TKG/test_output_16099615156850/cmdLineTester_pltest_numcpus_bound_aix_0"; \
20:43:00  cd "/home/jenkins/workspace/Test_openjdk8_j9_sanity.functional_ppc64_aix/openjdk-tests/TKG/../TKG/test_output_16099615156850/cmdLineTester_pltest_numcpus_bound_aix_0"; \
20:43:00  export LIBPATH="/home/jenkins/workspace/Test_openjdk8_j9_sanity.functional_ppc64_aix/openjdkbinary/openjdk-test-image/openj9:/home/jenkins/workspace/Test_openjdk8_j9_sanity.functional_ppc64_aix/openjdkbinary/j2sdk-image/jre/bin/../lib/ppc64/compressedrefs:/home/jenkins/workspace/Test_openjdk8_j9_sanity.functional_ppc64_aix/openjdkbinary/j2sdk-image/jre/bin/../lib/ppc64/j9vm:"; \
20:43:00  "/home/jenkins/workspace/Test_openjdk8_j9_sanity.functional_ppc64_aix/openjdkbinary/j2sdk-image/bin/java"   -DRESOURCES_DIR="/home/jenkins/workspace/Test_openjdk8_j9_sanity.functional_ppc64_aix/openjdk-tests/TKG/../../jvmtest/TestConfig/resources" -DJVM_TEST_ROOT="/home/jenkins/workspace/Test_openjdk8_j9_sanity.functional_ppc64_aix/openjdk-tests/TKG/../../jvmtest" \
20:43:00  -DEXE='execrset -c 1 -e /home/jenkins/workspace/Test_openjdk8_j9_sanity.functional_ppc64_aix/openjdkbinary/openjdk-test-image/openj9/pltest -include:j9numcpus -boundcpus:1  ' -jar "/home/jenkins/workspace/Test_openjdk8_j9_sanity.functional_ppc64_aix/openjdk-tests/TKG/../../jvmtest/functional/cmdline_options_tester/cmdlinetester.jar" \
20:43:00  -config "/home/jenkins/workspace/Test_openjdk8_j9_sanity.functional_ppc64_aix/openjdk-tests/TKG/../../jvmtest/functional/cmdLineTests/pltest/pltest_numcpus_bound.xml" -verbose -explainExcludes \
20:43:00  -xids all,aix_ppc-64_cr, -plats all,aix_ppc-64_cr, -nonZeroExitWhenError; \
20:43:00  if [ $? -eq 0 ] ; then echo ""; echo "cmdLineTester_pltest_numcpus_bound_aix_0""_PASSED"; echo ""; cd /home/jenkins/workspace/Test_openjdk8_j9_sanity.functional_ppc64_aix/openjdk-tests/TKG/..;  else echo ""; echo "cmdLineTester_pltest_numcpus_bound_aix_0""_FAILED"; echo ""; fi; } 2>&1 | tee -a "/home/jenkins/workspace/Test_openjdk8_j9_sanity.functional_ppc64_aix/openjdk-tests/TKG/../TKG/test_output_16099615156850/TestTargetResult";
20:43:00  *** Starting test suite: J9 Command-Line Option Test for pltest ***
20:43:00  Testing: PLTEST
20:43:00  Test start time: 2021/01/06 12:42:48 Pacific Standard Time
20:43:00  Running command: execrset -c 1 -e /home/jenkins/workspace/Test_openjdk8_j9_sanity.functional_ppc64_aix/openjdkbinary/openjdk-test-image/openj9/pltest -include:j9numcpus -boundcpus:1  
20:43:00  Time spent starting: 70 milliseconds
20:43:00  Time spent executing: 83 milliseconds
20:43:00  Test result: FAILED
20:43:00  Output from test:
20:43:00   [ERR] 1480-318 The requested operation is not permitted.
20:43:00  >> Success condition was not found: [Output match: ALL TESTS COMPLETED AND PASSED]
20:43:00  >> Failure condition was not found: [Output match: ASSERTION FAILED]
20:43:00  
20:43:00  Executing command: execrset -c 1 -e /home/jenkins/workspace/Test_openjdk8_j9_sanity.functional_ppc64_aix/openjdkbinary/openjdk-test-image/openj9/pltest -include:j9numcpus -boundcpus:1  
20:43:00  
20:43:00  
20:43:00  ---TEST RESULTS---
20:43:00  Number of PASSED tests: 0 out of 1
20:43:00  Number of FAILED tests: 1 out of 1
20:43:00  
20:43:00  ---SUMMARY OF FAILED TESTS---
20:43:00  PLTEST
20:43:00  -----------------------------
20:43:00  
20:43:00  
20:43:00  cmdLineTester_pltest_numcpus_bound_aix_0_FAILED
```

**Comment by sxa** [comment]
As per @lumpfish 's recommendation to me thids morning I have removed the `ci.role.test` label from [build-osuosl-aix71-ppc64-1](https://ci.adoptopenjdk.net/computer/build-osuosl-aix71-ppc64-1/) for now on the basis that there seems to be multiple issues relating to test runs on this particular box (Might be useful to have them all tied together by linking them in this issue)

**Comment by aixtools** [comment]
How difficult is it to get a node into a situation that this test can be run manually?

**Comment by aixtools** [comment]
one issue: https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1808 - but this was fine shortly before that. I am not able to find the error text posted - everything in the console output is after 06:00:00 while the ERR: text is between 03:40:00 and 03:45:00

Other issues related to AIX - not just this system - I worked on today are:
 - #1758, and made a quick fix:
 - #929 , I cleaned up /tmp on all AIX systems and made some additions to crontab to keep it clean. Likely a new issue should be made to figure out why these temporary files are being left behind.

As #1758 was working fine the day before - not running the tests makes it quite hard to figure out what is causing the different behavior. The two build-aix71 and two test-aix72 servers are intended to be identical pairs.

I have no idea what the benefit or hurt is to having the ci.role.test turned on or not.

iirc: the only two issues related to **build-aix71** are the two issues above. The other issues are supposedly resolved (offline, CPAN not working) - or not related to the build-aix71 systems.

**Comment by sxa** [comment]
Running on https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_sanity.functional_ppc64_aix/ to replicate/verify on the affected machine

**Comment by sxa** [comment]
Seemed to repliate in that run.

Now re-running via [a Grinder](https://ci.adoptopenjdk.net/job/Grinder/5998/) job which will hopefully retain the workspace for ease of reproduction/debugging - as @aixtools says it's rather hard to figure out what the issue is from this since the `pltest` tool is in the workspace and therefore cleared after the job is complete.

**Comment by sxa** [comment]
@smlambert @lumpfish  According to the Grinder log above:
```
16:32:12  Executing command: execrset -c 1 -e /home/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image/../native-test-libs//pltest -include:j9numcpus -boundcpus:1  
16:32:12  
16:32:12  
16:32:12  ---TEST RESULTS---
16:32:12  Number of PASSED tests: 0 out of 1
16:32:12  Number of FAILED tests: 1 out of 1
16:32:12  
16:32:12  ---SUMMARY OF FAILED TESTS---
```
it's pointing at `pltest` but the location that is in the log does not appear to exist. Is it getting cleaned out even if `KEEP_WORKSPACE` is checked?

**Comment by lumpfish** [comment]
I don't know why `KEEP_WORKSPACE` would not do as it says, sorry.
Regarding the test itself, I believe it needs the native test libraries which are created as part of the jdk build.   Unfortunately for these situations they have to be supplied as a 'customised' sdk (jdk.tar + test-image.tar (+ debugimage.tar) in the grinder from a build - e.g. here: https://github.com/AdoptOpenJDK/openjdk8-binaries/releases
(The `native-test-libs//pltest` in th epath should be `openjdk-test-image/openj9/pltest`.  I don't think that affects the ability to execute the `execrset` command though.

**Comment by smlambert** [comment]
https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1816#issuecomment-763026344 is correct in assumption that if pulling from API (SDK_RESOURCE=nightly or releases), all 3 artifacts (jdk/testimage/debugimage are present and downloaded to test machine).  

For native test like pltest, native test image is required and must be passed to test pipeline explicitly in SDK_RESOURCE=customized case.  If your tests do not require the artifacts, you can deselect TEST_IMAGES_REQUIRED/DEBUG_IMAGES_REQUIRED accordingly. 

<img width="1219" alt="Screen Shot 2021-01-19 at 1 42 40 PM" src="https://user-images.githubusercontent.com/2836948/105078594-3a81ac80-5a5c-11eb-9d22-7e486b3dad3e.png">

**Comment by sxa** [comment]
> For native test like pltest, native test image is required and must be passed to test pipeline explicitly in SDK_RESOURCE=customized case. If your tests do not require the artifacts, you can deselect TEST_IMAGES_REQUIRED/DEBUG_IMAGES_REQUIRED accordingly.

I'mn noit sure how to translate that into my scenario. I don't know if the `pltest` was present when the Grinder was there, only that it failed, and when I went back onto the machine it's not there even with the `KEEP_WORKSPACE` option. It sounds like I've done the right thing and all artefacts will have been pulled across correctly since I'm not using `customized`. What am I missing?

**Comment by lumpfish** [comment]
> [#1816 (comment)](https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1816#issuecomment-763026344) is correct in assumption that if pulling from API (SDK_RESOURCE=nightly or releases), all 3 artifacts (jdk/testimage/debugimage are present and downloaded to test machine)

That's not actually what I meant - I meant to say that in a Grinder all three URLs must be supplied when a native test case is being executed for any SDK_RESOURCE type.  That is my observation anyway - the only time I've seen the test-image and debugimage downloads pulled automatically is in a pipeline, when the SDK_RESOURCE is 'upstream'.  You then see output like:
```
19:45:59  + ./openjdk-tests/get.sh -s /home/jenkins/workspace/Test_openjdk8_j9_sanity.functional_ppc64_aix -t /home/jenkins/workspace/Test_openjdk8_j9_sanity.functional_ppc64_aix/openjdk-tests -p ppc64_aix -r upstream -j 8 -i openj9 --openj9_repo https://github.com/eclipse/openj9.git --openj9_branch master --tkg_repo https://github.com/AdoptOpenJDK/TKG.git --tkg_branch master
19:45:59  TESTDIR: /home/jenkins/workspace/Test_openjdk8_j9_sanity.functional_ppc64_aix/openjdk-tests
19:45:59  get jdk binary...
19:45:59  --sdkdir is set to upstream. Therefore, skip download jdk binary
19:45:59  unzip file: OpenJDK8U-jdk_ppc64_aix_openj9_2021-01-18-18-05.tar.gz ...
19:46:02  unzip file: OpenJDK8U-jre_ppc64_aix_openj9_2021-01-18-18-05.tar.gz ...
19:46:03  unzip file: OpenJDK8U-testimage_ppc64_aix_openj9_2021-01-18-18-05.tar.gz ...
19:46:03  unzip OpenJDK8U-debugimage_ppc64_aix_openj9_2021-01-18-18-05.tar.gz in ./j2sdk-image/jre...
19:46:05  Run /home/jenkins/workspace/Test_openjdk8_j9_sanity.functional_ppc64_aix/openjdkbinary/j2sdk-image/bin/java -version
```

In @sxa 's job (SDK_RESOURCE=nightly) this is the equivalent part of the execution, where only the JDK is downloaded even though the TEST_IMAGES_REQUIRED is ticked.
```
16:33:07  + ./openjdk-tests/get.sh -s /home/jenkins/workspace/Grinder -t /home/jenkins/workspace/Grinder/openjdk-tests -p ppc64_aix -r nightly -j 8 -i openj9 --openj9_repo https://github.com/eclipse/openj9.git --openj9_branch master --tkg_repo https://github.com/AdoptOpenJDK/TKG.git --tkg_branch master
16:33:07  TESTDIR: /home/jenkins/workspace/Grinder/openjdk-tests
16:33:07  get jdk binary...
16:33:07  _ENCODE_FILE_NEW=UNTAGGED curl -OLJSks  https://api.adoptopenjdk.net/v3/binary/latest/8/ea/aix/ppc64/jdk/openj9/normal/adoptopenjdk
16:33:38  unzip file: OpenJDK8U-jdk_ppc64_aix_openj9_2021-01-18-08-38.tar.gz ...
16:33:40  Run /home/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image/bin/java -version
```
So if SDK_RESOURCE=nightly is supposed to automatically get the test-image and debugimage files then there may be something which needs fixing.

Anyway, getting the test-image is what is required to get the test executing as it should, but @sxa 's question was actually about KEEP_WORKSPACE which seems to be not working (or not understood).

**Comment by sxa** [comment]
@smlambert Any idea why this isn't working? i'm using `nightly` so based on your comments there shouldn't be a problem - but I can't see what I can do to get visibility of the `pltest` tool that is required to debug this on the system - any advice?

**Comment by aixtools** [comment]
Reading - but not commenting.

@sxa - would it be an idea to keep the current image as a backup and just rebuild and reconfigure `build-osuosl-aix71-ppc64-1`. As there have been many changes to the playbook since these systems were first released. Start clean (AIX, ie, platform wise).

**Comment by aixtools** [comment]
Something I just noticed - files are deleted - but not removed - notice the change in filesystem free space after running `slibclean` (shared library clean)

```
# df -g /home
Filesystem    GB blocks      Free %Used    Iused %Iused Mounted on
/dev/hd1         108.00     75.64   30%   293939     2% /home
# slibclean
# df -g /home
Filesystem    GB blocks      Free %Used    Iused %Iused Mounted on
/dev/hd1         108.00     96.35   11%   287032     2% /home
```

Also, I have been trying to compare test-osuosl-aix71-ppc64-* with build-osuosl-aix71-ppc64-*

The build systems are at a different TL level:

```# oslevel -s -q | head -3
Known Service Packs
-------------------
7100-04-04-1717
7100-04-03-1642
7100-04-02-1614
# oslevel -s
7100-04-04-1717
```
than the test systems:
```root@p9-aix1-ojdk05:[/root]oslevel -s -q | head -3
Known Service Packs
-------------------
7100-05-06-2028
7100-05-06-2016
7100-05-06-2015
root@p9-aix1-ojdk05:[/root]oslevel -s
7100-05-02-1832
root@p9-aix1-ojdk05:[/root]oslevel -s -l 7100-05-06-2028
Fileset                                 Actual Level       Service Pack Level
-----------------------------------------------------------------------------
X11.vfb                                 7.1.3.0            7.1.5.30
```

Should, perhaps, the build* systems be updated - at least to a later 7100-04 level?

Note: this may require a re-install, as some of the core AIX tools are `broken` by the way the system has been managed (months ago I tried to update the OS but that fails).

**Comment by aixtools** [comment]
@lumpfish - Could you please try and recreate this? I still do not follow all the comments re: instructions on how to recreate.

**Comment by lumpfish** [comment]
I've rerun the whole sanity.functional test target on build-osuosl-aix71-ppc64-1 here: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/216/console.  Everything passed.

**Comment by aixtools** [comment]
I'll give you the honor of the 'close'

**Comment by lumpfish** [comment]
All sanity.functional tests pass on build-osuosl-aix71-ppc64-1 now, closing.
