### ISSUE TITLE
Add Ramdisk configuration to AIX ansible scripts

### ISSUE THREAD

**Issue by karianna** [AdoptOpenJDK/openjdk-infrastructure#182]
see #118 and #44

**Comment by sxa555** [comment]
@CJKwork I thought this was already done somewhere but it's still open ... Either way the AIX ansible scripts could do with being checked over. Give me a shout if you need a box to play with and don't have any available

**Comment by CJKwork** [comment]
Adding this as a cross-ref:
https://github.com/nodejs/build/issues/661

**Comment by CJKwork** [comment]
Pull request 
https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/568
for this issue.
