### ISSUE TITLE
Ansible request for Sles12sp5 update to playbook and missing systemtap-sdt-devel 

### ISSUE THREAD

**Issue by sej-jackson** [AdoptOpenJDK/openjdk-infrastructure#1820]
Please put the name of the software product (and affected platforms if relevant) in the title of this issue

- [ ] Missing install
- [x] Bug in ansible playbook
- [ ] Request for new playbook addition

Details:
Not so much a bug per se, but things have changed and the playbook won't currently run on Sles12 because the `zypper_repository` task in `roles/Common/tasks/SLES.yml` is looking for `https://download.opensuse.org/repositories/devel:/tools/SLE_12_SP4/`, which no longer exists, and only `SLE_12_SP5` is still available for Sles12.

However, once this is changed to be `SLE_12_SP5`, it then fails to install `systemtap-sdt-devel` because this package has now disappeared from `SLE_12_SP5` (although according to #1033, it was present in `SLE_12_SP4`).  

It is still present in the SLES15 repositories, so my current plan is to remove the package from the `Build_Tool_Packages` list in `roles/Common/vars/SLES.yml` and move it to `Additional_Build_Tools_SLES15` instead. 

I've been unable to find why the package has been removed though, and whether it's now available elsewhere or should be replaced with somewhere else, so could do with some advice on whether any further handling is required please.

**Comment by Willsparker** [comment]
https://sourceware.org/systemtap/

As far as I know, `systemtap-sdt-devel` isn't necessary to the building of JDKs (can you confirm, @sxa?) It appears to just be a debugging tool, which, while probably useful, isn't the be all and end all. 

Looking at the `inventory.yml` and https://ci.adoptopenjdk.net/computer/ , we appear to only have 1 SLES12 s390x machine ( https://ci.adoptopenjdk.net/computer/test-marist-sles12-s390x-1/ ), and we don't test for it in `VPC` - we used to test for openSUSE 12.3, but that was removed for some reason that I can't find right now :-)

**Comment by Willsparker** [comment]
Fixed as of #1823
