### ISSUE TITLE
Disable Monitor_AIX_ramdisks test (https://ci.adoptopenjdk.net/job/Monitor_AIX_ramdisks/)

### ISSUE THREAD

**Issue by aixtools** [AdoptOpenJDK/openjdk-infrastructure#1822]
Please set the title to indicate the test name and machine name where known.

To make it easy for the infrastructure team to repeat and diagnose, please
answer the following questions:

- test suite/name?
 As I cannot see the contents of the test I can not establish if the test name, or test content is wrong. Assuming the test is only checking for the existence of /ramdisk - the test is no longer needed. The AIX configuration has been modified so that a RAM disk is no longer needed.
- Is there an existing issue elsewhere covering this?
 Not to my knowledge. There are other AIX issues - and this test failure is, imho, additional noise.
- Which machine(s) does it work on?
 None: /ramdisk is no longer part of the AIX configuration
- Which machine(s) does it fail on?
 ALL - see above
- Do you have a link to a Grinder re-run if the test with the failure?

Any other details:
The last `success` nearly 6 months ago: https://ci.adoptopenjdk.net/job/Monitor_AIX_ramdisks/469/console
The last run: https://ci.adoptopenjdk.net/job/Monitor_AIX_ramdisks/591/console
```
Started by timer
Running as SYSTEM
Building on master in workspace /home/jenkins/.jenkins/workspace/Monitor_AIX_ramdisks
Triggering Monitor_AIX_ramdisks » build-osuosl-aix71-ppc64-2
Triggering Monitor_AIX_ramdisks » build-osuosl-aix71-ppc64-1
Monitor_AIX_ramdisks » build-osuosl-aix71-ppc64-2 completed with result FAILURE
Monitor_AIX_ramdisks » build-osuosl-aix71-ppc64-1 completed with result FAILURE
Finished: FAILURE
```

**Comment by sxa** [comment]
Thanks for raising this - I've disabled it now :-)
