### ISSUE TITLE
test-ibmcloud-win2012r2-x64-1 has hung Java processes

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-infrastructure#1824]
https://ci.adoptopenjdk.net/view/Failing%20Test%20Jobs/job/Test_openjdk8_hs_extended.openjdk_x86-64_windows/18/consoleFull
https://ci.adoptopenjdk.net/computer/test-ibmcloud-win2012r2-x64-1/
```
12:32:39     Id ProcessName StartTime             
12:32:39     -- ----------- ---------             
12:32:39   1820 java        10/21/2020 2:11:30 PM 
12:32:39   7336 java        10/21/2020 1:22:02 PM 
12:32:39   7908 java        10/22/2020 11:05:38 AM
12:32:39   8412 java        10/21/2020 1:06:02 PM 
12:32:39   9468 java        10/22/2020 10:49:37 AM
12:32:39   9532 java        10/22/2020 12:37:14 PM
12:32:39   9732 java        1/7/2021 6:08:15 AM   
12:32:39  12496 java        10/22/2020 11:23:13 AM
12:32:39  13840 java        10/22/2020 12:39:18 PM
12:32:39  13844 java        10/21/2020 1:55:06 PM 
12:32:39  14436 java        10/22/2020 10:33:37 AM
12:32:39  16552 java        10/21/2020 1:38:11 PM 
12:32:39  19796 java        10/21/2020 1:38:22 PM 
```

**Comment by Willsparker** [comment]
I thought that the changes that were made (i.e. https://github.com/AdoptOpenJDK/openjdk-tests/pull/2059 ), were meant to stop those processes? Manually fixing them now.

**Comment by andrew-m-leonard** [comment]
@Willsparker that logic won't do a kill -9, it also only kills processes spawned during the job, these are from back last October!

**Comment by Willsparker** [comment]
Oh gosh, okay! Yeah, I just read the log :-)

**Comment by Willsparker** [comment]
Alright, that's cleared up.

For future reference (primarily for me), if manual clean up is required, the powershell command `Get-Process java | select id,path` will list all the process IDs and their paths - any process running on the System Java is the Jenkins Agent, any others can be killed (via PS, or Resource Monitor). This only works with Admin privileges though (hence why we don't do that in tests).
