### ISSUE TITLE
Docs: Update Wiki docs section of Nagios

### ISSUE THREAD

**Issue by Willsparker** [AdoptOpenJDK/openjdk-infrastructure#1826]
Requested by @sxa , and I don't think it's a bad idea to go through and keep them updated if we intend to use them from now on :-)

**Comment by Willsparker** [comment]
Looking at the current docs, there's a lot of it talking about manual setup - which we aren't really using due to the [Nagios_Ansible_Config_Tool](https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/master/ansible/playbooks/Supporting_Scripts/Nagios_Ansible_Config_tool/Nagios_Ansible_Config_tool.sh) . I don't think all of it is irrelevant, but it does need looking at to determine what's still needed. I'm going to make a separate folder that talks about manual setup

**Comment by Willsparker** [comment]
I've currently got a WIP version of a document speaking specifically about the Manual setup of a Nagios client, which should encompass most (if not all) of the old document's information. From here, I'll double check if there's any missing info that could be written up.

**Comment by Willsparker** [comment]
Backup of the Old Docs : 

[old_Nagios_docs.tar.gz](https://github.com/AdoptOpenJDK/openjdk-infrastructure/files/5801970/old_Nagios_docs.tar.gz)

**Comment by Willsparker** [comment]
The doc regarding the manual setup of the machines has been completed: https://github.com/AdoptOpenJDK/openjdk-infrastructure/wiki/Manual-Setup-of-a-Nagios-Monitored-Machine#manual-setup-for-nagios-clients

**Comment by Willsparker** [comment]
That doc should encompass everything from the old docs, so I'm going to delete the pages from the Wiki. The backups are still in this issue if we want to reinstate them for any reason :-)

**Comment by Willsparker** [comment]
I've updated the 'Home' of the wiki to fix the missing pages links. I've also updated the `Monitoring-Additional-Services` page to correct links and make the layout more cohesive: https://github.com/AdoptOpenJDK/openjdk-infrastructure/wiki/Nagios%3A-Monitoring-Additional-Services

I think that's all the information I have for Nagios down, so, closing issue!

**Comment by sxa** [comment]
LGTM thanks - we might have to do a little more in terms of (a) ensuring we know how to remove stuff and (b) updating the [PR template](https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/master/.github/PULL_REQUEST_TEMPLATE.md) to include notes about confirming things have been added/removed as appropriate as well as bastillion

**Comment by Willsparker** [comment]
It'd be cool if we could have a more .. uh.. standardized process of removing machines, or put in some automation - At the minute, we have to manually update `inventory.yml`, Nagios, Bastillion whenever we want to remove something in Jenkins, AFAIK. I know automation of these sorts of things (i.e. removal) can be tricky though ..
