### ISSUE TITLE
testc-packet-fedora33-amd-2 : ps: command not found

### ISSUE THREAD

**Issue by lumpfish** [AdoptOpenJDK/openjdk-infrastructure#1827]
Tests are failing on testc-packet-fedora33-amd-2 with messages like:
```
12:29:11  STDERR:
12:29:11  ShellScaffold.sh: Version
12:29:11  /home/jenkins/workspace/Test_openjdk8_hs_sanity.openjdk_x86-64_linux/openjdk-tests/openjdk/openjdk-jdk/jdk/test/com/sun/jdi/ShellScaffold.sh: line 213: ps: command not found
12:29:11  --Top process (660176) is dead.  We better die too
```
Assuming we're running in a docker image which is missing `ps`?

**Comment by sxa** [comment]
WIthout seeing the log I can't tell when this occurred but as far as I can tell that system has a working `ps` on it at the moment, so I assume this is no longer an issue.

**Comment by lumpfish** [comment]
Sorry - forgot the job link: https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_sanity.openjdk_x86-64_linux/656/
9th Jan 13:14

**Comment by sxa** [comment]
I suspect it's been fixed since then, but I'm running that job again at https://ci.adoptopenjdk.net/job/Grinder/5899/console to be sure before closing

**Comment by sxa** [comment]
All passed - closing
