### ISSUE TITLE
Ansible request for GPG install before Debian apt-key task

### ISSUE THREAD

**Issue by rajdeepsingh1** [AdoptOpenJDK/openjdk-infrastructure#1828]
Please put the name of the software product (and affected platforms if relevant) in the title of this issue

- [ ] Missing install
- [X ] Bug in ansible playbook
- [ ] Request for new playbook addition

Details:

The following role breaks for non-Adopt users when trying to run:
in

ansible/playbooks/AdoptOpenJDK_Unix_Playbook/main.yml

```
TASK [Get_Vendor_Files : check out AdoptOpenJDK/secrets] ******************************************************************
fatal: [localhost -> localhost]: FAILED! => {"changed": false, "cmd": "/usr/bin/git clone --origin origin '' /tmp/openjdk-infrastructure/ansible/playbooks/AdoptOpenJDK_Unix_Playbook/vendor_files", "msg": "Cloning into '/tmp/openjdk-infrastructure/ansible/playbooks/AdoptOpenJDK_Unix_Playbook/vendor_files'...\nHost key verification failed.\r\nfatal: Could not read from remote repository.\n\nPlease make sure you have the correct access rights\nand the repository exists.", "rc": 128, "stderr": "Cloning into '/tmp/openjdk-infrastructure/ansible/playbooks/AdoptOpenJDK_Unix_Playbook/vendor_files'...\nHost key verification failed.\r\nfatal: Could not read from remote repository.\n\nPlease make sure you have the correct access rights\nand the repository exists.\n", "stderr_lines": ["Cloning into '/tmp/openjdk-infrastructure/ansible/playbooks/AdoptOpenJDK_Unix_Playbook/vendor_files'...", "Host key verification failed.", "fatal: Could not read from remote repository.", "", "Please make sure you have the correct access rights", "and the repository exists."], "stdout": "", "stdout_lines": []}
```

**Comment by Willsparker** [comment]
So, that role (and a few others) is tagged with `adoptopenjdk` (or `jenkins`) (See: https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/f61a5adcc2be6a89ddfacf469ee405b593cd12e3/ansible/playbooks/AdoptOpenJDK_Windows_Playbook/main.yml#L36 ) . Those roles should be skipped when executing the playbook as a non-Adopt users (See: https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/master/ansible/README.md#skipping-one-or-more-tags-via-cli-when-running-ansible-playbooks ), as they are specific to setting up machines specifically for AdoptOpenJDK's machine farm.

These can be skipped with `--skip-tags adoptopenjdk,jenkins` in your `ansible-playbook` command :-)

**Comment by rajdeepsingh1** [comment]
@Willsparker Thanks!

**Comment by rajdeepsingh1** [comment]
Another failure encountered:
```
TASK [Common : Add AdoptOpenJDK GPG key] ***************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed to find required executable gpg in paths: /opt/csw/bin/:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"}
```

This specific task has no tag(s) assigned to it 
- name: Add AdoptOpenJDK GPG key
- https://github.ibm.com/runtimes/infra-can/blob/4d757e5d7eb257ffc7b4b1470c38775d418d4f04/ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/Debian.yml#L19

**Comment by Willsparker** [comment]
So- looking at it, you need `gpg` installed on your machine (https://docs.ansible.com/ansible/latest/collections/ansible/builtin/apt_key_module.html#requirements). However - That really should be checked by Ansible before that task is run, so I'll put a fix in for that :-)
