### ISSUE TITLE
System unavailable: https://adoptopenjdk.jfrog.io/

### ISSUE THREAD

**Issue by Conky5** [AdoptOpenJDK/openjdk-infrastructure#1830]
- Please put the system name in the title of this issue.

- Link to any log file showing the problem:

- Please describe the issue:
Visiting https://adoptopenjdk.jfrog.io/ results in a `503 Service Temporarily Unavailable`.

From https://github.com/AdoptOpenJDK/openjdk-infrastructure/wiki/External-Services#artifactory I see this is managed by JFrog, who do appear to be experiencing an outage currently https://status.jfrog.io/, figured I would make a ticket here though for any other folks who come across this.

**Comment by aahlenst** [comment]
Seems resolved: https://status.jfrog.io/incidents/2q6k17bp6hyk.
