### ISSUE TITLE
No nodes with label: win2012&&dragonwell&&build&&windows&&x64 

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-infrastructure#1832]
Dragonwell node: https://ci.adoptopenjdk.net/computer/build-alibaba-win2012r2-x64-2/
does not have the win2012 label?

**Comment by Willsparker** [comment]
I know @Haroon-Khel & @sxa are doing work on them as part of #1818 , which may be why they are lacking tags. Previously, they weren't setup for builds that weren't Dragonwell, but I believe they are rectifying that now. See: https://adoptopenjdk.slack.com/archives/C53GHCXL4/p1610356948467700

**Comment by sxa** [comment]
It's not currently building properly, so it is correct that it gets queued up as we don't hjave anything that will build it successfully at the moment. It's being worked on.

**Comment by sxa** [comment]
https://github.com/AdoptOpenJDK/openjdk-build/pull/2376 will allow these builds to run on the existing build machines used for other variants while we resolve the issues on the AliBaba machines

**Comment by sxa** [comment]
This particular problem no longer exists, so closing ... But there is still an issue on the alibaba machines which is being worked under https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1818
