### ISSUE TITLE
System unavailable: Muliple Linux/s390x test machines at marist offline in jenkins

### ISSUE THREAD

**Issue by sxa** [AdoptOpenJDK/openjdk-infrastructure#1839]
The following machines are currnetly offline which significantly reduces our Linux/s390x testing capacity:

- https://ci.adoptopenjdk.net/computer/test-marist-ubuntu1604-s390x-2X/
- https://ci.adoptopenjdk.net/computer/test-marist-ubuntu1604-s390x-3/
- https://ci.adoptopenjdk.net/computer/test-marist-ubuntu1604-s390x-4/

![image](https://user-images.githubusercontent.com/6487691/104583646-471b9480-5659-11eb-9e34-6543deee0dfa.png)

**Comment by andrew-m-leonard** [comment]
https://ci.adoptopenjdk.net/computer/test-marist-ubuntu1604-s390x-2X/log fails with:
```
Exception in thread "main" java.io.IOException: The specified working directory should be fully accessible to the remoting executable (RWX): /home/jenkins
```

**Comment by andrew-m-leonard** [comment]
Other 2 won't re-launch, needs manual intervention

**Comment by sxa** [comment]
Not sure if anyone else did anything, but they all appear to be online this morning ... So I'll close this and we can reopen if they disappear again
