### ISSUE TITLE
Install xvfb on headless (linux) machines 

### ISSUE THREAD

**Issue by smlambert** [AdoptOpenJDK/openjdk-infrastructure#184]
1) install xvfb
Much like the jck machines have xvfb installed (https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/master/ansible/playbooks/ubuntu-jck.yml#L26), we need it to be installed on all machines.  

2) remove other x11 configuration
The other x11 server setup that is currently being done in the playbooks (https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/master/ansible/playbooks/AdoptOpenJDK_Linux_Playbook/roles/x11/tasks/main.yml) is likely not needed, unless you know of someone else using them.

It is not required to start the display as the ubuntu-jck playbook does, as we can/should control that from the Jenkinsfile.  

More details on this approach (suggested by @tellison): https://github.com/AdoptOpenJDK/openjdk-tests/issues/49#issuecomment-312652929

**Comment by sxa555** [comment]
Mac will require a different solution as I understand it. @gdams has my issue to do it for the JCK boxes (our first attempt didn't work properly) but if anyone else has experience of sensible ways of doing this they're welcome to volunteer ;-)

**Comment by sxa555** [comment]
@smlambert Do the other X packages explicitly need to be removed from the existing boxes? Or are you just asking for them to be removed from the playbook as they're not required to your knowledge?

**Comment by smlambert** [comment]
I do not believe they need to be removed from the playbook.  I mentioned it only as a code hygiene suggestion, since I am not aware of anyone who needs/depends on them.

**Comment by geraintwjones** [comment]
What is the relationship between this issue and #217?

**Comment by sxa555** [comment]
@geraintwjones Other than the query over whether it's necessary to remove any existing packages https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/217#issuecomment-365758060  there's no significant difference - the other one specifically references the playbook, I suppose you could consider this one "executing the playbook to resolve Shelley's issue" they're

**Comment by geraintwjones** [comment]
I was going to add  xorg-x11-server-Xvfb to CentOS and RedHat. However, someone's beaten me to it on RedHat, so I'll just make the CentOS change now.

**Comment by geraintwjones** [comment]
So all playbooks modified, and changes merged. Now need to run them.

**Comment by karianna** [comment]
@geraintwjones Can this be closed now?

**Comment by sxa555** [comment]
I reckon so, therefore closing :-)
