### ISSUE TITLE
System unavailable: All sparc nodes offline

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-infrastructure#1846]
https://ci.adoptopenjdk.net/label/build&&solaris&&sparcv9/

**Comment by sxa** [comment]
I don't have the contacts for this hosting provider on this one and I can't seem to connect to the host, so George will need to address this.

**Comment by gdams** [comment]
build-inspira-solaris10u11-sparcv9-2 is now online

**Comment by sxa** [comment]
LGTM
