### ISSUE TITLE
Revisit Jenkins backup

### ISSUE THREAD

**Issue by smlambert** [AdoptOpenJDK/openjdk-infrastructure#185]
Jenkins is backed up using thinBackup plugin, which does not actually restart Jenkins, but puts it into quiet mode (so no new jobs will be allowed to run).  Due to a known Jenkins issue, https://issues.jenkins-ci.org/browse/JENKINS-34256, pipeline jobs will hang when Jenkins is put into quiet mode (which is done nightly 11pm EST, or 5am in Hursley).

As we have now increased the amount of testing, the result is that we are seeing more hanging jobs (not limited to testing, but seen most often with test builds as there are so many of them).  

To mitigate the impact of this known Jenkins bug (and while we await a fix for it), there are a number of potential actions to take (in combination, if you want):

1) backup less frequently (is 1x per week sufficient?)
2) move the back up to an hour later (which indicates to be the lowest activity period of activity on the machines as per https://ci.adoptopenjdk.net/monitoring/nodes)
3) run thinBackup without putting Jenkins into quiet mode (it seems to have that option, though maybe not recommended)
4) pre-emptively kill jobs prior to running the thinBackup (I've added a job called https://ci.adoptopenjdk.net/view/work%20in%20progress/job/KillHangingBuilds/, though it needs to be updated to get all running jobs and then tested to ensure it does only what we want)
5) post-backup run of the KillHangingJobs script

**Comment by smlambert** [comment]
@geraintwjones

**Comment by smlambert** [comment]
The KillHangingJobs will kill pipeline builds prior to the backup stage, if we want to preemptively kill pipelines to avoid the hanging state (step 4 outlined above), while we wait for a fix to the Jenkins issue.

**Comment by AdamBrousseau** [comment]
Not sure all the settings you use on your ThinkBackup but I've never had the option to go into quiet mode on the Jenkins instance I manage. Never had a problem. Although I've only ever needed to look at the backup once or twice.

**Comment by smlambert** [comment]
I see that in our other Jenkins instance, we do not check that box that says wait until Jenkins is idle to perform backup.  

That would be an 'easy fix' to this issue, if it provides us with usable/suitable backups.

**Comment by smlambert** [comment]
I see that the only reason to check that box and force Jenkins into quiet mode is to ensure nothing is changed during the backup.  

"The specified cron triggers that the backup should be done. To be sure that nothing get changed during the backup Jenkins will swichted to a 'Quiet Mode' where no new jobs in the queue are handled. 
However this value in minutes specify when Jenkins get forced to the 'Quiet Mode'."

As it is highly unlikely to happen, that someone changes something (adds new build) in the few minutes every 5am that we backup, and then we do not back up that new build until the next backup 24 hrs later.  We keep 10 previous backups and backup every night, I think it is safe to uncheck that setting (of putting Jenkins into quiet mode).  We can revisit should anyone ever think we are at risk.

I will change the thinBackUp setting today and close this issue.
