### ISSUE TITLE
Allow AWX to locate private data (Vendor_FIles/secrets) required for setup

### ISSUE THREAD

**Issue by sxa** [AdoptOpenJDK/openjdk-infrastructure#1850]
Please put the name of the software product (and affected platforms if relevant) in the title of this issue

- [ ] Missing install
- [ ] Bug in ansible playbook
- [x] Request for new playbook addition

Details:
https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/1560 prevented AWX from installing using the `/Vendor_Files` directory and stops anyone who doesn't have access to the secrets repo from being able to set up a machine at adoptopenjdk. This is currently (a) undocumented and (b) Not so easy to automate securely.

My gut feel is that we should allow either the secrets repo or the `/Vendor_Files` location to be used. We could also not have the public keys requiring GPG encryption.

**Comment by Willsparker** [comment]
@gdams , could you weigh in on this? The PR @sxa linked is the one we implemented.

Regarding the automation - a very hacky workaround could be to setup the AWX server with a dummy github account that has admin access. Also, whats the issue of having `dotgpg` on AWX? 
The alternative, I suppose, is set it up so it skips `get_vendor_files` if it detects the Vendor Files.. I'll look at doing that.

**Comment by Willsparker** [comment]
Note: For this, I'm assuming that the vendor files at `/Vendor_Files` is going to be in the same format as the Vendor Files within the secrets repo, just not gpg encrypted. This will allow me to do a similar method to what this (and the task afterwards) does: https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/92bb453988ca77e13250883c35910ba4fcfe236b/ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Get_Vendor_Files/tasks/main.yml#L16

i.e. https://github.com/AdoptOpenJDK/secrets/blob/master/vendor_files/Jenkins_User_SSHKey.gpg in the local directory would be `/Vendor_Files/Jenkins_User_SSHKey`
