### ISSUE TITLE
test-ibm-aix71-ppc64-1 contains a "/home/jenkins/build-test" directory using 7.7Gb of space

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-infrastructure#1853]
https://ci.adoptopenjdk.net/computer/test-ibm-aix71-ppc64-1
"/home/jenkins/build-test" directory using 7.7Gb of space
This looks like a test someone did back on Oct 9th, presumably can be deleted?
Note it seems to have root permissions:
```
drwxr-xr-x  3 root    system     256 Oct  9 11:04 build_test
```

**Comment by sxa** [comment]
@Haroon-Khel Did you resolve this one?

**Comment by Haroon-Khel** [comment]
Yes this can be closed
