### ISSUE TITLE
test-osuosl-aix71-ppc64-1 only has an 18Gb disk, not enough to run some test suites

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-infrastructure#1854]
Some test suites create "dmp" files which can be very large. The minimum disk size really needs to be about 30Gb.
https://ci.adoptopenjdk.net/computer/test-osuosl-aix71-ppc64-1/
I've removed the ci.role.test label and taken offline

**Comment by Haroon-Khel** [comment]
/home has been increased to 30G on the machine
