### ISSUE TITLE
System unavailable: DTK: test-macstadium-macos11-arm64-1

### ISSUE THREAD

**Issue by sxa** [AdoptOpenJDK/openjdk-infrastructure#1855]
- Please put the system name in the title of this issue.

- Link to any log file showing the problem:

- Please describe the issue:
Unable to connect to [the machine](https://ci.adoptopenjdk.net/computer/test-macstadium-macos11-arm64-1) over ssh although the jenkins script conols still seems live and able to respond to commands. `-2` is ok.

Latest output in the `ssh -vvv` (it somehow locks up my terminal at this point so I can't abort the `ssh` client) is:
```
debug3: Ignored env COLORTERM
debug3: Ignored env _
debug2: channel 0: request shell confirm 1
debug3: send packet: type 98
debug2: callback done
debug2: channel 0: open confirm rwindow 0 rmax 32768
```

**Comment by aahlenst** [comment]
The machines were sent back to Apple because the DTK program has ended.
