### ISSUE TITLE
Please make me an author on the AdoptOpenJDK blog

### ISSUE THREAD

**Issue by geraintwjones** [AdoptOpenJDK/openjdk-infrastructure#186]
I'd like to contribute an article to the blog at https://blog.adoptopenjdk.net/, but am not an author, so I can't.

Please make me an author.

Thank you.

**Comment by bblondin** [comment]
Me too please

**Comment by geraintwjones** [comment]
Can you help me with this @tellison?

**Comment by karianna** [comment]
I think I can add you both, can you DM me your email addresses in Slack?

**Comment by gdams** [comment]
I am working on getting github oauth working with wordpress. In the mean time you need to go to https://blog.adoptopenjdk.net/wp-login.php?wle to login with wordpress credentials

**Comment by adoptopenjdk-admin** [comment]
Both have been added.
