### ISSUE TITLE
Access request for aarch64 for lumpfish

### ISSUE THREAD

**Issue by lumpfish** [AdoptOpenJDK/openjdk-infrastructure#1866]
Access level:

- [ ] Non-privileged
- [X ] jenkins user
- [ ] root/Administrative
- [ ] other (Please specify):

System for which access is needed: 
Any aarch64 machine

Please explain why you need this access including whether it is a temporary or permanent request:
I'm working on issue https://github.com/AdoptOpenJDK/openjdk-tests/issues/2120 which is aarch64 specific.  I'd like access to a machine so that I can create a stand alone test case which demonstrates the issue.

**Comment by sxa** [comment]
Access granted to [test-aws-rhel76-armv8-1](https://ci.adoptopenjdk.net/computer/test-aws-rhel76-armv8-1) (`rushton@18.202.36.216`). Have marked it off line in jenkins just now while youuse it.

**Comment by lumpfish** [comment]
I've verified the standalone test case recreates https://github.com/AdoptOpenJDK/openjdk-tests/issues/2120, so the machine can be reenabled.  I've cleaned up after myself.

**Comment by sxa** [comment]
Access removed
