### ISSUE TITLE
https://ci.adoptopenjdk.net/computer/build-osuosl-aix71-ppc64-2 on the verge of no disk space

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-infrastructure#1869]
https://ci.adoptopenjdk.net/computer/build-osuosl-aix71-ppc64-2/ only has 10.5Gb disk free...?

**Comment by sxa** [comment]
Not sure why this was ... There was very little on the filesystem but for some reason the space wasn't beeing freed up which is odd when there didn't seem to be any processes with file handles open on the file system.

I've unmounted and remounted `/home` and that's been enough to free up the space again.
`df -k` on `/home` was
```
Filesystem    1024-blocks      Free %Used    Iused %Iused Mounted on
/dev/hd1         33554432  11230104   67%    36536     1% /home
```
```
Filesystem    1024-blocks      Free %Used    Iused %Iused Mounted on
/dev/hd1         33554432  28979472   14%    32047     1% /home
```
FYI @aixtools @sej-jackson in case you havent' seen this issue. It's resolved now but no idea what caused this. an `fsck` on the filesystem showed no issues.

**Comment by aixtools** [comment]
Although closed - when unmount/mount solves issues - `slibclean` will probably solve it as well. The 'issue' is inodes that are open, but link-count is zero - and this is, sadly, rather common, for OSS applications and testing.

I do not know if there is an explicit command an application can use (e.g., a sort of dlclose()) - but as a workaround a cronjob - e.g., at midnight, to slibclean (shared library clean) - which closes (and hence returns diskspace when link-count == zero).

**Comment by sxa** [comment]
Interesting - I thought in that situation where `slibclean` removes references that the file handles would still be open on the filesystem so it wouldn't e possible to unmount it. I guess that's an AIX "special feature" :-) Useful to know - thanks.

Do you know if there's a way to identify the inodes in use on the file system (i.e. the ones that `slibclean` will release)

**Comment by aixtools** [comment]
Not sure. I'll look around a bit.

An easier example:

```
# df -m /home
Filesystem    MB blocks      Free %Used    Iused %Iused Mounted on
/dev/hd1       32768.00  26053.65   21%    80066     1% /home
# slibclean
# df -m /home
Filesystem    MB blocks      Free %Used    Iused %Iused Mounted on
/dev/hd1       32768.00  27003.53   18%    79733     1% /home
```
