### ISSUE TITLE
File deletion request for build-alibaba-win2012r2-x64-2

### ISSUE THREAD

**Issue by adamfarley** [AdoptOpenJDK/openjdk-infrastructure#1887]
- test suite/name?
TestJstack_SE80_0
- Is there an existing issue elsewhere covering this?
https://github.com/AdoptOpenJDK/openjdk-tests/issues/2220
- Which machine(s) does it work on?
test-ibmcloud-win2012r2-x64-2
- Which machine(s) does it fail on?
build-alibaba-win2012r2-x64-2
- Do you have a link to a Grinder re-run if the test with the failure?
https://ci.adoptopenjdk.net/job/Grinder/6270

Any other details:
The issue is a 9-hour hang, when the test itself should take 4-6 seconds.

Based on debug output, we believe this problem can be solved by manually deleting this:
C:\cygwin\tmp\\.com_ibm_tools_attach
Please do that and resubmit the grinder. Obliged. :)

**Comment by sxa** [comment]
What is that file, where does it come from, and what will stop this being an issue going forward? I don't want us to just have to regularly be deleting files manually.

**Comment by adamfarley** [comment]
That file is believed to be generated by openjdk on openj9 as part of the locking system for the attach api.

As far as I can tell, this problem was seem once, two years ago at eclipse/openj9, and did not reoccur when the file/folder was deleted.

Back then, when asked whether the test could be improved to tidy up this file in the future, pdbain had this to say:

```
I doubt it. Note that the Attach API already cleans up after itself in the common directory (and tries to clean artifacts left by defunct processes).

The issue here is that the malformed files were in j9build's temp directory but were owned by Administrator and had what looked like the wrong permissions.
```

**Comment by pshipton** [comment]
Who is the owner, what are the permissions of the file?

@JasonFengJ9 fyi

**Comment by Haroon-Khel** [comment]
Job rerunning on build-alibaba-win2012r2-x64-2 at https://ci.adoptopenjdk.net/job/Test_openjdk17_j9_extended.functional_x86-64_windows_xl/22/console

**Comment by sxa** [comment]
@Haroon-Khel Since you're working on this issue can you assign yourself to it please?

**Comment by adamfarley** [comment]
Verified fixed.
