### ISSUE TITLE
Ansible request for AIX playbook tasks that allows automation to continues when Vendor_Files are not available.

### ISSUE THREAD

**Issue by aixtools** [AdoptOpenJDK/openjdk-infrastructure#1888]
Please put the name of the software product (and affected platforms if relevant) in the title of this issue

- [ ] Missing install
- [ ] Bug in ansible playbook
- [x] Request for new playbook addition

Details:
Currently, running playbooks assumes access to Vendor_Files. When this is not available, the playbook stops.

For AIX (at least) I would like to add some logic around the locations where Vendor_Files access is requested - but permits processing to continue - as much as possible - when, for whatever reason - likely authorization to access - fails.

As there are so many tags (from memory, need to specify 7 tags to skip to run AIX playbook if Vendor_Files access is unavailable) - it makes it next to impossible for anyone except a senior (fully authorized) AdoptOpenJDK member do preparation work.

**Comment by sxa** [comment]
In the general *ix playbook we use the `AdoptOpenJDK` task which excludes that sort of thing and allows the playbooks to be run independently. I'm surprised it's 7 different ones, but I guess we do pull packages and things from that location on AIX that we don't on the other platforms.

I agree that tagging them all with `vendor_files` or similar would be a reasonable thing to do.
