### ISSUE TITLE
Ansible request for numactl on RHEL Linux/s390x

### ISSUE THREAD

**Issue by sxa** [AdoptOpenJDK/openjdk-infrastructure#1890]
Please put the name of the software product (and affected platforms if relevant) in the title of this issue

- [ ] Missing install
- [x] Bug in ansible playbook
- [ ] Request for new playbook addition

Details:

numactl does not install properly on RHEL77/s390x:
```
TASK [Common : Install numactl-devel excluding RHEL 7 on s390x] ****************
fatal: [build-marist-rhel77-s390x-2]: FAILED! => {"changed": false, "msg": "No package matching 'numactl-devel' found available, installed or updated", "rc": 126, "results": ["No package matching 'numactl-devel' found available, installed or updated"]}
```

**Comment by Willsparker** [comment]
That task is meant to be skipped for that platform. Let me check the conditions. What's `numactl-devel` for, do you know?

**Comment by Willsparker** [comment]
There's also no `numa` in the package list:
```
[root@build-marist-rhel77-s390x-2 ~]# yum list | grep numa
[root@build-marist-rhel77-s390x-2 ~]#
```
