### ISSUE TITLE
SXA-processCheck: build-alibaba-win2012r2-x64-2 rogue process error

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-infrastructure#1892]
https://ci.adoptopenjdk.net/view/Failing%20Builds/job/SXA-processCheck/label=build-alibaba-win2012r2-x64-2/155/console

**Comment by Willsparker** [comment]
From the looks of it, that's the Jenkins Agent. (It's running from `C:\Program Files\Java\jdk8u275 ... `)
That machine is being very odd - every couple of seconds its spawning a new java process, and closes the one before it. This is almost definitely related to #1818

**Comment by Willsparker** [comment]
Alright, I stopped that process- the Agent didn't disconnect when I did it, as far as I can see, so I suppose it was a true leftover process. Closing
