### ISSUE TITLE
Ansible request for Ubuntu 20.04/aarch64 OS detection for Nagio_Plugins role

### ISSUE THREAD

**Issue by sxa** [AdoptOpenJDK/openjdk-infrastructure#1901]
Please put the name of the software product (and affected platforms if relevant) in the title of this issue

- [ ] Missing install
- [x] Bug in ansible playbook
- [ ] Request for new playbook addition

Details: Not quite sure why, but when attempting to deploy the playbook on a Ubuntu 20.04/aarch64 machine the `ansible_distribution_major_version` is set to `***Undefined***` (as is `ansible_os_family`) which means that [this guard](https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/2925d55ff93ca8bbbbaf6ada6184b7aa18847a69/ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Nagios_Plugins/tasks/nagios_Ubuntu.yml#L30) in the `Nagios_Plugins` role causes the playbook to fail. Easily reproducible by running with `--tags debug`

**Comment by Willsparker** [comment]
Happy to look at this. But surely `ansible_distribution_major_version` being defined is going to cause a lot more issues than just Nagios, and we should probably figure out why it's doing that. Maybe a platform to add on QPC :thinking:

**Comment by Willsparker** [comment]
Closing due to #1912
