### ISSUE TITLE
test-marist-ubuntu1604-s390x-4x docker permission denied

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-infrastructure#1905]
https://ci.adoptopenjdk.net/computer/test-marist-ubuntu1604-s390x-4x/
```
04:51:11       [echo] Executing external.sh --clean --dir tomcat --tag nightly --version 11 --impl hotspot 
04:51:11       [exec] Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Delete http://%2Fvar%2Frun%2Fdocker.sock/v1.38/images/adoptopenjdk-tomcat-test:11-jdk-ubuntu-hotspot-full?force=1: dial unix /var/run/docker.sock: connect: permission denied
```

**Comment by Haroon-Khel** [comment]
I added the jenkins user to the docker group and relaunced the agent. Rerunning at https://ci.adoptopenjdk.net/view/Failing%20Test%20Jobs/job/Test_openjdk11_j9_sanity.external_s390x_linux_quarkus/40/console

**Comment by Haroon-Khel** [comment]
The job was able to run successfully

**Comment by Haroon-Khel** [comment]
Although, like https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1885#issuecomment-773944781, only the `MachineInfo_0` test ran

**Comment by sxa** [comment]
@Haroon-Khel Can you make sure you assign yourself to issues you're working on please?

**Comment by sxa** [comment]
@smlambert Are any of the external tests able to run on `s390x`? Looks like some (all? Not checked) of them are configured to execute only `MachineInfo_0`. Has an extra check of some sort been added to run a docker command at the start of the external suite that caused this to show up?

**Comment by Haroon-Khel** [comment]
I think this job behaves the same as https://ci.adoptopenjdk.net/view/Failing%20Test%20Jobs/job/Test_openjdk8_hs_sanity.external_x86-64_linux_spring/, where if I build it manually the build list defaults to external, but the nightlies will have a build list of external/quarkus (external/spring in the linked job) which may explain the different tests that run when manually built compared to the nightly job

**Comment by smlambert** [comment]
All external tests can run in Docker on s390x, and look for the https://ci.adoptopenjdk.net/label/sw.tool.docker/ label appended to the ci.role.test&&sw.os.linux&&hw.arch.s390x.

We run external tests in PARALLEL=Subdir mode.  This lets us break each application out into their own job and to not have to edit any hardcoded list as we add more external targets.  When we run sanity.external or extended.external, it will run each find each test target in the playlist inside a subdir and run those that match the level of the job.  As in, if the test job is sanity.external we run all tests tagged with `<level>sanity</level>` so as Haroon points out, for some subdirs, it will only exercise the MachineInfo test targets.  (related: https://github.com/AdoptOpenJDK/openjdk-tests/wiki/Graduated-Testing-&-Test-Numbers#external-test-group)

**Comment by Haroon-Khel** [comment]
Closing since the initial docker permission error is resolved
