### ISSUE TITLE
Access request for aahlenst

### ISSUE THREAD

**Issue by aahlenst** [AdoptOpenJDK/openjdk-infrastructure#1908]
Access level:

- [ ] Non-privileged
- [ ] jenkins user
- [x] root/Administrative
- [ ] other (Please specify):

System for which access is needed: test-macstadium-macos1014-x64-3

Please explain why you need this access including whether it is a temporary or permanent request:

I'm trying to track down https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/211 to get AWT testing enabled. I cannot reproduce the problem locally (without having an X server installed) so I want to have a look at the machine.

**Comment by sxa** [comment]
Access granted - good luck! I think a few people have tried this before and haven't managed to quite get it working yet :-)

**Comment by aahlenst** [comment]
I'm done. My access can be revoked.
