### ISSUE TITLE
Ansible request for locales on RHEL77/s390x

### ISSUE THREAD

**Issue by sxa** [AdoptOpenJDK/openjdk-infrastructure#1915]
Please put the name of the software product (and affected platforms if relevant) in the title of this issue

- [ ] Missing install
- [x] Bug in ansible playbook
- [ ] Request for new playbook addition

Details:
Tried to run playbooks on the bulid*rhel* systems at marist and got this:

```
TASK [Common : Install 'locales' package] **************************************
fatal: [build-marist-rhel77-s390x-1]: FAILED! => {"changed": false, "msg": "No package matching 'locales' found available, installed or updated", "rc": 126, "results": ["No package matching 'locales' found available, installed or updated"]}
fatal: [build-marist-rhel77-s390x-2]: FAILED! => {"changed": false, "msg": "No package matching 'locales' found available, installed or updated", "rc": 126, "results": ["No package matching 'locales' found available, installed or updated"]}
```

**Comment by Willsparker** [comment]
I'm going to test things on `build-marist-rhel77-s390x-1` - for `rhel7`, `localectl list-locales` can be used to get the list of locales, however, I'm unsure if the `locale_gen` task will work. The [ansible module](https://docs.ansible.com/ansible/2.5/modules/locale_gen_module.html) page doesn't provide much information about how it works - however the `/etc/locale.gen` file isn't on the systems, so I assume we'll need to go a different route for RHEL7
