### ISSUE TITLE
VPC: Add jdk16 as an option to build

### ISSUE THREAD

**Issue by sxa** [AdoptOpenJDK/openjdk-infrastructure#1919]
13, 14 and 15 are no longer in service. 16 is the current stream so that's the one we should stick with just using the current ones.

**Comment by Willsparker** [comment]
With `buildJDK.sh` and `buildJDKWin.sh`, what version it can build is taken from https://api.adoptopenjdk.net/v3/info/available_releases , so they already can, so it was just a case of configuring VPC to add jdk16 :-)
