### ISSUE TITLE
System unavailable: https://ci.adoptopenjdk.net/label/linux&&riscv64/ unavailable

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-infrastructure#1921]
https://ci.adoptopenjdk.net/label/linux&&riscv64/

**Comment by andrew-m-leonard** [comment]
@gdams fyi

**Comment by gdams** [comment]
Servers are back up. After lots of trawling through logs, it turned out to be a dynamic DNS issue
