### ISSUE TITLE
Access request for andrew-m-leonard for testing macos core permissions

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-infrastructure#1923]
Access level:

- [ ] Non-privileged
- [ ] jenkins user
- [X] root/Administrative
- [ ] other (Please specify):

System for which access is needed:
test-macstadium-macos1014-x64-1
test-macstadium-macos1014-x64-2
test-macstadium-macos1014-x64-3
test-macincloud-macos1010-x64-2

Please explain why you need this access including whether it is a temporary or permanent request:
Need "root/admin" access to be able to correct/debug   /cores testcase access issue

**Comment by sxa** [comment]
Granted to test-macstadium-macos1014-x64-1

**Comment by andrew-m-leonard** [comment]
Need jenkins user access on test-macstadium-macos1014-x64-1 please

**Comment by sxa** [comment]
You Can get to that via sudo - that should help :-)

**Comment by sxa** [comment]
@andrew-m-leonard Is this access still required?

**Comment by andrew-m-leonard** [comment]
nope, finished now thanks
