### ISSUE TITLE
Access request for andrew-m-leonard for macos ant-contrib setup

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-infrastructure#1924]
Access level:

- [ ] Non-privileged
- [ ] jenkins user
- [ x] root/Administrative
- [ ] other (Please specify):

System for which access is needed:  test-macincloud-macos1010-x64-2

Please explain why you need this access including whether it is a temporary or permanent request:
To debug issue https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1922
problem with ant-contrib setup

**Comment by sxa** [comment]
Looks from the slack thread as though @gdams  is investigating so we should hold off on this for now (I'd rather not have two people experimenting on the machine at the same time!)

**Comment by andrew-m-leonard** [comment]
not needed now

**Comment by sxa** [comment]
Has the problem been fixed? Looks like the node is still disabled
