### ISSUE TITLE
Ansible request for ansible-lint check failures

### ISSUE THREAD

**Issue by sxa** [AdoptOpenJDK/openjdk-infrastructure#1926]
Most of the changes to playbooks are showing up a failure in the `ansible-lint` checks. I'm not able to reproduce this with `ansible-lint` on my local machine (latest installed by `pip`, which shows no problems with the playbooks. Affecting multiple PRs at present. Log fragment below:
```
The error appears to be in '/home/runner/work/openjdk-infrastructure/openjdk-infrastructure/ansible/playbooks/adoptopenjdk_variables.yml': line 3, column 1, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

# AdoptOpenJDK variables file
Jenkins_Username: jenkins
^ here


Error: syntax-check A playbook must be a list of plays, got a <class 'ansible.parsing.yaml.objects.AnsibleMapping'> instead
You can skip specific rules or tags by adding them to your configuration file:
# .ansible-lint
warn_list:  # or 'skip_list' to silence them completely
  - syntax-check  # Ansible syntax check failed
Finished with 1 failure(s), 0 warning(s) on 263 files.
Error: Process completed with exit code 2.
1s 
```

**Comment by Willsparker** [comment]
I have managed to recreate the error! 
I had to install the new version of Ansible-lint (5.0.2) - which required that I install the new version of Ansible (3.0.0). This came up, hence the `apt purge` command : `Upgrading directly from ansible-2.9 or less to ansible-2.10 or greater with pip is known to cause problems.`
```
apt purge ansible
pip3 install ansible
pip3 install ansible-lint
```

Once I did that,  I ran `ansible-lint` in 'openjdk-infrastructure/ansible' and it flagged the error.

**Comment by Willsparker** [comment]
Initial impressions is that it's due to the structure of the playbooks - I can see the `aix.yml` playbook uses the file that's causing an error, and I think that's the only one, so it may be that it needs to be put into a `group_vars/adoptopenjdk_variables.yml` directory.

**Comment by Willsparker** [comment]
Ah okay- when I tried to move the file, I got this error message:
```
will@will-XPS-13-9360:~/Documents/Git/openjdk-infrastructure$ ansible-lint
WARNING  Listing 1 violation(s) that are fatal
internal-error: Unexpected error code 1 from execution of: ansible-playbook --syntax-check ansible/playbooks/adoptopenjdk_variables.yml
ansible/playbooks/adoptopenjdk_variables.yml:0 ERROR! the playbook: ansible/playbooks/adoptopenjdk_variables.yml could not be found
```

Which would imply that there's a list of commands that the linter is trying to execute somewhere, and within it, it thinks that the variables file is meant to be a playbook.
