### ISSUE TITLE
Jenkins needs an IPv6 address

### ISSUE THREAD

**Issue by aahlenst** [AdoptOpenJDK/openjdk-infrastructure#1928]
Our colocation network has only very few public IPv4 addresses that we do not want to waste on build and test machines. But we have plenty of IPv6 addresses (a /48 network). Every machine has a public IPv6 address. To enable Jenkins to see the machines (and vice versa), Jenkins needs an IPv6 address and a AAAA record in DNS. At least the AAAA record is currently missing:

```
$ dig ci.adoptopenjdk.net aaaa

; <<>> DiG 9.16.1-Ubuntu <<>> ci.adoptopenjdk.net aaaa
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 50435
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;ci.adoptopenjdk.net.		IN	AAAA

;; Query time: 32 msec
;; SERVER: 127.0.0.53#53(127.0.0.53)
;; WHEN: Sun Feb 14 15:11:29 CET 2021
;; MSG SIZE  rcvd: 48
```

**Comment by gdams** [comment]
I have enabled IPV6 Compatibility in Cloudflare https://support.cloudflare.com/hc/en-us/articles/229666767-Understanding-and-configuring-Cloudflare-s-IPv6-support#:~:text=1%20Login%20to%20your%20Cloudflare%20account.%202%20Select,app.%204%20Toggle%20IPv6%20Compatibility%20Off%20or%20On.

**Comment by gdams** [comment]
also created the following DNS record in Cloudflare:

```
ci.adoptopenjdk.net.	300	IN	AAAA	2a01:4f8:c0c:1804::
```

**Comment by gdams** [comment]
Dig looks better:

```bash
dig ci.adoptopenjdk.net aaaa
; <<>> DiG 9.10.6 <<>> ci.adoptopenjdk.net aaaa
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 64506
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1
;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;ci.adoptopenjdk.net.		IN	AAAA
;; ANSWER SECTION:
ci.adoptopenjdk.net.	300	IN	AAAA	2a01:4f8:c0c:1804::
;; Query time: 223 msec
;; SERVER: 2001:4898::1050:5050#53(2001:4898::1050:5050)
;; WHEN: Tue Mar 02 12:39:49 GMT 2021
;; MSG SIZE  rcvd: 76
```

**Comment by gdams** [comment]
I have confirmed that I can now ping `2a01:4f8:c0c:1804::2` from the bastion server.
