### ISSUE TITLE
Test machines with Alpine Linux

### ISSUE THREAD

**Issue by aahlenst** [AdoptOpenJDK/openjdk-infrastructure#1929]
I need to request a new machine:

- New machine operating system (e.g. linux/windows/macos/solaris/aix): Alpine Linux
- New machine architecture (e.g. x64/aarch32/arm32/ppc64/ppc64le/sparc): x64
- Provider (leave blank if it does not matter):
- Desired usage: Testing JDK 16+ built for musl libc
- Any unusual specification/setup required:
- How many of them are required: 2

Please explain what this machine is needed for: 
https://github.com/AdoptOpenJDK/openjdk-tests/issues/2223

Should be ready in time for JDK 16 release.

**Comment by sxa** [comment]
Created as:
- https://ci.adoptopenjdk.net/computer/test-docker-alpine311-x64-1/
- https://ci.adoptopenjdk.net/computer/test-docker-alpine312-x64-2/
Although jenkins is currently having problems interacting with them. FYA @smlambert do you have a particular tag you want to use for alpine/musl builds? Should it still have `sw.os.linux`? I've set them up with `sw.os.musl` just to differentiate it from now.

**Comment by gdams** [comment]
@sxa elsewhere we've called the os `alpine-linux` so maybe we could follow suit and use `sw.os.alpine-linux`

**Comment by sxa** [comment]
> @sxa elsewhere we've called the os `alpine-linux` so maybe we could follow suit and use `sw.os.alpine-linux`

SGTM - changed from `sw.os.musl`

**Comment by smlambert** [comment]
ok, given that change, we need to update https://github.com/AdoptOpenJDK/openjdk-tests/blob/master/buildenv/jenkins/openjdk_tests#L106

**Comment by sxa** [comment]
Set the machines to include both labels for now so that the tests won't cause a problem @smlambert

**Comment by smlambert** [comment]
I've now removed the sw.os.musl label since openjdk-tests/2336 is merged, thanks @sxa !
