### ISSUE TITLE
Provision mac Minis for perf tests

### ISSUE THREAD

**Issue by aahlenst** [AdoptOpenJDK/openjdk-infrastructure#1934]
I need to request a new machine:

- New machine operating system (e.g. linux/windows/macos/solaris/aix): macOS 10.15
- New machine architecture (e.g. x64/aarch32/arm32/ppc64/ppc64le/sparc): x64
- Provider (leave blank if it does not matter): Adoptium
- Desired usage: perf testing
- Any unusual specification/setup required:
- How many of them are required: 2

Please explain what this machine is needed for:
Replacement of perf testing machines we decommissioned last fall.

Machines have been installed and attached to the network (VLAN `TEST`):

test-nine-macos1015-x64-1 (10.0.40.10, 2a02:418:3001:40::10)
test-nine-macos1015-x64-2 (10.0.40.11, 2a02:418:3001:40::11)

Credentials are in LastPass.

@gdams volunteered to provision both machines.

**Comment by gdams** [comment]
https://ci.adoptopenjdk.net/computer/perf-adoptium-macos1015-x64-1/
https://ci.adoptopenjdk.net/computer/perf-adoptium-macos1015-x64-2/

Waiting on @aahlenst to allow jenkins through the firewall

**Comment by gdams** [comment]
https://ci.adoptopenjdk.net/computer/test-nine-macos1015-x64-1/ & https://ci.adoptopenjdk.net/computer/test-nine-macos1015-x64-2/ now online. @smlambert you may want to add a perf label to these as well
