### ISSUE TITLE
build-alibaba-win2012r2-x64-2 low on memory?

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-infrastructure#1940]
https://ci.adoptopenjdk.net/job/Test_openjdk17_j9_extended.functional_x86-64_windows_xl/28/ failing OutOfMemory, could this machine be low on resource?

**Comment by Willsparker** [comment]
I'd check, but I can't connect to the RDP server. @Haroon-Khel or @sxa , can you connect to it?

**Comment by Haroon-Khel** [comment]
It may have been out of memory at the time of the job, but as of now its only using 29% of its memory

**Comment by Haroon-Khel** [comment]
Like https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1939#issuecomment-780416056, there are 2 `revokeall` processes running in the background, one from feb 14, the other from feb 6

**Comment by Haroon-Khel** [comment]
Ive rebuilt the job on the machine, https://ci.adoptopenjdk.net/job/Test_openjdk17_j9_extended.functional_x86-64_windows_xl/29/console. While the job runs, both revokeall process are taking up 40-60% of the CPU

**Comment by sxa** [comment]
> Like [#1939 (comment)](https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1939#issuecomment-780416056), there are 2 `revokeall` processes running in the background, one from feb 14, the other from feb 6

Suggest stopping both of them. No reason for them to still be running beyond the job that started them.

**Comment by sxa** [comment]
@Haroon-Khel Is this fixed and therefore can be closed now?

**Comment by Haroon-Khel** [comment]
Yep
