### ISSUE TITLE
Synchronise how branches are specified in QPC and VPC

### ISSUE THREAD

**Issue by sxa** [AdoptOpenJDK/openjdk-infrastructure#1941]
Currently in [VagrantPlaybookCheck](https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/build?delay=0sec) we specify a branch in the `REPOSITORY_URL` with e.g. `https://github.com/sxa/openjdk-infrastructure/tree/mybranchname` whereas in [QEMUPlaybookCheck](https://ci.adoptopenjdk.net/view/Tooling/job/QEMUPlaybookCheck/build?delay=0sec) there is a separate `INFRA_BRANCH` parameter (Same for `BUILD_BRANCH`). We should make both behave the same way for a consistent user experience

**Comment by Willsparker** [comment]
I'll take that- I've been meaning to fix up VPC for awhile ... :facepalm:

**Comment by Willsparker** [comment]
ref: https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/1956
