### ISSUE TITLE
Ansible request for Windows shortnames

### ISSUE THREAD

**Issue by sxa** [AdoptOpenJDK/openjdk-infrastructure#1945]
Please put the name of the software product (and affected platforms if relevant) in the title of this issue

- [ ] Missing install
- [x] Bug in ansible playbook
- [ ] Request for new playbook addition

Details: This is showing up during the `[Common : Ensure 'Program Files (x86)' has a shortname]` task in the Windows playbook on at least some machines, preventing successful completion:

`fatal: [test-ibmcloud-win2012r2-x64-2]: FAILED! => {"changed": true, "cmd": "fsutil file setshortname \"C:\\Program Files (x86)\" \"PROGRA~2\"", "delta": "0:00:00.119001", "end": "2021-02-17 01:23:29.342042", "msg": "non-zero return code", "rc": 1, "start": "2021-02-17 01:23:29.223041", "stderr": "", "stderr_lines": [], "stdout": "Error:  Access is denied.\r\n\r\n", "stdout_lines": ["Error:  Access is denied.", ""]}`

**Comment by Willsparker** [comment]
This can't be run after we have installed the rest of the playbook, because services start running in the `Program Files (x86)` folder. 
I'll put the `Ignore_Errors: yes` var into it, as this should allow the playbook to be re-run on already setup machines.
