### ISSUE TITLE
build-osuosl-aix71-ppc64-1/2 missing libcurl.so ?

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-infrastructure#1946]
https://ci.adoptopenjdk.net/computer/build-osuosl-aix71-ppc64-1/

https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-aix-ppc64-hotspot/888/console
```
14:59:04  Caused by: hudson.plugins.git.GitException: Command "git fetch --tags --progress -- https://github.com/AdoptOpenJDK/openjdk-build.git +refs/heads/*:refs/remotes/origin/*" returned status code 141:
14:59:04  stdout: 
14:59:04  stderr: exec(): 0509-036 Cannot load program git-remote-https because of the following errors:
14:59:04  	0509-150   Dependent module libcurl.a(libcurl.so.4) could not be loaded.
14:59:04  	0509-022 Cannot load module libcurl.a(libcurl.so.4).
14:59:04  	0509-026 System error: A file or directory in the path name does not exist.
14:59:04  
14:59:04  	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2450)
14:59:04  	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandWithCredentials(CliGitAPIImpl.java:2051)
14:59:04  	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.access$500(CliGitAPIImpl.java:84)
14:59:04  	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$1.execute(CliGitAPIImpl.java:573)
```

**Comment by Haroon-Khel** [comment]
Using a [passing test](https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-aix-ppc64-hotspot/881/consoleFull) as a guidline, i ran 
```
git init /home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-aix-ppc64-hotspot
cd /home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-aix-ppc64-hotspot
git fetch --tags --progress -- https://github.com/AdoptOpenJDK/openjdk-build.git +refs/heads/*:refs/remotes/origin/

remote: Enumerating objects: 10394, done.
Receiving objectsremote: Total 10394 (delta 0), reused 0 (delta 0), pack-reused 10394
Receiving objects: 100% (10394/10394), 4.12 MiB | 3.43 MiB/s, done.
Resolving deltas: 100% (6845/6845), done.
From https://github.com/AdoptOpenJDK/openjdk-build
 * [new branch]      andrew-m-leonard-patch-1 -> origin/andrew-m-leonard-patch-1
 * [new branch]      awx.sxa.org.uk -> origin/awx.sxa.org.uk
 * [new branch]      compileOnly -> origin/compileOnly
 * [new branch]      douph1-1834 -> origin/douph1-1834
....

```
And wasnt able to recreate the error. As mentioned in slack, I do suspect that ansible updating each package is related to this as the same error has appeared on build-osuosl-aix71-ppc64-1

**Comment by Haroon-Khel** [comment]
> As mentioned in slack, I do suspect that ansible updating each package is related to this

Perhaps not, because I ran the ansible playbook on build-osuosl-aix71-ppc64-2 aswell, which hit the same error, but 
https://ci.adoptopenjdk.net/job/Test_openjdk17_j9_sanity.system_ppc64_aix/7/console has been running on it fine

**Comment by Haroon-Khel** [comment]
In regards to libcurl.so, it doesnt seem to be on the machine. I just updated git on the machine manually, in an attempt to circumvent the ansible error that I posted above

**Comment by andrew-m-leonard** [comment]
@Haroon-Khel 
build-osuosl-aix71-ppc64-2 is now failing the same:
 https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk16/job/jdk16-aix-ppc64-hotspot/55/console

**Comment by Haroon-Khel** [comment]
Ive updated git on build-osuosl-aix71-ppc64-2 to `2.20.4`

**Comment by sxa** [comment]
@Haroon-Khel What's the status of this one? I suspect the error referenced in the previous comment may be https://github.com/AdoptOpenJDK/openjdk-build/issues/2466 since it seems related to the `jvmti` area

**Comment by Haroon-Khel** [comment]
This issue can be closed, since the original problem was fixed when I updated git on both machines
