### ISSUE TITLE
System unavailable: Both windows wix nodes down

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-infrastructure#1948]
Both down: https://ci.adoptopenjdk.net/label/windows&&wix/

**Comment by sxa** [comment]
[build-azure-1](https://ci.adoptopenjdk.net/computer/build-azure-win2012r2-x64-1/) rebooted testerday and the agent service, for reasons which aren't clear, did not restart. It's also failing to start when I try to start it manually.
[build-azure-2](https://ci.adoptopenjdk.net/computer/build-azure-win2012r2-x64-2/) is now running again (so will be going through the queued up WiX jobs) although it's also prompting to restart to apply updates. I'll let it run through the installer queue before proceeding with that

**Comment by sxa** [comment]
`-1` now running again. For some reason it was in a restart loop and had done so over 1000 times. I switched the service from `Automatic` to `Manual` startup, then started it manually and it came up fine and is now running jobs.

I hadn't realised we were only able to run those jobs on the Azure cloud - we should at least have one of the ibmcloud windows machines able to do this too.

**Comment by sxa** [comment]
`-2` rebooted and restarted the agent without problems. Closing.

**Comment by sxa** [comment]
Going to reopen this. Azure `-1` is out of disk space so is not usable yet

**Comment by sxa** [comment]
Cleared:
- Old JDKs not needed for booting
- Old OpenSSL levels
- An extracted JDK head at `c:\openjdk-jdk`
- `C:\ProgramData\Package Cache` (Moved to `J:\ProgramDataMovedFromC and also Archive created with `7z` in that location)

System now has 15Gb free on C:
