### ISSUE TITLE
clear out hosts in nagios and let ansible set them up

### ISSUE THREAD

**Issue by gdams** [AdoptOpenJDK/openjdk-infrastructure#195]
since the hostname changes, many hosts are now out of sync in nagios. @bblondin can you remove all of these linux hosts and we can then use the ansible playbook to set them up again

**Comment by geraintwjones** [comment]
- __New machine gets added.__
  - Manually set up root on that machine with a keybox key.
  - Manually add the machine to keybox.
  - Use AWX/Ansible to complete machine setup and add it to Nagios.
  - Manually add the machine to infrastructure.md.

- __Existing machine removed.__
  - Manually remove machine from keybox.
  - Use AWX/Ansible (?) to remove machine from Nagios (we culd use Ansible).
  - Manually remove the machine from infrastructure.md.

- __Existing machine gets renamed, or redeployed with new name and/or IP address.__
  - Manually change machine's details in keybox.
  - Use AWX/Ansible (?) to update machine's config in Nagios.
  - Manually update the machine's details infrastructure.md.

Might this be a reason to look into auto-provisioning machines on-demand by the builds, tests, etc, that need them?

**Comment by bblondin** [comment]
Things look ok right now, as the playbook is run on more hosts, I will continue to monitor Nagios and ensure the old hostnames are cleaned up.
