### ISSUE TITLE
Remove aix710 label from https://ci.adoptopenjdk.net/computer/test-ibm-aix71-ppc64-1/ until debugging finished

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-infrastructure#1978]
Being used to help debug https://github.com/AdoptOpenJDK/openjdk-build/issues/2466

**Comment by Willsparker** [comment]
I've removed the label (and left a comment in the description) : https://ci.adoptopenjdk.net/computer/test-ibm-aix71-ppc64-1/

**Comment by andrew-m-leonard** [comment]
@Willsparker sorry, I wasn't very clear in the description. The purpose of this issue is to remember to remove aix710 once I have finished debugging the other issue, hopefully by next week. I've put aix710 back on it, thanks

**Comment by andrew-m-leonard** [comment]
Finished with the node now, i've removed aix710. thanks
