### ISSUE TITLE
Add additional hosts and services to Nagios

### ISSUE THREAD

**Issue by tellison** [AdoptOpenJDK/openjdk-infrastructure#2]
The following machines are not currently known to our Nagios installation, and should be added to ensure their basic health is monitored:

- `api.adoptopenjdk.net`
- `staging.adoptopenjdk.net`

The following publicly available services should also be monitored so the #infrastructure channel is notified if they go down:
 - HTTP/HTTPS
   - `www.adoptopenjdk.net`
   - `api.adoptopenjdk.net`
   - `ci.adoptopenjdk.net`
   - `keybox.adoptopenjdk.net`
   - `staging.adoptopenjdk.net`
   - `ansible.adoptopenjdk.net`

**Comment by tellison** [comment]
While there please also add in the new AIX boxes mentioned in #4

**Comment by bblondin** [comment]
- Added new service group "Web_Sites"
https://nagios.adoptopenjdk.net/nagios/cgi-bin/status.cgi?servicegroup=all&style=grid

- Enabled/confirmed website mointoring for:
www.adoptopenjdk.net
api.adoptopenjdk.net
ci.adoptopenjdk.net
keybox.adoptopenjdk.net
staging.adoptopenjdk.net
ansible.adoptopenjdk.net


- Installed Nagios plugins and enabled monitor of host for:
api.adoptopenjdk.net - https://nagios.adoptopenjdk.net/nagios/cgi-bin/status.cgi?host=api.adoptopenjdk.net 
staging.adoptopenjdk.net - https://nagios.adoptopenjdk.net/nagios/cgi-bin/status.cgi?host=staging.adoptopenjdk.net

The website https://api.adoptopenjdk.net appears to be down... not sure how to start it

**Comment by bblondin** [comment]
https://api.adoptopenjdk.net is now working and is being monitored.
now monitoring the AIX boxes: power8-aix-openjdk1.osuosl.org power8-aix-openjdk2.osuosl.org

**Comment by tellison** [comment]
I'm curious about why all the other machines in the Jenkins farm are known to Nagios by their executor name, e.g. `build-*` and `test-*` but the AIX boxes are known to Nagios by their hostnames?

_Signed: Your pedantic friend._

**Comment by bblondin** [comment]
@tellison 
When I was told about these new AIX systems, I was just given their IP addresses.
The hostname on the systems report back without build-* and test-* prefixes. So that is what I used for Nagios.

AIX system/Nagios
$ hostname
power8-aix-openjdk1.osuosl.org

Jenkins:
build-osuosl-ppc64-aix-71-1


This can be quite confusing to have two different names for the same system... It's an easy change to make... which I've made on the AIX systems and in Nagios to match that of Jenkins


Jenkins and Nagios don't know about each other (shh!)

**Comment by tellison** [comment]
@bblondin agreed, I don't know what the best practice is for naming hosts in Nagios, hostname would be a reasonable choice, but we were being inconsistent.  I'm happy with us choosing to use the machine's "common name", i.e. the one we use to identify it by purpose, hoster, CPU, OS, etc. which is arguably more generally useful to us than a straight hostname.
