### ISSUE TITLE
git missing from build-osuosl-ppc64le-centos-7.2

### ISSUE THREAD

**Issue by sxa555** [AdoptOpenJDK/openjdk-infrastructure#20]
All of my jobs on there are failing, which includes the parent of a matrix job which is therefore blocking some of my executions. Can we get git installed on this box please?

**Comment by tellison** [comment]
I don't understand why this is not configured via ansible ;-/  but I'll bring that up on the Slack channel.

In the meantime I've installed git manually.
```
$ git --version
git version 1.8.3.1
```
