### ISSUE TITLE
Many extended.openjdk tests timing out on aarch64

### ISSUE THREAD

**Issue by lumpfish** [AdoptOpenJDK/openjdk-infrastructure#2002]
There are many tests timing out in the extended.openjdk target with messages like:
```
06:58:21  TEST RESULT: Error. Program `/home/jenkins/workspace/Test_openjdk16_hs_extended.openjdk_aarch64_linux/openjdkbinary/j2sdk-image/bin/java' timed out (timeout set to 960000ms, elapsed time including timeout handling was 1006476ms).
```

Example job log: https://ci.adoptopenjdk.net/job/Test_openjdk16_hs_extended.openjdk_aarch64_linux/7/consoleFull

The tests do not time out on other platforms - could the resources allocated to the test docker images be a factor?

**Comment by sxa** [comment]
Re-running at https://ci.adoptopenjdk.net/job/Grinder/7435 on [the same system](https://ci.adoptopenjdk.net/computer/build-docker-fedora33-armv8-3/) just now while the host system should otherwise be idle.

**Comment by sxa** [comment]
@smlambert Are the extended openjdk suites similar to the system test suites in that they can chew up all the CPU cycles available to them?

**Comment by sxa** [comment]
After running a few other Grinders I'm now running `jdk_time_1` with 10 iterations on two affected machines (It's not 100% consistent):
- [Grinder 7537 on build-docker-ubuntu1804-armv8-2](https://ci.adoptopenjdk.net/job/Grinder/7537/)
- [Grinder 7538 on build-docker-fedora33-armv8-2](https://ci.adoptopenjdk.net/job/Grinder/7538/)

**Comment by sxa** [comment]
Current theory: The docker containers are restricted, however the tests are trying to spawn significantly more processes than there are CPUs available to the container. This is causing it to reach the memory limits of the container and slow things down. It would be good to know how the tests (`jdk_time_1` being a good example) decide how much processes to spawn off. At the moment on my container restricted to 8 CPUs I have 29 `javac` process and 21 `jstack` ones

**Comment by sxa** [comment]
ping @smlambert Is this expected? How many cores would you expect these tests to use up generally?

**Comment by smlambert** [comment]
A while back, I believe @jerboaa added this PR https://github.com/AdoptOpenJDK/openjdk-tests/pull/1427 which may be relevant to the question 'how many cores'?

**Comment by sxa** [comment]
> A while back, I believe @jerboaa added this PR [AdoptOpenJDK/openjdk-tests#1427](https://github.com/AdoptOpenJDK/openjdk-tests/pull/1427) which may be relevant to the question 'how many cores'?

That would explain it :-) I'll see what I can do ...
