### ISSUE TITLE
Access request for andrew_m_leonard to https://ci.adoptopenjdk.net/computer/test-nine-macos1015-x64-1

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-infrastructure#2011]
https://ci.adoptopenjdk.net/computer/test-nine-macos1015-x64-1
to debug why we can't perform core dumps

**Comment by karianna** [comment]
Still required?

**Comment by andrew-m-leonard** [comment]
nope thanks

**Comment by sxa** [comment]
@andrew-m-leonard Is this being progressed by someone?

**Comment by andrew-m-leonard** [comment]
@sxa yes, Keith Campbell is working on changing the way openj9 produces dumps
