### ISSUE TITLE
Access request for Willsparker, awx.adoptopenjdk.net

### ISSUE THREAD

**Issue by Willsparker** [AdoptOpenJDK/openjdk-infrastructure#2016]
### Access level:

- [ ] Non-privileged
- [ ] jenkins user
- [x] root/Administrative
- [ ] other (Please specify):

### System for which access is needed:
awx.adoptopenjdk.net

 ### Please explain why you need this access including whether it is a temporary or permanent request:

Ref: https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1876#issuecomment-772303011
I'm under the impression that the Nagios roles fail when running on AWX, due to AWX not being able to ssh to the Nagios server. It would probably be useful for me to have permanent access, but this is the only current reason I need access, so I'd call it temporary.

**Comment by sxa** [comment]
AWX only uses one key and it's the one which is on the root account of all the target machines so the question would be whether that key is on the Nagios server? We shouldn't need to change anything on AWX unless it's doing something a little odd ...

**Comment by Willsparker** [comment]
Ah, I may have had them mixed up in my head ... 
I put the AWX ssh key into `authorized_keys` on the Nagios server, and I was able to re-add `build-digitalocean-centos69-x64-2` into Nagios, after I manually removed it. That's going to be _fantastically_ useful for finally finishing #1716 :grin: 

I'll close this issue
