### ISSUE TITLE
java/nio/channels/FileChannel/LoopingTruncate.java : There is not enough space on the disk

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-infrastructure#2019]
Possibly a disk space issue...? Node: https://ci.adoptopenjdk.net/computer/build-ibmcloud-win2012r2-x64-2/
https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_extended.openjdk_x86-64_windows/15/consoleFull
java/nio/channels/FileChannel/LoopingTruncate.java
```
15:22:55  STDERR:
15:22:55  java.io.IOException: There is not enough space on the disk.
15:22:55  	at sun.nio.ch.FileDispatcherImpl.write0(Native Method)
15:22:55  	at sun.nio.ch.FileDispatcherImpl.write(FileDispatcherImpl.java:75)
15:22:55  	at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93)
15:22:55  	at sun.nio.ch.IOUtil.write(IOUtil.java:65)
15:22:55  	at sun.nio.ch.FileChannelImpl.write(FileChannelImpl.java:211)
15:22:55  	at LoopingTruncate.main(LoopingTruncate.java:53)
15:22:55  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
15:22:55  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
15:22:55  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
15:22:55  	at java.lang.reflect.Method.invoke(Method.java:498)
15:22:55  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
15:22:55  	at java.lang.Thread.run(Thread.java:823)
```

**Comment by andrew-m-leonard** [comment]
I'll have a look at this

**Comment by andrew-m-leonard** [comment]
Re-build: https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_extended.openjdk_x86-64_windows/22/

**Comment by andrew-m-leonard** [comment]
Problem caused by openjdk test LoopingTruncate which allocates a 8.5Gb file in the TEMP directory.
On this node TEMP is on C: which only has 7.5Gb free.

**Comment by andrew-m-leonard** [comment]
I've moved the TEMP env var for the Jenkins configuration to e:/jenkins/temp.

**Comment by andrew-m-leonard** [comment]
Test: https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_extended.openjdk_x86-64_windows/24/console

**Comment by andrew-m-leonard** [comment]
So the summary of this story, for Windows test jobs the location of the TMP env var needs to have at least being conservative 10Gb free.

**Comment by Willsparker** [comment]
Thanks for looking at this @andrew-m-leonard :-)
