### ISSUE TITLE
System unavailable: build-scaleway-ubuntu1604-armv7-1 down

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-infrastructure#2023]
https://ci.adoptopenjdk.net/computer/build-scaleway-ubuntu1604-armv7-1
is not contactable, cannot be re-launched

**Comment by Willsparker** [comment]
Seems to be back up, and I was able to `ssh` to it. Closing :+1:

**Comment by sxa** [comment]
That's because I dealt with it and hadn't come back to close the issue until now :-P
