### ISSUE TITLE
VPC: Debian10 VM disk too small to build a JDK

### ISSUE THREAD

**Issue by Willsparker** [AdoptOpenJDK/openjdk-infrastructure#2033]
Ref: https://ci.adoptopenjdk.net/job/VagrantPlaybookCheck/OS=Debian10,label=vagrant/1104/console
https://ci.adoptopenjdk.net/job/VagrantPlaybookCheck/OS=Debian10,label=vagrant/1103/console

These are both building JDK8 with 'fastmode' on, which installs even less for building the JDK. 

By default the Vagrant VM has only 20GB on it, upon boot.

**Comment by Willsparker** [comment]
The `vagrant disksize` plugin that we use for the Windows VM does work for this VM, however, it doesn't extended the partition in the VM:
```
agrant@adoptopenjdkD10:~$ sudo fdisk -l
Disk /dev/sda: 30 GiB, 32212254720 bytes, 62914560 sectors
Disk model: VBOX HARDDISK   
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0xfcf48969

Device     Boot    Start      End  Sectors  Size Id Type
/dev/sda1  *        2048 39438335 39436288 18.8G 83 Linux
/dev/sda2       39440382 41531391  2091010 1021M  5 Extended
/dev/sda5       39440384 41531391  2091008 1021M 82 Linux swap / Solaris
```

**Comment by sxa** [comment]
A quick fix would be to stop it from building the debug images:
- The default debug support was added here: https://github.com/AdoptOpenJDK/openjdk-build/pull/2488
- But it can be overridden via `CONFIGURE_ARGS`: https://github.com/AdoptOpenJDK/ci-jenkins-pipelines/pull/91/files

**Comment by Willsparker** [comment]
Hmm - I think I'll try that first then. Because, if the Debian10 VM is too low now, it probably won't be long until the rest of them are too low too :+1:

**Comment by Willsparker** [comment]
I've made a branch that are setting those `CONFIGURE_ARGS` before it runs `make-adopt-build-farm.sh`, Testing here: https://ci.adoptopenjdk.net/job/VagrantPlaybookCheck/OS=Debian10,label=vagrant/1106/ 
( The branch is here: https://github.com/Willsparker/openjdk-infrastructure/tree/2033 )

**Comment by Willsparker** [comment]
Ah - that didn't work as https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/2022 hasn't been merged yet

**Comment by Willsparker** [comment]
Rerunning now that it's been merged: https://ci.adoptopenjdk.net/job/VagrantPlaybookCheck/1108/
