### ISSUE TITLE
build-azure-win2016-x64-1: The paging file is too small for this operation to complete' (DOS error/errno=1455)

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-infrastructure#2035]
https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk/job/jdk-windows-aarch64-hotspot/48/console
Looks like a page file issue on: build-azure-win2016-x64-1
```
09:33:58  Attempting to download EA release of boot JDK version 17 from https://api.adoptopenjdk.net/v3/binary/latest/17/ea/windows/x64/jdk/hotspot/normal/adoptopenjdk
09:34:10  BOOT JDK: OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x0000000700000000, 268435456, 0) failed; error='The paging file is too small for this operation to complete' (DOS error/errno=1455)
09:34:10  BOOT JDK: #
09:34:10  BOOT JDK: # There is insufficient memory for the Java Runtime Environment to continue.
09:34:10  BOOT JDK: # Native memory allocation (mmap) failed to map 268435456 bytes for G1 virtual space
09:34:10  BOOT JDK: # An error report file with more information is saved as:
09:34:10  BOOT JDK: # C:\workspace\openjdk-build\hs_err_pid2820.log
```

**Comment by Willsparker** [comment]
The log file the error message is talking about (the pid2820 file wasn't there, I assume it was overwritten by this one) : 
[hs_err_pid9920.txt](https://github.com/AdoptOpenJDK/openjdk-infrastructure/files/6140388/hs_err_pid9920.txt)

**Comment by sxa** [comment]
Just running `java -version` on the latest JDK17 build  at https://api.adoptopenjdk.net/v3/binary/latest/17/ea/windows/x64/jdk/hotspot/normal/adoptopenjdk will likely replicate it although (1) It's not obvious why this has just started happening and (2) It's possible it'll only reproduce when run through jenkins.

**Comment by Willsparker** [comment]
I was able to reproduce it locally on the machine, in the `mintty` terminal:
```
adoptopenjdk@build-azure-win ~/jdk-17+12/bin
$ ./java -version
OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x0000025f5f390000, 4194304, 0) failed; error='The paging file is too small for this operation to complete' (DOS error/errno=1455)
#
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (mmap) failed to map 4194304 bytes for G1 virtual space
# An error report file with more information is saved as:
# C:\cygwin64\home\adoptopenjdk\jdk-17+12\bin\hs_err_pid10084.log
```
ping @gdams

**Comment by andrew-m-leonard** [comment]
and again last night: https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk16/job/jdk16-windows-aarch64-hotspot/60/console

**Comment by sxa** [comment]
This was mitigated by removing the platform as per https://github.com/AdoptOpenJDK/ci-jenkins-pipelines/pull/99
If no-one's actively working on it this shouldn't be in the March milestone.

**Comment by Willsparker** [comment]
I re-ran the `./java -version` as before, a handful of times, and it worked as expected; Not sure why, but it appears the issue isn't there. 

The log I linked to before says the following regarding memory
```
Memory: 4k page, system-wide physical 16383M (9425M free)
TotalPageFile size 20479M (AvailPageFile size 21M)
current process WorkingSet (physical memory assigned to process): 10M, peak: 10M
current process commit charge ("private bytes"): 51M, peak: 307M
```
(keep in mind, this log is old.) I assume the issue was the `current process WorkingSet` category.

When I go on the machine's settings, it says there is no pagefile for the C:\ drive:
![image](https://user-images.githubusercontent.com/52783864/112616022-258a1680-8e1b-11eb-94ab-4cdfba033052.png)

I could check the box, giving it a system managed page file, on the C drive? I'm not 100% on whether that'd help the issue not occur again?

**Comment by sxa** [comment]
Makes no difference where the file is, so if it's got one on D: that should be adequate. Saying that, the platform which this machine was being used to build for is no longer a priority. I'd be in favour of decomissioning the machine.

**Comment by Willsparker** [comment]
I checked again and again, there was no issue in running `./java.exe -version`. May have just been a one-off? As you say, we haven't been building that platform recently so we don't know if it recurs during builds. Do we not have any plans in the near future to carry on building for Windows aarch64, then?

**Comment by sxa** [comment]
Not unless someone gives us hardware, nothing stable/suitable has so far been forthcoming from MSFT.

**Comment by andrew-m-leonard** [comment]
Same issue on node: https://ci.adoptopenjdk.net/computer/build-ibmcloud-win2012r2-x64-2/
https://ci.adoptopenjdk.net/job/Test_openjdk11_j9_sanity.openjdk_x86-64_windows/481/consoleFull
