### ISSUE TITLE
jdk-17 has introduced a new MacOS dependency on XCode tool "metal"

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-infrastructure#2043]
Upstream change: https://github.com/openjdk/jdk/commit/8afec70c283ee549795996031e3a53a3212bf35a#diff-2a012ea02871008e8b925b096d139722b2611e194a1dc312c6513410ecb174a9
Failing nightly builds: https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk/job/jdk-mac-x64-hotspot/387/console
```
08:56:02  checking for metal... [not found]
08:56:02  checking if metal can be run using xcrun... no
08:56:02  configure: error: XCode tool 'metal' neither found in path nor with xcrun
08:56:02  configure exiting with result code 1
08:56:02  Error: No configurations found for /Users/jenkins/workspace/build-scripts/jobs/jdk/jdk-mac-x64-hotspot/workspace/build/src.
```

**Comment by gdams** [comment]
Looks like we need to switch to full blown Xcode rather than the command line tools. I can take a look at this? It's something that we do for the notarization jobs already which use xcrun

**Comment by aahlenst** [comment]
See #2063 for a possible PR.
