### ISSUE TITLE
System unavailable: linux&&riscv64 all offline

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-infrastructure#2066]
https://ci.adoptopenjdk.net/label/linux&&riscv64/
https://ci.adoptopenjdk.net/job/build-scripts/job/utils/job/cross-compiled-version-out/164/console

**Comment by Willsparker** [comment]
ping @gdams 

If absolutely required, we _may_ be able to use a QEMU VM, in a pinch. But they're horrifically slow

**Comment by gdams** [comment]
no idea what happened? They are back up now! I will close and monitor
