### ISSUE TITLE
Ansible request for OpenSSL 1.1.1k on Win build machines

### ISSUE THREAD

**Issue by Willsparker** [AdoptOpenJDK/openjdk-infrastructure#2085]
ref: #2083 

- [x] Missing install
- [ ] Bug in ansible playbook
- [ ] Request for new playbook addition

Details:

As the title suggests. Checklist:

- [ ] build-alibaba-win2012r2-x64-1
- [x] build-alibaba-win2012r2-x64-2
- [x] build-azure-win2012r2-x64-1
- [x] build-azure-win2012r2-x64-2
- [x] build-azure-win2016-x64-1
- [x] build-ibmcloud-win2012r2-x64-1
- [x] build-ibmcloud-win2012r2-x64-2

**Comment by Willsparker** [comment]
Having an issue with `build-ibmcloud-win2012r2-x64-1`:
```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ChunkedEncodingError: ("Connection broken: error(104, 'Connection reset by peer')", error(104, 'Connection reset by peer'))
fatal: [build-ibmcloud-win2012r2-x64-1]: FAILED! => {"msg": "Unexpected failure during module execution.", "stdout": ""}
```
Had this error twice, once whilst building VS2013 32-bit and VS2013 64-bit.

I'll delete those failed build directories and try the next machines.

**Comment by sxa** [comment]
i've deployed on the two alibaba machines via AWX. How's the `ibmcloud` machine looking?

**Comment by Willsparker** [comment]
Still trying. Getting some timeout issues too - thought that may be due to me closing the lid of my laptop

**Comment by Willsparker** [comment]
It failed again - Just doing it manually, it'll be easier.

**Comment by sxa** [comment]
LMK when it's ready - would be good to verify before the nightly pipelines

**Comment by Willsparker** [comment]
All machines done, closing the issue
