### ISSUE TITLE
Build machines with macOS and Apple Silicon

### ISSUE THREAD

**Issue by aahlenst** [AdoptOpenJDK/openjdk-infrastructure#2092]
I need to request a new machine:

- New machine operating system (e.g. linux/windows/macos/solaris/aix): macOS 11
- New machine architecture (e.g. x64/aarch32/arm32/ppc64/ppc64le/sparc): arm
- Provider (leave blank if it does not matter):
- Desired usage: build
- Any unusual specification/setup required:
- How many of them are required: 2

Please explain what this machine is needed for: Building JDK and other tools for macOS on Apple Silicon.

If we already have suitable machines (none are in the inventory), the purpose of this ticket is to record what machines we have, what the terms are, etc.

The playbooks need a cleanup before provisioning the machines.

**Comment by sxa** [comment]
Following machines are now available and [in use](https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk/job/jdk-mac-arm64-hotspot/):
- https://ci.adoptopenjdk.net/computer/build-macstadium-macos11-arm64-1
- https://ci.adoptopenjdk.net/computer/build-macstadium-macos11-arm64-2
