### ISSUE TITLE
Test machines with macOS 11 and Apple Silicon

### ISSUE THREAD

**Issue by aahlenst** [AdoptOpenJDK/openjdk-infrastructure#2093]
I need to request a new machine:

New machine operating system (e.g. linux/windows/macos/solaris/aix): macOS 11
New machine architecture (e.g. x64/aarch32/arm32/ppc64/ppc64le/sparc): arm
Provider (leave blank if it does not matter):
Desired usage: test
Any unusual specification/setup required:
How many of them are required: 2
Please explain what this machine is needed for: Testing JDK and other tools for macOS on Apple Silicon.

We have two machines in the inventory, but they are offline. It's unknown what their state is or what the specs are. So the purpose of this ticket is (a) to bring back the machines and capture all information or (b) get new machines.

The playbooks need a cleanup before provisioning the machines.

**Comment by aahlenst** [comment]
The test machines are gone: https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/2099.

**Comment by sxa** [comment]
The following two machines are now available for test use:
- https://ci.adoptopenjdk.net/computer/test-macstadium-macos11-arm64-1
- https://ci.adoptopenjdk.net/computer/test-macstadium-macos11-arm64-2
