### ISSUE TITLE
Add new s390x Linux machines to build test farm

### ISSUE THREAD

**Issue by tellison** [AdoptOpenJDK/openjdk-infrastructure#21]
Marist have generously created two new Ubuntu 16.04 systems for us.  One is the replacement for our old RHEL6 image (148.100.110.55) while the other is an extra one that we requested to cope with the additional workload.

Both images have 8 Gig Memory / 100G Disk / 4 CP's

Systems:
LXEOJ905  - 148.100.33.178
LXEOJ906  - 148.100.33.179

I have the login details for these for those that need them.

This task is to configure the machines for build/test as appropriate, add the new nodes to Jenkins, Nagios, etc.

**Comment by gdams** [comment]
okay added to the build farm....
