### ISSUE TITLE
System unavailable: Jenkins server (ci.adoptopenjdk.net)

### ISSUE THREAD

**Issue by sxa** [AdoptOpenJDK/openjdk-infrastructure#2101]
- Please put the system name in the title of this issue.

- Link to any log file showing the problem: None - system unresponsive

- Please describe the issue:

Jenkins became unavailable at approximately 3PM last night. There was a brief call (GA/MV) and a restart of jenkins was attempted. This did not work - the server never came back. At around 8PM, SXA started investigating and determined that it was hitting problems being out of heap space.

SXA (for some reason I can't include myself in the assignees list for this issue!) attempted to restart with a larger heap (We'd extended to 16GB a few weeks ago - this increased it to 20GB) This made no difference, it still used it all and didn't fully start up properly. A switch from OpenJ9 to Hotspot VM was performed. This also made no difference to the behavior

SXA attempted to eliminate potential sources of high use, after shutting down the `nginx` frontend to ensure there was no external activity to the server:
- Removal of nodes from the system (Temporarily removal from the jenkins `nodes` directory
- Removal of a subset of plugins

Neither of these made a difference. The jenkins service was starting up at around 9Gb of RAM when it gave the `    INFO    hudson.WebAppMain$3#run: Jenkins is fully up and running` message in the log, but it still was not responding so was unusable on the HTTP port, memory then climbed over the next few minutes until it exhausted all that was available, even after increasing the maximum heap size to 30Gb.

There were some warnings in the jenkins log about being unable to read certain XML files. These were present, but were either zero bytes or had truncated XML in them. Clearing some of them up did not seem to make a difference so it seemed unlikely that this was the cause of the memory leak.

MV then worked with SXA to get garbage collection logs in an attempt to debug what was happening, athough this gave no particular insights into what was happening.

During this investigation we also determined that there was an error in the `/etc/fstab` file although this was unrelated to the memory usage but was resolved nonethtless.

We had also been given a hint that a change had been made to the build job regenerators shortly before the server became unstable. As a result of this, we removed the `jobs/build-scripts/utils` directory to disable the regenerators from running on startup. This succeeded in allowing the server to start up. The server was left to run overnight since all of the build flows should be free to run (the `utils` folder was not the one which contained the signing and installer generators, so there will not have been a problem running those.

---

## Following day:

- Some of the cloud plugins had had their configuration in the top level `config.xml` removed, possibly as a result of some of the the plugins being temporarily unavailable, even though they'd been put back in place in the `plugins` directory. Reinstating those parts of the config from backup and dynamically loading the configuration from disk resoled this.
- Some of the `nodes` were not available. As part of debugging I had only reinstated the node configurations for machines which were live (otherwise the log got a but "noisy" from relaunch attempts. They have now been restored (Copied from `nodes-OFFLINE`). This will not have had any adverse effects as they were offline anyway

---

## Actions required:

- We still need to attempt to restore the `utils` folder. This will involve understanding why the code became leaky and backing out whatever might have caused it, then attempting another jenkins restart. We may be able to redeploy a subset of the `utils` directory if we determine that only part of it is problematic.

**Comment by douph1** [comment]
>During this investigation we also determined that there was an error in the /etc/fstab file although this was unrelated to the memory usage but was resolved nonethtless

The stack trace show during the night show that a http thread is blocking 3 other thread by keeping à lock on hudson.model.RunMap
The thread who get the lock was reading an xml file.
If the fstab was pointing to unstable storage ( nfs / sshfs or ? ) It will certainly block until timeout(or forever)  as shown in stacktrace:

   java.lang.Thread.State: RUNNABLE
        at java.io.FileInputStream.readBytes(Native Method)

and keep the lock on hudson.model.RunMap avoiding other http thread to get it.

Probably two issue for one downtime ...

**Comment by sxa** [comment]
Update:
Attempted restoration of `utils` directory under `build-scripts/utils/jdk11u` after stopping the two `ci-jenkins-pipeline` webhooks on the github side (That restored directory SHOULD just be the workspace directory that it uses) and something triggered it to chew up all the memory again. Since the worksapces should be recreated each time I'm going to leave it empty. The job definitions are still in place.

I've restarted jenkins after deleting those files again The job definitions are still in place

**Comment by sxa** [comment]
I've reinstated all but the `pipeline_jobs_generator_jdk11u*` directories under `build-script/utils` and we've been able to re-run the generator pipelines that we believe may have caused the problems (The log from https://ci.adoptopenjdk.net/job/build-scripts/job/utils/job/pipeline_jobs_generator_jdk11u/67/ was over 2Gb an was repeating messages such as these:
```
[Pipeline] echo
[2021-03-29T09:09:35.337Z] [INFO] Checking if openjdk11-pipeline is running...
[Pipeline] echo
[2021-03-29T09:09:35.355Z] [INFO] openjdk11-pipeline is running. Sleeping for null seconds while waiting for openjdk11-pipeline to complete...
[Pipeline] sleep
[2021-03-29T09:09:35.361Z] No need to sleep any longer
[Pipeline] echo
[2021-03-29T09:09:35.371Z] [INFO] Checking if openjdk11-pipeline is running...
[Pipeline] echo
[2021-03-29T09:09:35.391Z] [INFO] openjdk11-pipeline is running. Sleeping for null seconds while waiting for openjdk11-pipeline to complete...
[Pipeline] sleep
[2021-03-29T09:09:35.399Z] No need to sleep any longer
```
Also as an aside, we had one entry in the jenkins system log last night when debugging with this message:
```
java.io.IOException: Tried to load head FlowNodes for execution Owner[build-scripts/utils/pipeline_jobs_generator_jdk11u/67:build-scripts/utils/pipeline_jobs_generator_jdk11u #67] but FlowNode was not found in storage for head id:FlowNodeId 1:7117985
```
