### ISSUE TITLE
System unavailable: build-osuosl-aix71-ppc64-2 : low disk space

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-infrastructure#2103]
https://ci.adoptopenjdk.net/computer/build-osuosl-aix71-ppc64-2/
@Haroon-Khel fyi
https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk/job/jdk-aix-ppc64-hotspot/466/console

**Comment by Haroon-Khel** [comment]
Closing as Ive freed up 14g of space on the machine
