### ISSUE TITLE
JDK11/openj9 releases fail extended.functional on AIX https://ci.adoptopenjdk.net/label/aix/

### ISSUE THREAD

**Issue by aixtools** [AdoptOpenJDK/openjdk-infrastructure#2106]
Please set the title to indicate the test name and machine name where known.

To make it easy for the infrastructure team to repeat and diagnose, please
answer the following questions:

- test suite/name? TARGET: extended.functional
- Is there an existing issue elsewhere covering this?
- Which machine(s) does it work on?
- Which machine(s) does it fail on? Fails on all AIX systems
- Do you have a link to a Grinder re-run if the test with the failure?
https://ci.adoptopenjdk.net/job/Grinder/parambuild/?TARGET=extended.functional&CUSTOM_TARGET=&SDK_RESOURCE=releases&DEBUG_IMAGES_REQUIRED=true&JDK_BRANCH=&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=&TEST_IMAGES_REQUIRED=true&DOCKER_REQUIRED=false&EXTRA_DOCKER_ARGS=&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&PLATFORM=ppc64_aix&PERSONAL_BUILD=false&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2FAdoptOpenJDK%2Fopenjdk-tests.git&UPSTREAM_TEST_JOB_NUMBER=&DOCKERIMAGE_TAG=&JDK_IMPL=openj9&LABEL=test-ibm-aix71-ppc64-2&EXTRA_OPTIONS=&CUSTOMIZED_SDK_URL=&AUTO_DETECT=true&ADOPTOPENJDK_BRANCH=master&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=AdoptOpenJDK%3Amaster&ARCHIVE_TEST_RESULTS=false&NUM_MACHINES=&TRSS_URL=https%3A%2F%2Ftrss.adoptopenjdk.net&KEEP_WORKSPACE=false&BUILD_LIST=functional&JDK_VERSION=11&UPSTREAM_JOB_NUMBER=&ITERATIONS=1&STF_OWNER_BRANCH=AdoptOpenJDK%3Amaster&TIME_LIMIT=10&JDK_REPO=&OPENJ9_BRANCH=master&OPENJ9_SHA=&RELEASE_TAG=&OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse%2Fopenj9.git&UPSTREAM_JOB_NAME=&JVM_OPTIONS=&PARALLEL=None
Any other details:

* If the sdk_resource is changed to nightly - the tests proceed much further (maybe PASS, but too earely to say)
* A week ago (roughly) when nightly was used as source the build failed immediately, rather than after 2 minutes (so that is a great improvement)
* In short, this is an issue with the 'releases' - ALL AIX systems fail at the same point.
e.g.:
```
00:01:46.978       [echo] Ant version is Apache Ant(TM) version 1.9.9 compiled on February 2 2017
00:01:46.978       [echo] ============COMPILER SETTINGS============
00:01:46.978       [echo] ===fork:                         yes
00:01:46.978       [echo] ===executable:                   /home/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image/bin/javac
00:01:46.978       [echo] ===debug:                        on
00:01:46.978       [echo] ===destdir:                      /home/jenkins/workspace/Grinder/openjdk-tests/TKG/../../jvmtest/functional/DDR_Test
00:01:46.978      [javac] Compiling 56 source files to /home/jenkins/workspace/Grinder/openjdk-tests/functional/DDR_Test/bin
00:01:49.468      [javac] /home/jenkins/workspace/Grinder/openjdk-tests/functional/DDR_Test/src/j9vm/test/ddrext/AutoRun.java:60: error: package com.ibm.j9ddr.tools.ddrinteractive does not exist
00:01:49.468      [javac] import com.ibm.j9ddr.tools.ddrinteractive.Context;
00:01:49.468      [javac]                                          ^
00:01:49.468      [javac] /home/jenkins/workspace/Grinder/openjdk-tests/functional/DDR_Test/src/j9vm/test/ddrext/AutoRun.java:310: error: cannot find symbol
00:01:49.468      [javac] 	public static void runTest(Context ctx, PrintStream out, String testCaseList) {
00:01:49.468      [javac] 	                           ^
00:01:49.468      [javac]   symbol:   class Context
00:01:49.468      [javac]   location: class AutoRun
00:01:49.468      [javac] /home/jenkins/workspace/Grinder/openjdk-tests/functional/DDR_Test/src/j9vm/test/ddrext/DDRExtTesterBase.java:39: error: package com.ibm.j9ddr.tools.ddrinteractive does not exist
00:01:49.468      [javac] import com.ibm.j9ddr.tools.ddrinteractive.CommandUtils;
00:01:49.468      [javac]                                          ^
00:01:49.468      [javac] /home/jenkins/workspace/Grinder/openjdk-tests/functional/DDR_Test/src/j9vm/test/ddrext/DDRExtTesterBase.java:40: error: package com.ibm.j9ddr.tools.ddrinteractive does not exist
```

**Comment by andrew-m-leonard** [comment]
@aixtools I think this is due to a missmatch of the jdk and test tools, see: https://github.com/AdoptOpenJDK/openjdk-tests/issues/2346
jdk-11 January release will need openjdk-tests and TKG from January, not the latest as changes occurred late january.

**Comment by sxa** [comment]
I set `OPENJ9_BRANCH=openj9-0.24.0` in https://ci.adoptopenjdk.net/job/Grinder/8150/console which matched the release version being selected and it passed the build section OK. It didn't get as far as running any tests, but that explains the original issue described here, therefore closing.
