### ISSUE TITLE
AIX 7.2 nodes unable to run extended.functional tests

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-infrastructure#2110]
I've disabled both nodes from running test jobs:
https://ci.adoptopenjdk.net/label/ci.role.testDISABLE/
See:
https://ci.adoptopenjdk.net/view/Test_functional/job/Test_openjdk11_j9_extended.functional_ppc64_aix/121/consoleFull
https://ci.adoptopenjdk.net/view/Test_functional/job/Test_openjdk16_j9_extended.functional_ppc64_aix/52/console

**Comment by sxa** [comment]
I suspect this is a dup of https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/2059 (although perhaps the title needs to be more generic!) ... I'm closing this - if you disagree, re-open
