### ISSUE TITLE
build-equinix-ubuntu2004-armv8-1 intermittently fails to build openj9

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-infrastructure#2119]
https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk16u/job/jdk16u-linux-aarch64-openj9/17/
```
05:38:00  CompileJavaModules.gmk:604: recipe for target '/home/jenkins/workspace/build-scripts/jobs/jdk16u/jdk16u-linux-aarch64-openj9/workspace/build/src/build/linux-aarch64-server-release/jdk/modules/java.desktop/_the.java.desktop_batch' failed
05:38:00  gmake[3]: *** [/home/jenkins/workspace/build-scripts/jobs/jdk16u/jdk16u-linux-aarch64-openj9/workspace/build/src/build/linux-aarch64-server-release/jdk/modules/java.desktop/_the.java.desktop_batch] Error 1
05:38:00  make/Main.gmk:197: recipe for target 'java.desktop-java' failed
05:38:00  gmake[2]: *** [java.desktop-java] Error 1
```
No clear reason, but only fails on this node, and not always

**Comment by sxa** [comment]
I'll take this one since it's sufficiently weird that I'm intrigued by it ;-)

**Comment by sxa** [comment]
Failed in the final run out of the first five attempts: https://ci.adoptopenjdk.net/job/SXA-JDK16J9-aarch64-equinix/
Now attempting a further five in parallel (#6-#10)

This is odd given that it's within docker containers. If I can't identify an obvious reason I'll look at switching off this machine until we can resolve it at some point tomorrow in order to avoid any risk to next week's GAs.

**Comment by sxa** [comment]
Hmmm [one of my builds](https://ci.adoptopenjdk.net/job/SXA-JDK16J9-aarch64-equinix/9/console) has come up with this:
```
17:38:08  ccache: error: /home/jenkins/.ccache/ccache.conf: No such file or directory
```
I wonder if it's hitting a race condition (Entirely possible on a machine with 160 cores)
I'll

**Comment by sxa** [comment]
Nope - still happening with ccache disabled

**Comment by sxa** [comment]
And also still a problem with the build reduced to use 16 cores. ...

**Comment by sxa** [comment]
Have removed the `dockerBuild` label from the machine for now. Very odd problem though ...

**Comment by sxa** [comment]
Current testing:
- Does it fail with `--with-jobs=1`. So far, no [84](https://ci.adoptopenjdk.net/job/SXA-JDK16J9-aarch64-equinix/84/) [84](https://ci.adoptopenjdk.net/job/SXA-JDK16J9-aarch64-equinix/84/) [85](https://ci.adoptopenjdk.net/job/SXA-JDK16J9-aarch64-equinix/85/) [86](https://ci.adoptopenjdk.net/job/SXA-JDK16J9-aarch64-equinix/86/) [87](https://ci.adoptopenjdk.net/job/SXA-JDK16J9-aarch64-equinix/87/) [88](https://ci.adoptopenjdk.net/job/SXA-JDK16J9-aarch64-equinix/88/) [95](https://ci.adoptopenjdk.net/job/SXA-JDK16J9-aarch64-equinix/95/)
- Does it fail running on a CentOS8 host system (i.e. not docker). So far no: [83](https://ci.adoptopenjdk.net/job/SXA-JDK16J9-aarch64-equinix/83/) [89](https://ci.adoptopenjdk.net/job/SXA-JDK16J9-aarch64-equinix/89/) [90](https://ci.adoptopenjdk.net/job/SXA-JDK16J9-aarch64-equinix/90/) [91](https://ci.adoptopenjdk.net/job/SXA-JDK16J9-aarch64-equinix/91/) [92](https://ci.adoptopenjdk.net/job/SXA-JDK16J9-aarch64-equinix/92/) [93](https://ci.adoptopenjdk.net/job/SXA-JDK16J9-aarch64-equinix/93/) [94](https://ci.adoptopenjdk.net/job/SXA-JDK16J9-aarch64-equinix/94/) [96](https://ci.adoptopenjdk.net/job/SXA-JDK16J9-aarch64-equinix/96/) [97](https://ci.adoptopenjdk.net/job/SXA-JDK16J9-aarch64-equinix/97/) [98](https://ci.adoptopenjdk.net/job/SXA-JDK16J9-aarch64-equinix/98/) [99](https://ci.adoptopenjdk.net/job/SXA-JDK16J9-aarch64-equinix/99/) [100](https://ci.adoptopenjdk.net/job/SXA-JDK16J9-aarch64-equinix/100/)
- Does it fail outside jenkins in a docker container?
- Does it fail in a docker container with the file system mapped to the host?

**Comment by sxa** [comment]
OK - almost all the failures are at this point:
```
18:48:24  Updating support/src.zip
18:48:45  CompileJavaModules.gmk:604: recipe for target '/home/jenkins/workspace/SXA-JDK16J9-aarch64-equinix@6/workspace/build/src/build/linux-aarch64-server-release/jdk/modules/java.desktop/_the.java.desktop_batch' failed
18:48:45  gmake[3]: *** [/home/jenkins/workspace/SXA-JDK16J9-aarch64-equinix@6/workspace/build/src/build/linux-aarch64-server-release/jdk/modules/java.desktop/_the.java.desktop_batch] Error 1
18:48:45  make/Main.gmk:197: recipe for target 'java.desktop-java' failed
18:48:45  gmake[2]: *** [java.desktop-java] Error 1
18:48:45  gmake[2]: *** Waiting for unfinished jobs....
```
The one failure I've seen on the CentOS host systems was at this point in run 106
```
18:22:47  Compiling 5507 files for openj9.dtfj
18:22:49  Creating jdk/modules/jdk.jpackage/jdk/jpackage/internal/resources/jpackageapplauncher from 15 file(s)
18:23:08  gmake[3]: *** [CompileJavaModules.gmk:605: /home/jenkins/workspace/SXA-JDK16J9-aarch64-equinix@4/workspace/build/src/build/linux-aarch64-server-release/jdk/modules/openj9.dtfj/_the.openj9.dtfj_batch] Error 1
18:23:08  gmake[2]: *** [make/Main.gmk:197: openj9.dtfj-java] Error 2
```
115 failed in a container on the CentOS8 source but that was a different problem as it didn't get as far as running the build:

**Comment by sxa** [comment]
https://ci.adoptopenjdk.net/job/SXA-JDK16J9-aarch64-equinix/150/consoleFull failed with the build set to only use a single core (First time I've seen that):
```

15:39:07  Compiling 56 files for java.sql.rowset
15:39:07  Compiling 275 files for java.xml.crypto
15:39:10  Compiling 1 files for java.se
15:39:11  Compiling 22 files for java.smartcardio
15:39:13  CompileJavaModules.gmk:604: recipe for target '/home/jenkins/workspace/SXA-JDK16J9-aarch64-equinix@6/workspace/build/src/build/linux-aarch64-server-release/jdk/modules/java.smartcardio/_the.java.smartcardio_batch' failed
15:39:13  gmake[3]: *** [/home/jenkins/workspace/SXA-JDK16J9-aarch64-equinix@6/workspace/build/src/build/linux-aarch64-server-release/jdk/modules/java.smartcardio/_the.java.smartcardio_batch] Error 1
15:39:13  make/Main.gmk:197: recipe for target 'java.smartcardio-java' failed
15:39:13  gmake[2]: *** [java.smartcardio-java] Error 1
```

**Comment by sxa** [comment]
Hmmm I've just done 20 builds on this machine using a HotSpot boot JDK instead of OpenJ9 15.0.2-ea and have had zero failures. Given that this is an ea and the issue appears to be when processing java code I'm inclined to say that whatever we're seeing is specific to the OpenJ9 boot JDK at the moment.

Tagging @pshipton @0xdaryl for any input - this is happening on a 160 core Ampere Altra (armsystem but as per previous messages it has been seen even with --with-cores=1)

**Comment by pshipton** [comment]
Have you tried a new boot JVM? You can use OpenJ9 16 to build 16. Given that aarch64 is ea, you can expect there are number of problems fixed in the newer release.

**Comment by sxa** [comment]
Have been testing 16 for the last half hour - I got a failure in each of 10 attempts, so it seems to be worse than 15

**Comment by vielmetti** [comment]
One thought I had was to pull the latest version of Docker and see if the problem persists. I agree that 160 cores gives you lots of room for race conditions, especially within a containerized environment.

**Comment by sxa** [comment]
> Which 16 are you trying, the last release or the latest nightly build? Might as well try the latest.

It was last release, but I'm conscious of how much time it's taking at the moment for me to run the variations I already have

**Comment by sxa** [comment]
> One thought I had was to pull the latest version of Docker and see if the problem persists. I agree that 160 cores gives you lots of room for race conditions, especially within a containerized environment.

Yeah I've already eliminated that (since it was something you suggested to me I added it to the list of things to try) I'm on `20.10.6~3-0~ubuntu-focal` from the standalone docker repos and it hasn't made a difference. I'll be honest I think I've eliminated core count explicitly as a cause since I got the same when forcing the build to only use one core for the builds.

**Comment by sxa** [comment]
On some of the runs I've had problems with the `jvmti` compilations which seem similar to those seen occasionally on AIX (Ref: https://github.com/eclipse/openj9/issues/12061)
e.g.
```
Creating javadoc element list
In file included from ./src/hotspot/share/oops/arrayKlass.cpp:31:0:
./build/linux-aarch64-server-release/hotspot/variant-server/gensrc/jvmtifiles/jvmti.h:1589:5: error: expected identifier before ')' token
     );
     ^
```
and
```
Creating javadoc element list
./build/linux-aarch64-server-release/hotspot/variant-server/gensrc/jvmtifiles/jvmtiEnterTrace.cpp: In function 'jvmtiError jvmtiTrace_RedefineClasses(jvmtiEnv*, jint, const jvmtiClassDefinition*)':
./build/linux-aarch64-server-release/hotspot/variant-server/gensrc/jvmtifiles/jvmtiEnterTrace.cpp:9051:36: error: no matching function for call to 'JvmtiEnv::RedefineClasses()'
   err = jvmti_env->RedefineClasses();
                                    ^
In file included from ./src/hotspot/share/prims/jvmtiEnter.inline.hpp:29:0,
                 from ./build/linux-aarch64-server-release/hotspot/variant-server/gensrc/jvmtifiles/jvmtiEnterTrace.cpp:33:
./build/linux-aarch64-server-release/hotspot/variant-server/gensrc/jvmtifiles/jvmtiEnv.hpp:160:16: note: candidate: jvmtiError JvmtiEnv::RedefineClasses(jint, const jvmtiClassDefinition*)
     jvmtiError RedefineClasses(jint class_count, const jvmtiClassDefinition* class_definitions);
                ^~~~~~~~~~~~~~~
./build/linux-aarch64-server-release/hotspot/variant-server/gensrc/jvmtifiles/jvmtiEnv.hpp:160:16: note:   candidate expects 2 arguments, 0 provided
./build/linux-aarch64-server-release/hotspot/variant-server/gensrc/jvmtifiles/jvmtiEnterTrace.cpp: In function 'jvmtiError jvmtiTrace_GetObjectSize(jvmtiEnv*, jobject, jlong*)':
./build/linux-aarch64-server-release/hotspot/variant-server/gensrc/jvmtifiles/jvmtiEnterTrace.cpp:9125:34: error: no matching function for call to 'JvmtiEnv::GetObjectSize()'
   err = jvmti_env->GetObjectSize();
                                  ^
```

**Comment by sxa** [comment]
Looks like it might be ok with the latest JDK16 nightly - I've been able to run it ten times without a failure on this one:
```
BOOT JDK: openjdk version "16" 2021-03-16
BOOT JDK: OpenJDK Runtime Environment AdoptOpenJDK-16+36-202104192334 (build 16+36-202104192334)
BOOT JDK: Eclipse OpenJ9 VM AdoptOpenJDK-16+36-202104192334 (build master-21140c9f9, JRE 16 Linux aarch64-64-Bit Compressed References 20210419_22 (JIT enabled, AOT enabled)
BOOT JDK: OpenJ9   - 21140c9f9
BOOT JDK: OMR      - 840473a5d
BOOT JDK: JCL      - 073accb86d based on jdk-16+36)
```

**Comment by pshipton** [comment]
The failures mentioned in https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/2119#issuecomment-823216467 are compiling C/C++ code, not sure why this would have anything to do with the boot JDK.

**Comment by andrew-m-leonard** [comment]
> The failures mentioned in [#2119 (comment)](https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/2119#issuecomment-823216467) are compiling C/C++ code, not sure why this would have anything to do with the boot JDK.

@pshipton it's not the C compilation, it's the fact that the GenJvmti.java "build tool" that generates the C source which fails to compile, is run using the boot jdk and for whatever reason generates bad C source with openj9, but not with hotspot.

**Comment by sxa** [comment]
Latest GA of 16 also seems to fail: https://ci.adoptopenjdk.net/job/SXA-JDK16J9-aarch64-equinix/180/consoleFull
```
18:51:25  BOOT JDK: openjdk version "16.0.1-ea" 2021-04-20
18:51:25  BOOT JDK: OpenJDK Runtime Environment AdoptOpenJDK-16.0.1+9 (build 16.0.1-ea+9)
18:51:25  BOOT JDK: Eclipse OpenJ9 VM AdoptOpenJDK-16.0.1+9 (build openj9-0.26.0, JRE 16 Linux aarch64-64-Bit Compressed References 20210421_23 (JIT enabled, AOT enabled)
18:51:25  BOOT JDK: OpenJ9   - b4cc246d9
18:51:25  BOOT JDK: OMR      - 162e6f729
18:51:25  BOOT JDK: JCL      - cea22090ecf based on jdk-16.0.1+9)
```

**Comment by sxa** [comment]
In light of the above PR I've re-enabled the `dockerBuild` tag on the subject machine.
