### ISSUE TITLE
build-osuosl-aix71-ppc64-1 missing bootjdk

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-infrastructure#2127]
See failure: https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-aix-ppc64-hotspot/957/console
```
09:44:29  Detecting boot jdk for: jdk8u
09:44:29  Found build version: 8
09:44:29  Required boot JDK version: 7
09:44:29  [SUCCESS] Executing local file at /home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-aix-ppc64-hotspot/build-farm/platform-specific-configurations/aix.sh
09:44:29  Using default /tmp for temporary files as /ramdisk0/build/tmp does not exist
09:44:29  LDR_CNTRL=
09:44:29  BOOT JDK: /home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-aix-ppc64-hotspot/build-farm/platform-specific-configurations/aix.sh: line 102: /home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-aix-ppc64-hotspot/jdk-7/bin/java: A file or directory in the path name does not exist.
```

jdk-7 is default generated by build scripts, because it failed to find the jdk pointed to by the ENV var JDK7_BOOT_DIR which is set to: /home/bootjdk8 this folder does not exist

**Comment by sxa** [comment]
@Haroon-Khel  You've resolved this now haven't you?

**Comment by Haroon-Khel** [comment]
Yes. Didnt know an issue had been raised for it. Ill run a jdk 8 build on the machine before closing

**Comment by Haroon-Khel** [comment]
https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-aix-ppc64-hotspot/960/console

**Comment by Haroon-Khel** [comment]
Build passed. Closing
