### ISSUE TITLE
Start using a "qemu" label for QemuPlaybookCheck jobs

### ISSUE THREAD

**Issue by sxa** [AdoptOpenJDK/openjdk-infrastructure#2131]
We've now got more than one machine able to run the QemuPlaybookCheck jobs. They had been defined to use the `vagrant` label, since we always had vagrant and qemu on the same machines. Since the other machines don't run vagrant (And aren't x64 so won't in the same way) we should introduce a `qemu` label that we can use on the existing vagrant ones and https://ci.adoptopenjdk.net/computer/build-equinix-ubuntu2004-armv8-1/

**Comment by Willsparker** [comment]
I've added `qemu` to the `infra-ibmcloud-vagrant-x64-1.*` machines and to `build-equinix-ubuntu2004-armv8-1`. I've reconfigured `QPC` to run the `qemu` label, and have kicked off run [241](https://ci.adoptopenjdk.net/job/QEMUPlaybookCheck/241/) to double check it. It's started as expected, on 2 of the ibmcloud nodes, and they're now at the point of running the playbooks, so the changes have worked :+1: Closing issue
