### ISSUE TITLE
test-azure-win2019-x64-1: jdk_rmi java/rmi/Naming/legalRegistryNames/LegalRegistryNames.java test failure

### ISSUE THREAD

**Issue by lumpfish** [AdoptOpenJDK/openjdk-infrastructure#2133]
test-azure-win2019-x64-1: jdk_rmi java/rmi/Naming/legalRegistryNames/LegalRegistryNames.java fails on ` test-azure-win2019-x64-1`.  It does not fail on ` test-aws-win2019-x64-1`

It fails on openj9 and hotspot, jdk8  jdk11 and jdk16. 

Failing job link: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/80/console

To rerun just the failing test
```
 https://ci.adoptopenjdk.net/job/Grinder/parambuild/?JDK_VERSION=8&JDK_IMPL=hotspot&JDK_VENDOR=adoptopenjdk&BUILD_LIST=openjdk&PLATFORM=x86-64_windows&CUSTOM_TARGET=jdk/test/java/rmi/Naming/legalRegistryNames/LegalRegistryNames.java&TARGET=jdk_custom_1
```
Several subtests fail with a `java.net.MalformedURLException` such as:
```
17:48:20  testing form: rmi://test-win2019dc-/MyName
17:48:20  java.net.MalformedURLException: invalid authority: rmi://test-win2019dc-/MyName
17:48:20  	at java.rmi.Naming.intParseURL(Naming.java:330)
17:48:20  	at java.rmi.Naming.parseURL(Naming.java:237)
17:48:20  	at java.rmi.Naming.rebind(Naming.java:171)
17:48:20  	at LegalRegistryNames.main(LegalRegistryNames.java:89)
17:48:20  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
17:48:20  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
17:48:20  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
17:48:20  	at java.lang.reflect.Method.invoke(Method.java:498)
17:48:20  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
17:48:20  	at java.lang.Thread.run(Thread.java:748)
17:48:20  	unexpected lookup or unbind exception for form: rmi://test-win2019dc-/MyNameinvalid authority: rmi://test-win2019dc-/MyName
```
According to https://en.wikipedia.org/wiki/Hostname, hostnames cannot end with a hyphen. On that basis, the test is failing correctly.

The hostname value used in the test is assigned as follows:
```
localHostName = InetAddress.getLocalHost().getHostName();
```
So I assume there is something in the configuration of `test-azure-win2019-x64-1` which is incorrect - computer name or a registry entry?

**Comment by Willsparker** [comment]
Having a look now,
Following the steps listed [here](https://www.server-world.info/en/note?os=Windows_Server_2019&p=initial_conf&f=3#:~:text=Run%20%5BServer%20Manager%5D%20and%20select,section%20on%20the%20right%20pane.&text=Move%20to%20%5BComputer%20Name%5D%20tab,and%20click%20%5BChange%5D%20button.&text=Input%20any%20Computer%20Name%20you,button.), I've changed the hostname to remove the hyphen to `test-win2019dc`, the machine is restarting now for those changes to take effect

**Comment by Willsparker** [comment]
Machine is back up now, and the name has changed as it should. Rerunning grinder: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/91/console

**Comment by Willsparker** [comment]
Grinder ran green! Closing issue. Thanks @lumpfish for the comprehensive instructions! :grin:

**Comment by lumpfish** [comment]
Do we know how / why the hostname was incorrect? Is it the way the machine was given to us, or did we configure it (manually or via ansible)?  If it was given to us like that, is there something we could put into ansible to check it's not invalid?

**Comment by Willsparker** [comment]
AFAIK (and what I could briefly search), we don't set the host-name as part of the playbook (at least, for Windows). I think it's either given to us, or set when the machine is provisioned - however, we could fairly easily add a check in Ansible - It'd just be a case of getting the output of `hostname` from cmd.exe , and checking it doesn't end in `-`.

**Comment by lumpfish** [comment]
> checking it doesn't end in -

"Checking that it's correct" would be better - if we had a notion of what "correct" is.

**Comment by sxa** [comment]
The machine, as defined in Azure, is called `test-win2019dc-1` which suggests that something has truncated it. Our build machines have a similar hostname convention but prefixed `bld` rather than `test` which is one fewer characters. There has historically been a limit on the NetBIOS name of Windows systems, so my guess would be that the azure deployments truncate to 15 characters. [test-win2016dc-1](https://ci.adoptopenjdk.net/computer/test-azure-win2016-x64-1/) has the same problem (The final `1` is not present). Based on @lumpfish's research it would appear that Azure are deploying systems with invalid hostnames in this case.

@Willsparker I'd suggest `test-win2019dc1` would be better to allow for a convention with more than one machine, and I'd also suggest making the same change on the equivalent 2016 machine.

**Comment by Willsparker** [comment]
Okay, I've renamed `test-win2019dc` to `test-win2019-1`, and `TEST-WIN2016DC-` to `TEST-WIN2016-1`. Restarted both machines (after checking that nothing was running on them), and they both display the correct names when running `hostname` in cmd. 

> "Checking that it's correct" would be better - if we had a notion of what "correct" is.

Well, we could go off the Wikipedia article! From reading it, I gathered the following rules:
* Maximum of 253 ASCII characters, 63 per label, a label being each section split by a dot (`.`)
* Each label can only have `a-z,A-Z,0-9` and a hyphen in it, but can't end in a hyphen
* A label probably shouldn't start with a digit, but definitely shouldn't start with a hyphen

The rules are probably better defined in [RFC 1178](https://tools.ietf.org/html/rfc1178), but that's a lot of reading.

**Comment by sxa** [comment]
I think it's fair to say that most of those scenarios are pretty unlikely. If we really want to do a check I'd be ok with just the `-` thing since that's the only one that's likely to bite us (Famous last words ... I shouldn't have put this in writing ...)

**Comment by Willsparker** [comment]
You're a brave man :sweat_smile: . I'll look into creating an Ansible task :-)
