### ISSUE TITLE
test-ibm-aix71-ppc64-2: build error: keytool error: java.lang.Exception: Input not an X.509 certificate

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-infrastructure#2137]
https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-aix-ppc64-hotspot/966/console
```
10:19:26  Processing certificate with alias: C=BE,O=GlobalSign nv-sa,OU=Root CA,CN=GlobalSign Root CA
10:19:27  keytool error: java.lang.Exception: Input not an X.509 certificate
```

**Comment by andrew-m-leonard** [comment]
Works on test-ibm-aix71-ppc64-1
https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-aix-ppc64-hotspot/967/consoleFull

**Comment by sxa** [comment]
It's what I had suspected - The failing machine is using an IBM boot JDK:
```
10:15:38  BOOT JDK: java version "1.7.0"
10:15:38  BOOT JDK: Java(TM) SE Runtime Environment (build pap6470sr10fp60-20200113_02(SR10 FP60))
10:15:38  BOOT JDK: IBM J9 VM (build 2.6, JRE 1.7.0 AIX ppc64-64 Compressed References 20191221_435663 (JIT enabled, AOT enabled)
10:15:38  BOOT JDK: J9VM - R26_Java726_SR10_20191221_0017_B435663
10:15:38  BOOT JDK: JIT  - r11_20191221_435663
10:15:38  BOOT JDK: GC   - R26_Java726_SR10_20191221_0017_B435663_CMPRSS
10:15:38  BOOT JDK: J9CL - 20191221_435663)
10:15:38  BOOT JDK: JCL - 20200110_01 based on Oracle jdk7u251-b07
```
And the passing one is using an openjdk7 from `/usr/j2sdk-image`:
```
10:53:13  BOOT JDK: openjdk version "1.7.0-internal"
10:53:13  BOOT JDK: OpenJDK Runtime Environment (build 1.7.0-internal-jvmtests_2017_05_20_22_30-b00)
10:53:13  BOOT JDK: OpenJDK 64-Bit Server VM (build 24.95-b00, mixed mode)
```
If I switch the other machine to have `JDK7_BOOT_DIR=/usr/j2sdk-image` it passes: https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-aix-ppc64-hotspot/968/console

However ... (I'll continue in the next comment)

**Comment by sxa** [comment]
I failed to continue in the next comment because I talked myself out of it as what I was going to say was invalid for the production pipelines. Closing.

**Comment by andrew-m-leonard** [comment]
@sxa Same problem with node https://ci.adoptopenjdk.net/computer/test-osuosl-aix71-ppc64-1 i've updated to use JDK7_BOOT_DIR=/usr/j2sdk-image
