### ISSUE TITLE
Move TMP & Page File directory for all Windows nodes from C: to the workspace drive with plenty of disk space

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-infrastructure#2155]
TMP location is causing testcase failures due to C: not having enough space,
suggest moving TMP via Jenkin node config to the workspace drive on each win node

**Comment by andrew-m-leonard** [comment]
Jenkins node agent ENV config:
eg.set TMP to
E:\jenkins\jenkinstmp

**Comment by andrew-m-leonard** [comment]
Also verify windows Page file location on each node.

**Comment by andrew-m-leonard** [comment]
@Willsparker if you have a look at this, we can have a call to discuss

**Comment by adamfarley** [comment]
Will take a look at this this afternoon. Include me on any call please.

**Comment by adamfarley** [comment]
After discussing this with Andrew, this seems something that can only be effected by someone with access to the environment variables configuration for each jenkins node (located in one of the side-options on a "https://ci.adoptopenjdk.net/computer/node-name" page).

In short, the plan is to
- Wait until the release is complete.
- Identify all Windows nodes that have minimal free space on their C drives.
- Change the TMP environment variable path to E:\jenkins\jenkinstmp (on those nodes).
- run extended.functional/extended.sanity on those machines to verify the fix.
- Close issue.
- Ice cream.

**Comment by sxa** [comment]
> Change the TMP environment variable path to E:\jenkins\jenkinstmp (on those nodes).
There is no guarantee that an `E:` drive is valid for this - it may be different per machines/provider

> run extended.functional/extended.sanity on those machines to verify the fix.
If we know the individual tests that trigger the problems, presumably we can identify a smaller Grinder that demonstrates the problem and can therefore demonstrate that the fix works when applied? @andrew-m-leonard do you have a job log that shows which tests fail because of this?

**Comment by Willsparker** [comment]
As a further to @sxa 's comment, IIRC, there are some (test) machines that only have `C:\`. I'd need to check to confirm that though.

I could certainly try this with a single machine first, to see if it fixes the issues though (post release) :)

**Comment by andrew-m-leonard** [comment]
https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/2154

**Comment by andrew-m-leonard** [comment]
https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/2019

**Comment by andrew-m-leonard** [comment]
build-alibaba-win2012r2-x64-2 - C: 200Gb free space - Fine
build-azure-win2012r2-x64-2 - C: 8Gb fails : 
build-ibmcloud-win2012r2-x64-2
test-aws-win2019-x64-1
test-aws-win2019-x64-2
test-azure-win2012r2-x64-1
test-azure-win2012r2-x64-3
test-azure-win2016-x64-1
test-azure-win2019-x64-1
test-gdams-win10-aarch64-1
test-ibmcloud-win2012r2-x64-1
test-ibmcloud-win2012r2-x64-2
test-packet-win2012r2-x64-1

**Comment by andrew-m-leonard** [comment]
Active machines all changed, test grinder re-runs look good.

**Comment by sxa** [comment]
Recording recreate instructions for future reference. [Grinder](https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder) with:
- `BUILDLIST=openjdk`
- `TARGET=jdk_custom`
- `CUSTOM_TARGET=jdk/test/java/nio/channels/FileChannel/LoopingTruncate.java`
