### ISSUE TITLE
test-marist-ubuntu1804-s390x-3 git not setup correctly, missing symlink?

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-infrastructure#2171]
https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_sanity.perf_s390x_linux/171/console
```
Caused by: java.io.IOException: Cannot run program "/usr/local/bin/git" (in directory "/home/jenkins/workspace/Test_openjdk8_j9_sanity.perf_s390x_linux/openjdk-tests"): error=2, No such file or directory
```

Looks like there is no symlink for /usr/local/bin/git on this node?

**Comment by andrew-m-leonard** [comment]
Node is now marked offline until this issue is fixed: https://ci.adoptopenjdk.net/computer/test-marist-ubuntu1804-s390x-3/

**Comment by Willsparker** [comment]
As you say, there appears to be a missing symlink, `/usr/bin/git` is there. I can create the symlink easily enough, but why is it looking for `/usr/local/bin/git` specifically? I would've expected it just used system git ..

Should be fixed now

**Comment by Willsparker** [comment]
Well, I enabled the machine again, and a queued job starting running on it: https://ci.adoptopenjdk.net/job/Test_openjdk17_j9_extended.system_s390x_linux/34/
If this ends up being okay, I'll close the issue :+1:
