### ISSUE TITLE
System unavailable: test-azure-win2016-x64-1 ERROR: Cannot delete workspace

### ISSUE THREAD

**Issue by lumpfish** [AdoptOpenJDK/openjdk-infrastructure#2173]
Test job failed to start on  test-azure-win2016-x64-1 due to:
```
[WS-CLEANUP] Deleting project workspace...
[WS-CLEANUP] Deferred wipeout is used...
ERROR: Cannot delete workspace :Unable to delete 'C:\Users\jenkins\workspace\Grinder'. Tried 3 times (of a maximum of 3) waiting 0.1 sec between attempts.
[Pipeline] }
[Pipeline] // node
[Pipeline] }
[Pipeline] // stage
[Pipeline] End of Pipeline
ERROR: Cannot delete workspace: Unable to delete 'C:\Users\jenkins\workspace\Grinder'. Tried 3 times (of a maximum of 3) waiting 0.1 sec between attempts.
Finished: FAILURE
```
Failing job link: https://ci.adoptopenjdk.net/job/Grinder/522/console

**Comment by Willsparker** [comment]
Looks like a leftover Java process - Stopping and manually deleting the workspace. Not sure why that process wasn't automatically cleaned up though .. possibly an outlier given this hasn't happened before.
The folder was last modified on 29/4/21, so the process has been hanging around for awhile.
