### ISSUE TITLE
openjdk-tests pull request build do not have write access to the repo

### ISSUE THREAD

**Issue by sophia-guo** [AdoptOpenJDK/openjdk-infrastructure#218]
GitHub pull request #254 of commit 9ab471b9ae0d52328b27df495542202de462f900, no merge conflicts.
Setting status of 9ab471b9ae0d52328b27df495542202de462f900 to PENDING with url https://ci.adoptopenjdk.net/job/PR_sanity_openjdk_test_x86-64_linux/239/ and message: 'Build Started'
Using context: running openjdk sanity tests with openjdk8
FileNotFoundException means that the credentials Jenkins is using is probably wrong. Or the user account does not have write access to the repo.
org.kohsuke.github.GHFileNotFoundException: 

Which also make build as a jenkins user do not have write permission too. E.g. in pull reques build we cannot create folders or copy files.

Either jenkins configure system GitHub Pull Request Builder section credentials setting up or openjdk-test repo setting up have some issue. Suspect settings of  openjdk-test repo does not add bot user have write permission.

**Comment by sxa555** [comment]
@sophia-guo @smlambert Is this still an issue? It's been around for over a year now

**Comment by smlambert** [comment]
This was requested back then, as we wanted to enable PR testing for openjdk-tests changes.  We currently run Grinder jobs instead to test changes, which seems to accomplish what we need, which is to verify our changes prior to committing them.

You can close this.
