### ISSUE TITLE
Fix security vulnerability report for the two AIX openjdk systems at OSUOSL

### ISSUE THREAD

**Issue by tellison** [AdoptOpenJDK/openjdk-infrastructure#22]
OSUOSL system administrators have received a security vulnerability report about our two AIX openjdk systems hosted at OSUOSL.

Details available privately upon request.

This issue covers resolving the vulnerabilities and reporting the actions taken back to OSUOSL.

**Comment by tellison** [comment]
Changes have been made to address the problem.  Now waiting for confirmation from OSUOSL admins that the fix is good.

**Comment by gdams** [comment]
@tellison are we okay to close this now?

**Comment by tellison** [comment]
OSUOSL are happy again, so closing
