### ISSUE TITLE
Test Build failed for "sh: 1: Cannot fork "

### ISSUE THREAD

**Issue by sophia-guo** [AdoptOpenJDK/openjdk-infrastructure#235]
Suspect it's a jenkins setting up or master-slave network issue. Details:
https://github.com/AdoptOpenJDK/openjdk-tests/issues/274

**Comment by sophia-guo** [comment]
Could anyone label this as urgent, which make build fail and exit?

**Comment by sophia-guo** [comment]
Happened again:
https://ci.adoptopenjdk.net/view/OpenJDK%20tests/job/openjdk8_hs_openjdktest_x86-64_linux/39/console

**Comment by sxa555** [comment]
Both test machines were configured with two executors - have dropped this to one as it could be purely down to overloading the machines - the CPU load was sitting around 14 on the scaleway box.

Machines changed:
- https://ci.adoptopenjdk.net/computer/test-scaleway-ubuntu1604-x64-1/
- https://ci.adoptopenjdk.net/computer/test-packet-ubuntu1604-x64-1/

**Comment by sophia-guo** [comment]
For https://ci.adoptopenjdk.net/computer/test-packet-ubuntu1604-x64-1/ I can still see there are two executors.

**Comment by sophia-guo** [comment]
If it's due to machine changes I should see this issue twice at most. Once for each machine unless the change is back and forward. 
Confused seems it happened more than twice.

If this wont happen again I will close this.

**Comment by sxa555** [comment]
@sophia-guo It may have still been showing 2 when you looked because there were already jobs running on both executors and the change can't take effect until one of them is freed.

**Comment by gdams** [comment]
@sophia-guo could you let us know if you see this again with @sxa555's changes applied. If not I will close this issue in the next day or two

**Comment by sophia-guo** [comment]
The last time I saw it is on Feb 27. Ever since that didn't see it again. Suppose it should be good to close it.
