### ISSUE TITLE
build-marist-s390x-sles-12 can't resolve itself

### ISSUE THREAD

**Issue by sxa555** [AdoptOpenJDK/openjdk-infrastructure#24]
I'm getting an issue on `build-marist-s390x-sles-12` (148.100.110.56) where it is unable to resolve it's own hostname. Can we get an entry for `openjdk-sles12` (The output from `hostname`) added to `/etc/hosts` on the machine - either with it's real IP or just to 127.0.0.1 please so that it resolves? This is causing some tests to fail as per https://github.com/AdoptOpenJDK/openjdk-systemtest/issues/9

**Comment by karianna** [comment]
@bblondin Would this be an ansible thing?

**Comment by gdams** [comment]
okay this should be done now:

```bash
linux1@openjdk-sles12:~> getent hosts openjdk-sles12
148.100.110.56  openjdk-sles12
```

**Comment by gdams** [comment]
@sxa555 are you happy for me to close this now?

**Comment by sxa555** [comment]
yep looks good - closing
