### ISSUE TITLE
Nagios - Marist systems are noisy in slack channel 

### ISSUE THREAD

**Issue by bblondin** [AdoptOpenJDK/openjdk-infrastructure#246]
https://adoptopenjdk.slack.com/messages/C8C212BU6

Most of the warning slack messages from Nagios are for Marist systems ```build-marist-ubuntu1604-s390x-?```

**Comment by bblondin** [comment]
Work was done in issue #272 adding the `-k` flag to `check_proc` 
This should address messages for the services: `Zombie Processes` and `Total Processes`

**Comment by karianna** [comment]
I'll close this for now as it's no noisier than other hosts.
