### ISSUE TITLE
Add new test machines to infrastructure

### ISSUE THREAD

**Issue by tellison** [AdoptOpenJDK/openjdk-infrastructure#249]
I have created two new linux x64 machines for use by the general testing jobs.

They are hosted at Softlayer with hoistname, IP address, and logins as follows:
```
  test-softlayer-ubuntu1604-x64-1
  169.55.150.155
  root/********
```

and

```
   test-softlayer-rhel7-x64-1
   169.55.170.70
   root/********
```

These machines need configuring with Ansible, adding to Nagios and Jenkins etc to be made available for test.
Heads-up to @smlambert when they are done.

**Comment by bblondin** [comment]
Created pull request #248 to add these systems to the Ansible inventory

**Comment by bblondin** [comment]
**To do List:**

- [ ] Add systems to Keybox
- [ ] Update keybox's profile 'root_test_machines' to include these systems
- [ ] Create pull request to add these systems to the Ansible inventory file
- [ ] Create new entries in secrets gpg
- [ ] Refresh Ansible dynamic inventory 
- [ ] Execute Playbook on these systems

**Comment by bblondin** [comment]
Running playbook now - AWX job number 20839

**Comment by bblondin** [comment]
playbook failed... need to investigate

**Comment by bblondin** [comment]
```test-softlayer-ubuntu1604-x64-1``` looks good

``` test-softlayer-rhel7-x64-1``` Failure in playbook due to vendor being offline 

```
The sourceforge.net website is temporarily in static offline mode. Only a very limited set of project pages are available until the main website returns to service.

We are still working around the clock to restore full capacity to SourceForge. We do not have an ETA yet but we will update here when we do. We appreciate your patience. Thank you.
```


Manually installed/configured ant-contrib, re running play 20940

**Comment by gdams** [comment]
@bblondin we can always store files in https://ci.adoptopenjdk.net/userContent/
