### ISSUE TITLE
Switch linux build machines from Ubuntu16 to Rhel 6 or CentOS 6

### ISSUE THREAD

**Issue by gdams** [AdoptOpenJDK/openjdk-infrastructure#256]
We shouldn't be using Ubuntu16 to build as it has a high glibc version meaning that our binaries won't run on many OSes. Switching to Rhel 6 or CentOS 6 will fix this. This will require some ansible changes I would imagine. I will start with the x64 builds.

**Comment by gdams** [comment]
Hotspot OpenJDK8 build passed: https://ci.adoptopenjdk.net/job/openjdk8_build_x86-64_linux_centos/

**Comment by sxa555** [comment]
We'll need to be careful about potential issues with `libffi` - my RHEL6 box has `libffi.so.5.0.6` which may result in us hitting the same issue described in https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/25 at some point

**Comment by gdams** [comment]
so in order to build openj9 we need to use gcc4.6.x or higher (CentOS comes with 4.4.x so I have upgraded it to 4.8.x)

**Comment by gdams** [comment]
OpenJ9 OpenJDK8 build passed: https://ci.adoptopenjdk.net/job/openjdk8_openj9_build_x86-64_linux_centos/

**Comment by sxa555** [comment]
From an eclipse openj9 perspective I would prefer not to make this change to all of the builds until after we have released since we're already testing the final release candidate and it would be necessary to complete redo the testing if we started building on a new environment, but for the next release of AdoptOpenJDK+Eclipse OpenJ9, and for AdoptOpenJDK with HotSpot I fully support this (now that I know CentOS6 will be supported til 2020!)

**Comment by gdams** [comment]
okay so I'm going to leave the openj9 builds to run in their existing environment and will update the hotspot builds now :)

**Comment by gdams** [comment]
I have switched all arm builds to use centos74 (which is the lowest level of aarch64 supported centos that I can find)

**Comment by gdams** [comment]
created https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/260 to track the levels more closely

**Comment by sxa555** [comment]
I presume `ppc64le`/`s390x` the same as arm since we seem to have `build-osuosl-centos74-ppc64le-1` and `build-marist-rhel74-s390x-1` being used for the builds at present

**Comment by DanHeidinga** [comment]
Have the ansible scripts been run on that machine recently?  With my limited ansible knowledge, this may be fixed by re-running the ansible script as it attempts to install git 2.15:

https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/master/ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/GIT_Source/tasks/main.yml

**Comment by gdams** [comment]
I believe that @DanHeidinga is correct! I'll run the ansible playbook on all rhel7 machines now

**Comment by jdekonin** [comment]
This will also be an issue on build-osuosl-centos74-ppc64le-1 where the default git version is ~1.8.

**Comment by jdekonin** [comment]
If you want to grant me temporary access to one or both of the machines I can review/validate setup, rerunning or fixing the ansible scripts where required  and perform a test build.

**Comment by jdekonin** [comment]
I believe the current ansible scripts work with OpenJ9 machines.  @sxa555 @gdams is this something I can help out with; either running the ansible script on the new machines and/or manually debugging?

**Comment by sxa555** [comment]
@jdekonin Do you mean the ones for the OpenJ9 project as opposed to the adoptopenjdk machines that build openjdk+OpenJ9? Not sure if they've ever been used on the OpenJ9 project machines so far.

**Comment by jdekonin** [comment]
Yes they have, except for windows I've done all the machine configs for OpenJ9.  I run the ansible  standalone without using ansible tower like I believe is done on adoptopenjdk machines.

**Comment by sxa555** [comment]
SAP's xlinux builds are still running on the Ubuntu build machines https://ci.adoptopenjdk.net/computer/build-cloudcone-ubuntu1604-x64-1/builds

**Comment by sxa555** [comment]
Note to self: Linux/ppc64le builds are still on Ubuntu machines

**Comment by sxa555** [comment]
Using the following jobs to validate CentOS7 ppc64le builds:
https://ci.adoptopenjdk.net/view/work%20in%20progress/job/SXA-jdk8-linux-ppc64le-hotspot/
https://ci.adoptopenjdk.net/view/work%20in%20progress/job/SXA-jdk8-linux-ppc64le-openj9/
https://ci.adoptopenjdk.net/view/work%20in%20progress/job/SXA-jdk11-linux-ppc64le-hotspot/

**Comment by pshipton** [comment]
@ktbriggs I don't think this is the right issue to discuss this, but https://github.com/eclipse/openj9/blob/master/buildenv/jenkins/docker-slaves/x86/centos6.9/Dockerfile should help you.

**Comment by sxa555** [comment]
@ktbriggs I'm a bit confused by your message - you say an equivalent of the Dockerfile but end with "without Docker". Are you basically looking for the way we set up our build machines (which is with ansible and our setup scripts are in the https://github.com/AdoptOpenJDK/openjdk-infrastructure repository)
