### ISSUE TITLE
Add docker to ansible playbooks for test machines

### ISSUE THREAD

**Issue by smlambert** [AdoptOpenJDK/openjdk-infrastructure#258]
We will have a growing set of tests that run in Docker images, and would like to increase the number of test machines that have docker installed on them.

**Comment by gdams** [comment]
I think that those 4 ubuntu machines should all have docker installed on them :)

**Comment by smlambert** [comment]
aw sweet, I should add a label to the machines that have docker, that way the 3rd party application tests can just grab any available one.

**Comment by gdams** [comment]
okay! closing this issue. Let me know if there are any issues!
