### ISSUE TITLE
Add Jenkins shared library

### ISSUE THREAD

**Issue by VermaSh** [AdoptOpenJDK/openjdk-infrastructure#259]
We want the library to be able to automate adding and maintaining machines on Jenkins. Here is a list of desired features
- Adding machines to Jenkins based on the inventory list
- Determine machine stats (CPU, RAM, Disk, etc)
- Set machine description based on machine stats
- Determine machine capabilities (arch, OS, tools, versions, etc)
- Adding labels to nodes based on machine capabilities and inventory list
- Support for all of the above features on Linux, Windows, OS X, AIX and z/OS

**Comment by VermaSh** [comment]
I have been working on a shared library. It has the below functionalities for Linux, Windows, OS X, AIX and z/OS

- Add machines to Jenkins
- Determine machines stats (CPU, RAM, Disk, etc)
- Set machine description based on machine stats
- Determine machine capabilities (only arch, OS)
- Add labels to nodes based on machine capabilities


I'll open a pull request in couple of days

**Comment by gdams** [comment]
Hi @VermaSh, thanks for this issue. I would suggest that you take a look at my PR because it already does some of the described tasks https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/192

**Comment by VermaSh** [comment]
@gdams  I went through your PR and yes it does do a bunch of stuff. However, we want to do the machine maintenance on a regular schedule and It didn't make sense to couple Jenkins with Ansible. So we decided that we were better off with a library that resides solely on Jenkins. The end goal is to have one job that runs weekly and keeps the machine labels updated.

Other reason behind this is that the test team wanted the ability to get machine stats in real time, directly from the machine instead of labels.

**Comment by gdams** [comment]
Ahh okay, that makes sense. So we can use ansible to get the machines into jenkins and then let your scripts handle the labels etc

**Comment by VermaSh** [comment]
Except, we may not always want to Ansible a machine. Also, the solution will be an API not a script; anyone who wants to use it will have to create a Jenkins job. I did create a Jenkins job but at the moment it's too specific to be checked in here. I'll add some use cases as comments in the API (or somewhere else).
Things will get clearer once I submit a PR.

**Comment by karianna** [comment]
I think I'm going to have to see the PR to understand what this is trying to achieve over and above ansible.

**Comment by gdams** [comment]
@VermaSh can this be closed?

**Comment by VermaSh** [comment]
yes
