### ISSUE TITLE
STF tests failing on CentOS 7.2 (GLIBC_2.22 not found)

### ISSUE THREAD

**Issue by sxa555** [AdoptOpenJDK/openjdk-infrastructure#26]
if a CentOS machine is selected for the STF suites then the builds do not run. See https://github.com/AdoptOpenJDK/openjdk-jdk9/issues/1

We need a global set of appropriate `test` tags applied to the machines to match the current expectations in https://github.com/AdoptOpenJDK/openjdk-build/wiki/%5BWIP%5D-Minimum-OS-levels but at the moment we can't lock the jobs to that tag due to https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/25

**Comment by bblondin** [comment]
Do we support CentOS 7.2 and what is the minimum glibc version support?

Currently on our CentOS 7.2 system they are running ``` 2.17 ```

```
build-osuosl-centos72-ppc64le-1
ldd (GNU libc) 2.17

build-linaro-armv8-centos7-1
ldd (GNU libc) 2.17
```

**Comment by karianna** [comment]
@sxa555 #25 is now done, can this be resolved now by tagging the right hosts?

**Comment by sxa555** [comment]
I would suggest not until we have https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/256 complete. Bear in mind that the new test box referred to in #25 is an Ubuntu 16.04 one
