### ISSUE TITLE
git helper for 'https' rhel7

### ISSUE THREAD

**Issue by bblondin** [AdoptOpenJDK/openjdk-infrastructure#261]
Issue:

```
git clone  https://github.com/AdoptOpenJDK/openjdk-tests.git 
Cloning into 'openjdk-tests'...
fatal: Unable to find remote helper for 'https'
```

FYU: @sophieg @smlambert

**Comment by bblondin** [comment]
solution to the current issues was to installed curl-devel and recompiled git
Pull request to fix it is required

FYI: @gdams

**Comment by AdamBrousseau** [comment]
Isn't this resolved via #126 ?

**Comment by AdamBrousseau** [comment]
Ahh, that was only for Ubuntu, I didn't add it for rhel as it appeared to already work there. Looks like the rhel playbook only installs it on ppcle
https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/7e5f884d7d519c4711410eb2b9275f93e7265e08/ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/RedHat.yml#L45

**Comment by bblondin** [comment]
PR went through in #255
