### ISSUE TITLE
Add disk space to test-scaleway-ubuntu1604-x64-1 and test-softlayer-ubuntu1604-x64-1

### ISSUE THREAD

**Issue by pnstanton** [AdoptOpenJDK/openjdk-infrastructure#266]
test-scaleway-ubuntu1604-x64-1 and test-softlayer-ubuntu1604-x64-1 are out of disk space again. Both systems have unused disks. I will format these disks, mount them at `/home` and move the data from the existing disk to the new one.

**Comment by pnstanton** [comment]
test-softlayer-ubuntu1604-x64-1 has an additional 25 GB
test-scaleway-ubuntu1604-x64-1 has an additional 46 GB

**Comment by smlambert** [comment]
thanks @pnstanton !

**Comment by sophia-guo** [comment]
We got similar issue on test-macincloud-macos1010-2. @pnstanton does this machine have same issue? https://github.com/AdoptOpenJDK/openjdk-tests/issues/301
