### ISSUE TITLE
test-softlayer-rhel74-x64-1 have 'ant-contrib' issue

### ISSUE THREAD

**Issue by sophia-guo** [AdoptOpenJDK/openjdk-infrastructure#269]
Test build running on test-softlayer-rhel74-x64-1  got 

14:35:47 BUILD FAILED
14:35:47 /home/jenkins/workspace/openjdk8_j9_openjdktest_x86-64_linux/openjdk-tests/TestConfig/scripts/build_test.xml:36: Problem: failed to create task or type if
14:35:47 Cause: The name is undefined.
14:35:47 Action: Check the spelling.
14:35:47 Action: Check that any custom tasks/types have been declared.
14:35:47 Action: Check that any <presetdef>/<macrodef> declarations have taken place.
https://ci.adoptopenjdk.net/view/OpenJDK%20tests/job/openjdk8_j9_openjdktest_x86-64_linux/41/console

https://ci.adoptopenjdk.net/view/OpenJDK%20tests/job/openjdk8_j9_openjdktest_x86-64_linux/41/console

Suspect either ant-contrib isn't installed or installed with issue.

**Comment by bblondin** [comment]
host seems ok:

[jenkins@test-softlayer-rhel7-x64-1 ~]$ ant -diagnostics

```
-------------------------------------------
 ANT_HOME/lib jar listing
-------------------------------------------
ant.home: /usr/share/ant
ant-launcher.jar (19063 bytes)
ant-contrib.jar (232225 bytes)
ant.jar (1999724 bytes)
ant-bootstrap.jar (20919 bytes)
```

```
[jenkins@test-softlayer-rhel7-x64-1 ~]$ ls -lah /usr/share/ant/lib/ant-contrib.jar
-rw-r--r--. 1 root root 227K Mar  3 08:23 /usr/share/ant/lib/ant-contrib.jar
```

Are you sure the code is passing the environment into make?

**Comment by sophia-guo** [comment]
Exactly same build job works on other machines. The only difference is jenkins distribute the job to this machine as it has same required labels.
Other test jobs got other ant issue on this machine 

tests/TestConfig/../../jvmtest/TestConfig/resources -DJCK_ROOT= -DJVM_VERSION=openjdk10
15:51:32 Error: Could not find or load main class org.apache.tools.ant.launch.Launcher
15:51:32 Caused by: java.lang.ClassNotFoundException: org.apache.tools.ant.launch.Launcher
15:51:32 make: *** [compile] Error 1

https://ci.adoptopenjdk.net/view/System%20tests/job/openjdk10_hs_systemtest_x86-64_linux/26/console

**Comment by sophia-guo** [comment]
I also logged in this machine and tried a simple build.xml with <if> tag and got exactly same issue.
[jenkins@test-softlayer-rhel74-x64-1 test_personal]$ vi build.xml 
[jenkins@test-softlayer-rhel74-x64-1 test_personal]$ ant
Buildfile: /home/jenkins/workspace/test_personal/build.xml
  [taskdef] Could not load definitions from resource net/sf/antcontrib/antlib.xml. It could not be found.

BUILD FAILED
/home/jenkins/workspace/test_personal/build.xml:9: Problem: failed to create task or type if
Cause: The name is undefined.
Action: Check the spelling.
Action: Check that any custom tasks/types have been declared.
Action: Check that any <presetdef>/<macrodef> declarations have taken place.

**Comment by bblondin** [comment]
> Exactly same build job works on other machines.

Which machines? do you have a link to that job?

**Comment by sophia-guo** [comment]
Link is in my first comment.

**Comment by sophia-guo** [comment]
@bblondin Could we disable this machine for now, affects test build. 
https://ci.adoptopenjdk.net/view/work%20in%20progress/job/TestBuild_Sandbox2/137/console

**Comment by bblondin** [comment]
That didn't answer the question... both of those links look like  `test-softlayer-rhel74-x64-1`

Could you please tell me what machines it works on?

**Comment by sophia-guo** [comment]
Works for following except test-softlayer-rhel74-x64-1
https://ci.adoptopenjdk.net/label/test&&linux&&x64/

**Comment by sophia-guo** [comment]
https://ci.adoptopenjdk.net/view/OpenJDK%20tests/job/openjdk8_hs_openjdktest_x86-64_linux/46/console

Could you disable it for now?

**Comment by sophia-guo** [comment]
Those different links are different test build jobs, all of which failed for running on this rhel machine. The reason I comment here is it affects more than more test job. I'd like to disable this machine.

**Comment by bblondin** [comment]
So...
This test is known to work only on Ubuntu systems.
With the addition of a new RHEL system the test now fails but only on RHEL.
You believe its has something to do with `ant-contrib`

I have disabled `test-softlayer-rhel74-x64-1`

**Comment by bblondin** [comment]
Basic `ant build.xml` test

```
build.xml

<project name="ant-propregex-simple" default="run">
    <taskdef resource="net/sf/antcontrib/antlib.xml" />
    <target name="run">
        <property name="line.to.test" value="First Second" />
        <property name="the.regex" value="^([^ ]*) ([^ ]*)$" />
        <propertyregex 
            input="${line.to.test}" 
            regexp="${the.regex}" 
            select="\2" 
            property="the.match" 
        />
        <echo>${the.match}</echo>
    </target>
</project>

```

Passes on Ubuntu
Fails on RHEL

adding `<pathelement location="/MYPATH/ant-contrib.jar"/>` to the `build.xml` (ie point it to where the `ant-contrib.jar` lives fixes the issue

thus `ant-contrib` is not where ant thinks it should be on RHEL

**Comment by bblondin** [comment]
Installed ant-contrib from red hat. my test now works.
re-enabled host, please test

**Comment by bblondin** [comment]
Created pull request #275 to add solution to the playbook

**Comment by sophia-guo** [comment]
Fixed:
https://ci.adoptopenjdk.net/view/work%20in%20progress/job/TestBuild_Sandbox/172/console

**Comment by sophia-guo** [comment]
Didn't notice same machine still have another ant issue commented before still happened:

15:51:32 Error: Could not find or load main class org.apache.tools.ant.launch.Launcher
15:51:32 Caused by: java.lang.ClassNotFoundException: org.apache.tools.ant.launch.Launcher
15:51:32 make: *** [compile] Error 1

https://ci.adoptopenjdk.net/view/System%20tests/job/openjdk10_hs_systemtest_x86-64_linux/26/console

https://ci.adoptopenjdk.net/view/System%20tests/job/openjdk10_hs_systemtest_x86-64_linux/26/console

If it's not a same issue I can close this one and open a new one.

**Comment by bblondin** [comment]
please open a new issue for this
