### ISSUE TITLE
Add -k flag to check_procs Nagios check

### ISSUE THREAD

**Issue by pnstanton** [AdoptOpenJDK/openjdk-infrastructure#272]
I often see Nagios flagging machines as having too many processes running. As well as counting normal processes it is counting kernel threads, which there can be a lot of on a system with many CPUs.
The Nagios `check_procs` check has a `-k` flag which we are not currenlty using - it filters out kernel threads and only reports on userspace processes.

**Comment by bblondin** [comment]
- Applied change to mac commands

Thanks @pnstanton for finding this flag

**Comment by bblondin** [comment]
*NOTE* `-k` option don't work on AIX
