### ISSUE TITLE
Add Licence and Copyright to Repo

### ISSUE THREAD

**Issue by AdamBrousseau** [AdoptOpenJDK/openjdk-infrastructure#276]
Related #232 
We likely should have Copyright and License files in our repo as well as headers in the source files.
I believe we should be using Apache 2 just like the [tests](https://github.com/AdoptOpenJDK/openjdk-tests) and [build](https://github.com/AdoptOpenJDK/openjdk-build) repos.
https://github.com/AdoptOpenJDK/openjdk-build/blob/master/LICENSE

**Comment by gdams** [comment]
I have added the Apache2 License to the repo

**Comment by beckje01** [comment]
@gdams Please review, might be able to close this.
