### ISSUE TITLE
Grant @lumpfish a user account on the JCK machines to run interactive tests

### ISSUE THREAD

**Issue by sxa555** [AdoptOpenJDK/openjdk-infrastructure#279]
@lumpfish is going to run the first set of JCK interactive tests on the AdoptOpenJDK with Eclipse OpenJ9 for us. For this he will require his own login to the JCK machines (it is preferable not to use the jenkins account for this). I'm happy to act as his initial sponsor if approval is required.
One of each architecture should be adequate, but he will be executing on x64 first so that is the most important one. Based on the information on https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/267 I would suggest `jck-softlayer-ubuntu1604-x64-1` initially since the `-2` one had issues.

**Comment by gdams** [comment]
so I assume this account needs no sudo powers?

**Comment by sxa555** [comment]
Correct @gdams - only standard user privileges should be needed for this.

**Comment by lumpfish** [comment]
More generally, we will be asking for volunteers to run the JCK interactive tests from time to time, so others will be in this situation shortly.  Is there an established process for requesting accounts on machines?

**Comment by lumpfish** [comment]
Should I expect this issue to be updated when I have an account?

**Comment by lumpfish** [comment]
@pnstanton tells me the ip address of one of the jck test machines, jck-softlayer-ubuntu1604-x64-1, is 159.122.210.205, which is required to ssh into the machine.  Is there a way I should have been able to find this out myself after having been asked to "run the tests on jck-softlayer-ubuntu1604-x64-1"?  Future volunteers to run these tests will have the same issue.

**Comment by karianna** [comment]
@lumpfish - issue is typically updated yes

**Comment by pnstanton** [comment]
Created @lumpfish an ID on jck-softlayer-ubuntu1604-x64-1

**Comment by sxa555** [comment]
@lumpfish has been using the account without problems, therefore closing
