### ISSUE TITLE
api.adoptopenjdk.net seems unhappy

### ISSUE THREAD

**Issue by sxa555** [AdoptOpenJDK/openjdk-infrastructure#28]
The API information is at https://api.adoptopenjdk.net/ but that currently appears not to be serving up what it should.

Cc @gdams @karianna

**Comment by karianna** [comment]
This should probably be reported over in openjdk-api

**Comment by sxa555** [comment]
It looks like the whole system is a bit broken so I figured it was more of an issue in the infrastructure. 50/50 :-) @gdams is aiming to reboot it at the moment so will hopefully be resolved soon. Should we have a "systemdown" label that we use for these sorts of things so we can track how often they occur?

**Comment by gdams** [comment]
The API is now back, I will look through the logs tonight
