### ISSUE TITLE
Hosts specification in ubuntu-jck.yml playbook is wrong

### ISSUE THREAD

**Issue by geraintwjones** [AdoptOpenJDK/openjdk-infrastructure#280]
In order to get the `ubuntu-jck.yml` playbook to only run against JCK Ubuntu machines, I changed...
 ```
- hosts: all
```
to...
```
- hosts: "{{ groups['Vendor_groups'] | default('jck:*ubuntu*') }}"
```
That did not work. When I ran the playbook via AWX, it matched all hosts.

Fix this line so that the playbook will only run against JCK Ubuntu machines.

**Comment by bblondin** [comment]
Sorry @geraintwjones 
it should be `- hosts: "{{ groups['Vendor_groups'] | default('jck-*-ubuntu*') }}"`

**Comment by bblondin** [comment]
Pull request created: #282
