### ISSUE TITLE
test-softlayer-rhel74-x64-1 got "Could not find or load main class org.apache.tools.ant.launch.Launcher"

### ISSUE THREAD

**Issue by sophia-guo** [AdoptOpenJDK/openjdk-infrastructure#283]
test-softlayer-rhel74-x64-1 got "Could not find or load main class org.apache.tools.ant.launch.Launcher"
15:51:32 Error: Could not find or load main class org.apache.tools.ant.launch.Launcher
15:51:32 Caused by: java.lang.ClassNotFoundException: org.apache.tools.ant.launch.Launcher
15:51:32 make: *** [compile] Error 1

https://ci.adoptopenjdk.net/view/System%20tests/job/openjdk10_hs_systemtest_x86-64_linux/26/console

https://ci.adoptopenjdk.net/view/System%20tests/job/openjdk10_hs_systemtest_x86-64_linux/26/console

**Comment by sophia-guo** [comment]
https://ci.adoptopenjdk.net/view/OpenJDK%20tests/job/openjdk10_sap_openjdktest_x86-64_linux/12/console

**Comment by smlambert** [comment]
This likely implies the rhel ansible playbook needs to be looked at, as the ant installation does not seem correct/complete.

**Comment by bblondin** [comment]
Where does this code expect ANT_HOME to be located?
Would you be able to provide a basic test to reproduce this error?

**Comment by smlambert** [comment]
And if you like to reproduce this test after making changes to that machine, you can go to Sophia's [test_personal build [](412](https://ci.adoptopenjdk.net/view/work%20in%20progress/job/test_personal/412/) while its around, and hit the rebuild button.

![rebuildpersonal](https://user-images.githubusercontent.com/2836948/37541450-0d37c2a0-2931-11e8-8c47-a0ee4235def1.jpg)

**Comment by sophia-guo** [comment]
@pnstanton the error is because ant-contrib is not installed or installed uncorrectly. https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/269

**Comment by sxa** [comment]
As far as I can see this in place now on the machine - closing. Please re-open if required
