### ISSUE TITLE
new test-rhel6 machine

### ISSUE THREAD

**Issue by gdams** [AdoptOpenJDK/openjdk-infrastructure#286]
@tellison could you provision a new rhel6 machine on softlayer?

4CPU, 8GB Ram, disk ideally SSD

FYI @AdoptOpenJDK/testing

**Comment by tellison** [comment]
Created as `test-softlayer-rhel6-x64-1`
4 CPU | 8 GB RAM | 25 GB boot disk + 25 GB data disk | 100 Mbps network

Will advise login details separately
