### ISSUE TITLE
Add new RHEL6 test machine to project infrastructure

### ISSUE THREAD

**Issue by tellison** [AdoptOpenJDK/openjdk-infrastructure#288]
At the request of #286 I have created a new RHEL6 x64 machine for use by test.

It is hosted at Softlayer with hostname, IP address, and login as follows:

```
   test-softlayer-rhel6-x64-1
   169.55.150.147
   root/********
```

This machine need configuring with Ansible, adding to Nagios and Jenkins etc to be made available for test.
When completed please give a heads-up to @gdams

**Comment by bblondin** [comment]
**To do List:**

- [ ] Add system to Keybox
- [ ] Update keybox's profile 'root_test_machines' to include this system
- [ ] Create pull request to add these system to the Ansible inventory file
- [ ] Create new entries in secrets gpg
- [ ] Refresh Ansible dynamic inventory 
- [ ] Execute Playbook on is system
- [ ] Configure system in Jenkins

**Comment by bblondin** [comment]
Pull Request https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/289

**Comment by bblondin** [comment]
updated hostname was: `test-softlayer-rhel6-x64-1` 
is: ` test-softlayer-rhel69-x64-1`

**Comment by bblondin** [comment]
Playbook running - job 21762

**Comment by bblondin** [comment]
rerunning job 21800

**Comment by bblondin** [comment]
completed
