### ISSUE TITLE
Grant  three user accounts on the JCK machines to run interactive tests

### ISSUE THREAD

**Issue by irinarada** [AdoptOpenJDK/openjdk-infrastructure#292]
Please give access to the following people:

Suman Mitra (summitra@in.ibm.com)
Vaishnavi Pathipati (vaipathi@in.ibm.com
Divyarao Devaraneni (divydeva@in.ibm.com)

**Comment by gdams** [comment]
I'm not sure that I like the way that we are creating several user accounts on our machines. Can we not have a shared account that the JCK team can use?

**Comment by irinarada** [comment]
Shared account is good.

**Comment by karianna** [comment]
I'm OK with shared account as long as we know which individual is logging in as the shared account

**Comment by lumpfish** [comment]
So is the shared account now created?  We discussed using 'jcktester' in the AdoptOpenJDK infrastructure slack channel.
Also from the slack channel - what are the names of the JCK machines and their ip addresses which users will need to log into them.  Is the information is already available to the community somewhere?

**Comment by bblondin** [comment]
These are the ones I know of:

```
jck-osuosl-ppc64le-ubuntu-16.04-1 - 140.211.168.225

jck-osuosl-ppc64le-ubuntu-16.04-2 - 140.211.168.217

jck-softlayer-x64-ubuntu-1604-1 - 159.122.210.205

jckservices - 158.176.72.83
```

**Comment by bblondin** [comment]
Full list: https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/master/ansible/inventory.yml

**Comment by sxa555** [comment]
[Copying in my slack comments ref individual vs shared user accounts]

_I'm not sure I agree with the shared account approach. It adds extra complexity with the shared password, reduces audit-ability if you need to ask "Who is running this suspicious process that's running?" (as an example) and you don't really want people having their private keys on a shared account for accessing the private git repos that are required (You can copy there from a locally cloned version to avoid that but that's about 1.5Gb of stuff that had to be shunted around under unnecessarily over your LAN)_

**Comment by karianna** [comment]
Hi all - is this temp access still required?

**Comment by lumpfish** [comment]
I'm not sure what happened in the end (regarding a shared user).  For the tests I ran I had a user account set up on the machine, but I wasn't the only tester.  (@suman-mitra ?)  I don't believe there's anything 'temporary' about the accounts though, if that was the intent - I can still log into my account on that machine.  (Actually I will likely want to use it again soon to test a new release).

**Comment by karianna** [comment]
@gdams Just double checking here - I assume you didn't set up any temp accounts then?

**Comment by sxa555** [comment]
@karianna There is a shared `jcktestr` account on some of the machines for the purpose of JCK testing ...
Related issues: https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/421 https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/426 https://github.com/AdoptOpenJDK/JCK/issues/9

**Comment by sxa** [comment]
We no longer run these tests at AdoptOpenJDK therefore the request is obsolete - closing
