### ISSUE TITLE
Missing Windows Deps that need adding to Ansible

### ISSUE THREAD

**Issue by gdams** [AdoptOpenJDK/openjdk-infrastructure#294]
We need to download onto new build machines https://github.com/AdoptOpenJDK/openjdk-installer/raw/master/windows.p12

It should go into `C:\Users\jenkins`

**Comment by gdams** [comment]
Also install make-3.82 into `C:\openjdk\make-3.82`

**Comment by gdams** [comment]
set the hostname

**Comment by gdams** [comment]
machines also need signtool.exe

```/cygdrive/c/Program Files/Microsoft SDKs/Windows/v7.1/Bin/signtool.exe: No such file or directory```

**Comment by Willsparker** [comment]
@gdams Is this still an issue? Currently putting the windows playbook through it's paces with #942 and I've so far been able to build JDK8 and JDK11 without any extra dependencies on top of the playbook running.

**Comment by gdams** [comment]
@Willsparker the codesign/signtool steps are still required, we currently manually install them.

**Comment by Willsparker** [comment]
It seems all thats needed from #300 will be `roles/Certificate/tasks/main.yml` and possibly `roles/MS_SDK_7.1/tasks/main.yml`, for `signtool.exe`

**Comment by gdams** [comment]
closing as all the deps are in the playbook now
