### ISSUE TITLE
Invite two new members to the AdoptOpenJDK org and add to JCK team

### ISSUE THREAD

**Issue by tellison** [AdoptOpenJDK/openjdk-infrastructure#298]
@suman-mitra wrote:
Suman Mitra [10:19 AM]
Hi @tpellison , please add my team mates to AdoptOpenJDK and JCK private "Adopt OpenJDK/JCK " team. They need to go through the docs there and run the JCK manuals...Their git id's are :-
1. vaishnavipathipati
2. divydeva

**Comment by tellison** [comment]
Invites sent to @vaishnavipathipati and @divydeva

They'll be receiving an email shortly. They can also visit https://github.com/AdoptOpenJDK to accept the invitation.

**Comment by gdams** [comment]
@tellison please create these issues in the https://github.com/AdoptOpenJDK/TSC repo in the future.

**Comment by tellison** [comment]
@gdams please explain the rationale to using the TSC repo?

I'm guessing that we are generous in granting membership to the AdoptOpenJDK org, but understand if we require closer oversight of membership to the JCK group.  Is that what you were thinking?

**Comment by karianna** [comment]
There's now a few sub teams with privileges (infra, test, JCK) so it's worth having the TSC review before passing on (once we errr actually form the TSC)

**Comment by gdams** [comment]
So it's not really an infra descission to add someone to the JCK team. It would make more sense for the issue to be raised in eithe TSC or Test I suppose

**Comment by tellison** [comment]
It wasn't a decision, it was an action :-)  i.e. the request was already presumed granted via Slack (lazy consensus), and this infra task was to go ahead and modify the Github settings, which requires infra rights.

But whatever, we should have a place where the request/decision is made, and I'm happy for that to be the TSC repo.
