### ISSUE TITLE
Include host time synchronization pkgs in Ansible scripts

### ISSUE THREAD

**Issue by tellison** [AdoptOpenJDK/openjdk-infrastructure#3]
New machines that are configured for AdoptOpenJDK should have some real time clock synchronization package installed (e.g. NTP, timesyncd, etc) to ensure they do not drift too far and disrupt Jenkins pipeline coordination.

Although many of our jobs are quite long running, where they fail they may fail quickly and being out of sync by tens of seconds matters.

**Comment by bblondin** [comment]
Configured/setup ntp time on all Ubuntu and AIX systems:

List:
build-1and1-win2008r2-1
build-joyent-x64-freebsd-11-1
build-joyent-x64-smartOS-14-1
build-linaro-armv8-centos7-1
build-linaro-armv8-centos7-2
build-macstadium-macos1010-1
build-macstadium-macos1010-2
build-marist-s390x-rhel-6
build-marist-s390x-rhel-7.3
build-marist-s390x-sles-12
build-marist-s390x-ubuntu-16.04 - ntp time enabled
build-osuosl-ppc64-aix-71-1 - ntp time enabled
build-osuosl-ppc64-aix-71-2 - ntp time enabled
build-osuosl-ppc64le-centos-7.2
build-osuosl-ppc64le-fedora-24-1
build-osuosl-ppc64le-fedora-24-2
build-osuosl-ppc64le-ubuntu-16.10 - ntp time enabled
build-packet-armv8-ubuntu-16.04 - ntp time enabled 
build-packet-x64-ubuntu-16 - ntp time enabled
build-scaleway-armv7-ubuntu16.04-1 - ntp time enabled
build-scaleway-armv7-ubuntu16.04-2 - ntp time enabled
build-scaleway-x64-ubuntu-16.04-1 - ntp time enabled
build-scaleway-x64-ubuntu-16.04-2 - ntp time enabled
Nagios Server - ntp time enabled
openjdk-api-server - ntp time enabled
openjdk-staging-server - ntp time enabled
test-macincloud-macos1010-1
test-macincloud-macos1010-2
test-packet-x64-ubuntu-16.04-1 - ntp time enabled
test-packet-x64-windows-2012r2-1
test-scaleway-x64-ubuntu-16.04-1 -- ntp time enabled

**Comment by bblondin** [comment]
Configured/setup ntp time on all systems listed in previous comment

**Comment by bblondin** [comment]
ntp is now included in each of the playbooks in: https://github.com/AdoptOpenJDK/openjdk-infrastructure/tree/master/ansible/playbooks
