### ISSUE TITLE
AWX not able to run playbooks on the 2 JCK 390 machines

### ISSUE THREAD

**Issue by geraintwjones** [AdoptOpenJDK/openjdk-infrastructure#301]
AWX is not able to run playbooks on the the following 2 JCK 390 machines...
- 148.100.33.183 (jck-marist-ubuntu1604-s390x-1)
- 148.100.33.184 (jck-marist-ubuntu1604-s390x-2)

The error reported by AWX looks like this...
```
{
    "_ansible_parsed": false,
    "_ansible_no_log": false,
    "module_stderr": "Shared connection to 148.100.33.183 closed.\r\n",
    "changed": false,
    "_ansible_verbose_override": true,
    "module_stdout": "sudo: a password is required\r\n",
    "failed": true,
    "rc": 1,
    "msg": "MODULE FAILURE"
}
```
It seems to be an issue with sudo.

**Comment by sxa555** [comment]
Interesting problem. The machines are using the `linux1` ID to log in and then sudo to do the work.

`linux1` was listed explicitly in `/etc/sudoers` as being able to use sudo without a password, but it was also in the `sudo` group which gives it access, but requires a password ... That second entry appears to have taken precedence as I have now removed linux1 from the sudo group and it now works.

**Comment by sxa555** [comment]
Fiurther note - it seems that on the othre zlinux Marist machines the `sudo` group has `NOPASSWD` set, but that is not the case on the JCK machines, which explains the difference
