### ISSUE TITLE
AWX not able to run playbooks on jck-softlayer-x64-ubuntu-1604-2

### ISSUE THREAD

**Issue by geraintwjones** [AdoptOpenJDK/openjdk-infrastructure#302]
AWX not able to run playbooks on 159.122.210.194 (jck-softlayer-x64-ubuntu-1604-2).

Works fine on 159.122.210.205 (jck-softlayer-x64-ubuntu-1604-1).

No user is specified in the inventory, so it's using `root`.

I am able to ssh to `root@159.122.210.205` but not to `root@159.122.210.194`.

There are no entries for this machine in KeyBox. The solution to this problem is probably to add those entries. The accounts in KeyBox for 159.122.210.205 are `root` and `jenkins`.

**Comment by bblondin** [comment]
you already have access

```


Username | User Type | Last Name | First Name | Email Address |  
geraintj | Full Access | Jones | Geraint | geraintj@uk.ibm.com | Edit



```

**Comment by geraintwjones** [comment]
I thought that too.

- Manage > Systems > Add System
- Display name = jck-softlayer-x64-ubuntu-1604-2
- System user = root
- Host = 159.122.210.194
- Port = 22
- Authorized keys = ~/.ssh/authorized_keys
- Submit

Responds with...
```
Enter password for jck-softlayer-x64-ubuntu-1604-2 - ( root@159.122.210.194:22 )
Error: Auth fail
Password: *********
```

I don't know what the password is, so can go no further.

**Comment by gdams** [comment]
@sxa555 do you have access to this?

**Comment by bblondin** [comment]
@gdams This is not an issue with AWX... We are unable to log into the machine ourselves.
Once that is corrected then keybox can be updated, then AWX will work

**Comment by sxa555** [comment]
Closing as we're not using the machine
