### ISSUE TITLE
test-softlayer-rhel69-x64-1 got " /lib64/libc.so.6: version `GLIBC_2.14' not found "

### ISSUE THREAD

**Issue by sophia-guo** [AdoptOpenJDK/openjdk-infrastructure#304]
test build running on test-softlayer-rhel69-x64-1 and got:
/home/jenkins/workspace/TestBuild_Sandbox/openjdkbinary/j2sdk-image//bin/java: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /data/home/jenkins/workspace/TestBuild_Sandbox/openjdkbinary/j2sdk-image/bin/../lib/jli/libjli.so)

https://ci.adoptopenjdk.net/view/work%20in%20progress/job/TestBuild_Sandbox/174/console

**Comment by gdams** [comment]
@sophia-guo this is expected behavior for our OpenJ9 builds are they are currently built on ubuntu16. I recommended getting a rhel6 machine setup for you so that we could catch these errors in the future. Please test with one of our hotspot binaries as these **should** now work on rhel6 and rhel7. We will swap the openj9 builds to also build with a lower glibc version once this release is out of the way

**Comment by gdams** [comment]
This is traked in https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/256

**Comment by sophia-guo** [comment]
Thanks @gdams . I also noticed you have created job https://ci.adoptopenjdk.net/view/work%20in%20progress/job/openjdk-runtime-test/  to track this. That's great!

Is that the reason test-softlayer-rhel69-x64-1 is re-enabled? The thing is if it is enabled with same labels as other tests machines  it could be dispatched to all our routine jobs(jobs under *test tabs) and fails the jobs. 

We can test hotspot binaries on those rhel6 and rhel7 machines using a non-routine job(under work in progress tab) manually. @smlambert  has created a test job(or in progress) to do this. However for those in progress machine probably we need to use a different label convention before its available for routine jobs, say using its hostname. When it's good just update labels and it's ready for all routine jobs.

**Comment by smlambert** [comment]
I re-enabled test-softlayer-rhel69-x64-1 but removed the test label from it so the test jobs won't try to use it.
