### ISSUE TITLE
A number of OSUOSL machines are down

### ISSUE THREAD

**Issue by geraintwjones** [AdoptOpenJDK/openjdk-infrastructure#305]
Nagios is not getting a response from the following OSUOSL machines...
- build-osuosl-centos74-ppc64le-1 (140.211.168.138)
- build-osuosl-ppc64le-fedora-24-1 (140.211.168.134)
- build-osuosl-ubuntu1604-ppc64le-1 (140.211.168.243)
- test-osuosl-ubuntu1604-ppc64le-2 (140.211.168.190)

This in turn is filling up the [#infrastructure-bot](https://adoptopenjdk.slack.com/messages/C8C212BU6) Slack channel.

**Comment by geraintwjones** [comment]
This is backed up by KeyBox, where the status of the following entries are all "failed"...
- build-osuosl-centos74-ppc64le-1 (140.211.168.138:22) (users: centos, jenkins)
- build-osuosl-ppc64le-fedora-24-1 (140.211.168.134:22) (users: fedora, jenkins, root)
- build-osuosl-ppc64le-ubuntu-16.04 (140.211.168.243:22) (users: jenkins, root, ubuntu)
- ubuntu@test-osuosl-ppc64le-ubuntu-16.04-2 (140.211.168.190:22) (users: jenkins, root, ubuntu)

**Comment by geraintwjones** [comment]
There are other "failed" machines in keyBox too. I will cover those in a separate issue. This one's about the OSUOSL machines.

**Comment by geraintwjones** [comment]
None of those IP addresses respond to ping.
Who manages those machines? Is there somebody I can ask to look at them? Any suggestions @gdams?

**Comment by geraintwjones** [comment]
In the meantime, I've disabled notfications from those particular hosts to reduce the traffic to Slack.

**Comment by gdams** [comment]
I have access to openstack but the rebooting the machines made no difference. @tellison knows the contact I believe

**Comment by geraintwjones** [comment]
@tellison Can you tell me who to contact to get these machine issues resolved?

**Comment by gdams** [comment]
@geraintwjones I have found the contact. Have sent an email and CC'd you in it

**Comment by gdams** [comment]
I have had to take some steps to get the OpenJ9 builds through...

https://ci.adoptopenjdk.net/job/openjdk8_openj9_build_checksum/configure (removed ppc64le)
https://ci.adoptopenjdk.net/view/Pipelines/job/openjdk8_openj9_release_pipeline/configure
removed code block
```
Platforms["ppc64le"] = {
    node {
        build job: 'openjdk8_openj9_build_ppc64le_linux', parameters: [string(name: 'TAG', value: "${JDK_TAG}")]
    }
}```

These will need to be reverted once the machines come back online

**Comment by gdams** [comment]
machines are back online. Will revert the jobs

**Comment by gdams** [comment]
jobs have been reverted

**Comment by geraintwjones** [comment]
Thanks @gdams.
