### ISSUE TITLE
slackarchive.io isn't up to date

### ISSUE THREAD

**Issue by sxa555** [AdoptOpenJDK/openjdk-infrastructure#312]
It looks like it stopped working on the 11th January. It also doesn't appear to have been tracking #general and really needs to now that we shut down #getopenjdk earlier this week.

**Comment by karianna** [comment]
I've pinged their support as I've forgotten where to go to fix this.

**Comment by gdams** [comment]
I've added the slackarchive not to #general so hopefully when @karianna gets it back up and running we should start getting an archive of #general.

**Comment by karianna** [comment]
Apparently @gdams support is more responsive than the official one, I've pinged them again

**Comment by tellison** [comment]
@karianna Any progress on this?  Still no archiving of the `#general` channel :-(  Worth chasing again.

**Comment by karianna** [comment]
Yeah I've pinged them again, annoyingly no response and they've taken another year's payment!

**Comment by adoptopenjdk-admin** [comment]
They're dropping the service - we may have to host our own based off https://github.com/AdoptOpenJDK/slackarchive

**Comment by adoptopenjdk-admin** [comment]
From slackarchive:

Hi,

What will be the easiest is to work with the SlackArchive Importer to import an exported archive from Slack.

Remco

**Comment by gdams** [comment]
I'm not sure if hosting this ourselves is a good idea... I imagine that we are going to require a huge amount of disk space to store the full archive

**Comment by karianna** [comment]
It's text, I suspect it'll be tiny.

Cheers,
Martijn

**Comment by sxa555** [comment]
We've got a paid slack instance now so have the history back - closing
