### ISSUE TITLE
ci.adoptopenjdk.net forces a github login to see it

### ISSUE THREAD

**Issue by karianna** [AdoptOpenJDK/openjdk-infrastructure#321]
Reported by several new contributors

![ciblocked](https://user-images.githubusercontent.com/180840/37824453-91efce2c-2e84-11e8-8748-08c9778506e4.png)

**Comment by sxa555** [comment]
+1 - I've already been pinged about it too. I know we spoke about freeing up the access a little to allow anonymous users to see pipelines but it looks like we've gone the wrong way. Multiple users affected therefore marking as critical.

**Comment by sxa555** [comment]
Checking the admin panels it looks like Job Read access is still showing as being available for even Anonymous users, but it looks like something is forcing users to log in now. Need to understand if anyone has changed anything.

**Comment by karianna** [comment]
I've fixed this by setting anon users to have read access and view access
