### ISSUE TITLE
zlinux builds stuck as build-marist-rhel74-s390x-1 has fallen off the network 

### ISSUE THREAD

**Issue by sxa555** [AdoptOpenJDK/openjdk-infrastructure#323]
jenkins executor won't start and a ping of it's IP address `148.100.33.179` suggests it is offline

**Comment by sxa555** [comment]
(Raised this with my intermediary who talks to Marist)

**Comment by karianna** [comment]
Can you add the contact details on the wiki or if private then in lastpass / keybox / whereever?

**Comment by sxa555** [comment]
Reply is as follows:

```
It is actually up and responding.  However, I am not able to ssh into it.  I get  "Permission denied" message instead of a login prompt.  I am able to ssh in with the linadm account using a key. 

As far as I can see, this server is working.  They have made changes to the access method and possibly have messed themselves up.  The sshd_config file was modified on Feb. 8.  Perhaps the user doesn't have the right key?  Without more direct information as to what they are experiencing, I can't diagnose this further. 
```
I'm not aware that we have made any changes that would affect this ... Pretty confident I haven't.

**Comment by karianna** [comment]
Sounds like someone might have to go in as root and do some spelunking.

**Comment by sxa555** [comment]
Error on my part - I gave the wrong IP - it should have been `148.100.110.37` chasing again.

**Comment by sxa555** [comment]
Latest update from Marist:

> On 3/13, they rebooted the server, presumably after making changes to the filesystem.  When Linux came back up, it went into safety mode because it cannot find /tmp.  It looks like another case of making a mistake when moving /tmp and hosing /etc/fstab so that the system cannot boot.

The machine has been requested to be recreated so we can have another shot at getting the builds back in place once it's back

**Comment by sxa555** [comment]
Got a replacement machine now - just need to get into it :-)

**Comment by sxa555** [comment]
Access acquired - will look to getting it set up

**Comment by sxa555** [comment]
New machine setup in progress.
[x] Configured root user in keybox
[x] [Defined to ansible / AWX inventory ](https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/351)(NOTE: had a slight issue with the extract from git getting tied up with AWX trying to update itself from the extract which meant the whole list of hosts temporarily disappeared)
[x] Complete execution of standard UNIX playbook (Ran into issue with missing `nagios-plugins-all` yum package - reverted in https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/353 and continuing
[x] Configured jenkins user in keybox
[x] Created new 100GB file system on `/dev/dasdb1` and mounted as `/data` with a `jenkins` directory underneath (same as old machine - matches the configuration jenkins had)
[x] Reconnected to jenkins with correct IP

**Comment by sxa555** [comment]
Closing this as the machine appears to be "functional" although is running so incredibly slowly that it is unfit for purpose at the moment - builds are timing out once they reach 3 hours).

Will raise another issue and reference this one in there.
