### ISSUE TITLE
No JDK9 available on Ubuntu s390x build machines e.g. build-marist-ubuntu1604-s390x-3

### ISSUE THREAD

**Issue by sxa555** [AdoptOpenJDK/openjdk-infrastructure#324]
Required to bootstrap JDK10 in the absence of the RHEL74 machine being available (Ref: https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/323)

**Comment by geraintwjones** [comment]
Looking at the playbooks, I find the following packages being installed...
- CentOS
  - `java-1.7.0-openjdk-devel`
  - `java-1.8.0-openjdk-devel`
- FreeBSD
  - `openjdk`
  - `openjdk8`
- OracleLinux
  - `java-1.8.0-openjdk-devel`
- RedHat
  - RHEL 6
    - `java-1.7.0-ibm-devel`
    - `java-1.8.0-ibm-devel`
  - RHEL not 6
    - `java-1.7.0-openjdk-devel`
    - `java-1.8.0-openjdk-devel`
- SLES
  - none
- Ubuntu
  - `openjdk-7-jdk`
  - `openjdk-8-jdk`

**Comment by geraintwjones** [comment]
### Observation

Looking at the Unix Playbooks, I can find the following JDK packages being installed...

- CentOS
  - java-1.7.0-openjdk-devel
  - java-1.8.0-openjdk-devel
- FreeBSD
  - openjdk
  - openjdk8
- OracleLinux
  - java-1.8.0-openjdk-devel
- RHEL
  - RHEL6_PPC64:
    - java-1.7.0-ibm-devel
    - java-1.8.0-ibm-devel
  - NOT_RHEL6_PPC64
    - java-1.7.0-openjdk-devel
    - java-1.8.0-openjdk-devel
- SLES
  - SLES12
    - java-1_8_0-openjdk
- Ubuntu
  - openjdk-7-jdk
  - openjdk-8-jdk

No JDK9 anywhere. I therefore can't explain where the JDK9 you told me was on the CentOS build machines came from.

**Comment by geraintwjones** [comment]
### Questions
1. Should JDK9 be on **all** build machines?
1. Why don't SLES machines other than SLES12 have any JDK on them?
1. Why don't SLES12 machines have JDK7 on them?
1. Am I right to assume that `openjdk` on FreeBSD is JDK7?

**Comment by sxa555** [comment]
1. JDK9 should be on all build machines that are building JDK10 as it's required for bootstrapping.
2. I suspect they're not used for buiding
3. See 2
4. Not sure - I've not looked at FreeBSD yet :-)

**Comment by sxa555** [comment]
The JDK9 on `build-osuosl-centos74-ppc64le-1` wasn't installed via `rpm`. My best guess is that it was extracted from one of our built builds but I'm not sure if that was documented anywhere or added to the playbook. @gdams?
```
[jenkins@build-osuosl-centos74-ppc64le-1 ~]$ rpm -qf /usr/lib/jvm/jdk-9+181/bin
file /usr/lib/jvm/jdk-9+181/bin is not owned by any package
[jenkins@build-osuosl-centos74-ppc64le-1 ~]$ /usr/lib/jvm/jdk-9+181/bin/java -version
openjdk version "9-internal"
OpenJDK Runtime Environment (build 9-internal+0-adhoc.jenkins.openjdk)
OpenJDK 64-Bit Server VM (build 9-internal+0-adhoc.jenkins.openjdk, mixed mode)
[jenkins@build-osuosl-centos74-ppc64le-1 ~]$ 
```

**Comment by sxa555** [comment]
As a tactical fix without knowing how the CentOS machines were set up I have modified the two build jobs I'm interested in (https://ci.adoptopenjdk.net/job/openjdk10_openj9_build_s390x_linux and https://ci.adoptopenjdk.net/job/openjdk10_openj9_build_ppc64le_linux/) to download our AdoptOpenJDK9 into the workspace and run from there if the JDK9_BOOT_DIR) is not set to anything useful.

**Comment by gdams** [comment]
Yes the jdk9 binaries have been pulled from our own website. (except for x64 linux which uses zulu 9)

**Comment by sxa555** [comment]
Cheers @gdams ... @geraintwjones FYI 

`cd /usr/lib/jvm && wget -O - https://github.com/AdoptOpenJDK/openjdk9-releases/releases/download/jdk-9%2B181/OpenJDK9_s390x_Linux_jdk-9.181.tar.gz | tar xpfz -`

That will extract it - we've got variables defined on each machine within jenkins that point to the directory to get it from that are picked up by the build scripts.

**Comment by gdams** [comment]
basically we just need to get our own `apt` and `rpm` repos setup and then ansible will easily pick up our binaries

**Comment by sxa555** [comment]
That is another option

**Comment by sxa555** [comment]
I think the smart move here will be to create a separate role to handle this

**Comment by sxa555** [comment]
My only concern with this is that on some machines we've left it with the original name in the tarball (i.e. `/usr/lib/jvm/jdk9+181` on `build-osuosl-centos74-ppc64le-1`) which is going to change. Should we make a point of renaming this to something neutral such as `adoptopenjdk-9-` instead of `jdk9+181` on the machine?

(This does raise the question of whether we should have a way to update if the release version is updated)
