### ISSUE TITLE
Automate the process of updating website certificates

### ISSUE THREAD

**Issue by smlambert** [AdoptOpenJDK/openjdk-infrastructure#325]
To ensure no one has down-time due to expiration of certificates (which has happened several times in the last year), we should look to automate that process, especially as more downstream projects are starting to depend on downloading collateral from the adoptopenjdk website.

**Comment by karianna** [comment]
Letsencrypt is the way forward here I suspect.

**Comment by gdams** [comment]
@smlambert This should actually be working now. There was an error in the auto renew scripts but I have fixed this.

**Comment by sxa555** [comment]
Replaced again this weekend:
```
cd /opt/letsencrypt
./letsencrypt-auto --config /etc/letsencrypt/configs/ci.adoptopenjdk.net.conf certonly
```

**Comment by sxa555** [comment]
Ran the above again today as it had expired
