### ISSUE TITLE
Restart server.js when restarting the API server

### ISSUE THREAD

**Issue by karianna** [AdoptOpenJDK/openjdk-infrastructure#327]
See https://github.com/AdoptOpenJDK/openjdk-api/issues/51 for the full write up

**Comment by gdams** [comment]
`export PRODUCTION=true && /usr/local/bin/forever start /home/{{ Jenkins_Username }}/openjdk-api/server.js` is the command used to start the server. Should just be a case of writing a startup script that contains that command

**Comment by gdams** [comment]
I believe that this is now resolved? @johnoliver ?

**Comment by karianna** [comment]
This does work (the playbook fails to run npm install but there's a separate bug)
