### ISSUE TITLE
(keybox issue?) build-scaleway-x64-ubuntu-16-04-2 - 51.15.46.107 - not accepting jenkins' ssh key

### ISSUE THREAD

**Issue by sxa555** [AdoptOpenJDK/openjdk-infrastructure#332]
Jenkins is showing this when you try to start the slave. This is the machine used for a lot of the docker work so it's holding up 
https://ci.adoptopenjdk.net/computer/build-scaleway-x64-ubuntu-16-04-2/

```
ERROR: Server rejected the 1 private key(s) for jenkins (credentialId:b8101a03-36e8-4687-a722-d48ad48acd5c/method:publickey)
[04/04/18 23:36:11] [SSH] Authentication failed.
Authentication failed.
```

**Comment by sxa555** [comment]
jenkins `authorized_keys` files is zero bytes in length. Perhaps the file system filled up at some point and it went awry

**Comment by sxa555** [comment]
copied from another machine (SLES12/s390x one) and it's now back running and running through the jobs queue.

**Comment by sxa555** [comment]
Weirdly this seems to have recurred. I wonder if we've got a keybox issue. Fixed again but leaving open so it's visible in case it recurs.

**Comment by karianna** [comment]
@sxa555 Shall we close again? Else this will just stay open forever....

**Comment by gdams** [comment]
Seems to be working now. Closing
