### ISSUE TITLE
Add new Windows test machines to project infrastructure

### ISSUE THREAD

**Issue by tellison** [AdoptOpenJDK/openjdk-infrastructure#337]
Two new Windows 2012R2 machines have been created under issue #334 .
These need configuring with Ansible, and adding to Nagios, Jenkins etc as per the usual infra checklist.

1. `test-win2012-1.adoptopenjdk.net` (169.55.170.72) to be known to Jenkins as `test-softlayer-x64-windows-2012r2-1` and,
1. `jck-win2012-1.adoptopenjdk.net` (169.55.170.68) to be known to Jenkins as `jck-softlayer-x64-windows-2012r2-1`.

Administrator login passwords available under private communication.

Each one is 2 CPU, 8GB RAM, Windows 2012R2, 100Gb boot disk, 25 Gb data disk, 100 Mbs network link.

**Comment by bblondin** [comment]
**To do List:**

- [ ] Create pull request to add these system to the Ansible inventory file
- [ ] Create new entries in secrets gpg
- [ ] Refresh Ansible dynamic inventory 
- [ ] Execute Playbook on is system
- [ ] Configure system in Jenkins

**Comment by sxa555** [comment]
JCK machine added into the JCK jenkins instance. java and firefox are the only things installed and there's a "startjenkins" script in the jenkins (new user) homedir to initiate it.

**Comment by sxa555** [comment]
Blocked on the test machine due to my github credentials to ansible seemingly not working (I'm sure it has in the past!)

**Comment by sxa555** [comment]
java (default location) and git (C:\git) installed on the JCK machine and it's connected to jenkins as `jck-softlayer-x64-win2012r2-1`

**Comment by sxa555** [comment]
Need to ensure these are not subject to https://github.com/AdoptOpenJDK/openjdk-systemtest/issues/165
