### ISSUE TITLE
Please add my key to the secrets repository

### ISSUE THREAD

**Issue by geraintwjones** [AdoptOpenJDK/openjdk-infrastructure#346]
The key I (geraintj@uk.ibm.com) currently have in the secrets repository is no longer valid. I had to regenerate it because...
- I forgot my passphrase, and am suitably embarrassed about it.
- `dotgpg` has broken on my Macbook and I can't get it working. I've decided to throw it away and am now using `gpg` directly, with some help from a tool called GPG Keychain.

Because of this, I have regenerated my key, which means that the one in the repository is no longer correct.

Please replace it with this one...

```
-----BEGIN PGP PUBLIC KEY BLOCK-----

mQENBFrXXcQBCADfk/YTm7KZMILVEz9iim4RqN732Wuvds/gDpJSib8w/B3zgMcI
jucjQHFEKs5qlONEy3HOH4HZ1ktD4YgX+fuW3jr1JEvG5quKJ3bwjRdcRavYidBH
5VcAcuphLMwHIRKvex7aJakpbwgWAZFUZMW8ZhZ0EXj/SXkUMMl3y/PJQP//oKrX
8CWtARv7Dzx0mJx9Gb1UEPM6EDEheT4SHfW5nD9lwbdHM9p9+cVy3fQYFKMcpg0g
GgxGZK4PHgpZIB/kIA8iBf1HA7CGnKIupiBmcsh4/t3bx3PO/XK/1JDPanmBoqJz
iELwoVEwUx7Oo2z/fihBVVOsP9GXviXE4vFxABEBAAG0I0dlcmFpbnQgSm9uZXMg
PGdlcmFpbnRqQHVrLmlibS5jb20+iQFOBBMBCAA4FiEEhV7tkffzA6+FCOSjYnhS
uZ5uytoFAlrXXcQCGwMFCwkIBwIGFQoJCAsCBBYCAwECHgECF4AACgkQYnhSuZ5u
ytrZuAf9GldZi3DACad98PWfkpRXAslYz07LJtMQg6HgsTXCgPpLmUDevOotHgEE
hqPUlMt8/lMhUYc5A/9MYtzP78MzOlhFwxQc8pi7XoaXRm6CFuKb0NT2A0Ei0yej
gASCQ7aoin2qb0gcI1YwjTuE+p0Rlj7fG+CccNjAG3pYwgqR6dqZ8blIUFrb+Ad/
7gczNZgzwrkqynZmwAoyj98CVli9/b+7mZz+1wrzvxKmgNFBRR50BPZ1h0Q969Rj
zGb6OJMgEpGQ96NSqOwc4hbvC+a6bMDuE63hletzDMaGrUXsDI40fnl2nKVYPQMw
pbKESoI5Gh5bk/T1y67XD8ewcW4fMLkBDQRa113EAQgA5GjHkdNHBvuJ1BoyYrBQ
zGwcIs4b9Tq9GzHdeCRQ+K0LPkc62x1v75LaZP3jEBhlwYrmlBTNS0yTsTqRf+KL
NbfxIprC6+/43DxGW3Ka8sjnFmHz5AnK0oXZLqtyXEbiFlElg1FHrX17Y/CrXBMS
hjZCHdCCXlwpLNaD/SnHXZR8A57lEbZvbWSFWJINuWiBK69V1NhRuYv6mW8QRymF
hdA7vzfpIlnKCLf34LBAy3nGsLn1nWtvD8QltzUL+I8lrO1Plp+i1eGE5XKHJX9m
LxeZ5LI3yc0smEs44ei2q2M7dW2A3jXaJgC/Muyu7dUj6ij1hkVZk4Dcd0H4Cecz
zwARAQABiQE2BBgBCAAgFiEEhV7tkffzA6+FCOSjYnhSuZ5uytoFAlrXXcQCGwwA
CgkQYnhSuZ5uytrr+wf+Ofse6YPl4aekN9zEqrYyWVLrM0/28fWNF88SHRc8dYAP
4L74cO+jcmw1pEkZwSvtdofQ16B/t5cbXquHkWUt/p3mRFYn+F7RYR3mRUMXPM1C
3WZStScsF5PUcnUwhpd890pN3FFfb4bDFEIEWmN7m6gRPci6vE81rIIDdJZU5Gbb
Ea/IbwX5grjPXUc8HM1nRXkhU9mp1oNH5OOS4/lmOoh5lt3vwPTSfKr4u2R/N9Ay
Ug1/HN60VJ+VnDtaAr7YA2LXvDzGoXd5xrS21aF171sKy+dutbyc7IqOQtPfKaUE
KGpLQ6Ukdr6FYV8mAXszeMPgsDrjrtXkQKKJn2zyZA==
=MicK
-----END PGP PUBLIC KEY BLOCK-----
```

Thank you.

Note: for those of you for whom `dotgpg` works, here's what https://github.com/ConradIrwin/dotgpg/blob/master/README.md#use-without-ruby has to say...

> If you can't remember your passphrase then you generate a new key with `dotgpg key -n` and ask someone on your team to overwrite your existing key with `dotgpg add -f`.

Just mentioning it in case it helps :-)

This issue is the equivalent of asking someone to do `dotgpg add -f`.

**Comment by karianna** [comment]
My bad, I should have asked for this to go to secrets repo - I've added an issue in there instead.

**Comment by geraintwjones** [comment]
Haha :-) @pnstanton asked me if that's where it should be, but I said no, and since there were no issues over there, I created it here.

**Comment by geraintwjones** [comment]
The issue in the secrets repo is https://github.com/AdoptOpenJDK/secrets/issues/13.
