### ISSUE TITLE
Add Docker to all linux / mac playbooks 

### ISSUE THREAD

**Issue by smlambert** [AdoptOpenJDK/openjdk-infrastructure#347]
We can/should increase the number of test machines that have Docker available on them, to optimize our machine usage (to have the flexibility to add more or shift some testing into Docker containers.

**Comment by Mesbah-Alam** [comment]
The more machines we'd have with Docker installed, the better will shorter it will take for the External test builds (https://ci.adoptopenjdk.net/view/External%20tests/) to run, as we are going to parallellize the execution process for each different type of test under the External test builds. Currently they are running serially and taking somewhere betteen 2-4 hours on an average to finish. Moreover, we are actively working on adding new external tests (e.g. OpenLiberty will be added soon) - which will slow down the builds even further and may force us to make these builds run only weekly as opposed to nightly. So, having more docker-enabled machines will greatly help the cause going forward.

**Comment by sxa555** [comment]
Running the current playbooks on the following machines so will see what we end up with - current list with the tag are as follows: https://ci.adoptopenjdk.net/label/sw.tool.docker/ ;-)
- [test-osuosl-ubuntu1604-ppc64le-2](https://ci.adoptopenjdk.net/computer/test-osuosl-ppc64le-ubuntu-16-04-2/)
- [test-packet-ubuntu1604-x64-2](https://ci.adoptopenjdk.net/computer/test-packet-ubuntu1604-x64-2/)

**Comment by sxa555** [comment]
Now installed on both machines - if you can test and let me know if any further setup is needed that isn't in the playbooks that would be good

**Comment by sxa555** [comment]
@chandrams looks like there were alrady one ppc64le and s390x machine available - are they working ok for you now?

**Comment by sxa555** [comment]
Will assume this is ok now - please reopen if not
