### ISSUE TITLE
Build OpenJDK 10 for EV3 on ci.adoptopenjdk.net

### ISSUE THREAD

**Issue by jabrena** [AdoptOpenJDK/openjdk-infrastructure#355]
Hi,

I need to create new Tab on Jenkins with the name: `ev3dev` in AdoptOpenJDK CI infrastructure:
https://ci.adoptopenjdk.net/

The idea is the development of Jenkins jobs to build OpenJDK for ARM5 (Lego mindstorms EV3): 
https://github.com/ev3dev-lang-java/openjdk-ev3/

Currently, the project supports:

- OpenJDK 9 JDK
- OpenJDK 10 JDK
- OpenJDK 9 JRI
- OpenJDK 10 JRI

Subtasks:

- [x] Create view `ev3dev` https://ci.adoptopenjdk.net/view/ev3dev/
- [x] Create the project on Jenkins:  OpenJDK-10-EV3
- [x] Execute bash scripts on Jenkins Project.
- [ ] Run initial JenkinsFile to test the intregration from develop branch
- [ ] Upgrade JenkinsFile with the instructions from README.md https://github.com/ev3dev-lang-java/openjdk-ev3

Juan Antonio

**Comment by jabrena** [comment]
I have created in `develop` branch a JenkinsFile to test the integration.
https://github.com/ev3dev-lang-java/openjdk-ev3/tree/develop/
https://github.com/ev3dev-lang-java/openjdk-ev3/blob/develop/OpenJDK10_Jenkinsfile

Later, will upgrade the `Jenkinsfile` with the right statements but it is a good way to test the integration.

Juan Antonio

**Comment by jabrena** [comment]
Using the Jenkins feature `Replay` I will refactor the Jenkins file until I get the right execution to build OpenJDK 10 for ARM5.

**Comment by jabrena** [comment]
Created View:
https://ci.adoptopenjdk.net/view/ev3dev/

It is necessary to create a project for the view: OpenJDK-10-EV3

**Comment by jabrena** [comment]
Project created.
It is necessary to link Jenkinsfile created:
https://github.com/ev3dev-lang-java/openjdk-ev3/blob/develop/OpenJDK10_Jenkinsfile

with the project:
https://ci.adoptopenjdk.net/view/ev3dev/job/openjdk-10-ev3/

**Comment by sxa555** [comment]
@jabrena Is this issue still live and are there outstanding actions to take (Given that it says JDK10 I suspect at the very least it's outdated)

**Comment by jabrena** [comment]
Sorry, it is a bit old. I am going to close it.

Currently, we have support until java 13 in a stable way.
https://github.com/ev3dev-lang-java/openjdk-ev3
