### ISSUE TITLE
Deploy Packet aarch64 OpenStack

### ISSUE THREAD

**Issue by gdams** [AdoptOpenJDK/openjdk-infrastructure#356]
We currently have 3 large aarch64 machines from packet. If we install openstack then we can split this down and get a better test coverage.

I am working with @vielmetti to deploy https://github.com/WorksOnArm/OpenStackWorksOnArm

**Comment by gdams** [comment]
openstack deployed http://147.75.197.162/horizon/

**Comment by vielmetti** [comment]
Discussion of the details of OpenStack configuration going on in the Packet community Slack channel, which is also IRC Freenode #packethost .

**Comment by vielmetti** [comment]
Waiting for an IP address allocation from Packet to provide public IPs for the VMs.

**Comment by vielmetti** [comment]
IP's are now allocated.

**Comment by vielmetti** [comment]
We appear to have run into https://bugs.launchpad.net/cloud-images/+bug/1573095 to get Ubuntu images up and running.

**Comment by karianna** [comment]
Hi @vielmetti Have we been able to progress this?

**Comment by vielmetti** [comment]
Hi @karianna - the report from the bug report is "if i add a serial console to the VM it boots fine.".

@gdams I'm ready to help tackle this to the best of my ability if it's still an issue.

**Comment by gdams** [comment]
hi @vielmetti it is still an issue for me. I was going to try and spend a bit more time on it next week as it's been on the backburner for the last week

**Comment by vielmetti** [comment]
alerting @edolnx to this (and also via email) for next week.

**Comment by gdams** [comment]
closing for now as we've got some openlab machines
