### ISSUE TITLE
Some Marist zLinux machines are running slow

### ISSUE THREAD

**Issue by sxa555** [AdoptOpenJDK/openjdk-infrastructure#357]
The following machines are experiencing extremely low performance at present:

- build-marist-rhel74-s390x-1 (Reprovisioned as per https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/323) - builds timing out after 3 hours, took 38 minutes on the previous machine https://ci.adoptopenjdk.net/job/openjdk8_build_s390x_linux/195
- Both Linux/s390x JCK machines appear to be suffering a similar slowdown

**Comment by sxa555** [comment]
After optimistically setting the `openjdk8_(openj9_)build_s390x_linux` jobs to include the rhel74 tag I'm going to remove it again. Likewise for https://ci.adoptopenjdk.net/job/openjdk_amber_build_s390x_linux/ I'm also going to remove the `openj9` tag from the machine https://ci.adoptopenjdk.net/computer/build-marist-rhel74-s390x-1/ so that it isn't used for any of those builds either.

**Comment by irinarada** [comment]
@sxa555 - is this the underlying reason for the lack of builds on 390?

**Comment by r30shah** [comment]
Is there an ETA on when this will be fixed? Right now last build for Linux s390x we have is from 23rd March. There were some recent changes went into OpenJ9 which we want one of our customer to try out.

**Comment by sxa555** [comment]
This one had slipped off my radar - I'll figure out something even if it's upping the timeout for now as i don't think I've heard anything back on what might have caused this. Thanks for the prod @irinarada  :-)

**Comment by sxa555** [comment]
@r30shah Which version (8/9/10) is it that's highest priority for you?

**Comment by irinarada** [comment]
Highest priority is Java 8

**Comment by sxa555** [comment]
Builds appear to have sped up again, therefore closing

**Comment by sxa555** [comment]
Reopening this because `build-marist-rhel74-s390x-1` is running incredibly slowly. Seems to be CPU bound on `gmake` which suggests a very slow CPU or being held up by disk access:
```
top - 11:31:53 up 90 days, 19:37,  1 user,  load average: 1.01, 1.02, 1.05
Tasks: 119 total,   2 running, 113 sleeping,   0 stopped,   4 zombie
%Cpu(s): 25.0 us,  0.0 sy,  0.0 ni, 75.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem :  8047704 total,   827880 free,  1039304 used,  6180520 buff/cache
KiB Swap:  2549736 total,  2021624 free,   528112 used.  6858396 avail Mem 

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                    
27768 jenkins   20   0  870860 756492    936 R 100.0  9.4 125:56.41 gmake                                                      
24367 jenkins   20   0 2530268 186184   3228 S   0.7  2.3 344:46.83 java                                                       
24279 jenkins   20   0   17228   2708    604 S   0.0  0.0   2:19.57 sshd                                                       
24353 jenkins   20   0  107060   1180   1180 S   0.0  0.0   0:00.00 bash      
```

**Comment by sxa555** [comment]
Same issue still occurring - at the images phase gmake is sitting usin 100% of a core for a long period of time.

**Comment by sxa555** [comment]
Note: jdk11u builds at https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-linux-s390x-hotspot/ are not affected in the same way.

**Comment by sxa555** [comment]
Build 101 seems to have completed in 2h28 instead of 5-6 hours previously (although that may have been running in parallel with an 11 build so a bit slower than it might have been). Build 102 finished in 1h05

**Comment by sxa555** [comment]
NOTE: This solution does require the `/usr/bin/gmake` symlink to be pointing to 4.1 therefore replaces the `gmake->make` symlink that is installed by default on RHEL to the `3.81` version (other option is of course to ensure `/usr/local/bin` is first in the path in the build env.
