### ISSUE TITLE
missing autoconf and hg (at least) on aarch64 builder

### ISSUE THREAD

**Issue by judovana** [AdoptOpenJDK/openjdk-infrastructure#365]
and maybe more... we will see...

**Comment by sxa555** [comment]
Installed autoconf on `build-linaro-centos74-armv8-1` `build-linaro-centos74-armv8-2`  and `build-linaro-centos74-armv8-1`

hg was already on `build-linaro-centos74-armv8-1` and `build-linaro-centos74-armv8-2` and I've installed on `packet-centos74-armv8-1`

Leaving this work item open until it can be verified that the playbooks cover this.

**Comment by judovana** [comment]
checking if static link of stdc++ is possible... no
configure: error: Static linking of libstdc++ was not possible!
configure exiting with result code 1


that means installing: yum -y install libstdc++-static

**Comment by sxa555** [comment]
> libstdc++-static

Installed on all three machines

**Comment by judovana** [comment]
ty. build is now running; passing the configure

**Comment by sxa555** [comment]
Memo to self: These failures were seen during the execution of https://ci.adoptopenjdk.net/job/openjdk8_build_arm64_linux/6/console
