### ISSUE TITLE
dead link 520 error https://api.adoptopenjdk.net/openjdk9 - playbook

### ISSUE THREAD

**Issue by bblondin** [AdoptOpenJDK/openjdk-infrastructure#366]
While running the [Unix playbook ](https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/master/ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/adoptopenjdk9/tasks/main.yml) The following error is seen

```
TASK [adoptopenjdk9 : Install latest release if one not already installed] *****22:12:58
509
fatal: [10.20.13.87]: FAILED! => {"changed": false, "msg": "Failure downloading https://api.adoptopenjdk.net/openjdk9/releases/x64_linux/latest/binary, HTTP Error 520: Origin Error"}
```

Attempting to `curl https://api.adoptopenjdk.net/openjdk9/releases/x64_linux/latest/binary` fails with: `Error 520 Ray ID: 41fc4f71bf903048 • 2018-05-24 02:25:12 UTC Web server is returning an unknown error`

curl'ing https://api.adoptopenjdk.net/openjdk8 is working fine

**Comment by bblondin** [comment]
This currently blocks deployment and updates to systems. 

**Workaround**: use either the command line `--skip-tags` option or via AWX use Skip Tags (in the template) `adoptopenjdk9`

**Comment by karianna** [comment]
Or we need to get a Java 9 release out again pronto (which we're working on)

**Comment by gdams** [comment]
we could just switch it to use the latest nightly for now?

**Comment by karianna** [comment]
I'd go latest nightly

**Comment by sxa555** [comment]
Ref: https://github.com/AdoptOpenJDK/openjdk-build/issues/317 which is what caused it (linking to tie issues together to make them all easier to close off later :-) )

**Comment by gdams** [comment]
switched to nightly for now. closing
