### ISSUE TITLE
Add building of freetype (32+64 versions) to the Windows playbook

### ISSUE THREAD

**Issue by sxa555** [AdoptOpenJDK/openjdk-infrastructure#367]
Current freetype role at https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/master/ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/Freetype/tasks/main.yml seems to download the source but not build it. The built 64-bit version is in `C:\openjdk\freetype\{include,lib}` on the build machines - unclear of the source. We need a 32-bit version to satisfy https://github.com/AdoptOpenJDK/openjdk-build/issues/342, and get both versions into the ansible playbooks for setting up windows machines

**Comment by sxa555** [comment]
Build on `build-softlayer-win2012r2-x64-1` as follows:
```
msbuild.exe builds\windows\vc2010\freetype.vcxproj /p:PlatformToolset=v100 /p:Configuration="Release Multithreaded" /p:PlatformTarget=x86 /p:ConfigurationType=DynamicLibrary /p:TargetName=freetype /p:OutDir="C:/openjdk/freetype-2.5.3/lib32/" /p:IntDir="C:/openjdk/freetype-2,.5.3/obj32/"
msbuild.exe builds\windows\vc2010\freetype.vcxproj /p:PlatformToolset=v100 /p:Configuration="Release Multithreaded" /p:PlatformTarget=x86 /p:ConfigurationType=StaticLibrary /p:TargetName=freetype /p:OutDir="C:/openjdk/freetype-2.5.3/lib32/" /p:IntDir="C:/openjdk/freetype-2,.5.3/obj32/"
```

**Comment by gdams** [comment]
okay so `C:\openjdk\freetype\` was prebuilt by myself for the jdk8u builds. The newer builds just take the source and automatically handle the building as part of the job! We'll need to add a custom build of 32 bit though

**Comment by cwesMills** [comment]
@sxa555 I've just come across this issue and had to manually build freetype. I'm willing to take over this issue if you'd like.

**Comment by sxa555** [comment]
Thanks @cwesMills (And sorry for the delay in reponding!) Just one of those issues that's been on my backlog for a while so the help is appreciated!
