### ISSUE TITLE
JCK10 build can't find OpenJDK10-OpenJ9 SDK to download 

### ISSUE THREAD

**Issue by Mesbah-Alam** [AdoptOpenJDK/openjdk-infrastructure#368]
**daily_openjdk10_j9_jcktest_x86-64_linux** build has failed due to the fact that it can't find the SDK to download from where it looks for it.  

Same with **daily_openjdk10_j9_jcktest_s390x_linux**:  

**Error**
```
00:02:29.163 [daily_openjdk10_j9_jcktest_x86-64_linux] Running shell script
00:02:29.458 + /home/j9build/workspace/daily_openjdk10_j9_jcktest_x86-64_linux/openjdk-tests/get.sh -s /home/j9build/workspace/daily_openjdk10_j9_jcktest_x86-64_linux -t /home/j9build/workspace/daily_openjdk10_j9_jcktest_x86-64_linux/openjdk-tests -p x64_linux -v openjdk10-openj9 -r upstream -c https://api.adoptopenjdk.net/openjdk10-openj9/nightly/x64_linux/latest/binary --openj9_repo https://github.com/eclipse/openj9.git
00:02:29.458 git clone  https://github.com/eclipse/openj9.git
00:03:51.524 binary
00:03:51.525 
00:03:51.525 gzip: binary: not in gzip format
00:03:51.525 tar: This does not look like a tar archive
00:03:51.525 tar: Exiting with failure status due to previous errors
00:03:51.525 ls: cannot access */: No such file or directory
00:03:51.525 mv: missing destination file operand after ‘j2sdk-image’
00:03:51.525 Try 'mv --help' for more information.
```

Has anything changed in the way builds are published at `api.adoptopenjdk.net/openjdk10-openj9/nightly/` ? 

**Note:** 

The API links for OpenJDK8-OpenJ9 and OpenJDK9-OpenJ9 are working, but OpenJDK10-Openj9 is not. 

OpenJDK8-OpenJ9: https://api.adoptopenjdk.net/openjdk8-openj9/nightly/x64_linux/latest/ (works)
OpenJDK9-OpenJ9: https://api.adoptopenjdk.net/openjdk9-openj9/nightly/x64_linux/latest/ (works)
OpenJDK10-OpenJ9: https://api.adoptopenjdk.net/openjdk10-openj9/nightly/x64_linux/latest/ (doesn't work)

**Comment by karianna** [comment]
@gdams is leading the charge to replace those.

**Comment by sophia-guo** [comment]
refer to https://github.com/AdoptOpenJDK/openjdk-tests/issues/380

**Comment by karianna** [comment]
also see #366

**Comment by sxa555** [comment]
@Mesbah-Alam Where are the jobs you're referring to? They're not anything on the adoptopenjdk jenkins instances as far as I'm aware ...

**Comment by Mesbah-Alam** [comment]
I was referring to jck builds in the internal urv-jenkins (e.g. https://urv-jenkins.canlab.ibm.com:9095/view/JCK_Tests/) @sxa555

**Comment by sxa555** [comment]
@Mesbah-Alam Please don't post non-external URLs here. Is this still a problem that needs to be addressed? I'm assuming it's been resolved one way or another since no-one's been shouting at me for it :-)

**Comment by Mesbah-Alam** [comment]
Yes, it has been resolved.
