### ISSUE TITLE
Add  "binfmt-support" and "qemu-user-static" packages on build-scaleway-x64-ubuntu-16-04-2

### ISSUE THREAD

**Issue by jabrena** [AdoptOpenJDK/openjdk-infrastructure#369]
Good morning,

In order to execute the Testing jobs for the OpenJDK build for ARM5:
https://ci.adoptopenjdk.net/view/ev3dev/job/openjdk-10-ev3-test/

We need to be installed the following dependencies:

- binfmt-support
- qemu-user-static

Related issues:
https://github.com/ev3dev-lang-java/ev3dev-lang-java/issues/513

Juan Antonio

**Comment by gdams** [comment]
These have been installed. I'll leave the issue open so that we remeber to add this to the ansible playbooks

**Comment by jabrena** [comment]
I will test the pipeline now.

**Comment by JakubVanek** [comment]
Yaay!

Thank you @gdams, the container build now starts successfully.

https://ci.adoptopenjdk.net/job/openjdk-10-ev3-test/16/console

**Comment by jabrena** [comment]
For that server, the package was not installed: test-packet-ubuntu1604-x64-1 
https://ci.adoptopenjdk.net/job/openjdk-10-ev3-test/19/console

**Comment by jabrena** [comment]
Hi @gdams,

For some reason, now on `build-scaleway-x64-ubuntu-16-04-2`, it not working. Why?

**Comment by jabrena** [comment]
Hi @gdams,

I have just noticed that now the server `build-scaleway-x64-ubuntu-16-04-2` not have the packages.
https://ci.adoptopenjdk.net/job/openjdk-10-ev3-test/25/console

Any rollback?

Many thanks in advance.

Juan Antonio

**Comment by jabrena** [comment]
Running again the Pipeline. :) 
https://ci.adoptopenjdk.net/view/ev3dev/job/openjdk-10-ev3-test/40/console

**Comment by sxa555** [comment]
@jabrena looks like we're green on the last couple of runs - does that mean this can now be closed off?

**Comment by karianna** [comment]
@sxa555 I don't think these were added to ansible

**Comment by sxa555** [comment]
@karianna See earlier up where gdams has a PR to do it - at least for Ubuntu ...

**Comment by jabrena** [comment]
Hi @sxa555, yes from last week, Testing machines run fine with the packages.

**Comment by karianna** [comment]
In that case closing!
