### ISSUE TITLE
install newer version of autoconf on centos6

### ISSUE THREAD

**Issue by gdams** [AdoptOpenJDK/openjdk-infrastructure#371]
required steps:

```bash
yum install ftp://ftp.pbone.net/mirror/ftp5.gwdg.de/pub/opensuse/repositories/home:/monkeyiq:/centos6updates/CentOS_CentOS-6/noarch/autoconf-2.69-12.2.noarch.rpm
```

**Comment by sxa555** [comment]
@gdams Just to flesh out this issue, why is a newer one needed?

**Comment by gdams** [comment]
jdk10u builds and above require the later autoconf. This only applies to centos6 (not 7)

**Comment by sxa555** [comment]
This appears to have been installed on both `build-joyent-centos69-x64-1` and `build-digitalocean-centos69-x64-1`. Might be one that's worth adding to our self-hosted stuff Ref: https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/439

**Comment by sxa555** [comment]
The referenced PR contains the options that we could use going forward - basically need to choose between a source build or using this third-party RPM

**Comment by sxa555** [comment]
Looks like the code at present is attempting to build from source, although the playbooks are broken if you try and run on anything other than RHEL6 because it tries to reference the return code from a version check that is skipped on other systems.

**Comment by sxa555** [comment]
`autoconf_version.rc` is being checked even when the step that creates it is skipped. The referenced PR re-orders the step prereq checking to prevent this.
```
TASK [autoconf : Test if Autoconf v2.69 is installed] **************************
14:19:22
skipping: [build-osuosl-centos74-ppc64le-2]
TASK [autoconf : Download Autoconf v2.69] **************************************
14:19:22
fatal: [build-osuosl-centos74-ppc64le-2]: FAILED! => {"failed": true, "msg": "The conditional check '((autoconf_version.rc == 0) and (autoconf_version.stdout | version_compare('2.69', operator='lt')))' failed. The error was: error while evaluating conditional (((autoconf_version.rc == 0) and (autoconf_version.stdout | version_compare('2.69', operator='lt')))): 'dict object' has no attribute 'rc'\n\nThe error appears to have been in '/var/lib/awx/projects/_6__adoptopenjdk_git_infrastructure/ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/autoconf/tasks/main.yml': line 15, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Download Autoconf v2.69\n  ^ here\n"}
```
