### ISSUE TITLE
Addition of jdekonin to the openjdk-infrastructure team

### ISSUE THREAD

**Issue by jdekonin** [AdoptOpenJDK/openjdk-infrastructure#375]
Can I please be added to the infrastructure team?  Thanks

**Comment by karianna** [comment]
Hi @jdekonin Welcome to AdoptOpenJDK!  We usually get people to go through a few pull requests etc  before giving full fledged access.  I'll keep this open as a placeholder though!

**Comment by jdekonin** [comment]
I've been supplying changes since November last year.  I've also been active in reviewing changes other than my own.
https://github.com/AdoptOpenJDK/openjdk-infrastructure/commits?author=jdekonin

**Comment by gdams** [comment]
I'm happy to sponsor @jdekonin's access to the infra team. Please add a PR to add yourself to https://github.com/AdoptOpenJDK/openjdk-infrastructure#infrastructure and we can then proceed with the onboarding.
