### ISSUE TITLE
Add John Oliver to the Infra team

### ISSUE THREAD

**Issue by karianna** [AdoptOpenJDK/openjdk-infrastructure#381]
I'd like to nominate @johnoliver to the infra team - he's going to be heading our infra security and has run devops at jClarity for the past 4 years (Linux, Windows, MacOS X, Puppet etc).

**Comment by tellison** [comment]
+1

**Comment by gdams** [comment]
@karianna please create a pull request to add @johnoliver to the README and we can approve this over there. Also to clarify is this as an infra member or an infra-admin?

**Comment by karianna** [comment]
@gdams infra-admin - he's going to need to have super powers with you and Peter in case our farm gets compromised...

**Comment by sxa555** [comment]
All done. Closing. @gdams if there is anything further on this topic please open a separate issue.
