### ISSUE TITLE
Downgrade Grep to 2.27-2 on windows

### ISSUE THREAD

**Issue by gdams** [AdoptOpenJDK/openjdk-infrastructure#384]
jdk8u builds require `grep 2.27-2` but cygwin defaults to `grep 3.0`. There seems to be no easy way to programatically downgrade the package so this may take a bit of working out but ideally needs to be added to the playbook. Installed manually using the cygwin.exe gui application for now.

**Comment by gdams** [comment]
error for reference:

```bash
make[2]: *** [/cygdrive/c/Users/jenkins/workspace/openjdk8_build_x86-64_windows/openjdk/build/windows-x86_64-normal-server-release/images/lib/_the.rt.jar.contents] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [images] Error 2```

**Comment by ali-ince** [comment]
I've just downgraded grep `3.0-2` to `2.27-2` on host `build-softlayer-win2012r2-x64-1`. This is basically to test out if it will break any other build that's scheduled to run on these hosts. 

If everything works fine, then I'll also downgrade it on `build-softlayer-win2012r2-x64-2` and try to come up with an ansible script (`cygwin-setup.exe` doesn't provide a way to downgrade a base package on the command line, so one hack I thought of was to download `2.27-2` and unpack it to override the existing version). wdyt about such an approach @gdams?

**Comment by karianna** [comment]
Can we have both greps and symlink the right one for the right build?

**Comment by ali-ince** [comment]
@karianna Although that would be an option, I believe it will complicate the build definitions to have two different versions and having to modify symlinks for each build.

Seeing that there's not any build failures on `build-softlayer-win2012r2-x64-1` from the build history, I can make the same change on `build-softlayer-win2012r2-x64-2` too.

Any other comments on overwriting grep or should it leave as a manual step?

**Comment by karianna** [comment]
@ali-ince OK, go ahead then thanks!
