### ISSUE TITLE
Insufficient free space on jck-softlayer-x64-ubuntu-16.04-1

### ISSUE THREAD

**Issue by lumpfish** [AdoptOpenJDK/openjdk-infrastructure#386]
The JCK run here https://ci-jck.adoptopenjdk.net/job/JCK-fullrun-x64-linux/92/consoleFull. failed because the test machine did not have enough free disk space.

The tests require that there be 3Gb free disk space.  At the start of the test runs there was c. 3.5 Gb free, but part way through (about 80%) there was <3Gb (presumably taken up by logging and results files).

**Comment by sxa555** [comment]
Resolved (I fixed it on Wedneday but hadn't closed this item)
