### ISSUE TITLE
Install Ant 1.8.4 or higher on test machines 

### ISSUE THREAD

**Issue by Mesbah-Alam** [AdoptOpenJDK/openjdk-infrastructure#387]
Ant version 1.8.4 or later is required by system tests, as listed in https://github.com/AdoptOpenJDK/openjdk-systemtest/blob/master/openjdk.build/docs/build.md

This issue is to track the work of ensuring we have the correct version of Ant installed on all the Adopt test machines. 

fyi.. @AdamBrousseau

**Comment by vsebe** [comment]
This should also remove all of the ant* installed packages via package manager (yum, aptitude) and install ant from binaries in /usr/local on all systems.

**Comment by sxa555** [comment]
@vsebe does that PR solve this problem? It only seems to change things for ant-contrib, not ant itself.

**Comment by vsebe** [comment]
@sxa555 - It should. There is also an [ant role](https://github.com/AdoptOpenJDK/openjdk-infrastructure/tree/master/ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/ant/tasks) that installs ant.
@Mesbah-Alam please verify, thank you!

**Comment by Mesbah-Alam** [comment]
I do not see any failure in system test builds related to older than recommended version of Ant installation. I will close this issue at this point. Will open separate issue(s) if it surfaces again. Thanks.
