### ISSUE TITLE
Request to add Sophia Guo as a Jenkins admin

### ISSUE THREAD

**Issue by smlambert** [AdoptOpenJDK/openjdk-infrastructure#388]
As Sophia Guo (@sophia-guo) is a core test team member and has helped and will continue to help update, troubleshoot and enable build and test pipelines, it will be very beneficial to get her Jenkins admin privileges.

**Comment by karianna** [comment]
Added to release team for the same access.  @smlambert and @sophia-guo let us know if that's not sufficient
