### ISSUE TITLE
Request to install numactl for ODM test

### ISSUE THREAD

**Issue by llxia** [AdoptOpenJDK/openjdk-infrastructure#394]
For performance test (ODM), we need to run `numactl`. I would like to request to install `numactl` on the following machines. Thanks.
https://ci.adoptopenjdk.net/computer/test-packet-ubuntu1604-x64-2/
https://ci.adoptopenjdk.net/computer/test-softlayer-ubuntu1604-x64-1/

Related issue https://github.com/AdoptOpenJDK/openjdk-tests/issues/457

**Comment by jdekonin** [comment]
This is installed in unix playbooks on rhel via `numactl-devel` excluding RHEL 7 on s390x, and on cent via `numactl-devel`.

Ubuntu playbook updated via #570.  Is there a schedule for playbook updates?  If so, the next update will add this for free once #570 is merged.

**Comment by sxa555** [comment]
Have re-run the playbook on the two machines fromt he original comment and both now have numactl available.

**Comment by karianna** [comment]
#570 has landed - last run failed - https://ansible.adoptopenjdk.net/#/jobs/88515/#followAnchor

**Comment by jdekonin** [comment]
It gets long past this change.  The failure is in "ant : Remove the older Ant package" action.  I opened #572 to address.
