### ISSUE TITLE
Bring AIX boxes on-line for build / test

### ISSUE THREAD

**Issue by tellison** [AdoptOpenJDK/openjdk-infrastructure#4]
The following new AIX build / test boxes are available to the project.  I have added the keybox public key to the list of authorized_keys.  Note that there are existing authorized keys that should be retained for the hoster's maintenance use.

power8-aix-openjdk1.osuosl.org - 140.211.9.10
power8-aix-openjdk2.osuosl.org - 140.211.9.12

Each system is 32GB memory, 5 vCPU, 1 CPU unit that can dynamically adapt to 10 CPU, and a minimal AIX 7.1 install.  The AIX 7.1.4.4 DVD1 still is "mounted".  The OS and related files are installed on filesystems allocated from rootvg, and /home is allocated from homevg.  Each volume group is 80GB and most of rootvg is unallocated with considerable room for expansion.

Both systems have been set up with larger queue depth for the hdisks, which improves performance a little.  One also can create a ramdisk.

You can customize the systems as you wish.

**Comment by bblondin** [comment]
@gdams xlc version 13.1.3 has been installed on both systems
/opt/IBM/xlc/13.1.3/bin/xlc -qversion

IBM XL C/C++ for AIX, V13.1.3 (5725-C72, 5765-J07)
Version: 13.01.0003.0000

**Comment by bblondin** [comment]
Both systems are now being monitored by Nagios
https://nagios.adoptopenjdk.net/nagios/cgi-bin/status.cgi?host=power8-aix-openjdk1.osuosl.org
https://nagios.adoptopenjdk.net/nagios/cgi-bin/status.cgi?host=power8-aix-openjdk2.osuosl.org

**Comment by tellison** [comment]
According to Jenkins, both AIX boxes' `date` is about 2hrs different to `ci.adoptopenjdk.net`

**Comment by bblondin** [comment]
- Configured time server for both AIX boxes
ntpdate -b pool.ntp.org

vi /etc/ntp.conf 
remove: broadcastclient
add: server 1.pool.ntp.org
server 2.pool.ntp.org
server 3.pool.ntp.org

stopsrc -s xntpd 
/usr/sbin/chrctcp -S -a xntpd

test:
ntpq -p

**Comment by bblondin** [comment]
The two AIX systems were not deployed the same...
- The partition sizes are small on build-osuosl-ppc64-aix-71-2 which appear to be the default. (/, /opt, /tmp) I have changed them to match those of build-osuosl-ppc64-aix-71-1
- The environment variable for JDK_BOOT_DIR was not set in Jenkins on build-osuosl-ppc64-aix-71-2
- updated ulimit to match 
build-osuosl-ppc64-aix-71-2 is now on-line

**Comment by tellison** [comment]
via Ansible? ;-)

We may have to return these machines and set-up new ones when we move to better hardware.

**Comment by bblondin** [comment]
is there anything else required on this? 
Other than the playbook which will be addressed in: 
https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/6
