### ISSUE TITLE
Provide read access to Jenkins build jobs

### ISSUE THREAD

**Issue by tellison** [AdoptOpenJDK/openjdk-infrastructure#40]
As [described over in the Node community](https://github.com/nodejs/build/issues/972), there is a Jenkins launch option that will let people see the jobs definition.

Looks like a good idea and something we should be doing in this project.

This issue covers amending the Jenkins launch script and selectively opening up our job definitions.

**Comment by gdams** [comment]
@gibfahn Is there any progress that has been made in the Node.js world with this? It would be good to wait and see if you have any issues using this over there before we implement it.

**Comment by gdams** [comment]
related to https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/27

**Comment by gibfahn** [comment]
No-one has gotten around to implementing this yet, but as it's off by default even if you run Jenkins with the flag, it shouldn't be too much of an issue to start testing.

If you restart Jenkins with that flag, you can make sure no-one can see any configs.

Then you just enable it for an individual person or group, see how it goes. It can be enabled on a per-job basis as well.

Assuming there are no secrets in the job configs you should be good (if secrets are `Password parameters` that should be fine anyway).

**Comment by gdams** [comment]
Perhaps we should test this here then and feedback to the nodejs community?

**Comment by gdams** [comment]
Okay so I have enabled this on our jenkins,

Sure enough you now can access https://ci.adoptopenjdk.net/job/openjdk8_build_x86-64_windows/configure without being logged in (you can edit all parameters etc but have no save button)

I will do a quick double check myself of all jobs to confirm that no secrets are now being exposed to the public

**Comment by karianna** [comment]
Cool, I wish Jenkins made all the fields RO as well but this is why sometimes we can't have nice things :-)
