### ISSUE TITLE
Add curl to all playbooks

### ISSUE THREAD

**Issue by smlambert** [AdoptOpenJDK/openjdk-infrastructure#404]
curl is present in https://github.com/AdoptOpenJDK/openjdk-infrastructure/tree/master/ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars:
Ubuntu.yml
SLES.yml
Redhat.yml
FreeBSD.yml

but not in:
OracleLinux.yml
CentOS.yml

Should also ensure its present in the non-Linux playbooks.

**Comment by jdekonin** [comment]
Is there a specific version that is required based on options needed?

fyi @llxia

**Comment by smlambert** [comment]
curl (version 7.20.0 or later) to get the option -J/--remote-header-name

**Comment by vsebe** [comment]
It is not required on Windows - using the cygwin package: curl 7.59.0-1

**Comment by sxa555** [comment]
@smlambert For reference, what is that option needed for?

**Comment by smlambert** [comment]
We wish to download binaries using the api, which is not a direct link to a tgz file, but redirects to one, the -J option is needed.

**Comment by sxa555** [comment]
Never noticed that wasn't default behaviour - good to know - I tend to use `wget` more than `curl` myself  :-)

**Comment by smlambert** [comment]
we were using wget too, but since we had several people request we change to use curl, and since wget is not available on z/os and we decided to switch to it (and trying to eliminate our use of both, to decrease the number of prereqs needed)

**Comment by jdekonin** [comment]
Comment add to #554 for macos once that playbook is created.  The only remaining one not already mentioned is for aix, which is installed as part of coreutils v7.60.  I believe this is complete and can be closed.
