### ISSUE TITLE
Which distribution should we use for creation of docker images?

### ISSUE THREAD

**Issue by sxa555** [AdoptOpenJDK/openjdk-infrastructure#409]
Currently using Ubuntu, but we're moving to RHEL for build systems. Should we use the RHEL build boxes for docker creation to? If so we'll need to acquire a suitably up-to-date docker (`docker-ce` most likely) on each of our build systems.

Ref: https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/256

FYI @dinogun

**Comment by gdams** [comment]
this fits in with the recent discussions of creating a new `docker` infra group for machines that just have docker and some other minimal dependencies on.

**Comment by dinogun** [comment]
I'd prefer to have Ubuntu for the docker infra group. Redhat is not one of the supported OS'es for [docker-ce](https://docs.docker.com/install/)

**Comment by sxa555** [comment]
@dinogun True (although it does work...) It is for CentOS though, so we could move to CentOS for that (So x64 and ppc64le archs) just not s390x

**Comment by cwillhelm** [comment]
From my understanding, it is best to create Docker images based on the host OS they are running on. For example, you would create Ubuntu Docker images on Ubuntu, CentOS images on CENT, and SLES images on SLES. This ensures better compatibility, and reduces the need for adding additional packages to the images, which reduces the overall size of the image. The smaller the image, the faster the bootup time. It's also quicker when pulling pre-built images from a (private) Docker Hub.

Just offering my 2cents :)

**Comment by sxa555** [comment]
@cwillhelm What's the logic behind your assertion that using the same as the host OS "reduces the need for adding additional packages to the images"?

**Comment by cwillhelm** [comment]
Because Docker uses a layered file-system, images that share a common base will be more space efficient when sharing the same host.

**Comment by sxa555** [comment]
I didn't think it would share with the host OS though, only a base docker image - so should not be sharing with the host.

**Comment by cwillhelm** [comment]
Ah, I misread if you were referring to the base OS _for the container_ versus which os _to host the containers on_.

**Comment by sxa555** [comment]
Correct :-)

**Comment by sxa555** [comment]
For reference: zLInux build machines and a couple of the SoftLayer test machines are RHEL, others are CentOS which would take `docker-ce`

**Comment by sxa555** [comment]
Going to close this as we're using Ubuntu machines for this and there's no driving reason to switch it since we're not short of machines and use Ubuntu for more other things now

**Comment by sxa555** [comment]
[One of the CentOS 7.4 machines](https://ci.adoptopenjdk.net/computer/build-osuosl-centos74-ppc64le-1/) were tagged with docker which means that we were getting issues as per https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1222 ... The label has ben removed from that machine and so the subsequent docker multiarch builds on ppc64le will be running on the Ubnbut machine.
