### ISSUE TITLE
Request for additional git repository for microbenchmark code contribution

### ISSUE THREAD

**Issue by smlambert** [AdoptOpenJDK/openjdk-infrastructure#412]
Requesting the creation of a git repo within the AdoptOpenJDK organization named 'bumblebench' to house a microbenchmark framework, that can be used to easily write performance microbenchmarks for JVMs.  (suggesting: https://github.com/AdoptOpenJDK/bumblebench)

BumbleBench is a microbenchmark framework intended to make it as easy as possible to avoid common pitfalls when microbenchmarking OpenJDK implementations. It is intended to make sure that test runs spend most of their time running the desired piece of code compiled at the highest possible level of quality. 

We have several example microbenchmarks that we wish to run against builds at AdoptOpenJDK, as well as a plan to work on documentation to encourage the community to write new benchmarks to help measure performance in various scenarios.

**Comment by karianna** [comment]
Hi @smlambert Not opposed to this in prinicple but I'm curious as to how this compares to [JMH](http://openjdk.java.net/projects/code-tools/jmh/) which is a bit of a defacto standard in this space.

**Comment by smlambert** [comment]
Both jmh and bumblebench are very useful tools that I would like to start incorporating into an overall performance testing 'strategy'.  There are existing benchmarks written for both that we should plan to include in extended testing, or at least offer easy access and guidance for the community.

One of the differentiating features of bumblebench is that it can vary the iteration count of the benchmark's main loop in order to determine the highest iteration count that can be completed within a given target duration.   As in, it tunes itself based on the environment it is running in to make sure the piece of code under scrutiny is exercised most.

**Comment by karianna** [comment]
OK it's been created and you should have clone access, LMK if you want write access for an initial push
