### ISSUE TITLE
Windows playbook only works if machine is in inventory

### ISSUE THREAD

**Issue by jdekonin** [AdoptOpenJDK/openjdk-infrastructure#423]
This is not productive if we have developers wanting to run in their `local` machines or even through an alternate AWX install.

The same applies for the Unix playbooks.

**Comment by sxa555** [comment]
Related: https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/532

**Comment by sxa555** [comment]
@jdekonin Is this still required and if so do you have an idea of what might be required (Except for possibly having `localhost` as an option in the `hosts:` line in the top level playbook file? I don't believe it's possible to run ansible locally on a Windows machine.

**Comment by jdekonin** [comment]
I wanted to setup a machine via ansible tower but I had to either hack the host line in the main.yml or add the machine to an inventory.  Seems like an unwanted and unnecessary step if the machine isn't going into a build system where the inventory file is required.

How does the automated checks work?  Or do the automated checks work on windows yet?  For that matter the same issue would exist on linux.  How does the linux automated checks work?  Are those machine(s) in the inventory list?

**Comment by sxa555** [comment]
@jdekonin Ref: https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/master/ansible/pbTestScripts/testScript.sh
At the moment it runs a sed against the hosts line to change it to `all`

**Comment by jdekonin** [comment]
That seems like an unneeded step.  One that I don't want to embed in AWX automation as its add complexity when its not required.  Why not just have the main.yml default to `all`?

**Comment by Willsparker** [comment]
@jdekonin Can this be closed due to https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/1017 ?

**Comment by jdekonin** [comment]
That only covers unix, I had wanted that change for windows too but I guess that didn't get done so I just opened a PR with the change.

**Comment by sxa555** [comment]
Windows fix is in, therefore closing.
