### ISSUE TITLE
Remove tightvncserver from zLinux JCK machines

### ISSUE THREAD

**Issue by sxa555** [AdoptOpenJDK/openjdk-infrastructure#424]
tightvncserver has a tendancy to segfault on startup on the zLinux machines we have. The machines also have `vnc4server` which starts up without problems. The default `/usr/bin/vncserver` is pointing to `/etc/alternatives/vncserver` which points to `/usr/bin/tightvncerver` so by default running `vncserver` causes a crash. We could use `update-alternatives` but removing the tightvncserver package and leaving vnc4server as the default seems like a better approach

**Comment by karianna** [comment]
Tagging with ansible as well since I assume it'll need to get removed from there as well.
