### ISSUE TITLE
Request for access to Packet ARM systems

### ISSUE THREAD

**Issue by JamesKingdon** [AdoptOpenJDK/openjdk-infrastructure#43]
I'm working on getting the OpenJDK/OpenJ9 builds working on ARM. Would it be possible to get access to the ARM build systems for some basic toe-in-the-water evaluations of my initial builds?

**Comment by karianna** [comment]
@gdams approved.

**Comment by gdams** [comment]
@JamesKingdon do you want to DM me your public key on Slack and i'll get you added :)

**Comment by karianna** [comment]
@JamesKingdon Is this resolved now?

**Comment by gdams** [comment]
Keys are on the machine. We leave these issues open until the keys are revoked

**Comment by JamesKingdon** [comment]
Hi @karianna , my login is working and has proven very useful. If I could keep it for a while it would be great.
If/when you revoke my key, note that I created user jkingdon with /home/jkingdon on the machine to keep my stuff out of everyone's way, and that will need deleting. (I can do the cleanup if you give me notice)

**Comment by karianna** [comment]
@JamesKingdon Cool, we do prefer to revoke keys once the main work is done. Do you have a rough time estimate?

**Comment by JamesKingdon** [comment]
I have to confess that right now I don't have specific plans beyond tinkering and exploring. I was going to check the basic processor detection of the OpenJ9 build and look for any emulated instruction performance issues, but that went out of the window when I realised Thunder can't run 32 bit code.
Perhaps it makes the most sense if I open another request for access to one of the Huawei boxes.

**Comment by karianna** [comment]
@JamesKingdon If the box you're exploring on is completely spare I'm OK with it...

**Comment by JamesKingdon** [comment]
Ok, thanks, that's great. I keep an eye on it's load and make sure I don't interfere with it's real work. Fortunately I think that usually happens when I'm sleeping :)

**Comment by karianna** [comment]
@JamesKingdon I'm probably more concerned if you make a change and that breaks an existing build of a hotspot build, does that make sense?

**Comment by JamesKingdon** [comment]
Yes, I was worried about that too, so I do all my testing inside a Docker container now.

**Comment by gdams** [comment]
ping @JamesKingdon is this still required?

**Comment by JamesKingdon** [comment]
Hi George, many thanks for the access, it was really interesting. Feel free to drop me out now, I've signed up for my own account at Packet, so anything I need in the short/medium term I can do under that.

Thanks again!

**Comment by gdams** [comment]
key has now been revoked
