### ISSUE TITLE
Add ramdisk to speed up AIX builds

### ISSUE THREAD

**Issue by gdams** [AdoptOpenJDK/openjdk-infrastructure#44]
Investigate using ramdisk to speed up AIX builds

**Comment by gdams** [comment]
I have run the following commands on build-osuosl-ppc64-aix-71-1.

RAMDISK=`mkramdisk 10G`
mkdir /ramdisk0 >/dev/null 2>&1
DEVICE="/dev/ramdisk`echo $RAMDISK | awk -F'ramdisk' '{print $2}'`"
echo "yes" | mkfs -V jfs2 $DEVICE
mount -V jfs2 -o log=NULL $DEVICE /ramdisk0
mkdir /ramdisk0/build
chown jenkins /ramdisk0/build

I will no look at changing the workspace to be `/ramdisk0/build`

It is worth noting that ramdisk is not persistent so we would need a startup script to run the above command each time the machine reboots

**Comment by gdams** [comment]
https://ci.adoptopenjdk.net/job/openjdk8_build_ppc64_aix/146/console is running in a ramdisk workspace. It is worth noting that it is still requiring tooling and a boot jdk that isn't currently on ramdisk so that will slow things down but it should help with the git

**Comment by gdams** [comment]
git clone performance is significantly faster:

```
real    26m17.505s
user    0m10.658s
sys    0m4.540s
``` 
becomes
```
real    0m32.091s
user    0m6.227s
sys    0m2.359s
```

**Comment by gdams** [comment]
build has dropped down to 47 minutes from 1 hour 30 minutes!

**Comment by gdams** [comment]
applying same config to build-osuosl-ppc64-aix-71-2

**Comment by gdams** [comment]
@bblondin could you look at adding a the above script to run on startup for both machines?

**Comment by bblondin** [comment]
vi /etc/rc.d/rc2.d/Sramdisk
```
#!/bin/bash
# Enable RAMDISK
RAMDISK=`mkramdisk 10G`
mkdir /ramdisk0 >/dev/null 2>&1
DEVICE="/dev/ramdisk`echo $RAMDISK | awk -F'ramdisk' '{print $2}'`"
echo "yes" | mkfs -V jfs2 $DEVICE >/dev/null 2>&1
mount -V jfs2 -o log=NULL $DEVICE /ramdisk0 >/dev/null 2>&1
mkdir -p /ramdisk0/build
chown jenkins /ramdisk0/build
```
chmod 555 /etc/rc.d/rc2.d/Sramdisk

**Comment by bblondin** [comment]
Applied to both hosts
