### ISSUE TITLE
Please add me to this organisation/team so that I can start contributing

### ISSUE THREAD

**Issue by ali-ince** [AdoptOpenJDK/openjdk-infrastructure#444]
I've worked on getting windows-x86 builds back on to track and would like to apply the fixes.

**Comment by karianna** [comment]
@ali-ince - Invite in your inbox (or in your GitHub UI).  Once you accept that let me know and I'll get @gdams to give you and hte other new infra folks the guided tour.

**Comment by ali-ince** [comment]
@karianna I've accepted the invitation.

**Comment by sxa555** [comment]
Hi @ali-ince :-) For reference purposes:
https://ci.adoptopenjdk.net/view/work%20in%20progress/job/openjdk8_build_x86-32_windows is the jenkins job that covers HotSpot/Win32.
https://github.com/AdoptOpenJDK/openjdk-build/issues/384 is the relevant issue

**Comment by karianna** [comment]
https://ci.adoptopenjdk.net/view/work%20in%20progress/job/openjdk8_build_x86-32_windows/10/consoleFull gives you the latest failure with reference to the host it was trying to build on.  @sxa555 or @gdams can hopefully give you access to that for any manual grep code install changes you need to make.

@sxa555 Is that host dedicated to win32 builds?  I'd like to make sure that if we downgrade grep that we then don't disqualify that machine from 64 builds.  That said we could make this a dedicatd 32 build machine as we have plenty of azure capacity for 64 bit...

**Comment by sxa555** [comment]
No it's not dedicated to 32-bit but it's the only machine which is set up with the appropriate pieces to build. If we need to start downgrading stuff I'd definitely prefer to use a separate box (or dedicated the current one) at least while we experiment.

**Comment by ali-ince** [comment]
Another approach would be having openjdk8 builds to run always on the node `build-azure-win2008r2-x64-1` (which currently builds openjdk8_build_x86-64_windows)? The only thing we need to do then will be to split freetype binaries into two sets (x86 and x86-64) and change the build configuration accordingly.

Does this make sense @sxa555?

**Comment by sxa555** [comment]
@ali-ince Not quite sure what you're suggesting with "having openjdk8 builds to run always on build-azure-win2008r2-x64-1" - why would we want to lock all windows openjdk8 build onto one machine?

**Comment by ali-ince** [comment]
it's because it already successfully builds `openjdk8_build_x86-64_windows` which proves that machine has the version of `grep` that works. 

If it's our intention to have all build configurations to be successfully built on all available hosts, then you can ignore my suggestion. But since the host `build-azure-win2008r2-x64-1` currently builds only `openjdk8_build_x86-64_windows` and we can get it to also build `openjdk8_build_x86-32_windows` with no downgrades and small changes - that seemed viable to me.

**Comment by sxa555** [comment]
Ah - the critical piece of information is that `openjdk8_build_x86-64_windows` is already locked onto `build-azure-win2008r2-x64-1`. Hadn't realised that. Running https://ci.adoptopenjdk.net/job/openjdk8_build_x86-64_windows/382/console to verify whether the jdk8/win64 builds work on other machines (`build-softlayer-win2012r2-x64-2`  in this case)

**Comment by ali-ince** [comment]
That would fail with the same error at the same location - and it did.

My suggestion towards the fix of the problem would be;

1. Make the small changes on `build-azure-win2008r2-x64-1` so that `openjdk8_build_x86-32_windows` and `openjdk8_build_x86-64_windows` can start building on that specific host.
2. Try downgrade of `grep` to `2.27-2` on one of the other windows hosts to verify other dependent builds are not affected - and deploy the solution across all windows hosts.

**Comment by ali-ince** [comment]
Is it ok if I request access to secrets repo (to gain access to windows hosts) on this issue? If not, I'll create another issue.

Attached is my public gpg key.

[ali-ince-public.txt](https://github.com/AdoptOpenJDK/openjdk-infrastructure/files/2319315/ali-ince-public.txt)

**Comment by gdams** [comment]
added

**Comment by karianna** [comment]
@ali-ince - Let us know if you need any further details to get onto that box.
