### ISSUE TITLE
Abstract out a lot of the distro specific checks from the Common directory

### ISSUE THREAD

**Issue by sxa** [AdoptOpenJDK/openjdk-infrastructure#452]

**Comment by Willsparker** [comment]
@sxa Do you mean just removing the lines such as 
https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/b107e720cbf20e860c9a5f1e07db582a2e25215f/ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/RedHat.yml#L81
or something else?

**Comment by sxa** [comment]
I think if it's needed for some reason it's ok in the `RedHat.yml` for example, but if there are any in the main part of the common role then they shold probably be moved to distro specific files if possible

**Comment by Willsparker** [comment]
A good example of why descriptions are necessary then ;-) 
Okay, thanks for clarification :+1:

**Comment by Willsparker** [comment]
I've had a look, it looks like the only thing that _could_ be put into distributions would be the macOS hostname stuff, however, I sort of assume that this is required for the `update /etc/hosts` tasks below it.
I am going to remove the unnecessary distro checks that are already in the distro specific files however, just to cleanup.
