### ISSUE TITLE
ansible: fatal: [test-marist-ubuntu1604-s390x-1]: UNREACHABLE!

### ISSUE THREAD

**Issue by sxa555** [AdoptOpenJDK/openjdk-infrastructure#455]

**Comment by sxa555** [comment]
Looks ok at the moment, and some other Marist machines have been temperamental today, therefore closing

**Comment by karianna** [comment]
@sxa555 This is still open?

**Comment by sxa555** [comment]
Yes we're still getting a lot of intermittent failures. Today [build-marist-ubuntu1604-s390x-3](https://ci.adoptopenjdk.net/computer/build-marist-ubuntu1604-s390x-3/) and [test-marist-ubuntu1604-s390x-1](https://ci.adoptopenjdk.net/computer/test-marist-ubuntu1604-s390x-1/) are getting `Conection reset by peer` and [build-marist-rhel74-s390x-2](https://ci.adoptopenjdk.net/computer/build-marist-rhel74-s390x-2/)  is giving an unreachable error

**Comment by sxa555** [comment]
Managing to connect to the machine today from ansible but it's hitting issues with some of the kernel header packages - reporting disk full but it's actually running out of inodes. Clearing out old kernel packages as per https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/482 but also purging old `linux-headers-4.4.0-xxx` and `linux-headers-4.4.0-xxx-generic` packages via `apt autoremove`

**Comment by sxa555** [comment]
Playbook execution complete. Closing
