### ISSUE TITLE
ansible: nagios symlink issue on multiple machines

### ISSUE THREAD

**Issue by sxa555** [AdoptOpenJDK/openjdk-infrastructure#465]
```
TASK [Nagios_Plugins : Create symlink to plugins] ******************************
15:12:54
ok: [build-osuosl-centos74-ppc64le-2]
fatal: [build-osuosl-centos74-ppc64le-1]: FAILED! => {"changed": false, "failed": true, "gid": 0, "group": "root", "mode": "0755", "msg": "refusing to convert between directory and link for /usr/local/nagios/libexec", "owner": "root", "path": "/usr/local/nagios/libexec", "secontext": "unconfined_u:object_r:usr_t:s0", "size": 4096, "state": "directory", "uid": 0}
```
Ref: https://ci.adoptopenjdk.net/computer/build-osuosl-centos74-ppc64le-1
The new "twin" machine being set up under https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/408 does not have this issue

**Comment by sxa555** [comment]
Certainly seems to be the case ... the error message is correct:
```
[root@build-osuosl-centos74-ppc64le-1 nagios]# ls -lart
total 20
drwxr-xr-x.  2 root   root 4096 Apr 26  2017 include
drwxr-xr-x.  5 nagios root 4096 Apr 26  2017 .
drwxr-xr-x.  3 root   root 4096 Apr 26  2017 share
drwxr-xr-x.  2 root   root 4096 May 30  2017 libexec
drwxr-xr-x. 15 root   root 4096 Aug  2 16:21 ..
[root@build-osuosl-centos74-ppc64le-1 nagios]# 
```
The playbook is attempting to create the link from `/usr/local/nagios/libexec` to `/usr/lib64/nagios/plugins` after creating `/usr/local/nagios` in the previous step.

**Comment by sxa555** [comment]
This affects build-digitalocean-centos69-x64-1, build-joyent-centos69-x64-1 and build-osuosl-centos74-ppc64le-1

**Comment by sxa555** [comment]
@bblondin Do you know any of the history to this i.e. what the safest course of action is to undo how it was installed so that the current playbooks can run successfully.

**Comment by sxa555** [comment]
@CJKwork We don't seem to have much history for this one but would be a good one to investigate and sort out

**Comment by CJKwork** [comment]
Hmm, I've found this article on superuser which discusses the same error message:
https://superuser.com/questions/1063994/unable-to-form-a-link-of-a-file-which-is-in-sites-available-to-a-directory-sites

This suggests that:

Set force=true to create the symlink.

    force the creation of the symlinks in two cases:

        the source file does not exist (but will appear later);

        the destination exists and is a file (so, we need to unlink the "path" file and create symlink to the "src" file in place in it).

So it could be worth a try.

**Comment by sxa555** [comment]
Have removed the following packages, and the (empty) `/usr/lib64/nagios//plugins/eventlhandlers` along with the parent `plugins` directory, and now rerunning the playbook
```
nagios-plugins-mailq-2.2.1
nagios-plugins-snmp-2.2.1
nagios-plugins-ping-2.2.1
nagios-plugins-mysql-2.2.1
nagios-plugins-mrtg-2.2.1
nagios-plugins-procs-2.2.1
nagios-plugins-file_age-2.2.1
nagios-plugins-game-2.2.1
nagios-plugins-users-2.2.1
nagios-plugins-dns-2.2.1
nagios-plugins-http-2.2.1
nagios-plugins-dig-2.2.1
nagios-plugins-perl-2.2.1
nagios-plugins-breeze-2.2.1
nagios-plugins-wave-2.2.1
nagios-plugins-swap-2.2.1
nagios-plugins-fping-2.2.1
nagios-plugins-ssh-2.2.1
nagios-plugins-ups-2.2.1
nagios-plugins-oracle-2.2.1
nagios-plugins-ntp-perl-2.2.1
nagios-plugins-icmp-2.2.1
nagios-plugins-nagios-2.2.1
nagios-plugins-sensors-2.2.1
nagios-plugins-all-2.2.1
nagios-plugins-rpc-2.2.1
nagios-plugins-ircd-2.2.1
nagios-plugins-time-2.2.1
nagios-plugins-ldap-2.2.1
nagios-plugins-nt-2.2.1
nagios-plugins-ntp-2.2.1
nagios-plugins-pgsql-2.2.1
nagios-plugins-disk-2.2.1
nagios-plugins-log-2.2.1
nagios-plugins-smtp-2.2.1
nagios-plugins-cluster-2.2.1
nagios-plugins-overcr-2.2.1
nagios-plugins-flexlm-2.2.1
nagios-plugins-nwstat-2.2.1
nagios-plugins-hpjd-2.2.1
nagios-plugins-dhcp-2.2.1
nagios-plugins-tcp-2.2.1
nagios-plugins-ide_smart-2.2.1
nagios-plugins-2.2.1
nagios-plugins-disk_smb-2.2.1
nagios-plugins-dummy-2.2.1
nagios-plugins-real-2.2.1
nagios-plugins-load-2.2.1
nagios-plugins-mrtgtraf-2.2.1
nagios-plugins-by_ssh-2.2.1
```

**Comment by sxa555** [comment]
Playbook execution fell over due to the issue fixed by  https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/576

**Comment by sxa555** [comment]
This needs verifying again as hopefully it is no longer a problem

**Comment by sxa555** [comment]
Does not appear to be an issue any more - closing
