### ISSUE TITLE
RHEL7 ppc64le NVidia_Cuda_Toolkit DKMS download failure

### ISSUE THREAD

**Issue by sej-jackson** [AdoptOpenJDK/openjdk-infrastructure#467]
```
TASK [NVidia_Cuda_Toolkit : Download DKMS - RHEL 7 PPC64LE] ********************
fatal: [rtsvt-rhel74-ppc64le-1.fyre.ibm.com]: FAILED! => {"changed": false, "dest": "/tmp/dkms.noarch.rpm", "msg": "Request failed", "response": "HTTP Error 404: Not Found", "state": "absent", "status_code": 404, "url": "https://dl.fedoraproject.org/pub/epel/7/ppc64le/Packages/d/dkms-2.4.0-1.20170926git959bd74.el7.noarch.rpm"}
```
Checked `https://dl.fedoraproject.org/pub/epel/7/ppc64le/Packages/d/` to find that `dkms-2.6.1-1.el7.noarch.rpm` exists, but not `dkms-2.4.0-1.20170926git959bd74.el7.noarch.rpm`

**Comment by sxa555** [comment]
Relevant line: https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/master/ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/NVidia_Cuda_Toolkit/tasks/main.yml#L40

**Comment by sxa555** [comment]
(Also, for reference, this PR is trying to add CUDA to RHEL6/x86-64 systems as well: https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/362)

**Comment by keithc-ca** [comment]
I just tested this on a new system:
```
# cat redhat-release 
Red Hat Enterprise Linux Server release 6.10 (Santiago)
```
These two commands install the CUDA toolkit (`--override` can probably be omitted if gcc is installed first):
```
# wget https://developer.nvidia.com/compute/cuda/9.2/Prod2/local_installers/cuda_9.2.148_396.37_linux
# bash cuda_9.2.148_396.37_linux --silent --toolkit --override
```

**Comment by sxa555** [comment]
In light of the above I'm happy to remove the DKMS package from the playbooks unless we find a subsequent reason for reinstating them.

**Comment by sxa555** [comment]
@CJKwork One for you :-)

**Comment by CJKwork** [comment]
Did some testing, and in playbook 
https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/master/ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/NVidia_Cuda_Toolkit/tasks/main.ym

I removed the install DKMS steps, and updated the Install NVidia CUDA toolkit step to install cuda-toolkit-9-0

Tested out ok on a fyre image.
Pull request created.
