### ISSUE TITLE
Remove retired folks from the infra team(s)

### ISSUE THREAD

**Issue by karianna** [AdoptOpenJDK/openjdk-infrastructure#469]
- [ ]  @bblondin - Brad Blondin - can you confirm you've left the project?
~~@geraintwjones - Geraint Jones - can you confirm you've left the project?~~
~~@pnstanton - Peter Stanton - can you confirm you've left the project?~~

**Comment by geraintwjones** [comment]
While I have changed departments, and am not currently actively contributing to Adopt, I would like to remain a member so that I can contribute if necessary.

**Comment by sxa555** [comment]
Brand has confirmed that he has left the project, therefore can be removed. Will aim to action this in the next iteration

**Comment by sxa555** [comment]
Brad is no longer be in keybox as far as I can tell - closing.
