### ISSUE TITLE
ansible: cmake not installed on several machines

### ISSUE THREAD

**Issue by sxa555** [AdoptOpenJDK/openjdk-infrastructure#483]
Despite multiple playbook runs the following machines are still showing warnings that cmake isn't installed (but the playbooks appear to make no attempt to install it). How critical is it?

[build-marist-rhel74-s390x-1](https://ci.adoptopenjdk.net/computer/build-marist-rhel74-s390x-1)
[build-linaro-centos74-armv8-1](https://ci.adoptopenjdk.net/computer/build-linaro-centos74-armv8-1)
[build-packet-centos74-arm8-1](https://ci.adoptopenjdk.net/computer/build-packet-centos74-arm8-1)
[build-packet-ubuntu1604-armv8-2](https://ci.adoptopenjdk.net/computer/build-packet-ubuntu1604-armv8-2)

**Comment by karianna** [comment]
I think cmake is required for the Eclipse OpenJ9 builds no?

**Comment by jdekonin** [comment]
There is a cmake role, but not specifically for 390 or arm8 it would appear.
https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/master/ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/cmake/tasks/main.yml

OpenJ9 requirement for cmake is v3.4 or newer, and the playbook is using for 3.7.2 from source.  It will be an OpenJ9 requirement eventually, but its not required yet.

**Comment by sxa555** [comment]
Related request: https://github.com/eclipse/openj9/issues/90

**Comment by sxa555** [comment]
None of the machines referenced above are used for build, therefore this is not a problem. Closing
