### ISSUE TITLE
test-softlayer-rhel69-x64-1 has fallen off the network

### ISSUE THREAD

**Issue by sxa555** [AdoptOpenJDK/openjdk-infrastructure#484]
@tellison Are you able to check on the state of this machine and see if it can be brought back to life?
Should be 169.55.150.147

**Comment by tellison** [comment]
This machine was recently subject to a planned maintenance event.  Within the console it was marked as "Powered Off", and attempts to start it show it powered on but failing to connect to the network.

I have raised a Softlayer ticket (number 65157943) to address this connectivity problem.

**Comment by sxa555** [comment]
@smlambert FYI

**Comment by tellison** [comment]
The machine is back on-line after the following kernels were removed from the server. These kernels were preventing the server from booting properly.

kernel-2.6.32-754.3.5.el6.x86_64
kernel-2.6.32-754.2.1.el6.x86_64 

You can continue to yum update the server but you will want to exclude the current kernel updates for now. You can use the following command:

`# yum update --exclude=kernel*`

Please check it is working as expected for you, and if you are happy you can close the issue.

**Comment by sxa555** [comment]
Will we get any notification when it is safe to re-enable them? I would imagine many of the kernel updates will be for security reasons so I'm nervous about having them disabled.

**Comment by sxa555** [comment]
Have added that exclude to the crontab for now

**Comment by sxa555** [comment]
Will leave this issue open for now until we can confirm that it is safe to re-enable

**Comment by sxa555** [comment]
`kernel-2.6.32-754.3.5.el6.x86_64` has been reinstalled overnight by the crontab. If I try to remove it I get the following failure - can we get clarification on what commands the softlayer team ran to safely remove the later kernel packages, since the problem is likely to recur as soon as the machine is rebooted?
```
[root@test-softlayer-rhel69-x64-1 ~]# rpm -e kernel-firmware-2.6.32-754.3.5.el6.noarch kernel-headers-2.6.32-754.3.5.el6.x86_64 kernel-2.6.32-754.3.5.el6.x86_64
error: Failed dependencies:
	kernel-headers >= 2.6.27-0.144.rc0.git2.fc10 is needed by (installed) libdrm-devel-2.4.65-2.el6.x86_64
	kernel-headers >= 2.2.1 is needed by (installed) compat-glibc-headers-1:2.5-46.2.x86_64
	kernel-headers is needed by (installed) glibc-headers-2.12-1.212.el6.x86_64
	kernel-headers >= 2.2.1 is needed by (installed) glibc-headers-2.12-1.212.el6.x86_64
[root@test-softlayer-rhel69-x64-1 ~]# 
```
I've edited `/boot/grub/grub.cfg` to set `default=1` which should select the older kernel by default when it is rebooted. Hopefully that will be enough to protect us pending an official solution.

**Comment by sxa555** [comment]
Machine has rebooted and seems stable for now. Immediate problem resolved. Removing from this milestone.

**Comment by sxa555** [comment]
Seems alive - closing
