### ISSUE TITLE
Make gcc 7.5.0 available on arm32 machines

### ISSUE THREAD

**Issue by sxa** [AdoptOpenJDK/openjdk-infrastructure#487]
Currently fails to build as it can't find sys/cdefs.h on the arm32 distributions (on raspbian or Ubuntu). Possibly expecting it to be in the location it's supplied in on  the RHEL machines. I had a first attempt at overriding it with the configure parameters but that didn't succeed. Breaking this out to a separate work item so it doesn't impact closing issues related to the ansible scripts on [Milestone A](https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues?q=is%3Aopen+is%3Aissue+milestone%3A%222018+September+A%22)

**Comment by sxa555** [comment]
Probably worth trying this with the new 7.5.0 release on Linux/arm32 (armv7l)

**Comment by Haroon-Khel** [comment]
As anticipated, the `sys/cdefs.h` occurs. Will investigate

`/usr/include/features.h:367:12: fatal error: sys/cdefs.h: No such file or directory`

**Comment by sxa555** [comment]
Can you try adding `--includedir=/usr/include/arm-linux-gnueabihf` to the `./configure` parameters: https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/438#issuecomment-414434025`

**Comment by sxa555** [comment]
Can you try adding `--includedir=/usr/include/arm-linux-gnueabihf` to the `./configure` parameters: https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/438#issuecomment-414434025`

**Comment by Haroon-Khel** [comment]
@sxa That didn't work either. I tired something similar by including that directory using 
```
export CFLAGS=-I/usr/include/arm-linux-gnueabihf
export CXXFLAGS=-I/usr/include/arm-linux-gnueabihf 
```
but this gave the following error
`/usr/include/arm-linux-gnueabihf/gnu/stubs.h:7:11: fatal error: gnu/stubs-soft.h: No such file or directory`

Another proposed solution is to install the package `g++-multilib`, though I cannot find this in the apt repositories

**Comment by sxa** [comment]
`-mfloat-hard` on configure resolves the above issue and is the default that we use so shoudl be ok. I'll get tit built on the Ubuntu machines and make it live and enable the installation of it in the playbooks

**Comment by sxa** [comment]
Thought I'd closed this. Deployed and working and also enabled for JDK in https://github.com/AdoptOpenJDK/openjdk-build/pull/1968 to fix support issue 33
