### ISSUE TITLE
build-osuosl-centos74-ppc64le-2 does not have a JDK9_BOOT_DIR

### ISSUE THREAD

**Issue by johnoliver** [AdoptOpenJDK/openjdk-infrastructure#488]
`build-osuosl-centos74-ppc64le-2` defines `JDK9_BOOT_DIR=/usr/lib/jvm/jdk-9+181`

However building produces:

```
checking for version string... 10.0.2-adoptopenjdk+13
configure: Found potential Boot JDK using configure arguments
configure: Potential Boot JDK found at /usr/lib/jvm/jdk-9+181 did not contain bin/java; ignoring
configure: error: The path given by --with-boot-jdk does not contain a valid Boot JDK
configure exiting with result code 1
```

**Comment by sxa555** [comment]
That is a new machine being set up under #408 directly from the playbooks and the machine definition was copied from `-1` I think.

**Comment by sxa555** [comment]
Looks like the definition is imcompatible with what the playbook has installed on there (or more likely it's pulling "lates" which is in a differnet directory. I have adjusted the machine definitions in jenkins to point to `/usr/lib/jvm/jdk-9.0.4+11` which is where JDK9 is installed on that machine. Hopefully that will resolve this issue.
