### ISSUE TITLE
New OpenJ9 requirement: protobuf and openssl

### ISSUE THREAD

**Issue by jdekonin** [AdoptOpenJDK/openjdk-infrastructure#493]
This is specific to feature work surrounding eclipse/openj9#2726

@mpirvu @harryyu1994, can you please advise as to which version of protobuf (3.5.1) and openssl OpenJ9 requires?  What platform(s) do these packages need to be rolled out too?

**Comment by jdekonin** [comment]
fyi @vsebe

**Comment by vsebe** [comment]
@mpirvu 
What platforms?
What protobuf package - see https://github.com/protocolbuffers/protobuf/releases/tag/v3.5.1?

**Comment by mpirvu** [comment]
Forgot to mention: we need the cpp version protobuf-cpp-3.5.1.zip

**Comment by sxa555** [comment]
@mpirvu My understanding from the changes going into OpenJ9 is that the build would be downloading an appropriate version of OpenSSL itself. Has that changed since Monday?

**Comment by mpirvu** [comment]
For the time being all our testing has been done on LinuxAMD64. The vast majority of the code to be contributed is platform independent, so in theory with little work this could be extended to other platforms where protobuf is available/compilable. However, we decided to improve the LinuxAMD64 solution as much as possible before moving to other platforms.

For OpenSSL it is the same story as protobuf: building the JITaaS project needs the header files for OpenSSL. Running/testing it needs the OpenSSL shared library. If the test infrastructure can automatically download a development version or OpenSSL (that includes headers), then build JITaaS project and then run the tests, it's perfectly fine with me.

**Comment by jdekonin** [comment]
As small as the openssl package might be, I don't think we want the same package downloaded and compiled every time JITaaS is compiled and tested.  Unless the version of openssl is going to be changing frequently?

@vsebe has taken over what I started and has been working on something to review with you @mpirvu

**Comment by sxa555** [comment]
Looks like `automake` is a prereq for building `protobuf` from source so that will be needed as a prereq too

**Comment by sxa555** [comment]
protobuf 3.5.1 doesn't seem happy when used with the autoconf 2.69 supplied with RHEL6:
```
+ autoreconf -f -i -Wall,no-obsolete
configure.ac:30: error: possibly undefined macro: AC_PROG_LIBTOOL
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /usr/bin/autoconf failed with exit status: 1
```
Has anyone following this issue built it from source?

**Comment by vsebe** [comment]
@sxa555 - I had no issues on the OpenJ9 machines. I set an Ubuntu 16, a CentOS 6 and a RHEL6 for JIT testing. 
See https://github.com/vsebe/openjdk-infrastructure/commit/1155ff0d974b1cb1f98dc16d73a4f114a9c14248

**Comment by sxa555** [comment]
Ah ok thanks - didn't know you were already working on the playbook modifications for this

**Comment by vsebe** [comment]
I have in work one for opnessl too. 
Waiting for testing to validate the environment.

**Comment by harryyu1994** [comment]
The build seems to have worked. However, JITaaS testing has a different setup than the normal OpenJ9 testing. Opening an issue for that now.

**Comment by vsebe** [comment]
The OpenJ9 xlinux machines are updated.

**Comment by sxa555** [comment]
I think we're done with this now that the PRs are in (pending re-running the playbooks) therefore closing. If anyone disagrees please reopen :-)
