### ISSUE TITLE
build-osuosl-ppc64-aix-71-2 probably out of space on /ramdisk0

### ISSUE THREAD

**Issue by johnoliver** [AdoptOpenJDK/openjdk-infrastructure#495]
Getting consistent build failures from this node:

https://ci.adoptopenjdk.net/computer/build-osuosl-ppc64-aix-71-2/builds

looks like its probably got something filling up `/ramdisk0`

**Comment by sxa555** [comment]
Have removed all the weekly test job workspaces from the machine. Should be good to go again
