### ISSUE TITLE
[REQUEST] We need a separate machine to build sigtest

### ISSUE THREAD

**Issue by neomatrix369** [AdoptOpenJDK/openjdk-infrastructure#512]
The `sigtest` project is a special case where it needs JDK 5 to 8 in order to build successfully.

All other projects are green now except sigtest:
https://ci.adoptopenjdk.net/view/Dependencies/

Can we have a box which have these JDK version available with their paths mapped to environment variables so they can be accessed from within a script running via jenkins.

JDKs can be from any vendor.

@karianna  or @neomatrix369 are the best people to ask any queries about this request.

**Comment by sxa555** [comment]
Now building at https://ci.adoptopenjdk.net/view/Dependencies/job/sigtest/ on https://ci.adoptopenjdk.net/computer/build-cloudcone-ubuntu1604-x64-1

**Comment by karianna** [comment]
I'm guessing we still want an artifactory or nexus put into play here.

**Comment by neomatrix369** [comment]
Where are you looking (as in which folders) and what do you mean by earlier JDKs?

Also, I had issues `scp`-ing files across to the files area you had suggested the last time, can I try again if it works now?

**Comment by neomatrix369** [comment]
@sxa555 I think I know what you mean by the other JDKs, I couldn't copy them into `userContent` folder as the `scp` asks for a password on the jenkins box, I have prepared zip files that I need to copy over to the  `userContent` folder. After which the rest of the steps will become clearer.

**Comment by neomatrix369** [comment]
Closing as we have addressed it for now
