### ISSUE TITLE
AIX build machine 2: gmake[2]: *** virtual memory exhausted.  Stop

### ISSUE THREAD

**Issue by sxa555** [AdoptOpenJDK/openjdk-infrastructure#517]
Happening on https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-aix-ppc64-openj9/18/console and possible others on [the machine](https://ci.adoptopenjdk.net/computer/build-osuosl-ppc64-aix-71-2/)
```
Compiling 4 files for BUILD_BREAKITERATOR
Generating HTML DTD file
[Parsed DTD html32 in 703ms]
gmake[2]: *** virtual memory exhausted.  Stop.
gmake[2]: *** Waiting for unfinished jobs....
BuildJdk.gmk:68: recipe for target 'classes-only' failed
gmake[1]: *** [classes-only] Error 2
/home/jenkins/workspace/workspace/build-scripts/jobs/jdk8u/jdk8u-aix-ppc64-openj9/workspace/build/src//make/Main.gmk:119: recipe for target 'jdk-only' failed
make: *** [jdk-only] Error 2
[Pipeline] cleanWs
[WS-CLEANUP] Deleting project workspace...[WS-CLEANUP] done
[Pipeline] }
```

**Comment by jdekonin** [comment]
I think this is related to the environment setup for the user.

https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/86bccd2e3625e64eecd2ae22619906cb08a8f820/ansible/playbooks/aix.yml#L521

**Comment by sxa555** [comment]
Even with those changes in effect the error is still showing up.
Restarting the jenkins agent didn't resolve it.
Going to reboot the machine and see if that makes a difference.

**Comment by sxa555** [comment]
Setting jdku181-b13+openj9-0.9 as the boot JVM as a one-off to see if that improves things (1.7/HotSpot Server VM is the default) https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-aix-ppc64-openj9/31/console

**Comment by sxa555** [comment]
Made no difference - attempting top run the old build scripts at https://ci.adoptopenjdk.net/job/openjdk8_openj9_build_ppc64_aix/274/console

**Comment by sxa555** [comment]
Have removed the ramdisk to free up 16GB of RAM. Will likely be very slow but will see how it goes ... 
https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-aix-ppc64-openj9/36/console

**Comment by sxa555** [comment]
Have bumped swap space from 512MB to 2GB (`chps -s 12 hd6`)

**Comment by sej-jackson** [comment]
Just took a quick look and noticed 2 things.... 
- paging space was at default setting of 512MB, so have increased to 2GB (which might not make a great deal of difference unless if actually needs to use paging - was at 5%, now down to 1%)
- the rpc.lockd was crashing every minute (and is practically the only error in errpt - which goes back 2 days).   I'm not sure the cause at the moment, but since NFS isn't in use I've temporarily stopped all the nfs daemons (`stopsrc -g nfs`).  Note that since I've not disabled anything, they will restart on a reboot.

**Comment by sxa555** [comment]
It looks like the machine has got past the failing part on the build at https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-aix-ppc64-openj9/40/ (at least it's got past the section just after `Generating HTML DTD FILE` where it was choking before

**Comment by sxa555** [comment]
I will attempt to revert the above changes one by one at some point in the next couple of weeks to determine which change fixed it. Thanks for the help today @sej-jackson

**Comment by sxa555** [comment]
Reinstated a 10G ramdrive

**Comment by sxa555** [comment]
Rebooting the machine and will re-run the JDK8/J9/AIX build to see whether any of the non-permanent fix attempts were the cause of the problem.

**Comment by sxa555** [comment]
Rebuild successful. Closing this issue
