### ISSUE TITLE
Update NGINX Configuration on ci.adoptopenjdk.net to increase client_max_body_size

### ISSUE THREAD

**Issue by sophia-guo** [AdoptOpenJDK/openjdk-infrastructure#520]
We'd like to set a jenkins job to upload users own preferred JDK, which can be accessed in the same way as all JDKs generated by jenkins build jobs by job's artifact URL. This way test_grinder can also consume user generated JDK.

https://ci.adoptopenjdk.net/view/Test_grinder/job/UploadFile/

The current issue is if JDK is 200M we will get error `413 Request Entity Too Large    nginx/1.10.3 (Ubuntu)`.  Could NGINX Configuration be updated to set `client_max_body_size 300M; ` ?

**Comment by sxa555** [comment]
Update made (was previously 5M)
