### ISSUE TITLE
Create Test CI farm for Ansible testing

### ISSUE THREAD

**Issue by karianna** [AdoptOpenJDK/openjdk-infrastructure#522]
We should have an ansible-ci.adoptopenjdk.net leader with a follower of each type of O/S and arch combination that we want to test ansible on.

**Comment by sxa555** [comment]
This is covered for x86 platforms by https://ci.adoptopenjdk.net/view/work%20in%20progress/job/VagrantPlaybookCheck/

The use of "clean" virtual machines for each test means that it is more reliable than having statically allocated systems, although has the downside that at the moment we cannot test systems of other architectures (ppc64/s390x/arm) unless we can implement https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1059

Related: https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/842 https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/865 https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/910 https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/864 https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/924 https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/977

**Comment by Willsparker** [comment]
Just stumbled across this issue - #1059 has been implemented, and has been expanded to include ARM64 ( #1444 ), and hopefully soon ARM32 ( #1471 )

**Comment by Willsparker** [comment]
With #1640 , I think we test all the branches of our playbooks now. Closing
