### ISSUE TITLE
Set up macos machines to be able to build OpenJ9

### ISSUE THREAD

**Issue by sxa555** [AdoptOpenJDK/openjdk-infrastructure#524]
Instructions to follow via @groeges - plan would be to intiially apply this to https://ci.adoptopenjdk.net/computer/build-macstadium-macos1010-2/ to validate there are no side effects before deploying on the other build machine.

Ref support being added under https://github.com/eclipse/openj9/issues/36

**Comment by groeges** [comment]
**Setup of Mac OS system for build of OpenJDK with OpenJ9**

System needs to have the following code installed on it:
* `Xcode` 4.6.2 required (installed in /Applications/Xcode4/
* `nasm` 2.13.03 required   (install using brew)
* `bash` 4.4.23 required     (install using brew)

**_For JDK8 only_**
export MACOSX_DEPLOYMENT_TARGET=10.8
export SDKPATH=/Applications/Xcode4/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk
export UMA_SUPPRESS_WARNINGS_AS_ERRORS=1
export OMR_WARNINGS_AS_ERRORS=1

**Download the code from Github.com and make JDK**
**_For JDK8_**
- change into a directory to which the code should be downloaded.
- run commands 
    - git clone https://github.com/ibmruntimes/openj9-openjdk-jdk8.git
    - cd openj9-openjdk-jdk8
    - bash ./get_source.sh
    - bash ./configure --with-xcode-path=/Applications/Xcode4/Xcode.app —with-freemarker-jar=<path to freemarker.jar> --with-noncompressedrefs
    - make images

**_For JDK11_**
- change into a directory to which the code should be downloaded.
- run commands 
    - git clone https://github.com/ibmruntimes/openj9-openjdk-jdk11.git
    - cd openj9-openjdk-jd11
    - bash ./get_source.sh
    - bash configure —with-freemarker-jar=<path to freemarker.jar> —with-boot-jdk=<path to jdk11> —disable-warnings-as-erorrs
    - make images

**Comment by groeges** [comment]
JDK11 build completes successfully (on my local Yosemite system)
JDK8 build does not build successfully. Still has errors which are being worked on.

**Comment by sxa555** [comment]
Will start work on configuring https://ci.adoptopenjdk.net/computer/build-macstadium-macos1010-2/ tomorrow

**Comment by sxa555** [comment]
`brew install nasm` has brought it up from 0.98.40 to 2.13.03 (Had to `chown Administrator /usr/local/man/man3` as it couldn't write to there - other `/usr/local/man/man?` directories were already owned by Administrator but `man3` was root)

**Comment by sxa555** [comment]
Passing on JDK11: https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11/job/jdk11-mac-x64-openj9/

OpenJ9 team still have issues to work out for JDK8 - leaving this open until that has been resolved.

**Comment by groeges** [comment]
@sxa555 The OpenJ9 team have now got the JDK 8 build working on Mac OS.
There are some additional pre-requisite code that needs to be installed. 
This is documented in this issue: https://github.com/eclipse/openj9/issues/3323

**Comment by sxa555** [comment]
```
brew install gcc49
brew install gnu-sed
brew install gnu-tar
```
This left me with: `xcrun: error: missing DEVELOPER_DIR path: /Applications/Xcode7/Xcode.app/Contents/Developer`
Fixed with:
```
sudo mkdir /Applications/Xcode7
sudo ln -s /Applications/Xcode.app.7.2.1 /Applications/Xcode7/Xcode.app
```
Then this showed up:

```
/Applications/Xcode.app.7.2.1/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: ../lib/libffi.a(sysv.o) has no symbols
In file included from /usr/include/dispatch/dispatch.h:51:0,
                 from ../omr/include_core/./unix/thrdsup.h:91,
                 from ../omr/include_core/thrdsup.h:35,
                 from ../omr/include_core/thrtypes.h:32,
                 from ObjectMonitor.cpp:28:
/usr/include/dispatch/object.h:143:15: error: expected unqualified-id before '^' token
 typedef void (^dispatch_block_t)(void);
               ^
/usr/include/dispatch/object.h:143:15: error: expected ')' before '^' token
/usr/include/dispatch/object.h:362:3: error: 'dispatch_block_t' has not been declared
   dispatch_block_t notification_block);
   ^
make[3]: *** [ObjectMonitor.o] Error 1
make[3]: *** Waiting for unfinished jobs....
make[3]: *** [DebugBytecodeInterpreter.o] Interrupt: 2
make[2]: *** [j9vm] Interrupt: 2
make[1]: *** [build-j9] Interrupt: 2
make: *** [j9vm-build] Interrupt: 2
Process exited
```
Resolved via the change in the openj9 instructions to edit line 143 of /usr/include/dispatch/object.h and replace with:

```
#ifdef __clang__
typedef void (^dispatch_block_t)(void);
#else
typedef void* dispatch_block_t;
#endif
```
PR now in to set the appropriate variables.
