### ISSUE TITLE
UB18 x86 ansible failures

### ISSUE THREAD

**Issue by jdekonin** [AdoptOpenJDK/openjdk-infrastructure#530]
- azul repo errors
-- workaround...delete repo additions as well as zulu-9 package installation
- apt install errors with libmpfr4, libmpfr4-dbg, openjdk-7-jdk
-- workaround...delete from list
- docker role needs rework
-- workaround... run with `--skip-tags docker`

Note that I am using this machine for performing adoptopenjdk testing, and not compilation of openjdk or openj9-openjdk.  So there very well might be other issues when it comes to creating an SDK binary.

**Comment by karianna** [comment]
* Azul Repo errors maybe an http vs https issue.
* What's the failure on `apt install errors with libmpfr4, libmpfr4-dbg, openjdk-7-jdk`?
* What sort of rework does the docker role need?

**Comment by sxa555** [comment]
To be honest, Unless there's a reason to continue using the azul stuff I'd prefer to install ours now that we're close to having all the version coverage.

**Comment by karianna** [comment]
We don't have a solution for OpenJDK 7.  I think adding keys is a good idea

**Comment by sxa555** [comment]
@jdekonin Here's an example of adding a key: https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/master/ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Docker/tasks/main.yml#L56 although I'm surprised that what's in there doesn't cover you for docker.

**Comment by sxa555** [comment]
> Note that I am using this machine for performing adoptopenjdk testing, and not compilation of openjdk or openj9-openjdk. So there very well might be other issues when it comes to creating an SDK binary.

We could do with having a way to run a subset of the installs for build / test / JCK purposes. The additional JCK playbook is entirely independent at the moment that those requirements would be best included in the main playbooks. It's on the todo list to merge them ;-)

**Comment by sxa555** [comment]
> We don't have a solution for OpenJDK 7

Unless we bootstrap 8 with 8

**Comment by karianna** [comment]
We could do for later 8 builds as no spec changes are likely to come in.

**Comment by jdekonin** [comment]
Was azul added just for bootjdk for compiling JDK10?  If so, then I agree those entries could just be removed.

openjdk7 not being on the machine is only of importance if someone were to try compiling a JDK8 binary.  The build system compiles on centos6.9.

**Comment by karianna** [comment]
Azul was added to provide an OpenJDK 7 to bootstrap 8 builds.  I think we then stuck with Azul builds for subsequent versions

**Comment by jdekonin** [comment]
Not even have for test machine installations?  Are you saying that we should delete anything ubuntu?

**Comment by sxa555** [comment]
No I'm saying we don't need boot JDKs on Ubuntu so could remove the section that installs the JDK7 boot JDKs

**Comment by jdekonin** [comment]
Ah, yes of course.  That makes sense.

**Comment by sxa555** [comment]
As far as I know this is ok now - it fundamentally works (aarch64 may have some other problems) but in the main this is now done and we can deal with subsequent issues as they arise, so I'm closing this issue
