### ISSUE TITLE
Add test prereqs to build-osuosl-ppc64-aix-71-2

### ISSUE THREAD

**Issue by smlambert** [AdoptOpenJDK/openjdk-infrastructure#539]
We have the [test prereqs](https://github.com/eclipse/openj9/blob/master/test/docs/Prerequisites.md) installed on build-osuosl-ppc64-aix-71-1, where we have tagged that machine with labels to allow scripts to use it to run weekly tests.

Someone has added the same labels (hw.arch.ppc & sw.os.aix) to build-osuosl-ppc64-aix-71-2, which means test scripts are trying to run tests on it, but it does not have ant installed so tests can not compile.

Recent [example](https://ci.adoptopenjdk.net/view/Test_weekly/job/openjdk8_hs_openjdktest_ppc64_aix_weekly/27/console):
12:16:55 gmake: ant: Command not found
12:16:55 makefile:82: recipe for target 'compile' failed
12:16:55 gmake: *** [compile] Error 127

We should either ensure ant and other prereqs are installed on that machine, or remove the labels.  (Temporarily I will remove the labels, so the tests stop failing), but it would be more desirable to share weekend testing across both aix machines.  

Also with recent changes, release pipelines will also trigger tests on AIX platform, so this will avoid test compilation failures for release builds.

**Comment by sxa555** [comment]
Not sure how those extra labels got added - I don't believe I added them, but that's the only build machine I have at present so I'd prefer not to be running anything additional on them at the moment so keeping the labels off seems like the right thing. Hadn't appreciated you weren't also using a `test` labal to lock them down though.

**Comment by sxa555** [comment]
Closing as we're only using one AIX machine for tests - the labels should not be there
