### ISSUE TITLE
Should infrastructure.md be a wiki doc instead?

### ISSUE THREAD

**Issue by karianna** [AdoptOpenJDK/openjdk-infrastructure#54]

**Comment by gdams** [comment]
I would argue no as it's useful to have the history for it as it changes but if people are against it's current format then I'm not going to object to having it moved.

**Comment by karianna** [comment]
History... good point - I wonder then if it can be auto generated though from jenkins or some such.

**Comment by sxa555** [comment]
Since we've now done https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/193 (Not sure if there was a related issue) can we close this as being superceded with the yml file?
