### ISSUE TITLE
Get Windows playbooks production ready

### ISSUE THREAD

**Issue by sxa555** [AdoptOpenJDK/openjdk-infrastructure#553]
General issue to cover work being done to make the Windows playbooks "production ready". Should also result in some setup doc.

Info on setting up the communication to windows boxes (since it uses WinRM rather than ssh generally, and the `pywinrm` package to communicate with it) are at https://docs.ansible.com/ansible/latest/user_guide/windows.html

See also https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/300 which has been pending for a while.

**Comment by sxa555** [comment]
Related: https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/378

**Comment by karianna** [comment]
Build machines should always have rsync installed via Cygwin.  I'm not sure if/how Ansible can cover that.

**Comment by sxa555** [comment]
Yep we can cover by ansible - it's just another dependency we need to call out explicitly :-)

**Comment by sxa555** [comment]
@cwesMills Has your work/testing been based on PR300 as a starting point?

**Comment by cwesMills** [comment]
I did not use PR300 as a reference, but the changes I had to make were:
- Install nasm by downloading `https://www.nasm.us/pub/nasm/releasebuilds/2.13.03/win64/nasm-2.13.03-win64.zip` and extracting it to `C:\openjdk\nasm-2.13.03`
- Install clang based on steps provided in [this PR](https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/514)
- Run `ssh-host-config` based on [these steps](https://go.cloudbees.com/docs/cloudbees-documentation/admin-cje/agents/#_microsoft_windows). With the exception, when prompted `Enter the value of CYGWIN for the daemon:` the value should be nothing.
- The jdk I used didn't have the proper cacerts ([known issue](https://github.com/AdoptOpenJDK/openjdk-build/issues/555)), so I had to copy it from an existing machine

**Comment by sxa555** [comment]
What do we need an ssh server config for?

**Comment by cwesMills** [comment]
It is needed to setup cygwin ssh.

**Comment by cwesMills** [comment]
I've just added #589 so windows playbooks will install nasm.

**Comment by sxa555** [comment]
> It is needed to setup cygwin ssh, so the jenkins master can ssh into the machine.
At the moment the adoptopenjdk machines start the jenkins slave as a service, not via ssh so I'm not sure at the moment that I want another port exposed on the adoptopenjdk windows servers.

**Comment by jdekonin** [comment]
Are you wanting cygwin removed from the playbook, because its already present.  My suggestion would be to leave it and modify such that the role is run when requested.  In that way other projects that don't have the option of jenkins connection method can enable and use.

**Comment by sxa555** [comment]
cygwin 100% has to stay there and must not be removed - it's needed for the build scripts we use and a lot of the test infrastructure - my comment was purely about sshd :-)

**Comment by sxa555** [comment]
@cwesMills What's left to get the Windows playbooks into a fulling working state?

**Comment by cwesMills** [comment]
I've fixed a couple of the issues I found with the playbooks, but I don't know if more changes are needed. Currently I have other work that has my priority.

**Comment by sxa555** [comment]
For reference, next steps when you can get back to it:

1. Try running playbooks on a new machine and see if they run to completion
2. See if the machine will be able to `git clone https://github.com/AdoptOpenJDK/openjdk-build` and then
3. From that repository, `CONFIGURE_ARGS_FOR_ANY_PLATFORM="--with-target-bits=32 --target=x86 --with-freetype-include=/cygdrive/c/openjdk/freetype/include --with-freetype-lib=/cygdrive/c/openjdk/freetype/lib32 --with-toolchain-version=2010" ./makejdk-any-platform.sh jdk8u`
4. And then try another build with a fresh clone: `CONFIGURE_ARGS_FOR_ANY_PLATFORM="-with-freemarker-jar=/cygdrive/c/openjdk/freemarker.jar --with-freetype-include=/cygdrive/c/openjdk/freetype/include --with-freetype-lib=/cygdrive/c/openjdk/freetype/lib64 --with-toolchain-version=2013" ./makejdk-any-platform.sh --build-variant openj9 --jdk-boot-dir /cygdrive/c/openjdk/jdk10 jdk11u`

I think those commands should be correct and adequate for a decent amount of testing to understand if the playbooks are production ready.

Any questions give me a shout here or in the #infrastructure channel on the adoptopenjdk slack :-)

**Comment by sxa555** [comment]
That should matter as you can run the playbooks from the `ansible-platbook` command line

**Comment by cwesMills** [comment]
The MSVS_2017 role hangs endlessly when run as part of the playbook. I believe this is because even though the `/Silent` option is used, popups will still appear on the machine that require input (tested manually).

**Comment by cwesMills** [comment]
@sxa555 I've tried running the command you suggested that builds jdk8, but I get the following error
```
checking for FREETYPE... yes
configure: Found freetype using pkg-config, but ignoring since we can not bundle that
configure: error: Could not find freetype!
The freetype library can now be build during the configure process.
Download the freetype sources and unpack them into an arbitrary directory:

wget http://download.savannah.gnu.org/releases/freetype/freetype-2.5.3.tar.gz
tar -xzf freetype-2.5.3.tar.gz

Then run configure with '--with-freetype-src=<freetype_src>'. This will
automatically build the freetype library into '<freetype_src>/lib64' for 64-bit
builds or into '<freetype_src>/lib32' for 32-bit builds.
Afterwards you can always use '--with-freetype-include=<freetype_src>/include'
and '--with-freetype-lib=<freetype_src>/lib32|64' for other builds.
configure exiting with result code 1
```
This was run after the freetype role was updated in #633.

**Comment by cwesMills** [comment]
When I try to build JDK11 it throws an error about not being able to find freemarker, despite freemarker being exactly where I specified.
So to recap, the windows machine setup with the playbook isn't able to build JDK8 or JDK11, and I'm not sure how to fix it.

**Comment by sxa555** [comment]
Ref JDK8 - are the freetype directories at the locations specified in the command you ran?
The freemarker error sounds very odd though - can you paste the exact message?

**Comment by cwesMills** [comment]
The freetype directory is located at `/cygdrive/c/openjdk/freetype-2.5.3` and I made sure to change the command to point at `include` and `lib32` inside this directory. This is the error I get from freemarker while trying to compile jdk11
```
checking that freemarker location is set... no

The FreeMarker library is required to build the OpenJ9 build tools
and has to be provided during configure process.

Download the FreeMarker library and unpack it into an arbitrary directory:

wget https://sourceforge.net/projects/freemarker/files/freemarker/2.3.8/freemarker-2.3.8.tar.gz/download -O freemarker-2.3.8.tar.gz

tar -xzf freemarker-2.3.8.tar.gz

Then run configure with '--with-freemarker-jar=<freemarker_jar>'

configure: Could not find freemarker.jar
configure exiting with result code 1
```
The playbook I used is on `AdoptOpenJDK/openjdk-infrastructure` branch `master` commit `a6ea4f06d7d9cff895d2d0317e1adf3b549a6760`

**Comment by sxa555** [comment]
Some other concerns discovered while setting up the new test boxes #627 if the playbooks are ran as-is. Not sure if @cwesMills experienced any of these in addition to the freemarker concern:
- Some parts (e.g. freetype) require Visual Studio to be installed first. The installer tends to run in the background and takes about 30 minutes - will it be ready in time for the subsequent parts (was [already sequenced wrongly](https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/643))
- cmake silent install parameter was wrong - [should be fixed now](https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/642)
- `perl -MCPAN -e "install Text::CSV_XS"` didn't seem to work - picked up wrong compiler (Although Visual Studio wasn't installed the first time I tried so that may have got cached)
- CUDA toolkit role failed
- Playbook installs 7-Zip into default location `C:\Program Files\7-Zip` instead of `C:\7-Zip`  (MinGW-W64 references it in `C:\7-Zip` ... We could just change the MinGW role.
- One of the other compilers (I think VS2013) wasn't in the download location referenced by the playbooks

**Comment by sxa555** [comment]
NOTE: Will need cygwin64\bin in the PATH before the other git installation otherwise the openjdk-tests  `get.sh` will check out in CRLF format where the test jobs such as Grinder require `\r` only.

**Comment by AdamBrousseau** [comment]
>need cygwin64\bin in the PATH before the other git installation

https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/master/ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/GIT/tasks/main.yml
Assuming you mean Git for Windows. I thought that Cygwin Git was the only Git needed and the other one could be removed.

**Comment by sxa555** [comment]
Potentially yes but I don't want to risk it just now ;-)

**Comment by AdamBrousseau** [comment]
FWIW the OpenJ9 Windows machines don't have Windows Git.

**Comment by HusainYusufali** [comment]
Pull request #653 has been created which fixes 7-Zip installation directory. This should also fix the pull request #644

**Comment by karianna** [comment]
#653 has landed

**Comment by HusainYusufali** [comment]
Pull request #671 has been opened to fix MSVS 2017 installation. I had to install the package [Desktop development with C++](https://docs.microsoft.com/en-us/visualstudio/install/workload-component-id-vs-community?view=vs-2017#desktop-development-with-c) to get the DIA SDK. This entire package has extra packages that may not be needed. @sxa555 Do you know which packages are specifically needed?

**Comment by HusainYusufali** [comment]
Pull request #672 has been opened to fix the NVidia toolkit role which would fail during playbook deployment

**Comment by sxa555** [comment]
I'm not sure on the specific packages - the only details I have are what's in https://github.com/eclipse/openj9/blob/master/doc/build-instructions/Build_Instructions_V8.md

**Comment by sxa555** [comment]
That is https://github.com/AdoptOpenJDK/openjdk-build/issues/813 - delete/rename `clang` from the cygwin directory on the machine

**Comment by HusainYusufali** [comment]
Deleting/renaming clang does not fix this issue. Does the Clang path need to be added to the front of the path in the playbook or does the build script specify its location?

**Comment by HusainYusufali** [comment]
jdk 11 builds successfully when manually inputting the Clang location `C:\openjdk\LLVM64\bin` to the front of the PATH

**Comment by HusainYusufali** [comment]
jdk 8 32-bit and 64-bit build successfully when manually placing the correct Clang location at the front of the path. The commands used to do that are `setx /M PATH "C:\openjdk\LLVM32\bin;%PATH%"` for 32-bit and `setx /M PATH "C:\openjdk\LLVM64\bin;%PATH%"` for 64-bit. 

I also had to manually follow this [wiki](https://github.ibm.com/runtimes/infrastructure/wiki/Windows-Post-Ansible-Playbook-Configuration-for-OpenJ9-OpenJDK8) to install other tools which successfully build jdk 8. The jdk 8 builds failed before I installed the tools and passed after they were present. Some of the software in this wiki require accounts to download, and therefore we may not be able implement them into ansible.

The commands I used to build jdk 8 32-bit and 64-bit respectively are:
`./makejdk-any-platform.sh -C "--with-target-bits=32 --target=x86 --with-freetype-include=/cygdrive/c/openjdk/freetype-2.5.3/include --with-freetype-lib=/cygdrive/c/openjdk/freetype-2.5.3/lib32 --with-freemarker-jar=/cygdrive/c/openjdk/freemarker.jar --with-toolchain-version=2010" --build-variant openj9 --jdk-boot-dir /cygdrive/c/openjdk/jdk8 jdk8u`

`./makejdk-any-platform.sh -C "--with-freetype-include=/cygdrive/c/openjdk/freetype-2.5.3/include --with-freetype-lib=/cygdrive/c/openjdk/freetype-2.5.3/lib64 --with-freemarker-jar=/cygdrive/c/openjdk/freemarker.jar --with-toolchain-version=2010" --build-variant openj9 --jdk-boot-dir /cygdrive/c/openjdk/jdk8 jdk8u`

**Comment by sxa555** [comment]
> jdk 8 32-bit and 64-bit build successfully when manually placing the correct Clang location

This should be handled automatically by the logic in https://github.com/AdoptOpenJDK/openjdk-build/blob/master/build-farm/platform-specific-configurations/windows.sh - it shouldn't need to be set on the machine

> I also had to manually follow this wiki

Which bits specifically can't be automated?

**Comment by HusainYusufali** [comment]
![32bit build](https://user-images.githubusercontent.com/39133984/52438520-74637d80-2ae7-11e9-8963-6bd60e196a0e.PNG)
 When clang32-bit is at the front of the PATH this is the output of all the builds. Only jdk8-32bit builds successfully. The commands I am using are the ones I specified above. I will place clang 64 at the front of the path and rerun the exact same builds.

The only part that can't be automated is installing Windows Visual Studio 2010 SP1 and the the security update that depends on it being installed

**Comment by HusainYusufali** [comment]
![64bit build](https://user-images.githubusercontent.com/39133984/52457701-42730b00-2b29-11e9-80ff-4d471c9869f7.PNG)

When clang64-bit is at the front of the PATH jdk8 and jdk11 64-bit builds successfully. This means that it seems that clang is not specified properly in the build scripts.

**Comment by HusainYusufali** [comment]
The most recent application of the playbooks and completing the post playbook steps allows all the builds complete successfully. The OS's tested were Win 10, Server 2012, Server 2016, and Server 2019. 

For Server 2012, powershell needs to updated to version 5.1 in order for the playbook to work correctly. Some roles like Java installation hang when using an older powershell version. This [MSI](https://download.microsoft.com/download/6/F/5/6F5FF66C-6775-42B0-86C4-47D41F2DA187/Win8.1AndW2K12R2-KB3191564-x64.msu) will update powershell to 5.1 

These are the commands I used for each build:
```
### _JDK8-32_
git clone https://github.com/AdoptOpenJDK/openjdk-build
cd openjdk-build/build-farm
export TARGET_OS=windows
export ARCHITECTURE=x86-32
export JAVA_TO_BUILD=jdk8u
export VARIANT=openj9
export JDK_BOOT_DIR=/cygdrive/c/openjdk/jdk-8
./make-adopt-build-farm.sh

### _JDK8-64_
git clone https://github.com/AdoptOpenJDK/openjdk-build
cd openjdk-build/build-farm
export TARGET_OS=windows
export ARCHITECTURE=x64
export JAVA_TO_BUILD=jdk8u
export VARIANT=openj9
export JDK_BOOT_DIR=/cygdrive/c/openjdk/jdk-8
./make-adopt-build-farm.sh

### _JDK11-64_
git clone https://github.com/AdoptOpenJDK/openjdk-build
cd openjdk-build/build-farm
export TARGET_OS=windows
export ARCHITECTURE=x64
export JAVA_TO_BUILD=jdk11u
export VARIANT=openj9
export JDK_BOOT_DIR=/cygdrive/c/openjdk/jdk-11
./make-adopt-build-farm.sh
```

These are the POST PLAYBOOK steps that need to be completed:

# Windows Post Ansible Playbook Configuration for OpenJ9 OpenJDK8

**The following steps assume that the Windows machine has been already configure using the Windows Ansible Playbook.** 

## Windows Debugging Tools
You can get the Debugging Tools as part of the Windows 7 SDK. Download and install the [Microsoft Windows SDK for Windows 7](https://download.microsoft.com/download/A/6/A/A6AC035D-DA3F-4F0C-ADA4-37C8E5D34E3D/winsdk_web.exe). The default installation options will install the Debugging Tools for Windows (check the **Debugging Tools for Windows** checkbox on the Installation Options screen, under Common Utilities).

### Set Environement Variables 
To add a new system variable or update an existing variable, 

go to Control Panel\System and Security\System\Advanced system settings\, click on the Environment Variables... button and add:

* `C:\Program Files\Debugging Tools for Windows (x64)\sdk\inc` to `INCLUDE`
* `C:\Program Files\Debugging Tools for Windows (x64)\sdk\lib` to `LIB`

or run in Command Prompt:

`setx INCLUDE "C:\Program Files\Debugging Tools for Windows (x64)\sdk\inc";%INCLUDE% /M`
`setx LIB "C:\Program Files\Debugging Tools for Windows (x64)\sdk\lib";%LIB% /M`

## Microsoft Visual Studio 2010 SP1
Download and install the [Visual Studio 2010 SP1 from the official Microsoft download page](https://support.microsoft.com/en-us/help/983509/description-of-visual-studio-2010-service-pack-1).
Download and install the Security Update for Microsoft Visual Studio 2010 Service Pack 1 [(KB2565057)](http://download.windowsupdate.com/msdownload/update/software/secu/2011/07/vs10sp1-kb2565057-x86_03b095a5d3ef98336dffc2bb403ef81271ea6980.exe).

Restart your computer after installations.

### Grant shutdown permission to the Jenkins user

Open _Local Security Policy_(secpol.msc), go to _Local Policies_, expand _User Rights Assignments_ and open _Shut down the system_ (double click). In the _Local Security Settings_ tab click on _Add User or Group..._ button to add jenkins.

**Comment by sxa555** [comment]
Is there no way to install the Debugging SDK and VS2010SP1 automatically?
Also, what is the reason for the jenkins user to be granted shutdown permission?

**Comment by HusainYusufali** [comment]
Silent mode is not supported for the Debugging SDK and VS2010SP1 requires a Microsoft account to download the installer. The installer also has a warning message that hangs the silent install. The jenkins permission doesn't need to be there. I didn't catch it

**Comment by sxa555** [comment]
Hmmm annoying ref VS2010SP1, even more so if it won't silently install.
As far as the Debugging SDK is concerned I suppose to could still download it to the temp directory during the playbook and leave it there for someone to install.

**Comment by karianna** [comment]
We have moved almost all of hotspot to VS2017 - can the same be done here?

**Comment by jdekonin** [comment]
JDK8 Hotspot compile jobs [1] are using 2013, JDK8 OpenJ9 compile jobs [2] are using VS2010.  Oracle supported toolchain [3] is VS2010 atm.  I am not sure as to the current status on VS2017 for JDK8 compiles but when I attempted a few months ago for use with OpenJ9 it wasn't working. 

1. https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-windows-x64-hotspot/254/consoleFull
2. https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-windows-x64-openj9/343/consoleFull
3. https://wiki.openjdk.java.net/display/Build/Supported+Build+Platforms

**Comment by sxa555** [comment]
@HusainYusufali Can the powershell update be automated?

**Comment by HusainYusufali** [comment]
It can be automated. I will add that to the playbook

**Comment by adamfarley** [comment]
Some issues running the Windows playbook locally have been documented here:  https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/791

**Comment by sxa555** [comment]
When run multiple times one of the `PATH` additions fails - this needs to be idempotent:
```
TASK [cygwin : Add c:\cygwin64\bin to front of %PATH%] *************************
fatal: [40.121.164.56]: FAILED! => {"changed": true, "cmd": "setx /M PATH \"C:\\cygwin64\\bin;%PATH%\"", "delta": "0:00:00.125003", "end": "2019-05-28 03:32:41.392060", "msg": "non-zero return code", "rc": 1, "start": "2019-05-28 03:32:41.267057", "stderr": "ERROR: Invalid syntax. Default option is not allowed more than '2' time(s).\r\nType \"SETX /?\" for usage.\r\n", "stderr_lines": ["ERROR: Invalid syntax. Default option is not allowed more than '2' time(s).", "Type \"SETX /?\" for usage."], "stdout": "", "stdout_lines": []}
	to retry, use: --limit @/root/openjdk-infrastructure/ansible/playbooks/AdoptOpenJDK_Windows_Playbook/main.retry

PLAY RECAP *********************************************************************
```

**Comment by sxa555** [comment]
On the assumption that the later PowerShell is only erquired for this operation I have submitted https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/795

**Comment by sxa555** [comment]
The issue with the `SETX` of the cygwin PATH is because there is a `"` mark in the PATH - one of the entries is `C:\Program Files\Microft SQL Server\100\DTS\Binn"`

**Comment by sxa555** [comment]
Modified the SETX so that quote marks are removed from the PATH before it is processed under https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/796

**Comment by sxa555** [comment]
Note that the symptoms if you don't have VS2010SP1 installed you run into this issue: https://github.com/eclipse/openj9/issues/938 with the `_xgetvb` symbol not being found
