### ISSUE TITLE
Jenkins slaves on softlayer windows machines not starting as service

### ISSUE THREAD

**Issue by sxa555** [AdoptOpenJDK/openjdk-infrastructure#559]
Have mitigated for now by creating a `startjenkins.cmd` in Jenkins' home directory which can be used to start the agent. Needs more diagnosis though ...

**Comment by sxa555** [comment]
Marking as systemdown because it is when the machines reboot

**Comment by sxa555** [comment]
Assigning to Haroon for expertise (Not sure if he has access, but we can sort that out. Will need the machines to be quiesced from jenkins workloads before testing these changes though!)

**Comment by Haroon-Khel** [comment]
Despite my efforts, I cannot get the agent.jar to start as a service and it is not clear why. A solution would be to reconfigure Jenkins on the machine entirely.

**Comment by karianna** [comment]
@Haroon-Khel - Can you send in any error logs/messages that you're seeing?

**Comment by Haroon-Khel** [comment]
@sxa555 pointed out that the error messages that I am getting are a result of me trying to start the service manually, while it was already running

**Comment by Haroon-Khel** [comment]
The jenkins agent service on `build-softlayer-win2012r2-x64-1` continues to run after a restart of the machine.
Despite mistakenly restarting `build-softlayer-win2012r2-x64-2`, I can confirm that the agent service continues to run

**Comment by karianna** [comment]
@Haroon-Khel so we can close now?

**Comment by sxa555** [comment]
I thought I had another softlayer test machine available but if I do it's not in jenkins so I'm happy to close this as it appears to now be working based on what Haroon has done today
