### ISSUE TITLE
Get a second windows build machine

### ISSUE THREAD

**Issue by gdams** [AdoptOpenJDK/openjdk-infrastructure#57]
We could do with a windows 2012 server with visual studio 2013 to build the openj9 binaries as this is the required level for openj9 to build. I will investigate where we could source one from.

**Comment by gdams** [comment]
@tellison has powered up a softlayer machine. I am currently having issues building openj9 on it though so will leave this open until complete

**Comment by tellison** [comment]
@gdams any progress on the Eclipse OpenJ9 windows build?  or can you share a link to the issue where it is getting resolved so we can track it pls.

**Comment by gdams** [comment]
We are currently having issues with the Cygwin setup, I am working to get this resolved atm

**Comment by sxa555** [comment]
@gdams @tellison What's the situation on this one - can we get someone else to take it over and if so what's the current state of it (and what's it called?)

**Comment by karianna** [comment]
I'm going to close this as I think we're good here.
