### ISSUE TITLE
Install Build User Vars Plugin on Jenkins

### ISSUE THREAD

**Issue by llxia** [AdoptOpenJDK/openjdk-infrastructure#571]
Could we get `Build User Vars Plugin` installed on AdoptOpenJDK Jenkins? It provides variable such as `BUILD_USER_EMAIL`

https://wiki.jenkins.io/display/JENKINS/Build+User+Vars+Plugin

We would like to show who launch the build in [Grinder](https://ci.adoptopenjdk.net/view/work%20in%20progress/job/Grinder/). It will help users to quickly locate their own builds. For more detail, please see https://github.com/AdoptOpenJDK/openjdk-tests/issues/687

**Comment by karianna** [comment]
Installed - should be active once Jenkins reboots.
