### ISSUE TITLE
AIX Ansible cpan Text::CSV install expects compiler in /usr/vac/bin/xlc_r

### ISSUE THREAD

**Issue by CJKwork** [AdoptOpenJDK/openjdk-infrastructure#579]
On AIX cpan install of Text:CSV is failing becuase somewhere it seems to be hardcoding a path to the compiler of /usr/vac/bin/xlc_r despite the playbook issuing the command `CC=xlc_r cpan -i Text::CSV` - the install path for xlc_r is /opt/IBM/xlC/13.1.3/bin

We are going to implement a temporary workaround of adding a soft link, but this needs further consideration.

**Comment by sxa555** [comment]
Hmmm https://www.cpan.org/authors/id/I/IS/ISHIGAKI/Text-CSV-1.97.tar.gz doesn't reference that path (or even `xlc_r`) at all.

**Comment by jdekonin** [comment]
And the aix playbook already has links defined for xlc.  Which system are you having this problem on?

**Comment by sxa555** [comment]
It's a personal system used for testing playbook changes ... What links are you talking about? I don't believe the playbooks put anything in the `/usr/vac/bin` directory that this problem is about.

**Comment by jdekonin** [comment]
I just meant that the current aix playbook adds xlc links in `/usr/bin/`, so I would expect that first on the path and not `/usr/vac/bin`.  But maybe this is cpan configuration that was set prior to a new xlc install??

**Comment by sxa555** [comment]
From discussion with @CJKwork today it sounds like this is not a problem if you don't try and override `CC=xlc` for the `cpan` operation so I suggest simply removing that from the playbook so it picks up the default

**Comment by jdekonin** [comment]
A base AIX system doesn't come with xlc or gcc pre-installed, so there would be no default to pick up.

**Comment by sxa555** [comment]
True, but this isn't the playbook that's executed on AIX - it's still separate.

**Comment by sxa555** [comment]
In that sutation it'll just fail - but if there is a compiler installed it should pick up thte default one - I'd hope there was a cc->xlc link or something .... According to Clive it does manage to pick up something in that case.

**Comment by Willsparker** [comment]
@sxa555 @karianna Can this be closed now as all mentions of CPAN have been removed as of #1136
