### ISSUE TITLE
antlib could not be found on test-softlayer-ubuntu1604-x64-​1

### ISSUE THREAD

**Issue by llxia** [AdoptOpenJDK/openjdk-infrastructure#586]
Got following error when running the test on [test-softlayer-ubuntu1604-x64-1](https://ci.adoptopenjdk.net/computer/test-softlayer-ubuntu1604-x64-1/)

```
00:03:05.662 Buildfile: /home/jenkins/workspace/Grinder_Sandbox/openjdk-tests/TestConfig/scripts/build_test.xml
00:03:05.662   [taskdef] Could not load definitions from resource net/sf/antcontrib/antlib.xml. It could not be found.
00:03:05.662      [echo]  JAVA_BIN is /home/jenkins/workspace/Grinder_Sandbox/openjdkbinary/j2sdk-image/bin 
00:03:05.662 
00:03:05.662 BUILD FAILED
00:03:05.662 /home/jenkins/workspace/Grinder_Sandbox/openjdk-tests/TestConfig/scripts/build_test.xml:36: Problem: failed to create task or type if
00:03:05.662 Cause: The name is undefined.
```
https://ci.adoptopenjdk.net/view/work%20in%20progress/job/Grinder_Sandbox/17/console

The same test runs ok on other machines.

**Comment by sxa555** [comment]
Had the same problem yesterday on `test-packet-ubuntu1604-x64-2` - a newer version of ant had been installed in /usr/local but the ant-contrib.jar hadn't been installed alongside it - will re-run the playbook on that machine which should resolve it.

**Comment by sxa555** [comment]
Installed via playbook - now closing ... Let me know if there is still a problem.
