### ISSUE TITLE
Ensure OpenJ9 ansible requirements are explicitly called out as such

### ISSUE THREAD

**Issue by sxa555** [AdoptOpenJDK/openjdk-infrastructure#593]
Currently the OpenJ9 requirements have been inlined to the files along with everything else. In order to speed things up for users that may not need be building/using OpenJ9 we should tag with e.g. `build_tools_openj9` in the same we we now have for `build_tools_jfx` (https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/592) so that they can be excluded if desired (and also aid understanding why things are in the scripts.

**Comment by cwillhelm** [comment]
Is there a way to find out what the requirements for Open J9 are?

**Comment by sxa555** [comment]
If there was then this would be trivial ;-)

**Comment by jdekonin** [comment]
The ones I know for certain...

roles: nasm, cmake, clang (windows) msvc2017, git v2+, nvidea cuda drivers, openssl, protobuf, freemarker
packages (names varies to o/s): numactl, bison, flex, dwarf

gcc 4.8.5 which can possibly be removed at some point in the near future unless there are other dependencies on it.

**Comment by sxa555** [comment]
HotSpot is still build with 4.8. Sounds about right with what I expected, although I had thought bison/flex were needed for HotSpot too, but I'm not certian of the history of those being added :-)

**Comment by sxa555** [comment]
(They don't appear in the HotSpot build logs ...

**Comment by sxa555** [comment]
https://github.com/AdoptOpenJDK/openjdk-infrastructure/commit/8d49b3554518609ffd88ab24fad2375f877b7efa covered a first attempt at this, therefore closing. We can add other references as required.
