### ISSUE TITLE
Add Bootjdk11 (for jdk12) to Ansible playbooks and run/install on all build machines

### ISSUE THREAD

**Issue by AdamBrousseau** [AdoptOpenJDK/openjdk-infrastructure#594]
Do we have a flag so we can choose whether to install hs vs openj9?
Do we have flag(s) so we only install bootjdks on build machines and not test machines?

Platforms:
- [x] Linux x64 #604 
- [x] Linux ppc64le #604 
- [x] Linux s390x #604 #606
- [x] Windows #605 
- [ ] Mac #614
- [ ] Arm/Aarch?
- [x] AIX #632

**Comment by AdamBrousseau** [comment]
Is this finished for all platforms?

**Comment by jdekonin** [comment]
I didn't catch the comment in the description of #606.  This isn't complete no.

**Comment by sxa555** [comment]
Completed AFAIK (since we've shipped two releases of JDK12 now!) If anyone knows otherwise feel free to re-open
