### ISSUE TITLE
Create missing Ansible playbooks for build machines

### ISSUE THREAD

**Issue by tellison** [AdoptOpenJDK/openjdk-infrastructure#6]
To ensure that machine images can be reliably recreated for AdoptOpenJDK build/test we need entirely scripted configuration that sets up a VM "from scratch".

A number of the Ansible playbooks exist in the [openjdk-build repo](https://github.com/AdoptOpenJDK/openjdk-build/tree/master/ansible/playbooks), but they are not complete in their coverage.

Proposed steps are:
 - create an initial provisioning script to establish sufficient capability on a new node type to run as an Ansible client (e.g. keybox public key, python, more?)
 - ensure Ansible scripts exist for each CPU/OS type we manage, and are complete.

Goal is that we can discard a VM at any point and recreate it entirely using the public information in our scripts.

**Comment by bblondin** [comment]
Ref: https://github.com/AdoptOpenJDK/openjdk-tests/issues/33

**Comment by gdams** [comment]
We should create ansible scripts for AIX.... I know that once you have installed yum using yum.sh you can use ansible in a pretty normal way. I know that Beth started looking at this for Node https://github.com/nodejs/build/pull/784/files

**Comment by bblondin** [comment]
I'm working on the playbook for AIX. (I just got back from vacation)
I have a working script to configure the filesystem layout: https://github.com/AdoptOpenJDK/openjdk-infrastructure/tree/master/ansible/playbooks/scripts
and the playbook itself is about 75% completed: https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/master/ansible/playbooks/aix.yml
to do:
- Nagios
- Call filesystem script
- CCACHE
- JQ
- JSON
- Text::CSV
- Where do get java from?

**Comment by bblondin** [comment]
The playbook for AIX is now completed

**Comment by bblondin** [comment]
We lost our Semaphore a while back and that has resulted in losing some of the AIX rpms.
@jdekonin is working on rewritting the playbook for AIX

I have completed the playbooks for the following OS/Archs
CentOS 7 on x86 --> centos_7.yml
RHEL 6 on x86 --> rhel.yml
RHEL 7 on x86, ppc64, ppc64le and s390 --> rhel.yml
SLES 11 on x86 and ppc64 --> sles.yml
SLES 12 on x86 and s390 --> sles.yml
Ubuntu 14 on x86, and ppc64le --> ubuntu.yml
Ubuntu 16 on x86, ppc64le, s390, and ARM --> ubuntu.yml
Windows 7, 8, 10  --> windows.yml
Windows Server 2008, 2012, 2016 --> windows.yml

**Comment by gdams** [comment]
@bblondin do we know if the ubuntu.yml works on 32 bit arm as well as aarch64?

**Comment by bblondin** [comment]
It hasn't been tested yet on "armv7l"... good point, I'll update the playbook so its not missing leading
(arm --> aarch64) https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/47

**Comment by bblondin** [comment]
Raspbian 8 on armv7l on Raspberry Pi 2 is working now via  ubuntu.yml

@gdams We should look into scheduling the playbooks to run on all hosts via AWX to ensure they are all up to date with the latest changes/updates

**Comment by karianna** [comment]
Shall we close this issue and raise separate specific ones?  I think that list is complete now, except for Mac?

And thank you @bblondin !

**Comment by bblondin** [comment]
...Mac and z/OS
@jdekonin What is the status of the playbook for AIX?

**Comment by jdekonin** [comment]
I plan on getting back to AIX this week.

**Comment by sxa555** [comment]
@bblondin So is it worth splitting out macos and z/OS into separate issues? I somewhat suspect z/OS will need to be as it'll presumably be a signifcant amount of work ;-)

**Comment by gdams** [comment]
It's worth noting that the Node.js foundation now have working ansible scripts for z/OS so we should be able to copy a lot of that

**Comment by bblondin** [comment]
Closing issue. splitting out into 2 issues for the reminding two playbooks that are needed

Mac OS #212
z/OS #213
