### ISSUE TITLE
Docker is frozen on build-scaleway-x64-ubuntu-16-04-2

### ISSUE THREAD

**Issue by JakubVanek** [AdoptOpenJDK/openjdk-infrastructure#601]
Hi all,

currently, it is not possible to perform docker image removal on `build-scaleway-x64-ubuntu-16-04-2`. When a `docker rmi` or `docker kill` command is invoked, it simply freezes. It seems that docker process got stuck at some `cat` process in a container. It is possible that I caused it by interrupting an ev3 java build in the middle.

I tried to repair the issue from the build scripts, but I wasn't successful. This is output of some common diagnostic commands: https://ci.adoptopenjdk.net/view/ev3dev/job/openjdk12_build_ev3_linux/35/console

I think that docker reboot or machine reboot will solve this issue. There are also some new untagged images, which I think are not necessary.

Thanks,

Jakub

**Comment by karianna** [comment]
OK, managed to clean this all up.  Currently, there are no containers, images or volumes, so the job can start from scratch

**Comment by JakubVanek** [comment]
Thanks!
Jakub

**Comment by JakubVanek** [comment]
Hi,
I sadly managed to trigger this again. This time it is really due to interrupted docker.inside() block: https://ci.adoptopenjdk.net/view/ev3dev/job/openjdk12_build_ev3_linux/44/console
I interrupted the build because I was testing a patch and I realized that the build would crash.
Could you please reboot the machine again? I will have to let the build finish next time.
Thanks,
Jakub
