### ISSUE TITLE
Assign SLES12 box to the test team

### ISSUE THREAD

**Issue by sxa555** [AdoptOpenJDK/openjdk-infrastructure#607]
SInce https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/256 is complete we should now have a reasonable chance of being able to add SLES12 to the list of distributions we can support. I have a spare Linux/s390x system which hasn't been live in jenkins for a while and have just brought it online, removing the `build` tag and replacing it with `test`. 

I have raised https://github.com/AdoptOpenJDK/openjdk-tests/issues/711 to cover starting testing on this platform.

While the initial transfer of the machine is now done, I intend to keep this open until we are confident that the machine setup is good enough for tesing (right now I suspect it isn't...)

**Comment by smlambert** [comment]
Need to install the [test prereq](https://github.com/eclipse/openj9/blob/master/test/docs/Prerequisites.md) Perl modules, Text/CSV.pm & JSON

**Comment by sxa555** [comment]
Hasn't had ansible playbook run on it for a while as it wasn't in the inventory - that should resolve it. Will aim to run it once https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/608 is merged and will aim to run the grinder configuration myself until it does something useful ;-)

**Comment by smlambert** [comment]
Thanks Stewart!  I suggest to either [rebuild Grinder 480 job](https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/480/rebuild/parameterized), or provide the hostname as the LABEL=build-marist-s390x-sles-12 if running a new Grinder.  

I have not added the other labels to this machine used by test scripts, so that it won't get auto-picked up by our regular testing, so you need to use hostname for now as label.

**Comment by sxa555** [comment]
FYI I have renamed the box in jenkins to have a `test-` prefix but the machine itself (at the request of Marist) still has the original name. Hopefully this won't cause too much confusion ...

**Comment by sxa555** [comment]
Thanks - happy to work on adding prereqs until I can make that grinder configuration pass ;-)
Will start by running the currnt playbook on the machine since that should sort out a few of them.

**Comment by sxa555** [comment]
Had to adjust the `/home/jenkins` -> `/data/jenkins` symlink which was in place when it was used as a build machine as things like the ccache directory was chewing up too much space on the filesystem. The playbooks were objecting to the home directory being a symlink so I've cleaned it up and moved it back (`/data/jenkins/workspace` is still where the jobs will be executed)

**Comment by sxa555** [comment]
Memo to self: playbook failed to install downloaded junit rpm. I manually went onto the box and ran "`rpm -i` on the junit rpm and it worked (albeit with the following warning):
```
warning: junit-3.8.2-8.1.noarch.rpm: Header V3 RSA/SHA256 Signature, key ID 3dbdc284: NOKEY
```
Will need to resolve this for the future. Here is the failure when run via ansible:
```
TASK [Ant-Contrib : Install junit from rpm - SLES] *****************************
22:02:24
fatal: [build-marist-sles12-s390x-1]: FAILED! => {"changed": false, "failed": true, "msg": "python2 yum module is needed for this  module"}
```

**Comment by sxa555** [comment]
Had to force install the CPAN JSON module as it failed 2 of its tests:
```
Test Summary Report
-------------------
t/x02_error.t                       (Wstat: 256 Tests: 31 Failed: 1)
  Failed test:  10
  Non-zero exit status: 1
t/xe20_croak_message.t              (Wstat: 256 Tests: 1 Failed: 1)
  Failed test:  1
  Non-zero exit status: 1
Files=60, Tests=3715,  2 wallclock secs ( 0.21 usr  0.04 sys +  2.12 cusr  0.18 
```
```
build-marist-sles12-s390x-1:~ # cpanm --with-recommends JSON --force--> Working on JSON
Fetching http://www.cpan.org/authors/id/I/IS/ISHIGAKI/JSON-2.97001.tar.gz ... OK
Configuring JSON-2.97001 ... OK
Building and testing JSON-2.97001 ... FAIL
! Testing JSON-2.97001 failed but installing it anyway.
Successfully installed JSON-2.97001
1 distribution installed
```

**Comment by sxa555** [comment]
Playbook has installed a non-SSL enabled verison of git under `/usr/local/bin` which therefore cannot clone `https` URLs

**Comment by sxa555** [comment]
@smlambert can you check out https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/490/console for me please? It seems to have failed to locate jtreg:

`18:58:24 Error: Unable to access jarfile /data/jenkins/workspace/Grinder/openjdk-tests/TestConfig/scripts/testKitGen/../../../../jvmtest/openjdk_regression/jtreg/lib/jtreg.jar`

**Comment by smlambert** [comment]
I reran the grinder job, needed BUILD_LIST=openjdk_regression (the directory you wish to build) instead of openjdk, and looks good https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/491/testReport/

**Comment by smlambert** [comment]
Ran system test grinder also, as they have slightly different requirements than other tests:
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/492/

**Comment by sxa555** [comment]
Looks good, so I'll close this one and we can cover further work in the realted openjdk-tests issue :-D
