### ISSUE TITLE
Install perl XML::Parser module on test machines

### ISSUE THREAD

**Issue by llxia** [AdoptOpenJDK/openjdk-infrastructure#622]
Since we want to update testKitGen to use standard XML parser to parse *.xml files, we need to install XML::Parser module on test machines.

XML Parser is in the Adopt Unix playbooks, but we need to make sure it is installed on all test machines. See comment from Adam:
https://github.com/eclipse/openj9/pull/499#issuecomment-438005342

**Comment by jdekonin** [comment]
I think cygwin installs this by default when also installing perl.  At least that appears to be the case on the systems that I have that are setup with the windows playbook.  `/usr/lib/perl5/vendor_perl/5.26/x86_64-cygwin-threads/XML/Parser.pm` is where its put.

But Strawberry perl is also a role on windows, which version is this needed under?  Which version of perl should be used for windows?

**Comment by llxia** [comment]
Close this issue as we are going to switch to use TKG for java soon. Perl module is no longer needed.
