### ISSUE TITLE
Improve documentation around running the Playbooks.

### ISSUE THREAD

**Issue by flybd5** [AdoptOpenJDK/openjdk-infrastructure#626]
I'm sorry, but this repo should definitely not be made public. It's not ready for that. There are too many things in it that make it dangerous. For example, it starts an X11 server that locks up all sessions and video in gnome on Ubuntu 18, without asking for permission or even checking. I had to reboot three times before I figured out what was causing that in the playbook. It also checks for the existence of half a dozen keys that are unnecessary and relevant only to your internal infrastructure build. There are a number of integrations, such as jenkins, that should be disabled by default. In fact, all these things should ALL be disabled by default, with extensive documentation about what they are and in what circumstances to turn therm on. I have no idea now how I am going to set up an environment to build the jdk, and frankly cannot recommend the use of the AdoptOpenJDK to my client until all these problems are addressed. They customize the JDK to their needs and will not tolerate this situation.

**Comment by karianna** [comment]
@flybd5 Hi there and welcome to AdoptOpenJDK.

You've raised a number of points here that we need to split out.  Firstly a question, what platform(s) are you expecting to build on and which versions of OpenJDK?

Also please see AdoptOpenJDK.net/slack.html to join our community.

**Comment by flybd5** [comment]
The repo instructions don't give you options on the basis of what platforms I will build on, they just say to run the Ansible scripts, with a mention of how to skip some tags, but no inventory of all the tags and what they mean. I need JDK 8 and 11 with Hotspot. I tried the build on a Debian docker container as well as an Ubuntu 18 desktop.

**Comment by karianna** [comment]
@flybd5 - I assume you were following the instructions at:

https://github.com/AdoptOpenJDK/openjdk-infrastructure/tree/master/ansible/README.md

If you can confirm that, then I'll change this to a documentation issue and have someone look at that.

Then if there are further technical issues with the ansible scripts we should raise separate issues.

**Comment by flybd5** [comment]
Correct. The documentation does not warn the user about the harmful things
some of the steps in the playbooks can do, but the playbooks should be
modified to make all of those optional, not rely on the user to have to
read and figure out what to turn off.

**Comment by sxa555** [comment]
> It's not ready for that. There are too many things in it that make it dangerous.
I think in terms if running it on your own laptop that is correct, but for anyone who has a server farm, or is running in a virtual machine then it's suitable and for that reason I wouldn't want to hide it from being public.
> starts an X11 server that locks up all sessions and video in gnome on Ubuntu 18
That's a little bit strange - the x11 startup should be on a secondary X display so I'm a little surprised it interferes. Saying that I'm not sure it needs to be a full X11 server so an Xvfb may be a better choice (and safer ...)
> It also checks for the existence of half a dozen keys that are unnecessary
Agreed - our exclusion ability around this still needs work and it's finally bubbling somewhere near the top of my list and as Adam says any assistance is very much welcome ;-)
> I have no idea  now how I am going to set up an environment to build the jdk
The simplest answer - which we generally recommend to people looking to modify and build their own - is to run the build via a docker container which wouldn't negatively affect your host. The other option would be to manually run through the steps in the playbook (which is effectively what I've done on my personal laptop).
Related: https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/532

**Comment by flybd5** [comment]
I don't really have the time to figure this out and fix it for you. I'm up to my gills in other work. My client has an MSA with Azul, though. Maybe they can do something about this.

**Comment by karianna** [comment]
@sxa555 - assuming @flybd5 is unable to test out the latest changes I think it's still a good idea to have some entity outside of Adopt regularly try our scripts out.  One for the TSC to discuss perhaps?

**Comment by sxa555** [comment]
Related: #685

**Comment by sxa555** [comment]
Related: https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/791

**Comment by Willsparker** [comment]
As mentioned here https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/772#issuecomment-483252049 ; When skipping the `adoptopenjdk` tag, they now broadly safe, except for changing the host names. The docs have had a lot of work done on them to support running the playbooks too, with encouragement to run them on Vagrant VMs.
@sxa If you have no objections, I'll look at adding the `adoptopenjdk` tag to the tasks that changes the hostnames and then we can close this issue?

**Comment by sxa** [comment]
Hmmm that's definitely an omission if that tag isn't on that role, so no objections

**Comment by Willsparker** [comment]
Ah, my mistake, the tag IS on those tasks (https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/931).

I think since the creation of this issue, most (if not all) specific concerns have been fixed, in both documentation and with the addition of the `adoptopenjdk` tag. Feel free to re-open or create new issues if anybody disagrees with this.
