### ISSUE TITLE
Request 2 Windows machines for testing

### ISSUE THREAD

**Issue by smlambert** [AdoptOpenJDK/openjdk-infrastructure#627]
We are adding some MBCS testing at AdoptOpenJDK.  

For Linux/AIX, the language settings can be done dynamically for each process by setting LANG environment variable.  

Ansible could install language packs into English Windows and switch the language, but it requires to reboot.  Ultimately this will be best done when we have a dynamically allocated build/test farm as suggested by https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/609.

As that may take some time to achieve, so in the meantime, we would like to request 2 additional Windows machines to allow for greater language coverage.

**Comment by karianna** [comment]
@gdams - Do we still have Azure credits we can use up?

**Comment by gdams** [comment]
yeah we do :)

**Comment by tellison** [comment]
@smlambert What version of Windows and what machine spec are you requesting?

Common options include:
`Windows Server 2016 Datacenter`
`Windows Server 2012r2 Datacenter`
`Windows Server 2008r2 SP1`

2 vCPUs and 4Gb RAM ok, or do you require more?

Data disk size?

**Comment by smlambert** [comment]
Windows Server 2012r2 Datacenter, 2 vCPUs and 4Gb RAM should be fine

**Comment by smlambert** [comment]
The typical windows ansible test setup is a good start, there will be an additional setup on these 2 machines (for setting to Japanese and Korean locales for MBCS testing).

@toshiona @takiguc - can you please advise on what additional configuration needs to be done on these machines to ready them for use by MBCS tests?  Thanks!

**Comment by tellison** [comment]
Created `test-2012r2-2 (40.121.164.56)` and `test-2012r2-3 (13.68.219.237)` for the purpose.

Each of these are Windows 2012r2 Datacenter, 2vCPUs, 4Gb RAM, 127 Gb SSD data disk machines.

**Comment by tellison** [comment]
Unassigning myself so that somebody can pick up the task for configuring via Ansible, and adding to Jenkins.  I'll pass on the login info to the next person.

**Comment by sxa555** [comment]
`-3` is mostly ready now (Doesn't have all the compilers installed but hopefully enough)

I haven't put the character sets on yet though, and it's not connected to jenkins.

This has been set up as per the playbooks so will be a good test of whether the playbooks are in a reasonable state at the moment ..

**Comment by sxa555** [comment]
`-3` now connected to jenkins although without the test tags. I think it's got most of what test needs so @smlambert if you can try kicking off something on there and see what might still be missing that would be appreciated

**Comment by smlambert** [comment]
Something is not quite right, same test on `-1` vs `-3`:

https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/716 run on test-azure-win2012r2-x64-1
and 
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/715  run on test-azure-win2012r2-x64-3

chokes on get.sh script:

$ ssh-agent
16:00:44 ++ pwd
16:00:44 ++ pwd
16:00:44 + ./openjdk-tests/get.sh -s /cygdrive/c/Users/jenkins/workspace/Grinder -t /cygdrive/c/Users/jenkins/workspace/Grinder/openjdk-tests -p x64_windows -r nightly -j SE80 -i openj9 --openj9_repo https://github.com/eclipse/openj9.git --openj9_branch master
16:00:44 ./openjdk-tests/get.sh: line 14: $'\r': command not found
16:00:44 ./openjdk-tests/get.sh: line 15: set: -
: invalid option
16:00:44 set: usage: set [-abefhkmnptuvxBCHP] [-o option-name] [--] [arg ...]
16:00:44 ./openjdk-tests/get.sh: line 16: $'\r': command not found
16:00:44 ./openjdk-tests/get.sh: line 34: $'\r': command not found
16:00:44 ./openjdk-tests/get.sh: line 35: $'\r': command not found
16:00:44 ./openjdk-tests/get.sh: line 36: syntax error near unexpected token `$'\r''
16:00:44 ./openjdk-tests/get.sh: line 36: `usage ()
'
[Pipeline] }
16:00:45 [ssh-agent] Stopped.

**Comment by sxa555** [comment]
That looks like a git checkout thing with it translating the scripts to DOS CRLF line endings instead of leaving them in UNIX format ... Will take a look

**Comment by sxa555** [comment]
Path issue ... Now resolved https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/721/console

**Comment by smlambert** [comment]
So, next one is to install all the [test prereqs](https://github.com/eclipse/openj9/blob/master/test/docs/Prerequisites.md):

From [721/console output](https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/721/console):
make: ant: Command not found

**Comment by sxa555** [comment]
ant hadn't been added to PATH - now fixed.

**Comment by gdams** [comment]
can this be closed?

**Comment by sxa555** [comment]
Pretty sure I did a manual install of the appropriate locales, but will double check ...

**Comment by sxa555** [comment]
It has the languages installed - is there something else that is needed? 
![image](https://user-images.githubusercontent.com/6487691/51396857-dc055900-1b37-11e9-8a1c-3aba4dfc38cf.png)

**Comment by smlambert** [comment]
I ran https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/877/
and looks good, the MBCS_Tests_charsets test target passes!  

Once the 2nd machine is set up the same way, this can be closed, thanks!!

**Comment by toshiona** [comment]
@sxa555 Thank you for your kind support. The screen shot indicates Japanese and Korean language pack were installed expectedly.

The remaining setups are below:
- Change language list order and override it
- Change format setting
- Change system locale (Non-Unicode locale) setting
- Reboot

They are also defined in the suggested Ansible Playbook in PR #636.
The Playbook checks installed language pack and should work under the current condition.

Back ground:
Windows can set a single primary language, and rebooting is required to change it.
(Linux/AIX can switch language by just changing LANG environment variable, though.)

Additionally, each application refers language by its own way.
- OpenJ9 refers format setting.
- HotSpot refers language list order and system locale.
- Batch files for testcase refer format and system locale.
So, we need to set up all these configurations. And, this is the reason we requested two machines for Japanese and Korean.

@smlambert I'm sorry, our MBCS testcases for Windows hasn't been contributed yet.
I think Linux and AIX parts had been integrated.

**Comment by sxa555** [comment]
`-2` now set up via playbooks (first production machine to be done this way, so may be teething trouble) but with c:\openjdk\jdk-* symlinks created manually. Korean and Japanese locales installed. Let me know by reopening this issue if this causes any problems. I'll try and keep an eye on it

https://ci.adoptopenjdk.net/computer/test-azure-win2012r2-x64-2/

**Comment by sxa555** [comment]
`-2` currently offline (reason unknown). `-3` is not fully configured (`JAVA_HOME` wasn't set - pointed system environment variable to the right place for the adoptopenjdk 8 SDK). Currently failing on missing perl. Will run playbooks against `-3` today.

**Comment by Willsparker** [comment]
Re-enabled `test-azure-win2012r2-x64-3` to see if the issues that @sxa555 encountered that made him disable the machine, crop up again. Attempting to run a Grinder on it too : https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1524/console 
However that didn't go to well..

**Comment by Willsparker** [comment]
Reinstalled `Git` in cygwin, removed git-for-windows and a Grinder running the 32 bit tests passed, despite that being the thing the machine was disabled for on Jenkins: https://ci.adoptopenjdk.net/job/Grinder/1539/

**Comment by Willsparker** [comment]
Running the tests related to #964 , `test-azure-win2012r2-x64-3` passed: 
https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/964#issuecomment-571111368

Is there anything to left to be done with this issue ?

**Comment by sxa555** [comment]
`-2` is offline, so yes :-)

**Comment by sxa555** [comment]
`-2` should be back online now  so we can  work on getting this live again

**Comment by sxa555** [comment]
@Willsparker I think you previously had access to [test-azure-win2012r2-x64-2](https://ci.adoptopenjdk.net/computer/test-azure-win2012r2-x64-2) so can you see if we can get it back into a usable state? If you've lost the credentials I can get them to you again

**Comment by sxa555** [comment]
(NOTE: Two new windows server 2019 machines were also added under #1103)

**Comment by sxa555** [comment]
> @Willsparker I think you previously had access to [test-azure-win2012r2-x64-2](https://ci.adoptopenjdk.net/computer/test-azure-win2012r2-x64-2) so can you see if we can get it back into a usable state? If you've lost the credentials I can get them to you again - it would be good to get this finished

@adam-thorpe On second thoughts if you're looking for infra issues this might be a good one for you to take on :-)

**Comment by adam-thorpe** [comment]
Sure, I can pick this up. I imagine running the sanity openjdk tests against this machine is a good start? @sxa555 could I get the credentials please

**Comment by sxa555** [comment]
Have sent them to you :-) Good luck!

**Comment by sxa555** [comment]
Seems it's not responding to remote desktop connections - have asked @d3r3kk to look into it again

**Comment by sxa555** [comment]
Splitting off the issue with azure -2 since the original request for extra machines has been met
