### ISSUE TITLE
Get a more powerful ARM 32 box

### ISSUE THREAD

**Issue by karianna** [AdoptOpenJDK/openjdk-infrastructure#630]

**Comment by JakubVanek** [comment]
Hmmm, I wonder if running armhf Docker containers on aarch64 would do it. Alternatively if the only needed thing is to build the JDK, then cross compilation could work. However it is a compromise as this doesn't allow for runnings tests natively (outside of QEMU).

**Comment by vielmetti** [comment]
A brief update in advance of the TSC meeting.

1. There are currently two server-class architectures that support 32-bit code in addition to 64-bit code on Arm servers. The Hisilicon "Hi1616" chip and the Ampere "eMag 1" chip both do this today. 
2. Server-class chips from other vendors, including Marvell ("ThunderX" and "ThunderX2") and Qualcomm ("Centriq 2400"), do not have a 32-bit native execution environment.
3. Packet has both Hisilicon and Ampere systems in inventory in very small quantities. When additional units free up, I plan to get Adopt OpenJDK at least one of them and hopefully one of each of them at least for comparison.
4. The long-term availability of server-class devices that support both 32-bit and 64-bit work is uncertain. We expect more vendors to drop 32-bit support for their next generations of high end chips, but who knows, and there's always surprises.
5. The long-term demand for single-board and small devices for 32-bit work is unlikely to diminish, especially as the Android ecosystem still has a whole lot of 32-bit code in it.

Happy to talk through any or all of these points in suitable detail.

**Comment by karianna** [comment]
Thanks for the update that's very useful detail

**Comment by vielmetti** [comment]
New 32-bit ready Arm gear is in, so this can start to move forward. I'll coordinate with @gdams @sxa555 to get a machine reserved to the right place so we can test and set up.

**Comment by aahlenst** [comment]
More powerful ARM32 machines have been ordered.
