### ISSUE TITLE
AIX test machine build-osuosl-ppc64-aix-71-1 file ulimit is too low

### ISSUE THREAD

**Issue by ben-walsh** [AdoptOpenJDK/openjdk-infrastructure#637]
The file ulimit on AIX test machine build-osuosl-ppc64-aix-71-1 is too low for running the JTReg sanity test suite.
See https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/546/testReport/junit/java_io_FileOutputStream_ManyFiles/java/ManyFiles which had a knock-on effect to other tests too (https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/546).
Please increase it to a reasonable level - unlimited if that is acceptable.
Also make same change to any other AIX test machines.

**Comment by sxa555** [comment]
Already looks to be unlimited:
```
$ hostname
build-osuosl-ppc64-aix-71-1
$ ulimit -a
time(seconds)        unlimited
file(blocks)         unlimited
data(kbytes)         unlimited
stack(kbytes)        32768
memory(kbytes)       32768
coredump(blocks)     unlimited
nofiles(descriptors) 2000
threads(per process) unlimited
processes(per user)  unlimited
```

**Comment by ben-walsh** [comment]
The required RELEASE_TAG value changed between when the original job was completed and @sxa555 attempt to re-run with https://ci.adoptopenjdk.net/job/Grinder/619/console. I've kicked off a re-run at https://ci.adoptopenjdk.net/job/Grinder/625/console with the required change to the parameter.

**Comment by sxa555** [comment]
@ben-walsh Is this sorted now or is there still a problem with it?

**Comment by ben-walsh** [comment]
Unknown ... looks like https://ci.adoptopenjdk.net/job/Grinder/625/console got removed.
Rerunning at https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/694/console.
Note - I won't be working on AIX this side of the Xmas hols, so no urgency on this till after.

**Comment by sxa555** [comment]
@ben-walsh Is this still causing problems? (FYA @smlambert)

**Comment by ben-walsh** [comment]
Unknown. We haven't had a run on AIX that produced triageable results for months.
All manual AIX testing was temporarily shifted to internal only due to the machine resource limitations and/or failures.
I'll kick off a grinder job of the full JTReg Sanity suite - which will take at least 4-5 hours to successfully complete (assuming it does). This should be aborted if it's impacting build jobs.

**Comment by ben-walsh** [comment]
Proceeding - https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1188/console

**Comment by sxa555** [comment]
@smlambert Do you know if this has shown any issues recently? Since no-one's been yelling at me I'm guessing it might have gone away as an issue?

**Comment by smlambert** [comment]
Launched https://ci.adoptopenjdk.net/view/Test_openjdk/job/Test_openjdk8_j9_sanity.openjdk_ppc64_aix/6 and 
https://ci.adoptopenjdk.net/view/Test_openjdk/job/Test_openjdk11_j9_sanity.openjdk_ppc64_aix/3
to see what is the latest state of AIX sanity.openjdk

**Comment by smlambert** [comment]
https://ci.adoptopenjdk.net/view/Test_openjdk/job/Test_openjdk11_j9_sanity.openjdk_ppc64_aix/3/testReport/ - ManyFiles.java test passed, let's assume this issue has been addressed.
