### ISSUE TITLE
Require temp access to test-azure-win2012r2-x64-1

### ISSUE THREAD

**Issue by ben-walsh** [AdoptOpenJDK/openjdk-infrastructure#638]
I need to acquire temp access to the test machine test-azure-win2012r2-x64-1 to obtain two sets of coredumps which were generated during jobs https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/600 and https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/599.

**Comment by karianna** [comment]
@ben-walsh Ping me on slack when you're online.

**Comment by ben-walsh** [comment]
@karianna Thanks but likely not needed now - Stewart A has put together a modified test grinder job which we are testing out, which archives the workspace in the way I was expecting KEEP_WORKSPACE would - https://ci.adoptopenjdk.net/view/work in progress/job/SXA-Grinder.
Closing for now - will reopen if this modified job is insufficient for my needs. Thanks.
