### ISSUE TITLE
New ansible-lint reported rule errors

### ISSUE THREAD

**Issue by toshiona** [AdoptOpenJDK/openjdk-infrastructure#641]
ansible-lint seems to be updated recently and was reporting 191 errors now.

My CI result:
https://travis-ci.org/AdoptOpenJDK/openjdk-infrastructure/builds/469878639

The following are typical errors:

[601] Don't compare to literal True/False
/home/travis/build/AdoptOpenJDK/openjdk-infrastructure/ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Ant-Contrib/tasks/main.yml:30
  when: antcontrib_status.stat.exists == False
  
[204] Lines should be no longer than 120 chars
/home/travis/build/AdoptOpenJDK/openjdk-infrastructure/ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/CPAN/tasks/main.yml:11
    - (ansible_distribution == "RedHat" and ansible_distribution_major_version == "6") or (ansible_distribution == "CentOS" and ansible_distribution_major_version == "6") or (ansible_distribution == "SLES")
    
[405] Remote package tasks should have a retry
/home/travis/build/AdoptOpenJDK/openjdk-infrastructure/ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/CPAN/tasks/main.yml:17
Task/Handler: Install cpanminus RedHat 7 and Centos 7

[504] Do not use 'local_action', use 'delegate_to: localhost'
/home/travis/build/AdoptOpenJDK/openjdk-infrastructure/ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Nagios_Master_Config/tasks/main.yml:26
  local_action: command ssh -o StrictHostKeyChecking=no root@{{ Nagios_Master_IP }} "/usr/local/nagios/Nagios_Ansible_Config_tool/Nagios_Ansible_Config_tool.sh  {{ ansible_distribution }} {{ ansible_architecture }} {{ inventory_hostname  }} {{ ansible_host }} {{ provider }} {{ ansible_port }} "
 
[602] Don't compare to empty string
/home/travis/build/AdoptOpenJDK/openjdk-infrastructure/ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/curl/tasks/main.yml:31
    - ((curl_version.stdout == '') or ((curl_version.stdout != '') and (curl_version.stdout | version_compare('7.20.0', operator='lt', strict=True))))
    
[206] Variables should have spaces before and after: {{ var_name }}
playbooks/aix.yml:748
            if [[ $curr_swap_size -lt {{swap_size}} ]]
`

**Comment by sxa555** [comment]
I'm not keen on avoiding the 120 character thing since some of the URLs we retrieve are longer than that.
Also the `compare to literal True/False` thing is given in many of the examples in the ansible docs

**Comment by sxa555** [comment]
Looks like https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/master/ansible/yamllint.yml should be handling this from what I can tell, but it's not taking effect any more

**Comment by sxa555** [comment]
@inponomarev Do you know why this is no longer working as expected?

**Comment by inponomarev** [comment]
@sxa555 oops guys I'm really really sorry! Of course it was my mistake that I didn't specify the versions of components in Travis script. It turned out to be a sort of time bomb that eventually disrupted your work.

See my PR #648, this should fix the problem.

However, guys, AFAICS your builds are broken:

* playbooks/AdoptOpenJDK_Unix_Playbook/roles/GIT_Source/tasks/main.yml has yamllint violations,
* playbooks/AdoptOpenJDK_Windows_Playbook/main.yml even fails the --syntax-check!

**Comment by sxa555** [comment]
Yep I'm aware of the windows issue and we've hit the problem associated with it. Thanks for the PR!

**Comment by sxa555** [comment]
With Husain's PR and https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/650 we're now clean again - thanks @inponomarev :-D
