### ISSUE TITLE
Scaleway ARMv7 boxes are down

### ISSUE THREAD

**Issue by JakubVanek** [AdoptOpenJDK/openjdk-infrastructure#647]
Hi,

I noticed that the ARM32 boxes are down for some time. It might be related to https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/612. Something suspicious I had interrupted because it was looong stuck in offline mode is here: https://ci.adoptopenjdk.net/view/arm/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-linux-arm-hotspot/28/console

I suspect that the problem is this:
```
Build performance summary:
* Cores to use:   26
* Memory limit:   2000 MB
* ccache status:  Active (3.1.9)
```

It seems that typically the job count is limited to one job per 1 GB of RAM. This may indicate that the machine runs out of RAM or swap. It is however strange that the out of memory killer resulted in this.

Regards,

Jakub

**Comment by JakubVanek** [comment]
Hmmm, my reasoning may be wrong, because previously builds which claimed the same number of jobs succeeded: https://ci.adoptopenjdk.net/view/arm/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-linux-arm-hotspot/27/console

**Comment by karianna** [comment]
I'm rebooting the two machines as I can't ssh into them.

@sxa555 I think we may need to chat to the Scaleway folks about this, it's far too regular.

**Comment by karianna** [comment]
They're back up now.

**Comment by JakubVanek** [comment]
Thanks!

Jakub
