### ISSUE TITLE
Linux/ppc64le playbook failure on adoptopenjdk10 role

### ISSUE THREAD

**Issue by sxa555** [AdoptOpenJDK/openjdk-infrastructure#669]
Required for JDK11 builds. Looking at https://adoptopenjdk.net/releases.html?variant=openjdk10&jvmVariant=hotspot it appears that only x64 platforms (Linux/macos/win) are available. This seems wrong. Options:
- Find where they've gone and reinstate them
- Switch to using the OpenJ9 ones that are there
- Give up and bootstrap with a JDK11
@karianna @johnoliver FYI

**Comment by AdamBrousseau** [comment]
FWIW at OpenJ9 CI we switched to use 11 for 11 since it will be LTS and 10 is already done.

**Comment by karianna** [comment]
@johnoliver maybe we can look to provide a one-off build?

**Comment by sxa555** [comment]
Ref: https://github.com/AdoptOpenJDK/openjdk-build/issues/1011

**Comment by sxa555** [comment]
Will, once you get access to an internal Linux/ppc64le machine we can verify that is no longer an issue.

**Comment by Willsparker** [comment]
Ran a playbook on a Fyre VM and got past "adoptopenjdk10"- so issue resolved 👍

**Comment by sxa555** [comment]
Thanks
