### ISSUE TITLE
Jenkins agent issue on test-packet-armv8-ubuntu-16-04

### ISSUE THREAD

**Issue by smlambert** [AdoptOpenJDK/openjdk-infrastructure#674]
Unable to start a test run on https://ci.adoptopenjdk.net/computer/test-packet-armv8-ubuntu-16-04/

ERROR: Issue with creating launcher for agent test-packet-armv8-ubuntu-16-04. The agent is being disconnected
[Pipeline] // node

(see https://ci.adoptopenjdk.net/view/Test_openjdk/job/openjdk11_hs_openjdktest_aarch64_linux/74/console)

**Comment by smlambert** [comment]
Just disconnected/reconnected machine from Jenkins, will run test to see if resolved.  (thanks @AdamBrousseau for the suggestion).

If not, will ask that machine gets rebooted to see if resolves the problem.

**Comment by smlambert** [comment]
Disconnect/reconnect does not help, I have put the machine offline.  
Can someone try a reboot?  

This blocks aarch64 testing (our only machine).

<img width="826" alt="screen shot 2019-01-22 at 9 43 13 pm" src="https://user-images.githubusercontent.com/2836948/51579388-cc1aab80-1e8e-11e9-9863-5555d9c111a7.png">

**Comment by sxa555** [comment]
Hmmm easily reproducible as running something from the jenkins script console on that machine shows a problem ...

**Comment by sxa555** [comment]
Disconnect/reconnect seems to have worked for me - my script console job now works, and https://ci.adoptopenjdk.net/view/Test_openjdk/job/openjdk11_hs_openjdktest_aarch64_linux/90/console appears to be running on it.
