### ISSUE TITLE
Add new aarch64 test machines

### ISSUE THREAD

**Issue by gdams** [AdoptOpenJDK/openjdk-infrastructure#680]
test-openlab-ubuntu1804-armv8-1 - ubuntu@147.75.198.131
test-openlab-ubuntu1804-armv8-2 - ubuntu@147.75.198.132
test-openlab-ubuntu1804-armv8-3 - ubuntu@199.204.45.37
test-openlab-ubuntu1804-armv8-4 - ubuntu@162.253.55.204
test-openlab-ubuntu1604-armv8-1 - ubuntu@147.75.198.134
test-openlab-ubuntu1604-armv8-2 - ubuntu@147.75.198.137
test-openlab-ubuntu1604-armv8-3 - ubuntu@199.204.45.100
test-openlab-ubuntu1604-armv8-4 - ubuntu@199.204.45.53

FYI @AdoptOpenJDK/testing

**Comment by smlambert** [comment]
Wow!  This is great!

**Comment by gdams** [comment]
@smlambert centos7 on the way too!!

**Comment by vielmetti** [comment]
Just based on the IP address ranges and names in use, some of these look like OpenLab OpenStack systems running on servers at Packet. How are these systems configured?

**Comment by gdams** [comment]
@mrhillsman are you able to help here?

**Comment by mrhillsman** [comment]
@gdams unfortunately i do not have specific config details other than that they are 8vCPU|8G RAM|80G Disk VMs; is there something more being requested?

**Comment by vielmetti** [comment]
Do you happen to know, @mrhillsman @gdams , which CPU they are running on? `uname -a` or `cpuinfo` would be useful. 

(It's possible technically that some of these VMs could be useful for 32-bits as well, hence my questions; and the ThunderX CPU is different enough from the Ampere CPU that you'd notice it.)

**Comment by mrhillsman** [comment]
@vielmetti i will check shortly and provide output if @gdams does not beat me to it

**Comment by mrhillsman** [comment]
@vielmetti 

root@sample:~# uname -a
Linux sample 4.4.0-140-generic #166-Ubuntu SMP Wed Nov 14 20:10:28 UTC 2018 aarch64 aarch64 aarch64 GNU/Linux


from /proc/cpuinfo:
processor	: 0
BogoMIPS	: 200.00
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x43
CPU architecture: 8
CPU variant	: 0x1
CPU part	: 0x0a1
CPU revision	: 1

**Comment by mrhillsman** [comment]
@gdams @smlambert @vielmetti I was finally able to get centos image built - and working which was the critical part - so any OpenStack based cloud at least facilitated by OpenLab can provide centos7 now as well. I have four ready to handover; not sure if @gdams needs to do any additional setup.

**Comment by mrhillsman** [comment]
CentOS VMs (4) have been handed over to @gdams

**Comment by gdams** [comment]
ubuntu16.04 and 18.04 has been added. just waiting to hear back from @mrhillsman about the centos7 machines

**Comment by gdams** [comment]
missing ant so working on this now
