### ISSUE TITLE
Setup ansible tags to remove build prereqs

### ISSUE THREAD

**Issue by sxa555** [AdoptOpenJDK/openjdk-infrastructure#683]
A likely ever increasing proportion of our machines will be used for testing rather than building. This issue will cover adding tags so that `build_tools` can be excluded for test machines in the same way as we've (partially) implemented `test_tools` to be able to eliminate the test prereqs for ease of machine setup by third parties.

While adding the build prereqs to the test machines should not inherently be a problem, it is desirable to test on as "clean" a machine as possible in order to ensure that there aren't any rogue extra dependencies that might mask the need for documentation on any underlying prerequisites that we don't know about.

**Comment by Haroon-Khel** [comment]
Currently, many of the tasks in the Common are already tagged with `build_tools` thankfully. Its just a matter of finding the remaining roles

**Comment by sxa555** [comment]
There are quite a few that are also specific to OpenJ9 builds so we could potentially have `build_tools` and `build_tools_openj9` (anything with `build_tools_openj9` should also have `build_tools` I think). Would also allow people to avoid installing some quite big stuff like the NVidia toolkit.

They are mostly called out in the top level `main.yml`

**Comment by Haroon-Khel** [comment]
Roles that I have tagged with a `build_*` tag:
```
freemarker
NVidia_Cuda_Toolkit
gcc_7
cmake
nasm
adoptopenjdk_install for versions 10, 12 and 13
OpenSSL102
```

The `adoptopenjdk_install` have only `build_tools`, while the rest have both `build_tools` and `build_tools_openj9`.

`cmake` has an additional third, `build_tools_openjfx`

**Comment by Haroon-Khel** [comment]
The packages `zlib-devel` and `perl-devel` were installed manually for the task `GIT_Source` to work

**Comment by Haroon-Khel** [comment]
Installed `expat-devel` for `XML::Parser`

**Comment by Haroon-Khel** [comment]
It should be noted that the above was for running the playbook on a RHEL 7 machine. I am now testing the playbook on Ubuntu 16 and 18.
Manually installed `unzip` for Ubuntu 18

**Comment by sxa555** [comment]
> Any thoughts would be appreciated

Yep I think that's ok. I thought `cmake` was required by OpenJ9 builds too but that may never had got implemented - we can verify tomorrow (Or get @Willsparker to run a Vagrant test with a draft PR that removes the `cmake` role!)

**Comment by Willsparker** [comment]
On it : https://ci.adoptopenjdk.net/job/VagrantPlaybookCheck/329/

**Comment by Haroon-Khel** [comment]
I've also created a draft pr, https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/1100, which contains my progress so far. I have successfully tested on RHEL 7, SLES 12 and Ubuntu 16 and 18 x86_64 fyre machines

**Comment by Willsparker** [comment]
Yep, according to the playbook check, cmake isn't a dependency for building openj9 (at least not for jdk8)

**Comment by Haroon-Khel** [comment]
This issue can be closed as per the merged pull request https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/1100
