### ISSUE TITLE
Reduce Jenkins Logging

### ISSUE THREAD

**Issue by karianna** [AdoptOpenJDK/openjdk-infrastructure#690]
Could be related to https://issues.jenkins-ci.org/browse/JENKINS-29490. At least the numbers would match roughly.

not sure they have a solution but the workaround of `-Dhudson.DNSMultiCast.disabled=true`

4 replies
sxa [16 minutes ago]
Worth a shot - surprised it's only just shown up though, but I'll add it on the assumption it's not likely to make anything worse

johno [15 minutes ago]
looking at related logs others seem to say it will happen when the network is broken

johno [15 minutes ago]
*related bugs

johno [14 minutes ago]
pretty impressive this seems to have been an open issue since atleast 2011

**Comment by sxa555** [comment]
Have also covered in #689 - do you anticipate doing anything more under this issue now that the new parameter has been added?

**Comment by karianna** [comment]
Nope, closing
