### ISSUE TITLE
Configure issue in test-packet-ubuntu1604-x64-1 results test failure for RC1 build

### ISSUE THREAD

**Issue by archanaNogriya** [AdoptOpenJDK/openjdk-infrastructure#692]
IPV6 and Intel 6 test is failing in this particular machine all the time test-packet-ubuntu1604-x64-1.
To see the pattern: https://ci.adoptopenjdk.net/job/openjdk8_j9_openjdktest_x86-64_linux/

In the above link, job https://ci.adoptopenjdk.net/job/openjdk8_j9_openjdktest_x86-64_linux/433/ & 436 fails on these tests,
-- | --
java/net/Inet6Address/B6206527.java.B6206527 | 0.34 sec | 1
java/net/ipv6tests/B6521014.java.B6521014 | 0.44 sec | 1
java/net/ipv6tests/UdpTest.java.UdpTest

However, the same job runs on test-packet-ubuntu1604-x64-2 it all passes in other jobs listed. and this is xlinux plateform 

Looks like, related to machine configure issue rather than tests issue.

**Comment by sxa555** [comment]
@archanaNogriya Was that supposed to be a table? ;-)

Build 433 - Packet 1 - fail
Build 434 - Softlayer 1 - pass
Build 435 - Softlayer 1 - pass
Build 436 - Scaleway 1 - fail
Build 437 - Packet 2 - success

I can see this in the log - are there any more detailed logs from the execution?

```

06:25:13 ACTION: main -- Failed. Execution failed: `main' threw exception: java.net.BindException: Cannot assign requested address (Bind failed)
06:25:13 REASON: Assumed action based on file name: run main B6206527 
06:25:13 TIME:   0.278 seconds
06:25:13 messages:
06:25:13 command: main B6206527
06:25:13 reason: Assumed action based on file name: run main B6206527 
```

**Comment by archanaNogriya** [comment]
@sxa555 absolutely and a table is more descriptive, see below.
439 - failed  - Running on test-scaleway-ubuntu1604-x64-1 : failed 	java/rmi/dgc/dgcImplInsulation/DGCImplInsulation.java.DGCImplInsulation
438 - passed - Running on test-packet-ubuntu1604-x64-3
437 -passed - Running on test-packet-ubuntu1604-x64-2
436 -failed - Running on test-scaleway-ubuntu1604-x64-1 3 earlier test failure ipv6 and intel6
435 -passed - Running on test-softlayer-ubuntu1604-x64-1


I am trying to find artifacts which might have more logs to see what is causing this particular system "test-scaleway-ubuntu1604-x64-1" failure.

also, I see in console.log this error, looks like memory issue, which might be causing this failures?
07:02:17 [2019-01-30 07:02:17,655] Agent[0]: stderr: JVMDUMP013I Processed dump event "systhrow", detail "java/lang/OutOfMemoryError".
07:02:19 [2019-01-30 07:02:18,642] Agent[0]: stderr: JVMDUMP039I Processing dump event "systhrow", detail "java/lang/OutOfMemoryError" at 2019/01/30 07:02:18 - please wait.
07:02:19 [2019-01-30 07:02:18,643] Agent[0]: stderr: JVMDUMP032I JVM requested Heap dump using '/home/jenkins/workspace/openjdk8_j9_openjdktest_x86-64_linux/jvmtest/openjdk_regression/work/scratch/0/heapdump.20190130.070218.19171.0005.phd' in response to an event
07:02:19 [2019-01-30 07:02:19,060] Agent[0]: stderr: JVMDUMP010I Heap dump written to /home/jenkins/workspace/openjdk8_j9_openjdktest_x86-64_linux/jvmtest/openjdk_regression/work/scratch/0/heapdump.20190130.070218.19171.0005.phd
07:02:19 [2019-01-30 07:02:19,060] Agent[0]: stderr: JVMDUMP032I JVM requested Java dump using '/home/jenkins/workspace/openjdk8_j9_openjdktest_x86-64_linux/jvmtest/openjdk_regression/work/scratch/0/javacore.20190130.070218.19171.0006.txt' in response to an event
07:02:19 [2019-01-30 07:02:19,096] Agent[0]: stderr: JVMDUMP010I Java dump written to /home/jenkins/workspace/openjdk8_j9_openjdktest_x86-64_linux/jvmtest/openjdk_regression/work/scratch/0/javacore.20190130.070218.19171.0006.txt
07:02:19 [2019-01-30 07:02:19,099] Agent[0]: stderr: JVMDUMP032I JVM requested Snap dump using '/home/jenkins/workspace/openjdk8_j9_openjdktest_x86-64_linux/jvmtest/openjdk_regression/work/scratch/0/Snap.20190130.070218.19171.0007.trc' in response to an event
07:02:19 [2019-01-30 07:02:19,099] Agent[0]: stderr: JVMDUMP010I Snap dump written to /home/jenkins/workspace/openjdk8_j9_openjdktest_x86-64_linux/jvmtest/openjdk_regression/work/scratch/0/Snap.20190130.070218.19171.0007.trc
07:02:19 [2019-01-30 07:02:19,100] Agent[0]: stderr: JVMDUMP013I Processed dump event "systhrow", detail "java/lang/OutOfMemoryError".
07:02:20 [2019-01-30 07:02:20,073] Agent[0]: stderr: JVMDUMP039I Processing dump event "systhrow", detail "java/lang/OutOfMemoryError" at 2019/01/30 07:02:20 - please wait.

**Comment by sxa555** [comment]
The scaleway box does have half the amount of RAM as the others (4GB vs 8GB)

**Comment by sxa555** [comment]
Can you run a test with just that one test case in isolation on the scaleway machine?

**Comment by sxa555** [comment]
I'm assuming the issue on the packet-1 machien was different?

**Comment by sxa555** [comment]
They all seem to have some level of IPv6 set up.

**Comment by archanaNogriya** [comment]
Hi @sxa555 sorry for the delay, was caught up on something else with priority.

I have just run this job which is running only java/net in the same machine.

**Comment by sxa555** [comment]
Looks like it failed to build something on there:
```
12:44:37 cc   setup_.o   -o setup_
12:44:37 cc: error: setup_.o: No such file or directory
12:44:37 cc: fatal error: no input files
12:44:37 compilation terminated.
12:44:37 <builtin>: recipe for target 'setup_' failed
12:44:37 make: *** [setup_] Error 1
12:44:37 make: Leaving directory '/home/jenkins/workspace/Grinder/openjdk-tests/openjdk_regression'
```

**Comment by sxa555** [comment]
@archanaNogriya What's the status of this? The last error message you posted didn't appear to be anything to do with the configuration of the machine as far as I can tell

**Comment by archanaNogriya** [comment]
@sxa555 I think this has not been reported again so let's close this.

**Comment by sxa** [comment]
> Looks like it failed to build something on there:
> 
> ```
> 12:44:37 cc   setup_.o   -o setup_
> 12:44:37 cc: error: setup_.o: No such file or directory
> 12:44:37 cc: fatal error: no input files
> 12:44:37 compilation terminated.
> 12:44:37 <builtin>: recipe for target 'setup_' failed
> 12:44:37 make: *** [setup_] Error 1
> 12:44:37 make: Leaving directory '/home/jenkins/workspace/Grinder/openjdk-tests/openjdk_regression'
> ```

For my own reference, this happens if you specify a `CUSTOM_TARGET` but not a `TARGET` parameter in grinder
