### ISSUE TITLE
Redirect javacore etc. files on AIX so not on ramdisk

### ISSUE THREAD

**Issue by sxa** [AdoptOpenJDK/openjdk-infrastructure#693]
Hitting issues with the core files. Cleared up about 10Gb today. Need to either move them or adjust the jobs so that they clear up after each run.

`rm Snap* javacore* heapdump* core*`

**Comment by sxa555** [comment]
https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/693 removes `rm -f /ramdisk0/build/Snap.*.trc`  `/ramdisk0/build/core.*.dmp`  `/ramdisk0/build/heapdump.*.phd`  `/ramdisk0/build/javacore.*.txt` so while tyhis is a temporary workaround we need a better solution. @sej-jackson Have you gone back to look at this?

**Comment by sxa555** [comment]
Not sure what that link in the start of the previous comment was but it should have been https://ci.adoptopenjdk.net/view/Tooling/job/Monitor_AIX_ramdisks which searches for and deleted the core files in that location

**Comment by aixtools** [comment]
This can probably be closed - as far as it relates to /ramdisk*

Project Monitor_AIX_ramdisks
DISABLED AS WE NO LONGER USE RAMDISKS ON AIX BUILD MACHINES

However, if you would like me to look into managing core dumps - create a new issue with a clear description of the current issue.

**Comment by aixtools** [comment]
@sxa - can this be closed (as fixed/no longer relevant)?

**Comment by sxa** [comment]
There was a few situations where core files were ending up in Jenkins home dir I think but I don't think that's still a problem, so yes I'm happy to close now
