### ISSUE TITLE
JTReg IPV6 tests consistently failing on Scaleway Linux test machines

### ISSUE THREAD

**Issue by ben-walsh** [AdoptOpenJDK/openjdk-infrastructure#694]
See issue https://github.com/eclipse/openj9/issues/4564.

The test results imply a difference in IPV6 configuration between the Scaleway and Packet Linux test machines.

**Comment by Haroon-Khel** [comment]
I have ran both tests on the test Scaleway machine, and both consistently return successes. 
The standard output for the java/net/Inet6Address/B6206527.java test is:
```
trying LL addr: /fe80:0:0:0:dc2b:50ff:fe3f:8001%eth0
trying LL addr: /fe80:0:0:0:dc2b:50ff:fe3f:8001
```
while the standard out for the java/net/ipv6tests/B6521014.java test is:
`Using /fe80:0:0:0:dc2b:50ff:fe3f:8001`
both of which are consistent with the ipv6 configuration of the test-scaleway-ubuntu1604-x64-1 machine.

I will run the tests once more as a check before closing this issue

**Comment by Haroon-Khel** [comment]
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1175/testReport/
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1174/testReport/

**Comment by sxa555** [comment]
Closing as unreproducible now based on the above analysis :-) Thanks @Haroon-Khel !
