### ISSUE TITLE
cmake doesn't build via ansible on RHEL69

### ISSUE THREAD

**Issue by sxa555** [AdoptOpenJDK/openjdk-infrastructure#696]
Discovered on test-softlayer-rhel69-x64-1
```
Error when bootstrapping CMake:\nCannot find a C++ compiler supporting C++11 on this system.
Please specify one using environment variable CXX
```
Exporting the following allows it to work - these just need added to the environment before building on RHEL/CentOS69:
```
export CXX=/usr/local/gcc/bin/g++-7.3
```
Was bumped up from 3.7.2 to 3.11.4 under https://github.com/AdoptOpenJDK/openjdk-infrastructure/commit/9db62f7cba5a9acb986e71503816b2f2e985d4d9 for OpenJFX build

**Comment by Willsparker** [comment]
Running the `ansible-playbook` command as `sudo` (which is required to complete the Common tasks) causes gcc_7 to be put in `/opt/rh/devtoolset-7/root/usr/bin/gcc`. When adding `&& export CXX=/opt/rh/devtoolset-7/root/usr/bin/gcc` to the cmake task "Running ./configure & make for cmake", the above error message still shows.

**Comment by Willsparker** [comment]
When running the individual commands in the above task, I get as far as `PATH=/opt/gcc-4.8.5/bin:$PATH make -j`. The command initially failed as the VM ran out of memory, so having put that up, and running the same command, this error message is as follows:

```
...
libcmsys.a(SystemInformation.cxx.o): In function `cmsys::SystemInformation::~SystemInformation()':
SystemInformation.cxx:(.text+0x19c): undefined reference to `operator delete(void*, unsigned long)'
collect2: error: ld returned 1 exit status
make[2]: *** [Source/kwsys/cmsysTestsCxx] Error 1
make[1]: *** [Source/kwsys/CMakeFiles/cmsysTestsCxx.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 85%] Built target CMakeLib
make: *** [all] Error 2
```

**Comment by Willsparker** [comment]
On a completely new `git clone` and vagrant VM of CentOS6, the playbook has successfully installed cmake, seemingly without issue.

**Comment by sxa555** [comment]
Looks ok ... Happy to close unless this recurs
