### ISSUE TITLE
Ubuntu 16.04 arm32 playbook issues

### ISSUE THREAD

**Issue by sxa555** [AdoptOpenJDK/openjdk-infrastructure#697]
`openjdk-7-jdk` missing
`Chown /usr/lib/jvm/jdk-9.*` in `adoptopenjdk9` role doesn't work as directory is `/usr/lib/jvm/jdk-9+181`

**Comment by sxa555** [comment]
No particularly high priority on this one Will, but if you want an excuse to play with a raspberry pi, this could be your chance :-)

**Comment by sxa555** [comment]
ping @Willsparker - any update on this?

**Comment by Willsparker** [comment]
Not yet - I'll prioritise this tomorrow when I have access to the pi :)

**Comment by Willsparker** [comment]
Okay, I've managed to run through the playbook on Ubuntu1804 armv7l, with only the `adoptopenjdk_install` role being an issue as doesn't like the architecture being called `armv7l`. A fix for that will be to just add an additional role specifically for armv7l / armhf

The `chown` issue is no longer relevant as the `adoptopenjdk9` role isn't there anymore.

As for `openjdk-7-jdk` missing, that is unfortuantely still true, even when adding the `ppa:openjdk-r/ppa` repo. However, I'd ask is this entirely necessary as we're able to build with `JDK8` ? @sxa555

**Comment by sxa555** [comment]
Yeah under the circumstances I'm ok with just JDK8 being on there (for Ubuntu 18+) I would normally expect `arm` as the descriptor to mean arm32
