### ISSUE TITLE
Request to install AIX Asian Locales

### ISSUE THREAD

**Issue by toshiona** [AdoptOpenJDK/openjdk-infrastructure#704]
For MBCS (Internationalization) tests, we need AIX test environment to be installed the following filesets. They are in AIX Base OS. Because of handling of licensed files, Ansible playbook is not suitable (Ref #657).

I've asked this request in Slack channel, and this issue is for tracking purpose.

bos.iconv.*
bos.loc.com.CN
bos.loc.com.JP
bos.loc.com.utf
bos.loc.iso.*
bos.loc.pc.*
bos.loc.utf.JA_JP
bos.loc.utf.KO_KR
bos.loc.utf.ZH_CN
bos.loc.utf.ZH_TW

**Comment by toshiona** [comment]
Is it possible to ask OSUOSL the situation?

**Comment by karianna** [comment]
I've asked on Slack

**Comment by toshiona** [comment]
Thanks!

**Comment by sxa555** [comment]
@toshiona I'm not sure where `bos.iconv` or `bos.loc.pc` come from, but there is `bos.iconv.com` which is already on the systems and is presumably what has `/usr/bin/iconv` already on the system. Is that ok?

**Comment by toshiona** [comment]
@sxa555 Sorry for your confusion. I intended all packages in bos.iconv group and others. bos.iconv.com is a part of them, but we need other packages as well. I updated the top description. These filesets should be in AIX base OS DVD vol 1 or 2.

By the way, if you are using smit, "smit install_all" shortcut can list bos.loc filesets.

**Comment by sej-jackson** [comment]
Done - locales now installed are:
For 7.1:
```
locale -a
C
POSIX
JA_JP.UTF-8
JA_JP
Ja_JP.IBM-932
Ja_JP.IBM-943
Ja_JP
KO_KR.UTF-8
KO_KR
ZH_CN.UTF-8
ZH_CN
ZH_TW.UTF-8
ZH_TW
Zh_TW.big5
Zh_TW
en_US.8859-15
en_US.ISO8859-1
en_US
ja_JP.IBM-eucJP
ja_JP.UTF-8
ja_JP
ko_KR.IBM-eucKR
ko_KR.UTF-8
ko_KR
zh_CN.IBM-eucCN
zh_CN
zh_Hans_CN.UTF-8
zh_Hant_TW.UTF-8
zh_TW.IBM-eucTW
zh_TW
```
and for 7.2:
```
locale -a
C
POSIX
JA_JP.UTF-8
JA_JP
Ja_JP.IBM-943
Ja_JP
KO_KR.UTF-8
KO_KR
ZH_CN.UTF-8
ZH_CN
ZH_TW.UTF-8
ZH_TW
Zh_TW.big5
Zh_TW
en_US.8859-15
en_US.IBM-858
en_US.ISO8859-1
en_US
ja_JP.IBM-eucJP
ja_JP.UTF-8
ja_JP
ko_KR.IBM-eucKR
ko_KR.UTF-8
ko_KR
zh_CN.IBM-eucCN
zh_CN
zh_Hans_CN.UTF-8
zh_Hant_TW.UTF-8
zh_TW.IBM-eucTW
zh_TW
```
