### ISSUE TITLE
Ability to configure alternative SDK bootsdk installations for AIX

### ISSUE THREAD

**Issue by jdekonin** [AdoptOpenJDK/openjdk-infrastructure#708]
It would be nice to be able to use a parameter to select either hotspot or openj9 sdks to be installed.  OpenJ9 project would prefer to use OpenJ9 as the bootjdks.  I propose that the default be hotspot based on variable definition that can be modified at runtime.

**Comment by sxa555** [comment]
If this is AIX specific I'd be happy to make OpenJ9 the default on AIX for all builds. Shouldn't negatively impact others. Not sure if there's a specific reason why they want it though over "nice to be able to"

**Comment by karianna** [comment]
Is Hotspot not supported on AIX? I assumed it was.

**Comment by jdekonin** [comment]
Hotspot is supported on AIX.  The playbook is defaulting to OpenJ9.  #713 partially resolves.  @HusainYusufali can you update for JDK10 and 11 as well.  I should've caught that in the initial review sorry.  While you are touching the JDK11 section(s), can you please clean up the duplication?  Thanks.

**Comment by karianna** [comment]
I'm OK swapping between the Eclipse OpenJ9 and Hotspot boot JDK's but as a general philosophy, I think that we should default to Hotspot unless there's a compelling reason to do otherwise.  Cuts down a source of difference.  Happy to be overruled if OpenJ9 should have an OpenJ9 boot JDK

**Comment by HusainYusufali** [comment]
AIX is not supported by hotspot on JDK 10 & 11 as shown by trying to download the jdk from the following 2 links:

https://api.adoptopenjdk.net/v2/binary/releases/openjdk10?openjdk_impl=hotspot&os=aix&arch=ppc64&release=latest&type=jdk
https://api.adoptopenjdk.net/v2/binary/releases/openjdk11?openjdk_impl=hotspot&os=aix&arch=ppc64&release=latest&type=jdk

This is why OpenJ9 is the default for JDK 10 & 11 on AIX. Also, the pull request #718 has been submitted to remove the duplicate JDK 11 task.

**Comment by sxa555** [comment]
@karianna Technically there's no problems using either HotSpot or OpenJ9 as the boot JVM, although for s390x I think there are some significant performance benefits to using the OpenJ9 one and the OpenJ9 team did request that we switch, but I'm not sure what the driver was for this request on AIX.

**Comment by jdekonin** [comment]
For this request it was about determining how it would work and getting the code in place such that future merging roles with that of unix.  The current sdk variant for AIX is openj9, but that isn't the case for all platforms.

Cleanup and merges are complete.
