### ISSUE TITLE
Mac OS X 10.12.6+ machine required for Java 12 builds

### ISSUE THREAD

**Issue by karianna** [AdoptOpenJDK/openjdk-infrastructure#711]

**Comment by gdams** [comment]
shall we kill one of the JCK mac minis and re provision it as 10.12?

**Comment by karianna** [comment]
> shall we kill one of the JCK mac minis and re provision it as 10.12?

Go for it.

**Comment by gdams** [comment]
machine provisioned. Will try and run ansible on it soon

**Comment by karianna** [comment]
> machine provisioned. Will try and run ansible on it soon

Great! Are our Mac OS X ansible scripts PRD ready?

**Comment by jdekonin** [comment]
@cwillhelm has a change in progress #614, otherwise not really.

**Comment by lumpfish** [comment]
Do we have an estimate as to when the machine will be ready for building jdk12?

**Comment by gdams** [comment]
@lumpfish can we close this?

**Comment by sxa555** [comment]
@gdams Can you clarify which machine has been set up for this or why else you think it needs to be closed.

**Comment by gdams** [comment]
closing as inventory has been updated
