### ISSUE TITLE
Ability to configure alternative SDK bootsdk installations for Windows

### ISSUE THREAD

**Issue by jdekonin** [AdoptOpenJDK/openjdk-infrastructure#715]
It would be nice to be able to use a parameter to select either hotspot or openj9 sdks to be installed. OpenJ9 project would prefer to use OpenJ9 as the bootjdks. I propose that the default be hotspot based on variable definition that can be modified at runtime.

Same change as #713 should work nicely.

**Comment by HusainYusufali** [comment]
Pull request #742 opened to add this feature
