### ISSUE TITLE
add new linux test hosts

### ISSUE THREAD

**Issue by gdams** [AdoptOpenJDK/openjdk-infrastructure#720]
4 x centos 7
4 x ubuntu 16.04
4 x debian 8

FYI @AdoptOpenJDK/testing

**Comment by gdams** [comment]
closing

**Comment by sxa555** [comment]
@gdams Can you add the hostnames produced by this into the ticket and also provide the details somewhere for others to be able to log in. Reopening until access is provided.

**Comment by sxa555** [comment]
Also doesn't look like they're in the inventory

**Comment by gdams** [comment]
@sxa555 godaddy access is now in the secrets repo
