### ISSUE TITLE
unzip command fails on test-openlab-ubuntu1804-armv8-1 

### ISSUE THREAD

**Issue by Mesbah-Alam** [AdoptOpenJDK/openjdk-infrastructure#722]
Test builds fails on`test-openlab-ubuntu1804-armv8-1` with following error:  

```
16:12:58  unzip file: jdk20190308cr.zip ...
16:12:58  ./openjdk-tests/get.sh: line 175: unzip: command not found
```

https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1208/console

Likely other newly added aarch64 [machines](https://ci.adoptopenjdk.net/label/hw.arch.aarch64/) also need to be updated with the required software. 

Note: 
The problem is not seen on `test-packet-armv8-ubuntu-16-04` : https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1187/console 
It is also not seen on `test-openlab-ubuntu1604-armv8-4 `:  https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1210/console

**Comment by gdams** [comment]
added unzip to all the new aarch64 machines

**Comment by karianna** [comment]
@gdams How was this added?  Through Ansible?

**Comment by sxa555** [comment]
@karianna The new machines have not been subject to the standard full ansible playbooks

**Comment by karianna** [comment]
> @karianna The new machines have not been subject to the standard full ansible playbooks

OK @gdams - As a general rule let's run the playbook or raise an issue for the package to be added to the playbook if it's missing.
