### ISSUE TITLE
test-godaddy-debian8-x64-2 missing docker

### ISSUE THREAD

**Issue by smlambert** [AdoptOpenJDK/openjdk-infrastructure#723]
https://ci.adoptopenjdk.net/computer/test-godaddy-debian8-x64-2/

From recent job https://ci.adoptopenjdk.net/view/Test_all/job/openjdk11_j9_externaltest_x86-64_linux/155/console

20:46:48  BUILD FAILED
20:46:48  /home/jenkins/workspace/openjdk11_j9_externaltest_x86-64_linux/openjdk-tests/TestConfig/scripts/build_test.xml:71: The following error occurred while executing this line:
20:46:48  /home/jenkins/workspace/openjdk11_j9_externaltest_x86-64_linux/openjdk-tests/thirdparty_containers/build.xml:43: Execute failed: java.io.IOException: **Cannot run program "docker"** (in directory "/home/jenkins/workspace/openjdk11_j9_externaltest_x86-64_linux/openjdk-tests/thirdparty_containers"): error=2, **No such file or directory**
20:46:48  	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
20:46:48  	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)

For now, I will remove the sw.tool.docker label from this machine to avoid sending external test jobs (which require docker) to this machine.

**Comment by karianna** [comment]
I'm assuming the docker install wasn't part of the ansible playbook - @gdams ?

**Comment by sxa555** [comment]
@karianna The standard full playbooks were not used to set up these machines

**Comment by karianna** [comment]
@gdams Can you raise a separate issue for the missing docker package in our playbooks?  I think there was an issue with installing it right?

**Comment by gdams** [comment]
this issue is to do with the fact that the playbooks don't currently install docker on debian. Will close and create an issue to cover this.
