### ISSUE TITLE
Ant missing on (some) newly added aarch64 machines

### ISSUE THREAD

**Issue by Mesbah-Alam** [AdoptOpenJDK/openjdk-infrastructure#726]
The following newly added aarch64 machines have been found to not have Ant: 

test-openlab-ubuntu1804-armv8-1 
test-openlab-ubuntu1604-armv8-​1
test-openlab-ubuntu1804-armv8-2 
test-openlab-ubuntu1604-armv8-2

Likely some of the other newly added aarch64 machines have Ant missing as well. test-openlab-ubuntu1604-armv8-3 and test-openlab-ubuntu1604-armv8-4 seem fine (grinders pass on those 2 machines) 

This issue is raised to ensure we have Ant installed on all new aarch64 machines. 
 
Error: 

```
15:21:58  ant -f ./src/build_envInfo.xml -DJAVA_BIN=/home/jenkins/workspace/openjdk11_hs_systemtest_aarch64_linux/openjdkbinary/j2sdk-image/bin -DJAVAC=/home/jenkins/workspace/openjdk11_hs_systemtest_aarch64_linux/openjdkbinary/j2sdk-image/bin/javac
15:21:58  make: ant: Command not found
15:21:58  run_configure.mk:37: recipe for target 'testconfig' failed
15:21:58  make: *** [testconfig] Error 127
```

https://ci.adoptopenjdk.net/view/Test_system/job/openjdk11_hs_systemtest_aarch64_linux/134/console

**Comment by Mesbah-Alam** [comment]
FYI : @gdams  @sxa555

**Comment by sxa555** [comment]
I do not have access to the openlab systems ... @gdams @karianna Can these credentials be added somewhere please? Assigning to gdams to resolve the above issue since he set up the box

**Comment by Mesbah-Alam** [comment]
This is causing aarch64 system test builds to fail : https://ci.adoptopenjdk.net/view/Test_system/job/openjdk11_hs_systemtest_aarch64_linux/

I've asked Shelley to remove the tag from this particular machine until this issue is resolved.

**Comment by smlambert** [comment]
I have temporarily removed ci.role.test from this machine so no tests will be sent to it.

**Comment by smlambert** [comment]
ant also missing from:
test-openlab-ubuntu1604-armv8-2
removing ci.role.test label until machine can be updated

test-openlab-ubuntu1604-armv8-3 and test-openlab-ubuntu1604-armv8-4 seem fine (grinders pass on those 2 machines)

**Comment by Mesbah-Alam** [comment]
@smlambert  `test-openlab-ubuntu1804-armv8-2` is missing ant as well. Could we have tag removed from this one as well?

**Comment by smlambert** [comment]
removed ci.role.test labels from test-openlab-ubuntu1604-armv8-1 and test-openlab-ubuntu1804-armv8-2

**Comment by Mesbah-Alam** [comment]
It seems that, even with 'ci.role.test' removed, Grinder-systemtest jobs are still getting scheduled on  `test-openlab-ubuntu1604-armv8-1`. However, job scheduled on it is still complaining about missing Ant: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder-systemtest/21/console. 

Not sure if it has anything to do with the new Grinder-systemtest job.

**Comment by llxia** [comment]
[openjdk_aarch64_linux ](https://github.com/AdoptOpenJDK/openjdk-tests/blob/master/buildenv/jenkins/openjdk_aarch64_linux) does not have `ci.role.test` set in label.

**Comment by Mesbah-Alam** [comment]
@llxia : thanks for pointing out! I guess we were getting lucky earlier. Added that label to the ARM files: https://github.com/AdoptOpenJDK/openjdk-tests/pull/999

**Comment by gdams** [comment]
@Mesbah-Alam added ant to all the new aarch64 machines. Please confirm if this now works

**Comment by Mesbah-Alam** [comment]
Thanks @gdams. 

Hi @smlambert, could you please re-enable the `ci.role.test` on the following machines? 

```
[test-openlab-ubuntu1804-armv8-1](https://ci.adoptopenjdk.net/computer/test-openlab-ubuntu1804-armv8-1)
[test-openlab-ubuntu1604-armv8-​1](https://ci.adoptopenjdk.net/computer/test-openlab-ubuntu1604-armv8-​1)
[test-openlab-ubuntu1804-armv8-2](https://ci.adoptopenjdk.net/computer/test-openlab-ubuntu1804-armv8-2)
[test-openlab-ubuntu1604-armv8-2](https://ci.adoptopenjdk.net/computer/test-openlab-ubuntu1604-armv8-2)
```

**Comment by smlambert** [comment]
Re-labelling done.

**Comment by Mesbah-Alam** [comment]
@gdams, We have a different issue now: 

The same test works on `test-packet-armv8-ubuntu-16-04` : https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder-systemtest/29/consoleFull

But fails on the newly enabled machine ` test-openlab-ubuntu1604-armv8-2`: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder-systemtest/34/console

Error: 

```
15:16:21    [taskdef] Could not load definitions from resource net/sf/antcontrib/antlib.xml. It could not be found.
15:16:21       [echo]  JAVA_BIN is /home/jenkins/workspace/Grinder-systemtest/openjdkbinary/j2sdk-image/bin 
```

Note, in the working case, we have: ` Ant(TM) version 1.10.5 `, 
In the failing case we have: `Ant(TM) version 1.9.6`

I think we need 1.10.5 or later on all machines.

**Comment by sxa555** [comment]
Related: Machine definition was in #680

**Comment by gdams** [comment]
all openlab machines have been removed so this is now longer an issue. closing
