### ISSUE TITLE
Install IcedTea-Web pre-reqs on new Windows build machine

### ISSUE THREAD

**Issue by charliegracie** [AdoptOpenJDK/openjdk-infrastructure#738]
Building IcedTea-Web on Windows requires the following packages:

- [x] cygwin
- [x] preinstalled jdk 
- [ ] tagsoup
- [ ] mslinks 
- [ ] wixgen
- [x] wix
- [x] rust
- [x] cargo
- [ ] rhino

Would it be possible to get the required packages installed on a Windows machine?  I have captured the install instructions below for packages I believe are not already installed or in the Ansible playbooks.  I will create a PR to add them to the Ansible playbooks.

For the required jar files below the common folder that IcedTea-Web looks in is `/usr/share/java/`. If possible it would be great if we could put them all in that folder as it would make it easy to check to see if the requirements are there.

Since the Windows machines can compile OpenJDK I believe cygwin and a JDK are available.

tagsoup is a jar called tagsoup.jar which can be downloaded [here](http://vrici.lojban.org/~cowan/XML/tagsoup/tagsoup-1.2.1.jar). IcedTea-Web configure expect this file to be located in `/usr/share/java/tagsoup.jar` or `/usr/local/share/java/tagsoup.jar` so if it could be placed in either of those locations it would be ideal. If it can not put in either of those locations the location can be specified via an option to configure.

mslinks is a jar called mslinks.jar which can be downloaded [here](http://central.maven.org/maven2/com/github/vatbub/mslinks/1.0.5/mslinks-1.0.5.jar). IcedTea-Web configure expect this file to be located in `/usr/share/java/mslinks.jar` or `/usr/local/share/java/mslinks.jar` so if it could be placed in either of those locations it would be ideal. If it can not put in either of those locations the location can be specified via an option to configure.

wixgen is a jar called wixgen.jar which can be download [here](https://github.com/akashche/wixgen/releases/download/1.7/wixgen.jar). IcedTea-Web configure expects this file to be located in `/usr/share/java/wixgen.jar` or `$WIX_TOOLSET_DIR/wixgen.jar` or `$WIX_TOOLSET_DIR/../wixgen.jar`. I do not see any way to override where it looks.

Rust can be installed via the instructions in the Ansible playbook. I believe cargo is installed with Rust.

rhino is a jar called js.jar which can be download [here](http://ftp.mozilla.org/pub/mozilla.org/js/rhino1_6R7.zip). IcedTea-Web configure expects this file to be located in `/usr/share/java/js.jar` or `/usr/share/rhino-1.6/lib/js.jar`. I do not see any way to override where it looks. You can unzip the file above with this command to get the jar file:
`unzip -j -d /usr/share/java rhino1_6R1.zip rhino1_6R1/js.jar`

**Comment by karianna** [comment]
@sxa555 I'm tempted to say we should spin up specific hosts just for Icedtea-web and have it in its own playbook...

**Comment by gdams** [comment]
We've got plenty of windows 2016 so could build it on that?

**Comment by charliegracie** [comment]
I have not personally tried to build it on Windows 2016. @judovana have you tried?

**Comment by sxa555** [comment]
Yeah with there being so many additional things I'd prefer to do it in a standalone machine at least for now especially given we don't have a tried and tested playbook for it - @gdams can you allocate on for this please? I was expecting this work item to just be a rust installation :-)

**Comment by charliegracie** [comment]
The other 4 things are just simple jar files I believe. Any update? I could progress by just downloading them as part of the build until the machine can be configured.

**Comment by sxa555** [comment]
@charliegracie Have you added the other jar files to the playbook yet? I'd be reluctant to approve anything that downloaded things to a location outside the build workspace (which from your comment sounds like it is required).

**Comment by sxa555** [comment]
@charliegracie in order to unblock you I have installed those prereqs on one of the build machines and added an `icedteabuild` tag on the machine that you can use in your job to ensure it gets scheduled on there: https://ci.adoptopenjdk.net/computer/build-softlayer-win2012r2-x64-1/

**Comment by charliegracie** [comment]
Thanks @sxa555. Did those installs include rust? If so can you do a `which rustc` on the machine and tell me the path? Thanks

**Comment by sxa555** [comment]
It's installed as per the playbook, so from the cygwin shell it's `/cygdrive/c/rust/bin/rustc`

**Comment by gdams** [comment]
I've been trying to compile ITW 1.8.x on windows using GH Actions. Currently hitting the following failure:

```bash
Configure IcedTea-Web
configure:7136: error: possibly undefined macro: AC_CACHE_CHECK
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure:8621: error: possibly undefined macro: AC_DEFINE
autoreconf-2.69: autoconf failed with exit status: 1
configure: error: cannot find install-sh, install.sh, or shtool in "." "./.." "./../.."
```

Any idea what the issue might be? 

Link to PR https://github.com/AdoptOpenJDK/IcedTea-Web/pull/761/checks

**Comment by gdams** [comment]
Closing this. We have now ported all ITW builds over to use GH Actions: https://github.com/AdoptOpenJDK/IcedTea-Web/wiki/IcedTea-Web-1.8.x-Release-Guide

**Comment by Haroon-Khel** [comment]
@gdams As per your last comment, if this issue is resolved could you please close it. Thanks 👍🏻
