### ISSUE TITLE
Ansible: Change lib install location for Freetype 32-bit on Windows

### ISSUE THREAD

**Issue by HusainYusufali** [AdoptOpenJDK/openjdk-infrastructure#747]
The location of freetype libraries on windows build scripts is `/cygdrive/c/openjdk/freetype-2.5.3/lib` for 32-bit builds. The real location of the freetype library for 32-bit builds is `/cygdrive/c/openjdk/freetype-2.5.3/lib32`. A symlink is needed to point to this real location

**Comment by sxa555** [comment]
@ali-ince Presumably your recent changes render this irrelevant?

**Comment by ali-ince** [comment]
Yes @sxa555, we can now remove all freetype relevant stuff from the playbook as it's now part of the build.

I can create a PR later today with the relevant changes.

**Comment by karianna** [comment]
Superseded by https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/766
