### ISSUE TITLE
Windows machine for JCK testing

### ISSUE THREAD

**Issue by sxa555** [AdoptOpenJDK/openjdk-infrastructure#75]
We need to run the JCK suite on WIndows and it's access needs to be locked down so it cannot be shared with other jobs.

Needs to have a fast disk (so I'd say SSD) and ideally powerful cores (but doesn't need many of them) so something like 2 core/8Gb/100Gb SSD should suffice. Perhaps 16Gb+ if we decide to use a ramdrive for holding the JCK test suite itself.

Windows version TBD - what do Oracle test on?

**Comment by tellison** [comment]
Waiting for "Windows version TBD"

**Comment by gdams** [comment]
I think that we agreed 2012 R2? I will double check

**Comment by sxa555** [comment]
Gut feel is that that would be a sensible version to go for.

**Comment by gdams** [comment]
I have assigned a Joyent machine to @sxa555 for now. We can review performance and can migrate to another provider if performance is not suitable. Closing for now
