### ISSUE TITLE
Linaro aarch64 machines currently offline

### ISSUE THREAD

**Issue by sxa555** [AdoptOpenJDK/openjdk-infrastructure#753]
Both Linaro machines shown on https://ci.adoptopenjdk.net/label/centos7&&build&&linux&&aarch64/ are currently offline and jenkins is unable to contact them to restart the agent.

**Comment by gdams** [comment]
@sxa I last passed you the linaro openstack details a while back, let me know if you need more assistance.

**Comment by gdams** [comment]
Linaro shut down their US cloud a while back. I missed the email as it went to my IBM address. Working on getting us access again.

**Comment by stooart-mon** [comment]
I've raised "DC-437 Please create account for AdoptOpenJDK in uk.linaro.cloud", emailed Kevin Zhao at Linaro with George on CC.

**Comment by stooart-mon** [comment]
George has the details for accessing the replacement machines.

**Comment by sxa555** [comment]
Memo to self - current limits are as follows:
- 10 instances
- 16 vCPUs
- 32GB RAM
- 512GB storage

Size options:uk.medium (4CPU/8GB/160GB) or uk.large (8CPU,16GB,320GB) Ideally I'd have two of 8CPU, 16GB, 256GB but for now I've set up one of the `uk.large` and the other `uk.medium`

**Comment by sxa555** [comment]
build-linaro-centos76-armv8-1 213.146.141.99
build-linaro-centos76-armv8-2 213.146.141.123

**Comment by sxa555** [comment]
Capacity increased to 640GB of disk so I can have two of the larger ones now. The `-1` machine appears to have fallen off the network but I should be able to recover that, but the other one is now up and running, connected into the jenkins, and has managed to run a couple of builds without any obvious issues: https://ci.adoptopenjdk.net/computer/build-linaro-centos76-armv8-2/

On that basis I'm closing this.
