### ISSUE TITLE
Ansible AWX currently on Ubuntu 14.04 which is out of support

### ISSUE THREAD

**Issue by sxa** [AdoptOpenJDK/openjdk-infrastructure#756]
.... Therefore needs a upgrade to migitate security issues

**Comment by sxa555** [comment]
Failed die to the `/tmp/awxcompose` directory not being correctly regenerated. After a reboot (regardless of whether an upgrade has been performed) the contents of that directory is three subdirectories:
```
root@aoansibleupgrade1:/tmp# ls -l awxcompose
total 16
-rw------- 1 root root  817 Apr 30 09:04 credentials.py
-rw------- 1 root root 1745 Apr 30 09:04 docker-compose.yml
-rw------- 1 root root  201 Apr 30 09:04 environment.sh
-rw------- 1 root root    9 Apr 30 09:04 SECRET_KEY
root@aoansibleupgrade1:/tmp#
```
Obviously, they should be files. After a normal setup there is also a `docker-compose.yml` that's in there.

**Comment by sxa555** [comment]
After discussion with @karianna we had decided to create a new system for this and attempt to rebuild from scratch useful educational process anyway) - @karianna can you arrange for a new system of a similar spec to the existing ansible server to be created?

**Comment by sxa555** [comment]
This requires docker so need to be clear on which is an appropriate hosting provider to be able to progress this (GoDaddy for example has shown problems with network connectivity inside docker images)

**Comment by sxa** [comment]
GoDaddy server provisioned for this at `160.153.250.8` but I want to move it to Ubuntu 20.04 as soon as we can to ensure the longest possible life

**Comment by sxa** [comment]
New server set up with a base ansible installation. Need to ensure setup is documented, hence the final step in this ;-)

Stuff to do
- [x] Acquire test server
- [x] Install AWX
- [ ] Get SSL certificate
- [ ] Add an AWX key to Bastillion
- [ ] Add configurations for the machines
- [ ] Setup backups
- [ ] Setup github authentication
- [ ] Repeat all of the above on a new Ubuntu 20.04 system

**Comment by sxa** [comment]
Failed to get this finalised due to large numbers of build failures and AIX work in the last month - bumping

**Comment by sxa** [comment]
New system now under test (provisioned for now under AWS for experiments as GoDaddy machines still seem to struggle with networking in CentOS8 docker images under an Ubuntu 16.04 host) although at the moment neither the new one or the old (formerly live) one seems capable of parsing the inventory file using the `adoptopenjdk_yaml.py` file so that will need to be resolved before we can progress.

[Access control issue](https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1648)

**Comment by sxa** [comment]
I have the playbook running through on a single host (X64 buid machine 1 which is rarely used now with the move to docker-based x64 builds in most cases) using `--skip-tags adoptopenjdk,.hosts_file` (Arguable `hosts_file` should be included along with `adoptopenjdk` - I'll get that updated

**Comment by sxa** [comment]
Final step held up on deciding where to host it, but otherwise ok.

Also need to document with a policy for getting the password into the windows hosts as it is currently a (visible) password (`ansible_password`) on the template run

**Comment by sxa** [comment]
Having some issues on the final server with the postgres database. Pretty sure I hit issues with this before and I concluded it was password related, but that doesn't seem to be the issue this time

`2020-12-09 22:28:44.627 UTC [46] ERROR:  relation "conf_setting" does not exist at character 158
2020-12-09 22:28:44.627 UTC [46] STATEMENT:  SELECT "conf_setting"."id", "conf_setting"."created", "conf_setting"."modified", "conf_setting"."key", "conf_setting"."value", "conf_setting"."user_id" FROM "conf_setting" WHERE ("conf_setting"."key" = 'LOG_AGGREGATOR_ENABLED' AND "conf_setting"."user_id" IS NULL) ORDER BY "conf_setting"."id" ASC  LIMIT 1`

**Comment by sxa** [comment]
Had multiple instances of this `ECONNRESET` when deploying the latest OpenSSL update onto Windows machines so we may need to adjust a timeout somewhere if we start refreshing windows machines regularly via AWX. By retrying repeatedly it eventually got through on all systems. Noting here for information:
```
TASK [Install OpenSSL-1.1.1i 64-bit (VS2013)] **********************************
task path: /tmp/awx_4467_etxkoqj_/project/ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/OpenSSL/tasks/main.yml:73
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: requests.exceptions.ChunkedEncodingError: ('Connection broken: OSError("(104, \'ECONNRESET\')",)', OSError("(104, 'ECONNRESET')",))
fatal: [build-ibmcloud-win2012r2-x64-1]: FAILED! => {"msg": "Unexpected failure during module execution.", "stdout": ""}
PLAY RECAP *********************************************************************
build-ibmcloud-win2012r2-x64-1 : ok=9    changed=1    unreachable=0    failed=1    skipped=1    rescued=0    ignored=0

**Comment by sxa** [comment]
OK there's a bug that means that AWX doesm't properly initialise itself first time round. Waiting 2½ minutes after running the setup playbook then RE-RUNNING IT then the server will be ready after about four ADDITIONAL minutes.

**Comment by sxa** [comment]
When using cloudflare's proxy support, AWX falls foul of the HSTS support that is enabeld by default on the nginx configuration (as far as I can tell). Unless you disable the `Content-Security-Policy` header in `awx/installer/roles/local_docker/templates/nginx.conf.j2` prior to deploying you will only get a blank page when connecting via a cloudflare proxied AWX.

For reference this is what you will see in the `awx_web` log:


`2020-12-18 01:44:14,063 ERROR    awx {'csp-report': {'blocked-uri': 'https://ajax.cloudflare.com/cdn-cgi/scripts/7089c43e/cloudflare-static/rocket-loader.min.js', 'document-uri': 'https://awx.adoptopenjdk.net/', 'original-policy': "default-src 'self'; connect-src 'self' ws: wss:; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline' https://*.pendo.io; img-src 'self' https://*.pendo.io data:; report-uri https://awx.adoptopenjdk.net/csp-violation/", 'referrer': '', 'violated-directive': 'script-src'}}`

**Comment by sxa** [comment]
Now complete other than authentication required for Vendor_Files
