### ISSUE TITLE
pLinux-LE machine for JCK testing

### ISSUE THREAD

**Issue by sxa555** [AdoptOpenJDK/openjdk-infrastructure#76]
We need to run the JCK suite on pLinux-LE and it's access needs to be locked down so it cannot be shared with other jobs.

Spec-wise something like 2-core, 8Gb RAM and an SSD of around 100Gb would be ideal as that's what we're using for xLinux.

**Comment by gdams** [comment]
closing as `jck-osuosl-ppc64le-ubuntu-16.04-1` and `jck-osuosl-ppc64le-ubuntu-16.04-2` have now been deployed
