### ISSUE TITLE
Tests build got 'No space left on device 08:42:27  > No space left on device' 

### ISSUE THREAD

**Issue by sophia-guo** [AdoptOpenJDK/openjdk-infrastructure#761]
Test builds got ' No space left on device' message on  test-softlayer-ubuntu1604-x64-1

```
08:42:27  * What went wrong:
08:42:27  java.io.IOException: No space left on device
08:42:27  > No space left on device
```
https://ci.adoptopenjdk.net/view/Test_external/job/openjdk8_j9_external_sanity_openliberty-mp-tck_x86-64_linux/21/consoleFull

**Comment by sxa555** [comment]
There is at least 3Gb free on each real filesystem on that machine - is it possible that it's something going wrong inside the container?

**Comment by sxa555** [comment]
`/var/lib/docker` is using about 30Gb on that machine at the moment, although the filesystem still hasb 8Gb free on it.

**Comment by karianna** [comment]
@sxa555 I think some of the test runs may not be cleaning up their docker artifacts.  I also see this:

```
-rw-r--r--   1 root root 5.9G Jan 24 16:50 docker-original.tgz
-rw-r--r--   1 root root 5.2G Jan 24 19:07 docker-original.txz
```

They can be removed I suspect.

**Comment by karianna** [comment]
Cleaned up the files this should be OK now.
