### ISSUE TITLE
Request for access to test-osuosl-ppc64le-ubuntu-16-04-1

### ISSUE THREAD

**Issue by adamfarley** [AdoptOpenJDK/openjdk-infrastructure#763]
To run a test to reproduce a bug that only occurs here, for some reason.

**Comment by sxa555** [comment]
Will add @adamfarley's key onto [the machine](https://ci.adoptopenjdk.net/computer/test-osuosl-ppc64le-ubuntu-16-04-1/) temporarily and disable it in jenkins until resolved.

**Comment by karianna** [comment]
Will close once temp access is revoked.

**Comment by sxa555** [comment]
Adam's key hasn't been working. Will aim to debug with him over the next couple of days.

**Comment by adamfarley** [comment]
Got access. Turns out Windows Putty doesn't like ssh keys with passphrases. Odd.

Anyway, I've completed my test investigation, and this machine can be reenabled.

**Comment by sxa555** [comment]
Access removed again, machine re-enabled and issue 770 created to resolve the discovered issues.
