### ISSUE TITLE
Triplicate definition on Marist SLES12 machine

### ISSUE THREAD

**Issue by sxa555** [AdoptOpenJDK/openjdk-infrastructure#765]
https://ci.adoptopenjdk.net/computer/build-marist-s390x-sles-12
https://ci.adoptopenjdk.net/computer/test-marist-sles12-s390x-1
https://ci.adoptopenjdk.net/computer/test-marist-s390x-sles-12/

I suspect this was intended to be moved from being a build machine (We don't build on SLES) to a test machine but was never quite completed.

FYI @smlambert as discussed let me know if this machine (any of the three definitions :-D is usable to you in it's current state as it would be good to get your zLinux capacity increased with this system

**Comment by sophia-guo** [comment]
Tried with:
https://ci.adoptopenjdk.net/computer/build-marist-s390x-sles-12
https://ci.adoptopenjdk.net/computer/test-marist-sles12-s390x-1
https://ci.adoptopenjdk.net/computer/test-marist-sles12-s390x-1  -->
https://ci.adoptopenjdk.net/computer/test-marist-s390x-sles-12/

Got different failures:
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1457/
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1457/

**Comment by sxa555** [comment]
@sophia-guo Those builds have gone. Can you re-run and capture the error messages in the issue please?

**Comment by smlambert** [comment]
Ran [test on build-marist-s390x-sles-12](https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1534) and [test-marist-s390x-sles-12](https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1535/console) - fails with this error:

18:47:50  ant -f ./src/build_envInfo.xml -DJAVA_BIN=/data/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image/jre/bin -DJAVAC=/data/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image/jre/bin/../../bin/javac
18:47:50  Exception in thread "main" java.lang.UnsupportedClassVersionError: org/apache/tools/ant/launch/Launcher : Unsupported major.minor version 52.0
18:47:50  	at java.lang.ClassLoader.defineClass1(Native Method)
18:47:50  	at java.lang.ClassLoader.defineClass(ClassLoader.java:808)
18:47:50  	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
18:47:50  	at java.net.URLClassLoader.defineClass(URLClassLoader.java:443)
18:47:50  	at java.net.URLClassLoader.access$100(URLClassLoader.java:65)
18:47:50  	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
18:47:50  	at java.net.URLClassLoader$1.run(URLClassLoader.java:349)
18:47:50  	at java.security.AccessController.doPrivileged(Native Method)
18:47:50  	at java.net.URLClassLoader.findClass(URLClassLoader.java:348)
18:47:50  	at java.lang.ClassLoader.loadClass(ClassLoader.java:430)
18:47:50  	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:323)
18:47:50  	at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
18:47:50  	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)
18:47:50  run_configure.mk:37: recipe for target 'testconfig' failed

Should check JAVA_HOME / boot java on the machines (and therefore what Ant is using), also need to check version of Ant on machine and compare with test-marist-sles12-s390x-1.

**Comment by sxa555** [comment]
Default java on the machine was 1.8 but `JAVA_HOME` was pointing at a 1.7. Now fixed, and https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1555/ seems to have passed.

**Comment by karianna** [comment]
@sxa555 This can be closed now?

**Comment by sxa555** [comment]
Not until I decide which two of the three to delete :-)

**Comment by smlambert** [comment]
build-marist-s390x-sles-12 and test-marist-s390x-sles-12 appear to now run tests without incident.

As part of a separate investigation (see https://github.com/eclipse/openj9/issues/5542), I reran a test that was failing on test-marist-sles12-s390x-1.  Test fails consistently on test-marist-sles12-s390x-1, but passes on the others.  One difference, when looking at ulimit info, open files limit on test-marist-sles12-s390x-1 is 1048576, where as on build-marist-s390x-sles-12 is 4096.

(I will add details in 5542 issue).

**Comment by sxa555** [comment]
In light of the above I have deleted the entries for https://ci.adoptopenjdk.net/computer/build-marist-s390x-sles-12 and https://ci.adoptopenjdk.net/computer/test-marist-s390x-sles-12

**Comment by sophia-guo** [comment]
@sxa555 Did you mean deleted the entries as build machines? I wondered if we could create new entries for those two machines as test machines? Before we could fix the configuration issues we could just label the machine without 'ci.role.test'. 

We currently only have two 2 s390 test machines available https://ci.adoptopenjdk.net/label/s390x&&ci.role.test/

And one of them looks not working well. https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/808#issuecomment-508163264

Which actually left us only one machine available.

**Comment by sxa555** [comment]
There is only one machine. It had three definitions in jenkins. I removed two of them

**Comment by sxa555** [comment]
From @sophia-guo:

Running test and got 
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1723/console
```
16:02:01  ant -f ./src/build_envInfo.xml -DTEST_JDK_HOME=/data/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image
16:02:01  Exception in thread "main" java.lang.UnsupportedClassVersionError: org/apache/tools/ant/launch/Launcher : Unsupported major.minor version 52.0
16:02:01  	at java.lang.ClassLoader.defineClass1(Native Method)
16:02:01  	at java.lang.ClassLoader.defineClass(ClassLoader.java:808)
16:02:01  	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
16:02:01  	at java.net.URLClassLoader.defineClass(URLClassLoader.java:443)
16:02:01  	at java.net.URLClassLoader.access$100(URLClassLoader.java:65)
16:02:01  	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
16:02:01  	at java.net.URLClassLoader$1.run(URLClassLoader.java:349)
16:02:01  	at java.security.AccessController.doPrivileged(Native Method)
16:02:01  	at java.net.URLClassLoader.findClass(URLClassLoader.java:348)
16:02:01  	at java.lang.ClassLoader.loadClass(ClassLoader.java:430)
16:02:01  	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:323)
16:02:01  	at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
16:02:01  	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)

```

We'd like to enable this machine for test when all issues are fixed

**Comment by sxa555** [comment]
While the default java on the machine was java8, ant picks `JAVA_HOME` which was pointing at a java 7 directory. Symlink `/etc/alternatives/java_sdk` now adjusted to point at java8 instead of java7 and the Grinder job https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1738/ (a re-run of your failing one) is going through past that point.
