### ISSUE TITLE
Fail to run cmake and protobuf targets from Unix playbook

### ISSUE THREAD

**Issue by jdekonin** [AdoptOpenJDK/openjdk-infrastructure#767]
Attempting to run the specific tags for either ccache or protobuf fail to be found.

This change appears to be what caused the issue;
https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/584

**Comment by sxa555** [comment]
Hmmm yes that's potentially an issue. What's the use case for wanting to run individual ones like that in the playbook?

**Comment by jdekonin** [comment]
I have a machine that is missing protobuf and I don't want to waste time running the entire playbook to get one role.

**Comment by karianna** [comment]
Doesn't the playbook 'skip' everything that's already in place?

**Comment by sxa555** [comment]
@karianna It does but takes a bit longer than is ideal (An issue I'd quite like to look at...)

**Comment by Haroon-Khel** [comment]
The cmake, ccache and protobuf tasks, in their respective roles, are all tagged with cmake, ccache and protobuf respectively. So these specific roles can be run using `--tags "cmake,ccache,protobuf"` in the `ansible-playbook` command. However this will not run the protobuf tasks as the role is not included in the `AdoptOpenJDK_Unix_Playbook/main.yml`, as of the pr mentioned in the first comment.

Are there any plans to add protobuf back into `main.yml`?

**Comment by sxa555** [comment]
Up until a week ago it wasn't required by AdoptOpenJDK but since the JITserver support went into the extensions repository a few days ago it is (Linux/x64 only for now) so yeah I'll chuck in a PR to re-enable it ...

**Comment by Haroon-Khel** [comment]
@jdekonin Protobuf has been added back as a role, so the use of the option `--tags "cmake, ccache, protobuf"` should run only those roles. Is this what you were looking for?

**Comment by jdekonin** [comment]
Yes, although it looks like there is still an extra role to install protobuf on line 52 that needs to be cleaned up.  Its the role in this (current) form that cannot be omitted.

https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/b4c899faa26160d0f5479ef443c5cf478fcee175/ansible/playbooks/AdoptOpenJDK_Unix_Playbook/main.yml#L52

**Comment by sxa555** [comment]
Good point @jdekonin - with the desire to build with GCC7 where possible that needs to be removed now

**Comment by Haroon-Khel** [comment]
The `local_srcinstall` role has been removed as per https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/1102. 
Closing this issue.
