### ISSUE TITLE
zLinux machine for JCK testing

### ISSUE THREAD

**Issue by sxa555** [AdoptOpenJDK/openjdk-infrastructure#77]
We need to run the JCK suite on zLinux and it's access needs to be locked down so it cannot be shared with other jobs.

Spec wise a 2-core, 8Gb, and a fast disk of around 100Gb should be ideal.

**Comment by tellison** [comment]
Which Linux distro do you prefer?  The options are Ubuntu / SLES / Red Hat.

**Comment by sxa555** [comment]
Hmmm that's a good question - but lets go for Ubuntu 16.04 since that matches the platform it's built on

**Comment by gdams** [comment]
@tellison should we be able to get that from Marist or will we need to try and re allocate some of our build machines

**Comment by gdams** [comment]
I have requested two of the above machines from Marist

**Comment by sxa555** [comment]
Any info from Marist on when these will become available @gdams (It's not inherently a blocker as I can use non-public machines for now but just checking the request hasn't got lost)

**Comment by gdams** [comment]
Our current ETA is by the end of this week. Our contact at Marist is trying to speed this up but they are deploying env changes and don't generally like deploying new machines whilst doing this.

**Comment by gdams** [comment]
closing as the machines are now in the JCK farm
