### ISSUE TITLE
Tests build got 'No space left on device 08:42:27 > No space left on device' on test-scaleway-ubuntu1604-x64-1

### ISSUE THREAD

**Issue by sophia-guo** [AdoptOpenJDK/openjdk-infrastructure#777]
All container test builds failed on test-scaleway-ubuntu1604-x64-1 with message '

```
20:27:05  ERROR: [ssh-agent] Could not register BouncyCastle on the remote agent.
20:27:05  java.nio.file.FileSystemException: /tmp/resource-1012398343128323010: No space left on device
20:27:05  	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:91)

```
https://ci.adoptopenjdk.net/view/Test_external/
https://ci.adoptopenjdk.net/view/Test_external/job/openjdk11_hs_external_extended_elasticsearch_x86-64_linux/28/console

We had exactly same issue before on different machine  test-softlayer-ubuntu1604-x64-1 #761

**Comment by sophia-guo** [comment]
With only jenkins permission using 'docker volume ls' I can see there are some docker volumes here. Not sure how much disk space they occupied. 

I've manually done with `docker volume rm $(docker volume ls  -q --filter dangling=true)` hope it helps.

**Comment by sophia-guo** [comment]
If those dangling volumes are the real reason of this issue we need to think about how to delete those volumes either by jenkins regular maintenance or the builds using dockers.

**Comment by sophia-guo** [comment]
Remove Docker dangling volumes didn't help 

https://ci.adoptopenjdk.net/view/work%20in%20progress/job/Grinder_Sandbox/350/console

@sxa555 any idea?

**Comment by sxa555** [comment]
Cleanup done - there were a a lot of old versions of the images kicking around on the machine. Will raise a separate issue for cleaning this up going forward
