### ISSUE TITLE
Policy/process for cleaning up old docker images on machines

### ISSUE THREAD

**Issue by sxa555** [AdoptOpenJDK/openjdk-infrastructure#778]
Regarding https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/777 we need to determine how to deal with old docker images. Each time we do a pull of the current image the previous one gets left on the system and therefore the disk space required is continually expanding storing old images. Other artefacts may also be an issue.

**Comment by sxa555** [comment]
@dinogun Have you implemented enough cleanup that this should no longer be an issue? I remember you made some fixes in this area in the last few weeks

**Comment by dinogun** [comment]
There were some issues with the docker build scripts that would cause docker images to be left over even after the build finished. The cleanup scripts have been updated and I'm no longer seeing this issue.
