### ISSUE TITLE
Linux build requirements for ITW

### ISSUE THREAD

**Issue by charliegracie** [AdoptOpenJDK/openjdk-infrastructure#781]
To complete the builds for ITW on Linux the following packages have to be installed on a CentOS6.9 machine (or RHEL6.9 I guess) that has basic build tools (autoconf, gcc, make, etc.).

There are a few extra requirements but the biggest bottlenecks are Rust and a newer version of pkg-config. With these installed the other requirements can be downloaded to the workspace and they are small so the downloads are very quick.

To install Rust:
```
curl -o rust.tar.gz "https://static.rust-lang.org/dist/rust-1.34.1-x86_64-unknown-linux-gnu.tar.gz"
tar -zxf rust.tar.gz
cd rust-1.34.1-x86_64-unknown-linux-gnu
./install.sh
```

To install a newer version of pkg-config:
```
curl -o pkg-config.tar.gz "https://pkg-config.freedesktop.org/releases/pkg-config-0.29.2.tar.gz"
tar -zxf pkg-config.tar.gz
cd pkg-config-0.29.2
./configure --with-internal-glib
make install
```

I will update with the other requirements in the future when I get the ansible playbook changes ready.

**Comment by sxa555** [comment]
For now, I've installed them on [build-joyent-centos69-x64-1](https://ci.adoptopenjdk.net/computer/build-joyent-centos69-x64-1) which is now tagged with `icedteabuild` to be able to select it. You'll need to put `/usr/local/bin` explicitly at the start of the path to pick up the newer pkgconfig.

I'll leave this open until I've sorted the playbooks as well after we confirm that this is ok.

**Comment by charliegracie** [comment]
Hmm it has the same pkg-config issue.  I think it is because the `pkg.m4` it is finding is the one from the original version of pkg-config and not the new version installed into `/usr/local/...`

**Comment by charliegracie** [comment]
I am not sure how to force it to find the new definitions...

**Comment by sxa555** [comment]
That sounds rather broken if it's not using it's `local` one first :-(

Do you have a pkg-config invocation that I can use to reproduce it?

**Comment by jdekonin** [comment]
You need to setup a PKG_CONFIG_PATH environment variable.  Same problem exists on AIX.

https://askubuntu.com/questions/210210/pkg-config-path-environment-variable

**Comment by charliegracie** [comment]
@jdekonin I thought that might be it too but I do not believe it is.  I tried setting it and it did not resolve the issue.

When the test runs autoconf.sh that script will invoke `aclocal` to find m4 files to be used as automake macros. The issue is the search path for `aclocal` is not related to any particular tool or software package but instead tools install their .m4 files into the proper folder for aclocal ie. `/usr/share/aclocal/*.m4`

The originally installed version of pkg-config installed its pkg.m4 into `/usr/share/aclocal` and that file is found first.  I do not see to be able to prepend a search path using environment variables.  I can append to it but that means it just finds the original one first.

I will keep looking to see if I can force it to use the new install without having to make code changes to ITW or change the default on the machine.

**Comment by charliegracie** [comment]
After looking through a lot of source code and stackoverflow discussions it appears that this type of issue is fairly common.  The solutions are:
1. install the latest version of pkg-config into the default `/usr` instead of `/usr/local/`.
2. install the latest version of automake into the default `/usr` which provides new options for overriding the search paths, etc.
3. install the latest automake (which includes aclocal) into `/usr/local`. This will automagically map the new version of pkg-config as they will both use the same --prefix.
4. Modify the ITW code in ugly ways. 

I think solution #3 would likely be best as it would have the least impact. The latest version of automake is available here:
https://ftp.gnu.org/gnu/automake/

I am trying to get a CentOS 6 machine setup for local testing so I can verify that everything works but that make take a long time.

**Comment by charliegracie** [comment]
By following #3 I only had to add `/usr/local/bin` to the PATH and everything else worked.

**Comment by sxa555** [comment]
Option 3 sounds good as it won't involve changing anything on the original system so I'll look at doing that.

**Comment by charliegracie** [comment]
It works!

**Comment by gdams** [comment]
instructions for installing latest automake:

```bash
wget https://ftp.gnu.org/gnu/automake/automake-1.13.1.tar.gz
tar -xf automake-1.13.1.tar.gz 
cd automake-1.13.1
bash configure
make && make install
rm -rf /usr/local/bin/automake
ln -s /usr/local/bin/automake-1.13 /usr/local/bin/automake
```
