### ISSUE TITLE
Update ansible-lint to v4

### ISSUE THREAD

**Issue by JamieMagee** [AdoptOpenJDK/openjdk-infrastructure#782]
`ansible-lint` has a new major version release, v4, which adds a lot of new default rules.

**Comment by sxa555** [comment]
Assigning to WIll to make any changes needed to make our ansible playbooks compliant

**Comment by Willsparker** [comment]
A quick run through of the Windows and Unix PBs has shown the issues are: 
**Windows:**

- [601] Don't compare to literal True/False 
- [204] Lines should be no longer than 160 chars 
      ^ Not sure if we want this one in there? I know that's set as a warning for `yamlint`

**Unix:** 

- [204] Lines should be no longer than 160 chars
- [504] Do not use 'local_action', use 'delegate_to: localhost'
- [403] Package installs should not use latest
- [301] Commands should not change things if nothing needs doing
- [306] Shells that use pipes should set the pipefail option
- [602] Don't compare to empty string
- [601] Don't compare to literal True/False

Are there any in those lists that we would want to ignore?

**Comment by karianna** [comment]
I'm ambivalent about `204` - I think the rest makes sense to keep

**Comment by sxa555** [comment]
I'm also not sure about fixing versions and avoiding using latest, but I think we've discussed this elsewhere too :-)

**Comment by Willsparker** [comment]
Finished with above PR :-)
