### ISSUE TITLE
Unable to delete test directories on test-azure-win2012r2-x64-1 

### ISSUE THREAD

**Issue by smlambert** [AdoptOpenJDK/openjdk-infrastructure#784]
Urgent:

We have a **single Windows test machine online** and it is in bad shape, so there is effectively no testing on this platform at the moment.  

example of failures:  https://ci.adoptopenjdk.net/view/Test_all/job/openjdk11_hs_openjdktest_extended_x86-64_windows/11/console

Running on test-azure-win2012r2-x64-1 in C:\Users\jenkins\workspace\openjdk11_hs_openjdktest_extended_x86-64_windows
[Pipeline] {
[Pipeline] checkout
No credentials specified
Wiping out workspace first.
[Pipeline] }
[Pipeline] // node
[Pipeline] }
[Pipeline] // stage
[Pipeline] End of Pipeline
jenkins.util.io.CompositeIOException: Unable to delete 'C:\Users\jenkins\workspace\openjdk11_hs_openjdktest_extended_x86-64_windows\openjdk-tests'. Tried 3 times (of a maximum of 3) waiting 0.1 sec between attempts.
	at jenkins.util.io.PathRemover.forceRemoveDirectoryContents(PathRemover.java:86)
	at hudson.Util.deleteContentsRecursive(Util.java:260)

**Comment by karianna** [comment]
The following files are the culprit - I only have an `adoptopenjdk` user, I need some sort of Administrator to remove these (or perhaps be the jenkins user)

```
adoptopenjdk@test-2012r2-1 /cygdrive/c/Users/jenkins/workspace/openjdk11_hs_openjdktest_extended_x86-64_windows/openjdk-tests/TestConfig/test_output_15533899198838
$ ls -la
total 12
drwxr-xr-x+ 1 jenkins      None          0 Mar 30 15:59 .
drwxr-xr-x+ 1 jenkins      None          0 Mar 24 15:09 ..
drwxr-x---  1 Unknown+User Unknown+Group 0 Mar 24 06:34 jdk_2d_0
drwxr-x---  1 Unknown+User Unknown+Group 0 Mar 24 01:12 jdk_awt_0
```

**Comment by sxa555** [comment]
The `adoptopenjdk` user is an adminstrator so this shouldn't have been an issue. I'm going to reboot the machine (it's got some pending updates anyway) so will see if that allows us to clear it.

**Comment by sxa555** [comment]
Offending files vanished on a reboot without me having to take any further action.

**Comment by karianna** [comment]
Dang it - I remember that's what we had to do last time as well - there has to be a better way going forward :-/.  So we need to stop producing those files in the tests...
