### ISSUE TITLE
Allow Jenkins Daemon User to Kill Processes Without Requiring Password (test-packet-ubuntu1604-x64-2 & test-softlayer-ubuntu1604-x64-1)

### ISSUE THREAD

**Issue by piyush286** [AdoptOpenJDK/openjdk-infrastructure#785]
### Proposed Changes

I would request to allow Jenkins Daemon User to kill processes without requiring password. This would enhance our performance measurements for all benchmarks such as Open Liberty with Daytrader7. Thanks!

Currently, we just have 2 machines labelled with `ci.role.perf`: https://ci.adoptopenjdk.net/label/ci.role.perf/

We need to give privileges for `kill` to Jenkins Daemon users of those 2 machines.

### Justification

Please refer to this prerequisite for perf testing: https://github.com/AdoptOpenJDK/openjdk-tests/issues/1137

### Related Machines 
https://ci.adoptopenjdk.net/computer/test-packet-ubuntu1604-x64-2/
https://ci.adoptopenjdk.net/computer/test-softlayer-ubuntu1604-x64-1/

**Comment by sxa555** [comment]
Can you clarify what's needed here. The jenkins user (which everything executed through jenkins is run as) should be able to kill everything that it is running. What is it unable to kill?

**Comment by piyush286** [comment]
@sxa555 While running a benchmark, we want to make sure that only the processes related to that benchmark are running. At the start of most of our benchmarks, we kill any unnecessary processes, mainly java processes from previous runs since we're mainly using our machines for JVM testing. 

To make it more clear, when we start Liberty, we call this function `terminateRunningJavaProcs` to kill all Java processes. It uses `terminateRunningJavaProcs_getJavaPIDS` to find the unwanted processes and kills them. If we can't kill some Java processes, then we need to use non-catchable, non-ignorable kill (i.e. -9).

It might be more clear by looking at the relevant snippets below.

**Snippet from `terminateRunningJavaProcs_getJavaPIDS`**
https://github.com/AdoptOpenJDK/openjdk-tests/blob/a1a48439bf551f3160ca11f9b3f4d0c18f43a66b/performance/liberty/scripts/bin/common_utils.sh#L1774-L1793
```{
    case $PLATFORM in
        AIX)
            ps -ef -o pid,args | grep 'java' | grep -v 'grep' | grep -v 'slave.jar' | grep -v 'remoting.jar' | grep -v 'sufp' | grep -v 'throughput_benchmark' | grep -v 'durable' | awk '{print $1;}'
            ;;
        CYGWIN)
            ps | grep '/java' | grep -v 'grep' | grep -v 'slave.jar' | grep -v 'remoting.jar' | grep -v 'sufp' | grep -v 'throughput_benchmark' | grep -v 'durable' | awk '{print $1;}'
            ;;
        OS/390)
            ps -ef -o pid,args | grep 'java' | grep -v 'grep' | grep -v 'slave.jar' | grep -v 'remoting.jar' | grep -v 'sufp' | grep -v 'throughput_benchmark' | grep -v 'durable' | awk '{print $1;}'
            ;;
        *)
            ps -ef | grep 'java ' | grep -v 'grep' | grep -v 'slave.jar' | grep -v 'remoting.jar' | grep -v 'sufp' | grep -v 'throughput_benchmark' | grep -v 'durable' | awk '{print $2;}'
            ;;
    esac
}
```

**Snippet from `terminateRunningJavaProcs`**
https://github.com/AdoptOpenJDK/openjdk-tests/blob/a1a48439bf551f3160ca11f9b3f4d0c18f43a66b/performance/liberty/scripts/bin/common_utils.sh#L1797-L1849

```
    # Check to see if all JVMs exited
    JAVA_PIDS=$(terminateRunningJavaProcs_getJavaPIDS)

    local MAX_TRIES=5
    local TERMINATION_ATTEMPT=0
    # If not, try kill -9
    while [ -n "$JAVA_PIDS" ] && [[ ${TERMINATION_ATTEMPT} -lt ${MAX_TRIES} ]]; do
      echo "Trying kill -9: $JAVA_PIDS"
      kill -9 $JAVA_PIDS
      echo "`date`: Waiting 10s for JVMs to die"
      sleep 10
      JAVA_PIDS=$(terminateRunningJavaProcs_getJavaPIDS)
      let TERMINATION_ATTEMPT=TERMINATION_ATTEMPT+1
    done
```

> What is it unable to kill?

If you look at the `terminateRunningJavaProcs_getJavaPIDS` above, you'll see that we want to kill some old java processes. 

Looking at a Grinder run from last week: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1610/console, you'll see that some processes couldn't be killed. I believe Jenkins daemon user doesn't have the appropriate privileges to kill some processes (maybe launched by some other user), and hence we might need to give extra privileges.

https://linux.die.net/man/3/kill: "For a process to have permission to send a signal to a process designated by pid, unless the sending process has appropriate privileges, the real or effective user ID of the sending process shall match the real or saved set-user-ID of the receiving process."

**Error from https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1610/console**
```
14:29:51  | Terminating Any Running Java Processes
14:29:51  
14:29:51  Local date: Tue May 14 18:29:50 UTC 2019
14:29:51  List of Java processes to terminate:
14:29:51  Killing: 9042
14:29:51  9852
14:29:51  10335
14:29:51  11018
14:29:51  11601
14:29:51  /home/jenkins/workspace/Grinder/openjdk-tests/TestConfig/scripts/testKitGen/../../../../jvmtest/performance/liberty/scripts/bin/common_utils.sh: line 1816: kill: (9042) - Operation not permitted
...
...
14:30:42  Tue May 14 18:30:41 UTC 2019: Waiting 10s for JVMs to die
14:30:51  !!! WARNING !!! Could not terminate running Java processes. Exiting
```

**Comment by sxa555** [comment]
Do you know what machine that was? Interested to look at the state of the machine and find out what it was. It's either somethign that should be running or something that probably shouldn't be killed.

**Comment by piyush286** [comment]
From the runs I've launched so far, I've usually seen extra java processes running on this machine: https://ci.adoptopenjdk.net/computer/test-softlayer-ubuntu1604-x64-1/

AFAIR, the other perf machine (https://ci.adoptopenjdk.net/computer/test-packet-ubuntu1604-x64-2/) seems to be good.

**Comment by sxa555** [comment]
There appears to be multiple java processes running as root on that machine from May 12th initiating from `bash /kafka-test.sh`. I'll discuss in #testing in that adoptopenjdk slack to find out why that's there.

**Comment by sxa555** [comment]
@smlambert has confirmed that it's a cleanup issue with the externaltest docker images. I've shut down the two problematic containers which resolves the immediate problem:

```
jenkins@test-softlayer-ubuntu1604-x64-1:~$ docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS               NAMES
ac8a19423d32        41e33ae1d0dc        "/bin/bash /kafka-te…"   2 weeks ago         Up 2 weeks                              flamboyant_mendeleev
016665f82885        e3f4eded75a9        "/bin/bash /kafka-te…"   4 weeks ago         Up 4 weeks                              eager_margulis
```
