### ISSUE TITLE
One or all of the Linux slaves need python upgrade

### ISSUE THREAD

**Issue by neomatrix369** [AdoptOpenJDK/openjdk-infrastructure#788]
One or all of your Linux slaves are running python 2.6.x, instead of 2.7. In fact 3.7 should be a standard on all of them, unless there are apps that specifically need 2.7.

This is causing build apps requiring 2.7 or higher to break.

**Comment by karianna** [comment]
For reference, this is currently only breaking Graal builds.

**Comment by neomatrix369** [comment]
Well I think this issue has been fixed, as the build does not break due to python version anymore - someone might have fixed it or some technical change on the infra end fixed it.

Although it's breaking now due to disk space which isn't relevant to this issue: https://ci.adoptopenjdk.net/job/jdk8-with-graal_build_x86-64_linux/20/console

Last successful build: https://ci.adoptopenjdk.net/job/jdk8-with-graal_build_x86-64_linux/19/console
