### ISSUE TITLE
Jenkins Windows slave fails to install JDK

### ISSUE THREAD

**Issue by neomatrix369** [AdoptOpenJDK/openjdk-infrastructure#789]
See https://ci.adoptopenjdk.net/job/jdk8-with-graal_build_x86-64_windows/17/console, the Windows slave loops through a number of times and then times out.

Something on that slave or all slaves are preventing from the JDK from being installed.

**Comment by neomatrix369** [comment]
In the meanwhile, I will try to apply the suggestions provided on slack:
https://adoptopenjdk.slack.com/archives/C09NW3L2J/p1556882699040100

**Comment by gdams** [comment]
@neomatrix369 we don't install JDK's using the jenkins tool, you should find all the openjdk versions already installed on the machine.

**Comment by gdams** [comment]
JDK8 on that particular machine is in `/cygdrive/c/openjdk/jdk8`
