### ISSUE TITLE
Clean up abandoned/obsolete jobs in jenkins

### ISSUE THREAD

**Issue by sxa555** [AdoptOpenJDK/openjdk-infrastructure#790]
Working with Martijn on this - will report results and what we've done in this issue for future reference

TODO: Go through the Work in progress tab and encourage anyone with jobs in there to prefix them with their name

Also there are quite a lot of old jobs in the pipeline directories which are being kept (mostly but not exclusively GA ones) that could do with being cleaned up as they are chewing disk space.

**Comment by karianna** [comment]
We've made good progress - awaiting feedback from several job owners to clean up more

**Comment by sxa555** [comment]
List of jobs which we deleted today:

```
< amber-rsl_hs_openjdktest_x86-64_linux
< amber-rsl_hs_openjdktest_x86-64_macos

< ao8_jre_mirror_test_sxa

< attyt
< awx.job.playbook
< awx.job.shell
< awx.pipeline.job.playbook
< awx.pipeline.test
< Ben_test_job
< build_ao11j9_win_vs2017

< delete workspace

< freestyleTry

< GraalVM-suite-jdk8_x86-64_macos

< jdk10-solaris-sparcv9-hotspot-build

< jdk11-windows-x86-32-hotspot-wip
< jdk8u-mac-x64-hotspot-severin

< jdk8u-windows-x64-openj9

< lumpfish-openjdk12-pipeline
< lumpfish-openjdk12-pipeline2

< openjdk10_nightly_pipeline_scm

< openjdk10_openj9_nightly_pipeline_scm
< openjdk10_openj9_release_pipeline_scm

< openjdk10_release_pipeline_scm

< openjdk11_build_arm32_linux

< openjdk11_build_ppc64_aix
< openjdk11_build_ppc64le_linux
< openjdk11_build_s390x_linux
< openjdk11_build_x86-64_linux
< openjdk11_build_x86-64_macos
< openjdk11_build_x86-64_windows

< openjdk11_openj9_build_ppc64_aix
< openjdk11_openj9_build_ppc64le_linux
< openjdk11_openj9_build_s390x_linux
< openjdk11_openj9_build_x86-32_windows
< openjdk11_openj9_build_x86-64_linux
< openjdk11_openj9_build_x86-64_linux_largeHeap
< openjdk11_openj9_build_x86-64_windows

< openjdk8_build_aarch32_linux
< openjdk8_build_aarch64_linux
< openjdk8_build_arm32_linux
< openjdk8_build_checksum
< openjdk8_build_docker

< openjdk8_build_ppc64_aix
< openjdk8_build_ppc64le_linux
< openjdk8_build_s390x_linux
< openjdk8_build_x86-32_win-cacerts
< openjdk8_build_x86-32_windows
< openjdk8_build_x86-64_linux
< openjdk8_build_x86-64_linux-73
< openjdk8_build_x86-64_macos
< openjdk8_build_x86-64_macos-libfreetype
< openjdk8_build_x86-64_solaris
< openjdk8_build_x86-64_windows
< openjdk8_build_x86-64_windows_test

< openjdk8_nightly_pipeline_scm
< openjdk8_openj9_build_checksum
< openjdk8_openj9_build_ppc64_aix
< openjdk8_openj9_build_ppc64le_linux
< openjdk8_openj9_build_s390x_linux
< openjdk8_openj9_build_x86-32_windows
< openjdk8_openj9_build_x86-64_linux
< openjdk8_openj9_build_x86-64_linux_largeHeap
< openjdk8_openj9_build_x86-64_linux-SSL
< openjdk8_openj9_build_x86-64_windows
< openjdk8_openj9_nightly_pipeline_scm
< openjdk8_openj9_release_pipeline_scm

< openjdk8_release_pipeline_scm
< openjdk8_stf_systemtests-user

< openjdk9_nightly_pipeline_scm

< openjdk9_openj9_nightly_pipeline_scm
< openjdk9_openj9_release_pipeline_scm

< openjdk_amber_build_checksum
< openjdk_amber_build_s390x_linux
< openjdk_amber_build_x86-64_linux
< openjdk_amber_build_x86-64_macos
< openjdk_amber_build_x86-64_windows
< openjdk_amber_nightly_pipeline_scm
< openjdk-api-java-client

< windows-x64-jdk11-fix
```

**Comment by smlambert** [comment]
I additionally cleaned up old test jobs (containing strings '_systemtest_', '_openjdktest_', though I have left the ev3 runs, until I check with that team), as we have re-generated test jobs with a different naming convention now, https://github.com/AdoptOpenJDK/openjdk-tests/issues/1168.  Note we are still only keeping 5 jobs in history.

**Comment by smlambert** [comment]
I propose that we run a script that checks all Jenkins job and lists those that have not been used in over x months.  That way we can flag and remove stale jobs.  (I proposed this last year, and think I wrote a script that would do this & delete the jobs... though I think we want to be cautious and not blindly delete without human intervention).

**Comment by sxa555** [comment]
Space ran out again this weekend. Roughly speaking we have the following under the `jobs` dir:

- 130Gb in use by `build-scripts`
- 100Gb by the `Test_` jobs
- 72Gb from what I'll call "Legacy" build jobs (Those not in the `build-scripts` directories)
- Exclusing the above, 6 jobs using more than 1Gb: Three `Grinder` jobs, `openjdk8_jcov`, `UploadFile` (Used by test) and `ev3dev`)

Also, in the `worksapce` directory on master, ~125Gb in the `workspace` directory of which a little over 90Gb is the `build-scripts` pipelines.

Implemented https://ci.adoptopenjdk.net/view/work%20in%20progress/job/SXA-masterSpace/ to periodically check this and post to slack if the space goes under 10Gb
