### ISSUE TITLE
Enable Local Execution of Windows Playbook

### ISSUE THREAD

**Issue by adamfarley** [AdoptOpenJDK/openjdk-infrastructure#791]
When running the Ansible playbook locally on Windows, there are various blockers which prevent successful execution. The ones we know about are listed below, as well as the work-arounds we used to resolve them.

Note: After all these changes, the playbook still don't run to completion locally. This is just the point where we gave up, and set up a remote ansible server.

The objective of this issue is to enable someone to install ansible and run the Windows playbook to completion locally without failure.

Known issues:

- The fact that there are PowerShell commands in the Windows playbook isn't advertised anywhere except inside the playbook.

- Said commands can't be run unless you've enabled script execution via, e.g:  Set-ExecutionPolicy Unrestricted

- Ansible can't just be installed. Users need to follow a guide like the one here:

 www.oznetnerd.com/installing-ansible-windows

- When configuring cygwin packages during installation, users need to choose the modules specified in the guide, except replacing all the "python" modules with python37 modules (python 2 modules can be added as-is).

- The file "/etc/ansible/hosts" needs to be created from scratch, with the content being: 
```
[local] 
1270.0.1
```

- Users need to edit main.yml file for windows, and replace 
```
"- hosts: etc etc"
```
with
```
- hosts: 127.0.0.1
  connection: local
```

- People need to run the pip install as a python module:
```
python37 -m pip install ansible
```

- Users need to install winrm using the command below, to prevent an error when ansible can't find it.
```
Run: python37 -m pip install "pywinrm>=0.2.2"
```

- The main.yml file should also be edited to remove the "Windows Updates" and "Jenkins" roles, because the former didn't work on a windows 10 machine (something about not being able to find the reboot_needed variable), and the latter fails for some other reason. Neither are needed if the user's machine is up to date, and they're running locally.

- the "/playbook_git_repo_location/group_vars/all/adoptopenjdk_variables.txt" file needs to be edited to replace
```
#ansible_password: CHANGE_ME
```
with
```
ansible_user: <your username>
ansible_password: <your password>
```

- When running the cygwin role, it restarts the computer after editing the path variable. This is a problem while running locally, as it stops the process, and you have to restart it again.

- When finally running the playbook command, ansible on windows doesn't recognise the -s option.

**Comment by sxa555** [comment]
Alternative is to run it from a Linux (except RHEL7 which will have a problem with the pyOpenSSL version - may be fixable using a python  venv) or other machine that's got ansible installed. Safest way is to run this on the other machine that has ansible installed to get the appropriate protocol packages installed:
```
pip install --ignore-installed pywinrm
pip install --upgrade pywinrm[credssp]
```
Run the `ps1` script with the EnableCredSSP option documented in the playbook, adjust the variables file to include `ansible_winrm_transport: credssp` and uncomment/set `ansible_password`, create a `hosts.win` or any other name you want with the remote IP address, change the line in `main.yml` to `hosts: all` and run:
```
ansible-playbook -i hosts.win -u <your_admin_username> main.yml
```

**Comment by sxa555** [comment]
Ref the `Jenkins` roles it would be useful to know the error, but we should implement a suitable tag which matches what was done on the UNIX side under https://github.com/AdoptOpenJDK/openjdk-infrastructure/commit/04502f26df34ba8a13822c98e9be323629b4ce97

**Comment by sxa555** [comment]
See also https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/423

**Comment by karianna** [comment]
@Willsparker - So you think this can be closed?

**Comment by Willsparker** [comment]
@karianna I'd say so- It's not *true* local execution, but it's as close as we can get with Ansible as it is :)
