### ISSUE TITLE
Increase MacOS test capability

### ISSUE THREAD

**Issue by lumpfish** [AdoptOpenJDK/openjdk-infrastructure#794]
While testing the jdk-11.0.3+7_openj9-0.14.2 release I observed that the biggest 'laggard' in the build + test process was the MacOS test jobs:

- openjdk test job submitted 28/05/2019 11:52
- then "Waiting for next available executor on ‘ci.role.test&&hw.arch.x86&&sw.os.osx’"
- tests started running 29/05/2019 10:53

So nearly 24 hours waiting for a machine to become available.

Once running, the tests on MacOS take 8 hours or so to complete: https://ci.adoptopenjdk.net/job/openjdk11_j9_openjdktest_x86-64_macos_macosXL/buildTimeTrend

On linux_x86, the same tests take about an hour: https://ci.adoptopenjdk.net/view/Test_openjdk/job/openjdk11_j9_openjdktest_x86-64_linux/buildTimeTrend

So this is issue is to request more, and more powerful, macOS machines for testing in order to meet our goals of building and testing releases within 24 hours (this situation is worse if there are other releases (jdk8, jdk11 etc.) requiring the same test machines.

Perhaps redeploying JCK machines (see https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/610) might provide a little extra resource in the short term.

**Comment by karianna** [comment]
@sxa555 Redeploying the JCK machines is a good idea in the short term, we'd just need to change their labels right?  Or do you also want to rename the host?

**Comment by sxa555** [comment]
@karianna The only thing that stopped me doing this was not having playbooks fully ready for macosx, but in principle that's how to do it - remove it from the other jenkins instance and reconnect it to this one after wiping the JCK material from them

**Comment by sxa555** [comment]
I'll look at moving one of the JCK macs across once the current round of releases (JDK11 for OpenJ9 0.14.3 and JDK8 b04 for HotSpot) are done to avoid risking destabilising anything)

**Comment by sxa555** [comment]
Have moved one JCK mac across as https://ci.adoptopenjdk.net/computer/test-macincloud-macos1010-3-XJ/ (without any additional setup yet)

**Comment by karianna** [comment]
Looks like that's being used well, thanks

**Comment by sxa555** [comment]
Applied some extra bits under https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/808
Now seems to be working ... closing.
