### ISSUE TITLE
Update playbooks to be able to build OpenJFX on RHEL6/7

### ISSUE THREAD

**Issue by sxa555** [AdoptOpenJDK/openjdk-infrastructure#797]
Changes are in to build on Ubuntu, but if possible we want to build on RHEL/CentOS to be consistent with our other build machines.

**Comment by aahlenst** [comment]
I guess this can be closed: https://adoptopenjdk.net/faq.html#openjfxfaq

**Comment by sxa555** [comment]
Part of me thinks we should have it in there to allow people to build it themselves if desired, although I suspect most people will be using Ubuntu, and we've not removed the stuff from the playbooks to support building it on there (maybe we should) but I agree that this is not currently required, therefore closing.
