### ISSUE TITLE
RedHat playbooks should not set default java to the IBM ones

### ISSUE THREAD

**Issue by sxa555** [AdoptOpenJDK/openjdk-infrastructure#799]
e.g. https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/347f5ceb6c0e5b6dd82b8ce921bfe03a1eccd18f/ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/RedHat.yml#L98 - can't guarantee that the IBM java is installed (and we shoudln't be relying on it anyway)

**Comment by Willsparker** [comment]
According to: https://access.redhat.com/articles/1299013

"What hardware architectures are supported by the Red Hat build of OpenJDK for RHEL?
...
PPC64 (start wth RHEL7)"

It seems we can't set the default java to be the RHEL6 ppc64 equivalent of what everything else is being set as. 
@sxa555 What would be a suitable alternative?

**Comment by sxa555** [comment]
Since this is java 8, the adoptopenjdk ones should be suitable

**Comment by Willsparker** [comment]
Do you know what the path would be, or where I could find out?

**Comment by sxa555** [comment]
None of our production machines are RHEL6/ppc64 so if anyone wants to use it on their own systems I'm happy for this to be left in so it works, but it doesn't affect any of our systems. Closing.
