### ISSUE TITLE
openjdk test pipeline failing on test-azure-win2012r2-x64-1

### ISSUE THREAD

**Issue by lumpfish** [AdoptOpenJDK/openjdk-infrastructure#804]
After tests have run (successfully) on test-azure-win2012r2-x64-1, the Jenkins job fails with the messages:
```
[Pipeline] junit
18:14:18  Recording test results
18:14:20  Remote call on JNLP4-connect connection from 13.68.134.204/13.68.134.204:52102 failed
```
e.g. see https://ci.adoptopenjdk.net/job/openjdk8_j9_openjdktest_x86-64_windows/294/console

**Comment by sxa555** [comment]
Have bounced the jenkins agent - let me know if that resolves it ... It looks like the sort of error that might be cured by this - post any new job link if it shows up again.

**Comment by karianna** [comment]
It's running again
