### ISSUE TITLE
Redhat6 x86 playbooks not 100% functional

### ISSUE THREAD

**Issue by jdekonin** [AdoptOpenJDK/openjdk-infrastructure#807]
I ran into a few issues creating a machine from scratch yesterday.
- cmake requires c++11 support, which #801 has covered
- fix conditional such that openjdk7/8 are installed
- correct java alternative for x86 as its openjdk and not the ibm package that installed
- compile expat from source, such that cpanm install of XML parser works
- ccache fails to uncompress...seems to be working fine now when doing it manually though

**Comment by jdekonin** [comment]
I think PR #806 covers the issue I raised, minus ccache which is working now so a non-issue.

**Comment by sxa555** [comment]
Can you give the errors that are showing on your install? I don't remember those from the last time I ran the playbooks and it's not entirely obvious what's going wrong from the problem descriptions.. The exception is the IBM java package issue which has also been reported in https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/799

**Comment by jdekonin** [comment]
It seems expat is available if your starting rh6 release is new enough.  My original base was 6.3, where this error occurred.  With 6.10, expat.x86_64 v2.0.1-13.el6_8 is available.  I'm fine with removing the expat changes if there is an agreement that the playbooks will only run against the latest of a specific release.

ccache is still not working for me even with 6.10 machine.
```
TASK [../AdoptOpenJDK_Unix_Playbook/roles/ccache : Download ccache.tar.gz] *****
fatal: [aurar1.fyre.ibm.com]: FAILED! => {"changed": false, "dest": "/tmp/ccache.tar.gz", "msg": "Request failed: <urlopen error [Errno 8] _ssl.c:492: EOF occurred in violation of protocol>", "state": "absent", "url": "https://www.samba.org/ftp/ccache/ccache-3.4.2.tar.gz"}
...
"msg": "Request failed: <urlopen error [Errno 8] _ssl.c:492: EOF occurred in violation of protocol>"
```

**Comment by sxa555** [comment]
@Willsparker I'll assign this to you to see if you've hit the `ccache` issue in the playbook during your CentOS6 testing :-)

**Comment by sxa555** [comment]
Related: https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/696

**Comment by Willsparker** [comment]
@sxa555 Issue still seems to persist using CentOS6. 'wget' ing the URL does work though, the error message says:

```
TASK [local_srcinstall : Download source tarball from "https://www.samba.org/ftp/ccache/ccache-3.4.2.tar.gz"] ***
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed to validate the SSL certificate for www.samba.org:443. Make sure your managed systems have a valid CA certificate installed. If the website serving the url uses SNI you need python >= 2.7.9 on your managed machine  (the python executable used (/usr/bin/python2.6) is version: 2.6.6 (r266:84292, Jun 20 2019, 14:14:55) [GCC 4.4.7 20120313 (Red Hat 4.4.7-23)]) or you can install the `urllib3`, `pyOpenSSL`, `ndg-httpsclient`, and `pyasn1` python modules to perform SNI verification in python >= 2.6. You can use validate_certs=False if you do not need to confirm the servers identity but this is unsafe and not recommended. Paths checked for this platform: /etc/ssl/certs, /etc/pki/ca-trust/extracted/pem, /etc/pki/tls/certs, /usr/share/ca-certificates/cacert.org, /etc/ansible. The exception msg was: [Errno 8] _ssl.c:492: EOF occurred in violation of protocol."}
```
