### ISSUE TITLE
jdk8u-windows-x64-hotspot fails to build

### ISSUE THREAD

**Issue by maru-sama** [AdoptOpenJDK/openjdk-infrastructure#810]
I noticed that since some days the nightly builds for jdk8u-windows-x64-hotspot fail. Looking at the console
https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-windows-x64-hotspot/311/console i see this

> Running on build-azure-win2008r2-x64-1 in C:\Users\jenkins\workspace\build-scripts\jobs\jdk8u\jdk8u-windows-x64-hotspot
[Pipeline] {
[Pipeline] stage
[Pipeline] { (build)
[Pipeline] checkout
No credentials specified
Cloning the remote Git repository
Cloning repository https://github.com/AdoptOpenJDK/openjdk-build.git
ERROR: Failed to clean the workspace
jenkins.util.io.CompositeIOException: Unable to delete 'C:\Users\jenkins\workspace\build-scripts\jobs\jdk8u\jdk8u-windows-x64-hotspot'. Tried 3 times (of a maximum of 3) waiting 0.1 sec between attempts.
	at jenkins.util.io.PathRemover.forceRemoveDirectoryContents(PathRemover.java:86)
	at hudson.Util.deleteContentsRecursive(Util.java:259)
	at hudson.Util.deleteContentsRecursive(Util.java:248)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$2.execute(CliGitAPIImpl.java:653)
	...

Can someone please take a look at this?

**Comment by karianna** [comment]
I've cleared the offending directory, will review after tonight's run

**Comment by sxa555** [comment]
This looks to be running ok now, although we had a similar problem on the OpenJ9 JDK8 32-bit builds which I've also resolved (Ref: https://github.com/AdoptOpenJDK/openjdk-build/issues/1136). Closing
