### ISSUE TITLE
Install Database for Liberty Throughput Benchmark on x86 Perf Machine

### ISSUE THREAD

**Issue by piyush286** [AdoptOpenJDK/openjdk-infrastructure#812]
I want to add Liberty Throughput benchmark for perf testing as part of https://github.com/AdoptOpenJDK/openjdk-tests/issues/1127. This benchmark is the one of the most popular ones, and it would be essential to have that on Adopt. One of the pre-requisites of that benchmark is to have Db2 installed. The setup for Liberty throughput would look like this:

Machine 1: Liberty Server (DayTrader)
Machine 2: Database (Db2) + Client

We usually use the same configs across all DB2 setups to that it's easier to remember, maintain and use them for benchmarking, eliminating the need to have different config files for Db2 setups on different machines.

Username: db2inst1
Password: Usually same as username
Port: 50000
Home: /home/db2inst1

Free Db2 can be downloaded from here: https://www.ibm.com/us-en/marketplace/ibm-db2-direct-and-developer-editions

Please let me know if you need help with the installation.

### Machine Requirement
This machine must be at least as powerful as the app server (i.e. machine running Liberty) it will support. Strong the database machine, the better, so that database doesn't become a bottleneck while benchmarking.

Since we currently have 2 perf machines (https://ci.adoptopenjdk.net/label/ci.role.perf/) and both seem to have similar configs, we can use any of them.

**Comment by sxa555** [comment]
Does this require Db2 specifically or could a fully open-source database be used in place?

**Comment by smlambert** [comment]
My preference will be an open-source DB.  If it is not possible at the present moment, we should make it possible.

**Comment by piyush286** [comment]
> Does this require Db2 specifically or could a fully open-source database be used in place?

@sxa555 Doesn't have to be Db2. We should be able to use some other database besides Db2 but requirements would be similar as mentioned above. 

> My preference will be an open-source DB. If it is not possible at the present moment, we should make it possible.

Sounds good! Let me find some alternative (i.e. MongoDB, PostGreSQL or other newer ones) that's open-source and do some internal testing to verify that it can be work with Open Liberty without any issues. I'll get back on this issue. Thanks!

**Comment by sxa555** [comment]
@piyush286 Any update on  this one? Previous action was with you

**Comment by piyush286** [comment]
Sorry, forgot to put an update here. 

I've managed to use an alternate database (Apache Derby), and made it part of my build step of my test to download it and populate it for running the benchmark. Due to other pressing issues, I didn't get a chance to clean up my code and make a PR yet.

Hence, we wouldn't need to machine to be installed with it before hand, so closing this issue. Thanks!
