### ISSUE TITLE
Update Nagios to latest version

### ISSUE THREAD

**Issue by tellison** [AdoptOpenJDK/openjdk-infrastructure#82]
Our installation of Nagios Core 4.3.1 is outdated and should be upgraded. The latest version of Nagios Core is 4.3.4 was released on 2017-08-24.

**Comment by bblondin** [comment]
- Tested latest automatic backup of Nagios: nagios_backup_12-09-2017.tar.gz
- Created personal backup of everything in /usr/local/ 
- Confirmed Nagios is currently working
- Downloaded latest version of Nagios: nagios-4.3.4.tar.gz

**Comment by bblondin** [comment]
- Shutdown the Nagios service
- Compiled new version and installed
- Updated website
- Restarted Nagios
- Tested

version 4.3.4 is now up and running
