### ISSUE TITLE
Add git subtree to ansible script for git-hg follower

### ISSUE THREAD

**Issue by karianna** [AdoptOpenJDK/openjdk-infrastructure#822]
Git subtree wasn't installed for the `gi-hg` GoDaddy follower, not sure if that's a failing of our ansible script there.  To install git subtree (that matches the git version on the host), as the `adoptopenjdk` user I executed:

```
git clone -b 'v2.15.0' --single-branch --depth 1 https://github.com/git/git.git
cd git/contrib/subtree
make
sudo make prefix=/usr/local install
```

And then cleaned up the git source clone afterward.

**Comment by sxa555** [comment]
ansible script is not finalised at present. Tagging https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/819 which is where extra things needed in the playbook are being logged and closing this issue.
