### ISSUE TITLE
Set up four new Windows 2016 machines via godaddy for system test

### ISSUE THREAD

**Issue by sxa555** [AdoptOpenJDK/openjdk-infrastructure#827]
Related: https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/553 (Windows Playbook setup) https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/627 (2 softlayer machines) https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/559 (Not starting as service on some machines) https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/791 (Local execution) https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/423 (Fail if not in inventory) 

New machines to be set up:
- test-godaddy-win2016-x64-1
- test-godaddy-win2016-x64-2
- test-godaddy-win2016-x64-3
- test-godaddy-win2016-x64-4

**Comment by sxa555** [comment]
@smlambert Do you require any specific compiler on the Windows machines? There are some manual steps that we'd generally install on the build machines (stuff that can't be automated including the Windows SDK) but if the test machines don't require it I can skip those steps. I'll look at enabling the new `-1` machine and see if I can run a grinder on it

**Comment by sxa555** [comment]
- https://ci.adoptopenjdk.net/job/Test_upstream_openjdk8_hs_sanity.system_x86-64_windows/8/console has been run on `-1` and working ok
- https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1787/console ran on `-2` and working ok.

Based on the above I will add the `ci.role.test` to those machines and also to `-3` once I get it talking to jenkins on the assumption that the setup we have is "good enough". `-4` will follow later

**Comment by smlambert** [comment]
Answering https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/827#issuecomment-512213220, when asked that before, I have answered whatever compiler was used to build the sdk should work (as at all other projects where we run these tests, build & test machines are one in the same.  

https://github.com/AdoptOpenJDK/openjdk-systemtest/blob/master/openjdk.build/docs/build.md#prereqs-which-cannot-be-installed-by-the-openjdk-systemtest-build-scripts (looks like we could add doc for prereqs to build native tests to the doc)

**Comment by sxa555** [comment]
Unfortunately that's three different ones depending on which JDK it is ;-) Wasn't sure if the test scripts tried to find the specific one for any given release

**Comment by Willsparker** [comment]
" TASK [MSVS_2013 : Reboot machine after Visual Studio installation] ***********************************
 [WARNING]: Since Ansible 2.5, shutdown_timeout is no longer a valid option for win_reboot "

Warning that came up as the playbook was running for one of the machines. Didn't stop the playbook, but thought it should be documented 👍

**Comment by sxa555** [comment]
Something odd is happening when I set up the `-3` machine in jenkins with the correct name (It seems to thing `-2`'s executor is connected to it. Have therefore renamed to `test-godaddy-win3` for now in jenkins to resolve.

**Comment by Willsparker** [comment]
Machine 4 is running through it's tests:

https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1818/console

**Comment by Willsparker** [comment]
Completed the job!
