### ISSUE TITLE
Add IcedTeaWeb to Windows playbooks

### ISSUE THREAD

**Issue by sxa555** [AdoptOpenJDK/openjdk-infrastructure#829]
Using web start is the simplest way to be able to get the jenkins agent running as a service.

1. `wget https://github.com/AdoptOpenJDK/IcedTea-Web/releases/download/icedtea-web-1.8.2/icedtea-web-1.8.2.msi` (or another version from https://adoptopenjdk.net/icedtea-web.html)
2. Install with `msiexec /l* %TEMP%\icedteaweb.log /quiet /i icedteaweb-1.8.2.msi INSTALLDIR="C:\Program Files\IcedTeaWEB"`

**Comment by karianna** [comment]
Hmmmm, is that really the recommended best practice from Jenkins?
