### ISSUE TITLE
Free up disk space on build-marist-s390x-sles-12 root partition

### ISSUE THREAD

**Issue by tellison** [AdoptOpenJDK/openjdk-infrastructure#83]
The `/dev/dasdb2` file system on build-marist-s390x-sles-12 (148.100.110.56) is filling up, currently at 96%.

On the Ubuntu sister machine, the system upgrades had multiple versions of the kernel left behind.  That may be happening on SLES too.

This task is to clear out any unused packages and kernels to free up the root partition.

**Comment by bblondin** [comment]
Cleaned up hosts, details below.

Both of these hosts are configured with very small root partitions and have a /data mount point (100GB on SLES and 60GB on UB) we should be using /data where possible.

If this becomes an issue again, we should look at repointing /tmp to /data/tmp

build-marist-s390x-sles-12:
Was:
```
Filesystem      Size  Used Avail Use% Mounted on
/dev/dasdb2     5.8G  5.3G  243M  96% /
```

Now is:
```
Filesystem      Size  Used Avail Use% Mounted on
/dev/dasdb2     5.8G  3.8G  1.7G  70% /
```



build-marist-s390x-ubuntu-16.04:
Was:
```
Filesystem               Size  Used Avail Use% Mounted on
/dev/dasdb1              4.8G  2.0G  2.6G  44% /
```

Now is:
```
Filesystem               Size  Used Avail Use% Mounted on
/dev/dasdb1              4.8G  1.8G  2.8G  39% /
```

**Comment by gdams** [comment]
can this now be closed?
