### ISSUE TITLE
pLinux-LE machines for all non-JCK testing

### ISSUE THREAD

**Issue by smlambert** [AdoptOpenJDK/openjdk-infrastructure#84]
I will piggy-back on the requests for JCK test machines (asking for same requirements as #76), 
"Spec-wise something like 2-core, 8Gb RAM and an SSD of around 100Gb ".

One (or eventually two) machines, so that we can enable the following types of tests:
- openjdk regression tests
- system/stress tests
- functional tests

(optionally/eventually some perf micro benchmarks).

**Comment by gdams** [comment]
two ppcle machines have now been spun up
