### ISSUE TITLE
Automating the testing of the playbooks for Linux using Vagrant

### ISSUE THREAD

**Issue by Willsparker** [AdoptOpenJDK/openjdk-infrastructure#842]

**Comment by sxa555** [comment]
Reopening this until we have a full solution that works via our CI :-)

One issue we currently have is that we need to be able to get VirtualBox running within one of our cloud VMs which means getting VirtualBox configured from the command line not to use hardware virtualisation instructions (Alternative is to get a dedicated bare metal VM that we can run VMs on but that would be more expensive)

**Comment by Willsparker** [comment]
@sxa and I looked into it and it seems not possible to run Virtualbox from another VM as hardware virtualisation can't be disabled. So, a bare metal VM will be needed.

**Comment by sxa555** [comment]
Now running on a Thinkpad at https://ci.adoptopenjdk.net/computer/infra-vagrant-1/ but continuing to investigate sourcing a suitable cloud machine for this - will deal with that separately.

See also separate task #890 for adding Debian to this set of tests.
