### ISSUE TITLE
clone build-azure-win2008r2-x64-1

### ISSUE THREAD

**Issue by gdams** [AdoptOpenJDK/openjdk-infrastructure#847]
having a single 2008r2 build machine was slowing down the release pipeline. Also means we have 2 machines incase one goes down

**Comment by gdams** [comment]
I've created a build snapshot of `build-azure-win2008r2-x64-1` brining up a second box. Note that the IP has changed on build-azure-win2008r2-x64-1 so I will update the infra yaml file.

**Comment by gdams** [comment]
`build-azure-win2008r2-x64-2` has been created

**Comment by gdams** [comment]
PR to add IP's https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/848

**Comment by sxa555** [comment]
What's the reason for needing the clone?

**Comment by gdams** [comment]
having a single 2008r2 build machine was slowing down the release pipeline. Also means we have 2 machines incase one goes down
