### ISSUE TITLE
zLinux machine(s) for non-JCK testing

### ISSUE THREAD

**Issue by smlambert** [AdoptOpenJDK/openjdk-infrastructure#85]
Request for minimally 1 (eventually 2, if we do not start sharing machines across build/test functionality) zLinux machines for JCK testing (similar request to #77), "Spec wise a 2-core, 8Gb, and a fast disk of around 100Gb".

**Comment by tellison** [comment]
Which Linux distro do you prefer?  The options are Ubuntu / SLES / Red Hat.

**Comment by tellison** [comment]
I presume this request is in addition to request #25 ?

**Comment by smlambert** [comment]
Yes, these requests are in addition to the JCK test machine requests, unless those machines will somehow be available for other testing (and visible / accessible) so that the non-JCK test results are public.

**Comment by tellison** [comment]
> Yes, these requests are in addition to the JCK test machine requests

Wait, number #77 is for zLinux JCK testing machines, and (#25 and #85) are requests for non-JCK testing machines.

I guess I'm figuring out the need for (#25 and #85), so checking they are both required independently.

**Comment by tellison** [comment]
Closing as duplicate of #25
