### ISSUE TITLE
Experiment with playbook format/layout roles/tasks

### ISSUE THREAD

**Issue by bblondin** [AdoptOpenJDK/openjdk-infrastructure#86]
I believe that we have outgrown the currently format/layout.
Initially we thought the playbooks for OS deploys would be small/simple. 
They have become very lengthy as our requirements have expanded.

It appears that it’s time to look into evolving the playbooks to use roles, task and vars.

I will be experimenting with the Ansible playbooks format/layout.

**Comment by gdams** [comment]
The Node.js Foundation use this sort of system https://github.com/nodejs/build/tree/master/ansible

**Comment by bblondin** [comment]
Here is what I have so far:
https://github.com/bblondin/openjdk-infrastructure/tree/master/New_Play

What do you think? Comments/Questions?

**Comment by karianna** [comment]
@bblondin That is looking really good.

**Comment by gdams** [comment]
I'm certainly liking how it works

**Comment by bblondin** [comment]
- Added Playbook support for Oracle Linux 7 on aarch64 
- Included gcc 4.8 for RedHat 6 on x86_64
- Fixed spelling error in '**c**cache' section and updated to use stat.isdir, now skips if already installed 
- Fixed version comparison in 'cmake' and 'GIT_Source' roles 
- Added 'enable: yes' for NTP[d] service

**Comment by gdams** [comment]
Can we have windows support in this format? Also macos support would be good!

**Comment by gdams** [comment]
I wrote the macOS scripts for the Node.js foundation here https://github.com/nodejs/build/pull/971/files

**Comment by bblondin** [comment]
The 'Nagios_Plugins' role needs some work. I'll have a look at this selection next week.

Such as: 

- The way it adds a new user
- How it download loads plugins 
- Consistency in layout and format

**Comment by tellison** [comment]
I'd encourage you to go live with it in the infra repo as soon as you are ready Brad.  No point in trying to keep two styles going side-by-side when you have general agreement that this is goodness.

**Comment by gdams** [comment]
yeah I'd agree, let's get this in a PR so we can review and then we should be good to go

**Comment by bblondin** [comment]
- pull request created #100 
- also renamed and moved, {New_Play => ansible/playbooks/AdoptOpenJDK_Linux_Playbook}
