### ISSUE TITLE
Investigate feasibility of testing Windows playbooks under Vagrant

### ISSUE THREAD

**Issue by sxa555** [AdoptOpenJDK/openjdk-infrastructure#864]
How easily can Windows systems be created and run via Vagrant? Can we automate the playbook testing on "clean" OS installs as we can now do on Linux (https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/842)?

**Comment by Willsparker** [comment]
Written a vagrantfile that can boot a Windows 10 VM, however when using `vagrant ssh` it boots into a linux shell script. `cmd` can then be run from there.

**Comment by Willsparker** [comment]
Created a vagrantfile that can boot a windows VM, and have a list of reliable steps towards running the playbook remotely. A `readme.md` file will need to be created, or an existing one altered to give steps on how to do this.
Overview of the steps taken:
1. `vagrant up` on Vagrantfile.WindowsS12
2. On windows vagrant machine:
  - `wget https://raw.githubusercontent.com/ansible/ansible/devel/examples/scripts/ConfigureRemotingForAnsible.ps1 -OutFile .\ConfigureRemotingForAnsible.ps1`
  - ` .\ConfigureRemotingForAnsible.ps1 -EnableCredSSP ` 
  - `ipConfig` to find the ip-address for the VM
3. (if on Mac host) `export OBJC_DISABLE_INITIALISE_FORK_SAFETY=yes`
4. On Host machine:
  - change `hosts.txt` in `../ansible/playbooks/AdoptOpenJDK_Windows_Playbook/` to include the Windows VM ip address.
  - add in `../AdoptOpenJDK_Windows_Playbook/group_vars/all/adoptopenjdk_variables.yml`, the line `ansible_winrm_transport=CredSSP`
  - From `../ansible` run `sudo ansible-playbook -i playbooks/AdoptOpenJDK_Windows_Playbook/hosts.win -u vagrant playbooks/AdoptOpenJDK_Windows_Playbook/main.yml`

.. and the playbook should run.
