### ISSUE TITLE
Add more ppc64le test machines

### ISSUE THREAD

**Issue by gdams** [AdoptOpenJDK/openjdk-infrastructure#868]
First step is to decommission the two ppc64le jck machines

Then I'll create more test machines.

**Comment by gdams** [comment]
Will add 

2 x Ubu 16.04 (making the total 4)
4x Centos 7 (total 4)
3 x Ubu 18.04 (total 3)

**Comment by gdams** [comment]
Openstack reporting that no more IP addresses are available, I've raised a support ticket to get this resolved.

**Comment by gdams** [comment]
added: 
- https://ci.adoptopenjdk.net/computer/test-osuosl-centos74-ppc64le-1/
- https://ci.adoptopenjdk.net/computer/test-osuosl-centos74-ppc64le-2/
- https://ci.adoptopenjdk.net/computer/test-osuosl-centos74-ppc64le-3/
- https://ci.adoptopenjdk.net/computer/test-osuosl-centos74-ppc64le-4/

**Comment by smlambert** [comment]
Launched grinders:
-1 : https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder_Advanced/52
-2 : https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder_Advanced/53
-3 : https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder_Advanced/54
-4 : https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder_Advanced/55

fail with 
14:58:27  ant -f ./src/build_envInfo.xml -DTEST_JDK_HOME=/home/jenkins/workspace/Grinder_Advanced/openjdkbinary/j2sdk-image
14:58:27  make: ant: Command not found
14:58:27  run_configure.mk:38: recipe for target 'testconfig' failed
14:58:27  make: *** [testconfig] Error 127

Needs ant prereq installed (see the prereqs list here: https://github.com/eclipse/openj9/blob/master/test/docs/Prerequisites.md)

**Comment by sxa555** [comment]
@gdams has any setup been done on these? If not they shouldn't be added into jenkins and made live with all the production tags. They don't seem to have my ssh key installed so I can't see what's been done, therefore I am marking all four offline in jenkins to avoid destabilising our CI further.

**Comment by gdams** [comment]
they are all setup, grinder jobs have passed

**Comment by smlambert** [comment]
Reran grinders which now pass (https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder_Advanced/55 through 59) so from test perspective they are good, but will assume you need other stuff setup for easier maintenance of them.

**Comment by gdams** [comment]
added more machines:

https://ci.adoptopenjdk.net/computer/test-osuosl-ubuntu1604-ppc64le-3/
https://ci.adoptopenjdk.net/computer/test-osuosl-ubuntu1604-ppc64le-4/
https://ci.adoptopenjdk.net/computer/test-osuosl-ubuntu1804-ppc64le-1/
https://ci.adoptopenjdk.net/computer/test-osuosl-ubuntu1804-ppc64le-2/
https://ci.adoptopenjdk.net/computer/test-osuosl-ubuntu1804-ppc64le-3/

**Comment by gdams** [comment]
grinders look good to me

**Comment by smlambert** [comment]
Grinders:
ubuntu1604-ppc64le-1: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder_Advanced/66

ubuntu1604-ppc64le-2: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder_Advanced/67

ubuntu1604-ppc64le-3: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder_Advanced/68

ubuntu1604-ppc64le-4: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder_Advanced/69
