### ISSUE TITLE
ssh-agent provider missing from machine: build-marist-sles12-s390x-1.adoptopenjdk.net

### ISSUE THREAD

**Issue by adamfarley** [AdoptOpenJDK/openjdk-infrastructure#879]
Kindly add an ssh-agent provider to this machine, as we get the below error when running tests on it.

```
17:20:44  [ssh-agent] Looking for ssh-agent implementation...
17:20:45  [ssh-agent]   Exec ssh-agent (binary ssh-agent on a remote machine)
17:20:32  $ ssh-agent
17:20:45  [ssh-agent]   Java/JNR ssh-agent
17:20:45  [ssh-agent] Registered BouncyCastle on the remote agent
17:20:45  [ssh-agent] FATAL: Could not find a suitable ssh-agent provider
17:20:45  [ssh-agent] Diagnostic report
17:20:45  [ssh-agent] * Exec ssh-agent (binary ssh-agent on a remote machine)
17:20:45  [ssh-agent]     hudson.AbortException: Failed to run ssh-agent
```

https://ci.adoptopenjdk.net/view/Test_openjdk/job/Test_openjdk11_j9_sanity.openjdk_s390x_linux/20/console

**Comment by sxa555** [comment]
Which machines is this? We only have one sles12 machine defined in jenkins at the moment - `test-marist-sles12-s390x-1` and it has `ssh-agent` installed so I'm unclear on what the requirement is here:
```
jenkins@build-marist-sles12-s390x-1:~> which ssh-agent
/usr/bin/ssh-agent
jenkins@build-marist-sles12-s390x-1:~> ssh-agent
SSH_AUTH_SOCK=/tmp/ssh-DnMAD4dTNnmf/agent.49760; export SSH_AUTH_SOCK;
SSH_AGENT_PID=49761; export SSH_AGENT_PID;
echo Agent pid 49761;
jenkins@build-marist-sles12-s390x-1:~> 
```

**Comment by sxa555** [comment]
May be related to https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/684 although there was still 60Mb free on `/` (which I'm surprised is used at that point - all other file systems are fine). I've had a clear up on `/tmp` which has freed up a few hundred Mb so we should run a Grindr job to see if that's improved things.

**Comment by adamfarley** [comment]
Works now.
