### ISSUE TITLE
Tests fail from refused connections on s390 machines

### ISSUE THREAD

**Issue by adamfarley** [AdoptOpenJDK/openjdk-infrastructure#880]
**Symptom**

A set of OpenJDK regression tests are failing on these machines with the following error:

```
java.net.ConnectException: Connection refused
```

The test appears to expect a timeout, but doesn't get that far because the connection is refused immediately. This affects OpenJ9 and Hotspot, but only on zLinux, and there have been other timeout/connection refuseds so we have to rule out machine issue.

Please review the below machines for anything that could be causing these problems, e.g. overrunning processes, port-hogging, etc. 

**Machines Affected:**

test-marist-ubuntu1604-s390x-1
test-marist-ubuntu1604-s390x-2-XJ

**Comment by sxa555** [comment]
I've moved all abandoned processes on both machines. the `-2-XJ` machine was keeping a lock on TCP/IP port 34339 which has now been released

**Comment by adamfarley** [comment]
Thanks Stewart. Re-running the tests now.
