### ISSUE TITLE
Windows Playbook Java installation API broken

### ISSUE THREAD

**Issue by HusainYusufali** [AdoptOpenJDK/openjdk-infrastructure#882]
The Windows playbook roles that install the OpenJ9 Java doesn't work because it produces multiple zip files because of the new large heap binary. Adding `heap_size` variable to the URL should fix this. 

```
"OpenJDK8U-jdk_x64_windows_openj9_8u222b10_openj9-0.15.1.zip", "heap_size": "normal"
"OpenJDK8U-jdk_x64_windows_openj9_windowsXL_8u222b10_openj9-0.15.1.zip", "heap_size": "large"
```

The affected roles are `Java8`, `Java11`, and `Java12`.

Not sure what the default should be, but it can be added to `AdoptOpenJDK_Windows_Playbook/group_vars/all/adoptopenjdk_variables.yml`.

**Comment by sxa555** [comment]
We generally use the hotspot ones at AdoptOpenJDK so this isn't an issue, but we don't have any particular need for the large heap ones to my knowledge so I'd pick normal for any PR on this.
