### ISSUE TITLE
Errors in linting of adoptopenjdk_vars.yml

### ISSUE THREAD

**Issue by sxa555** [AdoptOpenJDK/openjdk-infrastructure#886]
Sample error: https://travis-ci.org/AdoptOpenJDK/openjdk-infrastructure/builds/569368722?
```
 [ERROR]: /home/travis/build/AdoptOpenJDK/openjdk-
infrastructure/ansible/plugins/inventory/adoptopenjdk_yaml.py:77:
YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the
default Loader is unsafe. Please read https://msg.pyyaml.org/load for full
details.   hosts = yaml.load(stream)
```
Offending line: https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/8f141d80c7b7d120c4c98143ef6e2770b17ee5ee/ansible/plugins/inventory/adoptopenjdk_yaml.py#L77
Description of problem: https://github.com/yaml/pyyaml/wiki/PyYAML-yaml.load(input)-Deprecation

Assigning to @gdams since he wrote the file and can likely advise on the best `Loader` option to add from the list in the last link

**Comment by gdams** [comment]
@sxa555 that error isn't actually causing the travis failures, It's this one here:

```bash
./playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/MacOSX.yml
  10:10     warning  too few spaces before comment  (comments)
  13:10     warning  too few spaces before comment  (comments)
  24:11     warning  too few spaces before comment  (comments)
  24:59     error    trailing spaces  (trailing-spaces)
  25:11     warning  comment not indented like content  (comments-indentation)
```

**Comment by gdams** [comment]
linter fixed: https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/888
