### ISSUE TITLE
Various new machines do not have the infra team's SSH keys available

### ISSUE THREAD

**Issue by sxa** [AdoptOpenJDK/openjdk-infrastructure#894]
As far as I can tell at least the following need the keys put on:
- The new OSUOSL PPCLE machines https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/868
- New macincloud test systems (e.g. 74.80.249.207)

- I also can't connect to the openlab machines over ssh at the moment - is that expected? https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/680

**Comment by gdams** [comment]
Can you use the Zeus ssh key?

**Comment by sxa555** [comment]
Seems to be on the osuosl machines but not the mac ones, but the root keys - this needs to be a part of the process of putting new machines in place until we get a keybox replacment in place so if you can put the team's ones into `root` and `jenkins` that would be appreciated

**Comment by karianna** [comment]
This reminds me we still need to replace keybox.

**Comment by gdams** [comment]
All machines should have at minimum a zeus key on them now. Closing
