### ISSUE TITLE
Donate build s390x machines to test

### ISSUE THREAD

**Issue by sxa555** [AdoptOpenJDK/openjdk-infrastructure#899]
We[ have](url) these two machines in the build farm:
- [build-marist-ubuntu1604-s390x-2](https://ci.adoptopenjdk.net/computer/build-marist-ubuntu1604-s390x-2/)
- [build-marist-ubuntu1604-s390x-2](https://ci.adoptopenjdk.net/computer/build-marist-ubuntu1604-s390x-3/)

These are also used for building the s390x docker images, but it should be possible to share them with test. I am going to add the `ci.role.test`  tag to them now to increase capacity - I have already run a Grinder on both machines to verify that they have the critical test prereqs.

FYI @smlambert

**Comment by gdams** [comment]
I would also suggest we pull over any remaining JCK ones.

**Comment by sxa555** [comment]
Closing this as I believe they are enabled now
