### ISSUE TITLE
ci.adoptopenjdk.net package upgrade problems

### ISSUE THREAD

**Issue by tellison** [AdoptOpenJDK/openjdk-infrastructure#9]
The Jenkins host `ci.adoptopenjdk.net` had a number of critical OS package updates pending.  Upgrading the packages has introduced problems with Jenkins.

Jenkins is up and running, but a number of nodes are currently flagged as offline.

**Comment by tellison** [comment]
Starting a Jenkins downgrade

**Comment by tellison** [comment]
Jenkins stuck on "Jenkins is going to shut down" message, even though no jobs in flight. 
May need an OS signal to shutdown?

Looking for the launch line to restart Jenkins from the command-line.  Thought there may be a script for this, but looking back through command history it looks like:
```
/usr/bin/daemon --name=jenkins --inherit --env=JENKINS_HOME=/home/jenkins/.jenkins --output=/var/log/jenkins/jenkins.log --pidfile=/var/run/jenkins/jenkins.pid -- /usr/bin/java -Djava.awt.headless=true -jar /usr/share/jenkins/jenkins.war --webroot=/var/cache/jenkins/war --httpPort=8080
```

Figured we should get confirmation of this plan, so not yet tried.

**Comment by karianna** [comment]
I'd prefer if we moved to a seimple service / sysemctl / systemd  / whatever way of firing these up.  a `sudo service jenkins restart` is much simple to remember

**Comment by tellison** [comment]
Ok, plan is to downgrade Jenkins to most recent version that does not require JDK8.  From [the Jenkins changelog](https://jenkins.io/changelog/) this is 2.53, but that version is not available in the master machine's repositories, so the latest compatible I see is `apt-get install jenkins=2.46.3`.

**Comment by tellison** [comment]
Also issued an `apt-mark hold jenkins` ;-)

**Comment by tellison** [comment]
Jenkins successfully restarted.

Some observations:
 - `build-marist-s390x-rhel-6` is offline due to `Cannot find SSH User credentials`
 - `build-osuosl-ppc64-aix-71-2` is getting `OutOfMemory` errors
 - `build-osuosl-ppc64le-fedora-24-2` is `Disconnected by gdams`

Otherwise things look ok.

**Comment by karianna** [comment]
Are we going to plan to move to 8 though?  I'd hate to fall behind in Jenkins versioning as security updates come thick and fast.

**Comment by tellison** [comment]
@karianna yes, there is an open issue #10 to move to JDK8 across all machines, and then we can update Jenkins.

Closing out this particular issue now.
