### ISSUE TITLE
Jlink issues causing mac sanity system tests to fail

### ISSUE THREAD

**Issue by adam-thorpe** [AdoptOpenJDK/openjdk-infrastructure#902]
- Roughly 12 sanity system tests are failing on Mac and Mac XL systems both openj9 and hotspot and all JDK versions.
- Issue is with JLink hashes:
```
JLNK Error: Hash of java.xml (d9e6eec1756f38b883b1c69e27df20aa1c0e64a3dc35a20fb3878bab30f8e8d6) differs to expected hash (5aee92322afdecdb3534889f81e524368d11ad975068cfb88bba941671a90585) recorded in java.base
```
- Not sure if this is an infrastructure problem or not but thought it was most likely
- Link: https://ci.adoptopenjdk.net/view/Test_system/job/Test_openjdk13_j9_sanity.system_x86-64_mac/13/tapResults/

**Comment by sxa555** [comment]
Not sure why this would be an infrastructure issue - is it the same issue covered in https://github.com/AdoptOpenJDK/openjdk-build/issues/1214?

**Comment by adam-thorpe** [comment]
Yes seems to be related, I didn't think to check if there was an issue at build. Anything I need to do to update this?

**Comment by sxa555** [comment]
Nope I'll close now on the basis that it's a duplicate now
