### ISSUE TITLE
Demande to contribute to the AdpotOpenJdk project

### ISSUE THREAD

**Issue by khairaneMurad** [AdoptOpenJDK/openjdk-infrastructure#909]
Hello,

I'm a Java developper working on improving the baking system on a widely known bank and i want to contirubte to this project.

best regards,
Mourad.

**Comment by sxa555** [comment]
We are happy to take pull requests on any aspect of the project. If your interest is in the infrastructure are please go ahead, but for a general overview of the project and the repositories that are available start at the readme in https://github.com/AdoptOpenJDK/TSC to find your way around, and to discuss things, feel free to join us on our Slack channel by getting an invite at https://adoptopenjdk.net/slack.html - hope that helps :-)

Welcome to the project!
