### ISSUE TITLE
jenkins user access to build-osuosl-ppc64le-ubuntu-16.10

### ISSUE THREAD

**Issue by alenbadel** [AdoptOpenJDK/openjdk-infrastructure#91]

**Comment by bblondin** [comment]
Alen is requesting jenkins user access to build-osuosl-ppc64le-ubuntu-16.10

**Comment by bblondin** [comment]
@alenbadel how long will you require access?

**Comment by bblondin** [comment]
Access requested until Wednesday Dec. 13, 2017

**Comment by tellison** [comment]
@alenbadel 
Alen, please give a reason why you are requesting access.

**Comment by alenbadel** [comment]
Hi, all. 

I was able to fix up OpenJ9 issue 769. I don't require access anymore to the PPCLE machines. 

Thank you for the resources.

**Comment by bblondin** [comment]
- Access has been revoked. 
- closing issue

**Comment by alenbadel** [comment]
@bblondin Seems another issue has come up in regards to OpenJ9 Issue 769 blocking PPCLE builds on adoptOpenJDK. 

Could I get access back to the system?

**Comment by gdams** [comment]
@alenbadel I think we are all fixed now
