### ISSUE TITLE
Obtain new bare metal system for permanent playbook testing

### ISSUE THREAD

**Issue by sxa555** [AdoptOpenJDK/openjdk-infrastructure#910]
Ref #842 #865
We need a permanent machine that can run Vagrant. This will likely need a bare metal system. At the moment we are using a laptop at https://ci.adoptopenjdk.net/computer/infra-vagrant-1/ using the job at https://ci.adoptopenjdk.net/view/work%20in%20progress/job/SXA-PlaybookCheck/
May be easiest/quickest in the short term to obtain this via the IBM Cloud, so tagging in Tim - I want to test how well we can make use of multi-cores before finalising this request :-)

@willsparker Can you see if your script can be parallelised? I'm happy with it having the ability to take a parameter of the VagrantFileName to use then I can handle the execution of them in parallel in the jenkins job for now (also makes the reporting a bit easier in the jenkins UI that way)

**Comment by Willsparker** [comment]
#918 - Modifying script for parallelisation

**Comment by sxa555** [comment]
@tellison as mentioned a while back, can we proceeed with getting a bare-metal server provisbioned for this please?

**Comment by tellison** [comment]
@sxa555 please let me know what spec of bare metal machine you require (cores, RAM, SSD size, OS request)

**Comment by sxa555** [comment]
At the moment we're using a laptop with 8 cores which would be ideal but 4 would be ok (it's mostly for parallelism). 16GB of RAM at a minimum (will be for 5 * 2GB VMs running in parallel at the moment, and disk-wise it's unlikely we'd need more than 50GB initially but I'd prefer 100GB to give us a bit of flexibility

**Comment by tellison** [comment]
Which OS do you want installed?

**Comment by tellison** [comment]
Created as 1 x 4 core Intel CPUm 32 Gb RAM, 1TB HDD, Ubuntu 18. named `infra-softlayer-vagarant-1.adoptopenjdk.net`.
Currently being provisioned.  Please close the issue if that works out ok for you.
