### ISSUE TITLE
Failure executing "file" on AIX during build

### ISSUE THREAD

**Issue by sxa555** [AdoptOpenJDK/openjdk-infrastructure#919]
From job 346 on https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-aix-ppc64-hotspot/346 executing on https://ci.adoptopenjdk.net/computer/build-osuosl-ppc64-aix-71-2/ :
```
Creating images/lib/ct.sym
exec(): 0509-036 Cannot load program /opt/freeware/bin/file because of the following errors:
	0509-130 Symbol resolution failed for file because:
	0509-136   Symbol getline (number 37) is not exported from
		   dependent module /opt/freeware/lib/libmagic.a(libmagic.so.1).
	0509-192 Examine .loader section symbols with the
		 'dump -Tv' command.
## Finished images (build time 00:01:17)
```

**Comment by sej-jackson** [comment]
Fixed by upgrading "rpm.rte" to latest version (ie. 4.13.0.10 - was previously 4.9.1.3), so `/opt/freeware/bin/file` is now a symlink to `/usr/opt/rpm/bin/file`, which works.  This had already been done on the other AIX systems.
