### ISSUE TITLE
jenkins user access to build-osuosl-ppc64le-ubuntu-16.10 

### ISSUE THREAD

**Issue by alenbadel** [AdoptOpenJDK/openjdk-infrastructure#92]
I'm requesting access again for this machine. There seems to be a few comparability issues with the adoptOpenJDK machines for OpenJ9. 

I'm currently looking at OpenJ9 Issue # 769 which has been blocking the adoptOpenJDK Linux PPCLE builds.

**Comment by gdams** [comment]
These builds seem to have now been fixed. I will close this and can repopen if the issues return
