### ISSUE TITLE
Enable parallelisation of Vagrant playbook testing

### ISSUE THREAD

**Issue by sxa555** [AdoptOpenJDK/openjdk-infrastructure#923]
Now that https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/918 is in we can work on allowing the vagrant testing to execute on parallel instead of sequential.

We have an "empty" job at https://ci.adoptopenjdk.net/view/work%20in%20progress/job/sxa-PlaybookCheckParallel/ which can use the operations in https://ci.adoptopenjdk.net/view/work%20in%20progress/job/SXA-PlaybookCheck/ as a basis, and also use the `label` setup in https://ci.adoptopenjdk.net/view/work%20in%20progress/job/SXA-DockerfileCheck/ as an example of how to split it up with a parameter that can be passed in. I've modified the machine definition https://ci.adoptopenjdk.net/computer/infra-vagrant-1/ so that it has four executors which will allow it to run four playbooks at once and hopefully significantly reduce the current time of over 4 hours to run the playbooks sequentially.

**Comment by Willsparker** [comment]
https://ci.adoptopenjdk.net/view/work%20in%20progress/job/sxa-PlaybookCheckParallel/
I've set it up. As of current, it doesn't test the builds, just the playbook- but that's just a case of adding `--build` to the commands it executes :-)

**Comment by sxa555** [comment]
Looks good. Hopefully we can get build and a basic test in there too as well +Execution of the `MachineInfo` fake test to show that the test pets are installed. If you talk to Adam/Morgan they can probably show you what to run to run a specific test on your own machine
