### ISSUE TITLE
Add Windows Server 2012 playbook to automated Vagrant testing

### ISSUE THREAD

**Issue by sxa555** [AdoptOpenJDK/openjdk-infrastructure#924]
Now that we have a Windows Server playbook, we should add it into the Vagrant playbook testing scripts to include that platform in the automated testing to be introduced in #923 

Hopefully with these two new issues it'll keep you going until I get back Will ;-)

**Comment by sxa555** [comment]
Failed at https://ci.adoptopenjdk.net/job/sxa-PlaybookCheckParallel/OS=Win2012,label=infra-vagrant-1/4/console

**Comment by Willsparker** [comment]
This was an issue with the `infra-vagrant-1` machine- the `winrm` `winrm-fs` and `winrm-elavated` plugins weren't installed with vagrant.
Ansible then required the installation of `pywinrm` and `requests-credssp`

**Comment by Willsparker** [comment]
Initially I installed it in the User space, so it worked on the laptop, but not using Jenkins as it wasn't accessible to the Jenkins user. To properly setup the machine, I did the following:
`sudo vagrant plugin install winrm winrm-fs winrm-elevated` <-- Installs plugins for vagrant
`sudo apt-get install virtualbox-qt` <-- Required for the GUI
`sudo pip install "pywinrm>=0.2.2"`
`sudo pip install "requests-credssp"` <-- Both required to allow ansible connection to the VM

**Comment by Willsparker** [comment]
Ran into an issue when the inline script in the Vagrantfile won't seem to configure the Windows VM correctly to use WinRM , when the following is put in:
```
config.vm.provider "virtualbox" do |v|
    v.gui = false
end
```
However, this is required, as there is no GUI environment available for Jenkins to use.

**Comment by Willsparker** [comment]
The Windows Playbook is now testable on Jenkins! 👍 

https://ci.adoptopenjdk.net/job/SXA-PlaybookCheckParallel/OS=Win2012,label=infra-vagrant-1/11/
