### ISSUE TITLE
Test machines need to have make v4.1 and above

### ISSUE THREAD

**Issue by llxia** [AdoptOpenJDK/openjdk-infrastructure#925]
We need to upgrade test machines to have make to v4.1. Otherwise, the test will fail during make gen:

```
00:02:32.545  make[3]: Entering directory `/home/jenkins/workspace/Grinder/openjdk-tests/functional/JIT_Test'
00:02:32.545  autoGen.mk:750: *** Malformed target-specific variable definition.  Stop.
00:02:32.545  make[3]: Leaving directory `/home/jenkins/workspace/Grinder/openjdk-tests/functional/JIT_Test'
00:02:32.545  make[2]: *** [compile-JIT_Test] Error 2
00:02:32.545  make[2]: Leaving directory `/home/jenkins/workspace/Grinder/openjdk-tests/functional'
00:02:32.545  make[1]: *** [compile-functional] Error 2
00:02:32.545  make[1]: Leaving directory `/home/jenkins/workspace/Grinder/openjdk-tests'
00:02:32.545  make: *** [compile-..] Error 2
```

https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1962/console
machine: https://ci.adoptopenjdk.net/computer/test-godaddy-centos7-x64-4/

**Comment by sxa555** [comment]
Hmmm they ought to have 4.1 available since the playbooks do attempt to install it on Centos 7 as visible in https://ci.adoptopenjdk.net/job/sxa-PlaybookCheckParallel/OS=CentOS7,label=infra-vagrant-1/3/consoleText ... @willsparker Can you take a look on a machine set up with the Centos7 playbook and run `/usr/bin/make --version` and `/usr/local/bin/make -version`

**Comment by Willsparker** [comment]
`/usr/bin/make --version` output with this:
```
GNU Make 3.82
Built for x86_64-redhat-linux-gnu
Copyright (C) 2010  Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```
`/usr/local/bin/make -version` output with:
```
GNU Make 4.1
Built for x86_64-unknown-linux-gnu
Copyright (C) 1988-2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```
I think it says `Built for x86_64-unknown-linux-gnu` because I didn't run the whole playbook.

**Comment by sxa555** [comment]
Looks like the playbooks haven't been executed on these machines as `/usr/local/bin/make` is not present and the standard make is `3.82` - assigning to George

Related: https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/839 https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/894 and maybe https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/721

**Comment by smlambert** [comment]
I have disabled test-godaddy-centos7-x64-4 and test-godaddy-centos7-x64-1 (with a note that links to this issue) as we keep hitting this issue (it is likely that 2 & 3 are same, just have not had time to check so will leave them enabled until functional tests land on them and we see it).

**Comment by llxia** [comment]
`test-godaddy-centos7-x64-3` also has make issue:
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/901/console

```
14:17:09  make[3]: Entering directory `/home/jenkins/workspace/Grinder@2/openjdk-tests/functional/JIT_Test'
14:17:09  autoGen.mk:750: *** Malformed target-specific variable definition.  Stop.
```

**Comment by smlambert** [comment]
This issue is causing failures that are seen in the release build candidates - we should either fix or I should re-disable these machines.

**Comment by Willsparker** [comment]
I've run the `goodmake_source` tag on `test-godaddy-centos7-x64-*` machines.
```
[root@test-godaddy-centos7-x64-1 ~]# make --version
GNU Make 4.1
Built for x86_64-unknown-linux-gnu
Copyright (C) 1988-2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```
Were there any more than needed it on?

**Comment by Willsparker** [comment]
Okay, been through all linux machines with the `goodmake_source` role, they're all at make 4.1 or above- closing issue
