### ISSUE TITLE
Access to AIX slaves to debug build failures

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-infrastructure#928]
Please can I get temporary ssh access to the following AIX slaves to debug the current build failures:
build-osuosl-ppc64-aix-71-2
test-osuosl-ppc64-aix-71-1

**Comment by sxa555** [comment]
Approved, and added Andrew's ssh keys to those two boxes

**Comment by karianna** [comment]
@sxa555 Can this be closed now?

**Comment by sxa555** [comment]
Yep it can now
