### ISSUE TITLE
Migrate Jenkins Master to a bigger box (HDD)

### ISSUE THREAD

**Issue by karianna** [AdoptOpenJDK/openjdk-infrastructure#933]

**Comment by sxa555** [comment]
Current thinking is to chew up some AWS EC2 credits (I don't have access to them though) and use the Jenkins EC2 plugin to give us some more elastic capacity going forwards.

To consider: Do we really need to keep all GA pipeline artifacts when they are stored in jenkins? Doing so means we have a constantly increasing amount of disk space. If we're moving it to EC2 storage perhaps that doesn't matter, but it's worth considering if it's necessary now (We made the decision to do so sometime last year as I recall but I don't quite remember the justification for wanting to do it for full history)

**Comment by karianna** [comment]
Done!
