### ISSUE TITLE
Add basic test verification to the playbook testing

### ISSUE THREAD

**Issue by sxa555** [AdoptOpenJDK/openjdk-infrastructure#939]
Follow on to #938 - once we've verified that the build prereqs are installed correctly by ansible we should verify that we have things needed to run the test harnesses - the `MachineInfo` target mentioned by @smlambert in https://adoptopenjdk.slack.com/archives/C53GHCXL4/p1564580457030100 would seem a reasonable choice and should verify the various perl and ant prereqs that we have.

**Comment by Willsparker** [comment]
@smlambert I've tried running that test on an Ubuntu1604 VM, however it was unable to find `MachineInfo` as a test target. This was after declaring the following environment variables:
```
BUILD_LIST=systemtest,openjdk
JDK_CUSTOM_TARGET=MachineInfo
```
This was after following the instructions here:
https://github.com/eclipse/openj9/wiki/Reproducing-Test-Failures-Locally

**Comment by smlambert** [comment]
BUILD_LIST=system,openjdk
TARGET=MachineInfo

**Comment by smlambert** [comment]
In fact, for the purpose of this test, you do not need openjdk dir in your build list.  The build list tells us which test directory you want to compile, and which test targets (defined in playlists) that you want to generate. MachineInfo is a test target defined in playlists in system directory, so you'd only need to indicate that dir to enable that test.

If you do not need to run any openjdk tests, you do not need to build that directory.
