### ISSUE TITLE
Need FreeBSD machine setup for testing *BSD builds

### ISSUE THREAD

**Issue by smlambert** [AdoptOpenJDK/openjdk-infrastructure#945]
As per https://github.com/AdoptOpenJDK/openjdk-tests/pull/1325#issuecomment-536663664 we need a FreeBSD machine set up for testing.  Creating this issue, as I do not think its been formally captured as a requirement yet.

**Comment by gdams** [comment]
dupliacate of https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/944
