### ISSUE TITLE
jckservices.adoptopenjdk.net required

### ISSUE THREAD

**Issue by gdams** [AdoptOpenJDK/openjdk-infrastructure#95]
- [ ] Spin up a softlayer Ubuntu 16.04 host (lowest spec should be fine) @tellison 
- [ ] Point DNS to machine (once @tellison has got an IP address)

**Comment by tellison** [comment]
Created `jck-softlayer-x64-ubuntu-16.04-3` as 
1 vCPU / 1Gb RAM / 25Gb SAN / 100 Mbps / Ubuntu16.04-64 Minimal for VSI

DNS updated
`jckservices` points to `158.176.72.83`

Login details sent privately.
