### ISSUE TITLE
Request for Access to test-scaleway-x64-ubuntu-16.04-1

### ISSUE THREAD

**Issue by smlambert** [AdoptOpenJDK/openjdk-infrastructure#99]
The test-scaleway-x64-ubuntu-16.04-1 machine is full and needs cleaned up.  Either someone with access needs to clean it, or I can if I have temp access.

Since we started running system tests, it seems this machine is full, we should follow-up and make sure we are cleaning the workspace properly after the system test runs.

**Comment by gdams** [comment]
closing as access should already be in place for the jenkins user

**Comment by bblondin** [comment]
Cleaned up  16G  free
