### ISSUE TITLE
Issue to log timeouts occurring when using adoptopenjdk playbooks

### ISSUE THREAD

**Issue by sxa555** [AdoptOpenJDK/openjdk-infrastructure#994]
As part of the playbook testing we're doing under vagrant we're seeing various intermittent timeouts with external services e.g. cmake, sourceforget (for ant-contrib) and at least in once case today our own adoptopenjdk api. Due to the vagrant testing we're running the playbooks more frequently so it's more likely to show up intermittent issues This issue will log when these are occurring.

We can log them in comments saying somethign like this to include date and time to see if that has any bearing on the outcome:

```
Ubuntu1604    | ant-contrib     | 14/11 | 0805
```

**Comment by Willsparker** [comment]
CentOS6:
  -  Ant Contrib: 
  ```
  TASK [Ant-Contrib : Download ant-contrib] **************************************
fatal: [localhost]: FAILED! => {"changed": false, "dest": "/tmp/", "gid": 0, "group": "root", "mode": "01777", "msg": "Request failed: <urlopen error _ssl.c:477: The handshake operation timed out>", "owner": "root", "secontext": "system_u:object_r:tmp_t:s0", "size": 4096, "state": "directory", "uid": 0, "url": "https://sourceforge.net/projects/ant-contrib/files/ant-contrib/ant-contrib-1.0b2/ant-contrib-1.0b2-bin.tar.gz"}
	to retry, use: --limit @/vagrant/playbooks/AdoptOpenJDK_Unix_Playbook/main.retry
  ```

**Comment by Willsparker** [comment]
To Do: 
- [ ] Add Retries to the following:
  - [ ] Ant-Contrib
  - [ ] Git-Source
  - [ ] adoptopenjdk_install

**Comment by sxa555** [comment]
I think we have mitigations in for all known issues now, so resolving this one...
