### ISSUE TITLE
Replace keybox server

### ISSUE THREAD

**Issue by sxa** [AdoptOpenJDK/openjdk-infrastructure#997]
Our keybox server has been rather dead for a while and we need to get it replaced. Just spotted we don't have an issue covering this so here's one we can use.
Ref: https://github.com/AdoptOpenJDK/security/issues/30 (restricted) https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/894#issuecomment-521006518

Blog on original setup: https://blog.adoptopenjdk.net/2017/08/ssh-key-management-keybox

**Comment by sxa** [comment]
New server set up on GoDaddy at `160.153.244.137` - I've cleaned up the access lists so that many people (particularly alumni) no longer have access, but all the active members of the admin team have access across all systems.

I'll do the deployment in waves. Here are the action points:
- [x] Set up a machine to run it
- [x] Ensure the setup is repeatable
- [x] Ensure that bulk adds of new machines is feasible and documented
- [x] Add primary users to the server
- [ ] Ensure backups of the server are in place

Waves to do:
- [ ] admin user on test systems
- [ ] admin user on build systems
- [ ] jenkins user on test systems
- [ ] jenkins user on test systems
- [ ] admin/jenkins user on "restricted" build/test systems
- [ ] Other systems (infra?)

**Comment by sxa** [comment]
The following script can be used to generate sql for the underlying database for the machines. Run it with parameters of hostname, IP address and the name of the profile group to add the machine to:

```
#!/bin/bash
[ $# -lt 3 ] && echo $0 display_name ip profile && exit 1
case $3 in
      jenkins-only) PROFILE_ID=1;;
    jenkins-secret) PROFILE_ID=2;;
              root) PROFILE_ID=3;;
       root-secret) PROFILE_ID=4;;
       root-marist) PROFILE_ID=5;;
       root-ibmaix) PROFILE_ID=6;;
                 *) echo Invalid profile name - should be one of: jenkins-only jenkins-secrert root root-secret root-secret admin-ibmaix && exit 2;;
esac

echo "insert into system values (default, '$1', 'root', '$2', 22, '~/.ssh/authorized_keys', default);"
echo "insert into system_map values ($PROFILE_ID, select id from system where display_nm='$1');"
```

**Comment by sxa** [comment]
Most build systems now in. Exceptions are admin accounts on:
- build-marist-rhel77-s390x-* (Cannot allow direct logins)
- scaleway systems (They likely have auto-refreshing key files)

**Comment by Haroon-Khel** [comment]
@sxa  What is left to do on this issue?

**Comment by sxa** [comment]
Only the backups really for which I'm still awaiting input from @gdams and @karianna but I can close this off and cover those outside this issue since the server is operational.
